### ISSUE TITLE
Feature request: bind softether to specific IP / device

### ISSUE THREAD

**Issue by cnf** [SoftEtherVPN/SoftEtherVPN#100]
It would be really nice if we could bind the listeners to a specific device or ip.

Right now, it takes over my entire server.

Really need the ability to bind the listeners to one specific IP or device.

**Comment by LordMike** [comment]
I would love this too. Trying to host the VPN service on a server which doubles as a webserver (HTTP(S))., meaning I can't make use of the great port 443 support.

**Comment by jok40** [comment]
I also ask to add the ability to bind the listeners to specific IP-address.

**Comment by soakes** [comment]
Likewise.

Any update on this as the latest post was a year ago.

**Comment by moatazelmasry2** [comment]
Please add a thumb up to the issue description, so it is clear how many users want this feature

**Comment by davidebeatrici** [comment]
#202 added the parameter `ListenIP` to the server configuration, however it's a single setting for all the listeners.
