### ISSUE TITLE
SECURITY ALERT: Please remove Dual_EC_DRBG in SSL-VPN, if OpenSSL still support it

### ISSUE THREAD

**Issue by 0x391F** [SoftEtherVPN/SoftEtherVPN#1000]
https://cs.stanford.edu/people/eroberts/cs181/projects/ethics-of-surveillance/tech_encryptionbackdoors.html

This is one reason why I hope SoftEtherVPN use LibreSSL. Please remove the DUAL_EC_DRBG in OpenSSL which SoftEtherVPN using if OpenSSL still support it.

**Comment by davidebeatrici** [comment]
From https://en.wikipedia.org/wiki/Dual_EC_DRBG:
> OpenSSL implemented all of NIST SP 800-90A including Dual_EC_DRBG at the request of a client. The OpenSSL developers were aware of the potential backdoor because of Shumow and Ferguson's presentation, and wanted to use the method included in the standard to choose a guarantied non-backdoored _P_ and _Q_, but was told that to get FIPS 140-2 validation they would have to use the default _P_ and _Q_. OpenSSL chose to implement Dual_EC_DRBG despite its dubious reputation for completeness, noting that OpenSSL tried to be complete and implements many other insecure algorithms. OpenSSL did not use Dual_EC_DRBG as the default CSPRNG, and it was discovered in 2013 that a bug made the OpenSSL implementation of Dual_EC_DRBG non-functioning, meaning that no one could have been using it.

Source: https://marc.info/?l=openssl-announce&m=138747119822324

**Comment by 0x391F** [comment]
Oh, I see. Thank you very much!
