### ISSUE TITLE
Ping DUP on Ubuntu 19.10

### ISSUE THREAD

**Issue by scegg** [SoftEtherVPN/SoftEtherVPN#1004]
Run with the code pull today on Ubuntu 19.10.
When server started, any computer ping to this server, no matter it is connected to the service or not, will get a DUP result replied. TTL is different.
When server stopped, the DUP packages are gone.

Server has no bind interface.

**Comment by davidebeatrici** [comment]
#332

**Comment by scegg** [comment]
> #332

Thanks. I close this issue and wait for the closing of that.
