### ISSUE TITLE
Cannot disable default webpage

### ISSUE THREAD

**Issue by ciscozine** [SoftEtherVPN/SoftEtherVPN#1021]
Hi, I have installed the last version of softether (v4.30-9696-beta-2019.07.08-linux-x64-64bit) and I have to disable the https webpage.

I used this procedure

----
If you want to disable this embedded web server and JSON-RPC server:
    Stop the daemon.
    Modify the value of "bool DisableJsonRpcWebApi" from "false" to "true" on the vpn_server.config or vpn_bridge.config.
    Restart the daemon.
---

But the webpage still remains. Why?

Thanks
Fabio

**Comment by metalefty** [comment]
Because the feature is not implemented in your version.

> SoftEther VPN 4.31 Build 9727 Beta (November 18, 2019)
> * Added the function to hide "index.html" by setting "bool DisableJsonRpcWebApi true" on the configuration file.

https://www.softether.org/5-download/history

**Comment by metalefty** [comment]
CC: @chipitsine 
I confirmed "bool DisableJsonRpcWebApi" is working as expected for me.
Tested with 4.31.9727 and 5.01.9671.

**Comment by davidebeatrici** [comment]
Excellent!

**Comment by vgdh** [comment]
doesn't work on SoftEther VPN Server (Ver 4.43, Build 9799, beta)

**Comment by jmsola1** [comment]
First **Stop the daemon**, then modify the config and restart the daemon. And welcome web is disabled.
