### ISSUE TITLE
DO NOT use self-signed certificate & reduce expiry date

### ISSUE THREAD

**Issue by 0x391F** [SoftEtherVPN/SoftEtherVPN#1027]
1. Uses self-signed certificate is extremely insecure which is easy to suffer MITM. So if possible, NEVER use self-signed certificate.
2. The expiry date of certificate in default (3650 days) compare with Let's Encrypt (90 days) is too long! So if possible, reduce the expiry date, 90 days to 1 year is OK. The maximum better less than 1 year.  Concider use Let's Encrypt's certificate. It is free.

**Comment by chipitsine** [comment]
great. please send PR on that

**Comment by 0F4mpzDafcLwFugk** [comment]
**The proper method is creating a self-signed ROOT CA, then signing a server cert with this ROOT CA.**

[XCA](https://github.com/chris2511/xca) is a good cert manager tool.

**Comment by metalefty** [comment]
I don't think auto-generated self-signed certificate is not a problem. Users can always replace auto-generated certificates with their own certificates. It up to users.

**Comment by 0x391F** [comment]
Oh, no. Maybe most of users doesn't know the risk of using self-signed certificate (sufter MITM) if they don't learn about computer. Maybe they only think it's easy to generate it. Unfortunately, in some countries, government could MITM, I'm not kidding. What's worse, when suffering MITM, users couldn't discover when using self-signed certificate, they still think the connection is "secure". 
So, here are two way:
1. NEVER use self-signed certificate (the better choice). 
2. Allow user use self-signed certificate, but show a security alert (the worse) and suggest him/her to register a trustable certificate. 
Security is most important. Safety first! It's not difficult to make a Let's Encrypt's certificate. It's free.

**Comment by chipitsine** [comment]
well, any user including you can choose proper certificate when installing SE VPN. please define the scope of this issue.

**Comment by 0x391F** [comment]
Show a message such as:
Pay attention please/Warning: SE-VPN will use a self-signed certificate by default (which is easy to suffer MITM). 
Do you want to continue? 
You could also choose a trustable certificate. 

Is this OK?

**Comment by chipitsine** [comment]
sounds reasonable. please send pull request

**Comment by h1z1** [comment]
Nothing wrong with self-signed certificate so long as you can verify it some other way -  CA's do this.   Ironically (or more paradoxically), CA's are less secure for in part the reasons given as to why self-certs are.  You have to trust them, and for longer.  More often then not I _want_ to know if a certificate changes.

x509 also leaks a metric shit ton of metadata.

**Comment by metalefty** [comment]
@h1z1 I completely agree with you.

**Comment by 0x391F** [comment]
@h1z1 Yeah, maybe someone think CA doesn't trustable, but without CA, user need to check the public key/certificate of server like using SSH or at the risk of suffer MITM because every attacks could replace it easily. When user connect to a new server such as VPN Gate public VPN relay servers, they really don't want to check the public key/certificate of server, that's too troublesome. Use a trustable certificate - maybe someone doesn't trust the CA, but a certificate verified by CA could reduce the risk of suffer MITM.

**Comment by h1z1** [comment]
> user need to check the public key/certificate of server like using SSH or at the risk of suffer MITM because every attacks could replace it easily.

To understand why that is moot, one need only look at the number of  root CA certificates no plaguing the world.  Installed by default too.

I would say 99.99% of them are never used by users yet we are forced, by default, to accept and trust them?  Globally?  Most have names bearing nothing related to their source nor purpose.  Couple more interesting ones:

```
China Financial Certification Authority
Expires: December 30, 2029

Chunghwa Telecom Co., Ltd.
Expires: December 19, 2034

TWCA Root Certification Authority
Expires: December 31, 2030

Government Root Certification Authority
Expires: December 5, 2032

GUANG DONG CERTIFICATE AUTHORITY CO.,LTD.
Expires: December 31, 2040

Hongkong Post Root CA 1
Expires: May 15, 2023

Japan Certification Services, Inc.
Expires: April 8, 2029

XRamp Security Services Inc
Expires: January 1, 2035
```

The core issue is this push to remove any kind of user feedback when things DO go wrong.  Example is browsers no longer warn when certificates change.  Both Chrome and Firefox literally have hardcoded "logic" to deal with certs that were compromised.

The rather delicious irony is despite all the metadata in certificates, not one of them limits their scope to a particular domain.  Despite all the SSL/PKI implementations, not one of them allows conditional acceptance (say per session or timed).   You must accept their trust entirely, and that is asinine.

Simply being signed by a "trusted" CA should never have included _future_ attestation.  The only real strength in public CA's was their death in the event a certificate was compromised.  Yet even western companies are unwilling to do that.

**Comment by claw6148** [comment]
actually, SE supports "Server Certificate Verification". u can specify the server cert from "VPN Connection Settings" on client or cascade. it will verify the cert when connecting and failed if the server cert does not match client-side settings. self-signed cert is ok in this situtation.

**Comment by chipitsine** [comment]
well, it is really a user decision. indeed, user can install either self-signed or CA signed cert.
thank you, @claw6148
