### ISSUE TITLE
not working when docker installed

### ISSUE THREAD

**Issue by pouyamiralayi** [SoftEtherVPN/SoftEtherVPN#1029]
Hi there!

### Steps to reproduce:
[1 ] install docker for windows
### Versions:
**SoftEther version: 5.01.9671**
**Component:** Client
**Operating system:** Windows 10
**Architecture:** 64 bit

### Description

installing docker for windows will stop softEther from working.

**Expected behavior:**
docker for windows would not have any effect on the system vpn client.

**Actual behavior:**
by installing docker for windows, when i try to connect to one of my vpn servers through softEther, it will immediately show me a window about network connection.

**Comment by chipitsine** [comment]
what network prefix do you use in docker ?

**Comment by pouyamiralayi** [comment]
@chipitsine what do you mean? i just installed it. have no experience on it.

**Comment by pouyamiralayi** [comment]
this is related to docker, not softEther as in this [post](https://forums.docker.com/t/when-is-vpn-compatibility-mode-going-to-be-enabled-docker-for-windows/10773/4)people are experiencing the same. feel free to close this. 
the odd thing happening is that i just removed everything related to docker (interfaces, registry and drivers) and gave my os a full network reset (windows 10 network reset) but still softEther does not work.
is there any battle scenario for reverting back everything to default for this working again?
