### ISSUE TITLE
Feature request: VPN over recursive DNS lookup

### ISSUE THREAD

**Issue by liangent** [SoftEtherVPN/SoftEtherVPN#103]
It appears the current VPN over DNS implementation is just VPN over UDP port 53 with some DNS header. However in some extremely restrictive networks, DNS queries to non-whitelisted name servers are blocked.

There can be some way to make use of the only whitelisted name servers: if I set up a NS record on my domain `dns-vpn.liangent.com` to my VPN server and query the whitelisted name server for `[vpn-payload].dns-vpn.liangent.com`, `[vpn-payload]` will be sent to my VPN server, and my VPN server will be able to send some data back.

There'll be no way to send data directly from my VPN server to the client, but I guess there are always some outgoing packets from time to time, and polling can be the last solution.

**Comment by jdstroy** [comment]
The strategy outlined above has been implemented in other tools before (see [tcp-over-dns](http://analogbit.com/software/tcp-over-dns/) and [iodine](http://code.kryo.se/iodine/)).  One could probably cobble something together combine the projects with SoftEther for actual VPN over DNS.

**Comment by domosekai** [comment]
This looks like abusive activity to the DNS system. Only direct connection is legitimate.
