### ISSUE TITLE
softether in openwrt interface！need help?

### ISSUE THREAD

**Issue by chinamore** [SoftEtherVPN/SoftEtherVPN#1036]
I tried softether on the openwrt system, but it was complicated to set up sotether. I spent more than 10 hours on each setup. I hope to compile the latest version on the router. Who can write a tutorial on how to compile openwrt's softether interface?

**Comment by Andy2244** [comment]
The package is called 'softethervpn5' and is in openwrt snapshots or the 19.07-rc1/master branches. You can also try use my [package-builder](https://github.com/Andy2244/openwrt-package-builder) to try compile it for 18.06, since i wont backport it there.

I followed this [setup](https://wordpress.tirlins.com/2015/03/setting-up-softether-vpn-on-openwrt/) from there back than and since the config is preserved between openwrt upgrades i never had to touch it again.

**Comment by chinamore** [comment]
I have a problem in most of openwrt. The tap fails to run and cannot be deleted. May I ask if the operating environment is missing in openwrt?

**Comment by Andy2244** [comment]
You need to be more specific, what does not work and what did you try, Did your follow the setup i linked and at what step you got a problem?

**Comment by chinamore** [comment]
I don't want to compile it myself. I just want to use the bridge in openwrt. The router model is: newifi3 d2. Can I help compile a bridge running on openwrt? I don't need other functions, I just want to run softether bride in newifi3 d2

**Comment by chinamore** [comment]
It took me 12 hours to try all the firmware compiled for the newifi 3 d2 router. When the softether bridge was installed, the tap could not be turned on, and I haven't got it yet.

**Comment by chipitsine** [comment]
@Andy2244, fyi @metalefty did some packaging improvements

https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1047

it allows to perform packaging in more intelligent way

**Comment by Andy2244** [comment]
@chipitsine ah nice, will use it for your next release

**Comment by chinamore** [comment]
I solved this problem in the latest version of openwrt19.07.0-rc1. It took 7 days. Of course, I also read your article. The core problem is that the kernel is too low to support. Another problem is that the official access of Openwrt is really Too slow, I am going to make an openwrt image for access to China right away. It takes too much time to solve this problem, mainly because of the dependency of softether on the environment of openwrt. It is difficult to solve, mainly because China-openwrt is too slow, as slow as snails, but at present, there are more openwrt users in China than in the world. I think openwrt needs to do something in Asia Efforts, otherwise execute a command: opkg update takes half an hour, and then all kinds of errors, compile time, it is very inconvenient. In addition, you said that your focus is on wireguard, which has been successfully identified and blocked in China at present Just because of the Chinese video tutorial on youtube! If a software has no way to solve its own feature code, and it is not safe for itself, how to ensure the safety of users, this is why I have been using softether

**Comment by chinamore** [comment]
Back to the question itself: The basic environment of softether installation is not supported in the default environment of openwrt: opkg install zlib libpthread librt libreadline libncurses libiconv-full kmod-tun libopenssl. Such a command cannot assemble the softether installation environment at all. My suggestion is this: Environment detection in softether5 and bundle installation environment command:
cd / tmp / && wget XXXX / zlib.IPK
Installation kit
opkg install zlib.IPK
Then softvpn5 can be successfully installed and used normally
As for the following command:
opkg update
opkg install zlib libpthread librt libreadline libncurses libiconv-full kmod-tun libopenssl
I just smiled and did n’t talk, anyway, in China, do n’t expect success, I ’m not sure about other countries
No matter whether it is SOFTETHER version 4.29 or softether version 5.0 or above, no one cares about solving this problem, so the official openwrt version takes into account the perfect network speed, perfect various support, the imagination is beautiful, the reality is cruel

**Comment by chinamore** [comment]
The package is called 'softethervpn5' and is in openwrt the 19.07-rc1 ,
I tested this version. When the router restarts, the server information will not be saved, it will be restored to the default state which is 192.168.1.1, and other information is empty.

**Comment by chinamore** [comment]
I checked the startup document /init.d/ and tried to modify but failed. When OPENWRT restarted, vpnserver.config was not called properly

**Comment by Andy2244** [comment]
> opkg install zlib libpthread librt libreadline libncurses libiconv-full kmod-tun libopenssl

On 19.07/snapshots all you should need is:
`opkg install softethervpn5-server` or `opkg install softethervpn5-bridge`

> When the router restarts, the server information will not be saved, it will be restored to the default state which is 192.168.1.1, and other information is empty.

Ok, i could reproduce this bug, seems atm the server_config is only written correctly if you manually stop the service via `luci/system/startup` or shell `/etc/init.d/softethervpnserver stop`.
Then you can check the save in the system-log, aka:
 `daemon.notice softethervpn-server[5491]: Writing vpn_server.config (AutoSaveConfigSpan set to < 259201 > seconds)`

> I checked the startup document /init.d/ and tried to modify but failed.

The init scripts should work fine, just make sure to stop the service once after you have made changes via the external server manager tool, so the changes get written to `/usr/libexec/softethervpn/vpn_server.config`.

PS: softethervpn has a very nvram unfriendly way of using its config and dynamic data, see my issue #575. I will try find a workaround for the next update, so sorry for the inconvenience.

**Comment by chinamore** [comment]
Thank you for your efforts and look forward to your completion of the work of saving server information in subsequent updates! I have solved this problem perfectly! Since the solution I used was violent, it was simple and effective!

**Comment by victorzzt** [comment]
Here because the same problem, settings lost after openwrt reboot.
My current workaround. though extremely troublesome, sees to work on docker.

- Use the configuration tool to set the settings
- Edit config -> Export
- Copy the file `vpn_server.config` manually to `/usr/libexec/softethervpn`
- Restart

**Comment by Sheathan** [comment]
> Here because the same problem, settings lost after openwrt reboot.
> My current workaround. though extremely troublesome, sees to work on docker.
> 
> * Use the configuration tool to set the settings
> * Edit config -> Export
> * Copy the file `vpn_server.config` manually to `/usr/libexec/softethervpn`
> * Restart

As @Andy2244 has mentioned above, if you stop the service, it will write to the config file and be preserved after a reboot. It's a lot easier than running docker on OpenWRT. Configure Softether, stop the service, then reboot.

**Comment by Andy2244** [comment]
Yeah sorry #575 is still open and i really don't want to allow letting Softether eat away the nvram write cycles quickly. Its a trade-off on openwrt, since its geared toward embedded devices mainly.
