### ISSUE TITLE
Freebsd 12, segmentation fault on vpncmd and vpnserver binaries

### ISSUE THREAD

**Issue by tbogdan** [SoftEtherVPN/SoftEtherVPN#1045]
Install VPN server on FreeBSD 12, using ./.install.sh
Segmentation fault on the check and also when you try to run manually vpncmd or vpnserver.
On 11 or lower it works with the same installation steps.

**Comment by chipitsine** [comment]
what do you mean by "install.sh" ? where did you download it ?

**Comment by tbogdan** [comment]
I'm using Version 4.31 Build 9727 compiled 2019/11/18, downloaded from https://www.softether.org yesterday.
In the tar.gz is a file called ".install.sh" (with a . in front). I always use it when I install softether to a server.

**Comment by chipitsine** [comment]
well, 4.31 is "Stable edition". you opened an issue in "DEveloper edition" which is 5.X

we do some FreeBSD-12 testing in 5.X brahcn

https://cirrus-ci.com/task/5142479929606144

however, those tests are currently "build only". can you test 5.X and tell whether it works or not ? Maybe we should add some tests actually

**Comment by chipitsine** [comment]
@tbogdan , I reproduced

```
Preparing SoftEther VPN Server...
ranlib lib/libcharset.a
ranlib lib/libcrypto.a
ranlib lib/libedit.a
ranlib lib/libiconv.a
ranlib lib/libncurses.a
ranlib lib/libssl.a
ranlib lib/libz.a
ranlib code/vpnserver.a
gcc code/vpnserver.a -fPIE -O2 -fsigned-char -pthread -m64 -lm -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a -o vpnserver
ranlib code/vpncmd.a
gcc code/vpncmd.a -fPIE -O2 -fsigned-char -pthread -m64 -lm -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a -o vpncmd
./vpncmd /tool /cmd:Check
vpncmd command - SoftEther VPN Command Line Management Utility
*** Signal 11

Stop.
make: stopped in /usr/home/ilia/v4.31-9727/vpnserver
# 

```

**Comment by chipitsine** [comment]
it is indeed SE VPN Stable edition.

can you try 5.1 version ?

**Comment by tbogdan** [comment]
I checked and 5.x version from FreeBSD ports and from this git is working! 
Thank you!
