### ISSUE TITLE
Freebsd 11, bridge with tap and ethernet doesn't work.

### ISSUE THREAD

**Issue by tbogdan** [SoftEtherVPN/SoftEtherVPN#1046]
1. Install the VPN server on FreeBSD 11.
2. Assign IP from the same lan on an ethernet adapter or tap interface.
3. Bridge on an ethernet adapter or tap interface.
4. Try to ping from host a VPN IP or ping the ethernet/tap from VPN IP. - doesn't work. (works on Linux but not on FreeBSD).

Tested on AWS ec2 instance t3.small.
The secureNat works well, however, I hoped to be able to move the nat on the host for improving the performances.

**Comment by chipitsine** [comment]
what is your SE VPN version ?

**Comment by tbogdan** [comment]
Version 4.31 Build 9727 compiled 2019/11/18, downloaded from https://www.softether.org yesterday.

**Comment by davidebeatrici** [comment]
TAP support for FreeBSD has not been implemented in the stable version yet, you have to build SoftEther VPN from this repository.

**Comment by tbogdan** [comment]
The bridging with an ethernet also doesn't work. Thank you for your recommendation, to build it from the repo. I will do that!

**Comment by chipitsine** [comment]
btw, there's no need to build yourself

https://www.freebsd.org/cgi/ports.cgi?query=softether&stype=all

something like `pkg install softether5` should do the trick (or installing using ports collection), are you familiar with freebsd ports collection ?

**Comment by metalefty** [comment]
Hi, FYI, I am the maintainer of SoftEther ports of FreeBSD.  I might be able to help you.

**Comment by metalefty** [comment]
Bridgeing is working for me on FreeBSD.

**Comment by davidebeatrici** [comment]
@metalefty Thank you very much for your work!

**Comment by chipitsine** [comment]
@tbogdan , can you describe steps you taken to download file ? I downloaded a file, but there;s no "install.sh", seems we downloaded different files

**Comment by tbogdan** [comment]
@chipitsine I've downloaded the file from https://www.softether-download.com/en.aspx?product=softether (after you select SoftEther VPN server, Freebsd, x64) you get some download URLs, the last version is: https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.31-9727-beta/softether-vpnserver-v4.31-9727-beta-2019.11.18-freebsd-x64-64bit.tar.gz
Here you will find a ".install.sh" file (install.sh with . (dot) prefix)

@metalefty I will try the ports version also, I dose not know that SoftEther has a port version. Thank you!

I also tried the latest version from git and bridging with tap is working :)

**Comment by freultwah** [comment]
@metalefty Care to share how you got it to work? I have made multiple attempts, but nothing moves between tap0 and re0 and I had to resort to using a passive USB Ethernet adapter instead of tap0. I don't think there's any written documentation about it.
