### ISSUE TITLE
SoftEther is very slow

### ISSUE THREAD

**Issue by omidshojaee** [SoftEtherVPN/SoftEtherVPN#1052]
Hello,

I have installed SoftEther on DigitalOcean droplet by following [this guide](https://miff2000.github.io/blog/2017/05/18/softether-multi-protocol-vpn-server.html)

Droplet: Ubuntu 18.04.3. 2GB RAM. 
SoftEther: 4.31-9727-beta-2019.11.18.x64
Clients: Windows 10 x64 and Android 9

If not connected to VPN, my throughput is around 14 Mbps. When connected to VPN it is around 1 Mbps.

I have tried both SSTP and SoftEther client.

DigitalOcean graphs shows that the CPU utilization has never reached above %7.5 and Bandwidth utilization is 500 kbps max. RAM usage by vpnserver is less than %3.

My PC and phone are connected to ADSL mode. I am not behind any firewall or NAT.

I have a paid VPN account too and the provider is using SoftEther as server. When I connect to that, there is no significant impact on throughput.

Please help.

**Comment by chipitsine** [comment]
Hello, you have opened an issue in se VPN developer edition, while you are using stable edition

Can you reproduce your issue on developer edition?

**Comment by Omid-Shojaee** [comment]
Hello

Thanks. My server is beta edition. You say stable edition is going to be different?

**Comment by chipitsine** [comment]
4.x is stable edition, 5.x is developer edition

This issue tracker is for 5.x

**Comment by chinamore** [comment]
wget --no-check-certificate -O tcp.sh https://github.com/cx9208/Linux-NetSpeed/raw/master/tcp.sh && chmod +x tcp.sh && ./tcp.sh

**Comment by chinamore** [comment]
one way:up
two way:use Local_Bridges +dnsmasq

**Comment by chinamore** [comment]
I have carefully analyzed your question and found a special solution. I believe you can also find

**Comment by skyjohn5510** [comment]
maybe it is mtu setting problem, I also encounter similar problem before, not sure if the root of cause is the same as yours

**Comment by macvk** [comment]
did you try to use L2TP connection? L2TP is the fastest VPN connection under Windows.

**Comment by Lott-Noob** [comment]
> maybe it is mtu setting problem, I also encounter similar problem before, not sure if the root of cause is the same as yours

How did you solve it?

**Comment by domosekai** [comment]
Close due to inactivity
