### ISSUE TITLE
TLS 1.0 is disabled by default, unable to turn it on with Tls_Disable1_0 in vpn_server.config

### ISSUE THREAD

**Issue by Firm** [SoftEtherVPN/SoftEtherVPN#1053]
### Prerequisites

* [ yes ] Can you reproduce?
* [ yes ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** 5.01 Build 9672
**Component:** Server
**Operating system:** Linux
**Architecture:** 64 bit

### Description

It's found that support of TLS 1.0 is disabled in Developer Edition of SoftEther VPN. This causes some Windows clients to fail when connecting via SSTP protocol. Same clients work fine with stable version.

I found

`c->SslAcceptSettings.Tls_Disable1_0 = CfgGetBool(f, "Tls_Disable1_0");`

in src/Cedar/Server.c and expected to enable support of TLS 1.0 by adding

`bool Tls_Disable1_0 false`

but server silently ignores this option and even doesn't write it back to config.

**Expected behavior:**
`bool Tls_Disable1_0 false` should work as expected

**Actual behavior:**
Server silently ignores this option.

### Steps to reproduce

1. Try to connect from Windows client to SSTP using TLS 1.0 only (with disabled TLS 1.2 in registry) - failed
2. Try to connect from Windows client to SSTP using TLS 1.2 - worked.
3. Try to add config option mentioned above to vpn_server.confg - server silently ignores it.

**Comment by domosekai** [comment]
For solution see #1358
