### ISSUE TITLE
Disable WebUI Management

### ISSUE THREAD

**Issue by TheRealSonicFan** [SoftEtherVPN/SoftEtherVPN#1055]
Hello,

   Though the WebUI feature on the latest version of SoftEther is marvelous, such feature prevents me from setting up a web server as SoftEther allocates port 443 for management. Could anyone please tell me how I can disable the WebUI? I cannot find a way to disable it on the latest version of the SoftEther VPN Server Manager.

Hope to get your reply soon.

Thanks! Much appreciated!

Regards,

Andy

**Comment by metalefty** [comment]
#1021

**Comment by chinamore** [comment]
Install without webui version

**Comment by chinamore** [comment]
In fact, the author has always wanted everyone to use webui to commercially manage the softether server. This idea is very good, but many people who do n’t want to change feel that it is unnecessary or troublesome, so please use an older version to install and still get Very good effect
