### ISSUE TITLE
Expand bandwidth limit more than 2^32-1 bps?

### ISSUE THREAD

**Issue by metalefty** [SoftEtherVPN/SoftEtherVPN#1056]
Hi, 

as far as I understand, upload/download bandwidth limit is restricted to 2^32 -1 bps. This is about 4Gbps. In 100M/1G era, 4Gbps limit was high enough because physical bandwidth limit was 100Mbps/1Gbps. Now 10G era is coming. The 4Gbps limit is a little bit low.

Of course SoftEther's throughput might not be fast enough to configure bandwidth limit more than 4Gbps. However, software limit should not be lower than hardware limit.

What about starting thinking about expanding these 32bit uint limit?

I know SoftEther both supports 32bit & 64bit architecture, the expansion would be available only on 64bit environment.

**SoftEther version:** all
**Component:** [both Client & Server]
**Operating system:** all
**Architecture:** [64 bit]

![image](https://user-images.githubusercontent.com/941609/71468683-2beda500-280a-11ea-9912-a168088017da.png)

**Comment by domosekai** [comment]
This has nothing to do with 32/64 bit but it will break backward compatibility.
Also I don't see any valid usage that should be restricting bandwidth at Gbps level.

**Comment by metalefty** [comment]
Yes, actually, I also think there's no valid reason to do that. 

Thank you for your recent work on the issue triage.

**Comment by domosekai** [comment]
No problem. Thanks for understanding! I just felt there were too many dead issues.
