### ISSUE TITLE
Docker for the Beta Version

### ISSUE THREAD

**Issue by fabiodcorreia** [SoftEtherVPN/SoftEtherVPN#1067]
Guys I was thinking into a build a webapp to admin the server by the new API, but the docker images that I found it's for the RTM versions but not for the beta.

It's possible to get docker image for the beta so I can try to make the web ui for it?

**Comment by chipitsine** [comment]
hmm.

web ui is very good.
did you we already have some web ui, btw ?

**Comment by fabiodcorreia** [comment]
Not yet, I was thinking to build it in React outside of the server then it can be deployed to other  servers like nginx or apache and later we can see how to put it inside the server.

For start I was thinking in something more like a dashboard where the user can login on the server, see the status, list of hubs, list of ports,... and then add the more complex parts like add, change, remove...

**Comment by chipitsine** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN#about-html5-based-modern-admin-console-and-json-rpc-api-suite

**Comment by fabiodcorreia** [comment]
> https://github.com/SoftEtherVPN/SoftEtherVPN#about-html5-based-modern-admin-console-and-json-rpc-api-suite

I already saw that doc and the javacript client lib, but to start I need a docker image for the beta version since the rtm doesn't have it.

**Comment by chipitsine** [comment]
I have chocolatey package in my queue. After that I'll have a look at docker.
or someone else will volunteer

**Comment by fabiodcorreia** [comment]
I tried to connect the my app to the server using the typescript lib and I found two issues.
1 - The fetch call is using keepalive and on Chrome it gives an error.
2 - The fetch call requires CORS but if I host the app outside the serve it doesn’t work, the plan is to force CORS on the same host or allowed domains would be configured on the server?

**Comment by chipitsine** [comment]
if I were you, I would put reverse proxy (nginx, haproxy, ... ) in front of api and just add proper CORS headers

**Comment by fabiodcorreia** [comment]
Yes I managed that for development, my question is more for the future. 
The user will only be able to use the web app behind a reverse proxy or install it on the vpnserver?
I was thinking in something like drop the web app in any server and then allow to setup the host allowed to do CORS on the vpnserver config. But maybe that’s not the vision for the product.

**Comment by chipitsine** [comment]
as "for the future" from my point of view using reverse proxy is good and flexible.

**Comment by fabiodcorreia** [comment]
I manage to create a new Dockerfile that installs the beta version and then I used it for local development. The Dockerfile will be on the web ui repo.

**Comment by chipitsine** [comment]
if you beleive docker image might be useful, can you help with regular builds ?

**Comment by fabiodcorreia** [comment]
In what exactly you need help? I only use the docker to run the beta version of the vpn server on my computer and then make the RPC calls to the vpn server inside the container.
