### ISSUE TITLE
Windows 10 client cannot connect to Internet

### ISSUE THREAD

**Issue by tiiiko** [SoftEtherVPN/SoftEtherVPN#1068]
### Prerequisites

* [X] Can you reproduce?
* [X] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** Ver 4.32, Build 9731, beta
**Component:** Client
**Operating system:** Linux (ubuntu 18.04) on server, Windows 10 on client
**Architecture:** 64 bit
**Processor:** Surface Pro 7, Intel i7-1065G7 CPU

### Description

When establishing a VPN connection with the SoftEther VPN Client Manager, there is no connection to the Internet - i.e. after activating the connection, when hovering over the connection details it is displayed that the VPN user ("userWindows") cannot connect to the Wifi network ("TP-Link_XYZ"):

> TP-Link_XYZ
> Internet access
> 
> userWindows
> No Internet access
> 

**Expected behavior:**
Establishing VPN connection maintains the Internet connection and websites can be accessed.  

**Actual behavior:**
VPN connection fails to connect to the Internet and websites cannot be accessed.
 
### Steps to reproduce

1. Setup Ubuntu 18.04 server (Standard B1ms with 1 vcpus, 2 GiB memory)

2. Enable SSH and set password

3. Install Ver 4.32, Build 9731, beta Server on Ubuntu based on this instruction:

> sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y	
> 
> sudo apt-get -y install build-essential wget curl gcc make wget tzdata git 
> 
> sudo wget https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.32-9731-beta/softether-vpnserver-v4.32-9731-beta-2020.01.01-linux-x64-64bit.tar.gz
> 
> sudo tar xzf softether-vpnserver-v4.32-9731-beta-2020.01.01-linux-x64-64bit.tar.gz
> 
> cd vpnserver && sudo make
> 
> 1
> 
> 1
> 
> 1
> 
> 	
> cd ..
> 	
> sudo cd /usr/local/vpnserver/	
> 
> sudo chmod 600 *	
> 
> sudo chmod 700 vpnserver vpncmd	
> 
> 	
> sudo ./vpnserver start	
> 
> sudo ./vpncmd	
> 
> 1
> 
> -Enter-
> 
> -Enter-
> 
> -password-
> 
> ServerPasswordSet	
> 
> -password-
> 
> -password-
> 
> exit
> 
> 	
> sudo bash -c 'cat > /lib/systemd/system/vpnserver.service' << EOF
> [Unit]	
> Description=SoftEther VPN Server	
> After=network.target	
> [Service]	
> Type=forking	
> ExecStart=/usr/local/vpnserver/vpnserver start	
> ExecStop=/usr/local/vpnserver/vpnserver stop	
> [Install]	
> WantedBy=multi-user.target	
> EOF	
> 	
> sudo echo net.ipv4.ip_forward = 1 | sudo tee -a /etc/sysctl.conf	
> 
> sudo echo net.ipv6.ip_forward = 1 | sudo tee -a /etc/sysctl.conf	
> 
> 	
> systemctl enable vpnserver	
> 
> -password-
> 
> systemctl start vpnserver	
> 
> -password-
> 
> systemctl stop vpnserver	
> 
> -password-
> 
> systemctl restart vpnserver	
> 
> -password-
> 
> systemctl status vpnserver	
> 	
> sudo ufw allow 500/udp	
> 
> sudo ufw allow 4500/udp	
> 
> sudo ufw allow 5555	
> 
> sudo ufw allow 1194	
> 
> sudo ufw allow 443

4. Follow the steps described in a [YouTube Video by Aman Juman starting from minute 5:30](https://www.youtube.com/watch?v=H9157KFBPdc) to setup the SoftEther Server and Client

5. Connect to VPN with SoftEther client on Surface 7 laptop with Windows 10

**Comment by streetster** [comment]
Have you tried unchecking the `Use default gateway on remote network` checkbox?

Network Connections -> VPN Adapter -> Properties -> Networking -> TCP/IPv4 -> Advanced

![image](https://user-images.githubusercontent.com/22226349/73133772-573ffb80-4025-11ea-840c-471133bcd8ad.png)
