### ISSUE TITLE
Free Softether Account partner?

### ISSUE THREAD

**Issue by internetfirewall** [SoftEtherVPN/SoftEtherVPN#1073]
Hi teams,

thanks for this wonderful application, Softether helps us to get back to the real internet.

I have been used a free account from https://www.fastssh.com/page/softether-servers for a month and it is free and fast enough but I need to get fresh account regularly

I just wondering, is that website part of softether service/project?
can we use that for something more secret? I mean can we trust that website? 

thank you

**Comment by moatazelmasry2** [comment]
Nop. This site is not affiliated with softether project in any way
