### ISSUE TITLE
Fix DNS Leak with OpenVPN

### ISSUE THREAD

**Issue by vormz** [SoftEtherVPN/SoftEtherVPN#1077]
Hey, you should add "block-outside-dns" to generated .ovpn files to avoid dns leaking when connecting over OpenVPN clients.

**Comment by chipitsine** [comment]
it is only good for public vpn services.

for example, if I run SE VPN in corporate environment, I'm ok with such queries.

you are welcome to add some additional setting and send a PR. please keep default behaviour untouched

**Comment by davidebeatrici** [comment]
Done in #1092.
