### ISSUE TITLE
Some serious question about propietary part of code(Packetix)

### ISSUE THREAD

**Issue by vpnfreak** [SoftEtherVPN/SoftEtherVPN#108]
INTERLINK(インターリンク) is offering VPN service named "マイIP ソフトイーサ版"($11/mo).
It is using PacketixVPN, similar to SoftetherVPN.

Hey dnobori, I have a question.
1. When I connect to VPN server(INTERLINK's MyIPSE) using "PacketixVPN client",
   your software make a suspicious connection to Education network.
   This always happens even I disable automatic update/Keep alive in client.

130.158.6.113:5004/UDP < -- What the F is this? Please answer.
1. I don't want these unknown connection.
   So, can I use "SoftetherVPN client" to connect to "Packetix VPN Server"(INTERLINK's)?
2. I want to hide my computer name to be send to INTERLINK's server?
   Would you kindly add such config to Softether/Packetix client?

Thanks. (Nihongo de no kaitou de mo okay desu.)

**Comment by domosekai** [comment]
Port 5004 is used for NAT-T and can be disabled.
