### ISSUE TITLE
VPNGate OpenVPN Issue

### ISSUE THREAD

**Issue by hoang-rio** [SoftEtherVPN/SoftEtherVPN#1083]
Sorry because i don't know how to connect  with VPN Gate Team so create issue here.
All VPN Server of [VPN Gate Project](https://www.vpngate.net/en/) can not connect via OpenVPN because certificate issue.
`mbed TLS: SSL read error: x509 - certificate verification failed`

Here is thread in VPN Gate Forum: https://forum.vpngate.net/viewtopic.php?f=11&t=65342

Hope it will fix soon.

**Comment by chipitsine** [comment]
we do not know much about vpngate.

can you try to reproduce your error with SE VPN developer edition ?

**Comment by hoang-rio** [comment]
> we do not know much about vpngate.
> 
> can you try to reproduce your error with SE VPN developer edition ?

I think it's OpenVPN certificate expires issue. Because all VPN Gate Server can not connect via OpenVPN

**Comment by chipitsine** [comment]
indeed, it might be better error handling. we are not related to vpngate at all

**Comment by hoang-rio** [comment]
@chipitsine Do you know how to report this issue to vpngate team?

**Comment by chipitsine** [comment]
no idea
