### ISSUE TITLE
No half-duplex connection established

### ISSUE THREAD

**Issue by sanchobear** [SoftEtherVPN/SoftEtherVPN#1087]
* [ YES] Can you reproduce?
* [ ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** 4.32 Build 9731
**Component:** Server, Client
**Operating system:** Windows
**Architecture:** 64 bit

**Processor:** Client i7-8595U, Server i7-5960
**Firewall**: IPFire, required ports redirected to Softether server

### Description
The Client Manager Configuration for L2TP uses "Direct TCP/IP" and defines 16 connection for using  half-duplex connection in 10 seconds establishing intervall.

**Expected behavior:**
The connection is established successfully and in the client manager "View Status" the connection mode should be half-duplex and the number of connections indicated as 16.

**Actual behavior:**
 The connection is established successfully, but there is only one single connection indicated in "View Status" and connection mode is full-duplex.

### Steps to reproduce

1. Configure L2TP connection to server
2. Set Number of TCP connections to 16 and check use half-duplex mode
3. Increase establishing interval to 10 seconds
4. Start connection
5. View Status for open connection

**Comment by domosekai** [comment]
Multi-connection and half-duplex only works in SoftEther protocol. L2TP does not support that.
