### ISSUE TITLE
SSL-VPN: Mimic TLS handshake as Chrome (Chromium) and/or Firefox (Gecko) 

### ISSUE THREAD

**Issue by 0x391F** [SoftEtherVPN/SoftEtherVPN#1089]
It's possible to distinguish common HTTPS and SSL-VPN handshake such as the number of cipher suits, TLS version. So it's better to mimic SSL-VPN's handshake as a browser. Maybe we can use some modules of Chromium (the core of Chrome and Edge) and Gecko (the core of Firefox) to do this.

**Comment by subsys-R9boq8** [comment]
The browser engine (the "core")of Chrome and Edge is not Chromium but Blink.
