### ISSUE TITLE
Linux path for 5.x ?

### ISSUE THREAD

**Issue by Voronenko** [SoftEtherVPN/SoftEtherVPN#1096]
There were number of releases for 5.x family (with latest 5.01.9663)

However for unix you are still at 4.34

SoftEther VPN Server (Ver 4.34, Build 9745, beta)
softether-vpnserver-v4.34-9745-beta-2020.04.05-linux-x64-64bit.tar.gz (7.16 MB)
Release Date: 2020-04-05 

Any plans for linux binaries support on 5.x in downloads section ?

**Comment by metalefty** [comment]
> However for unix you are still at 4.34

Where are you looking at?

**Comment by Voronenko** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/releases  

https://www.softether.org/4-docs/1-manual/7._Installing_SoftEther_VPN_Server/7.3_Install_on_Linux_and_Initial_Configurations

In both cases either releases or suggested download binary for AMD64 arch on linux, you would see 4.34

**Comment by chipitsine** [comment]
second URL is SoftEtherVPN Stable edition.
it is managed by separate team.
