### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by djony** [SoftEtherVPN/SoftEtherVPN#1099]
You have a translation bug in all SoftEther VPN client versions (dev and stable)
Bug is that, when choosing any language, the description of the Nat-t message is always in English
In the translation files this is a NATT_MSG and NATT_MSG2 strings
See screenshots 
![Japanese](https://user-images.githubusercontent.com/3650513/79782672-1e73a200-8348-11ea-86e9-a81ab1ea80f3.JPG)
![Chinese](https://user-images.githubusercontent.com/3650513/79782679-1fa4cf00-8348-11ea-87bb-a53d16cd60ca.JPG)

**Comment by metalefty** [comment]
Indeed. I've also seen the NAT-T message in Japanese UI.

**Comment by domosekai** [comment]
This message is sent by the server to the client so it is sent in the server's language. The client has no control over it.

**Comment by metalefty** [comment]
Understood. The message `NATT_MSG` is sent to client depending on server language.
