### ISSUE TITLE
Incompatibility with OpenVPN built with --enable-small (OCC is somehow required)

### ISSUE THREAD

**Issue by patrakov** [SoftEtherVPN/SoftEtherVPN#110]
Some router vendors (OpenWRT, Tomato Shibby) build their OpenVPN program from the official OpenVPN sources and, to save space, use the --enable-small configure option. This strips out the usage message and OCC code. Unfortunately, such client is incompatible with vpngate.net, and they say they run SoftEther VPN. The incompatibility disappears if I re-enable the OCC code in OpenVPN:

```
CPPFLAGS="-DENABLE_OCC=1" ./configure --prefix=/usr --enable-small
```

This incompatibility has been already reported to OpenWRT folks, and then I have reported it to OpenVPN upstream.

https://dev.openwrt.org/ticket/16898
https://community.openvpn.net/openvpn/ticket/472

They, however, deny that it is an OpenVPN bug and ask me to report the issue to vpngate.net. I could not find how to report the issue to vpngate.net, and thus report this bug against software they claim to use.

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by davidebeatrici** [comment]
This issue has been fixed in commit 75f9836ce5f0a1dea2c3fe304bbc26c962ee64bf.

I think that it can now be closed.

**Comment by moatazelmasry2** [comment]
Hi @patrakov has this issue been resolved by now?

**Comment by patrakov** [comment]
So far, I have tested that it is fixed in the default configuration of the server. However, if my understanding is correct, it is not fully resolved, because there is no guarantee that this option string is equivalent to what the official OpenVPN client would send if given the config file generated by OpenVpnMakeConfig.

**Comment by chipitsine** [comment]
I added an issue https://github.com/SoftEtherVPN/SoftEtherVPN/issues/515
details are not clear yet.

some interoperability tests would be nice

**Comment by patrakov** [comment]
I have no concrete details, sorry, and I am not interested in testing SoftEther myself. Basically, here are the facts and ideas that I am basing my suspicion of incomplete fix on:

1. There is OpenVpnMakeConfig command that can generate openvpn configs.
2. It can put various options into the generated configs, that depend on SoftEther VPN server settings. Speculative guess about relevant options: cipher, tun, tap.
3. The config that is generated can be read by the OpenVPN instance on a home router, compiled without OCC, or on a PC, compiled with OCC.
4. SoftEther VPN makes some decisions based on the option string sent by the client.
5. If the client sends "V0 UNDEF", then the default option string comes into play.
6. There is a OpenVPNDefaultClientOption directive, which sets the default option string, hopefully allowing small clients to connect.
7. The "default default" client option string is just a static string that does not depend on any other SoftEther VPN options, thus creating the need to configure certain settings twice - once in other directives, and once in OpenVPNDefaultClientOption, in order to allow small clients to connect.

Well, all of the above is theoretical. The test plan would be to create a SoftEther VPN server that emulates a TAP OpenVPN server, then generate an OpenVPN client config, then try to connect with normal client, and try to connect with a small client, and this all should either work without the need to set  OpenVPNDefaultClientOption, or without such option there must be a prominent warning in SoftEther VPN log that the default client option is not compatible with the configured settings. So that admins that are educated enough to read logs don't create servers incompatible with small OpenVPN clients by mistake.

**Comment by domosekai** [comment]
Close due to inactivity
