### ISSUE TITLE
Fix Patch Acceptance Policy (GPLv2 remains)

### ISSUE THREAD

**Issue by takotakot** [SoftEtherVPN/SoftEtherVPN#1100]
### Prerequisites

* [X] Can you reproduce?
* [X] Are you running the latest version of SoftEtherVPN?

### Description

"SoftEther VPN Patch Acceptance Policy" is old and "GPLv2" remains.

https://www.softether.org/5-download/src/9.patch
https://ja.softether.org/5-download/src/9.patch

**Expected behavior:**
Some "GPLv2" must be replaced by "Apache License 2.0".
Maybe it is needed to declare "SoftEther VPN *WAS* released under GPLv2 but switched to Apache License 2.0."

**Comment by chipitsine** [comment]
SoftEtherVPN Developer edition has changed licence
SoftEtherVPN is GPLv2

**Comment by takotakot** [comment]
If so, remaining "Apache License 2.0" should be "GPLv2" and https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/LICENSE must be fixed.

**Comment by chipitsine** [comment]
I was wrong, both stable and developer editions are Apache licenced now

**Comment by metalefty** [comment]
I guess only Nobori-san can update softether.org site. It's up to @dnobori .

**Comment by MtCedarNet** [comment]
I have fixed the description of the website.

**Comment by takotakot** [comment]
Thank you.
