### ISSUE TITLE
CHECK_PROC_NETWORK Failed 

### ISSUE THREAD

**Issue by takotakot** [SoftEtherVPN/SoftEtherVPN#1101]
### Prerequisites

* [X] Can you reproduce?
* [X] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
9073452b AND v4.29-9680-rtm two versions
**Component:**
vpncmd
**Operating system:**
CentOS 8 (kernel 4.18.0-147.8.1.el8_1.x86_64)
**Architecture:**
x86_64

**Processor:**
Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
(Running on VMware vSphere)

### Description

**Expected behavior:**
`CHECK_PROC_NETWORK` Check passed.

**Actual behavior:**
`CHECK_FAIL`
`Connect Failed. (0)`
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/Command.c#L169
(not line 161)

### Steps to reproduce

1. `./configure && make -C tmp`
2. run `./build/vpncmd` and check with "3" "check"

openssl: `1:1.1.1c-2.el8_1.1`
gcc: `8.3.1 20190507 (Red Hat 8.3.1-4)`

I tried to compile both 9073452b and SoftEtherVPN_Stable-4.29-9680-rtm and failed.

I can successfully compile SoftEtherVPN_Stable-4.29-9680-rtm on Ubuntu 18.04. (I didn't tried 9073452b .)
openssl: `1.1.1-1ubuntu2.1~18.04.5`
gcc: `7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)`

### Extra information
1. Extract `softether-vpnserver-v4.29-9680-rtm-2019.02.28-linux-x64-64bit.tar.gz` to `vpnserver` on CentOS 8
2. Copy `SoftEtherVPN_Stable-4.29-9680-rtm/tmp/as/vpncmd.a` which compiled on Ubuntu to `vpnserver/code` on CentOS 8
3. `make` (on CentOS 8) and run `vpncmd` works

Because of avobe, I assume that it is a openssl problem.

I can do further research with guidance.

**Comment by metalefty** [comment]
This repository is for SoftEtherVPN 5.x. Can you confirm if the issue exists in **this** repository?

**Comment by takotakot** [comment]
@metalefty  I tried 9073452 . Please notify me an id to try.

**Comment by metalefty** [comment]
Ah,  you've tried multiple versions 9073452 and `v4.29-9680-rtm`. I confused a bit. Sorry for the noise.

**Comment by takotakot** [comment]
No ploblem. Soffy for confusing you. (Added "AND".)

**Comment by takotakot** [comment]
I checked with manually build openssl(s). I added `LD_LIBRARY_PATH=` and test `./build/vpncmd` 3 check.

openssl 1.1.1c from github (97ace46e11) is OK.
openssl 1.1.1c-2.el8 (from CentOS 8 openssl-1.1.1c-2.el8.src.rpm) is NG.

Maybe CentOS 8 problem... I'll check which option or patch is causing the problem.

**Comment by chipitsine** [comment]
nice catch

**Comment by takotakot** [comment]
Finally I've found:

- CentOS 8 OpenSSL configure option contains `--openssldir=/etc/pki/tls`
- `/etc/pki/tls/openssl.cnf` includes `/etc/crypto-policies/back-ends/opensslcnf.config`
- By default, `CipherString = DEFAULT@SECLEVEL=2 (:!aNULL: .. etc.)` is written in `/etc/crypto-policies/back-ends/opensslcnf.config` (i.e. `sudo update-crypto-policies --set DEFAULT`)

When `@SECLEVEL=2` is set by config, `SSL_accept(sock->ssl);` and `SSL_connect(sock->ssl);` returns `-1` (`src/Mayaqua/Network.c`).

Workaround1:
Rewrite `@SECLEVEL=2` to `@SECLEVEL=1` or run `sudo update-crypto-policies --set LEGACY`

Workaround2:
Add `SSL_CTX_set_security_level(ssl_ctx, 0);` to ignore `@SECLEVEL=2` also works(patch WIP).

**Comment by chipitsine** [comment]
is that related to https://www.redhat.com/en/blog/consistent-security-crypto-policies-red-hat-enterprise-linux-8 ?

**Comment by takotakot** [comment]
Yes. If we switch policy using `update-crypto-policies`, `/etc/crypto-policies/back-ends/opensslcnf.config` is updated. `opensslcnf.config` is included by `/etc/pki/tls/openssl.cnf`.

`DEFAULT` policy sets `SipherString = DEFAULT@SECLEVEL=2` and `SSL_accept` fails.
```
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher
```

`LEGACY` is safe for us.

I'm considering to add `SSL_CTX_set_security_level(ssl_ctx, 0);` to downgrade seclevel for SE (works).

**Comment by chipitsine** [comment]
there is hard choice.

either you follow OS policy (and it might be your desire)
or you may wish to violate corporate policy in purpose (i.e. manipulating with SSL_CTX_set_security_level)


I like your approach. However, I think we should some documentation on it, because people may blindly beleive that if they set openssl system wide policy they will stay compliant for every single application including SE.

**Comment by takotakot** [comment]
I agree.

But openssl included in the RTM version looks for another path and ignores system policy.

> I think we should some documentation on it

I want to try. May I ask which file is good for such documentation (`src/WARNING.TXT` or README.md or ...).

By the way, modifying `RsaGen(&pri, &pub, 1024);` to `RsaGen(&pri, &pub, 4096);` also passes the test (https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/Command.c#L76). What kind of change is better for SE?

**Comment by takotakot** [comment]
I've found Stable version set security level force.
https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/commit/e3370fb62c31eb10d0d221e628161863358d4cc3#diff-023300e46b097e2690bca05baa698ffeR18177

Before that, just planned to code:
- Add options `Use_OS_Security_Level` and `SE_Security_Level`
  (or `-1` for use OS level and otherwise set SE level)
- If high level is set, change RSA bit to 4096.
