### ISSUE TITLE
RADIUS issue with Windows native VPN client

### ISSUE THREAD

**Issue by hajekj** [SoftEtherVPN/SoftEtherVPN#1103]
**SoftEther version:** 4.32 9731
**Component:** Server
**Operating system:** Ubuntu 18.04
**Architecture:** 64 bit (Virtual Machine)

### Description

When connecting to SoftEther VPN Server via built-in Windows VPN client (either SSTP or L2TP with IPSec) and explicitly selecting a hub to use - `jan.hajek@thenetw.org@HUBNAME` the authentication fails when RADIUS server is used.

This is caused by the computer doing MSCHAPv2 authentication by default (when I switch it manually to PAP everything works). The issue is that the MSPCHAPv2 challenge is generated with username: `jan.hajek@thenetw.org@HUBNAME` but the username which arrives to RADIUS is `jan.hajek@thenetw.org`. On the RADIUS server, I don't have any means to determine whether the hub was specified implicitly or explicitly to edit the username.

**Expected behavior:**
It would be great if the full username was either sent in additional RADIUS attribute (not a breaking change) or sent fully instead of just username without the hub (breaking change).

### Steps to reproduce

1. Setup SoftEther VPN server with RADIUS authentication (using FreeRADIUS for example)
1. Setup VPN connection from Windows native VPN client (Windows 10, 1909+) using MSCHAPv2 authentication
1. Specify the hub explicitly in the username
1. RADIUS server receives error but MSCHAPv2 authentication fails
1. Authentication fails

**Comment by Evengard** [comment]
This is another of the issues because I changed the default auth mechanism for PPP stack from PAP to MS-CHAP. I sure can switch it back, but that wouldn't be too secure. Is there any way to actually tweak the RADIUS part?

**Comment by hajekj** [comment]
I am looking at the ways to configure the FreeRADIUS part to try first with regular username, and if it fails to append the SoftEther hub name in case it is present. I will post back when I figure out how to set it up.
And I completely agree that switching back to PAP isn't the proper solution, since it's way less secure than MSCHAPv2.

**Comment by hajekj** [comment]
I think one of the quickest fixes would be to pass `MS-CHAP-User-Name` from SoftEther to the RADIUS server (FreeRADIUS [prefers it](https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/src/modules/rlm_mschap/rlm_mschap.c#L227) to regular `User-Name`).

This would make the most sense to me, as you would be passing the correct value of the username by which the challenge has been generated to the RADIUS server. However, it is hard to say whether this would be a breaking change for existing RADIUS deployments with SoftEther.

It is generally bad practice to make the fix in FreeRADIUS - try to authenticate and if it fails, try to authenticate again with different parameters.

**Comment by Viktort-rf** [comment]
Is there any news on this issue?
I came across the same behavior.
Cannot connect to any vpn hub other than the default vpn hub. Standard Win 10 client (ms-chap v2) over l2tp+ipsec. Everything works on auth PHP

**Comment by Viktort-rf** [comment]
I found an option on how to get around this issue:)
Use the "hubname\username" construct instead of the "username@hubname" construct

**Comment by domosekai** [comment]
Closing as the solution has been found.
