### ISSUE TITLE
Android binaries. needed so much!

### ISSUE THREAD

**Issue by DI555** [SoftEtherVPN/SoftEtherVPN#1105]
Please provide and Android binaries too. Client, server and bridge builds would be awesome!
Since i found linux binaries here:
github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases
Great to be and Android binaries be there also!
Many thanks in advance!

**Comment by drkrool** [comment]
Android client would be godsent

**Comment by chipitsine** [comment]
not many PRs were seen on the subject

**Comment by DI555** [comment]
yes, at least android client one could be greatest!
...because in other way we're using openvpn one which not so good as softethervpn(((

**Comment by domosekai** [comment]
Duplicate of #1019
