### ISSUE TITLE
Import changes from stable

### ISSUE THREAD

**Issue by takotakot** [SoftEtherVPN/SoftEtherVPN#1110]
Is there any rule for importing changes of version 4?
I've found some changes (ex. Tls_Disable1_3) are only in SoftEtherVPN_Stable repo.

**Comment by chipitsine** [comment]
we sometimes do porting. feel free to do backport if you have time/wish :)

**Comment by chipitsine** [comment]
can we wait a backport PR from you ?

**Comment by takotakot** [comment]
Yes, but we have to consider (or maybe just I don't know)

- what change to backport / ignore
- which commit (after v4.23-9647-beta) is done / not
- split commit / not
- which order...
- etc.

at first.

Looking at https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/commit/e3370fb62c31eb10d0d221e628161863358d4cc3, I *easily* found `bool Tls_Disable1_3;` is not yet added. It's not always easy because v4 commit is large.
