### ISSUE TITLE
The generated ovpn file has no key and cer

### ISSUE THREAD

**Issue by roycho93** [SoftEtherVPN/SoftEtherVPN#1118]
The key and cer in the ovpn file generated in the 5.01 version of softether are blank. The old version (4.23) does not have this problem. Is my setting wrong? What should I do?thanks！
![1589079436(1)](https://user-images.githubusercontent.com/50717235/81489917-cfb58a00-92ad-11ea-9da1-557545d5a7bc.png)

![1589079343(1)](https://user-images.githubusercontent.com/50717235/81489907-b8769c80-92ad-11ea-911c-4b0cfe292786.png)

![1589079500(1)](https://user-images.githubusercontent.com/50717235/81489920-d47a3e00-92ad-11ea-87c8-c919bac01b98.png)

**Comment by metalefty** [comment]
I confirmed the issue with 5.01.9674. As mentioned in config file, "client certificate and private key is required in case you want to use the certificate authentication" and you must have the client cert and key in the client. So just paste it there *if you want to use the certificate authentication*.

**Comment by roycho93** [comment]
> I confirmed the issue with 5.01.9674. As mentioned in config file, "client certificate and private key is required in case you want to use the certificate authentication" and you must have the client cert and key in the client. So just paste it there _if you want to use the certificate authentication_.

Thank you for your reply, just curious, why in the new version, the automatically generated client certificate and the key in the opvn file are cancelled?

**Comment by davidebeatrici** [comment]
The `<cert>` and `<key>` sections are entirely missing in the stable version.

The certificate and key are not filled automatically because the configuration is generic, rather than for a specific user.

**Comment by metalefty** [comment]
> The <cert> and <key> sections are entirely missing in the stable version.

Did you mean developer version? Stable version HAS `<cert>` and `<key>` section (but it is a dummy for some client implementation).

```
###############################################################################
# The client certificate file (dummy).
#
# In some implementations of OpenVPN Client software
# (for example: OpenVPN Client for iOS),
# a pair of client certificate and private key must be included on the
# configuration file due to the limitation of the client.
# So this sample configuration file has a dummy pair of client certificate
# and private key as follows.

<cert>
(snip)
```

**Comment by roycho93** [comment]
> The `<cert>` and `<key>` sections are entirely missing in the stable version.
> 
> The certificate and key are not filled automatically because the configuration is generic, rather than for a specific user.
Thank you for your reply！

**Comment by davidebeatrici** [comment]
@metalefty You're right, I forgot about that. Thank you for pointing it out.

@roycho93 You're welcome!

**Comment by metalefty** [comment]
Just for the note and IIRC,

| | Stable version | Developer version |
|-|-|-|
|OpenVPN certificate authentication|  | ☑  |
| (dummy) cert and key in generated config | ☑ | |

**Comment by davidebeatrici** [comment]
Yes, that's correct.

**Comment by roycho93** [comment]
> Just for the note and IIRC,
> 
> Stable version	Developer version
> OpenVPN certificate authentication		☑
> (dummy) cert and key in generated config	☑

thanx！When I originally used the 4.23 build 9647 version, I could generate cer and key in the ovpn file. Is there a way to modify the configuration file so that the 5.01 version can also automatically generate the key and cer?

**Comment by davidebeatrici** [comment]
Are you sure they were the right certificate and key and not the dummy ones?

**Comment by roycho93** [comment]
> Are you sure they were the right certificate and key and not the dummy ones?

Sorry, I am not a professional and do n’t know how to distinguish between a right certificate and a dummy certificate? I only know that the certificate is automatically generated

**Comment by metalefty** [comment]
Some more related issues: #521 #990

**Comment by davidebeatrici** [comment]
The certificate and its key are indeed generated automatically (and valid), however they're not associated to a user.

They were added in order to get the configuration to work with the OpenVPN Client for iOS back when it required them.

The dummy certificate doesn't cause an authentication failure only because the stable version doesn't support OpenVPN's certificate authentication method.

See #521.

**Comment by roycho93** [comment]
Thank you guys, so if I want to automatically generate the key and cer, is it a way to switch to the developer version?This is the certificate I have
![1589165423(1)](https://user-images.githubusercontent.com/50717235/81519931-5ed9a500-9375-11ea-91c0-998de4767d5a.png)

**Comment by davidebeatrici** [comment]
The certificate and key are never inserted automatically into the OpenVPN configuration.

In addition to filling the `<cert>` and `<key>` fields, you have to use the developer version.

**Comment by roycho93** [comment]
Where can I filling the cert and key insertion?

> The certificate and key are never inserted automatically into the OpenVPN configuration.
> 
> In addition to filling the `<cert>` and `<key>` fields, you have to use the developer version.

thnx,I got it!

**Comment by metalefty** [comment]
The certificate you showed is server certificate. The `<cert>` and `<key>` field in `.ovpn` file is client certificate. You need to register client certificates to server for each users if you want to use certificate authentication in OpenVPN.

(Excuse me the screenshot is in Japanese)
![スクリーンショット 2020-05-11 12 12 37](https://user-images.githubusercontent.com/941609/81520997-e11b9680-9380-11ea-9f1c-716c235c22a1.png)

**Comment by roycho93** [comment]
> The certificate you showed is server certificate. The `<cert>` and `<key>` field in `.ovpn` file is client certificate. You need to register client certificates to server for each users if you want to use certificate authentication in OpenVPN.
> 
> (Excuse me the screenshot is in Japanese)
> ![スクリーンショット 2020-05-11 12 12 37](https://user-images.githubusercontent.com/941609/81520997-e11b9680-9380-11ea-9f1c-716c235c22a1.png)
> 
> 1. Create **client** certificates for each users (1 certificate per 1 user)
> 2. Register the client certificate to the server for users
> 3. Copy & paste `1.` to `.ovpn` file

日本の方ですか？ご回答ありがとうございます！
図のようにしていますが、認証方法を固有証明書選択し、こういうメッセージを出てしまいました。
![20200511143213](https://user-images.githubusercontent.com/50717235/81530889-55ac0080-9394-11ea-9727-0032acf76b14.png)

**Comment by metalefty** [comment]
I'll give you a hint. Here it is:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/942051d/src/Cedar/Server.c#L10596-L10647

**Comment by roycho93** [comment]
> I'll give you a hint. It is an open secret.
> https://github.com/SoftEtherVPN/SoftEtherVPN/blob/942051d/src/Cedar/Server.c#L10596-L10647

thnx！
