### ISSUE TITLE
Cascade no active UDP Acceleration

### ISSUE THREAD

**Issue by kerus1024** [SoftEtherVPN/SoftEtherVPN#1127]
### Prerequisites

- [x] Can you reproduce?
- [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** 5.01.9674
**Component:** Server
**Operating system:** Linux
**Architecture:** 64bit
**Processor:** QEMU

### Description

**Expected behavior:** In the Cascade mode, UDP Acceleration is not activated when the target server is the developer edition.

**Actual behavior:** 

UDP Acceleration is Supported : Yes
UDP Acceleration is Active  No

### Steps to reproduce

1. Install SoftEtherVPN Developer Edition
2. Make Cascade Connection from another server
3. Check UDP Acceleration Status

**Comment by davidebeatrici** [comment]
OpenSSL version?

**Comment by kerus1024** [comment]
> OpenSSL version?

OpenSSL 1.1.1d -> OpenSSL 1.0.2k-fips [Not work]
OpenSSL 1.1.1.d -> OpenSSL 1.1.1g [Not work]
OpenSSL 1.1.1g -> OpenSSL 1.0.2k-fips [Not work]

**Comment by davidebeatrici** [comment]
Does it work with a client?

**Comment by kerus1024** [comment]
Yes. In Windows client, it is connected by UDP Acceleration.

**Comment by domosekai** [comment]
I can't reproduce it. Cascade has UDP acceleration working.
