### ISSUE TITLE
wrong dhcp hostname request with sstp 

### ISSUE THREAD

**Issue by mrred06** [SoftEtherVPN/SoftEtherVPN#1129]
Hi all, when I use softether server 5.01(9672) with a SSTP client (win or android) the client hostname registration given to the dhcp server on the lan are wrong (localhost? _gateway or empty) but never the correct name of the computer.

log from my dhcpd server:

```
dhcpd |   | DHCPACK on 192.168.1.243 to aa:7b:6f:2e:0f:bb (localhost) via vmx1
dhcpd |   | DHCPREQUEST for 192.168.1.243 (192.168.1.1) from aa:7b:6f:2e:0f:bb (localhost) via vmx1
dhcpd |   | DHCPOFFER on 192.168.1.243 to aa:7b:6f:2e:0f:bb (localhost) via vmx1
dhcpd |   | DHCPDISCOVER from aa:7b:6f:2e:0f:bb via vmx1

```
so the dns server record (by the dhcpd registration) for the client are wrong and break the windows sharing when another client on the network try to reach the vpn client.

I have no issues with SoftEther/OpenVpn Mode only sstp.

SoftEther is configured without Layer3 Switching/ Virtual NAt

Thx alot.

**Comment by domosekai** [comment]
SSTP client doesn't send its hostname to the server. This is not a softether issue.
