### ISSUE TITLE
Is this software considered as stable ?

### ISSUE THREAD

**Issue by rbecheras** [SoftEtherVPN/SoftEtherVPN#113]
I notice that there is no release version. I would want install this soft at work but we need a stable software.

**Comment by slacka** [comment]
This is issue tracker not a discussion forum. Please direct future questions [to the forum instead:](http://www.vpnusers.com/)


I have been using SoftEther for several years and never run into any stability issues. All of the releases are well tested. If the "beta" tag worries you, the last stable release was [v4.08](http://www.softether-download.com/files/softether/v4.08-9449-rtm-2014.06.08-tree/) that you can can be found from on [the official download site.](http://www.softether-download.com/en.aspx)

**Comment by rbecheras** [comment]
Okay I didn't found the forum before, thanks. And thanks for your response.
