### ISSUE TITLE
SoftEther VPN client is blocked in China 

### ISSUE THREAD

**Issue by lirdi** [SoftEtherVPN/SoftEtherVPN#1133]
Hello, thanks for reading my issue.
I am Lirdi Cani

Currently I am trying to use SoftEther VPN client from China(my location).
But I can't use it.
I think it is blocked on my location.

" IS IT POSSIBLE TO USE SoftEther VPN client on CHINA " !!!!!!

thanks Lirdi

**Comment by chipitsine** [comment]
we do not provide such support level, also we generally do not know whether China blocks it or not.

however, you can use sniffer software like Wireshark (on both client and server side) and figure it out by yourself.

sorry, we cannot do it for you

**Comment by souchprod** [comment]
Just for the record, same issue here, for hours, sometimes weeks my Softether vpn is not reachable at all from China (it is from Singapore to France without issue for ex.). I changed to port, the ip, whatever i do it's down. I guess that the great firewall detect the protocol signature or the softether specific handshake :'(
So for, no better way than having another VPN server & client... so bad.

**Comment by ariaxiii** [comment]
[Just in case somebody encounter with similar problem specially for china and iran ]
Setup VPN over ICMP in Server side and then try to connect to a random port on your server from client. this will mostly solve the problem unless your server ip got blocked by  ISP.
