### ISSUE TITLE
Error 13876 Load Failed

### ISSUE THREAD

**Issue by devinharrison8** [SoftEtherVPN/SoftEtherVPN#1135]
When SoftEther VPN Server is Running on Services, IKE and AuthIP IPsec Keying Modules Service Gets Disable, So You Can't Run SoftEther VPN Server and Use Windows built-in VPN in Same Time!

I Checked This Problem with Two Different RDP that Using Win Server 2016, and Win 10 Home & Pro Edition.

**Comment by devinharrison8** [comment]
Or I Can Say: SoftEther forcibly disables IKEEXT.

**Comment by davidebeatrici** [comment]
The behavior is expected:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/2fafd7c70eef9da8a9337c1c818a14bfdf3371d6/src/WARNING.TXT#L124-L131

**Comment by devinharrison8** [comment]
Oh it's OK! 👍

**Comment by devinharrison8** [comment]
A Short Question! Does SoftEther VPN Server Supports PPTP & IKEv2 Configuration? if not, is there any plan to add them or it's impossible for SoftEther Project.
