### ISSUE TITLE
A Short Question!

### ISSUE THREAD

**Issue by devinharrison8** [SoftEtherVPN/SoftEtherVPN#1136]
Does SoftEther VPN Server Supports PPTP & IKEv2 Configuration? if not, is there any plan to add them or it's impossible for SoftEther Project?

**Comment by metalefty** [comment]
No both.

PPTP would never be added. IKEv2 has a chance if someone works on it.

**Comment by chipitsine** [comment]
people tend to "plus one", maybe they beleive it will add IKEv2 anytime.
nobody yet submitted a patch

https://github.com/SoftEtherVPN/SoftEtherVPN/issues/13

**Comment by DRSDavidSoft** [comment]
@metalefty Is the reason for PPTP the severe lack of security?

**Comment by metalefty** [comment]
I think lack of security is one of the reasons but not the only reason.

IKEv2 is more worth than PPTP. IMO, everyone wants to spend time on writing  KEv2 code rather than PPTP. I would say Implementing PPTP now has few benefits than effort.
