### ISSUE TITLE
L2TP doesnt work -> Possible documentation improvements

### ISSUE THREAD

**Issue by harm-smits** [SoftEtherVPN/SoftEtherVPN#1139]
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN? (5.01 Build 9672)

**SoftEther version:**
**Component:** [Server]
**Operating system:** [Linux / Ubuntu Server 20.04 LTS]
**Architecture:** [64 bit]
**Processor:** [Intel Xeon X5650]

### Description

L2TP doesnt work (listeners are not starting)

**Expected behavior:**
I expect L2TP to listen to ports 500, 4500 and 1701.

Running netstat will give back the following (other ports are opened and all):

```
sudo netstat -lntp | grep -w "vpnserver"
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      248170/vpnserver
tcp        0      0 0.0.0.0:992             0.0.0.0:*               LISTEN      248170/vpnserver
tcp        0      0 0.0.0.0:1194            0.0.0.0:*               LISTEN      248170/vpnserver
tcp        0      0 0.0.0.0:5555            0.0.0.0:*               LISTEN      248170/vpnserver
tcp6       0      0 :::443                  :::*                    LISTEN      248170/vpnserver
tcp6       0      0 :::992                  :::*                    LISTEN      248170/vpnserver
tcp6       0      0 :::1194                 :::*                    LISTEN      248170/vpnserver
tcp6       0      0 :::5555                 :::*                    LISTEN      248170/vpnserver
```

IPsec config looks as follows:
```
declare IPsec
{
	bool EtherIP_IPsec false
	string IPsec_Secret something
	string L2TP_DefaultHub RootNetwork
	bool L2TP_IPsec true
	bool L2TP_Raw true

	declare EtherIP_IDSettingsList
	{
	}
}
```

**Actual behavior:**
No port listeners are opened and I am unable to connect using IPsec

### Steps to reproduce

1. Install on Ubuntu 20.04 LTS
2. Using the server manager create an Virtual Hub
3. Add a user to the virtual hub
4. Enable IPsec
5. Try connecting using a windows desktop / android phone / iphone doesnt work as the listeners are not running.

**Comment by metalefty** [comment]
Please make sure to fill out **SoftEther version:**. Even if you check **Are you running the latest version of SoftEtherVPN?**. 

"The latest version" you mean and we expect might be different.

**Comment by harm-smits** [comment]
I have added the build number, however, I did manage to solve the issue by enabling SecureNAT and by setting `/proc/sys/net/ipv4/ip_forward` to 1. It is not present anywhere in the documentation which caused me to believe this was a bug although all was working correctly in the end. Still weird how it isn't showing up on netstat though.

**Comment by chipitsine** [comment]
@harm-smits , do you think we should improve documentation ? or maybe modify setup scenario ? it is not hard to check that `/proc` setting from program itself

**Comment by harm-smits** [comment]
First of all, the command line utility absolutely sucks. It does not obey unix conventions and makes automatic setup scripts an absolute pain. Please don't use your own CLI, they are the worst (I already have a CLI, why do you create your own one :/).

Secondly, the "SecureNAT" option description seems way too overkill:

```
The SecureNAT function is recommended only for system administrators or people with a detailed knowledge of networking.
```

This is completely false, the only knowledge one needs is what IP ranges are free on their network for the virtual hub to avoid IP collisions and how DHCP should be handled. Having this more explicitly stated would be for the best.

Thirdly, it would be good to have a proper diagnostic section where you say to users what ports to open for e.g. L2TP, instead of all the way at the bottom of the page on "configuring L2TP".

Finally, perhaps add a dedicated setup section for e.g. Ubuntu (I can do this too but am short on time for now), a lot of people use it for a reason and not having any documentation on that is just weird.

**Comment by harm-smits** [comment]
Reopened the issue due to documentation fixes that could be made.

**Comment by chipitsine** [comment]
yeah, first hand experience is good thing :)

**Comment by metalefty** [comment]
Hey, this is completely wrong.

```
sudo netstat -lntp | grep -w "vpnserver"
```
`netstat -t`  is a short form of `--tcp`. You're limiting to show TCP services however all of ISAKMP, IPsec NAT-T, and L2TP are UDP. It is definitely natural that TCP services are not shown.

SecureNAT and `/proc/sys/net/ipv4/ip_forward` doesn't matter listening on 500/udp, 4500/udp at all.

**Comment by harm-smits** [comment]
@metalefty Yes, I did notice that once I re-read the post. Should've updated the post accordingly :)
