### ISSUE TITLE
PPP always pushing 1.0.0.1 via IPCP

### ISSUE THREAD

**Issue by colemar** [SoftEtherVPN/SoftEtherVPN#114]
I am using sstp-client (https://sourceforge.net/p/sstp-client/) on Linux for connecting via SSTP to SoftEther VPN server with SecureNAT on Ubuntu 14.04.1 LTS x64.
I noticed that the SoftEther VPN server is pushing the address 1.0.0.1 via IPCP, causing the client pppd to set up a route for it:

```
# route -n4
Kernel IP routing table
Destination Gateway Genmask Flags Metric Ref Use Iface
0.0.0.0 0.0.0.0 0.0.0.0 U 0 0 0 ppp0
1.0.0.1 0.0.0.0 255.255.255.255 UH 0 0 0 ppp0
10.0.0.0 10.220.21.1 255.0.0.0 UG 0 0 0 eth0
10.220.21.0 0.0.0.0 255.255.255.0 U 1 0 0 eth0
127.0.0.1 0.0.0.0 255.255.255.255 UH 0 0 0 lo

# grep IPCP /var/log/syslog
Nov 21 08:28:58 lub pppd[3533]: sent [IPCP ConfReq id=0x1 <compress VJ 0f 01> <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Nov 21 08:28:58 lub pppd[3533]: rcvd [IPCP ConfReq id=0x2 <addr 1.0.0.1>]
Nov 21 08:28:58 lub pppd[3533]: sent [IPCP ConfAck id=0x2 <addr 1.0.0.1>]
Nov 21 08:28:58 lub pppd[3533]: rcvd [IPCP ConfRej id=0x1 <compress VJ 0f 01> <ms-dns2 0.0.0.0>]
Nov 21 08:28:58 lub pppd[3533]: sent [IPCP ConfReq id=0x2 <addr 0.0.0.0> <ms-dns1 0.0.0.0>]
Nov 21 08:28:58 lub pppd[3533]: rcvd [IPCP ConfNak id=0x2 <addr 192.168.30.11> <ms-dns1 192.168.30.1>]
Nov 21 08:28:58 lub pppd[3533]: sent [IPCP ConfReq id=0x3 <addr 192.168.30.11> <ms-dns1 192.168.30.1>]
Nov 21 08:28:58 lub pppd[3533]: rcvd [IPCP ConfAck id=0x3 <addr 192.168.30.11> <ms-dns1 192.168.30.1>]

# ifconfig -a
eth0 Link encap:Ethernet HWaddr 08:00:27:75:fb:7c 
inet addr:10.220.21.73 Bcast:10.220.21.255 Mask:255.255.255.0
[...]
ppp0 Link encap:Point-to-Point Protocol 
inet addr:192.168.30.11 P-t-P:1.0.0.1 Mask:255.255.255.255
UP POINTOPOINT RUNNING NOARP MULTICAST MTU:1500 Metric:1
RX packets:15 errors:0 dropped:0 overruns:0 frame:0
TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:3 
RX bytes:1219 (1.2 KB) TX bytes:450 (450.0 B)
```

The Virtual Host's Network Interface IP address is 192.168.30.1, therefore I do not understand why the VPN server pushes 1.0.0.1 instead of 192.168.30.1.
Since the pppd configuration has the options [defaultroute] and [replacedefaultroute], there is a default route to interface ppp0 in place, therefore missing the route for 192.168.30.1 is USUALLY not a problem.
However if we have a route for 192.168.0.0/16 (which is PRIVATE-ADDRESS-CBLK-RFC1918-IANA-RESERVED) in place (because there are such hosts on the LAN), then having a more specific route for 192.168.30.1 to ppp0 is mandatory (also because 192.168.30.1 is the DNS server address pushed by the VPN server to the client).
Of course I can myself force the route using a command like [route add -net 192.168.30.1/32 dev ppp0], still I believe that the VPN server should push it through IPCP.

The problematic code piece is
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/IPsec_PPP.c#L304
and was identified by dajhorn in thread
http://www.vpnusers.com/viewtopic.php?f=7&t=3899

**Comment by davidebeatrici** [comment]
Related issue: #61

**Comment by CatastroWing42** [comment]
Is this issue solved yet? i'm trying to modify the server ip,but meet some problems

**Comment by davidebeatrici** [comment]
Pull request: #524

**Comment by itsrmcintosh** [comment]
I looked back at the commit and noticed this is no longer applied from what I'm seeing and also the latest SE server reflects still handing out 1.0.0.1. This is an issue, that's now a cloudflare IP, and I believe its still the cause of routing issues on mikrotik (and possibly others) trying to L2TP to SE.

**Comment by davidebeatrici** [comment]
#524 changed the IP address to `192.0.0.8`, which is defined in RFC7600 as dummy IPv4 address.

**Comment by Upitep** [comment]
It's great that you fixed this for PPP. But why has everyone forgotten about SSTP? It still returns 1.0.0.1 as the remote address, and Mikrotik creates a dynamic route to this interface. This is simply terrible, since the actual CloudFlair address is now wrapped in the SSTP interface. Meanwhile, the network address is also returned as 1.0.0.1. Please correct this oversight for SSTP as well.

```
[admin@MikroTik ax2] > /ip address print detail where interface=sstp-out1
Flags: X - disabled, I - invalid; D - dynamic; S - slave 
 2  D  address=10.73.120.10/32 network=1.0.0.1 interface=sstp-out1 actual-interface=sstp-out1 
```

```
[admin@MikroTik ax2] > /ip route print detail where gateway=sstp-out1
Flags: D - dynamic; X - disabled, I - inactive, A - active; c - connect, s - static, r - rip, b - bgp, o - ospf, i - is-is, d - dhcp, v - vpn, m - modem, y - bgp-mpls-vpn; H - hw-offloaded; + - ecmp 
   DAc   dst-address=1.0.0.1/32 routing-table=main gateway=sstp-out1 immediate-gw=sstp-out1 distance=0 scope=10 target-scope=5 local-address=10.73.120.10%sstp-out1 
```

**Comment by viciious** [comment]
I can confirm that the issue is also still relevant for Keenetic SSTP client.
