### ISSUE TITLE
Connection issues with SSTP

### ISSUE THREAD

**Issue by devinharrison8** [SoftEtherVPN/SoftEtherVPN#1141]
.

**Comment by devinharrison8** [comment]
I know you're saying why didn't you read readme or tutorials or FAQ!  But believe me, I searched a lot on the internet and didn't find the answer to my questions.  I finally didn't understand how SSTP works, if the certificate requires why VPN Gate servers don't need it, and if the certificate doesn't need, why SoftEther Server emphasizes that we need to create a certificate.

**Comment by devinharrison8** [comment]
I can't connect with both of methods (via certificate and without certificate), when I change domain name, SoftEther wants to me to generate and save and finally import certificate in Trusted Certificate Authorities, so I accept it and do all of them, but when i try to Connect, pops up an error something like certificate not found to use on this server (I'll send errors in next comment); but when i try to Connect without Certificate, appears an error about season eneded by host (I'll send errors exactly in next comment), so what i have to do? but VPN Gate servers work properly without certificate for me.

**Comment by metalefty** [comment]
BTW, you should give a more appropreate title. "Short Question" describes nothing, useless, not informative at all.

**Comment by devinharrison8** [comment]
1- If you are not blind, you will see a short question in the first comment.

2- I have a problem, now tell me what to do, get help from a specialist? I don't know, say problem in forum? I did, but no one answered. Search the internet? I did and couldn't find an answer. Now here is the final place to raise my issue. Yes! It's inconvenient! that I don't know anyone to get help from. Yes, it is inconvenient when I raise the issue in the forum and no one answers. Yes, it is inconvenient when the answer is not found on the Internet!

3- Instead of playing the role of holiness and saying useless words so that someone understands that you are a human being with personality and rule of law, help. If you can't help , suffocate!

**Comment by devinharrison8** [comment]
> BTW, you should give a more appropreate title. "Short Question" describes nothing, useless, not informative at all.
> 
> Imagine everyone create many issues with "A short question" and issue list are filled with "A short question". What inconvenient it is!

1- If you are not blind, you will see a short question in the first comment.

2- I have a problem, now tell me what to do, get help from a specialist? I don't know, say problem in forum? I did, but no one answered. Search the internet? I did and couldn't find an answer. Now here is the final place to raise my issue. Yes! It's inconvenient! that I don't know anyone to get help from. Yes, it is inconvenient when I raise the issue in the forum and no one answers. Yes, it is inconvenient when the answer is not found on the Internet!

3- Instead of playing the role of holiness and saying useless words so that someone understands that you are a human being with personality and rule of law, help. If you can't help , suffocate!

**Comment by metalefty** [comment]
Anyway, apologizes I didn't give you any helpful information. That's really my fault.

> Should I Create and Import Certificate to Use SSTP?

Yes. 

>If Yes Should I Create a Separate Certificate for Users

No. Certificate per domain name.

However what is the reason you persist not giving apropriate title to the issue?   I just adviced you to give the appropriate issue title because you repeated  "A Short Question" twice. Title is an important part in forum. 

I would say appropriate title will get people's attention and helps you to get helpful answer. Poor title will have less chance to get clicked. See other issues,  most people summarize their issue in its title.  It will help people to understand overview of the issue at first glance. Inappropriate title is one of the reason that your issue is not seen and you get no answer.

![コメント 2020-06-07 195436](https://user-images.githubusercontent.com/941609/83967255-bd555d00-a8fa-11ea-998b-b05dc0b0363b.png)

**Comment by devinharrison8** [comment]
> Anyway, apologizes I didn't give you any helpful information. That's really my fault.
> 
> > Should I Create and Import Certificate to Use SSTP?
> 
> Yes.
> 
> > If Yes Should I Create a Separate Certificate for Users
> 
> No. Certificate per domain name.
> 
> However what is the reason you persist not giving apropriate title to the issue? I just adviced you to give the appropriate issue title because you repeated "A Short Question" twice. Title is an important part in forum.
> 
> I would say appropriate title will get people's attention and helps you to get helpful answer. Poor title will have less chance to get clicked. See other issues, most people summarize their issue in its title. It will help people to understand overview of the issue at first glance. Inappropriate title is one of the reason that your issue is not seen and you get no answer.
> 
> ![コメント 2020-06-07 195436](https://user-images.githubusercontent.com/941609/83967255-bd555d00-a8fa-11ea-998b-b05dc0b0363b.png)

Your advice about choosing topic is reasonable and I will definitely remember it.

My intention was to be seen faster!
As I see it, there are a lot of issues and a lot of closed issues, I thought the repetitive issues were boring and no one was willing to answer.

Anyway, I apologize for the extremism and I hope you will explain more because I am still confused.

**Comment by devinharrison8** [comment]
The best way can help me is record a few minutes (or even a gif) video about configuring and connecting to SSTP on the Windows OS.

Top topics I need to know more: import the certificate correctly (However, I imported it and to make sure it was correct, I also saw some videos about import the certificate on YouTube, but because my problem is undedicating the certificate I prefer to focus more on it) and how to configure client for connecte and creating a certificate on the server.

**Comment by devinharrison8** [comment]
Even a picture guide is great enough!
