### ISSUE TITLE
It is normality to get DUP packet in ping by using vpn over dns mode ?

### ISSUE THREAD

**Issue by XiaoliChan** [SoftEtherVPN/SoftEtherVPN#1142]
Prerequisites

- [ √]  Can you reproduce?

- [ X]  Are you running the latest version of SoftEtherVPN?  

SoftEther version: 5.01.9672
Component: Server
Operating system: Windows 2008
Architecture: 64bit

Description

I always get DUP packet in ping by using linux client, it is normal ?

**Comment by davidebeatrici** [comment]
Should be the case only in ICMP mode.
