### ISSUE TITLE
Changing the encryption algorithm in server manager does not have any effect.

### ISSUE THREAD

**Issue by mKenfenheuer** [SoftEtherVPN/SoftEtherVPN#1143]
* [Yes] Can you reproduce?
* [Yes] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** SoftEther VPN Server (Ver 4.34, Build 9745, beta)
**Component:** Server + Client
**Operating system:** Server (Ubuntu 18.04) + Client (Windows 10 Build 1909 18363.836)
**Architecture:** [x86 64 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** Server (Digital Ocean droplet Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz) Client (Surface Book 2, Intel(R) i7-8650U)

### Description

Changing the encryption algorithm in server manager does not have any effect on client connections no matter what encryption algorithm is selected.

**Expected behavior:**
Changing the encryption algorithm in server manager will affect the encryption algorithm used by the clients. Shown in the connection status (e.g. AES128-SHA selected, Encryption Enabled (Algorithm: TLS_AES_128..... )

**Actual behavior:**
I can select any cipher provided, none have any effect on the used cipher. The connection info always shows TLS_AES_256_GCM_SHA384 as shown below:

Connection Info:
![image](https://user-images.githubusercontent.com/26744396/83978386-6ace6d80-a907-11ea-8bec-4fce01086ec8.png)

Server config:
![image](https://user-images.githubusercontent.com/26744396/83978428-ad904580-a907-11ea-9f08-3fab188dc7ba.png)

### Steps to reproduce

1. Install download and compile latest version of sothether vpnserver
2. Change the cipher to anything else than AES_256 
3. Connect from a client, display connection info.

**Comment by metalefty** [comment]
Here's the repository for SoftEtherVPN 5.x however I also reproduce this even with the reporter's version and 5.01.9674.

**Comment by davidebeatrici** [comment]
Superseded by #1197.
