### ISSUE TITLE
Connection Issues with Azure

### ISSUE THREAD

**Issue by devinharrison8** [SoftEtherVPN/SoftEtherVPN#1144]
When I Try to Connect SoftEther VPN  Server Via Azure Domain, After "_Verifying your sing in info_" I Get "**The PPP link control protocol was terminated**" Error.

But **softether.net** Domain Works Properly.

Protocol Used: **SSTP**

**Comment by metalefty** [comment]
I don't intend to bother you but please don't ignore the issue template.  Fill out the template to provide prerequisite information. If you provide such information from the beginning, we can reduce extra ping-pong of conversation.

Right now, we need to ask you about your client, server OS and version. That could be skipped if you provide such information from the beginning and I might be possible to provide one-shot answer to you.

**Comment by devinharrison8** [comment]
@metalefty ?

**Comment by domosekai** [comment]
Connections to *.softether.net are direct connections and those to *.vpnazure.net are relays.
I have the same issue (PPP termination) with vpnazure via SSTP. Softether native protocol does not have the issue.
And the failure is kind of random (not happening every time(. Since vpnazure is closed source, I can't dig further.

**Comment by devinharrison8** [comment]
> Connections to *.softether.net are direct connections and those to *.vpnazure.net are relays.
> I have the same issue (PPP termination) with vpnazure via SSTP. Softether native protocol does not have the issue.
> And the failure is kind of random (not happening every time(. Since vpnazure is closed source, I can't dig further.
> 
> Update: The issue does not arise if PAP is used as authentication method. When MSCHAPv2 is used, it randomly occurs.

Thank You Sir!
