### ISSUE TITLE
Remove OpenSSL < 1.1.1 compatibility layer(s)

### ISSUE THREAD

**Issue by davidebeatrici** [SoftEtherVPN/SoftEtherVPN#1147]
https://endoflife.software/applications/security-libraries/openssl

OpenSSL 1.0.2 is EOL since January, 1.1.0 since September 2018.

As discussed in #1113, we should remove all compatibility layer(s) and assume the machine SoftEther VPN is being built on has at least OpenSSL 1.1.1.

**Comment by chipitsine** [comment]
1.1.0 is EOL as well


but I wonder about openssl  versions shipped with modern Linux distributions, not 1.0.2 left ?

**Comment by davidebeatrici** [comment]
As far as I know all recent Linux distributions ship OpenSSL 1.1.1.

**Comment by chipitsine** [comment]
RHEL 7 ?

**Comment by davidebeatrici** [comment]
From https://access.redhat.com/solutions/2728111:

> **Issue**
> - I like to provide `HTTP/2` support for apache web server and need an updated `openssl` version.
> - When will `openssl` version 1.0.2 or 1.1.0 be available on Red Hat Enterprise Linux 7.x?
>
> **Resolution**
> - With the release of RHEL 7.4, `openssl` has been updated to version 1.0.2. Please update to this version by applying errata [RHBA-2017:1929](https://access.redhat.com/errata/RHBA-2017:1929)
> - An update to `openssl` 1.1.x, however, is unlikely due to ABI and API compatibility issues.

**Comment by chipitsine** [comment]
well, I do have RHEL7 where I work. we build our own openssl package, no problem at all.

I'm not sure whether it is a big deal to switch to custom built openssl or not

**Comment by chipitsine** [comment]
people usually are afraid of installing openssl because it messes with system openssl. in our travis-ci we use LD_LIBRARY_PATH for mangling with various locations of openssl, it is good for CI, but it is too aggressive for regular use.


what is good for regular use is rpath approach. people usually do not know about it.
so, what should we do

1. write an article (in github wiki ?) "how to build custom openssl and link against it" - I'll take care of it
2. change our CI to use rpath approach as well
3. check openssl version during cmake, if it is lower than 1.1.1, so point people to wiki


few questions

1. linux, freebsd do support rpath. not sure about other OSes
2. libressl ?

**Comment by chipitsine** [comment]
@metalefty , how are you dependent on libressl ? I recall you added a lot them to CI
also, nice thing about libressl that I recall is ability to detect memory leaks (it's more picky than openssl)

anyway, I'm fine with "if you have libressl, please install openssl-1.1.1" approach

**Comment by metalefty** [comment]
Actually I don't depend on LibreSSL but some FreeBSD users might depend on it. In FreeBSD, users can choose OpenSSL or LibreSSL for system SSL library. When users who choose LibreSSL want to use SoftEther, it will be compiled with LibreSSL. macOS is another example that uses LibreSSL.

[LibreSSL started to add OpenSSL 1.1 compatible API](https://marc.info/?l=openbsd-cvs&m=151862593422966&w=2). So I believe LibreSSL is (will be?) still a drop-in replacement of OpenSSL 1.1.

I would like to let users choose which LibreSSL or OpenSSL to use.

**Comment by metalefty** [comment]
BTW, it would be nice to add the feature to show SSL library version SoftEther compiled with.

I added this to xrdp because I wanted to know which is used to compile when multiple OpenSSL/LibreSSL are installed to the system.

```
$ xrdp -v
xrdp 0.9.13
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2018 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  (snip)

  Compiled with OpenSSL 1.1.1g  21 Apr 2020

**Comment by domosekai** [comment]
1.1.1 is our baseline now. Can we close this?

**Comment by chipitsine** [comment]
there're several leftovers with LibreSSL "ifdef"

ok, let's close the issue to clean backlog :)
