### ISSUE TITLE
IFLA_OPERSTATE of virtual NIC is always UNKNOWN

### ISSUE THREAD

**Issue by ronisaacson** [SoftEtherVPN/SoftEtherVPN#1150]
**SoftEther version:** 5.01.9674
**Component:** Client
**Operating system:** Ubuntu 18.04.4
**Architecture:** 32 bit

### Description

According to a comment in Cedar/Client.h, the NicDownOnDisconnect flag means: "Put NIC down on disconnect/connection loss and put it up again after connecting to VPN server."

In src/Cedar/VLanUnix.c, the up/down state is managed by UnixVLanSetState, which sets the interface flags using SIOCSIFFLAGS. This is good but it fails to set IFLA_OPERSTATE which remains UNKNOWN. See here:

```
%: ip a show vpn
7: vpn: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet xx.xx.xx.xx/24 brd xx.xx.xx.255 scope global vpn
       valid_lft forever preferred_lft forever
```

Notice where it says `state UNKNOWN` on the first line.

According to [this](https://www.kernel.org/doc/Documentation/networking/operstates.txt), UnixVLanSetState is only managing the _administrative_ state of the interface. IFLA_OPERSTATE should be set to IF_OPER_UP / IF_OPER_DOWN to reflect the _operational_ state.

**Expected behavior:**

The virtual NIC's interface state (IFLA_OPERSTATE value) should be either UP or DOWN.

**Actual behavior:**

The virtual NIC's interface state (IFLA_OPERSTATE value) is always UNKNOWN.

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue!

SoftEther VPN originally created the NIC in the `UP` state and never changed its state.
The behavior was changed in #337, which also added the `NicDownOnDisconnect` option; it's disabled by default for backwards compatibility with scripts that don't check whether the NIC is down, but it's not good practice in my opinion.

What are your thoughts about entirely removing the option, in addition to setting the proper value for `IFLA_OPERSTATE`?

**Comment by ronisaacson** [comment]
Personally, I'd be in favor of that. Forget the option (which isn't even documented, I just happened to find it in the config file) and have the interface state always reflect whether the VPN is up or down. This would certainly be the most logical behavior.

I started down this rabbit hole by trying to get NetworkManager to respond to the interface the same way it would respond to a physical interface, and automatically start/stop dhclient on connect/disconnect. It was never seeing the NIC as connected though, and I think this is why.

**Comment by davidebeatrici** [comment]
Yes, this is probably why.

**Comment by ronisaacson** [comment]
Well I managed to set the IFLA_OPERSTATE to UP using netlink (manually) but unfortunately NetworkManager still won't manage the connection. You can't activate it as Ethernet because NetworkManager tells you it's the wrong device type:

```
Error: device 'vpn' not compatible with connection 'vpn':The connection was not a tun connection..
```

And NetworkManager has basic support for TUN devices that it creates, but I don't think you can get it to adopt an existing TAP device. So this whole avenue appears to be a non-starter for now. I still think the other up/down changes would be good though.

For reference, here's a quick & dirty way to set IFLA_OPERSTATE, and it will indeed get `ip a` to show the interface as UP:

```
// Copied from https://stackoverflow.com/a/59173853

#include <stdio.h>
#include <string.h>
#include <net/if.h>
#include <sys/socket.h>
#include <linux/rtnetlink.h>
#include <linux/if.h>

#define IFACE_NAME "vpn"

int main(void) {
     int ret, nl_sock;
     char operstate = IF_OPER_UP;
     struct rtattr  *rta;
     struct {
          struct nlmsghdr nh;
          struct ifinfomsg  ifinfo;
          char   attrbuf[512];
     } req;

     nl_sock = socket(AF_NETLINK, SOCK_DGRAM, NETLINK_ROUTE);
     if(nl_sock < 0) {
          perror("socket():");
          return -1;
     }

     memset(&req, 0, sizeof req);
     req.nh.nlmsg_len   = NLMSG_LENGTH(sizeof(struct ifinfomsg));
     req.nh.nlmsg_flags = NLM_F_REQUEST;
     req.nh.nlmsg_type  = RTM_NEWLINK; // RTM_SETLINK
     req.ifinfo.ifi_family = AF_UNSPEC;
     req.ifinfo.ifi_index  = if_nametoindex(IFACE_NAME);
     if(!req.ifinfo.ifi_index) {
          perror("if_nametoindex():");
          return -1;
     }
     printf("%s index: %d\n", IFACE_NAME, req.ifinfo.ifi_index);

     rta = (struct rtattr *)(((char *) &req) + NLMSG_ALIGN(req.nh.nlmsg_len));
     rta->rta_type = IFLA_OPERSTATE;
     rta->rta_len = RTA_LENGTH(sizeof(char));
     req.nh.nlmsg_len = NLMSG_ALIGN(req.nh.nlmsg_len) + RTA_LENGTH(sizeof operstate);
     memcpy(RTA_DATA(rta), &operstate, sizeof operstate);

     ret = send(nl_sock, &req, req.nh.nlmsg_len, 0);
     if(ret < 0) {
          perror("send():");
          return -1;
     }

     return 0;
}
```

**Comment by ronisaacson** [comment]
UPDATE: sorry I spoke too soon. It turns out you CAN get NetworkManager to adopt an existing TAP device after all! I found the magic incantation [here](https://mail.gnome.org/archives/networkmanager-list/2016-January/msg00049.html). This is all it takes:

```
nmcli dev set vpn managed yes
nmcli connection add type tun ifname vpn con-name vpn mode tap
```

This works fine, even with IFLA_OPERSTATE still UNKNOWN. So to keep things clean, I'm going to close this ticket for now. I opened #1154 for just the NicDownOnDisconnect change discussed above.
