### ISSUE TITLE
Radius accounting [Request]

### ISSUE THREAD

**Issue by metallicats** [SoftEtherVPN/SoftEtherVPN#1151]
Hi, I would like to request Freeradius accounting to be supported by SoftEther. SE has an openvpn clone and openvpn has a radius plugin for years now. It would be great if this would be implemented in SE's openvpn clone or better yet to SE itself. 

Thanks!

**Comment by metalefty** [comment]
Dup of #101.

**Comment by chipitsine** [comment]
closing in favour of #101 
thank you, @metalefty
