### ISSUE TITLE
[Feature request] Provide separate vpnsmgr.exe

### ISSUE THREAD

**Issue by ingria** [SoftEtherVPN/SoftEtherVPN#1152]
It would be nice to have admin tools as dedicated .exe files, so that it's possible to launch them with Wine on desktop Linux systems.

AFAIK, since v4.29 admin tools are only available via installer (so they won't work on Linux).

**Comment by DRSDavidSoft** [comment]
If I may, the same thing would be appreciated for the client manager too (on macOS devices using Wine).  Currently, the [download page](https://www.softether-download.com/en.aspx?product=softether) offers only installable `.exe` files – So I'd need to use either a VM or a physical Windows machine to extract the `.exe` files.

I'd appreciate it if both the server and client manager were to be released as a `.zip` file for Wine usage.

**Comment by davidebeatrici** [comment]
Until 5.01.9674 we provided standalone (they only need `hamcore.se2` in the same directory) executables.

The reason why they're missing in 5.01.9674 (currently the latest release) is that Azure Pipelines was misconfigured at the time.

We're now revamping the entire release pipeline and will provide installers and `.zip` archives containing the various executables.

**Comment by domosekai** [comment]
No longer relevant.
