### ISSUE TITLE
Remove the NicDownOnDisconnect option

### ISSUE THREAD

**Issue by ronisaacson** [SoftEtherVPN/SoftEtherVPN#1154]
In the VPN client, it would be good to remove the (undocumented) NicDownOnDisconnect option, and always have the interface be up/down to mirror the state of the connection.

This replaces #1150 which turned out to be a red herring, but I still think this change is worthwhile.

**Comment by davidebeatrici** [comment]
Could you test #1157, please?

**Comment by ronisaacson** [comment]
Looks good! I built from your branch, tested and the NIC behavior was as expected. I tried an AccountDisconnect on the client, and also tried killing the VPN server. I also tried with/without StartupAccount=true. In all cases, when disconnected:

```
192: vpn: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
```

And when connected:

```
192: vpn: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
```

I think you're good to merge. Thank you for this!

**Comment by davidebeatrici** [comment]
Merged, thank you very much for testing!
