### ISSUE TITLE
Fix three issues when building RPM packages

### ISSUE THREAD

**Issue by ronisaacson** [SoftEtherVPN/SoftEtherVPN#1158]
There are three issues with the current RPM packages generated by `make -C tmp package`:

1. The build fails at this step due to an invalid rpath setting:

```
+ /usr/lib/rpm/check-rpaths
*******************************************************************************
*
* WARNING: 'check-rpaths' detected a broken RPATH and will cause 'rpmbuild'
*          to fail.
[...]
*******************************************************************************
ERROR   0002: file '/usr/local/lib64/libcedar.so' contains an invalid rpath '/usr/local/lib64' in [/usr/local/lib64]
ERROR   0002: file '/usr/local/lib64/libmayaqua.so' contains an invalid rpath '/usr/local/lib64' in [/usr/local/lib64]
```

2. Installation of the generated RPM fails on Fedora because /lib is a symlink to /usr/lib, but it's in the RPM as a directory:

```
file /lib from install of softether-vpnserver-5.1.9674-1.x86_64 conflicts with file from package filesystem-3.12-2.fc31.x86_64
```

3. CMake defaults to installing in /usr/local. This should be /usr. See https://www.tldp.org/HOWTO/HighQuality-Apps-HOWTO/fhs.html and the underlying FHS for further discussion.

A PR for all three of these is coming momentarily.

**Comment by ronisaacson** [comment]
Upon further research: #⁠1 is a known issue in CPack ([see here](https://stackoverflow.com/questions/40096753/cpack-adds-system-directories-to-generated-rpm) among many other reports). I'm using a much newer version of CMake, but it appears their "solution" was just to allow you to specify more directories in CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST. I'll make this more comprehensive.

And for #⁠3, /usr/local is correct when doing make install. It's only the RPM that should use /usr.

I'll update and resubmit.

**Comment by chipitsine** [comment]
I played a bit with CPack. I found it pretty flexible on one hand. However, we cannot easily use it together with Fedora COPR

**Comment by ronisaacson** [comment]
Have you tried using CPACK_RPM_PACKAGE_SOURCES to generate a src.rpm? In theory, you should then be able to upload that to COPR. This is a little outside of the scope but I can take a look at that as well.

**Comment by chipitsine** [comment]
well, I think at least major RPM distributions (which are served by COPR) would be good to have on yum/dnf level. 

it is not that useful to be able to build RPM by people themselves, just because if they build, they can build from source code.

**Comment by ronisaacson** [comment]
This is how I always do it, incidentally, when installing either the server or client on a new machine. Clone from github, follow the [build instructions](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/BUILD_UNIX.md), but as the last step, do `make -C tmp package` instead of `make -C tmp install`. Then install the generated package.

This has SO many advantages. The idea of using `make install` to put stuff in /usr/local really should have gone out with the '90s.

**Comment by chipitsine** [comment]
I understand advantages of using packages :)
