### ISSUE TITLE
High load test bottlenecks

### ISSUE THREAD

**Issue by mproper** [SoftEtherVPN/SoftEtherVPN#116]
Hi, dear author.
We internally benchamarked  SoftEtherVPN solution and it looks like it does not capable running more 1000 sessions from 1 hub. Acting like  VPN concentrator. What number of sessions max your product supports, and what are they ways to increase number of VPN sessions per host.

We used 2 processors Xeon machine with 12 cores per socket. and 64 GB of RAM.

CPU` usage stays max on 30% and memory is never usage reaching 30 GB hover more then 1K of sessions(with minimal load), new users was unable to connect. Note we was using your product with OpenVPN clients using openvpn protocol. Same results was if switched to L2TP via softEther.

**Comment by Gramler** [comment]
The suggested configuration above set  DisableIPParsing to true
Is there any good info available on how filters are impacted by this.
The documentation on this is extremely vague, only implying that they will work "less well"

**Comment by domosekai** [comment]
Close due to inactivity.
