### ISSUE TITLE
IPv6 traffic doesn't go through VPN if client is IPv6 reachable

### ISSUE THREAD

**Issue by metalefty** [SoftEtherVPN/SoftEtherVPN#1163]
# Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** 5.01. 9674 (both server and client)
**Component:** Client
**Operating system:** Windows 10 2004 build 19041.329
**Architecture:** 64bit

### Description

**Prerequisites:** The client network is IPv6 reachable, the VPN server has a virtual hub bridged to dual-stack network.

IPv6 traffic doesn't go thru VPN in a such condition. 

**Expected behavior:**
Both IPv4/IPv6 traffic goes thru the VPN.

**Actual behavior:**
Only IPv4 traffic goes thru the VPN. IPv6 traffic goes out directly. 

### Steps to reproduce

1. Setup a virtual hub bridged to dual-stack network
2. Confirm also the client is IPv6 reachable
3. Connect to the virtual hub
4. Access https://inonius.net/ for example to know the client's IP addresses.

### Result 

The client has dual-stack internet connection with NTT Communications.
The server has dual-stack internet connection with Asahi Net.

After VPN connection established, the below figure shows IPv4 traffic goes thru the VPN however IPv6 traffic goes directly.

![inonius](https://user-images.githubusercontent.com/941609/86318709-a55cc900-bc6d-11ea-85bd-d5fb802baa6c.png)

**Comment by metalefty** [comment]
```
IPv4 ルート テーブル
===========================================================================
アクティブ ルート:
ネットワーク宛先        ネットマスク          ゲートウェイ       インターフェイス  メトリック
          0.0.0.0          0.0.0.0    192.168.100.1    192.168.100.2     25
          0.0.0.0          0.0.0.0     192.168.24.1   192.168.24.110      2
        127.0.0.0        255.0.0.0            リンク上         127.0.0.1    331
        127.0.0.1  255.255.255.255            リンク上         127.0.0.1    331
  127.255.255.255  255.255.255.255            リンク上         127.0.0.1    331
     172.18.224.0    255.255.240.0            リンク上      172.18.224.1    271
     172.18.224.1  255.255.255.255            リンク上      172.18.224.1    271
   172.18.239.255  255.255.255.255            リンク上      172.18.224.1    271
     192.168.24.0    255.255.255.0            リンク上    192.168.24.110    257
   192.168.24.110  255.255.255.255            リンク上    192.168.24.110    257
   192.168.24.255  255.255.255.255            リンク上    192.168.24.110    257
    192.168.100.0    255.255.255.0            リンク上     192.168.100.2    281
    192.168.100.2  255.255.255.255            リンク上     192.168.100.2    281
  192.168.100.255  255.255.255.255            リンク上     192.168.100.2    281
        224.0.0.0        240.0.0.0            リンク上         127.0.0.1    331
        224.0.0.0        240.0.0.0            リンク上    192.168.24.110    257
        224.0.0.0        240.0.0.0            リンク上     192.168.100.2    281
        224.0.0.0        240.0.0.0            リンク上      172.18.224.1    271
  255.255.255.255  255.255.255.255            リンク上         127.0.0.1    331
  255.255.255.255  255.255.255.255            リンク上    192.168.24.110    257
  255.255.255.255  255.255.255.255            リンク上     192.168.100.2    281
  255.255.255.255  255.255.255.255            リンク上      172.18.224.1    271
===========================================================================
```

**Comment by domosekai** [comment]
This is a feature, not a bug, controlled by a hub option `NoIPv6DefaultRouterInRAWhenIPv6`.
However I do think this feature is outdated.
https://forum.vpngate.net/viewtopic.php?t=8249

**Comment by davidebeatrici** [comment]
Feel free to create a pull request to remove it.

**Comment by davidebeatrici** [comment]
> If you set this option to non-zero value, then all VPN Sessions on the Virtual Hub will have the enabled "No Default-Router on IPv6 RA (physical IPv6)" security policy. When the physical communication protocol between VPN Client / VPN Bridge and VPN Server is IPv6, any IPv6 RA (Router Advertisement) packet with non-zero value in the router-lifetime will set to zero-value. This is effective to avoid the horrible behavior from the IPv6 routing confusion which is caused by the VPN client's attempts to use the remote-side IPv6 router as its local IPv6 router.

**Comment by domosekai** [comment]
Yeah I know the official explanation. But what makes me confused is that the situation is the same in IPv4, isn't it? Why using remote-side IPv6 router is "horrible" but using IPv4 default gateway is not?

**Comment by davidebeatrici** [comment]
I asked @dnobori.

Turns out the issue the option works around is the VPN client currently only enforcing the gateway for IPv4.

Disabling the option causes local IPv6 routers to compete with the VPN server's one, meaning that there's no guarantee that the internet traffic is routed through the VPN.

**Comment by domosekai** [comment]
I am sorry but I still can’t get it. If the client fails to add default gateway for IPv6 we should fix the client instead of disabling the router on the server side.

**Comment by davidebeatrici** [comment]
Absolutely.

**Comment by domosekai** [comment]
I sort of understand why this option is needed.
In Linux, when a default IPv4 route is present, you can't add another one so remote router provided by DHCP will not conflict with the local router.
But in IPv6, since IPv6 ND is a kernel function (unlike DHCP), if a remote router is announced by RA the default route is always added, leading to routing loop. It can be solved by manually adding route to server's IPv6 address.

**Comment by davidebeatrici** [comment]
Correct. It would be great to automatize that though.

**Comment by domosekai** [comment]
And for Windows client, we currently only add route to server address in IPv4. But since Windows does not reroute established connection, we are fine (at least for a period of time) even after a second IPv6 default route is added.
It will be better if we can refactor `Win32AddRouteEntry()` to handle both IPv4 and IPv6 routes. I have zero Win32 experience but it seems we should use `CreateIpForwardEntry2()` instead of `CreateIpForwardEntry()`, and use `MIB_IPFORWARD_ROW2` struct to hold route entries.  It's available since Vista.

**Comment by davidebeatrici** [comment]
Also, now that our baseline is Vista, we can do that without the need for a fallback.
