### ISSUE TITLE
A proof: suffering MITM (Man-in-the-middle) because of self-signed certificate

### ISSUE THREAD

**Issue by 0x391F** [SoftEtherVPN/SoftEtherVPN#1165]
As what I said in #1027 , it's extremely easy to suffer MITM when using self-signed certificate. recently I noticed and proofed the exist of it, almost EVERYTIME - Yes, EVERYTIME when I connected to VPN Gate Public VPN Relay Servers. Here are the screenshoots I saved. It's unbelievable they're coincidence that 3 servers in different IP use the SAME certificate with SAME Public key. 

![1](https://user-images.githubusercontent.com/56181919/86463552-4deb5580-bd60-11ea-87de-1cc67cd246bd.png)
![2](https://user-images.githubusercontent.com/56181919/86463554-4f1c8280-bd60-11ea-8424-dc856b2176c1.png)
![3](https://user-images.githubusercontent.com/56181919/86463557-504daf80-bd60-11ea-855b-3a5ce8aa7dfa.png)

It's unbelieveable they're coincidence that 3 servers in different IP use the SAME certificate with SAME Public key. Yes, user could specify the server certificate from "VPN Connection Settings" on client when they connect to a server which is operated by himself or company, but when user connect to a public VPN relay server, how could user do this? 

It's very, very important that VPN Gate Public VPN Relay Servers do not use the self-signed certificate. Nowadays, here're some CA, such as Let's Encrypted  provide free certificate, money is no object.

**Comment by chipitsine** [comment]
I know that feeling.
but this project is not related to VPN Gate

**Comment by metalefty** [comment]
As chipitsine says, this project is not related to VPN Gate. VPN Gate is academic research and experiment.  The biggest topic of the research is to get through the government's firewall. Security is not the prior topic of the research.

From a different perspective, the VPN Gate traffic is relayed through volunteers' public relay servers. Even if there's no MITM between VPN Gate users and public relay servers, however, volunteers are still in the middle of you and the final destination server.  Why can you rely on volunteers? Volunteers might behave evilly.

Using CA-signed certificates can protect traffic between users and volunteer servers (path A).  However, volunteers are still able to peep into traffic between A and B.  So not using self-signed certificates does not contribute to eliminating MITMs between the whole communication path.

```
[VPN Gate users] ----A---- [ VPN Gate volunteer server] ----B---- [Final destination server]
```

You cannot see the wood for the trees.

**Comment by metalefty** [comment]
Anyway, any suggestions on VPN Gate Project should be sent to VPN Gate Project, not SoftEther Project.
https://www.vpngate.net/en/about_abuse.aspx

**Comment by claw6148** [comment]
i tried some servers on VPNGate, it seems that most servers are exactly using the same cert and private key for the wildcard domain ***.opengw.net** and it's NOT self-signed. it probably embedded in software binary or obtained from somewhere centrally.

here's the chain
![opengw-chain](https://user-images.githubusercontent.com/20199668/87222174-48b38980-c3a4-11ea-818f-832ea9fb7cb5.png)

MITM risk still exists as this protected cert and private key can be exported from VPNGate-shipped(official) SEVPN after some patches.
![opengw-cert](https://user-images.githubusercontent.com/20199668/87222176-4ea96a80-c3a4-11ea-9dc3-ead34588f00c.png)

as @metalefty 's said, volunteer may be this "MAN" in the middle.
