### ISSUE TITLE
/usr/local/libexec/softether/vpnserver/vpnserver: error while loading shared libraries: libcedar.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by boubou** [SoftEtherVPN/SoftEtherVPN#1167]
Hi
This 2 issues seem not fixed with the latest git.
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/766
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/767

I used the latest git, ./configure, make -C tmp, cd tmp/, make install.
/usr/local/libexec/softether/vpnserver/vpnserver: error while loading shared libraries: libcedar.so: cannot open shared object file: No such file or directory

Can you fix it asap plz ?

**Comment by chipitsine** [comment]
can you please provide step by step repro ?

**Comment by chipitsine** [comment]
nevermind, I reproduced on debian 10

**Comment by amastelek** [comment]
I have the same problem while trying to build on buster.

**Comment by Tomon613** [comment]
I have install this  to /usr/local/git, and libcedar.so was isntall /usr/local/git/lib, built with cmake option " -DCMAKE_INSTALL_PREFIX=/usr/local/git" on FreeBSD 11.
But vpncmd says 'Shred object "libcedar.so" not found, recuired by "vpncmd" ', vpncmd cannot find /usr/local/git/lib. Also, my FreeBSD system doesn't have /usr/local/lib directory. 
How can I fix it?

**Comment by Tomon613** [comment]
I have fixed it with  Fixes SoftEtherVPN#766  . Thanks.
