### ISSUE TITLE
Funding information

### ISSUE THREAD

**Issue by paulmenzel** [SoftEtherVPN/SoftEtherVPN#1172]
I found `FUNDING.yml`, but accessing the URL in there does not work, and I couldn’t see anything on the GitHub project page.

**Comment by davidebeatrici** [comment]
![](https://user-images.githubusercontent.com/5897523/87438086-6294dc80-c5ef-11ea-93d8-d7b4c5d56d74.png)

Click on the `Sponsor` button.

**Comment by paulmenzel** [comment]
Thank you for clearing that up. Having a section in the `README.md` might be a good idea nevertheless.

**Comment by davidebeatrici** [comment]
I agree.
