### ISSUE TITLE
Feature Request: Dynamic Outbound IP Routing

### ISSUE THREAD

**Issue by Elikster** [SoftEtherVPN/SoftEtherVPN#118]
I would like to add the option to add dynamic outbound IP routing assigned to the server for the VPN clients.  Let say that the server have 24 IPs assigned to the server for use, and I would like to dynamically assign a pool of IPs to users that it randomly uses the IP for VPN Outbound traffic to the Internet.

Right now, it is only set to use only one IP and rather like to have option to use a range of IPs available for use.

**Comment by moatazelmasry2** [comment]
Sorry I think this is a very specific use case. Or I may have not understood this feature.

**Comment by domosekai** [comment]
This is something that should be done in the server OS / firewall (SNAT) rather than in SE.
