### ISSUE TITLE
Very strange network connection problem with bind network

### ISSUE THREAD

**Issue by scegg** [SoftEtherVPN/SoftEtherVPN#1181]
## Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

Server with vpn server, version SoftEther VPN 4.34 Build 9745 RTM x64, on Windows Server 2012 R2.
A1 and A2 are Raspberry Pi 4 (4G mem), SoftEther is pulled here yesterday and built by the same device, on Ubuntu Server ARM64 20.04 and latest patches. Both A1 and A2 have a USB NIC.
Hub is created on server.
Both A1 and A2 have a local hub, and connect the hub to the server using cascade connection.
Both A1 and A2 bind the local hub to the eth0 (the physical nic built in Raspberry Pi 4).
Computer B1 is connected to A1 through the eth0. Computer B2 is connected to the A2 through the eth0.
IP are set static in B1 and B2.

Now, in the vpn server, I can see both B1 and B2 ip address listed in manager.
In B1 and B2 (Windows 10), the other one is visible through arp -a.
BUT: B1 and B2 cannot ping to each other.

The workaround is: Add a loopback device on the server, bind it to the hub, assign an IP address in the same subnet on the loopback device, and ping to one IP (B1 or B2) from the server. After that, B1 and B2 can ping to each other.

If B1 and B2 changed to another IP subnet, the server need to assign a new IP in the same subnet and ping once again, or it still fails in ping test.

**Comment by scegg** [comment]
happened again on another solution with one client in raspberry pi and another in windows.

**Comment by domosekai** [comment]
I have read multiple times and I still don't understand your issue. Please describe it clearly, with screenshots and illustrations.

**Comment by scegg** [comment]
Too late. Problem solved by changing server to linux.
