### ISSUE TITLE
disable multiple logins for same user for openvpn client is not working at all 

### ISSUE THREAD

**Issue by codesiddhant** [SoftEtherVPN/SoftEtherVPN#1183]
* [ ] Can you reproduce? 
* [x] Are you running the latest version of SoftEtherVPN? yes

**SoftEther version:** latest
**Component:** [Server, Client, Bridge, etc.]
**Operating system:** ubuntu 20.04 docker image (https://hub.docker.com/r/siomiz/softethervpn/)
**Architecture:** [64 bit] 

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** vmware over inter corei3 3rd gen

### Description

[Description of the bug]

**Expected behavior:**
want to restrict multiple login for a single user while using openvpn client

**Actual behavior:**
multiple logins for same user for openvpn client is not working at all but softether vpn client works fine

**Comment by shakibamoshiri** [comment]
Hi @codesiddhant 
Please specify the exact version, e.g. 

```
SoftEther VPN Command Line Management Utility (vpncmd command)
Version 4.41 Build 9782   (English)
Compiled 2022/11/17 16:36:25 by buildsan at crosswin with OpenSSL 3.0.7
Copyright (c) 2012-2022 SoftEther VPN Project. All Rights Reserved.
```

Plus this features weeks, when you connect from different networks, I think (not sure, but guess) when the source IP is the same (e.g. some people connecting through a wifi) it does not work and makes sense why not.

I have tested this feature with 
- SSTP
- L2TP
- OpenVPN
I has worked fine.

**Comment by domosekai** [comment]
For protocols other than the native SoftEther protocol, the uniqueness is determined by the client's IP. Clients from the same IP are regarded the same session.
