### ISSUE TITLE
Debian Buster 10.4 to 10.5 causes protocol error

### ISSUE THREAD

**Issue by amastelek** [SoftEtherVPN/SoftEtherVPN#1193]
Upgrade on debian buster from 10.4 to 10.5 results in client reporting protocol error when connecting to server.

Accessing via web browser to management port reports SSL_ERROR_NO_CYPHER_OVERLAP

Failed on current release and previous release.

I have moved the VPN back onto stable in the mean time.

**Comment by davidebeatrici** [comment]
What browser are you using? Version?

**Comment by amastelek** [comment]
Firefox



*From:* Davide Beatrici <notifications@github.com>
*Sent:* Monday, 10 August 2020 23:50
*To:* SoftEtherVPN/SoftEtherVPN <SoftEtherVPN@noreply.github.com>
*Cc:* amastelek <ronald@amastelek.com>; Author <author@noreply.github.com>
*Subject:* Re: [SoftEtherVPN/SoftEtherVPN] Debian Buster 10.4 to 10.5
causes protocol error (#1193)



What browser are you using? Version?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1193#issuecomment-671607494>,
or unsubscribe

**Comment by davidebeatrici** [comment]
Version?

**Comment by amastelek** [comment]
Figured out the problem.
/usr/local/lib/libcedar.so and
/usr/local/lib/libmayaqua.so
should be in /usr/lib
If you have an old build of SoftEther and re-install then the older versions of those files are used causing the problem.
The build on the latest debian buster does not install those files correctly as a generic problem!
