### ISSUE TITLE
CMake does not build the project using Clang on Windows

### ISSUE THREAD

**Issue by flriancu** [SoftEtherVPN/SoftEtherVPN#1194]
* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**Operating system:** Windows 10 version 2004
**CMake version:** 3.18.1

### Description

CMake does not build the project using Clang on Windows. Taking a cursory look in the source code, I think the needed modifications are not massive. I would make them myself, but I think it's best the developers do it instead, as they know the code better.

### Steps to reproduce

1. install Make for Windows and add it to `%PATH%`
    - manually
    - or, with Chocolatey via `choco install make`
2. install Clang for Windows and add it to `%PATH%`
    - manually from the [project website](https://releases.llvm.org/download.html)
    - or, with Chocolatey via `choco install llvm`
3. in the SoftEther root directory, from a `cmd` terminal:
```
mkdir build && cd build
cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_MAKE_PROGRAM:FILEPATH=make -G "Unix Makefiles"
```

### Actual behavior

```
[  1%] Building C object src/Mayaqua/CMakeFiles/mayaqua.dir/Microsoft.c.obj
In file included from C:/Users/flria/Desktop/github/SoftEtherVPN/src/Mayaqua/Microsoft.c:64:
In file included from C:/Users/flria/Desktop/github/SoftEtherVPN/src/.\Mayaqua/Mayaqua.h:231:
C:/Users/flria/Desktop/github/SoftEtherVPN/src/.\Mayaqua/MayaType.h:211:23: error: typedef redefinition with different
      types ('signed char' vs 'char')
typedef signed char                     CHAR;
                                        ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h:450:14: note: previous definition is here
typedef char CHAR;
             ^
```

**Comment by chipitsine** [comment]
thank for the report!

**Comment by davidebeatrici** [comment]
Thank you very much for your report!

The error was fixed in #1195, however I reopened the issue because the build still doesn't succeed.

**Comment by davidebeatrici** [comment]
@flriancu You should now be able to build with Clang without any issues (aside from the plethora of warnings that we have to fix).

Please note that you'll probably want to use `clang-cl`, due to the "normal" version ignoring `.manifest` files; this results in the GUI tools having the classic look and `vpndrvinst` not working unless manually executed as administrator.

**Comment by flriancu** [comment]
Thanks! If I have some time on my hands maybe I'll make a PR for the warnings.

**Comment by davidebeatrici** [comment]
No problem, that would be great!
