### ISSUE TITLE
Cancel the data compression function and its option

### ISSUE THREAD

**Issue by 0x391F** [SoftEtherVPN/SoftEtherVPN#1199]
Should never use data compression whatever any protocol, because it had cause CRIME and BREACH attacks in SSL. These attack maybe exist in other protocols.

**Comment by metalefty** [comment]
If you don't want to use data compression, just don't use it. I think it up to users. Users can take a risk. Users who understand and the risk and data compression is worth more than the risk, the users should be able to use data compression. 

In the end, it's the user's decision.
