### ISSUE TITLE
AdminLTE for HTML5 server manager frontend?

### ISSUE THREAD

**Issue by andrewfer000** [SoftEtherVPN/SoftEtherVPN#1202]
Hi, I had some suggestions for the SE HTML5 server manager. I know this is a WIP at the moment and I do not know if any recent work was done on it so I'd thought I'll just share some suggestions to make development go faster.

If the fronted is holding you back from developing the HTML5 server manager then try out [AdminLTE](https://github.com/ColorlibHQ/AdminLTE). This way you can focus on the back-end stuff and not waste time on making the interface work. Also like the SE client it would be nice if users can login on any device and change their password or view/change other information such as device limits or bandwidth use. It can also be made so users can use the web interface to manage their WireGuard keys as mentioned in the post I made in the WireGuard discussion. 
Currently the only real features I feel like are missing from SE now is a HTML5 manager and some DHCP related features such as per-user static IPs/IP ranges and better IPv6 support (without having to setup a DHCPv6 server)
Also, I may be able to help with the HTML5 server manager development. Just let me know where you keep the current files for it and I'll take a look. Also I see you added a Sponsor button so I'll be checking that out too :)

**Comment by davidebeatrici** [comment]
Thank you very much!

I was aware of AdminLTE, but never tried it. The GUI is indeed the main reason why the web manager is considered "WIP".

All files for the interface are in `src/bin/hamcore/wwwroot/admin`, let me know whether you have any questions!

**Comment by andrewfer000** [comment]
@davidebeatrici Does the web interface support PHP in any way? Would you be able to add support for PHP in any way? While AdminLTE does not require PHP I am just curious if it could.

**Comment by davidebeatrici** [comment]
Anything that runs client-side can be used.

Running server-side stuff (e.g. PHP code) is not possible right now, because the web server is pretty basic.
