### ISSUE TITLE
SoftEther server from AWS Marketplace on centos looking up DNS for potentially malicious url

### ISSUE THREAD

**Issue by arrkaye** [SoftEtherVPN/SoftEtherVPN#1203]
Hi,

We have been running SoftEther server for a while now, installed from the AWS Marketplace. Ver 4.20, Build 9608, Intel x64 / AMD64

Last week we got an alert from AWS GuardDuty to say that the server was making DNS requests to a known malicious URL. The AWS alert was for Trojan:EC2/DropPoint!DNS.

The URL appears to be: **standard.t-0001.t-msedge.net**

We are not using the Azure DNS feature.

Does anyone have any idea what this request is and why it is being made?

Many thanks,
Ark

**Comment by davidebeatrici** [comment]
Hi,

[VPN Azure](https://www.vpnazure.net) is not related to the Azure services provided by Microsoft.

`msedge.net` appears to be owned by Microsoft Corporation (AS8068).

It's very possible that the requests are being made by a VPN client that is connected to the server.
