### ISSUE TITLE
OpenVPN cannot get correct IPv4 Address in L2 mode

### ISSUE THREAD

**Issue by codingm0nkey** [SoftEtherVPN/SoftEtherVPN#1204]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [Y ] Can you reproduce?
* [ Y] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**  git-490fc7b
**Component:** Server
**Operating system:** Linux
**Architecture:**64bit

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:**  E5-2680v3

### Description
I use OpenVPN Client in Google play which support Tap mode.

In src/Cedar/Proto_OpenVPN.c Line 2489
`StrCat(option_str, sizeof(option_str), ",ifconfig 192.0.0.8 255.255.255.240");`
This will make OpenVPN Client cannot get correct IPv4 address, the IP and gateway should get from DHCP. Otherwise, the client will get 192.0.0.8 only not real IP.
BTW,IPv6 do not have such problem, the client can get correct IPv6 address , and in stable version the OpenVPN works without this bug.
For push such address ,will stop Client to send DHCP request.
I think we should Modify this line, push IP via DHCP, if cannot get DHCP address push this address, or , If possible detect OpenVPN client to determine whether push such address or not.

**Expected behavior:**

It can get correct ipv4 address Connect  by using OpenVPN Client in L2 mode.

**Actual behavior:**
[What actually happened]
Connect  by using OpenVPN Client in L2 mode can get 192.0.0.8 only

### Steps to reproduce

download OpenVPN client in Google play store
connect Softether server by using L2 profile

**Comment by davidebeatrici** [comment]
See #828.
