### ISSUE TITLE
Softether assigned 1.0.0.1 to L2TP Client,How to get the real IP by L2TP?

### ISSUE THREAD

**Issue by fitnig** [SoftEtherVPN/SoftEtherVPN#1207]
I found this question in issues,which was closed,but this problem did not solve now.
So,how to get the real ip in l2tp?not the dummy value?BTW,reopen closed issue?

**Comment by davidebeatrici** [comment]
It was fixed in #524.

What version of the server are you using?

**Comment by fitnig** [comment]
#524 is useless.because ros need the real ip ,not 1.0.0.1,also not 192.0.0.8,real only.
as for version,cloned lastest version from git yestday.

**Comment by fitnig** [comment]
client is ros 6.46.3 and 6.47，cpu is mips .

**Comment by metalefty** [comment]
Can you show the output of `ifconfig`?

**Comment by metalefty** [comment]
Both `1.0.0.1` and `192.0.0.8` are pseudo peer's IP address but not the interface address. So you don't need to worry about that.

**Comment by fitnig** [comment]
This is ros interface status,i can not get ifconfig because of no shell.
![image](https://user-images.githubusercontent.com/34291200/92341726-2a8eaf00-f0f1-11ea-95e2-3a0b5472a380.png)

**Comment by metalefty** [comment]
The IP address `1.0.0.1` is NOT the one assigned to the CLIENT but L2TP peer. 

So your issue 

> Softether assigned 1.0.0.1 to L2TP Client

doesn't exist. SoftEther never assign `1.0.0.1` to L2TP client. No worries, it's fine.

**Comment by fitnig** [comment]
but，how to get the real ip?just like 192.168.30.1?

**Comment by isharrrry** [comment]
Local Address

**Comment by domosekai** [comment]
1.0.0.1 is the address of the PPP peer. It's just a requirement of the PPP protocol and is not used anywhere.
The client knows the address of the server via DHCP.
