### ISSUE TITLE
PPTP Support

### ISSUE THREAD

**Issue by cdemi** [SoftEtherVPN/SoftEtherVPN#121]
Please start supporting the PPTP protocol. Some networks have very weird firewall restrictions and PPTP will nearly always work. Apart from that many mobile OSes have native support for PPTP

**Comment by Cattze2015** [comment]
PPTP is cracked by NSA, and also encryption algo is already destroyed by Microsoft. Don't use PPTP.

**Comment by cdemi** [comment]
Yes, it is common knowledge that PPTP is cracked and destroyed but it is also common knowledge that it is the most widely implemented VPN protocol. 

Not everybody needs military grade encryption

**Comment by meganerd** [comment]
If there is no security advantage in using it, then there is no advantage
in increasing the complexity of any security related package by trying to
include pptp or l2tp.

If you want a PPTP based server, there are already projects to that.
