### ISSUE TITLE
Change NAS-Identifier

### ISSUE THREAD

**Issue by metallicats** [SoftEtherVPN/SoftEtherVPN#1213]
HI, it seems like SoftEther is sending "SoftEther VPN Server" as its NAS-Identifier when authenticating via RADIUS.

How can this be changed? I've checked the config and can't seem to find this variable.

Thanks!

**Comment by davidebeatrici** [comment]
Hi, `UseHubNameAsRadiusNasId` allows to set the hub name as NAS ID.

**Comment by metallicats** [comment]
Thanks davidebeatrici, never knew this option existed. Cheers!

**Comment by davidebeatrici** [comment]
You're welcome!

**Comment by metalefty** [comment]
This also helped me, thanks.
