### ISSUE TITLE
Select encryption algorithm for TLS

### ISSUE THREAD

**Issue by scegg** [SoftEtherVPN/SoftEtherVPN#1217]
* [*] Can you reproduce?
* [*] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** 5.0.1.9674
**Component:** Server, Client
**Operating system:** Ubuntu Server 20.04
**Architecture:** 64 bit

### Description
TLS_AES_256_GCM_SHA384 is always selected as encryption algorithm.

**Expected behavior:**
Use the algorithm selected by server configuration.

**Actual behavior:**
TLS_AES_256_GCM_SHA384 is always selected.

### Steps to reproduce

1. Create a server, select an encryption algorithm.
2. Use client to connect this server.
3. Check the log file on the server side.

**Comment by metalefty** [comment]
It reproduces for me, too.

**Comment by davidebeatrici** [comment]
Any thoughts about dropping the option and letting the TLS library negotiate the best cipher?

**Comment by davidebeatrici** [comment]
Superseded by #1197.
