### ISSUE TITLE
VPN adapter metric is not guaranteed to be below that of regular adapters

### ISSUE THREAD

**Issue by AyrA** [SoftEtherVPN/SoftEtherVPN#1219]
### Prerequisites

* [X] Can you reproduce? **Yes (on one machine only)**
* [x] Are you running the latest version of SoftEtherVPN? **Yes**

**SoftEther version:**
**Component:** Client (Build 9674)
**Operating system:** Windows 10 (10.0.18363.1082)
**Architecture:** 64 bit

**Processor:** Intel64 Family 6 Model 60 Stepping 3

### Description

The VPN adapter is not prioritized in Windows. The priority (metric) is left for windows to decide. This means Windows can prefer the LAN adapter over the VPN adapter for conflicting routes.

**Expected behavior:**

When a VPN connection is made, the routes pushed by the adapter to the system should be the preferred routes.

**Actual behavior:**

Currently the metric is decided by Windows. On this machine I'm writing this message, LAN routes have a metric of 25 and VPN routes a metric of 35, meaning Windows will prefer the LAN routes over the VPN routes.

Example routing table (`10.13.37.x` is the VPN network, `192.168.30.x` is the regular LAN network, `192.168.1.x` is a network that has been pushed via SecureNAT rule):

```
IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0     192.168.30.1    192.168.30.50     25
          0.0.0.0          0.0.0.0       10.13.37.1      10.13.37.11     35
       10.13.37.0    255.255.255.0         On-link       10.13.37.11    291
      10.13.37.11  255.255.255.255         On-link       10.13.37.11    291
     10.13.37.255  255.255.255.255         On-link       10.13.37.11    291
    46.140.111.89  255.255.255.255     192.168.30.1    192.168.30.50     25
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
      192.168.1.0    255.255.255.0       10.13.37.1      10.13.37.11     36
     192.168.30.0    255.255.255.0         On-link     192.168.30.50    281
    192.168.30.50  255.255.255.255         On-link     192.168.30.50    281
   192.168.30.255  255.255.255.255         On-link     192.168.30.50    281
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link     192.168.30.50    281
        224.0.0.0        240.0.0.0         On-link       10.13.37.11    291
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link     192.168.30.50    281
  255.255.255.255  255.255.255.255         On-link       10.13.37.11    291
===========================================================================
```

### Fix

LAN adapters in Windows support a value called "metric". This can be set to 1 for the VPN adapter to make it the preferred choice for routing. The client should do this when a VPN adapter is created or a VPN connection is made. This needs to be done twice, once for IPv4 and once for IPv6.

![image](https://user-images.githubusercontent.com/1301960/94145215-7b810000-fe72-11ea-9e45-5574fe401a28.png)

**Comment by domosekai** [comment]
Interface metric is actually set to 1 in the registry. It just needs a reboot to take effect.

**Comment by AyrA** [comment]
The metric can be reset by windows if it runs network diagnostics. The VPN client makes no attempts at detecting and correcting the wrong metric. This should be possible without a reboot, since installing the VPN adapter itself doesn't requires one either.

**Comment by domosekai** [comment]
User can alter the metric too. So we can only reset metric to 1 at installation to avoid overwriting user's action.
