### ISSUE TITLE
L2TP unable to adjust accepted ciphers

### ISSUE THREAD

**Issue by dyemi511** [SoftEtherVPN/SoftEtherVPN#1220]
SE version. Any. Using latest builds to reproduce.

Operating system. Ubuntu 18.04 or centos7 and centos8.

Adjusting the algorithms used in the vpncmd or GUI for the ciphers has no effect on L2TP client. 

Unable to disable ike aggressive mode. 

Using ike-scan you can clearly identify that insecure ciphers allowing connections to the server. But also lacks ability to force main mode. This is a big security risk as a client could negotiate to use a broken cipher. There should most definitely be a flag to adjust these settings. If it's using the openswan or strongswan libraries, there's definitely the ability to set these parameters.

This security vulnerability for server/client connections should hopefully be an easy fix. 
Can someone guide me on where to look to test adjusting this?
Why is this important? 
MacOS is deprecated the support for the Tunnelblick so no more Openvpn. Using the built in client, l2tp is the best solution but need better control of ciphers. 

L2TP is also greater performance than Openvpn due to running on kernel space vs user space. 

Please let's fix this security vulnerability to remove or atleast select ciphers accepted by server.

**Comment by domosekai** [comment]
The cipher selection is for TLS. L2TP does not use TLS.

**Comment by dyemi6075** [comment]
L2TP does use ciphers. The IKE/IPSEC portion of L2TP handshake uses proposal sets. It's currently using/allowing very insecure ciphers/Proposals which should be an option to turn off/select proposals. 

I've edited the source code and built my instances by removing the insecure cipher sets for OPENVPN and IKE/IPSEC proposals.

There needs to be an option to select the ciphers/proposals used.
