### ISSUE TITLE
An error occurred connecting to the server, error code (1)！

### ISSUE THREAD

**Issue by 520ignite** [SoftEtherVPN/SoftEtherVPN#1221]
I tried to randomly select an IP to ping, but the result was that the ping failed. The leaked IP address and port number have been blacklisted by the Chinese government's GFW! This means that all services are invalid!

**Comment by 520ignite** [comment]
It is recommended to change from a traditional VPN to a new anonymous proxy server!Run V2ray service on all servers, simple and easy to deploy, with many perfect clients to provide support!

**Comment by chipitsine** [comment]
hello, what IP did you ping ? how is related to SE VPN ?

**Comment by AyrA** [comment]
I assume that this user uses SoftEther to bypass network restrictions put in place by the local government, possibly by using VPNGate. He is suggesting adding support for a v2ray software that appears to be a set of tools to tunnel traffic over other types of protocols.

**Comment by 520ignite** [comment]
> I assume that this user uses SoftEther to bypass network restrictions put in place by the local government, possibly by using VPNGate. He is suggesting adding support for a v2ray software that appears to be a set of tools to tunnel traffic over other types of protocols.

The Great Firewall will send back the certificate to the OpenVPN server to complete the handshake to create a valid encrypted connection and interfere with the connection. The handshake will be reset when the TCP protocol mode is used. When the UDP protocol is used, the data packets containing the server authentication certificate will be deliberately discarded, making OpenVPN Unable to create a valid encrypted connection and the connection failed .Therefore SoftEther is not available in China!

**Comment by AyrA** [comment]
SoftEther is not the same as OpenVPN. The server supports VPN but the SoftEther client has its own protocol.

**Comment by 520ignite** [comment]
> hello, what IP did you ping ? how is related to SE VPN ?



> SoftEther is not the same as OpenVPN. The server supports OpenVPN but the SoftEther client has its own protocol.

Use TCP connection
An error occurred while connecting to the VPN Server "ip".
Error (error code 2):
Protocol error, the target server returns an error!

Use UDP connection
An error occurred while connecting to the VPN Server "ip".
Error (error code 1):
The server connection failed. Please check the network connection to ensure that the target server address and port are correct

**Comment by AyrA** [comment]
You can close this issue. Your problem is not related to SoftEther but the underlying network. If you need to bypass network restrictions, the SoftEther client provides you with fields to enter a proxy server address.

**Comment by 520ignite** [comment]
> You can close this issue. Your problem is not related to SoftEther but the underlying network. If you need to bypass network restrictions, the SoftEther client provides you with fields to enter a proxy server address.

Login with proxy
VPN server "160.86.137.32" connection has been cut
Error (error code 3):
Disconnected

**Comment by AyrA** [comment]
Normal proxies do not encrypt your traffic. Use TOR or a similar network

**Comment by 520ignite** [comment]
> Normal proxies do not encrypt your traffic. Use TOR or a similar network

Okay thank you!
