### ISSUE TITLE
Client fails on FreeBSD amd64 with an obscure error

### ISSUE THREAD

**Issue by yurivict** [SoftEtherVPN/SoftEtherVPN#124]
I have the vpnclient running as root, and am getting this error from vpncmd:

```
VPN Client>niccreate se
NicCreate command - Create New Virtual Network Adapter
Error occurred. (Error code: 31)
Installation of the Virtual Network Adapter device driver failed.
```

Web search only returns the recommendation to run as root, but I already run it as root.
An error message should say what command fails.

File client_20150105.log also doesn't have any indication of what happened.
kdump log doesn't show any failing call in 'vpnclient' process that may be related.

Now this leads me to the dead end.

**Comment by vamsee** [comment]
You need to run both vpnclient as well as vpncmd as root. It worked for me.

**Comment by Diaron** [comment]
FreeBSD 10.3-RELEASE-p5
Softether installed from ports (softether-src-v4.18-9570-rtm).
vpnclient and vpncmd running as root
Got same 31 error with NicCreate command. 
Logs are keeping silence.
Anyone have this working or maybe it can be configured manually?

**Comment by MtCedarNet** [comment]
http://www.softether.org/3-spec#Supported_Operating_Systems
FreeBSD (32bit, 64bit) (Server and Bridge only)

**Comment by Diaron** [comment]
O, thanks, missed this.
Any plans to add client support for FreeBSD?

**Comment by scd-systems** [comment]
Hi,

Would be nice to get FreeBSD as Client Version.
The Admin tools for Linux and FreeBSD are also still missing.

What is the main blocker for FreeBSD as Client ?

Regards

**Comment by moatazelmasry2** [comment]
Hi all. Currently I'm trying to put up a roadmap for this project. So if this an actual feature request, then please change the description accordingly and vote (thumbs up) on the issue, so it is easy to know which features are wanted the most. Cheers

**Comment by davidebeatrici** [comment]
Client support for FreeBSD and OpenBSD has been added in #670.
