### ISSUE TITLE
How to connect with company database

### ISSUE THREAD

**Issue by nine-city** [SoftEtherVPN/SoftEtherVPN#1242]
hi
We are now planning to use softether to build a VPN network. We need to connect to the company's database. The open source version of softer does not support radius. How should I operate to use users in the database

**Comment by davidebeatrici** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/5f12684b42f747c2d15f3b89a03133c15dd902ea/src/Cedar/Server.c#L10586-L10637

**Comment by nine-city** [comment]
thanks.

**Comment by davidebeatrici** [comment]
No problem.
