### ISSUE TITLE
GUI Bug: Server Manager - New Connection Setting

### ISSUE THREAD

**Issue by scegg** [SoftEtherVPN/SoftEtherVPN#1247]
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** 5.01.9674 Unstable 2020.04.30 (from release)
**Component:** Server
**Operating system:** Windows
**Architecture:** 64 bit

### Description

In Server Manager, New Setting, clicking "Connect via SOCKS5 Proxy Server" doesn't enable "Proxy Server Setting" button.

**Expected behavior:**
"Proxy Server Setting" button should be enabled.

**Actual behavior:**
"Proxy Server Setting" button keeps disabled.

### Steps to reproduce
1 Open SoftEther Server Manager.
2 Click "New Setting"
3 Click "Connect via SOCKS5 Proxy Server"

![image](https://user-images.githubusercontent.com/3340557/101346968-52460c80-38c4-11eb-9124-2ce8d1518f0b.png)

### Workaround
Click "Connect via SOCKS4 Proxy Server" or "Connect via HTTP Proxy Server" to enable the button.

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue!

I'm not sure why it happens, because the button is supposed to be enabled for all settings but direct connection (no proxy):
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/bf1201aa265a874a4ce50bec03acf76f8f89f440/src/Cedar/SM.c#L87

**Comment by scegg** [comment]
> ClientOption

Maybe it is not triggered by selected that radio button.

**Comment by davidebeatrici** [comment]
You're absolutely right:

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/bf1201aa265a874a4ce50bec03acf76f8f89f440/src/Cedar/SM.c#L19617-L19634

`case R_SOCKS5:` should be added.

Here too, for the hub enumeration:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/bf1201aa265a874a4ce50bec03acf76f8f89f440/src/Cedar/SM.c#L19641-L19663

Feel free to create a pull request!

**Comment by scegg** [comment]
Line 116 also modified.

PR created.
