### ISSUE TITLE
I think it is time to improve documentation

### ISSUE THREAD

**Issue by andrewfer000** [SoftEtherVPN/SoftEtherVPN#1251]
After working with SoftEther for the past few months doing everything from using the program normally, testing new features, to digging into the code I found how complex of a project SoftEther really is. Not to offend anyone, but this project does not have the best documentation and it also looks and feels very dated. I would like this issue to be pinned as a long term goal to improve the documentation on the Github Wiki. SoftEther VPN is a very cool and important open source project and I believe it has a bright future as one of the best truly FOSS VPN program for individual enthusiasts like myself all they way up to large enterprises. 

In order for any Open Source project to become more adopted by individuals and bushiness small and large it must be well documented with everything from quick-start guides to advance-use guides with the end goal to be able to have detailed and easy to follow documentation for everything from installing SoftEther as a binary to compiling from source and even creating a better and more solid contributor's guide. Also it would be a good idea to start to comment the code better so newcomers and future contributors have an easier time fixing bugs and contributing. This is a huge undertaking that will take the efforts of the whole of the SoftEther community. Developers, one time contributors, feature testers (like myself), and everyday users. I do not know C programming very well so I feel like this is one of the best ways I can contribute.

**Comment by andrewfer000** [comment]
Is there a documentation directory in the source code where the GitHub wiki is pulling from? I'd love to get started but I do not know where you keep the .md files for the Wiki in the repository.

**Comment by chipitsine** [comment]
Wiki is separate got based repo.
It would be lovely to populate wiki

**Comment by andrewfer000** [comment]
So how do I submit new files and changes?

**Comment by davidebeatrici** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/wiki

Does it let you edit existing pages and create new ones?

**Comment by andrewfer000** [comment]
I can't edit/change since I am not a member of SoftEther. I will clone it to my local system and email you the new/edited files. Unless you make a github page for it we will have to compare changes and approve changes manually.

**Comment by andrewfer000** [comment]
I am starting to work on a new compilation guide. I will need some testers especially for FreeBSD and Windows.

**Comment by davidebeatrici** [comment]
Awesome, thank you very much!

I edited the access setting for the Wiki, you should now be able to write to it.
