### ISSUE TITLE
SSTP and IPsec issues with Windows 10 on Master

### ISSUE THREAD

**Issue by andrewfer000** [SoftEtherVPN/SoftEtherVPN#1253]
So I'm going to get straight to the point and describe this as best as I can. So on the stable version of SoftEther (that's in the Ubuntu apt repo) I can set up Windows 10 SSTP and it "just works". In this Master branch it seems that now I have to go into the Windows Network and Sharing center after setting up the VPN connection to enable MS-CHAPv2 and enable the require encryption option for the VPN connection to work. The same goes for L2TP/IPsec on Win10. Windows 7 on the other hand automatically configures the VPN settings without issue on both the stable and latest master branch. Why can Windows 7 auto-configre the settings while Windows 10 cannot. Tbh this wouldn't be a major issue if changing VPN settings in Network and Sharing center did not require administrator privileges (which I do not have on my work laptop at the moment).

There had to be a slight change in the PPP stack that somehow confuses newer OSes into not being able to automatically configure the VPN security settings.   

I know I have been posting a lot of issues and stuff recently and I'm sorry if it's annoying. I just think this is the best way for me to track and keep record of issues I am experiencing since I have been messing around with SoftEther. 

Edit: Also if Linux or Windows has EAP enabled the VPN connection will fail as well. The logs below are from Windows 10 connecting to SSTP and IPsec running on the master branch code.

**Comment by andrewfer000** [comment]
SSTP Log:

of PPP Server: 443, Client Software Name: "Microsoft SSTP VPN Client", IPv4 TCP MSS (Max Segment Size): 0 bytes
PPP starting main dataloop
Request EAP
Got LCP packet request ID=0 OptionsListSize=5
Unsupported LCP option = 0x5
Unsupported LCP option = 0x7
Unsupported LCP option = 0x8
Unsupported LCP option = 0xd
Rejected LCP option = 0x5, proto = 0xc021
Rejected LCP option = 0x7, proto = 0xc021
Rejected LCP option = 0x8, proto = 0xc021
Rejected LCP option = 0xd, proto = 0xc021
Rejected LCP options...
Setting BEFORE_AUTH from ACK on LCP response parse on EAP accept
Got LCP packet request ID=1 OptionsListSize=1
NACKed LCP option = 0x1, proto = 0xc021
NACKed LCP options...
Got LCP packet request ID=2 OptionsListSize=1
ACKed LCP option = 0x1, proto = 0xc021
../src/Cedar/Proto_PPP.c: 109
../src/Cedar/Proto_PPP.c: 109
../src/Cedar/Proto_PPP.c: 109
Got a EAP_NAK, abandoning EAP protocol
Rejecting PPP protocol = 0xc227
Request MSCHAPv2 from EAP NAK
SSTP Control Packet Recv: Msg = 6, Num = 1
SSTP Control Packet Send: Msg = 7, Num = 0
ProtoHandleConnection(): breaking main loop

**Comment by andrewfer000** [comment]
L2TP/IPsec

New IKE_CLIENT: 0x7fa9f0070cd0: 69.***.***.**4:56426 -> 0.0.0.0:500
LOG: IPsec Client 4 (69.***.***.**4:56426 -> 0.0.0.0:500): A new IPsec client is created.
P1 Transform: MODP 2048 (Group 14) SHA-1 AES-CBC(32) 4294967295 28800
New IKE SA (Mode = 0): 12659176132627621425 <--> 2681143613976997564 (MODP 2048 (Group 14) SHA-1 AES-CBC(32) 4294967295 28800)
LOG: IPsec IKE Session (IKE SA) 4 (Client: 4) (69.***.***.**4:56426 -> 0.0.0.0:500): A new IKE SA (Main Mode) is created. Initiator Cookie: 0xAFAE6D9F165F6631, Responder Cookie: 0x253555E95EE7EEBC, DH Group: MODP 2048 (Group 14), Hash Algorithm: SHA-1, Cipher Algorithm: AES-CBC, Cipher Key Size: 256 bits, Lifetime: 4294967295 Kbytes or 28800 seconds
Initial IV: 87 DE D7 B7 7B 98 ED E5 68 0B F4 64 28 C1 07 69
ResponderRand: 2C C5 63 F5 B5 1D 65 DA 85 A4 6F F8 4B A5 D0 E2 02 33 CF C8 8C 11 B6 53 BE 6A 3A EA FF AC 80 75 FD E0 D2 F6 A6 63 4B 70 B3 3D 34 EF D9 8C F8 0E
InitiatorRand: B6 27 72 30 5C 6B 6F E1 AF EE D1 07 15 7F 1A B5
SKEYID: 0D 7D C1 19 44 2C F0 E1 70 DD D2 CA 57 86 2F 75 A9 3C 76 CB
SKEYID_d: F7 49 0E 43 C9 AF 65 EB 3C 19 0D 58 2A 0C 3F 9F A7 63 34 84
SKEYID_a: 44 04 EE EF EA 9C 64 C3 B4 C9 99 A5 57 9F 0C 68 B6 8F B7 B9
SKEYID_e: 2B B2 18 63 84 30 99 99 5D A1 BE C6 AA 67 2C A1 18 2F 7C 94
Update IKE_CLIENT: 0x7fa9f0070cd0: 69.***.***.**4:4500 -> 0.0.0.0:4500
LOG: IPsec Client 4 (69.***.***.**4:4500 -> 0.0.0.0:4500): The port number information of this client is updated.
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
Client ID = 192.168.122.196
LOG: IPsec Client 4 (69.***.***.**4:4500 -> 0.0.0.0:4500): 
IKE SA 0xF0070140 Established. Client ID=192.168.122.196
LOG: IPsec IKE Session (IKE SA) 4 (Client: 4) (69.***.***.**4:4500 -> 0.0.0.0:4500): This IKE SA is established between the server and the client.
IKE_CLIENT 0xF0070CD0: Begin QuickMode
Error: c->CachedTransformSetting is not existing.
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
P2 Transform: (null) SHA-1 AES-CBC(32) 250000 3600
LOG: IPsec IKE Session (IKE SA) 4 (Client: 4) (69.***.***.**4:4500 -> 0.0.0.0:4500): The client initiates a QuickMode negotiation.
New IPsec SA (StoC = 0): 0x1 0xF11777EE ((null) SHA-1 AES-CBC(32) 250000 3600)
LOG: IPsec ESP Session (IPsec SA) 4 (Client: 4) (69.***.***.**4:4500 -> 0.0.0.0:4500): A new IPsec SA (Direction: Client -> Server) is created. SPI: 0xF11777EE, DH Group: (null), Hash Algorithm: SHA-1, Cipher Algorithm: AES-CBC, Cipher Key Size: 256 bits, Lifetime: 250000 Kbytes or 3600 seconds
  KEYMAT: C2 EC 5D E6 27 0F 74 CB 20 CC 93 75 51 DB AF C4 E6 F8 FB 6F 86 5C 8B 69 83 16 98 2A AC 58 46 DD
New IPsec SA (StoC = 1): 0x1 0x222625AC ((null) SHA-1 AES-CBC(32) 250000 3600)
LOG: IPsec ESP Session (IPsec SA) 4 (Client: 4) (69.***.***.**4:4500 -> 0.0.0.0:4500): A new IPsec SA (Direction: Server -> Client) is created. SPI: 0x222625AC, DH Group: (null), Hash Algorithm: SHA-1, Cipher Algorithm: AES-CBC, Cipher Key Size: 256 bits, Lifetime: 250000 Kbytes or 3600 seconds
  KEYMAT: 3D 62 5E 15 01 5E 69 DD 5B 29 97 ED DE 45 BC B1 3E 72 E0 BC 19 A2 C5 80 D8 27 77 DD 7F F7 92 0F
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
IPsec SA 0xF11777EE & 0x222625AC Established.
LOG: IPsec ESP Session (IPsec SA) 4 (Client: 4) (69.***.***.**4:4500 -> 0.0.0.0:4500): This IPsec SA is established between the server and the client.
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
IKE_CLIENT 0xF0070CD0: L2TP Server Started.
LOG: IPsec Client 4 (69.***.***.**4:4500 -> 0.0.0.0:4500): The L2TP Server Module is started.
L2TP New Tunnel From 69.***.***.**4 (DESKTOP-J9U7VPK, Microsoft): New Tunnel ID = 5/1
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
L2TP New Session: ID = 1/1 on Tunnel 5/1
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
Thread Created for Session 1/1 on Tunnel 5/1
PPP InitializeMsChapV2_UseDoubleMsChapV2 = 0x0
PPP Link establishment phase
LOG: L2TP PPP Session [69.***.***.**4:1701]: A new PPP session (Upper protocol: L2TP) is started. IP Address of PPP Client: 69.***.***.**4 (Hostname: "DESKTOP-J9U7VPK"), Port Number of PPP Client: 1701, IP Address of PPP Server: 0.0.0.0, Port Number of PPP Server: 1701, Client Software Name: "L2TP VPN Client - Microsoft", IPv4 TCP MSS (Max Segment Size): 1314 bytes
PPP starting main dataloop
Request EAP
Got LCP packet request ID=0 OptionsListSize=5
Unsupported LCP option = 0x5
Unsupported LCP option = 0x7
Unsupported LCP option = 0x8
Unsupported LCP option = 0xd
Rejected LCP option = 0x5, proto = 0xc021
Rejected LCP option = 0x7, proto = 0xc021
Rejected LCP option = 0x8, proto = 0xc021
Rejected LCP option = 0xd, proto = 0xc021
Rejected LCP options...
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
Setting BEFORE_AUTH from ACK on LCP response parse on EAP accept
Got LCP packet request ID=1 OptionsListSize=1
ACKed LCP option = 0x1, proto = 0xc021
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
../src/Cedar/Proto_PPP.c: 109
../src/Cedar/Proto_PPP.c: 109
../src/Cedar/Proto_PPP.c: 109
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
Got a EAP_NAK, abandoning EAP protocol
Rejecting PPP protocol = 0xc227
Request MSCHAPv2 from EAP NAK
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
Trying to Disconnect Session ID 1/1 on Tunnel 5/1
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
Trying to Disconnect Tunnel ID 5/1
L2TP Session 1/1 on Tunnel 5/1 Disconnected.
Thread Stopped for Session 1/1 on Tunnel 5/1
L2TP Tunnel 5/1 is Disconnected.
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
IPsec SA 0x222625AC has been marked as being deleted.
LOG: IPsec ESP Session (IPsec SA) 4 (Client: 4) (69.***.***.**4:4500 -> 0.0.0.0:4500): This IPsec SA is deleted.
140368205227072:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:583:
IKE SA 12659176132627621425 - 2681143613976997564 has been marked as being deleted.
LOG: IPsec IKE Session (IKE SA) 4 (Client: 4) (69.***.***.**4:4500 -> 0.0.0.0:4500): This IKE SA is deleted.
Purging IKE SA 12659176132627621425-2681143613976997564
  Deleting IPsec SA 0xF11777EE of this IKE SA (no alternatives)
IPsec SA 0xF11777EE has been marked as being deleted.
LOG: IPsec ESP Session (IPsec SA) 4 (Client: 4) (69.***.***.**4:4500 -> 0.0.0.0:4500): This IPsec SA is deleted.
LOG: L2TP PPP Session [69.***.***.**4:1701]: The PPP session is disconnected because the upper-layer protocol "L2TP" has been disconnected.
Exited main dataloop, status = 0x110
LOG: L2TP PPP Session [69.***.***.**4:1701]: The PPP session is disconnected

**Comment by sl077** [comment]
You say this is caused by the server? Observed the missing authentication protocol on new VPN connections on current Windows too, but thought that this problem was introduced in Redmond. It's really annoying, creating a new VPN connection on a Windows client should be super easy, but now I have to tell my colleagues, that they have to change some security related settings for this adapter someplace else.
You attached connection logs (I guess), but aren't those authentication flags configured on the setup of the connection or is it actually happening on the first connection attempt? If it's on setup time, then there should be some request to the server asking for it's capabilities.

**Comment by andrewfer000** [comment]
I had to do no other configuration in Windows 10 on the version of SoftEther in the PPA.

**Comment by sl077** [comment]
Looks like you are right, if I create a new VPN connection (SSTP or L2TP/IPsec) on Windows, then it doesn't preset any authentication protocols initially. On the first connection attempt, client and server try to agree on a protocol to use for authentication. If this succeeds, Windows seems to set this protocol in the adapter settings for subsequent uses.
The current SoftetherVPN offers EAP first, since it got the code for this in may. The Windows client accepts, but it fails, because the current EAP implementation in Softether only contains the code for EAP-TLS (authentication by certificate) and not for password auth. Now the Windows client doesn't try to proceed with any other availabe protocol und aborts the connection attempt.
And all of this was found out before: #1169

To test this, I created a quick&dirty (!!!, and it also breaks EAP auth) patch to make Softether offer MS-CHAPv2 first (see attachment). This makes Windows clients (with username and password) happily connect to SoftetherVPN without requiring any special adapter settings.
I think I'd prefer having a server configuration option, to select between EAP or MS-CHAPv2 as the first offered authentication protocol. Having EAP support is great, but it being incomplete now causes this inconvenience for classic password auth. Never tried EAP with a certificate, but aren't you required to setup your certificate/key in the adapter settings anyway? So what does it help, that the server defaults to EAP, if you still have to configure everything beforehand?

[PPP_default-to-MSCHAPv2.diff.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/5710045/PPP_default-to-MSCHAPv2.diff.txt)

**Comment by andrewfer000** [comment]
Yes, I reviewed your code (not that I understand it anyway) but what I don't understand is why Windows XP and 7 have no issues but Windows 10 does. That's what's strange.

**Comment by sl077** [comment]
Maybe they just updated their code or the defaults (like SoftEther did). And probably didn't expect to run into incomplete EAP implementations.
The "patch" is hardly my code btw, I just copied the fallback MS-CHAPv2 request to where the EAP request used to be. This is definitely not a good way to solve this, but I guess it should work, as long as no client ever wants to use EAP-TLS.
