### ISSUE TITLE
openSUSE/ SUSE Enterprise info for Documentation (Wiki)

### ISSUE THREAD

**Issue by andrewfer000** [SoftEtherVPN/SoftEtherVPN#1254]
I am opening this issue to ask if anyone has experience with SoftEther on (open)SUSE. Because of the recent news about CentOS I want there to be well-tested installation and compilation documentation for the SUSE platform. This issue is here so I can gather information on how to install and run SoftEtherVPN on all versions of SUSE as well as any issues with the Operating System (i.e dependencies etc.). If you are currently using SoftEther on SUSE please leave as many details as possible so I can test it myself and make proper documentation. Thank you.

Edit: When I talk openSUSE I am talking about Leap and NOT Tumbleweed. This is to keep things consistent for SUSE Enterprise.

**Comment by chipitsine** [comment]
I think we can enable OpenSuSE builds in docker GitHub Actions. I'm not very familiar with OpenSUSE itself (I used to run it few years ago on laptop), so I will ask you for review as soon as I create github action pipeline.


Another point of interest is OpenSUSE Build Service. Are you familiar with it ?

**Comment by chipitsine** [comment]
as for building from source, it should be similar to other rpm based distro, not sure we should encourage building from source. I more tend to providing rpm repo.

**Comment by chipitsine** [comment]
@andrewfer000 


https://github.com/chipitsine/SoftEtherVPN/runs/1572462848


seems OpenSUSE comes without "tar" :)


any ideas on https://github.com/chipitsine/SoftEtherVPN/commit/5fd1557ac616e2930bd1c0f0239d8266c54615ec ?

**Comment by andrewfer000** [comment]
zypper addrepo https://download.opensuse.org/repositories/openSUSE:Leap:15.2/standard/openSUSE:Leap:15.2.repo (if not already added by default)
zypper refresh
**zypper install tar**

This should be added to chipitsine@5fd1557 on line 19

-zypper install openssl cmake gcc
+zypper install openssl cmake gcc tar

**Comment by chipitsine** [comment]
which package provides "gzip" executable ?

https://github.com/chipitsine/SoftEtherVPN/runs/1575417146
