### ISSUE TITLE
Malicious domains

### ISSUE THREAD

**Issue by F1reP0wer12345** [SoftEtherVPN/SoftEtherVPN#1258]
---

### Prerequisites

Can you reproduce?
Yes

Are you running the latest version of SoftEtherVPN?
I don't know, but these are the version details:

**SoftEther version:** 4.0 version 4.34, build 9745
**Operating system:** Windows 7
**Architecture:** 64 bit

### Description

vpnclient_64.exe gets picked up contacting malicious or at least blacklisted domains. some of the following domains were picked up by avast free antivirus which are stopped from reaching the internet:

xml.pop.adacts.com
www.mhsk.club

These domains shouldn't be contacted in the first place because i'm not visiting them. I don't even have a vpn active. when i look into task manager and proccess explorer, i can see this so called vpnclient_64.exe running as a system user. Why on earth would you need system rights?! As soon as i stop the process, a new one appears seconds later, while id didn't even click anything.

**Expected behavior:**
Not contacting these domains, and stop when i'm asking it to.

**Actual behavior:**
Contacting these domains, and probably more.

### Steps to reproduce

1. Do nothing
2. do more nothing
3. And the process starts, as a freaking system user...

**Comment by davidebeatrici** [comment]
The process runs as `SYSTEM` because it's a service.

Also, administrator privileges are required in order to manage the virtual network interfaces.

The service management applications can run in a non-privileged environment without any issues.

As for the domains: are you sure it's the service itself that is attempting to access them?

**Comment by hjk789** [comment]
Are you using the VPN Gate Relay Servers plugin? If yes, it will keep pinging a very long IP list of VPN servers in intervals of around 15 minutes. Maybe your Avast is resolving the IPs or it's looking up in a database that says that some of these IPs were resolved to these malicious domains at some point in the past, which may or may not be true nowadays.

**Comment by Killham** [comment]
I don't use this particular VPN, but in the Opera latest version browser, the Browsec VPN extensions and also SurfEasy VPN are installed. Redirects in browser happening periodically and unexpected right to: 
xml.adokutcontextual.com
xml.pop.adacts.com
click.ad-monetize.com
It can be popping like 5-7 time in a row and Avast free saving me from this every time. All of them marked as URL:blacklist by avast.
Was deleteding SurfEasyVpn extension in opera right now, and will watch is this happening again or not.
