### ISSUE TITLE
put latest client on git

### ISSUE THREAD

**Issue by 249550148** [SoftEtherVPN/SoftEtherVPN#126]
always failed to download client bin, and do not want to build myself.

**Comment by TEKRCG** [comment]
It’s all fine with the binary download from softether.org. But if your download always failed and if you wan’t help yourself with a own compiled client binary, it’s your problem…

So, please stop spam.

Rgds, Robert

P.S. Google, Bing and Co. are your friends:
http://lmgtfy.com/?q=softether+vpn+client+download+-softether.org

Have Fun

Von: 249550148 [mailto:notifications@github.com]
Gesendet: Mittwoch, 14. Januar 2015 05:05
An: SoftEtherVPN/SoftEtherVPN
Betreff: [SoftEtherVPN] put latest client on git (#126)


always failed to download client bin, and do not want to build myself.
