### ISSUE TITLE
DHCP lease is not renewed 

### ISSUE THREAD

**Issue by chornyitaras** [SoftEtherVPN/SoftEtherVPN#1262]
### Prerequisites

* [x] Can you reproduce?

* [x] Are you running the latest version of SoftEtherVPN?
installed using  Ubuntu PPA https://launchpad.net/~paskal-07/+archive/ubuntu/softethervpn

**SoftEther version:**   5.0.1 9674
**Component:**  Server
**Operating system:** Linux
**Architecture:**  64 bit

**Processor:** Intel XeonCPU E3-1270 v5 

### Description

When SSTP session is established I can see IP is in IP Lease table. After lease time expires even is the session is still active IP is not renewed. This causing the issue that next user that will connect will get IP that is currently used.

**Expected behavior:**
Ip should be renewed

**Actual behavior:**
IP is not renewed and deleted from lease table
### Steps to reproduce

1. Install VPN server Using ubuntu PPA (Ubuntu 20.41)
2. Create a virtual hub
3. Enable Secure nat and virtual DHCP
4. Set Lease limit to 60 seconds
4. Create 2 vpn users
5. enable support for MS-SSTP
6. Configure SSTP vpn connection on client PCs(Windows 10)
7. Connect client 1 PC to VPN and check assigned IP (in my case 192.168.30.10)
8. Check that IP is in Ip Lease table
9. wait 60 sec
10. Check that  IP is removed from lease table
11. Connect client 2 PC to VPN and check assigned IP (in my case 192.168.30.10) which is incorrect

**Comment by kazan-priv** [comment]
I'm having exactly same issue with server 5.02 Build 5180
Is there any fix for this?
Thanks
