### ISSUE TITLE
请求帮助，已检测到TCp监听器上有Dos攻击

### ISSUE THREAD

**Issue by 759071793** [SoftEtherVPN/SoftEtherVPN#1264]
![image](https://user-images.githubusercontent.com/23308600/106350086-28cabf80-630e-11eb-8d3a-f96ffb187843.png)
请求大佬这个会是什么问题呢，现在b连不上a的服务端。。会被强制断开，然后出现此日志

**Comment by davidebeatrici** [comment]
Could you paste the log here, please?

**Comment by 759071793** [comment]
> Could you paste the log here, please?
OK,THANK YOU
[vpn_20210130.log](https://github.com/SoftEtherVPN/SoftEtherVPN/files/5897681/vpn_20210130.log)

**Comment by 759071793** [comment]
Is this attack initiated by computer B? Computer a will reject this IP link. I can successfully link computer B with another IP

**Comment by 759071793** [comment]
我把B客户端换一个ip后可以成功链接，但是用222.213.236.98这个ip就会被A 服务端拒绝

**Comment by davidebeatrici** [comment]
SoftEther VPN version?
