### ISSUE TITLE
CMake always compiles BLAKE2 from SSE2 sources

### ISSUE THREAD

**Issue by akuropka** [SoftEtherVPN/SoftEtherVPN#1288]
I'm building SoftEtherVPN on a Raspi-4 with Arch Linux Arm installed.
Building runs fine including commit 8a37f5c, but from b339104 onwards building fails due to missing SSE2 set on arm chipsets.

> [ 65%] Building C object src/Cedar/CMakeFiles/cedar.dir/__/__/3rdparty/BLAKE2/sse/blake2s.c.o

> In Datei, eingebunden von /usr/local/vpnserver/sources/3rdparty/BLAKE2/sse/blake2s.c:23:

> /usr/local/vpnserver/sources/3rdparty/BLAKE2/sse/blake2-config.h:69:2: Fehler: #error "This code requires at least SSE2."

>    69 | #error "This code requires at least SSE2."

>       |  ^~~~~

> /usr/local/vpnserver/sources/3rdparty/BLAKE2/sse/blake2s.c:26:10: schwerwiegender Fehler: emmintrin.h: Datei oder Verzeichnis nicht gefunden

>    26 | #include <emmintrin.h>

>       |          ^~~~~~~~~~~~~

> Kompilierung beendet.

> make[2]: *** [src/Cedar/CMakeFiles/cedar.dir/build.make:862: src/Cedar/CMakeFiles/cedar.dir/__/__/3rdparty/BLAKE2/sse/blake2s.c.o] Fehler 1

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue, I can reproduce it on Ubuntu 20.04.
