### ISSUE TITLE
How to fix(fasten) DDNS key which changes every time restart after in docker

### ISSUE THREAD

**Issue by bsnresearcher** [SoftEtherVPN/SoftEtherVPN#1290]
Dear everyone

I am in trouble that a DDNS(Dynamic DNS) hostname is changed in a docker every times the os restarted.

Of course, the DDNS hostname's key hash was described in "vpn_server.config".

Please tell me how to fix(fasten) the DDNS key hash.

Best regard

**Comment by davidebeatrici** [comment]
Does the hostname in Docker change after every restart?

**Comment by bsnresearcher** [comment]
Yes.
I uses the docker of https://hub.docker.com/r/siomiz/softethervpn/

**Comment by paulmenzel** [comment]
`docker run` has the switch `--hostname` allowing you to set a hostname.

    $ docker help run
    […]
      -h, --hostname string                Container host name
    […]

**Comment by bsnresearcher** [comment]
Thanks.

The parameter was invalid in my env.

I guessed:

The mechanism is that the hostname have been registered depended on the previous DDNS hostname key,but the DDNS key is forcibly changed. So if I want to indicate hostname, the indicated hostname cannot be registered again due to the previous hostname was related with the previous DDNS key.

So I want to forcibly fix(fasten) the DDNS key is unique.

**Comment by paulmenzel** [comment]
What is your environment?

I still do not understand your problem. Should a fixed hostname fix it? Then, as this is not a Docker support forum, just set a hostname for your container, and use that in subsequent restarts.

**Comment by bsnresearcher** [comment]
Thanks.

This parameter is incomplete.

The reason why there is a case the specified hostname as parameter used was rejected to register due to duplication with the previous registered hostname which I registered. 

In my environment,  the DDNS key was changed even the DDNS hostname key was specified in "vpn_server.conf" after the docker container restarted

So nevertheless in docker, I want to know tips/technique to fix(fasten) DDNS host key if the knowledge exists.

In not docker but a raspberry Pi, there is a case the DDNS key was changed. I concerns about the DDNS key will change in operation.

**Comment by paulmenzel** [comment]
Sorry, I do not want to be rude, but I am having a really hard time to understand, what you want to say.

Please paste the versions you use, the commands you executed, and the errors you got.

**Comment by matthuo333** [comment]
I have the same problem. But not in the docker environment, but on the embedded physical machine, the openwrt system.
According to the above discussion, it seems that the ddns key is based on the host name. I did change the host name, but is there no way to force the key to be replaced?

**Comment by bsnresearcher** [comment]
# Solution

```bash
rm vpnserver.conf
touch vpnserver.conf.
```

# Cause:
The docker client user vpnserver.conf described hostname hash key, which was gotten by "clone" from the repository.
The hash key is duplicated one of the author using. So we use it, DDNS host(master server) changes our hostname in force.

If vpnserver.conf was size 0, it is recreated according to entorypoint.sh.

https://hub.docker.com/r/siomiz/softethervpn/
