### ISSUE TITLE
Improve UDP acceleration by using the external IP reported by NAT-T server

### ISSUE THREAD

**Issue by domosekai** [SoftEtherVPN/SoftEtherVPN#1291]
When I use SE client from my home computer, UDP acceleration never works, because my broadband carrier uses some ugly NAT that causes TCP and UDP connections have different external IPs.

Then I dig into the code and did some wireshark, and found that the external IP for UDP is actually obtained from the NAT-T server, but is never used by the client.

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/b00aa39b29962ff1cf09202d00b5e51839428b02/src/Cedar/UdpAccel.c#L63-L83

Here the port is saved (to be later sent via TCP keep-alive) but the IP is discarded. If we can use this IP and send it to server in keep-alive as well, the server can send UDP packet to this correct IP and very likely solves this issue.

**Comment by JJS777** [comment]
That’s Great

**Comment by davidebeatrici** [comment]
Why was this issue closed?

**Comment by domosekai** [comment]
There are just too many open issues and this is not an urgent one. It's more of an enhancement proposal. Feel free to reopen or discuss.

**Comment by davidebeatrici** [comment]
Your finding is definitely interesting.

**Comment by domosekai** [comment]
@davidebeatrici Thank you for reopening it.
There is actually another reason why I raised it. 
I am the developer of iOS app "SSTP Connect", which also supports SoftEther VPN.
Mobile devices can move from one network to another (mobile to wifi, for example) and thanks to the "additional connection" function, the current VPN session can be reused and the switch is sort of "seamless". However, UDP re-connection is currently impossible (unless the port is open) because there is no way to send the new address of client to the server.
Of course this is a 3rd party enhancement and it's not appropriate to let a paid app take a free ride. Just for your information.

**Comment by davidebeatrici** [comment]
Oh, I see. Thank you very much!

Should I create a pull request so that you can test whether the fix works?

**Comment by domosekai** [comment]
Oh, thank you so much. That would be great.

**Comment by davidebeatrici** [comment]
Could you test #1324, please?
