### ISSUE TITLE
VPN Server is located under two-level NAT, VPN cannot establish a connection

### ISSUE THREAD

**Issue by matthuo333** [SoftEtherVPN/SoftEtherVPN#1294]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

NO
- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [ ] Can you reproduce?
* [y ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** [Server, Client, Bridge, etc.]
**Operating system:** [Windows, Linux, BSD, macOS, etc.]
**Architecture:** [64 bit, 32 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]

### Description

VPN Server 端拓扑网络：VPN SE Server 位于Openwrt(192.168.0.a) -->Route2( LAN: 192.168.0.b  Wan: 192.168.1.a) -->Route1(LAN: 192.168.1.b  WAN: 公网IP)

VPN Client : 手机 L2TP/IPsec 

位于Route1 LAN, 没问题，可以正常通过openwrt相关应用协议栈访问到互联网。但是位于上面拓扑，即，Route2 下则不行。

同时，对两层的NAT均做了端口映射，仍然不行。

In English:

VPN Server Topology Network: VPN SE Server is located in Openwrt(192.168.0.a) -->Route2( LAN: 192.168.0.b Wan: 192.168.1.a) -->Route1(LAN: 192.168.1.b) WAN: Public IP)

VPN Client: Mobile phone L2TP/IPsec

Located on the Route1 LAN, no problem, you can access the Internet through the openwrt related application protocol stack normally. But in the top topology, that is, under Route2, it doesn't work.

At the same time, port mapping is done for both layers of NAT, but it still does not work.

**Expected behavior:**
[What you expected to happen]

**Actual behavior:**
[What actually happened]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [And so on...]

**Comment by davidebeatrici** [comment]
Could you write the message in English, please?

**Comment by matthuo333** [comment]
> Could you write the message in English, please?

English version has been added

**Comment by domosekai** [comment]
I have tested on iOS and confirm that L2TP connection to server under double NAT works perfectly. Check your router settings instead.
