### ISSUE TITLE
Compiling and running in Docker

### ISSUE THREAD

**Issue by Armik2** [SoftEtherVPN/SoftEtherVPN#1297]
Hello. Encountered a problem during assembly, please tell me what could be the problem? Also had to add "libsodium-dev" and change the system to latest.
```
`Status: Downloaded newer image for alpine:latest
---> 28f6e2705743
Step 2/10 : WORKDIR /usr/src
---> Running in a4a5a40b9b9c
Removing intermediate container a4a5a40b9b9c
---> 5e77f5913996
Step 3/10 : RUN apk add --no-cache binutils build-base readline-dev openssl-dev ncurses-dev libsodium-dev git cmake gnu-libico nv zlib-dev && git clone --recurse-submodules https://github.com/SoftEtherVPN/So ftEtherVPN.git && cd SoftEtherVPN && ./configure && make -C tmp && make -C tmp install && tar -czf /artifacts.tar.gz /usr/local
---> Running in c05a47791170
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/48) Installing libgcc (10.2.1_pre1-r3)
(2/48) Installing libstdc++ (10.2.1_pre1-r3)
(3/48) Installing binutils (2.35.1-r1)
(4/48) Installing libmagic (5.39-r0)
(5/48) Installing file (5.39-r0)
(6/48) Installing libgomp (10.2.1_pre1-r3)
(7/48) Installing libatomic (10.2.1_pre1-r3)
(8/48) Installing libgphobos (10.2.1_pre1-r3)
(9/48) Installing gmp (6.2.1-r0)
(10/48) Installing isl22 (0.22-r0)
(11/48) Installing mpfr4 (4.1.0-r0)
(12/48) Installing mpc1 (1.2.0-r0)
(13/48) Installing gcc (10.2.1_pre1-r3)
(14/48) Installing musl-dev (1.2.2-r0)
(15/48) Installing libc-dev (0.7.2-r3)
(16/48) Installing g++ (10.2.1_pre1-r3)
(17/48) Installing make (4.3-r0)
(18/48) Installing fortify-headers (1.1-r0)
(19/48) Installing patch (2.7.6-r6)
(20/48) Installing build-base (0.5-r2)
(21/48) Installing libacl (2.2.53-r0)
(22/48) Installing libbz2 (1.0.8-r1)
(23/48) Installing expat (2.2.10-r1)
(24/48) Installing lz4-libs (1.9.2-r0)
(25/48) Installing xz-libs (5.2.5-r0)
(26/48) Installing zstd-libs (1.4.5-r3)
(27/48) Installing libarchive (3.5.1-r0)
(28/48) Installing ca-certificates (20191127-r5)
(29/48) Installing brotli-libs (1.0.9-r3)
(30/48) Installing nghttp2-libs (1.42.0-r1)
(31/48) Installing libcurl (7.74.0-r1)
(32/48) Installing ncurses-terminfo-base (6.2_p20210109-r0)
(33/48) Installing ncurses-libs (6.2_p20210109-r0)
(34/48) Installing rhash-libs (1.4.1-r0)
(35/48) Installing libuv (1.40.0-r0)
(36/48) Installing cmake (3.18.4-r1)
(37/48) Installing pcre2 (10.36-r0)
(38/48) Installing git (2.30.2-r0)
(39/48) Installing gnu-libiconv (1.15-r3)
(40/48) Installing libsodium (1.0.18-r0)
(41/48) Installing pkgconf (1.7.3-r0)
(42/48) Installing libsodium-dev (1.0.18-r0)
(43/48) Installing ncurses-dev (6.2_p20210109-r0)
(44/48) Installing openssl-dev (1.1.1j-r0)
(45/48) Installing libhistory (8.1.0-r0)
(46/48) Installing readline (8.1.0-r0)
(47/48) Installing readline-dev (8.1.0-r0)
(48/48) Installing zlib-dev (1.2.11-r3)
Executing busybox-1.32.1-r3.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 261 MiB in 62 packages
Cloning into 'SoftEtherVPN'...
Updating files: 100% (1768/1768), done.
Submodule '3rdparty/BLAKE2' (https://github.com/BLAKE2/BLAKE2.git) registered for path '3rdparty/BLAKE2'
Submodule '3rdparty/tinydir' (https://github.com/cxong/tinydir.git) registered for path '3rdparty/tinydir'
Submodule 'src/Mayaqua/3rdparty/cpu_features' (https://github.com/google/cpu_features.git) registered for path 'src/Mayaqua/3rdparty/cpu_features'
Submodule 'src/libhamcore' (https://github.com/SoftEtherVPN/libhamcore.git) registered for path 'src/libhamcore'
Cloning into '/usr/src/SoftEtherVPN/3rdparty/BLAKE2'...
Cloning into '/usr/src/SoftEtherVPN/3rdparty/tinydir'...
Cloning into '/usr/src/SoftEtherVPN/src/Mayaqua/3rdparty/cpu_features'...
Cloning into '/usr/src/SoftEtherVPN/src/libhamcore'...
Submodule path '3rdparty/BLAKE2': checked out 'b52178a376ca85a8ffe50492263c2a5bc0fa4f46'
Submodule path '3rdparty/tinydir': checked out 'ec6bff2043eaac3ad25423705e63a781762a0dfd'
Submodule path 'src/Mayaqua/3rdparty/cpu_features': checked out '26133d3b620c2c27f31d571efd27371100f891e9'
Submodule path 'src/libhamcore': checked out 'b7f5d8d735b280fc77673c4a29f0436a92ca6660'
SoftEther VPN for Unix

Copyright (c) all contributors on SoftEther VPN project in GitHub.
Copyright (c) Daiyuu Nobori, SoftEther Project at University of Tsukuba, and SoftEther Corporation.

Licensed under the Apache License, Version 2.0 (the License).

Read and understand README, LICENSE and WARNING before use.
Welcome to the corner-cutting configure script !

'rpm' executable not found, CPack will generate DEB packages.

-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/auxv.h
-- Looking for sys/auxv.h - found
-- Build date: 14/03/2021
-- Build time: 11:30:54
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3")
-- Checking for one of the modules 'libsodium'
-- Found Curses: /usr/lib/libcurses.so
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1j")
-- Found ZLIB: /lib/libz.so (found version "1.2.11")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- The CXX compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/SoftEtherVPN/build

The Makefile is generated. Run 'make -C build' to build SoftEther VPN.
make: *** tmp: No such file or directory. Stop.
The command '/bin/sh -c apk add --no-cache binutils build-base readline-dev openssl-dev ncurses-dev libsodium-dev git cmake gnu-libiconv zlib-dev && git clone --recurse-submodules https://github.com/SoftEtherVPN/SoftEtherVPN.git && cd SoftEtherVPN && ./configure && make -C tmp && make -C tmp install && tar -czf /artifacts.tar.gz /usr/local' returned a non-zero code: 2`
```

**Comment by davidebeatrici** [comment]
Replace `tmp` with `build` in the command:
```
apk add --no-cache binutils build-base readline-dev openssl-dev ncurses-dev libsodium-dev git cmake gnu-libico nv zlib-dev && git clone --recurse-submodules https://github.com/SoftEtherVPN/So ftEtherVPN.git && cd SoftEtherVPN && ./configure && make -C build && make -C build install && tar -czf /artifacts.tar.gz /usr/local
```

**Comment by Armik2** [comment]
> Replace `tmp` with `build` in the command:
> 
> ```
> apk add --no-cache binutils build-base readline-dev openssl-dev ncurses-dev libsodium-dev git cmake gnu-libico nv zlib-dev && git clone --recurse-submodules https://github.com/SoftEtherVPN/So ftEtherVPN.git && cd SoftEtherVPN && ./configure && make -C build && make -C build install && tar -czf /artifacts.tar.gz /usr/local
> ```

Thanks.

**Comment by Armik2** [comment]
del

**Comment by davidebeatrici** [comment]
No problem, we definitely have to improve the build instructions.

**Comment by Armik2** [comment]
Sorry. But now I have other problems the container does not start and gives such errors:
`root@dsch1-23259:~# docker start -ia a7978ab289e6
Error loading shared library libcedar.so: No such file or directory (needed by /usr/local/libexec/softether/vpnserver/vpnserver)
Error loading shared library libmayaqua.so: No such file or directory (needed by /usr/local/libexec/softether/vpnserver/vpnserver)
Error relocating /usr/local/libexec/softether/vpnserver/vpnserver: InitProcessCallOnce: symbol not found
Error relocating /usr/local/libexec/softether/vpnserver/vpnserver: FreeCedar: symbol not found
Error relocating /usr/local/libexec/softether/vpnserver/vpnserver: UnixService: symbol not found
Error relocating /usr/local/libexec/softether/vpnserver/vpnserver: InitCedar: symbol not found
Error relocating /usr/local/libexec/softether/vpnserver/vpnserver: StFree: symbol not found
Error relocating /usr/local/libexec/softether/vpnserver/vpnserver: StInit: symbol not found
Error relocating /usr/local/libexec/softether/vpnserver/vpnserver: StStopServer: symbol not found
Error relocating /usr/local/libexec/softether/vpnserver/vpnserver: StStartServer: symbol not found
Error relocating /usr/local/libexec/softether/vpnserver/vpnserver: VgUseStaticLink: symbol not found`

**Comment by davidebeatrici** [comment]
Where were the libraries installed (see CMake output)?

**Comment by Armik2** [comment]
here is the file I used to do:


[Dockerfile.zip](https://github.com/SoftEtherVPN/SoftEtherVPN/files/6139440/Dockerfile.zip)

**Comment by Armik2** [comment]
all this is too difficult for me))

**Comment by Armik2** [comment]
I found these files along the way: /var/lib/docker/overlay2/5690df5e45ccf46ac68949e663a7821a32ccd192d1e793d7aa84f7f4a581af0b/diff/usr/local/lib64

**Comment by paulmenzel** [comment]
As this is not about a compilation issues anymore, could you please close this issues and create a new issue?

**Comment by davidebeatrici** [comment]
Alternatively, I can rename the issue.

**Comment by paulmenzel** [comment]
Thank you. That’s a little better, but as no threading is supported in the comments, issues with a lot of comments are not as useful for other users searching for solutions for similar problems in the future. In this case, the issues description would also need to be updated, but then it’s confusing for those being subscribed to the project and the issues. Therefore, I always prefer one issue per problem. ;-)

**Comment by davidebeatrici** [comment]
Sure, in this case I think we can keep the same issue as it's not long and it's basically for support.

**Comment by chipitsine** [comment]
I'm afraid of using Alpine + musl, because it works differently from glibc.
lack of testing probably will lead to strange issues.

I'm not against strange issues. I'm againt "it is too difficult". ok, it is challenge and responsibility. 
everybody will benefit if someone owns alpline+musl testing (and it will be documented and presented as docker image)

**Comment by Armik2** [comment]
maybe something needs to be changed in "Dockerfile"?

**Comment by Armik2** [comment]
here is the compilation file:
[Softether Compile in Docker.zip](https://github.com/SoftEtherVPN/SoftEtherVPN/files/6140486/Softether.Compile.in.Docker.zip)

**Comment by Armik2** [comment]
have any thoughts?

**Comment by axot** [comment]
I'm using the following Dockerfile, the build itself seems smoothly, and once I launch the server with

```
# /usr/local/vpnserver/vpnserver execsvc
dmesg: read kernel buffer failed: Operation not permitted`
```
My question is that there is a way to run with non-root user?

Dockerfile
```
FROM debian:buster-slim
MAINTAINER axot

ENV VERSION v4.34-9745-rtm-2020.04.05
WORKDIR /usr/local/vpnserver

RUN set eux && \
    apt update && \
    apt install -y make gcc wget && \
    wget http://www.softether-download.com/files/softether/${VERSION}-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-${VERSION}-linux-x64-64bit.tar.gz -O /tmp/softether-vpnserver.tar.gz && \
    tar -xzvf /tmp/softether-vpnserver.tar.gz -C /usr/local/ && \
    rm /tmp/softether-vpnserver.tar.gz && \
    make i_read_and_agree_the_license_agreement && \
    apt remove -y make gcc
```

**Comment by chipitsine** [comment]
@axot , it is not clear how your issue is related to initial thread issue. Also, please notice this is issue tracker for 5.N versions, you downloaded 4.N

**Comment by axot** [comment]
@chipitsine I want to test the latest 5.x, but I can not found it in www.softether-download.com. Here, this thread want to solve that how to run it in container properly. So I posted in this thread.

**Comment by chipitsine** [comment]
5.x is not supposed to be on that website. that website is dedicated to 4.x
however this issue tracker is dedicated to 5.x

**Comment by axot** [comment]
Sure, any advice to run 5.x in container? If there is an official Dockerfle will be grateful. If there is no one for it, we could discuss how to make it works and I could also file PR for it.

**Comment by chipitsine** [comment]
There's no official Docker. If you are interested, you can contribute

**Comment by axot** [comment]
Okay, then let me try 5.x to see whether not the same `dmesg: read kernel buffer failed: Operation not permitted` happens. Any way do you know softether will work in lib-musl?

**Comment by chipitsine** [comment]
There's musl community, however it is small. Not sure how good SE VPN is tested in musl world

**Comment by davidebeatrici** [comment]
`dmesg: read kernel buffer failed: Operation not permitted` can be ignored if you're not running the server as `root`.

**Comment by axot** [comment]
Hi @davidebeatrici, could you share what the actually error was happened?

**Comment by davidebeatrici** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/192083e7c46ccf8155238eecccd222cad6c94d38/src/Mayaqua/Unix.c#L293-L328

**Comment by axot** [comment]
Thank you @davidebeatrici for sharing the code, I think if I am right, when softether is running in a non-root container, the result of  `UnixIsInVmMain` should be false, the main purpose of this cap was used for showing a dialog of the failure of bridge creation https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/Command.c#L9488

For creating a bridge, I think it is need to add NET_ADMIN to the container. And how to detect the program is running inside a container maybe a little trick.

**Comment by davidebeatrici** [comment]
You're right.

I believe we can actually just delete the VM-specific messages.
