### ISSUE TITLE
The dhclient is not working.

### ISSUE THREAD

**Issue by vhok74** [SoftEtherVPN/SoftEtherVPN#1298]
Hi. We received the latest version client from Ubuntu 20.04 and proceeded with the build. I created a virtual adapter through niccreate and set the vpn server settings on vpngate.net using accountcreate. And I checked that it is connected using account connection.
And I modified the sysctl.conf file.

However, ip cannot be dynamically assigned through the command "dhclient vpn_se". If you check with the -v option, only DHCPDISCOVER is confirmed. The DHCPOffer doesn't respond. I'll attach a picture. Where should I modify to get an ip from the dhcp server of the vpn server?
![image](https://user-images.githubusercontent.com/35132299/111322636-7a57bf80-86ac-11eb-8051-ece2a662196f.png)

![image](https://user-images.githubusercontent.com/35132299/111322660-804da080-86ac-11eb-8dd6-528ff55f0776.png)

**Comment by davidebeatrici** [comment]
Are you the owner of the server?

If that's the case, make sure a DHCP server is running.

**Comment by vhok74** [comment]
I only use clients. The server is trying to use https://www.vpngate.net/en/ here. The dhclient works in the standable version. However, it does not work with the instable version. Is there anything else you need to set up?

**Comment by davidebeatrici** [comment]
No, it's supposed to work just like the stable version.

**Comment by vhok74** [comment]
ok thank you!

**Comment by davidebeatrici** [comment]
Could you try ti run your own server and check whether the issue persists, please?

**Comment by vhok74** [comment]
The server and client must be set up after the build with the standable version before it can be connected. Is that right?

**Comment by vhok74** [comment]
We created a Ubuntu server for testing in the stable version and confirmed that it was connected to the Windows client. However, it does not connect with the Linux client. Is there any additional settings that Linux needs to do? For example, firewall settings...

**Comment by davidebeatrici** [comment]
The server port has to be opened in your firewall, yes.

**Comment by vhok74** [comment]
thank you

**Comment by ashah976** [comment]
did this work, I'm having the same issues no firewalls in place.  Simple connection to a virtual hub with virtual dhcp enabled, but no ip received on client

**Comment by domosekai** [comment]
I assume the issue has already been fixed in the latest version. Can reopen if necessary.
