### ISSUE TITLE
服务器连不上

### ISSUE THREAD

**Issue by yingxueziqi** [SoftEtherVPN/SoftEtherVPN#1299]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [ ] Can you reproduce?
* [ ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** [Server, Client, Bridge, etc.]
**Operating system:** [Windows, Linux, BSD, macOS, etc.]
**Architecture:** [64 bit, 32 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]

### Description

[Description of the bug]

**Expected behavior:**
[What you expected to happen]

**Actual behavior:**
[What actually happened]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [And so on...]

**Comment by yingxueziqi** [comment]
Since the two sessions of the Chinese Communist Party closed, most of the public servers of vpngate have been unable to connect. I personally guess that greatfirewall has used a new blocking strategy for vpngate, but the technology is not enough to prove it. If the situation is true, please improve the vpn protocol.

**Comment by chipitsine** [comment]
we are open for improvements, feel free to contribute.

also, we are not involved into confrontation between chinese people and chinese government. we do not take any part of this confrontation.

**Comment by yingxueziqi** [comment]
> 我们愿意改进，随时为您做贡献。
> 
> 同样，我们不参与中国人民与中国政府之间的对抗。我们不参与这场对抗的任何部分。

I understand this, after all, it is a public welfare project and should not have a political purpose.  But none of your public servers can be connected now, I personally suggest restarting it

**Comment by chipitsine** [comment]
this project is about source code. we do not run servers.

please contact server owners to restart their servers
