### ISSUE TITLE
China's firewall blocked openvpn agreement

### ISSUE THREAD

**Issue by fjyans** [SoftEtherVPN/SoftEtherVPN#130]
Will shield regular server, resulting vpn connection is not up, is there a way to break through the blockade China GFW?

**Comment by Cattze2015** [comment]
Maybe this is the time to add "Tor's hidden service".

xxxxxxxxxxxxxxxxxxxxx.onion.

**Comment by moatazelmasry2** [comment]
Did you try SoftEther Own vpn Protocol instead of OpenVPN???

**Comment by aicochow** [comment]
@fjyans 

you should try my server.
[download pdf file](https://github.com/aicochow/vpn/releases/download/v4.24/vpn.pdf)
