### ISSUE TITLE
Softethervpn client policy routing

### ISSUE THREAD

**Issue by Armik2** [SoftEtherVPN/SoftEtherVPN#1301]
Hello.  I am completely confused with routes and tables. In openwrt there is a separate package "wan and vpn-policy-routing" which is responsible for this and configures the table and routes itself. In ubuntu, you have to do everything by hand. How to set up the table and routes? I only need two ip to go through vpn.

**Comment by davidebeatrici** [comment]
You can use `iptables`.

**Comment by Armik2** [comment]
I'm not too strong at this

**Comment by Armik2** [comment]
del
