### ISSUE TITLE
After multiple users are created, restart is lost

### ISSUE THREAD

**Issue by matthuo333** [SoftEtherVPN/SoftEtherVPN#1303]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?
No
- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

[Y] Can you reproduce?
[Y] Are you running the latest version of SoftEtherVPN?

SoftEther version: 1.0-3
Component:Server
Operating system:Openwrt
**Architecture:ArmV8

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]

### Description

Step 1: After creating a user and configuring VPN Server, the remote access is normal.
Step 2: Add another user. After restarting the VPN Server, the user is lost. Similarly, if the L2TP PSK pre-shared key is modified, it will be restored to the previous one after restarting.

**Expected behavior:**
[What you expected to happen]

**Actual behavior:**
[What actually happened]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [And so on...]

**Comment by davidebeatrici** [comment]
Could you paste the server log, please?

**Comment by matthuo333** [comment]
It can't be reproduced for the time being . After you find out, upload the log immediately.
