### ISSUE TITLE
Does cross compile to arm linux supported?

### ISSUE THREAD

**Issue by 564398053** [SoftEtherVPN/SoftEtherVPN#1315]
Hi:

I want use SoftEhterVPN as a local bridge so the remote PC can access the local LAN.
I tested it works well with PC .

But for Internet of Things, most cases we do not have a PC to install SoftEhterVPN bridge. 
I want to deploy SoftEhterVPN  on a device that runs ARM Linux.
The ARM linux OS: Allwinner Linux A40i Platform V1.3

I have tried cross compile the project, but its hard and impossible for me to cross compile the whole project from scratch.

My question is:
Does SoftEhterVPN support cross compile for ARM Linux ?
If it supports, How ? 

Thanks :D

**Comment by paulmenzel** [comment]
What did you try to cross compile SoftEtherVPN?

I read, that people use SoftEtherVPN on Raspberry Pis, so it should be possible.

**Comment by 564398053** [comment]
I've tried cross compile guide by the following:
https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/blob/master/BUILD_UNIX.TXT

and it's seems that I have to cross compile it's Requirements first.
- GNU C Library (glibc).
- POSIX Threads (pthread).
- OpenSSL (crypto, ssl).
- libiconv.
- readline.
- ncurses.

While cross compile the requirements,  errors reported.
It's hard for me to get every thing right to compile these depedencies.

I'll try it again anyway. :D

**Comment by 564398053** [comment]
Since I'm a newbee in cross compile, I don't know how to change the makefile by hand.
I will use OpenVPN instead. It's has more tutorials for cross compile in China.

Close this issue.
