### ISSUE TITLE
Cleanup unwanted large files

### ISSUE THREAD

**Issue by yfdyh000** [SoftEtherVPN/SoftEtherVPN#132]
I see that you careless added some large files to commits 350927067a0e4e0b6a26a3424869d8ddb9ac9d02 - 71d1e667958308373972998cbc684d7e518ed94a (v4.13-9522-beta), I feel now is a good time to clean up them and rewrite the subsequent commits, otherwise it will lead to a permanent expansion for the git repository.

**Comment by dnobori** [comment]
Thank you for your advice. However, I do not understand how to perform the "clean up them and rewrite the subsequent commits" task. Could you please kindly tell me the exact command what I should do on the git command?

**Comment by yfdyh000** [comment]
https://help.github.com/articles/working-with-large-files/#removing-the-file-added-in-an-older-commit have a way; you might also consider other methods, use Google search it. Caution operating.

**Comment by dnobori** [comment]
Thank you! But I do not know how to use the Google search!

**Comment by yfdyh000** [comment]
Do you use TortoiseGit? It is a simple operation.
Show the Revision Log Dialog in the repo, select the three commits for v4.13-9522-beta, click the 'Combine to one commit' in the context menu. Reduce the duplicate message, commit it. Then, push it with 'Force (May discard known changes)' option.

sorry for I cannot give a straightforward method of operation for use git.exe or else.

**Comment by el1n** [comment]
```
git filter-branch --tree-filter 'git rm -rf --ignore-unmatch binary/' --prune-empty HEAD
git push -f
```
これで 350927067a0e4e0b6a26a3424869d8ddb9ac9d02 - 71d1e667958308373972998cbc684d7e518ed94a が削除されます

でもこれ以降のコミット全てが更新されるのである人がgit cloneした後にdnoboriさんが上記改変するとある人がコミットできなくなります

**Comment by el1n** [comment]
余談ですが.gitignore使うとこういうミスがなくなります

**Comment by dnobori** [comment]
ありがとうございました。上記コマンドで不要ファイル削除しました。

**Comment by yfdyh000** [comment]
Good job.
