### ISSUE TITLE
5.01.9675 version release

### ISSUE THREAD

**Issue by paskal** [SoftEtherVPN/SoftEtherVPN#1348]
Hi there! It would be great to release a new version, the last one was released on 30 Apr 2020, and I've received a bug report on [Ubuntu PPA](https://code.launchpad.net/~paskal-07/+archive/ubuntu/softethervpn) which doesn't reproduce on [nightly builds](https://launchpad.net/~paskal-07/+archive/ubuntu/softethervpn-nightly): I believe you fixed something since then and it's worth delivering to the users.

**Comment by davidebeatrici** [comment]
5.02.0 released!

**Comment by paskal** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/712534/119426720-053ae300-bd0a-11eb-8b29-eb86ce4f487a.png">
I get green build, you get green build, everyone gets green build, yay!

**Comment by davidebeatrici** [comment]
Awesome, thank you very much!
