### ISSUE TITLE
CMake returns error on latest code

### ISSUE THREAD

**Issue by scegg** [SoftEtherVPN/SoftEtherVPN#1349]
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** all
**Operating system:** Linux
**Architecture:** 64 bit

### Description

run cmake on latest code, returns error:
```
-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build date: 25/05/2021
-- Build time: 01:20:44
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:41 (find_package_handle_standard_args)
  src/Cedar/CMakeLists.txt:34 (find_package)


-- Configuring incomplete, errors occurred!
```

Log file is attached.
[CMakeOutput.log](https://github.com/SoftEtherVPN/SoftEtherVPN/files/6535825/CMakeOutput.log)

### Steps to reproduce

Pull code from github
git submodule update --init --recursive
cmake .

**Comment by davidebeatrici** [comment]
Install pkg-config.

**Comment by scegg** [comment]
> Install pkg-config.

Thanks. Also libsodium-dev is required.

**Comment by davidebeatrici** [comment]
Yes, for WireGuard. We have to update the dependencies list.
