### ISSUE TITLE
EAP identifier is reused

### ISSUE THREAD

**Issue by domosekai** [SoftEtherVPN/SoftEtherVPN#1350]
EAP identifier is controlled by `Eap_PacketId` which is always incremented like this.
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/97d9761a9b49bc539945045a54733b6ff29b4106/src/Cedar/Proto_PPP.c#L260-L262

However, there is one exception, the first one.
Since it's initially set to zero, when sending the first EAP packet by calling `PPPSendAndRetransmitRequest()`, the following if clause is triggered and the identifier is changed to 1. **This duplicates with the next EAP packet.**
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/97d9761a9b49bc539945045a54733b6ff29b4106/src/Cedar/Proto_PPP.c#L2249-L2252

I think it can start from 1 or more preferably, follow LCP identifier just as `MsChapV2_PacketId` does.
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/97d9761a9b49bc539945045a54733b6ff29b4106/src/Cedar/Proto_PPP.c#L3022-L3023

By the way, EAP Success and Failure packets should have the same identifier as Reponse. So these lines are not a hack.
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/97d9761a9b49bc539945045a54733b6ff29b4106/src/Cedar/Proto_PPP.c#L3278-L3281

**Comment by davidebeatrici** [comment]
Feel free to create a pull request.
