### ISSUE TITLE
error while loading shared libraries: libcedar.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by LinearAlpha** [SoftEtherVPN/SoftEtherVPN#1355]
- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

[*] Can you reproduce?
[*] Are you running the latest version of SoftEtherVPN?

SoftEther version: 5.2
Component: Server
Operating system: Linux (ubuntu on a )
Architecture: 64 bit 
Processor: raspberry pi 4  4GB

After compile and install it shows an error as shown below,
/usr/local/libexec/softether/vpnserver/vpnserver: error while loading shared libraries: libcedar.so: cannot open shared object file: No such file or directory

I even changed /usr/local/lib/libcedar.so permission to 755, but still it is showing the same error

**Comment by LinearAlpha** [comment]
After running fallowing commned it got solved,
sudo ln -s /usr/local/lib/libcedar.so /usr/lib/libcedar.so
sudo ln -s /usr/local/lib/libmayaqua.so /usr/lib/libmayaqua.so

**Comment by davidebeatrici** [comment]
In that case the issue is `/usr/local/lib` not being in `ld`'s search path list.

**Comment by LinearAlpha** [comment]
Those files are in the /usr/local/lib, but still, it shows an error.
Also, currently, L2TP and SoftEtherVPN clients cannot be connected to the VPN server.
