### ISSUE TITLE
How to enable TLS 1.0 and 1.1 when built with OpenSSL 1.1.1?

### ISSUE THREAD

**Issue by domosekai** [SoftEtherVPN/SoftEtherVPN#1358]
Hello, when I build either dev version or stable version from source on Debian 10 with Openssl 1.1.1d, TLS 1.0 and 1.1 clients can't connect. Only those with TLS 1.2 and 1.3 can.
However when I use the official binary (build 9745), it connects in all versions from 1.0 to 1.3. So it must be using 1.1.1 as well.
What should I do to make TLS 1.0 and 1.1 work in my builds?

**Comment by chipitsine** [comment]
OpenSSL on Debian 10 is built with TLS 1.0 disabled.

You may build your own separate openssl from source and link it using rpath

**Comment by domosekai** [comment]
Thank you for your quick answer. I will try it.

**Comment by domosekai** [comment]
I managed to get TLS 1.0 working by making a copy of `/etc/ssl/openssl.cnf` and change the last section like this.
```diff
361,362c361,362
< MinProtocol = TLSv1.2
< CipherString = DEFAULT@SECLEVEL=2
---
> MinProtocol = TLSv1
> CipherString = DEFAULT@SECLEVEL=1
```
Then set the environment by `export OPENSSL_CONF=new path to openssl.cnf` and run `vpnserver` again.
There is no need to rebuild the project or OpenSSL. (I actually rebuilt OpenSSL but it didn't work... could be my fault...)
This approach is obviously different from the official binary which does not need exporting. It's definitely not ideal but working.
This might duplicate with #1053 .

**Comment by chipitsine** [comment]
I did not mean to rebuild and install in place. Sorry for that.
I meant "install in separate folder ... and make it use separate openssl.cnf" :)

great you've figured it out.
also, there are some hardening in RHEL8 and maybe other modern distro as well.

should we adopt documentation ? or make changes in code ?
what would you suggest based on your experience ?

**Comment by domosekai** [comment]
Apparently Debian 10 and Ubuntu 20.04 have dropped TLS 1.0/1.1.
Since it's been over a year and there is very few complain so far, I assume most users are fine with the change. 🤔
I personally do not need these obsolete versions either. I was just doing some experiment with my app.
So if we change the code and overwrite the system default, the user might not even notice but we are actually introducing risks. 
To me a mention in the documentation sounds enough. At least the official binary still supports old versions and ordinary users would be just fine.

**Comment by davidebeatrici** [comment]
I would consider supporting TLS 1.0/1.1 when the system explicitly forbids it a bug.

**Comment by tew42** [comment]
Thanks for the pointers here, very helpful in fixing my #1525!

Just a quick comment for those running SoftEther as a service with the provided systemd files - I think the recommended way to implement the fix in this case should be to create a duplicate/edited OpenSSL `<new cnf file>` file as described by domosekai above, and then changing the environment variable at the service level, i.e. editing `softether-vpnserver.service` and adding the following line before ExecStart:
`Environment="OPENSSL_CONF=/etc/ssl/<new cnf file>"`
