### ISSUE TITLE
Feature Request: Adding custom route option in the client GUI.

### ISSUE THREAD

**Issue by harshil93** [SoftEtherVPN/SoftEtherVPN#137]
The user should have the option of adding some custom routes.
For eg. The user wants intranet ips to not use vpn.
Something like this
route ADD 172.16.27.23 MASK 255.255.255.255 192.168.1.1 METRIC 25 IF 16

**Comment by moatazelmasry2** [comment]
If you are using OpenVPN, this is easily done on the client side. Or are you using SoftEther own Protocol?

**Comment by domosekai** [comment]
Close due to inactivity
