### ISSUE TITLE
Release tarball is broken, lacks submodules

### ISSUE THREAD

**Issue by rofl0r** [SoftEtherVPN/SoftEtherVPN#1370]
Hello, i'm trying to package softethervpn for my distro, however the [autogenerated github-tarball-from-tag](https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck) lacks the contents of the git submodules and is therefore useless; as one needs to use git anyhow to fetch the sources - which in turn is not compatible with our (and most other distro's) build framework.

the only feasible solution is to ship a source tarball that contains *all* sources, this, however, requires that the tarball is created (e.g. by using a script) and attached by hand to the release tag.
alternatively, it's possible to have it done automatically as a github action, i've implemented it for another project [in this PR](https://github.com/WebAssembly/wabt/pull/1615).

**Comment by davidebeatrici** [comment]
Hello, thank you very much for reporting the issue.

We used AppVeyor at one point to create and upload the tarball for past tags, however I would definitely prefer a dedicated GitHub Action to do that instead. Feel free to create a pull request!

**Comment by rofl0r** [comment]
thanks for the merge, i'm gonna leave this open until there is a tarball created with the new GH action... or do you think it is possible to manually trigger the action from "actions" panel to existing last tag ?
