### ISSUE TITLE
Coverity workflow: Configure fails with `None of the required 'libsodium' found`

### ISSUE THREAD

**Issue by paulmenzel** [SoftEtherVPN/SoftEtherVPN#1372]
Looking at the [workflow Coverity #108][1], configure fails:

```
-- Checking for one of the modules 'libsodium'
CMake Error at /usr/local/share/cmake-3.20/Modules/FindPkgConfig.cmake:843 (message):
  None of the required 'libsodium' found
Call Stack (most recent call first):
  src/Cedar/CMakeLists.txt:35 (pkg_search_module)
[…]
 -- Configuring incomplete, errors occurred!
See also "/home/runner/work/SoftEtherVPN/SoftEtherVPN/build/CMakeFiles/CMakeOutput.log".
See also "/home/runner/work/SoftEtherVPN/SoftEtherVPN/build/CMakeFiles/CMakeError.log".
```

The `|| true` in the workflow configuration covers this issue up.

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/192083e7c46ccf8155238eecccd222cad6c94d38/.github/workflows/coverity.yml#L26-L30

[1]: https://github.com/SoftEtherVPN/SoftEtherVPN/runs/2815671030?check_suite_focus=true

**Comment by davidebeatrici** [comment]
Thanks, feel free to create a pull request!

**Comment by chipitsine** [comment]
btw, @paulmenzel  there are about 50 unresolved coverity issues. if you have an appetite for them, I can add permissions to you (I did not find how to make all issues public)

**Comment by YangShizhao** [comment]
hi，I met the same problem today, when I try to build the project, the message was shown, followed with an openssl not found message. is this a new issue or something else?
![image](https://user-images.githubusercontent.com/13344900/147800214-eb83988c-e89e-4cfd-86e8-f62d3655ee22.png)
