### ISSUE TITLE
m1 ship not supported 

### ISSUE THREAD

**Issue by SlashTec** [SoftEtherVPN/SoftEtherVPN#1375]
Hi there 
Thanks for providing this awesome product.
is there a plan for the VPN client to support the mac m1 ship?

**Comment by davidebeatrici** [comment]
Hi, have you tried compiling the project? Do problems arise at runtime?

**Comment by chipitsine** [comment]
I guess it is 4.x <--> 5.x versioning issue.

**Comment by chipitsine** [comment]
btw, Oracle Cloud offers Ampere arm64 machines, I was able to build / run / whatever using Ubuntu 21.04 arm 64 vm.

**Comment by domosekai** [comment]
Close as compiling on M1 has succeeded.

**Comment by parsanoori** [comment]
Why isn't the binary available [here](https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/) ?

**Comment by mohammad-aqajani** [comment]
not sure if it works, I found it by google:
https://apps.apple.com/us/app/sstp-connect/id1543667909
