### ISSUE TITLE
Linux Client Issues Across Most Modern OSes

### ISSUE THREAD

**Issue by andrewfer000** [SoftEtherVPN/SoftEtherVPN#1387]
### Prerequisites

* [x] Can you reproduce? - Yes
* [x] Are you running the latest version of SoftEtherVPN? -Yes (version 4.36 released in 06/2021 from softether.org)

**SoftEther version:**
**Component:** [Client]
**Operating system:** [Linux]
**Architecture:** [64 bit]

### Description

[Description of the bug]

**Expected behavior:**
The VPN Client connects to the server, gets an IP address with `dhclient`, and allows network access and internet access.

**Actual behavior:**
The VPN client connects to the server and gets an IP address with `dhclient` but cannot communicate on the LAN segment or the Internet. 

### Steps to reproduce

1. Download and make the VPN client and start it as root. then use vpncmd to configure a connection
2. Connect to the VPN server and ensure to run `AccountList` to see that it's `Connected`
3. Run `sudo dhclient vpn_adaptername` to obtain an IP address from the DHCP server and run `ip a` to verify it has one
4. Try to connect to a website such as https://ipv6-test.com/ and either only see your current ISP address or not connect at all
5. Try to ping the virtual hub address (in my case 192.168.30.1) and get nothing

Maybe I'll pull down the absolute latest code client and/or server from Github and test it out. I understand not having internet access, but not being able to communicate on the virtual network segment when it has an assigned IP address from SecureNAT is very strange.

**Comment by andrewfer000** [comment]
UPDATE: I just tested this with the latest code for both Client and Server in my home and still the same issue occurs.

**Comment by chipitsine** [comment]
sorry, this issue tracker is for 5.X versions.
can you try please building from source (this repo) ?

softether.org is SoftEtherVPN Stable edition, it is different beast.

**Comment by andrewfer000** [comment]
@chipitsine as you can see in my Update above, I have also tired the the latest code from this branch. It has the exact same issue sadly.

**Comment by andrewfer000** [comment]
UPDATE: It seems Ubuntu 20.04 LTS on kernel 5.8 works with Client and Server from the repository (5.0.2-0). It just took some time to set itself up. After 2 minutes IPv4 and IPv6 seem to be working. (I tested IPv6 which is globally routed and IPv4 on a LAN device).

**Comment by domosekai** [comment]
Since your external IP unchanged after VPN is connected, it is a routing issue unrelated to softether. You didn't add the default route.

**Comment by andrewfer000** [comment]
> Since your external IP unchanged after VPN is connected, it is a routing issue unrelated to softether. You didn't add the default route.

Yeah I know, I'm not too worried about the defualt route for internet traffic. My goal is to have a "Virtual LAN" between IoT devices and VPS machines.

 But on my Linux laptop I would like to know how to setup the static route to send data through the VPN. I can get IPv6 to work on network that does not have native IPv6 but IPv4 is still the original IP.

**Comment by domosekai** [comment]
If you are asking a question, state it clearly instead of speaking as if softether has a bug.

**Comment by andrewfer000** [comment]
Well at first when I originaly made this issue, I couldn't communicate with the network (LAN) that I was connecting to at all when using the SoftEther vpnclient. But on Ubuntu 20.04 LTS with Kernel 5.8 it works with no issue. I need to re-test Manjaro, Fedora and my Ubuntu 20.04 with kernel 5.10 to rule out if it's a kernel issue. At first I thought it was SoftEther but now i'm starting to think it could be kernel or network stack related. 

I'm sorry if it sounded like a SE bug, I thought it was at first, but after doing some testing it might be somthing on the Linux side. I made this issue to get input/feedback if anyone else was expreicing the same thing.

**Comment by domosekai** [comment]
Close since it's not a bug. Leave comments if you found new evidence.
