### ISSUE TITLE
Latest Version of SoftEther VPN Server does not listen on UDP Ports

### ISSUE THREAD

**Issue by andrewfer000** [SoftEtherVPN/SoftEtherVPN#1388]
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version: Latest Github pull as of 06/20/2021**
**Component:** [Server]
**Operating system:** [Linux, Ubuntu 20.04]
**Architecture:** [64 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]

### Description

SoftEther VPN Server does not listen on UDP Ports on IPv4. 

**Expected behavior:**
The VPN Server should listen on the UDP Ports and L2TP/IPsec Ports on IPv4 when enabled

**Actual behavior:**
The VPN server only listens to the TCP ports on IPv4 and the UDP ports on IPv6

### Steps to reproduce

1. Compile the latest version of SoftEther VPN server and configure it
2. Enable L2TP/IPsec as normal
3. run `netstat -tlupn` and see that the UDP Ports on IPv4 are not open.

This is NOT an issue on SoftEther version 4.36 that was built in 06/2021. This has only been happening with this new code.

**Comment by davidebeatrici** [comment]
Are you using the `ListenIP` setting?

**Comment by andrewfer000** [comment]
No? Is there a way to set that?

**Comment by davidebeatrici** [comment]
Yes, in the configuration file.

**Comment by andrewfer000** [comment]
I fixed it by setting the `ListenIP ::` to `ListenIP *` Now it Listens on UDP on IPv4 but not on IPv6. Is there a way to do both? (multiple IPs?)

**Comment by davidebeatrici** [comment]
Unfortunately not, see #1328.

**Comment by metalefty** [comment]
Hi, I was about to file an issue identical to this yesterday. It appears ports set by `PortsUDPSet` are not listening on.
Other ports such as IPsec `500/udp`, `4500/udp` are listening.

**Comment by domosekai** [comment]
At least in Linux, UDP listeners do not need to listen at IPv4 address anymore, because IPv6 listeners are capable to do IPv4 as well, as long as `IPV6_V6ONLY` is false.

**Comment by davidebeatrici** [comment]
Excellent point. I think we should provide granular control though.

In fact, I'm working on making the `ListenIP` setting listener-specific.

**Comment by domosekai** [comment]
> Excellent point. I think we should provide granular control though.
> 
> 
> 
> In fact, I'm working on making the `ListenIP` setting listener-specific.

I understand. So I fixed the issue without touching the definition of `ListenIP`. (I was thinking of making it optional but that would create compatibility issues.)

Also I ended up not using dual stack listener because there is lots of stuff needed to be changed accordingly. For example, a UDP v6 listener handling v4 connections.

**Comment by shwuhk** [comment]
We can't use L2TP and OpenVPN udp at the moment on ubuntu 20.04. May I know if there is any quick fix now to make it work? Thanks

**Comment by domosekai** [comment]
This issue is already fixed. You may compile from the master branch to see if it works for you. If not you may open another issue.
