### ISSUE TITLE
make erro on linux ,there is no such file ?

### ISSUE THREAD

**Issue by otakukyoto** [SoftEtherVPN/SoftEtherVPN#139]
compilation erro  under 64bit linux:
"src/Mayaqua/Mayaqua.h:285:31: fatal error: readline/readline.h: No such file or directory
 #include --- readline/readline.h----

compilation terminated.
make: **\* [tmp/objs/Mayaqua/Cfg.o] Error 1
"

**Comment by NiuQiang** [comment]
I met the same question?can you tell me how to solve this problem?

**Comment by cjm0000000** [comment]
same question too. Please help!

**Comment by PawelDefee** [comment]
See src/BUILD_UNIT.TXT, it gives you instructions on the dependencies. In your case, the readline development library needs to be installed, for example in Fedora:

`yum -y install readline-devel`

or Ubuntu:

`sudo apt-get install libreadline6 libreadline6-dev`

**Comment by moatazelmasry2** [comment]
@PawelDefee  answered the question correctly. Closing this issue
