### ISSUE TITLE
Possible Race Condition

### ISSUE THREAD

**Issue by jishanshaikh4** [SoftEtherVPN/SoftEtherVPN#1398]
Also see #1394 

Possible race condition (CWE-362). This accepts filename arguments; if an attacker can move those files, a race condition results. (CWE-362).

LABEL: Bug
SEVERITY: Major
SOLUTION: Use fchmod( ) instead.

- [ ] src\Mayaqua\Unix.c:820

**Comment by andrewfer000** [comment]
Not sure if this is correct but I changed line 820 to `(void)fchmod(fd, mode);` The server seems to compile and work.

**Comment by jishanshaikh4** [comment]
> Not sure if this is correct but I changed line 820 to `(void)fchmod(fd, mode);` The server seems to compile and work.

That's exactly what we needed to do.

**Comment by lixh1223** [comment]
CentOS7版视频安装教程：https://youtu.be/fWGw6Qdh1pY
Windows版视频安装教程：https://youtu.be/lXb7FxxEcE0
