### ISSUE TITLE
latest version(5.02 5180) cannot push correct static route to the client

### ISSUE THREAD

**Issue by ricksuzade-maker** [SoftEtherVPN/SoftEtherVPN#1399]
Follow these steps to config static route:
1. Open SoftEther Server Manager
2. Double Click on your hub name
3. Click on "Virtual Nat and virtual DHCP Settings"
4. Click on SecureNAT Configurations
5. Click on the static routing table to push
6. Add routes you want as described in that window

But the client cannot get the route as configered above, and the client always gets the 0.0.0.0 route.

**Comment by ricksuzade-maker** [comment]
The last version that can push correct static route is apr.7.2021 and commit id is: 
  01663f836d6438a4b0b82e40f863bda72251f242

The bug would be introduced by the two commits of apr.8.2021. commit ids are: 
 192083e7c46ccf8155238eecccd222cad6c94d38
  1708998a11c72e4775889979d91780d66912fb14

**Comment by davidebeatrici** [comment]
Thank you very much for the detailed report!

For a moment I thought it was another hardcoded build number issue, glad to know that's not the case.

**Comment by ricksuzade-maker** [comment]
glad to do some help. this project is great!

**Comment by ricksuzade-maker** [comment]
is there anyway to workaround for it? macos or windows is ok to set static route locally, but android and ios cannot do the same way. thanks for your help.

**Comment by domosekai** [comment]
@davidebeatrici If you don't have time I can help on this.

**Comment by davidebeatrici** [comment]
That would be great, thanks!
