### ISSUE TITLE
Compilation error, which library is not installed

### ISSUE THREAD

**Issue by summerwindy** [SoftEtherVPN/SoftEtherVPN#1405]
server is centos 7 mini 

[root@localhost SoftEtherVPN]# make -C build
make: Entering directory `/usr/local/SoftEtherVPN/build'
make[1]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[  4%] Built target libhamcore
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[  6%] Built target hamcorebuilder
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[  7%] Built target hamcore-archive-build
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 57%] Built target cedar
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 68%] Built target cpu_features
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 90%] Built target mayaqua
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 91%] Built target list_cpu_features
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
[ 92%] Linking C executable ../../vpnserver
../../libmayaqua.so: undefined reference to `EVP_ENCODE_CTX_new'
../../libmayaqua.so: undefined reference to `EVP_ENCODE_CTX_free'
../../libmayaqua.so: undefined reference to `EVP_PKEY_get0_RSA'
collect2: error: ld returned 1 exit status
make[2]: *** [vpnserver] Error 1
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
make[1]: *** [src/vpnserver/CMakeFiles/vpnserver.dir/all] Error 2
make[1]: Leaving directory `/usr/local/SoftEtherVPN/build'
make: *** [all] Error 2
make: Leaving directory `/usr/local/SoftEtherVPN/build'
[root@localhost SoftEtherVPN]#

when run make -C build Compilation error, which library is not installed？ thanks！

**Comment by chipitsine** [comment]
seems we locked to "OpenSSL-1.1.1" or higher.

I'll add guard for EVP_ENCODE_CTX_new
not sure if we have good workaround for earlier openssl

what is your openssl version ? is it possible to update to 1.1.1 ?

**Comment by chipitsine** [comment]
btw, on centos 7 I recall "openssl11" package (and "openssl11-devel" probably)

**Comment by summerwindy** [comment]
I find this close issue . 
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1259

thank you , let me upgrade and   try it again.

**Comment by summerwindy** [comment]
I upgrade openssl from 1.0 to 1.1.1g 

[root@localhost SoftEtherVPN]# make -C build
make: Entering directory `/usr/local/SoftEtherVPN/build'
make[1]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[  4%] Built target libhamcore
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[  6%] Built target hamcorebuilder
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[  7%] Built target hamcore-archive-build
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 57%] Built target cedar
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 68%] Built target cpu_features
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 90%] Built target mayaqua
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 91%] Built target list_cpu_features
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
[ 92%] Linking C executable ../../vpnserver
../../libmayaqua.so: undefined reference to `EVP_ENCODE_CTX_new'
../../libmayaqua.so: undefined reference to `EVP_ENCODE_CTX_free'
../../libmayaqua.so: undefined reference to `EVP_PKEY_get0_RSA'
collect2: error: ld returned 1 exit status
make[2]: *** [vpnserver] Error 1
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
make[1]: *** [src/vpnserver/CMakeFiles/vpnserver.dir/all] Error 2
make[1]: Leaving directory `/usr/local/SoftEtherVPN/build'
make: *** [all] Error 2
make: Leaving directory `/usr/local/SoftEtherVPN/build'
[root@localhost SoftEtherVPN]# openssl version
OpenSSL 1.1.1g FIPS  21 Apr 2020

**Comment by summerwindy** [comment]
I had upgrade to 1.1.1g , but the issue still happened.


[ 56%] Building C object src/Cedar/CMakeFiles/cedar.dir/__/__/3rdparty/BLAKE2/sse/blake2s.c.o
[ 57%] Linking C shared library ../../libcedar.so
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 57%] Built target cedar
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 68%] Built target cpu_features
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 90%] Built target mayaqua
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
[ 91%] Built target list_cpu_features
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
make[2]: Entering directory `/usr/local/SoftEtherVPN/build'
[ 92%] Linking C executable ../../vpnserver
../../libmayaqua.so: undefined reference to `EVP_ENCODE_CTX_new'
../../libmayaqua.so: undefined reference to `EVP_ENCODE_CTX_free'
../../libmayaqua.so: undefined reference to `EVP_PKEY_get0_RSA'
collect2: error: ld returned 1 exit status
make[2]: *** [vpnserver] Error 1
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
make[1]: *** [src/vpnserver/CMakeFiles/vpnserver.dir/all] Error 2
make[1]: Leaving directory `/usr/local/SoftEtherVPN/build'
make: *** [all] Error 2
make: Leaving directory `/usr/local/SoftEtherVPN/build'
[root@localhost SoftEtherVPN]# openssl version
OpenSSL 1.1.1g FIPS  21 Apr 2020
[root@localhost SoftEtherVPN]#

**Comment by chipitsine** [comment]
please try deleting "build" subfolder and starting from scratch.

also, please provide output of `rpm -qa | grep openssl`

**Comment by summerwindy** [comment]
[ 92%] Building C object src/vpnserver/CMakeFiles/vpnserver.dir/vpnserver.c.o
[ 93%] Linking C executable ../../vpnserver
../../libmayaqua.so: undefined reference to `RSA_get0_key'
../../libmayaqua.so: undefined reference to `SSL_CTX_set_security_level'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_pop_free'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_value'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_new_null'
../../libmayaqua.so: undefined reference to `X509_STORE_CTX_get0_cert'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_push'
../../libmayaqua.so: undefined reference to `EVP_MD_CTX_new'
../../libmayaqua.so: undefined reference to `EVP_ENCODE_CTX_new'
../../libmayaqua.so: undefined reference to `DH_get0_key'
../../libmayaqua.so: undefined reference to `RSA_get0_crt_params'
../../libmayaqua.so: undefined reference to `SSL_get1_supported_ciphers'
../../libmayaqua.so: undefined reference to `HMAC_CTX_free'
../../libmayaqua.so: undefined reference to `SSL_CTX_get_security_level'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_num'
../../libmayaqua.so: undefined reference to `X509_get0_notBefore'
../../libmayaqua.so: undefined reference to `EVP_ENCODE_CTX_free'
../../libmayaqua.so: undefined reference to `EVP_PKEY_get0_RSA'
../../libmayaqua.so: undefined reference to `OPENSSL_init_crypto'
../../libmayaqua.so: undefined reference to `ASN1_STRING_get0_data'
../../libmayaqua.so: undefined reference to `TLS_method'
../../libmayaqua.so: undefined reference to `TLS_client_method'
../../libmayaqua.so: undefined reference to `EVP_MD_CTX_free'
../../libmayaqua.so: undefined reference to `X509_get0_notAfter'
../../libmayaqua.so: undefined reference to `SSL_CTX_set_options'
../../libmayaqua.so: undefined reference to `HMAC_CTX_new'
../../libmayaqua.so: undefined reference to `OPENSSL_thread_stop'
../../libmayaqua.so: undefined reference to `DH_set0_pqg'
../../libmayaqua.so: undefined reference to `RSA_get0_factors'
../../libmayaqua.so: undefined reference to `TLS_server_method'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_free'
collect2: error: ld returned 1 exit status
make[2]: *** [vpnserver] Error 1
make[2]: Leaving directory `/usr/local/SoftEtherVPN/build'
make[1]: *** [src/vpnserver/CMakeFiles/vpnserver.dir/all] Error 2
make[1]: Leaving directory `/usr/local/SoftEtherVPN/build'
make: *** [all] Error 2
make: Leaving directory `/usr/local/SoftEtherVPN/build'
[root@localhost SoftEtherVPN]# rpm -qa | grep openssl
openssl-devel-1.0.2k-21.el7_9.x86_64
openssl11-1.1.1g-3.el7.x86_64
openssl-libs-1.0.2k-21.el7_9.x86_64
openssl11-devel-1.1.1g-3.el7.x86_64
openssl-1.0.2k-21.el7_9.x86_64
openssl11-libs-1.1.1g-3.el7.x86_64
[root@localhost SoftEtherVPN]#

**Comment by chipitsine** [comment]
looks like cmake picks default openssl-1.0.2

we override openssl for CI builds https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.travis.yml#L71-L73
it is not a proper how to, but should be good script to start with :)

**Comment by chipitsine** [comment]
issue 1259 is not related.
looks like the most recent commit https://github.com/SoftEtherVPN/SoftEtherVPN/commit/233e28f38ce7decd56f7dc7438ae7b847303a764 introduced openssl-1.1.1 requirement (it is not bad, but documentation and cmake should be updated)

**Comment by summerwindy** [comment]
I had successful install it on CentOS Linux release 7.9.2009 (Core)

this is my history

    1  cd /usr/local/
    2  yum install git
    3  git init
    4  git
    5  git add https://github.com/SoftEtherVPN/SoftEtherVPN.git
    6  git submodule add https://github.com/SoftEtherVPN/SoftEtherVPN.git
    7  yum -y groupinstall "Development Tools"
    8  cmake
    9  cmake –version
   10  yum install -y wget
   11  yum install openssl11-devel
   12  wget -c https://github.com/Kitware/CMake/releases/download/v3.17.0-rc3/cmake-3.17.0-rc3.tar.gz
   13  tar zxvf cmake-3.17.0-rc3.tar.gz
   14  cd cmake-3.17.0-rc3./bootstrap
   15  gmake
   16  gmake install
   17  yum install gmake
   18  ls
   19  rm -rf cmake-3.17.0-rc3
   20  rm -rf cmake-3.17.0-rc3.tar.gz
   21  wget https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5.tar.gz
   22  tar -zxf cmake-3.15.5.tar.gz
   23  cd cmake-3.15.5
   24  ./bootstrap --prefix=/usr --datadir=share/cmake --docdir=doc/cmake && make
   25  sudo make install
   26  cmake version
   27  cmake -version
   28  cd ..
   29  ls
   30  cd SoftEtherVPN/
   31  ./configure
   32  git submodule update --init --recursive
   33  cd ..
   34  git submodule update --init --recursive
   35  cd SoftEtherVPN/
   36  ./configure
   37  cd ..
   38  wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable.tar.gz
   39  tar -zxf libsodium-1.0.18-stable.tar.gz
   40  cd libsodium-stable
   41  ./configure --prefix=/usr
   42  make && make check
   43  sudo make install
   44  sudo ldconfig
   45  ls
   46  cd ..
   47  ls
   48  cd SoftEtherVPN/
   49  ls
   50  ./configure
   51  cd ..
   52  yum libsodium-stable/
   53  cd libsodium-stable/
   54  make install
   55  ls
   56  cd ..
   57  ls
   58  cd SoftEtherVPN/
   59  ./configure
   60  yum install libsodium-devel
   61  ./configure
   62  yum install wlibsodium
   63  ./configure
   64  yum install boost
   65  ./configure
   66  cmake –graphviz
   67  cmake-graphviz
   68  ./configure
   69  yum install ncurses-devel
   70  ./configure
   71  openssl -version
   72  openssl
   73  openssl version
   74  cd ..
   75  ls
   76  wget https://www.openssl.org/source/openssl-1.1.1g.tar.gz
   77  tar xzvf openssl-1.1.1g.tar.gz
   78  cd openssl-1.1.1g
   79  ls
   80  ./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic make make install
   81  ./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic
   82  make
   83  make install
   84  export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
   85  echo "export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64"
   86  openssl version
   87  cd ..
   88  ls
   89  cd SoftEtherVPN/
   90  ls
   91  ./configure
   92  yum install libncurses-dev
   93  yum install readline-devel
   94  yum install readline
   95  yum install readline-devel
   96  ./configure
   97  make -C build
   98  history
   99  systemctl start vpnserver.service
  100  ls
  101  netstat -an
  102  netstat -tlnup
  103  ls
  104  cd systemd/
  105  ls
  106  less softether-vpnserver.service
  107  ls
  108  make -C build
  109  make install
  110  cd ..
  111  ls
  112  cd src/
  113  ls
  114  cd vpnserver/
  115  ls
  116  ls -l
  117  cd ..
  118  ls
  119  cd ..
  120  ls
  121  ls -l
  122  cd build/
  123  ls
  124  ./vpnserver
  125  ./vpnserver start
  126  netstat -tlnup
  127  yum -y install iptables-services
  128  systemctl stop firewalld.service
  129  systemctl disable firewalld.service
  130  ls -l /etc/*-release
  131  cat /etc/redhat-release
  132  history

**Comment by summerwindy** [comment]
@chipitsine  Thank your help  :)

**Comment by chipitsine** [comment]
you specified `--prefix=/usr`, but later you use `export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64`

glad it works for you, but I do not understand why

**Comment by summerwindy** [comment]
export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64   

is unnecessary , Haha  :)
