### ISSUE TITLE
How can I set up a dedicated IP for each user?

### ISSUE THREAD

**Issue by abolfazl-biria** [SoftEtherVPN/SoftEtherVPN#1412]
Hi

**Comment by abolfazl-biria** [comment]
I want to give a dedicated IP to the user. What should I do for this purpose?

**Comment by dnobori** [comment]
See https://www.softether.org/5-download/history/
SoftEther VPN 4.31 Build 9727 Beta (November 18, 2019)
Added the new function to reserve and each Virtual MAC address and IP address for each user of L2TP/IPsec, SSTP and OpenVPN L3.

**Comment by abolfazl-biria** [comment]
There is no other way?

**Comment by abolfazl-biria** [comment]
I want to do this using C #

**Comment by dnobori** [comment]
You can use C# to control your DHCP server to assign each user's IP address.

**Comment by davidebeatrici** [comment]
A user always has a unique IP under normal circumstances. Did you perhaps mean "static IP" instead?

In that case, you can use the feature mentioned by @dnobori. To enforce the IP address, you can use the dedicated user policy.

**Comment by PeTeeR-mpl** [comment]
Hi,
this issue was fixed by pull request #1218

**Comment by davidebeatrici** [comment]
I'm not sure what the user is trying to achieve exactly, but let's close the issue for now.
