### ISSUE TITLE
Revert bool type refactor to restore IPv6 listeners

### ISSUE THREAD

**Issue by domosekai** [SoftEtherVPN/SoftEtherVPN#1413]
### Description

The current version doesn't listen at IPv6 TCP sockets, as mentioned in #1308 .
At first I thought it was the side effect of #1321 , which changed the IP structure. But I was wrong.
The reason turned out to be in https://github.com/SoftEtherVPN/SoftEtherVPN/commit/914bfe7d44f8e693d21178055f0b845c613dc777 we changed the definition of `bool` type.

### Explanation

Unix `bool` type is just `int`, which is 4-byte long. But after the refactor, the `bool` we are using now is 1-byte from C99.
Since `setsockopt()` takes `int` flags, it is not working anymore. 
Especially, `IPV6_V6ONLY` option is not set to true and IPv6 listeners always fail due to the same address already occupied by IPv4 listeners.

### Temporary fix

I am able to restore the IPv6 listening function by changing `bool` to `int` type in Network.c.
However, we had better revisit the refactor and make further fixes. For this reason, I am not posting this as a PR.
Also, I am not sure about the consequences in Win32.

```diff
diff --git a/src/Mayaqua/Network.c b/src/Mayaqua/Network.c
index 3c20154f..3b56b0b5 100644
--- a/src/Mayaqua/Network.c
+++ b/src/Mayaqua/Network.c
@@ -12883,13 +12883,13 @@ SOCK *ListenEx62(UINT port, bool local_only, bool enable_ca)
                return NULL;
        }

-       bool true_flag = true;
+       int true_flag = 1;^M
 #ifdef OS_UNIX
        // It is necessary to set the IPv6 Only flag on a UNIX system
        (void)setsockopt(s, IPPROTO_IPV6, IPV6_V6ONLY, &true_flag, sizeof(true_flag));
        // This only have enabled for UNIX system since there is a bug
        // in the implementation of REUSEADDR in Windows OS
-       (void)setsockopt(s, SOL_SOCKET, SO_REUSEADDR, (char *)&true_flag, sizeof(bool));
+       (void)setsockopt(s, SOL_SOCKET, SO_REUSEADDR, (char *)&true_flag, sizeof(true_flag));^M
 #endif // OS_UNIX

        if (bind(s, (struct sockaddr *)&addr, sizeof(struct sockaddr_in6)) != 0)
@@ -12984,11 +12984,11 @@ SOCK *ListenEx2(UINT port, bool local_only, bool enable_ca, IP *listen_ip)
                return NULL;
        }

-       bool true_flag = true;
+       int true_flag = 1;^M
 #ifdef OS_UNIX
        // This only have enabled for UNIX system since there is a bug
        // in the implementation of REUSEADDR in Windows OS
-       (void)setsockopt(s, SOL_SOCKET, SO_REUSEADDR, (char *)&true_flag, sizeof(bool));
+       (void)setsockopt(s, SOL_SOCKET, SO_REUSEADDR, (char *)&true_flag, sizeof(true_flag));^M
 #endif // OS_UNIX

        if (bind(s, (struct sockaddr *)&addr, sizeof(struct sockaddr_in)) != 0)
```

**Comment by davidebeatrici** [comment]
UNIX doesn't have a specification for `bool` as far as I know.

The reason why our datatype's size was originally 4 bytes is because it was based on the one provided by the Windows SDK: https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/blob/ddc99f085fd6c54feaf4e41912bc8ab5903bdf8e/src/Mayaqua/MayaType.h#L244-L260

I personally consider it a waste of memory, as the type is only supposed to represent either `0` or `1`.

`true_flag` being `bool` instead of `int` is a bug. Your fix is correct.

Feel free to create a pull request, as `setsockopt()`'s signature is the same on Windows: https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-setsockopt

**Comment by domosekai** [comment]
True. Unix has no `bool` type. The proper way to say is that Unix conventionally uses `int` as boolean flags.

**Comment by davidebeatrici** [comment]
Yes, indeed.

Until C99 `bool` didn't officially exist, which is why many projects had (or still have) their own datatype and you have to include `<stdbool.h>` in order to define it.
