### ISSUE TITLE
a strange bug

### ISSUE THREAD

**Issue by ajdgsu** [SoftEtherVPN/SoftEtherVPN#1419]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [yes ] Can you reproduce?
* [ yes] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** [Server]
**Operating system:** [Linux]
**Architecture:** [64 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [doesn't matter]

### Description

[the newest version (5.02.5180) has some code issuse, i have to useing dos2unix convert them to success compile (i'm not sure which file  did this problem because i convert all the files by dos2unix)]

**Expected behavior:*
[just work]

**Actual behavior:**
[Hunk #1 FAILED at 9 (different line endings)]

### Steps to reproduce

1.[i guess just compile it]

**Comment by davidebeatrici** [comment]
While it's true that most files in the repository use CRLF right now, you should encounter no issues compiling the code.

> [Hunk #1 FAILED at 9 (different line endings)]

Did you perhaps attempt to rebase from `master` after committing the change from CRLF to LF?

**Comment by ajdgsu** [comment]
No, actually im try to build up a 3rd openwrt (https://github.com/xiaoqingfengATGH/HomeLede) and it include your program, but this openwrt useing your

**Comment by ajdgsu** [comment]
No, actually im try to build up a 3rd openwrt (https://github.com/xiaoqingfengATGH/HomeLede) and it include your program, but this openwrt useing 
a makefile to add your program.(noticed that i  changed PKG_HASH because dos2unix did modified the source file )
[Makefile.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/6786813/Makefile.txt)

**Comment by davidebeatrici** [comment]
Where is SoftEther VPN being included in the project you linked?
