### ISSUE TITLE
OpenVPN settings commands are missing in the latest version Softether 5.02 Build 9675

### ISSUE THREAD

**Issue by SHRDLU19** [SoftEtherVPN/SoftEtherVPN#1424]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [yes] Can you reproduce?
* [yes] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** [Server]
**Operating system:** [BSD]
**Architecture:** [64 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Intel(R) Xeon(R) CPU E5-2640 v4]

### Description

[I can't use any OpenVPN clone server configuration command in vpncmd interface after upgrade my SoftEther VPN server to version 5.02 - with the exception of OpenVpnMakeConfig command:]

**Expected behavior:**
[VPN Server>OpenVpnGet
OpenVpnGet command - Get the Current Settings of OpenVPN Clone Server Function
Item                        |Value
----------------------------+-----
OpenVPN Clone Server Enabled|Yes
UDP Port List               |1194
The command completed successfully.

VPN Server>OpenVpnObfuscationGet
OpenVpnObfuscationGet command - Get the current settings of the OpenVPN clone server function's obfuscation mode
Item                       |Value
---------------------------+-----
OpenVPN obfuscation enabled|No
XOR mask                   |
The command completed successfully.]

**Actual behavior:**
[VPN Server>OpenVpnGet
"OpenVpnGet": Command not found.
You can use the HELP command to view a list of the available commands.
VPN Server>OpenVpnObfuscationGet
"OpenVpnObfuscationGet": Command not found.
You can use the HELP command to view a list of the available commands.]

### Steps to reproduce

1. [Just install a latest version of SoftEther VPN Server]

**Comment by andrewfer000** [comment]
You need to use the commands `ProtoOptionsGet OpenVPN` and `ProtoOptionsSet OpenVPN` to change settings for OpenVPN in SoftEther 5.x

**Comment by SHRDLU19** [comment]
> You need to use the commands `ProtoOptionsGet OpenVPN` and `ProtoOptionsSet OpenVPN` to change settings for OpenVPN in SoftEther 5.x
> Personally I would suggest just stopping the VPN server and edit the `vpn_server.conf` file. It makes things easier in my opinion.

Hmm... thanks...
Editing the configuration file is undoubtedly the easiest way, but in the presence of a specialized management interface, it would still be preferable to use it - IMHO.

**Comment by metalefty** [comment]
See also #1130 and #1177.
