### ISSUE TITLE
How use different certificates for SSTP & OpenVPN

### ISSUE THREAD

**Issue by 1o1o1** [SoftEtherVPN/SoftEtherVPN#1430]
Hi!  How use different certificates? 

Example:  For SSTP Let's Encrypt  and  for OpenVPN Self-Signed Certificate

**Comment by davidebeatrici** [comment]
There's no way to do that. What's your use case?

**Comment by metalefty** [comment]
I guess the Let’s encrypt certificate turns over in each 3months but OpenVPN clients want to pin a steady server certificate.

**Comment by 1o1o1** [comment]
Yes it is ..  (:
I added certificates CA Let’s Encrypt R3 in trusted And generated file config for OpenVPN 
it's give me correct CA certificates for ovpn (:

**Comment by domosekai** [comment]
Can you elaborate your needs?
What do you mean by OpenVPN better use self-signed certificate? Let's encrypt has leaf certificates renewed every 3 months but the CA is not that short.

**Comment by 1o1o1** [comment]
separately for openvpn should be a choice of either self-signed certificate or Let's encrypt i think :)
is it logical?

**Comment by domosekai** [comment]
Every certificate has a root ca which is self-signed. Let's encrypt also has it. 
What exactly is your issue when using let's encrypt? Have you tried?

**Comment by 1o1o1** [comment]
to make certificates for openvpn clients for a long time, and at the same time use Let's encrypt for other vpn

i use now Let's encrypt for all type vpn :) it's workin too

**Comment by malikshi** [comment]
> for update each 3months used certbot with (--post-hook) script
> /usr/bin/vpncmd /server localhost /adminhub:DEFAULT /PASSWORD:1234 /CMD ServerCertSet /LOADCERT:/etc/letsencrypt/live/domaim/fullchain.pem /LOADKEY:/etc/letsencrypt/live/domaim/privkey.pem

@1o1o1 can i see your full script post-hook

**Comment by tkmw1985** [comment]
> > for update each 3months used certbot with (--post-hook) script
> > /usr/bin/vpncmd /server localhost /adminhub:DEFAULT /PASSWORD:1234 /CMD ServerCertSet /LOADCERT:/etc/letsencrypt/live/domaim/fullchain.pem /LOADKEY:/etc/letsencrypt/live/domaim/privkey.pem
> 
> @1o1o1 can i see your full script post-hook
Create 
1. sudo nano /etc/cron.monthly/renew_cert.sh
2. Copy and paste the text into the file and replace the missing fields.
#!/bin/sh
certbot renew
vpncmd localhost:5555 /server /PASSWORD:[*** YOUR SERVER PASSWORD ***] /CMD ServerCertSet /LOADCERT:/etc/letsencrypt/live/[*** YOUR SERVER NAME ***]/fullchain.pem /LOADKEY:/etc/letsencrypt/live/[*** YOUR SERVER NAME ***]/privkey.pem
3. Save
4. chmod +x /etc/cron.monthly/renew_cert.sh
5. /etc/cron.monthly/renew_cert.sh
6. Done !

**Comment by 1o1o1** [comment]
people! i know that!  :)  --post-hook etc ...
But separately certs for ovpn, its coud be better, isnt it?

**Comment by metalefty** [comment]
>  But separately certs for ovpn, its coud be better, isnt it?

Definitely, it has benefits. If we ignore the complexity of configuration/implementation.
