### ISSUE TITLE
build: 'pthread_t' error on musl c build

### ISSUE THREAD

**Issue by cenk1cenk2** [SoftEtherVPN/SoftEtherVPN#1439]
---

### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version: latest**
**Component:** [Server, Client, Bridge, etc.]
**Operating system:** [Alpine Linux with MUSL C]
**Architecture:** [64 bit]
**Processor:** AMD Ryzen 2700x

### Description

Hello,

I am generating two containers out of building the latest tagged version for softether, one for client and one for server. Using Alpine Linux as base since I prefer to keep the container sizes on the lightweight side of things like everybody else.

I guess this issue was already fixed for OpenBSD and also mentioned in https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1341 , but it might have broken the MUSL part of it. 

The last working version for me is v5.01.9674.

The repositories I link down below because for Alpine Linux there are tons of missing dependencies due to its lightweight, although I think I added them all Mayaqua is still not liking it very much.

Thank you for still maintaining and upgrading this beautiful software.

**Expected behavior:**
Just continue building.

**Actual behavior:**
With the latest updates it stopped building and throws out the same error which is:

![image](https://user-images.githubusercontent.com/26881592/126703909-ebe33eb4-d42c-4558-b674-33f79cc9751f.png)

The logs can also be seen on: https://drone.kilic.dev/cenk1cenk2/docker-softether-vpncli/46/1/2

### Steps to reproduce

Can be reproduced via docker.

1. Either clone https://github.com/cenk1cenk2/docker-softether-vpnsrv/tree/update or https://github.com/cenk1cenk2/docker-softether-vpncli/tree/update
2. `cd build`
3. `docker build .`

**Comment by davidebeatrici** [comment]
#1342 only included `<pthread.h>` for OpenBSD, we should probably include it for all UNIX systems instead:

```c
#ifdef OS_UNIX
#include <netinet/in.h>
#include <pthread.h>
#endif
```

**Comment by davidebeatrici** [comment]
@cenk1cenk2 Does the fix I proposed work for you?

**Comment by cenk1cenk2** [comment]
Yes it should work on paper. But i have to check the build process afterwards because I am not very familiar with the codebase.

**Comment by weidi** [comment]
Was able to circumvent the build issue on alpine by include pthread.h like mentioned from @davidebeatrici, sadly hit another issue here,  
```
/usr/local/src/SoftEtherVPN/src/Cedar/BridgeUnix.c:52:10: fatal error: linux/if_packet.h: No such file or directory
   52 | #include <linux/if_packet.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by davidebeatrici** [comment]
Please try to remove the include.

**Comment by weidi** [comment]
Next error incoming
```
[ 41%] Building C object src/Cedar/CMakeFiles/cedar.dir/BridgeUnix.c.o
/usr/local/src/SoftEtherVPN/src/Cedar/BridgeUnix.c: In function 'OpenEthLinux':
/usr/local/src/SoftEtherVPN/src/Cedar/BridgeUnix.c:486:21: error: storage size of 'addr' isn't known
  486 |  struct sockaddr_ll addr;
      |                     ^~~~
```

**Comment by davidebeatrici** [comment]
`#include <netpacket/packet.h>`

**Comment by weidi** [comment]
That did it, compiling successful now on alpine latest

**Comment by davidebeatrici** [comment]
You mean without breaking compilation for other environments?

**Comment by weidi** [comment]
Yes, i tested it now on alpine and debian without problems, shall i raise a pull request (for just three little changes)?

**Comment by davidebeatrici** [comment]
Sure, thanks!
