### ISSUE TITLE
build failed! help me!

### ISSUE THREAD

**Issue by chenxudong2020** [SoftEtherVPN/SoftEtherVPN#1440]
run make -C build 

printf flowing :
```
[ 18%] Building C object src/Mayaqua/CMakeFiles/mayaqua.dir/Crypto/Key.c.o
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c: In function ‘CryptoKeyTypeToID’:
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:16:11: error: ‘EVP_PKEY_X25519’ undeclared (first use in this function)
    return EVP_PKEY_X25519;
           ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:16:11: note: each undeclared identifier is reported only once for each function it appears in
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:18:11: error: ‘EVP_PKEY_X448’ undeclared (first use in this function)
    return EVP_PKEY_X448;
           ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c: In function ‘CryptoKeyRawNew’:
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:61:3: warning: passing argument 2 of ‘Copy’ discards ‘const’ qualifier from pointer target type [enabled by default]
   Copy(key->Data, data, key->Size);
   ^
In file included from /root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:4:0:
/root/SoftEtherVPN/src/Mayaqua/./Memory.h:184:6: note: expected ‘void *’ but argument is of type ‘const void *’
 void Copy(void *dst, void *src, UINT size);
      ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c: In function ‘CryptoKeyRawToOpaque’:
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:109:3: warning: implicit declaration of function ‘EVP_PKEY_new_raw_public_key’ [-Wimplicit-function-declaration]
   return EVP_PKEY_new_raw_public_key(id, NULL, key->Data, key->Size);
   ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:109:3: warning: return makes pointer from integer without a cast [enabled by default]
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:113:3: warning: implicit declaration of function ‘EVP_PKEY_new_raw_private_key’ [-Wimplicit-function-declaration]
   return EVP_PKEY_new_raw_private_key(id, NULL, key->Data, key->Size);
   ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:113:3: warning: return makes pointer from integer without a cast [enabled by default]
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c: In function ‘CryptoKeyOpaqueToRaw’:
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:164:7: error: ‘EVP_PKEY_X25519’ undeclared (first use in this function)
  case EVP_PKEY_X25519:
       ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:167:7: error: ‘EVP_PKEY_X448’ undeclared (first use in this function)
  case EVP_PKEY_X448:
       ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:177:3: warning: implicit declaration of function ‘EVP_PKEY_get_raw_private_key’ [-Wimplicit-function-declaration]
   int ret = EVP_PKEY_get_raw_private_key(opaque, NULL, &size);
   ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:200:3: warning: implicit declaration of function ‘EVP_PKEY_get_raw_public_key’ [-Wimplicit-function-declaration]
   int ret = EVP_PKEY_get_raw_public_key(opaque, NULL, &size);
   ^
make[2]: *** [src/Mayaqua/CMakeFiles/mayaqua.dir/Crypto/Key.c.o] Error 1
make[2]: Leaving directory `/root/SoftEtherVPN/build'
make[1]: *** [src/Mayaqua/CMakeFiles/mayaqua.dir/all] Error 2
make[1]: Leaving directory `/root/SoftEtherVPN/build'
make: *** [all] Error 2
make: Leaving directory `/root/SoftEtherVPN/build'
[root@VM-0-7-centos SoftEtherVPN]# make -C build^C
[root@VM-0-7-centos SoftEtherVPN]# clear
[root@VM-0-7-centos SoftEtherVPN]# make -C build
make: Entering directory `/root/SoftEtherVPN/build'
make[1]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
[  3%] Built target libhamcore
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
[  6%] Built target hamcorebuilder
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
[  7%] Built target hamcore-archive-build
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
[ 18%] Built target cpu_features
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
make[2]: Entering directory `/root/SoftEtherVPN/build'
[ 18%] Building C object src/Mayaqua/CMakeFiles/mayaqua.dir/Crypto/Key.c.o
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c: In function ‘CryptoKeyTypeToID’:
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:16:11: error: ‘EVP_PKEY_X25519’ undeclared (first use in this function)
    return EVP_PKEY_X25519;
           ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:16:11: note: each undeclared identifier is reported only once for each function it appears in
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:18:11: error: ‘EVP_PKEY_X448’ undeclared (first use in this function)
    return EVP_PKEY_X448;
           ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c: In function ‘CryptoKeyRawNew’:
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:61:3: warning: passing argument 2 of ‘Copy’ discards ‘const’ qualifier from pointer target type [enabled by default]
   Copy(key->Data, data, key->Size);
   ^
In file included from /root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:4:0:
/root/SoftEtherVPN/src/Mayaqua/./Memory.h:184:6: note: expected ‘void *’ but argument is of type ‘const void *’
 void Copy(void *dst, void *src, UINT size);
      ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c: In function ‘CryptoKeyRawToOpaque’:
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:109:3: warning: implicit declaration of function ‘EVP_PKEY_new_raw_public_key’ [-Wimplicit-function-declaration]
   return EVP_PKEY_new_raw_public_key(id, NULL, key->Data, key->Size);
   ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:109:3: warning: return makes pointer from integer without a cast [enabled by default]
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:113:3: warning: implicit declaration of function ‘EVP_PKEY_new_raw_private_key’ [-Wimplicit-function-declaration]
   return EVP_PKEY_new_raw_private_key(id, NULL, key->Data, key->Size);
   ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:113:3: warning: return makes pointer from integer without a cast [enabled by default]
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c: In function ‘CryptoKeyOpaqueToRaw’:
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:164:7: error: ‘EVP_PKEY_X25519’ undeclared (first use in this function)
  case EVP_PKEY_X25519:
       ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:167:7: error: ‘EVP_PKEY_X448’ undeclared (first use in this function)
  case EVP_PKEY_X448:
       ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:177:3: warning: implicit declaration of function ‘EVP_PKEY_get_raw_private_key’ [-Wimplicit-function-declaration]
   int ret = EVP_PKEY_get_raw_private_key(opaque, NULL, &size);
   ^
/root/SoftEtherVPN/src/Mayaqua/Crypto/Key.c:200:3: warning: implicit declaration of function ‘EVP_PKEY_get_raw_public_key’ [-Wimplicit-function-declaration]
   int ret = EVP_PKEY_get_raw_public_key(opaque, NULL, &size);
   ^
make[2]: *** [src/Mayaqua/CMakeFiles/mayaqua.dir/Crypto/Key.c.o] Error 1
make[2]: Leaving directory `/root/SoftEtherVPN/build'
make[1]: *** [src/Mayaqua/CMakeFiles/mayaqua.dir/all] Error 2
make[1]: Leaving directory `/root/SoftEtherVPN/build'
make: *** [all] Error 2
make: Leaving directory `/root/SoftEtherVPN/build'
```

**Comment by chipitsine** [comment]
hi,

it is known issue.
recent changes in SoftEtherVPN are only compatible with OpenSSL-1.1.1
no OpenSSL-1.0.2 or LibreSSL are supported anymore

**Comment by chipitsine** [comment]
your command line contains "centos 7". most probably openssl-1.0.2 is taken as it is shipped by default on centos 7.

some ideas how to install openssl from source (to separate folder) and point se vpn to that folder might be taken from ci script

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.travis.yml#L71-L73

**Comment by chenxudong2020** [comment]
i install openssl 1.1.1d version but  build failed  also ;

root@VM-0-7-centos SoftEtherVPN]# make -C build
make: Entering directory `/root/SoftEtherVPN/build'
make[1]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
[  3%] Built target libhamcore
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
[  6%] Built target hamcorebuilder
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
[  7%] Built target hamcore-archive-build
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
[ 18%] Built target cpu_features
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
[ 40%] Built target mayaqua
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
[ 89%] Built target cedar
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
[ 91%] Built target list_cpu_features
make[2]: Entering directory `/root/SoftEtherVPN/build'
make[2]: Leaving directory `/root/SoftEtherVPN/build'
make[2]: Entering directory `/root/SoftEtherVPN/build'
[ 92%] Linking C executable ../../vpnserver
../../libmayaqua.so: undefined reference to `RSA_get0_key'
../../libmayaqua.so: undefined reference to `SSL_CTX_set_security_level'
../../libmayaqua.so: undefined reference to `EVP_PKEY_new_raw_public_key'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_pop_free'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_value'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_new_null'
../../libmayaqua.so: undefined reference to `X509_STORE_CTX_get0_cert'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_push'
../../libmayaqua.so: undefined reference to `EVP_MD_CTX_new'
../../libmayaqua.so: undefined reference to `EVP_ENCODE_CTX_new'
../../libmayaqua.so: undefined reference to `DH_get0_key'
../../libmayaqua.so: undefined reference to `RSA_get0_crt_params'
../../libmayaqua.so: undefined reference to `SSL_get1_supported_ciphers'
../../libmayaqua.so: undefined reference to `HMAC_CTX_free'
../../libmayaqua.so: undefined reference to `SSL_CTX_get_security_level'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_num'
../../libmayaqua.so: undefined reference to `X509_get0_notBefore'
../../libmayaqua.so: undefined reference to `EVP_ENCODE_CTX_free'
../../libmayaqua.so: undefined reference to `EVP_PKEY_get0_RSA'
../../libmayaqua.so: undefined reference to `OPENSSL_init_crypto'
../../libmayaqua.so: undefined reference to `ASN1_STRING_get0_data'
../../libmayaqua.so: undefined reference to `EVP_PKEY_new_raw_private_key'
../../libmayaqua.so: undefined reference to `TLS_method'
../../libmayaqua.so: undefined reference to `TLS_client_method'
../../libmayaqua.so: undefined reference to `EVP_MD_CTX_free'
../../libmayaqua.so: undefined reference to `EVP_PKEY_get_raw_private_key'
../../libmayaqua.so: undefined reference to `X509_get0_notAfter'
../../libmayaqua.so: undefined reference to `SSL_CTX_set_options'
../../libmayaqua.so: undefined reference to `HMAC_CTX_new'
../../libmayaqua.so: undefined reference to `OPENSSL_thread_stop'
../../libmayaqua.so: undefined reference to `DH_set0_pqg'
../../libmayaqua.so: undefined reference to `RSA_get0_factors'
../../libmayaqua.so: undefined reference to `TLS_server_method'
../../libmayaqua.so: undefined reference to `OPENSSL_sk_free'
../../libmayaqua.so: undefined reference to `EVP_PKEY_get_raw_public_key'
collect2: error: ld returned 1 exit status
make[2]: *** [vpnserver] Error 1
make[2]: Leaving directory `/root/SoftEtherVPN/build'
make[1]: *** [src/vpnserver/CMakeFiles/vpnserver.dir/all] Error 2
make[1]: Leaving directory `/root/SoftEtherVPN/build'
make: *** [all] Error 2
make: Leaving directory `/root/SoftEtherVPN/build'

**Comment by chenxudong2020** [comment]
i used flowing link to used;
https://blog.csdn.net/rdisme/article/details/103414435

**Comment by chipitsine** [comment]
Sorry, I'm not affiliated with the link above, please ask author of that article
