### ISSUE TITLE
Redundant checks may be needed in the future

### ISSUE THREAD

**Issue by domosekai** [SoftEtherVPN/SoftEtherVPN#1442]
In https://github.com/SoftEtherVPN/SoftEtherVPN/commit/564ca6087fc489ba3551e5b5aa0afc0f18093494 we removed the redundant checks on `Ready == false` inside the lock.
Currently it's fine because in the code `Ready` is never changed. However there is no guarantee that this won't happen in the future. If it happens, one is very unlikely to remember to add back these checks and it is possible that `Ready` changes after the lock.
Can we revert the commit? @chipitsine

**Comment by chipitsine** [comment]
I think we'd better to use thread sanitizer to catch race condition

**Comment by domosekai** [comment]
Sorry I am not sure how that relates to my question.
