### ISSUE TITLE
window build error(visual studio2019)

### ISSUE THREAD

**Issue by vhok74** [SoftEtherVPN/SoftEtherVPN#1455]
I have a question following yesterday's question. I modified src/Cedar/CMakeList.txt, but the same error occurred. Do you know what the problem is? The error is the same as the previous error as shown in the picture below.

![image](https://user-images.githubusercontent.com/35132299/128965892-d7629cf2-2aa0-4980-9fd1-5aed9bb15ba7.png)

**Comment by davidebeatrici** [comment]
The pull request was accidentally merged without waiting for your feedback, sorry.

Have you tried cleaning CMake's cache and running it again?

**Comment by vhok74** [comment]
I manually modified src/Cedar/CMakeList.txt and cleared the cache, but there is still an error.
![image](https://user-images.githubusercontent.com/35132299/128968692-eb7279f5-60f9-4e0c-81b0-6b6fbabdb342.png)

**Comment by davidebeatrici** [comment]
As a workaround you can simply remove the code block that causes the error, I will investigate why the fix doesn't work.

**Comment by vhok74** [comment]
If i erase the 69th block from the black2-config.h file, many errors occur when i build it. I'd appreciate it if you could check.
![image](https://user-images.githubusercontent.com/35132299/128975369-225c9123-7eb1-4aae-b206-a3d2e33865b1.png)

**Comment by davidebeatrici** [comment]
Looks like it's not linking to the networking library from the Windows SDK.

That's definitely not expected.

**Comment by vhok74** [comment]
ok thank you !

**Comment by kingzleshe** [comment]
Hi: I also needed to build on windows, the windows build guide is not nice for a new guy.
Not sure how to do this " Install the needed submodules to build the project"

**Comment by domosekai** [comment]
Closing in favor of #1516
