### ISSUE TITLE
Feature request: Support of saving connection connected via "VPN Gate Public VPN Relay Servers" list

### ISSUE THREAD

**Issue by whatacold** [SoftEtherVPN/SoftEtherVPN#146]
With my short time experience of SoftEther VPN Client, i think there are some trouble in making it work due to below points(possibly due to our country's firewall).

1.Taking a lot of time to find a high quality server.
  Most of time there are few high quality(high line speed, low ping value) relay servers, and many of these servers may be blocked, then it may have no chance to refresh the list.

2.The automatically refreshing mechanism of relay server list make me failed to keep info about a connection.
  If i happen to successfully connect to a high quality server, i will have no way to connect the server again after disconnecting.

So saving such a connection would be necessary and handy, it will save me a bunch of time.

PS:
Creating a connection using the same properties of a existing one does not work.
And this project is brilliant, thank you.

Best regards.

**Comment by Suncatcher** [comment]
Any news about it? It is end of 2016 already.

**Comment by domosekai** [comment]
VPN gate is another project. Unrelated.
