### ISSUE TITLE
What is the best security cipher suite for SSTP protocol?

### ISSUE THREAD

**Issue by zullusax** [SoftEtherVPN/SoftEtherVPN#1462]
https://github.com/kittoku/Open-SSTP-Client/issues/37

Can anyone share which TLS cipher SoftetherVPN's SSTP module can talk and which one is the best security?

Dude I'm asking here because your forum site vpnusers.com iirc was blocked me as a spammer because I am a damn VPN user.

Please help!

**Comment by chipitsine** [comment]
the choice is usually limited by client. i.e., please check what your client supports and choose best of it.

in wireshark client sends "Client Helo" first. all protocols and suites supported by (your) client are exposed. choose from them

**Comment by andrewfer000** [comment]
> Dude I'm asking here because your forum site vpnusers.com iirc was blocked me as a spammer because I am a damn VPN user.
> 

The truth is, vpnusers.com isn't really used for users on Softether's bleeding edge (5.x) version. The best thing to so is to stick with Github Issues if your having a problem or Discssions if a question/comment/idea.
