### ISSUE TITLE
[WARNING] VPNAzure is locked to TLS1.0!

### ISSUE THREAD

**Issue by oknowwhy** [SoftEtherVPN/SoftEtherVPN#1464]
Before:
So now I can set up personal VPN without opening a port | having global IP? Cool.

After:
Wow VPNAzure locked itself to **TLS1.0**.
It only supports **SSTP** protocol.

---

Expected:
1. VPNAzure make a secure connection between Azure(Front IP) and SEVPNServer(Backend IP) **via TLS1.3**.
2. Not only SSTP, VPNAzure shall relay OpenVPN and Wireguard connections too. (L2TP can go f**k itself)

**Comment by andrewfer000** [comment]
Yeah this is a known issue. Until an Open Source implementation of VPN Azure is made it's what we're stuck with. Once people can start hosting their own VPN Azure services this is what it's going to be.

Also OpenVPN (using TCP on port 443) is likely to be implemented if we end up making an open implementation of VPN Azure. However, WireGuard uses UDP so it may not be possible to get that working.

**Comment by hooliga** [comment]
Isn't TLS1.0 already insecure? Removing from the UI will protect unaware users.

**Comment by hooliga** [comment]
http://www.gcd.org/sengoku/stone/

Udp from/to Tcp rediretor

stone x.x.x.x:443/tcp x.x.x.x:12345/udp

**Comment by domosekai** [comment]
VPN azure is a proprietary service provided by SoftEther Corporation for free. There is an attempt to write an open source version.
See #1094.
Any comment should be made there.
