### ISSUE TITLE
The instability of Dynamic DNS service (rendering VPN Azure useless)

### ISSUE THREAD

**Issue by oknowwhy** [SoftEtherVPN/SoftEtherVPN#1465]
SoftEtherVPN insisted on connecting to non-HTTP ports (not tcp80 nor tcp443).

UDP 5004

From VPNAzure's website, the initial developer advertised it to bypass corporate firewall.

Well unfortunately there are many corporated firewall which allow only HTTP ports. Even worse, some companies only allow TCP443 (https only).

I failed to use SEVPN because of this. Without Dynamic DNS Function, your software renders VPN Azure useless (because VPN Azure *requires* Dynamic DNS function)

I also want to know why you need so many FQDNs to look up domains?

```
get-my-ip.ddns.softether-network.net
get-my-ip-v6.ddns.softether-network.net
x?.x?.servers.ddns.softether-network.net
x?.x?.servers-v6.ddns.softether-network.net
x?.x?.servers.nat-traversal.softether-network.net
x?.x?.servers.nat-traversal.softether-network.net
x?.x?.servers.nat-traversal.softether-network.net
```

How about **letting user to set their own Dynamic DNS endpoint**?

---

SEVPN's Dynamic DNS Function should **knock port TCP 443**, not 80 or ugly UDP.

**Comment by davidebeatrici** [comment]
See #1094.

**Comment by domosekai** [comment]
DDNS and VPNAzure uses TCP. You do not need UDP to use them.
UDP 5004 is used by NAT traversal which of course is UDP only.
