### ISSUE TITLE
It is not possible to use SOCKS5 proxy to connect VPNAzure.

### ISSUE THREAD

**Issue by hooliga** [SoftEtherVPN/SoftEtherVPN#1466]
My ISP is hostile enough and I have to use Tor to bypass.

There's a proxy settings panel inside SoftEtherVPN and I set it to 192.168.x.y:9050 (tor server on same network).

SoftEtherVPN does tried to make a connection over proxy, but it failed to connect to VPNAzure.

Expected

1. SoftEtherVPN connect to proxy to connect to VPNAzure (outgoing traffic)
2. Keep it alive (keep-alive)
3. When the client knocks VPNAzure(SSTP or something) just return packet to SoftEtherVPN (punch-hole network)

**Comment by domosekai** [comment]
I tried connecting to VPN azure via SOCKS5 and everything works fine.
If it still troubles you, comment with wireshark capture.
