### ISSUE TITLE
ShadowSocks support?

### ISSUE THREAD

**Issue by hooliga** [SoftEtherVPN/SoftEtherVPN#1467]
Wireguard is nice but ShadowSocks is better because it doesn't keep session alive. THis is great for smartphone cause the data usage costs money.

**Comment by domosekai** [comment]
Shadowsocks is proxy and Wireguard is VPN. Different species.

**Comment by andrewfer000** [comment]
ShadowSOCKS is in a grayarea between a Proxy and VPN. While ShadowSOCKS may look like a VPN if you are using a client like Outline or Shadowsocks Android, the underlying networking componets are not Layer 2 or 3 like a VPN but more like Layer 4 where it can transport TCP/UDP data over a proxy-like connection that does not create a virtual network interface in the same way a real VPN does.

ShadowSOCKS can create a virtual network interface like in the case of Outline, but that cannot communicate on a LAN segment to other devices on the VPN's network like a real L2/L3 tunnel can. Making it kinda useless.

You are better off just setting up a ShadowSOCKS server along side SoftEther like I did on my home VPN machine.
