### ISSUE TITLE
Is VPNGate down or is it just me!?

### ISSUE THREAD

**Issue by disconnctedok** [SoftEtherVPN/SoftEtherVPN#1469]
https://www.vpngate.net/en/

`curl https://www.vpngate.net/en/` stuck in wait. Tested from 4 friends.

Hey, who can pressure upsteam to release VPNGate/VPNAzure code publicly? You can't call yourself open source, this is closed source!!

oh... it now returns something... can't read this. Who can translate it??

``# curl https://www.vpngate.net/en/
サービスを利用できません。``

**Comment by chipitsine** [comment]
call the police to make pressure.

**Comment by davidebeatrici** [comment]
There was a power blackout in Tsukuba at 9:00 AM JST, the website is now reachable again.

**Comment by andrewfer000** [comment]
> Hey, who can pressure upsteam to release VPNGate/VPNAzure code publicly? You can't call yourself open source, this is closed source!!

VPNGate and VPNAzure are separate from the SoftEther VPN Open Source Project and are out of our control. There is currently an Open Source implementation planned for VPNAzure but it's not ready yet.
