### ISSUE TITLE
[SECURITY ALERT] STOP USING SSL3 COMPLETELY

### ISSUE THREAD

**Issue by secur1tyge3k** [SoftEtherVPN/SoftEtherVPN#147]
SoftEther VPN 4.11 Build 9506 Beta (October 22, 2014)
As a response to the SSLv3 POODLE problem we added the "AcceptOnlyTls" configuration flag on the vpn_server.config for SoftEther VPN Server. Please set this flag is you want to completely disable the SSLv3 function in SoftEther VPN Server.
Added the perfect forward security (PFS) support on SSL/TLS. SoftEther VPN Server can now accept connections with DHE-RSA-AES128-SHA or DHE-RSA-AES256-SHA ciphers.

https://github.com/SoftEtherVPN/SoftEtherVPN/issues/new

If the server admin(PacketixVPN) blocks TLS and force users to use SSL, users will exposed to this vuln.
PLEASE STOP USING SSL3 COMPLETELY.

**Comment by omlaverde** [comment]
Modify files:
/src/Cedar/Server.c
Line 132:
#define SERVER_DEFAULT_CIPHER_NAME "AES128-GCM-SHA256"

/src/Mayaqua/Network.c
Line 236:
static char *cipher_list = "AES128-GCM-SHA256 AES128-SHA256 AES256-GCM-SHA384 AES256-SHA256 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-SHA256 DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-SHA256 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384";

Recompile, instructions in BUILD_UNIX.TXT

Install:
cp bin/vpnserver/hamcore.se2 /opt/vpnserver
cp bin/vpnserver/vpnserver /opt/vpnserver

Good luck

**Comment by moatazelmasry2** [comment]
@omlaverde would you please create a Pull Request for this???

**Comment by davidebeatrici** [comment]
Solved by #343.
