### ISSUE TITLE
Empty index.html blocks connection from Manager

### ISSUE THREAD

**Issue by kazan-priv** [SoftEtherVPN/SoftEtherVPN#1475]
* [ ] Can you reproduce? YES
* [ ] Are you running the latest version of SoftEtherVPN? YES

**SoftEther version:** 5.02 Build 5180
**Component:** [Server]
**Operating system:** [Ubuntu 20.04]
**Architecture:** [64 bit]

**Processor:** [Intel]

### Description
I connect to VPNServer from Windows 10 by using "SoftEther VPN Manager 4.38 Build 9760". 
After creating empty "hamcore/wwwroot/index.html" VPN Manager can't connect to server. 
Removing index.html restores possibility to connect to server via VPN Manager.

**Expected behavior:**
After creating empty "hamcore/wwwroot/index.html" I expect blank page while going to webpage of VPN server and VPN Manager still being able to connect to server.

**Actual behavior:**
After creating empty "hamcore/wwwroot/index.html" blank page is displayed but connection to VPNServer from Manager is no longer possible.

### Steps to reproduce

1. create empty "hamcore/wwwroot/index.html" in the location for SoftEther VPN Server installation

**Comment by davidebeatrici** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/3cc85c1d51a8c9c3b7c5cb1d482f2045e2e92760/src/Mayaqua/Network.c#L74-L75

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/3cc85c1d51a8c9c3b7c5cb1d482f2045e2e92760/src/Mayaqua/Network.c#L13615-L13727

What's the exact error you're getting?

**Comment by skindzierm** [comment]
From VPN Manager on Windows 10. I've tried to connect on all ports which are set as listeners by default but always the same.
![image](https://user-images.githubusercontent.com/11707335/131216454-239fa3b5-7eec-46a7-96e9-d186be81d99c.png)

As soon as I remove index.html from the server connection from Manager is possible again.

**Comment by domosekai** [comment]
You are not supposed to add that file.
