### ISSUE TITLE
SecureNAT issues

### ISSUE THREAD

**Issue by 0liverTejada** [SoftEtherVPN/SoftEtherVPN#1485]
I don't know if anybody else has observed this before, but **for some reason, secure NAT has a built-in DHCP client that can NOT be disabled** _(at least, I don't see where)_ and this is a problem when you need that virtual NAT as a router to **all** the different networks the physical server may belong to. Basically **secure NAT itself obtains an IP from physical network** and the acquired IP becomes the WAN IP address of the virtual router, **instead of using physical host's IP address(es) for NATting..,**

- Disabling the DHCP server on the network is not an option for me.
- Isolating physical host on a separate VLAN where DHCP server is unreachable is not an option for me.
- Filtering DHCP packets or broadcasts within the Hub is also not a proper solution, 
- This behavior happens with, or without bridging hubs to any adapter. It requests an IP using physical host's uplink to the network... This built-in DHCP client shouldn't even exist. I currently don't have evidence of securenat appearing as a DHCP client, but I have definetely seen it.

**Is there any way to suppress/disable this DHCP client from secure NAT entirely?**

**Comment by metalefty** [comment]
In my understanding, I don't think Virtual DHCP function does not solve the issue. It is a DHCP server, not a client. I also think SecureNAT function cannot specify the outer interface which NAT'ed packets go out.

His pointing out makes sense.

**Comment by domosekai** [comment]
What's your environment and product version?

**Comment by metalefty** [comment]
I found it. Maybe this is still same in developer version. This document is written in Japanese though. https://ja.softether.org/4-docs/3-kb/VPNFAQ036

RawIP mode SecureNAT attempts to send DHCP request over an Ethernet interface and Raw IP socket connected to the host OS . If SecureNAT could acquire IP address by DHCP, the IP address will be used as WAN interface of NAT.

If you want to host's IP address for NATing, can you try Usermode NAT? SecureNAT has three NAT modes, Usermode NAT, Kernelmode NAT, RawIP mode NAT.
