### ISSUE TITLE
Wrong name in Sock struct

### ISSUE THREAD

**Issue by YangShizhao** [SoftEtherVPN/SoftEtherVPN#1492]
### Prerequisites

* [* ] Can you reproduce?
* [* ] Are you running the latest version of SoftEtherVPN?

**SoftEther version: v4.38 and v5.02
**Component: Network.h and related source files
**Operating system: null
**Architecture: all

### Description

The parameter *WaitToUseCipher* in struct SOCK should be *WantToUseCipher*

![image](https://user-images.githubusercontent.com/13344900/136533899-25694d71-9980-4ee1-8cf9-580cbe76372b.png)

**Comment by domosekai** [comment]
Typos not facing users are generally not fixed as they are everywhere.
