### ISSUE TITLE
Compile error: undeclared identifier 'VG_DLL_X86' in \src\Cedar\SW.c

### ISSUE THREAD

**Issue by cxun** [SoftEtherVPN/SoftEtherVPN#150]
When compiling using BuildAll.cmd as tutorial said in BUILD_WINDOWS.TXT, error occured in compiling step of Cedar project. The output is given below:

.\SW.c(4605): error C2065: 'VG_DLL_X86' : undeclared identifier
.\SW.c(4606): error C2065: 'VG_DLL_X64' : undeclared identifier

I've searched the whole SoftEtherVPN project, no definition of both of them can be found.

**Comment by moatazelmasry2** [comment]
Is this issue still happening?

**Comment by chipitsine** [comment]
feel free to reopen (with more feedback available)
