### ISSUE TITLE
WireGuard does not like my LAN

### ISSUE THREAD

**Issue by andrewfer000** [SoftEtherVPN/SoftEtherVPN#1501]
Oh wow it's been awhile since I had an issue. I tried to use WG at home but I'm having a problem.
### Prerequisites

* [ ] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version: [Latest compiled code]**
**Component:** [Server,]
**Operating system:** [Linux]
**Architecture:** [Intel 64 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Intel Core 2 Duo]

### Description

WireGuard does not work when using a external DHCP server such as on a SOHO Router.

**Expected behavior:**
WireGuard client connects and allows for communication on the LAN

**Actual behavior:**
WireGuard client connects, VPN Session is seen by SoftEther, Internet/LAN communication does not work.

### Steps to reproduce

1. Set up SoftEtherVPN and configure a Hub to use the local network (bridge). Set up SoftEther related stuff.  
2. Connect the client to the server. Check the current sessions and see that the WireGuard client is connected to the VPN Server
3.  Try pinging a local device such as a printer or NAS, and get nothing. Try to connect to an internet site and get nothing.

Btw, The IP I use for the Interface Address is 10.0.188.189/16 That is an available address in my home router's Subnet. Not sure if I need to configure that somewhere in SoftEther VPN Server.

**Comment by andrewfer000** [comment]
Nvm I fixed it with 'SetStaticNetwork /GATEWAY:10.0.0.1 /SUBNET:255.255.0.0' I think this needs to be documented somewhere xD. I just took a shot in the dark and it somehow worked.

**Comment by andrewfer000** [comment]
Now that I got IPv4 working... How do I get IPv6 working?

**Comment by paulmenzel** [comment]
Please create a new issue for the new question, and close this one.
