### ISSUE TITLE
UdpAccel

### ISSUE THREAD

**Issue by tkmw1985** [SoftEtherVPN/SoftEtherVPN#1503]
Hi, there!

Is there any way to change udp acceleration ports to custom ones ?

**Comment by domosekai** [comment]
UDP acceleration port is not supposed to receive incoming connections directly. There is no benefit of changing it.

**Comment by MtCedarNet** [comment]
If the port number is fixed, UDP packets can be allowed by the firewall rule.
I think it is a merit to be able to use the UDP acceleration function even in the FW.

**Comment by domosekai** [comment]
> If the port number is fixed, UDP packets can be allowed by the firewall rule.
> 
> I think it is a merit to be able to use the UDP acceleration function even in the FW.

Yes but it is useful only if any endpoint is under symmetric nat.

**Comment by MtCedarNet** [comment]
The UDP acceleration function works even if the VPN Server has a global IP address.

**Comment by tkmw1985** [comment]
In our country, 5-digit ports have recently been closed, but 3-digit and 4-digit ones are working. The fact is that without it our connection unstable, I tried to change the standard 5-digit ports in src / Cedar / UdpAccel.h to 4-digit ones, but, the minimum ones work as expected, but the maximum is still 5-digit!

**Comment by tkmw1985** [comment]
In our country, 5-digit ports have recently been closed, but 3-digit and 4-digit ones are working. The fact is that without it our connection unstable, I tried to change the standard 5-digit ports in src / Cedar / UdpAccel.h to 4-digit ones, but, the minimum ones work as expected, but the maximum is still 5-digit!
