### ISSUE TITLE
Error build on CentOS 7

### ISSUE THREAD

**Issue by runoka** [SoftEtherVPN/SoftEtherVPN#1504]
### Prerequisites

CentOS Linux 7.9.2009
OpenSSL 1.1.1l  - after 1.0.2k-fips
CMake 3.17.5 - after 2.8.12.2 

### Description

Error build on CentOS 7

```
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1l")
CMake Error at src/Mayaqua/CMakeLists.txt:32 (message):
  Required EVP_PKEY_get_raw_public_key() not found in OpenSSL library!
```

**Expected behavior:**
build ok

**Actual behavior:**
build error

### Steps to reproduce

1.
```
yum install epel-release -y
yum groupinstall "development tools" -y
yum install cmake readline-devel ncurses-devel openssl-devel -y
```

2.
```
cd $HOME
git clone https://github.com/SoftEtherVPN/SoftEtherVPN.git
cd SoftEtherVPN
git submodule update --init --recursive
```

3.
```
./configure
```

4. error "CMake 3.10 or higher is required"
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.10 or higher is required.  You are running version 2.8.12.2
```

5. install  CMake 3
```
yum install cmake3 -y
sed -i.bak 's/cmake/cmake3/g' configure
```

6.
```
./configure
```

7. error "Required EVP_PKEY_get_raw_public_key() not found in OpenSSL library!"
```
-- Found Curses: /usr/lib64/libcurses.so
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")
-- Looking for EVP_PKEY_get_raw_public_key
-- Looking for EVP_PKEY_get_raw_public_key - not found
CMake Error at src/Mayaqua/CMakeLists.txt:32 (message):
  Required EVP_PKEY_get_raw_public_key() not found in OpenSSL library!
```
EVP_PKEY_get_raw_public_key() functions were added in OpenSSL 1.1.1 https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_get_raw_public_key.html

8. install OpenSSL 1.1.1l LTS
```
yum install -y make gcc perl-core pcre-devel wget zlib-devel -y
cd $HOME
wget https://ftp.openssl.org/source/openssl-1.1.1l.tar.gz
tar -xzvf openssl-1.1.1l.tar.gz
cd openssl-1.1.1l
./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic
make
make test
make install
export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
```
```
openssl version
OpenSSL 1.1.1l  24 Aug 2021
```

9.
```
cd $HOME/SoftEtherVPN
./configure
```

10. error "None of the required 'libsodium' found" and "Required EVP_PKEY_get_raw_public_key() not found in OpenSSL library!"
```
-- Build date: 19/11/2021
-- Build time: 11:15:44
-- Checking for one of the modules 'libsodium'
CMake Error at /usr/share/cmake3/Modules/FindPkgConfig.cmake:745 (message):
  None of the required 'libsodium' found
Call Stack (most recent call first):
  src/Cedar/CMakeLists.txt:43 (pkg_search_module)

-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1l")
CMake Error at src/Mayaqua/CMakeLists.txt:32 (message):
  Required EVP_PKEY_get_raw_public_key() not found in OpenSSL library!
```

11. install libsodium 
```
yum install libsodium libsodium-devel -y
```

12. error  "Required EVP_PKEY_get_raw_public_key() not found in OpenSSL library!"
```
-- Checking for one of the modules 'libsodium'
CMake Error at src/Mayaqua/CMakeLists.txt:32 (message):
  Required EVP_PKEY_get_raw_public_key() not found in OpenSSL library!
```

**Comment by q592850** [comment]
Preparing SoftEther VPN Server...
ranlib lib/libcharset.a
ranlib lib/libcrypto.a
ranlib lib/libedit.a
ranlib lib/libiconv.a
ranlib lib/libncurses.a
ranlib lib/libssl.a
ranlib lib/libz.a
ranlib code/vpnserver.a
gcc code/vpnserver.a -fPIE -O2 -fsigned-char -pthread -lm -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a -ldl -o vpnserver
/usr/bin/ld: code/vpnserver.a(vpnserver.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: code/vpnserver.a(vpnserver.o): Relocations in generic ELF (EM: 183)
code/vpnserver.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[1]: *** [main] Error 1
make[1]: Leaving directory `/usr/soft/vpnserver'

**Comment by domosekai** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1405
