### ISSUE TITLE
Shared libraries can't be found after program relocated

### ISSUE THREAD

**Issue by domosekai** [SoftEtherVPN/SoftEtherVPN#1509]
## Problem
I understand that a `make install` installs the libraries and link them with binaries. However, sometimes users may not want to install (e.g. to avoid clashing with an installed version).

Running directly from the built directory works fine. But the catch is that the directory can't be moved or renamed. Otherwise the following error is thrown:
```
./vpntest: error while loading shared libraries: libcedar.so: cannot open shared object file: No such file or directory
```

## Question
I assume the issue is in the cmake configuration. What should I do in order to make the program easily relocatable on Linux?

**Comment by domosekai** [comment]
## Reason
According to https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling,
> By default if you don't change any RPATH related settings, CMake will link the executables and shared libraries with full RPATH to all used libraries in the build tree.

However the default build RPATH is absolute so it won't work after being moved.

## Solution
I found one solution.

Add the next line in `CMakeLists.txt`.
```
set(CMAKE_BUILD_RPATH \$ORIGIN)
```

Or if you have cmake 3.14 and later, you can also use:
```
set(CMAKE_BUILD_RPATH_USE_ORIGIN TRUE)
```
This way the resulted RPATH is relative.

**Comment by domosekai** [comment]
I have limited knowledge of cmake so I am not proposing any change to the current code. Please leave your comments regarding the best practice to this issue.

**Comment by chipitsine** [comment]
we can keep current rpath behaviour ... and let user override it (or even disable, so LD_LIBRARY_PATH may be used)
will it work for you ?

btw, I did not try, but maybe LD_LIBRARY_PATH can override path already, need to read docs :)

**Comment by domosekai** [comment]
Well I am not sure. I haven't seen people complaining this so it might be not important to most users. Probably we should just stay put.

**Comment by chipitsine** [comment]
I did small setup, I built in `/home/azureuser/softethervpn/build` and rename "build" to "build1"


```
azureuser@rpath:~/softethervpn/build1$ ldd vpntest
        linux-vdso.so.1 (0x00007fff04de0000)
        libcedar.so => not found
        libmayaqua.so => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4933806000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4933a07000)
```

```
azureuser@rpath:~/softethervpn/build1$ LD_LIBRARY_PATH=`pwd` ldd vpntest
        linux-vdso.so.1 (0x00007ffcd33fd000)
        libcedar.so => /home/azureuser/softethervpn/build1/libcedar.so (0x00007f6d8320b000)
        libmayaqua.so => /home/azureuser/softethervpn/build1/libmayaqua.so (0x00007f6d83144000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6d82f4a000)
        libsodium.so.23 => /lib/x86_64-linux-gnu/libsodium.so.23 (0x00007f6d82ef2000)
        libreadline.so.8 => /lib/x86_64-linux-gnu/libreadline.so.8 (0x00007f6d82ea2000)
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f6d82e0d000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f6d82b37000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6d82b1b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6d82af8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6d833ff000)
        libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f6d82ac8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6d82ac2000)

```



seems, LD_LIBRARY_PATH overrides rpath.
does it solve the issue ?

**Comment by chipitsine** [comment]
rpath cleanup:

```
 patchelf --remove-rpath vpntest
```

**Comment by domosekai** [comment]
> seems, LD_LIBRARY_PATH overrides rpath. does it solve the issue ?

On recent Linux systems, cmake uses RUNPATH instead of RPATH. 
```
# objdump -x vpntest | grep PATH
  RUNPATH              /root/SoftEtherVPN/build
```

Since RUNPATH has lower precedence than LD_LIBRARY_PATH, yes, user can override it.

**Comment by chipitsine** [comment]
do we still need cmake level override ?

**Comment by domosekai** [comment]
Probably not for the time being until someone else complains about it. I am closing it now.
