### ISSUE TITLE
Bad_Pool_caller in windows 

### ISSUE THREAD

**Issue by belldandu** [SoftEtherVPN/SoftEtherVPN#151]
http://forum.vpngate.net/viewtopic.php?f=7&t=4628&p=11457#p11457
http://www.tomshardware.com/answers/id-2638425/windows-network-bridge-bsod-cold-boot-restart.html#15832087
http://answers.microsoft.com/en-us/windows/forum/windows8_1-performance/windows-81-network-bridge-bug-on-anything-but-cold/34236d34-705a-464e-8461-d2a9b4ffce31?tm=1430797001135

**Comment by domosekai** [comment]
Close due to inactivity
