### ISSUE TITLE
ubuntu 20.04 amd64 builds failing

### ISSUE THREAD

**Issue by maurerr** [SoftEtherVPN/SoftEtherVPN#1514]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

[*] Can you reproduce?
[*] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** [Server, Client, Bridge, etc.]
**Operating system:** [Ubuntu 20.04 Linux]
**Architecture:** [amd64 and ppc64el]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]

### Description

ubuntu 20.04 amd64 and ppc64el builds failing - both nightly and daily
last time it worked was on 27.05.2021

**Expected behavior:**
ubuntu 20.04 amd64 and ppc64el builds working

**Actual behavior:**
ubuntu 20.04 amd64  and ppc64el builds failing 

### Steps to reproduce

1. [First step] https://code.launchpad.net/~paskal-07/+archive/ubuntu/softethervpn-nightly/+packages
2. [Second step] https://launchpad.net/~paskal-07/+archive/ubuntu/softethervpn/+packages
3. [And so on...]

**Comment by maurerr** [comment]
cc @paskal

**Comment by domosekai** [comment]
Launchpad is maintained by a third party. Please build from the main repository.

**Comment by maurerr** [comment]
> Launchpad is maintained by a third party. Please build from the main repository.

but you advertise this on the README.md so it needs to be addressed

**Comment by metalefty** [comment]
Yes, it needs to be addressed but the PPA maintainer is responsible to do that. You should contact Dmitry Verkhoturov, not to upstream developers.

**Comment by paskal** [comment]
[Starting](https://launchpad.net/ubuntu/+source/softether-vpn) with Ubuntu 21.04 softether-vpn is available from [Debian](https://packages.debian.org/source/sid/softether-vpn), we have new enough version of the package available in the PPA and I'm not willing to invest time into fixing the nightly build as it will be duplicating effort with Debian maintainers and I would rather suggest helping them.

I will update the description of the PPAs to mention that and will likely stop the builds altogether rather than having them fail on every commit.

**Comment by paskal** [comment]
I've updated the description of the daily build and stable PPA, feel free to update Readme here to reflect that before 21.04 you need to use no longer updated packages from the PPA, and after that, you have only the option of using upstream packages. [Debian 11](https://packages.debian.org/sid/softether-common) has these packages out of the box as well.

Thanks for pointing this situation out, @maurerr.

**Comment by maurerr** [comment]
a big thank you for all your work @paskal
