### ISSUE TITLE
build on windows methods

### ISSUE THREAD

**Issue by kingzleshe** [SoftEtherVPN/SoftEtherVPN#1516]
Would SoftEtherVPN5 build methods be the same as SoftEtherVPN4?
Currently, the windows build guide is too hard for a none developer
I ran into some problems which I can not fix.
If not the case Hopley the windows build guide will be more detailed

**Comment by chipitsine** [comment]
it is our debt.

windows build guide is not only hard, but it is broken.
maybe I'll take time this weekend, who knows.

meanwhile, you can use Azure DevOps build artifacts (from pipeline)

**Comment by chipitsine** [comment]
![image](https://user-images.githubusercontent.com/2217296/145585121-b55736ce-e2e2-4826-be8e-ba8b3960b40d.png)

**Comment by kingzleshe** [comment]
Thanks for the quick reply
Never used Azure before nonetheless, I will try it.
Also, I'm not eager to use SoftEtherVPN5,  Maybe I'll wait :)
