### ISSUE TITLE
The number of routes is limited by a security policy when a Computer running Windows sets up Intranet routes

### ISSUE THREAD

**Issue by liucheng0325** [SoftEtherVPN/SoftEtherVPN#1523]
I need to use SoftEtherVPN to set up an environment that can connect to the company Intranet from my home computer. 
In this environment, a public network cloud Server (CentOS7 64-bit) is used to deploy the Server program (using the default configuration and enabling the access restriction of port 433 on the external network), and the Client is installed using Windows 10 64-bit system to keep the internal network and external network connected.   The Intranet adapter is shared with the VPN adapter.   The computer I use at home is Windows10 64-bit operating system.  I install the Client and Server management program, and use the Server management program to create a virtual HUB and set the login authentication in the way of user name and password.   After the connection is successful, the Intranet access route is configured, and the gateway points to the Client IP address deployed in the enterprise. 
After the deployment and construction of the above environment was completed, I could connect the machine on the Intranet from the computer at home. 
However, I can access only three Intranet machines.  After the PING command is used to verify that the connection is successful, I can PING only three random IP addresses on the Intranet.  Then, I cannot access other terminals. 
My expectation is that all Intranet terminals can be connected. 

The HUB log saved on the Server contains the following information:
2021-12-20 00:09:38.140 Session "SID-GUEST-249": Although the virtual hub has attempt to assign a new IP address 10.3.0.10 was made, 4 IP addresses have already been assigned for this service. According to the security policy, this session is denied routing and is therefore allowed to hold no more than 4 IP addresses. The packet has been discarded.

Server Version 4.38 Build 9760
Client  Version 4.03 Build 9408

Please help me out:How do I adjust: Security policies described in logs?

**Comment by domosekai** [comment]
Please write in English and use our template. Please also describe the steps to reproduce the issue.

**Comment by liucheng0325** [comment]
@domosekai Thanks for your reply. I will resubmit my question

**Comment by domosekai** [comment]
By default a VPN client is not supposed to be bridged with another network. That's what a VPN bridge does.
You can try enabling "Bridge / router mode" in the VPN client, or replacing VPN client with VPN bridge.

**Comment by liucheng0325** [comment]
Thanks for your quick reply.Let me try it. @domosekai

**Comment by liucheng0325** [comment]
Thank you, as you said. My problem is solved.
