### ISSUE TITLE
Add check on TLS 1.0 support for VPN Azure setup/connections

### ISSUE THREAD

**Issue by tew42** [SoftEtherVPN/SoftEtherVPN#1525]
_(Update: as pointed out below, the issue originally described arises out of VPN Azure requiring TLS 1.0, which is disabled by default on some systems. The connection issue can be resolved by manually adjusting OpenSSL config as described in #1358 ; however, introducing some basic compatibility checks and error messages could be helpful to fully resolve.)_

## Prerequisites

* [yes] Can you reproduce?
* [yes] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** 5.02 build 5180 (Github release) / 5.02 Github nightly
**Component:** Server (mainly)
**Operating system:** Debian (DietPi) for Server, Windows or Unix for client
**Architecture:** 32bit
**Processor:** RBpi 3b server

## Description

I used to run stable server and client (4.38), with connection via VPN Azure (DynDNS + NAT-T never worked for me). I recently upgraded to 5.02 both server- and client-side (trying to mitigate a latency issue, which it actually might have fixed). I migrated the configuration files by copy-pasting non-default entries into the new default files.

### Expected behavior:
Able to use VPN Azure connections in 5.02 the same as in 4.38.

### Actual behavior:

**Server 5.02 build 5180:**

**Server** can't establish VPN Azure connection (i.e. VpnAzureGetStatus shows Enabled, but No connection).
This prompted me to move on to - 

**Server 5.02 nightly build** (December 19):

**Server** establishes VPN Azure connection just fine. I can also ping xxxx.vpnazure.net from my client with the latency that I would expect.

**Client** can't connect, no matter the version or platform I use (4.38 stable, 5.02 nightly, Windows, Unix). Using `xxxx.vpnazure.net`, the connection fails on "Connecting..." after ~10 seconds with "Error (Error Code 1): Connection to the server failed. Check network connection and make sure that address and port number of destination server are correct."

Interestingly, with `xxxx.vpnazure.net/tcp`, the failure occurs instead on certificate verification, with "Error (Error Code 2): Protocol error occurred. Error was returned from the destination server." (certificate verification is disabled on the client, AND I have individually added the server certificate on the client regardless)

The server log remains empty in both cases.

(I should also note that - unlike on 4.38 - with the 5.xx builds I am now able to successfully establish a VPN using xxxx.softether.net, i.e. using DynDNS + NAT-T, showing that my basic config should be fine)

## Steps to reproduce

1. Configure 5.02 VPN server with VPN Azure (besides my 4.38 to 5.02 config transfer, I also attempted with a from-scratch config)
2. Attempt to connect from remote client via vpnazure.net
3. Fail to connect, either directly, or on certificate verification (when /tcp)

**Comment by domosekai** [comment]
1. 5.x uses shared library and links to the OpenSSL library installed on your system. 
2. Vpn azure requires TLS 1.0 to connect. 
3. Debian disables TLS 1.0 by default. But you can enable it in /etc/ssl/openssl.cnf 
4. Your Unix client needs to do the same.

**Comment by tew42** [comment]
Many thanks, that indeed solved the issue - with these hints I also came across your helpful pointers in #1358

Anyway, regarding the VPN Azure issue then - is there a way to have Softether log an error (Server) and/or throw a more helpful error (Client) if (a) trying to set up a VPN Azure connection, and (b) TLS 1.0 isn't supported?

**Comment by domosekai** [comment]
That might be something that needs to be improved. This is a free project. Feel free to submit a patch.

**Comment by tew42** [comment]
While I know enough to mess around with shell scripts and simple programming in some rather niche languages, the level of complexity here is unfortunately beyond my skill level... But maybe this can stay open in case someone else with the necessary skills  and motivation feels inspired to look into this further.

**Comment by andrewfer000** [comment]
@tew42
The outdated TLS issue is the one thing the SoftEtherVPN Project does not have control over since we do not have access to VPNAzure's servers or source code. Personally I do not recommend using VPNAzure at all even if you get it to work due to TLS 1.0 and other related issues.

The best solution would be to rent a cheap, high-limit (2TB+)/unlimited bandwidth VPS from OVH or Contabo and follow [my guide](https://github.com/SoftEtherVPN/SoftEtherVPN/wiki/Creating-your-own-VPNAzure-DynamicDNS-Like-Service-(In-Testing,-Needs-Testers)) in the Wiki. I use an OVH Starter VPS for mine and it only costs $3.50/mo and it works very well. You will also need a domain which you can get for as low as $2/year on Namecheap. I will be more than happy to help you if you decide to go this route.

- Andrew

**Comment by domosekai** [comment]
There is report that VPN azure has been upgraded to support TLS 1.3.
https://www.vpnusers.com/viewtopic.php?f=15&t=67267
Closing this issue.
