### ISSUE TITLE
Radius Multilogin issue

### ISSUE THREAD

**Issue by kooran** [SoftEtherVPN/SoftEtherVPN#1526]
Hello
i've been using latest version of stable SoftEther, i have successfully connected it to my radius server for accounting, but it only works with BSAE RAS type in my radius server, and it doesn't support multi login and it keeps users online few minutes after disconnection so they cant connect again, not just me , there are many others with same issue and we couldn't find any solution for years now, is there any chance we can solve our problem by using this modified version? how?
thanks

**Comment by domosekai** [comment]
This is a free project. If you want something, please submit the code that implements it.

**Comment by kooran** [comment]
> This is a free project. If you want something, please submit the code that implements it.

sorry i guess there is a misunderstanding, this is an issue , "multi login" with radius , so i opened an issue, if i had a fix code i would do a pull request , but im not a developer, so this is as much as i can do, saying this issue is exist and its a big bug

**Comment by domosekai** [comment]
No I don't understand. If it's a bug, how to reproduce it?

**Comment by kooran** [comment]
> No I don't understand. If it's a bug, how to reproduce it?

obviously the issue is in Radius section , as i said im not a developer , but, the best solution that i can think of is making SoftEther Radius more compatible with other RAS types.

For example we using IBSng database for radius and accounting , it has 15 RAS type , and SE is just compatible with one of them (BSAE) and its not a good one.
for PPTP L2TP, cisco, socks5 we use PPPD RAS type and it supports every thing that everyone needs in radius , but SE wont work with it

**Comment by kooran** [comment]
> No I don't understand. If it's a bug, how to reproduce it?

obviously the issue is in Radius section , as i said im not a developer , but, the best solution that i can think of is making SoftEther Radius more compatible with other RAS types.

For example we using IBSng database for radius and accounting , it has 15 RAS type , and SE is just compatible with one of them (BSAE) and its not a good one.
for PPTP L2TP, cisco anyconnect
, socks5 we use PPPD RAS type and it supports every thing that everyone needs in radius , but SE wont work with it

**Comment by domosekai** [comment]
You didn't answer my question. How to reproduce the issue?

**Comment by kooran** [comment]
> You didn't answer my question. How to reproduce the issue?

im sorry i don't fully understand that but i can give access to our data base (a simulation) and soft ether server connected to it to anyone who's willing to check

**Comment by domosekai** [comment]
Please describe how you setup the server, the hub and the users. After that, what should another person do in order to see the bug that you mentioned. That's called reproduction.

**Comment by kooran** [comment]
> Please describe how you setup the server, the hub and the users. After that, what should another person do in order to see the bug that you mentioned. That's called reproduction.

alright , thank you

setting up SE server is easy and everything works fine without Radius , even with Radius everything works fine except multi login , that means no matter if you setup multilogin in SE or your Radius server , more that one connection with same username wont be stablished , for example we need 3 devices connecting with same username , we tried defining multi login on radius side, didnt work , we tried on SE server Group Policies , still didn't work (it works without radius) and even after first device disconnects , other devices have to wait few minutes so one of them could connect.
we need these 3 devices use same username at the same time and we tried everything in configurations , nothing worked , as i said we use this radius server for multiple services (cisco anyconnect, l2tp, pptp, socks5,.....) all of them works fine except SE users

**Comment by domosekai** [comment]
I tried setting up a FreeRADIUS server. I can multi login without any issue.
I created a user named `testing` and I can create two sessions with it.

```
VPN Server/vpn>userget testing
UserGet command - Get User Information
Item                         |Value
-----------------------------+-------------------------
User Name                    |testing
Full Name                    |
Description                  |
Expiration Date              |(None)
Auth Type                    |RADIUS Authentication
-----------------------------+-------------------------
Created on                   |2021-12-21 (Tue) 13:26:28
Updated on                   |2021-12-21 (Tue) 13:26:28
Outgoing Unicast Packets     |80 packets
Outgoing Unicast Total Size  |4,284 bytes
Outgoing Broadcast Packets   |171 packets
Outgoing Broadcast Total Size|21,669 bytes
Incoming Unicast Packets     |68 packets
Incoming Unicast Total Size  |3,252 bytes
Incoming Broadcast Packets   |122 packets
Incoming Broadcast Total Size|13,890 bytes
Number of Logins             |2
The command completed successfully.

VPN Server/vpn>sessionlist
SessionList command - Get List of Connected Sessions
Item            |Value
----------------+--------------
Session Name    |SID-TESTING-1
VLAN ID         |-
Location        |Local Session
User Name       |testing
Source Host Name|
TCP Connections |2 / 2
Transfer Bytes  |25,202
Transfer Packets|265
----------------+--------------
Session Name    |SID-TESTING-2
VLAN ID         |-
Location        |Local Session
User Name       |testing
Source Host Name|
TCP Connections |2 / 2
Transfer Bytes  |15,103
Transfer Packets|144
The command completed successfully.
```
