### ISSUE TITLE
I have a multi IP station group server. After setting up L2TP, how to allocate public IP to different accounts

### ISSUE THREAD

**Issue by lwoldt** [SoftEtherVPN/SoftEtherVPN#1537]
hello,I have a multi IP station group server. After setting up L2TP, how to allocate public IP to different accounts

**Comment by andrewfer000** [comment]
There are a few ways you can do this but I need some info:
Is this in the cloud or on premises?
Do you use DHCP in your network?
If in the cloud, Do you have a OVH/SYS dedicated server or VPS?

The Easy (Tested) Way:
1:1 NAT is the best option. It can be done in almost any environment. Ether by the VPN itself if it's acting as the router or an external router if it supports it. If you need to set IPs to specific users WITH DHCP, I believe you can set a note in the user's account such as MAC='A1:B2:C3:D4:E5:F6' to give them a Virtual MAC on L3 connections so the DHCP server always gives the same IP. I tested this on a multi-IP OVH VPS Running Debian 11. Refering to this [wiki article](https://github.com/SoftEtherVPN/SoftEtherVPN/wiki/Creating-your-own-VPNAzure-DynamicDNS-Like-Service-(In-Testing,-Needs-Testers)) 

The Hard (Untested) Way,
OVH Failover IPs support Virtual MAC addresses if you have a Physical dedicated server with them or SoYouStart. What you would do is generate the virtual MAC addresses through OVH's IP control panel and then set that MAC to the user via the user notes as stated above. You also need  bridge to the external network interface in SoftEtherVPN to the respected Virtual Hub. You can then connect the client and manually set the IP in it's network settings. The Virtual MAC and Bridging feature is designed for Virtual Machines on a dedicated server. However this is a possible use too. However all documentation from OVH will refer to Virtual Machine uses so be prepared to think outside the box a little if you go this route. **I have NOT tested this myself, but theoretically it should work**
