### ISSUE TITLE
Openwrt

### ISSUE THREAD

**Issue by lwk523** [SoftEtherVPN/SoftEtherVPN#1540]
Hi, 

Anyone have experience that install softether bridge into openwrt (CPU : MT7621) ? 

I only get the download/upload speed around 60-80Mbps (MY ISP: 500Mbps ) . Is that any tweak can do for speed improvement and i see the cpu usage still not reach 100% yet for said speed ?  (No Encrypted connections here )

Telegram me : @wkm49 for sharing about Softether bridge in OPENWRT

**Comment by domosekai** [comment]
Network software won't reach 100% utilization due to its I/O nature. Given that weak CPU I would say the result is within expectation.
