### ISSUE TITLE
Ubuntu install instructions need to be updated

### ISSUE THREAD

**Issue by guideloom** [SoftEtherVPN/SoftEtherVPN#1544]
The Softether README probably needs to be updated. According to the README, we should be able to update Ubuntu via a PPA located at a Launchpad PPA maintained by Dmitry Verkhoturov (@paskal). Then 2 links are presented; Daily builds (latest released tag) and Nightly builds.

However, when visiting both PPAs, the following is displayed:

```
SoftEtherVPN Daily Builds.
NO LONGER SUPPORTED AND UPDATED.
```

```
SoftEtherVPN Nightly Builds (built against master branch)
NO LONGER SUPPORTED AND UPDATED.
```

I assume this means we can no longer update Ubuntu via this means?

**Comment by paskal** [comment]
This discussion has relevant information: https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1514
