### ISSUE TITLE
CMake always compiles BLAKE2 from SSE2 sources

### ISSUE THREAD

**Issue by akuropka** [SoftEtherVPN/SoftEtherVPN#1546]
I'm building SoftEtherVPN on a Raspi-4 with Arch Linux Arm installed.
**Architecture:** aarch64

Building fails consequently due to missing SSE2 set on arm chipsets:
```
[ 89%] Building C object src/Cedar/CMakeFiles/cedar.dir/__/__/3rdparty/BLAKE2/sse/blake2s.c.o
In Datei, eingebunden von /usr/local/src/vpnserver/3rdparty/BLAKE2/sse/blake2s.c:23:
/usr/local/src/vpnserver/3rdparty/BLAKE2/sse/blake2-config.h:69:2: Fehler: #error "This code requires at least SSE2."
   69 | #error "This code requires at least SSE2."
      |  ^~~~~
/usr/local/src/vpnserver/3rdparty/BLAKE2/sse/blake2s.c:26:10: schwerwiegender Fehler: emmintrin.h: Datei oder Verzeichnis nicht gefunden
   26 | #include <emmintrin.h>
      |          ^~~~~~~~~~~~~
Kompilierung beendet.
```
(Note: `emmintrin.h` is not included in gcc-aarch64 since it is SSE2 / x86_64 specific.)

This is basically a duplicate of #1288, however that time it was about armv7h.

**Comment by davidebeatrici** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/78e89eb3c738b016331c50253e97bda948d5d88c/src/Cedar/CMakeLists.txt#L24

Could you check whether `HAS_SSE2` is true, please?

**Comment by akuropka** [comment]
yes?!

```
/usr/local/src/vpnserver/src/Cedar/CMakeLists.txt(24):  cmake_host_system_information(RESULT HAS_SSE2 QUERY HAS_SSE2 )
/usr/local/src/vpnserver/src/Cedar/CMakeLists.txt(25):  if(HAS_SSE2 )
/usr/local/src/vpnserver/src/Cedar/CMakeLists.txt(26):  message(HAS_SSE2 true! )
HAS_SSE2 true!
```

So it's not an issue of SoftEtherVPN?!

**Comment by davidebeatrici** [comment]
Looks like CMake reports SSE2 support even if the Raspberry Pi 4's CPU doesn't have the instruction set.

**Comment by akuropka** [comment]
... which makes no sense since arm generally doesn't support SSE.
However, the issue is not related to SoftEtherVPN.
I adjusted `CMakeLists.txt` by unconditionally defining BLAKE2_SRC and BLAKE2_SRC_PATH and it builds. 😀
Thank you for looking into it.

**Comment by davidebeatrici** [comment]
No problem and thank you for your report!

Your workaround is correct, we should probably report the bug upstream (CMake).
