### ISSUE TITLE
softether service running in the background and uploads data

### ISSUE THREAD

**Issue by paymanz** [SoftEtherVPN/SoftEtherVPN#1552]
why softether keeps using bandwidth and uploading some data while  i haven't even connected to any softether server!? and it uses quite high bandwidth!(1-2 Mb/s)

 what data it uploads and why?! 

i'm using a network monitor app and the upload bandwidth usage immediately drops when i stop softether service.

**Comment by domosekai** [comment]
I have no idea what you are talking about.

**Comment by chipitsine** [comment]
@paymanz , network monitor (or similar app) should also provide traffic details, such as source, destination, port numbers, etc.
without those details it is hard to make a guess for us.

**Comment by paymanz** [comment]
> @paymanz , network monitor (or similar app) should also provide traffic details, such as source, destination, port numbers, etc. without those details it is hard to make a guess for us.



> I have no idea what you are talking about.

ok i will try to add more information regarding source and destination , but please take a look at this video i recorded , i just started the softether service a few minutes before recording:  https://i.imgur.com/0odtIWQ.gif

most of uploads destination is this ip 78.85.49.81

**Comment by chipitsine** [comment]
can you please try [Fiddler](https://www.telerik.com/fiddler) or [FiddlerCap](https://www.telerik.com/fiddler/fiddlercap) (no installation required). It allows capture https traffic. I really wonder what those queries are.

also, please notice that you are using 4.x version which is SoftEtherVPN_Stable (this repo is about 5.x)

**Comment by paymanz** [comment]
> can you please try [Fiddler](https://www.telerik.com/fiddler) or [FiddlerCap](https://www.telerik.com/fiddler/fiddlercap) (no installation required). It allows capture https traffic. I really wonder what those queries are.
> 
> also, please notice that you are using 4.x version which is SoftEtherVPN_Stable (this repo is about 5.x)

thank you for respond , i am not a pro , tried but couldn't make fiddler work , i tried wireshark and captured some packets that softether sent(filtered by destination).  if this helps please tell me to upload more files like this with other destinations.
https://file.io/X5GES0sJkvYE
and where can i post for 4.x version?

**Comment by chipitsine** [comment]
I tried the following filters in attached pcap

`ip.addr == 78.85.49.81`
`ip.addr == 1.247.0.232`
`ip.addr == 121.138.240.207`

no packets. 


as for 4.x support, there's link on www.softether.org website:

![image](https://user-images.githubusercontent.com/2217296/154124173-67088163-a7db-4998-a668-120b2ae906e4.png)
