### ISSUE TITLE
Feature request: Dynamic DNS tweak, ability to choose which IP to register (private/public).

### ISSUE THREAD

**Issue by alcatraz-zz** [SoftEtherVPN/SoftEtherVPN#1558]
Hey fellow softether users. Got a tiny feature request here.

I run softether on many small routers and it's working great. Many of these don't obtain public IP's because the ISP isn't providing any (no problem). They get private IPs but they are still all on the same network and can connect to eachother using the private IPs. These private IPs still change every time a device reboots and it gets a bit annoying to manually update all the cascade connection profiles. (One suggestion was to cascade them all to one public IP device, but I'm afraid that would have to go to another ISP, which is a long way around with a hefty performance sacrifice.)

I was wondering if it's possible to tweak the softether dynamic dns function "xxx.softether.net" to override which IP is being registered? I'd like it to be the private IP which still is very useful to me for ISP internal connections.

Thank you so very much for reading and commenting. /Mike

**Comment by andrewfer000** [comment]
Unfortunately, VPNAzure/DynamicDNS is out of our control since it is not Open Source. For your situation it may be best to build your own Dynamic DNS Service. If you have any experience with python it's probably possible and for I know there may already be a solution out there for that. Not sure...

**Comment by alcatraz-zz** [comment]
Thank you. Got it to work with duckdns.org. I had to whitelist the domains in my router's dnsmasq because apparently resolving private IPs is a security concern.
