### ISSUE TITLE
Ethernet over SSL on Android

### ISSUE THREAD

**Issue by quentinhardy** [SoftEtherVPN/SoftEtherVPN#156]
Hello,

Awesome project. Thank you for the work.

Is there an Android application which use Ethernet over SSL (HTTPS) with a Softether VPN server?

I think there's Softether VPN Client (Linux and Windows) only which uses Ethernet over SSL.

Thank you in advance for your response,

**Comment by dajhorn** [comment]
@quentinhardy, no, but the native OpenVPN client for Android is compatible with the SoftEther server implementation (and usually performs better than alternatives like L2TP and IPSec).

**Comment by nomadturk** [comment]
You can also use 3rd party apps for OpenVPN but I never had a stable connection with those.
L2TP / IPSec does indeed work just fine.

**Comment by moatazelmasry2** [comment]
Question has been answered. Closing the issue
