### ISSUE TITLE
BSOD/ Windows 11 Crashes after connection to server and streaming data

### ISSUE THREAD

**Issue by shawnhaywood** [SoftEtherVPN/SoftEtherVPN#1560]
Hello, I recently installed SoftEther Server 4 on a new Windows 11 PC. After setting up the server and connecting via OpenVPN client, the Windows PC crashes a couple of minutes after connection.  I use the server to stream video from home while traveling. I can connect and begin streaming, but after a few minutes my pc does BSOD stating ndis.sys failed and restarts.  One suggestion was to try SoftEther 5, which does the same thing. Also, I installed an Intel NIC card, which does the same thing. The onboard NIC is a Realtec and I tried the latest Realtec drivers and Windows drives.  The Intel drivers are the Windows drivers.  According to Intel's diagnotic app, the current driver is the best to use.  Ideas? 

Please use or adapt it as needed.

### Prerequisites

* [ ] Can you reproduce? Yes, each time I connect to the server running on Windows 11, I get a BSOD a few minutes into the connection.  Message displayed on BSOD says ndis.sys failed.
* [ ] Are you running the latest version of SoftEtherVPN? Yes, occured on server v4 and currently on SoftEther VPN 5.0 Dev.

**SoftEther version:**
**Component:** [Server, Client, Bridge, etc.]  v. 5.02 build 5180
**Operating system:** [Windows, Linux, BSD, macOS, etc.]  Windows 11 v. 10.0.22000 build 22000
**Architecture:** [64 bit, 32 bit] x64 
Current NIC Info:  Intel PRO/1000 PL.   Microsoft driver date 9/29/2011 v. 9.13.41.3
Onboard NIC info: Realtec PCIe GbE.  Microsft driver date 7/23/202 v. 10.43.723.2020.  Also tried Realtec's drivers dated 2021.

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:**  Intel i7 10700
Hard Drive:  Samsung 980. Good health. No bad sectors.
RAM:   16gb 2933 (2 modules)
PC:  Dell Inspiron 3891

### Description

Not sure what logs to upload?
![20220310_185444_resized](https://user-images.githubusercontent.com/93692595/157796797-5118c6ce-8fdf-43a1-96c4-2cb8ac01e8f3.jpg)

**Comment by shawnhaywood** [comment]
[vpn_20220310.log](https://github.com/SoftEtherVPN/SoftEtherVPN/files/8228836/vpn_20220310.log)
[031022-6921-01.zip](https://github.com/SoftEtherVPN/SoftEtherVPN/files/8228841/031022-6921-01.zip)

**Comment by shawnhaywood** [comment]
Did a fresh install of Windows 11, updated all drivers, and reinstalled SoftEther 4.  Connect a client and streamed some content for about 10 minutes.  PC then crashed again with BSOD. Only crashes under this scenario.  This is the most recent minidump and server error log.
[vpn_20220311.log](https://github.com/SoftEtherVPN/SoftEtherVPN/files/8232739
[031122-6500-01.zip](https://github.com/SoftEtherVPN/SoftEtherVPN/files/8232742/031122-6500-01.zip)
/vpn_20220311.log)

**Comment by dnobori** [comment]
Hmm it seems that the error causes outside SoftEther VPN's Ethernet Bridge kernel driver. 

```
DRIVER_IRQL_NOT_LESS_OR_EQUAL (d1)
An attempt was made to access a pageable (or completely invalid) address at an
interrupt request level (IRQL) that is too high.  This is usually
caused by drivers using improper addresses.
If kernel debugger is available get stack backtrace.
Arguments:
Arg1: 000000000000000a, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000000, value 0 = read operation, 1 = write operation
Arg4: fffff8012451aeda, address which referenced memory


STACK_TEXT:  
ffffbd08`ca9e1858 fffff801`21c290a9 : 00000000`0000000a 00000000`0000000a 00000000`00000002 00000000`00000000 : nt!KeBugCheckEx
ffffbd08`ca9e1860 fffff801`21c25200 : 00000000`00000002 00000000`00000001 00000000`00000002 fffff801`21aaa7a8 : nt!KiBugCheckDispatch+0x69
ffffbd08`ca9e19a0 fffff801`2451aeda : 00000000`00000000 00000000`00000000 ffff878f`00000001 ffff878f`5ed72be0 : nt!KiPageFault+0x440
ffffbd08`ca9e1b30 fffff801`2451b132 : ffff878f`698d00c0 ffff878f`69000000 ffff878f`698acb00 00000000`00000000 : ndis!ndisMIsLoopbackNetBuffer+0x3e
ffffbd08`ca9e1b90 fffff801`244a63f9 : 00000000`00000000 00000000`00000000 ffff878f`00000000 00000000`ffffffff : ndis!ndisMLoopbackNetBufferLists+0xaa
ffffbd08`ca9e1c10 fffff801`2447539e : 00000000`00000000 ffff878f`698acb00 ffff878f`00000000 fffff801`24a91010 : ndis!ndisMSendNBLToMiniportInternal+0x31049
ffffbd08`ca9e1ce0 fffff801`244a477c : 00000000`00000001 ffff878f`698acb00 00000000`00000001 00000000`00000000 : ndis!ndisMSendNBLToMiniport+0xe
ffffbd08`ca9e1d20 fffff801`244a44d9 : ffff878f`5ed73040 fffff801`24475390 ffff878f`5ed73040 ffff878f`5a4d41a0 : ndis!ndisIterativeDPInvokeHandlerOnTracker<0,void __cdecl(void * __ptr64,_NET_BUFFER_LIST * __ptr64,unsigned long,unsigned long)>+0xcc
ffffbd08`ca9e1d80 fffff801`244a8707 : ffff878f`698acb00 00000000`00000000 00000000`00000000 ffff878f`5ed74620 : ndis!ndisInvokeIterativeDatapath<0,void __cdecl(void * __ptr64,_NET_BUFFER_LIST * __ptr64,unsigned long,unsigned long)>+0xd9
ffffbd08`ca9e1df0 fffff801`24474c74 : 00000000`00000000 ffffbd08`ca9e1ec9 ffff878f`5a4d41a0 ffff878f`698acb00 : ndis!ndisInvokeNextSendHandler+0x1280f
ffffbd08`ca9e1e40 fffff801`24700f5c : ffff878f`698acb00 ffff878f`5edf8010 ffff878f`00000000 ffffbd08`00000000 : ndis!NdisSendNetBufferLists+0x184
ffffbd08`ca9e1f30 fffff801`24703bcd : ffff878f`5f487030 00000001`e0004f00 ffff878f`54f40800 00000000`00000000 : tcpip!FlpSendPacketsHelper+0x2ac
ffffbd08`ca9e1fe0 fffff801`247bfa6f : fffff801`248e0004 00000000`00000000 ffff878f`54f98360 ffff878f`54f4f100 : tcpip!IppFragmentPackets+0x2ed
ffffbd08`ca9e20c0 fffff801`2475829e : ffff878f`58e16210 00000000`00000000 ffffbd08`ca9e2201 00000000`00000000 : tcpip!IppReceivePackets+0xb899f
ffffbd08`ca9e21d0 fffff801`24756208 : ffff878f`00000001 ffff878f`5edf8000 fffff801`246e3a20 ffffbd08`ca9e25a0 : tcpip!FlpReceiveNonPreValidatedNetBufferListChain+0x29e
ffffbd08`ca9e22d0 fffff801`21add058 : 00000000`00000000 fffff801`24756070 ffff878f`54dba200 00000000`00000002 : tcpip!FlReceiveNetBufferListChainCalloutRoutine+0x198
ffffbd08`ca9e2410 fffff801`21adcfcd : fffff801`24756070 ffffbd08`ca9e25c0 ffff878f`54ffb0d0 00000000`00000000 : nt!KeExpandKernelStackAndCalloutInternal+0x78
ffffbd08`ca9e2480 fffff801`246e32cd : 00000000`00000000 00000000`0000ffff 00000000`0000000e 00000004`00000000 : nt!KeExpandKernelStackAndCalloutEx+0x1d
ffffbd08`ca9e24c0 fffff801`246e2a4c : 00000000`00000000 ffffbd08`ca9e2620 ffff878f`5edf8010 fffff801`21af6672 : tcpip!NetioExpandKernelStackAndCallout+0x8d
ffffbd08`ca9e2520 fffff801`24472d6c : ffff878f`5ee4c101 ffff878f`5a5b1c61 00000000`00000020 00000000`00000001 : tcpip!FlReceiveNetBufferListChain+0x5ec
ffffbd08`ca9e2810 fffff801`245134e9 : ffff878f`51769aa0 ffffbd08`ca9e2901 ffff878f`00000000 00000000`00000002 : ndis!ndisMIndicateNetBufferListsToOpen+0x15c
ffffbd08`ca9e28f0 fffff801`244a9073 : ffff878f`5a4d41a0 00000000`00000000 fffff801`244a0a01 ffff878f`5a5ef570 : ndis!ndisDoPeriodicReceivesIndication+0x38d
ffffbd08`ca9e29f0 fffff801`244a0c01 : ffff878f`5a000302 ffff878f`5a4d4e58 ffffbd08`ca9e2a89 fffff801`244a0a00 : ndis!ndisPeriodicReceivesWorker+0x73
ffffbd08`ca9e2a20 fffff801`21a5a8b5 : ffff878f`54dba200 ffff878f`54dba200 fffff801`244a0a50 00000000`00000000 : ndis!ndisReceiveWorkerThread+0x1b1
ffffbd08`ca9e2af0 fffff801`21c1a574 : ffffd401`7216f180 ffff878f`54dba200 fffff801`21a5a860 00000000`00000000 : nt!PspSystemThreadStartup+0x55
ffffbd08`ca9e2b40 00000000`00000000 : ffffbd08`ca9e3000 ffffbd08`ca9dc000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x34
```

**Comment by shawnhaywood** [comment]
I also have VirtualBox loaded running Openvpn on the same pc. Would that cause the problem?

**Comment by chipitsine** [comment]
I cannot repro this on "windows 11 dev environment" (shipped as hyper-v vm: https://www.windowscentral.com/windows-11-enterprise-virtual-machine-now-available-developers-download )

is it something specific to virtualbox ?

**Comment by domosekai** [comment]
Seems not related to softether. Closing.
