### ISSUE TITLE
is it possible to use softether vpncmd to connect the VPN-SERVER by L2TP/IPSec on the command line?

### ISSUE THREAD

**Issue by blogdaren** [SoftEtherVPN/SoftEtherVPN#1579]
well, I intended to post this question in `vpnusers.com`,  but I counld't get through the register page again and again, and it seems no administrator tells me what is going on, so I decide to post here.

Environment:
* OS：Centos 6.5
* vpnlcient：softether-vpnclient-v4.21-9613-beta-2016.04.24-linux-x64-64bit

so I wanna know is that possible to use softether vpncmd to connect the remote VPN-SERVER on the command line by `L2TP/IPSec` protocol in the Linux environment?

**Comment by domosekai** [comment]
No. Softether client only uses softether protocol.
