### ISSUE TITLE
SSL certificate considered insecure by Chrome

### ISSUE THREAD

**Issue by arbitrix** [SoftEtherVPN/SoftEtherVPN#158]
In the current version of Chrome 

https://www.softether.org/

show the following SSL error:

![image](https://cloud.githubusercontent.com/assets/1563212/8013218/30b5d556-0b8d-11e5-9b91-7f8a22b8f001.png)

**Comment by lancethepants** [comment]
Probably because of its use of sha1 in the certificate.

http://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html

**Comment by moatazelmasry2** [comment]
Looks like certificate has been updated a while back
