### ISSUE TITLE
Feature request: mptcp support

### ISSUE THREAD

**Issue by Sunser** [SoftEtherVPN/SoftEtherVPN#1585]
If necessary, the author can add MPTCPv1 support.

mptcp wiki: https://github.com/multipath-tcp/mptcp_net-next/wiki

Introduction to MPTCP: http://multipath-tcp.org/

**Comment by domosekai** [comment]
Thank you for the suggestion. 
Implementation is not hard but since it is Linux only I am not sure how much benefit we can get.
Is there any real world use case?

**Comment by Sunser** [comment]
Currently known open source projects are: https://github.com/Ysurac/openmptcprouter

MPTCP is mainly used in the large environment of the Internet, which can provide better results with multiple lines, reduce packet loss and improve throughput, and its advantages are suitable for network environments with unequal upstream and downstream.
I think most people use the linux route, and it is not difficult to meet the linux requirements.

**Comment by domosekai** [comment]
I know the general idea. The question is how softether users can benefit, given most of clients are on Windows.

**Comment by Sunser** [comment]
Has no effect on windows, and mptcp is not intended for windows.
The two are not common. Consider making a parameter to choose whether to enable mptcp support.

**Comment by lixh1223** [comment]
CentOS7版视频安装教程：https://youtu.be/fWGw6Qdh1pY
Windows版视频安装教程：https://youtu.be/lXb7FxxEcE0
