### ISSUE TITLE
Failed to ConfigSet when an absolute path is given as an argument

### ISSUE THREAD

**Issue by mitu217** [SoftEtherVPN/SoftEtherVPN#1588]
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version: Version 4.39 Build 9772   (English)**
**Component:Server** [Server, Client, Bridge, etc.]
**Operating system:Linux** [Windows, Linux, BSD, macOS, etc.]
**Architecture:64bit** [64 bit, 32 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]

### Description

**Expected behavior:**

The ability to give an absolute path as an argument to the VPN Server's ConfigSet command.

example:
```
# /usr/local/vpnserver/vpncmd /server /csv /cmd ConfigSet /usr/local/vpnserver/vpn_server.config
```

**Actual behavior:**

occured error. 
but it works fine if you pass a path relative to the vpncmd or give path by interactive.

Is this the intended behavior?

↓ absolute path
```
# /usr/local/vpnserver/vpncmd /server /csv /cmd ConfigSet /usr/local/vpnserver/vpn_server.config
Specify the host name or IP address of the computer that the destination VPN Server or VPN Bridge is operating on.
By specifying according to the format 'host name:port number', you can also specify the port number.
(When the port number is unspecified, 443 is used.)
If nothing is input and the Enter key is pressed, the connection will be made to the port number 8888 of localhost (this computer).
Hostname of IP Address of Destination: localhost

If connecting to the server by Virtual Hub Admin Mode, please input the Virtual Hub name.
If connecting by server admin mode, please press Enter without inputting anything.
Specify Virtual Hub Name:
Password: ********

The parameter "/usr/local/vpnserver/vpn_server.config" has been specified. It is not possible to specify this parameter when using the command "ConfigSet". Input "ConfigSet /HELP" to see the list of what parameters can be used.

#
```

↓ relative path
```
# /usr/local/vpnserver/vpncmd /server /csv /cmd ConfigSet ./vpn_server.config
Specify the host name or IP address of the computer that the destination VPN Server or VPN Bridge is operating on.
By specifying according to the format 'host name:port number', you can also specify the port number.
(When the port number is unspecified, 443 is used.)
If nothing is input and the Enter key is pressed, the connection will be made to the port number 8888 of localhost (this computer).
Hostname of IP Address of Destination: localhost

If connecting to the server by Virtual Hub Admin Mode, please input the Virtual Hub name.
If connecting by server admin mode, please press Enter without inputting anything.
Specify Virtual Hub Name:
Password: ******************

#
```

### Steps to reproduce

1. install latest softether server
2. run `/usr/local/vpnserver/vpncmd /server /csv /cmd ConfigSet /usr/local/vpnserver/vpn_server.config`
4. occured error

**Comment by domosekai** [comment]
The reason is that the leading `/` is considered special in softether language. It is used to speficy an option.

**Comment by domosekai** [comment]
You can use path like `//usr/local` to escape.

**Comment by mitu217** [comment]
thanks for support 🙏 

I can confirm that ConfigSet works by escaping the `/` 👍
