### ISSUE TITLE
Where can I assign a static IP to vpn users?

### ISSUE THREAD

**Issue by ghost** [SoftEtherVPN/SoftEtherVPN#16]
I want to set up like this: PC1,PC2,PC3 -> SEVPNserver(123.123.123.123/wan IP)

I don't want to connect SEVPNserver's network(lan IP 10.10.50.X range)
but I want to connect to SEVPNserver itself / VPN users.

ex.
SEVSERVER 10.10.20.1
PC1(vpn connected) 10.10.20.22
PC1(vpn connected) 10.10.20.27

[ALLOW]
10.10.20.22 -> 10.10.20.1:8080 = 127.0.0.1:8080(in server side)
10.10.20.22 -> 10.10.20.1:465 = 127.0.0.1:465(in server side)
10.10.20.22 -> 10.10.20.27 (pc-to-pc)
10.10.20.22 -> 120.130.140.150 (to internet, just like a router)

[DENY]
10.10.20.22 -> 10.10.50.25

The question is,
1. Where can I set a static IP for each VPN user? (ex. 10.10.20.x range for VPN)
2. If can't, should I use SecureNAT's DHCP instead?

server has 2 NIC card.
one is 10.10.1.2 WAN(Global IP: 123.123.123.123)
second is 10.10.50.1 LAN

**Comment by moatazelmasry2** [comment]
The question was answered correctly. The user does not exist anymore on github. I'd like to close this issue.
