### ISSUE TITLE
mac os vpn connection failed

### ISSUE THREAD

**Issue by xiongwu1** [SoftEtherVPN/SoftEtherVPN#1608]
I connect through L2TP and always show connection failure, but the same account can be successfully connected on windows platform.
How do I troubleshoot the cause of the problem？View the error log or other methods ？

The error screenshot is as follows:
![image](https://user-images.githubusercontent.com/15642586/172822495-4f5dfc12-5632-4a6a-b72d-dae6fe633c4d.png)

**Comment by howtodo1** [comment]
If it is about the VPN not responding, I have the same problem

**Comment by domosekai** [comment]
I can confirm L2TP still connects to SoftEther VPN server as of macOS 12.6. Please build from the latest source and open all ports needed.
