### ISSUE TITLE
请问:如何修改log日志格式？

### ISSUE THREAD

**Issue by leqii-com** [SoftEtherVPN/SoftEtherVPN#1612]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.
我没有办法注册你们的vpnusers.com账户，因为在注册时候，可能有无封禁原因，无论我换什么邮件，你们的网站都提示“The solution you provided was incorrect
Please note that you will need to enter a valid email address before your account is activated. You will receive an email at the address you provide that contains an account activation link.”

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [ ] Can you reproduce?
* [ ] Are you running the latest version of SoftEtherVPN? 

**SoftEther version: Server ver4.36,Build 9754
**Component:** [Server]
**Operating system:** [Linux, censtos7.6]
**Architecture:** [64 bit, 32 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [英特尔]

### Description

[Description of the bug]

**Expected behavior:**
[What you expected to happen]

**Actual behavior:**
[What actually happened]

### Steps to reproduce

1、请教一下：我想修改日志输出格式，例如每条日志里面加一个username，这样方便找到是哪个用户发送的数据请求。
log example：
2022-06-17 09:01:40.019 SecureNAT: The TCP session 584831 has been created. Connection source 172.100.100.10:51486, Connection destination 220.181.33.11:443 "username蒼井そら"
2022-06-17 09:01:49.453 SecureNAT: The TCP session 584828 has been deleted "username蒼井そら".

2、或者：我可以设置Server，让每个用户分配到固定的IP地址吗？例如openvpn就支持这个功能。

**Comment by YangShizhao** [comment]
日志里现在是已经有用户名信息的，如果你想改日志格式的话，首先找到你想修改的地方，一般日志输出的代码长这个样子：
```
SLog(c->Cedar, "LS_WG_KEY_NOT_FOUND", c->Name, hubname);
```
引号里的那一串，就是日志的格式模板，找到\src\bin\hamcore\strtable_cn.stb这个文件，在里面搜索“LS_WG_KEY_NOT_FOUND”，然后修改这个对应的字符串就可以

**Comment by leqii-com** [comment]
@YangShizhao 没有找到你说的文件呀

**Comment by YangShizhao** [comment]
你应该用的Visual Studio编辑的，先点解决方案资源管理器里右上角的显示全部文件按钮：
![image](https://user-images.githubusercontent.com/13344900/178630213-cc20b7ed-befb-4fa6-8526-43bbc4492ea4.png)

**Comment by leqii-com** [comment]
@YangShizhao 你的代码 跟我 不一样，我的版本是SoftEther version: Server ver4.36,Build 9754
![QQ截图20221024132621](https://user-images.githubusercontent.com/79353242/197454215-24fcdc54-adc4-4f52-874d-f84e8fd1f7c0.png)

**Comment by leqii-com** [comment]
我是下载编译后的，我不会源码
@YangShizhao
