### ISSUE TITLE
Support OpenVPN multi-daemon mode

### ISSUE THREAD

**Issue by AminMoradian** [SoftEtherVPN/SoftEtherVPN#1613]
Hi

Please add a feature to support OpenVPN multi-daemon mode, TCP and UDP together

**Comment by domosekai** [comment]
What is the purpose and benefit?

**Comment by AminMoradian** [comment]
In the OpenVPN Access Server you can choose to connect one of the tcp or udp
or it handled automatically by openvpn client

some ISP just allow you to connect with udp

**Comment by davidebeatrici** [comment]
How does the OpenVPN client handle it automatically?

**Comment by domosekai** [comment]
Softether already supports tcp and udp. What else do you want?

**Comment by liam-prog** [comment]
I need to choose tcp or udp in client side for connect to softether openvpn

**Comment by liam-prog** [comment]
is there way to set softether openvpn to listening on TCP and UDP concurrent?

**Comment by mohamadpk** [comment]
openvpn client test first udp and if not connected try tcp if setting is set in config file.
SoftEtherVPN can do this like openvpn on access server?
or can get just link to client and openvpn client download config?

**Comment by mohamadpk** [comment]
one SoftEther server listen both UDP and TCP???

**Comment by mohamadpk** [comment]
tnx for response

**Comment by lixh1223** [comment]
CentOS7版视频安装教程：https://youtu.be/fWGw6Qdh1pY
Windows版视频安装教程：https://youtu.be/lXb7FxxEcE0
