### ISSUE TITLE
SSL Authentication For windows built-in VPN Client

### ISSUE THREAD

**Issue by HighBrowInTown** [SoftEtherVPN/SoftEtherVPN#1619]
We are working on our proxy server and we are planning to make it cloud based solution which will have multi-tenant software architecture, we are now planning to use SofthEther to connect to proxy server using windows built-in VPN SSTP as client.
Proxy configuration will differ from user to user and organization to organization 
However, for this to work we require users to be successfully authenticated. 
Using password based authentication is not logical in our setup as we cannot provision users in VPN server because we are clueless about the user that will be using our proxy server, but it will not be an open proxy server.
We want user to be created and authenticated using SSL certificate which will have details of users and organization they below to.

Using SSL certificate for authentication will result in a secure proxy connection and user will be create as users are logged in.

We want to know if there is any configuration for SSL certificate based authentication for windows built-in VPN client? or can this feature be added to SoftEther

**Comment by domosekai** [comment]
Already supported. SSTP clients can authenticate by certificate just like SoftEther clients.

**Comment by HighBrowInTown** [comment]
We have tried using SSL certificate for authentication in windows using SSTP and during the connection process in Softhether logs it says "(The client denied to accept both the "PAP" (Password Authentication Protocol, a clear-text password authentication protocol) and MS-CHAP v2 Protocol. Enable either PAP or MS-CHAP v2 on the client-side and retry.)"

We need to authentication using SSL certificate in windows built-in vpn client. 
Authentication using SSL certificate in Softhether VPN client was successful.

**Comment by domosekai** [comment]
Please build from the trunk and try again.

**Comment by HighBrowInTown** [comment]
can you provide me the link for the trunk?

**Comment by davidebeatrici** [comment]
It's this repository, `master` branch.

**Comment by HighBrowInTown** [comment]
Thank You, I will try and let you know

**Comment by HighBrowInTown** [comment]
We build the Softether VPN server from the master branch, but we are still unable to connect using SSL certificate.
I have provided the screenshot of the error we got from the Windows VPN client and our configuration file.
![image](https://user-images.githubusercontent.com/89702887/176159978-ac7c3a7b-affe-4c67-86ae-7fbafd497c8a.png)
[vpn_server.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/9000277/vpn_server.txt)

**Comment by HighBrowInTown** [comment]
Is there anything I can do to achieve SSL certificated-based authentication in windows built-in VPN client, or can you add this feature in Softhether?

**Comment by domosekai** [comment]
I can't reproduce the issue. Please provide the error log.

**Comment by shipitsin-ilia** [comment]
@HighBrowInTown , please provide repro steps. Particularly I'm triggered on `We are working on our proxy server`

SSTP is highly integrated with SSL transport layer, as a very basic and stupid error might be non trusted ssl certificates. But any other SSL interception might break it easily.

In theory SSTP should work in cascade mode if SSL is carefully implemented on each party involved.

**Comment by HighBrowInTown** [comment]
Okay, so today I tried to replicate the error which I was getting when I tried last time. 
I did fresh install of Softhether again and generated new root certificates and client/user certificates, when I connected to VPN server I was authenticated successfully and connected to the VPN server without any errors.

**Comment by HighBrowInTown** [comment]
We now want users to be created based on the client certificate they provide which will be signed by the root certificate of  VPN server. 
We have no idea how many users will be accessing our proxy server and we cannot have user provisioning in VPN server, with the logging facility where in only username, IP address assigned by VPN server and connected/disconnected  status will be written in the log file.

**Comment by lixh1223** [comment]
CentOS7版视频安装教程：https://youtu.be/fWGw6Qdh1pY
Windows版视频安装教程：https://youtu.be/lXb7FxxEcE0

**Comment by HighBrowInTown** [comment]
Can you provide detailed information on how to use signed certificate authentication settings.

I want users to be authenticated based on the client certificate they have which will be signed by VPN root CA and the users will not be explicitly mentioned in the VPN server.

**Comment by domosekai** [comment]
Users have to be created first.

**Comment by domosekai** [comment]
You can create a common username for all users. They can use individual certificates issued by a common parent. 
If you definitely need dynamic user creation, you might need to look into the code and do it yourself.

**Comment by HighBrowInTown** [comment]
Are you guys planning to release this feature some time ahead?

**Comment by domosekai** [comment]
I don't think this feature makes sense because it will expose vpn server configuration to users. 
When a new certificate is issued, a new user should be created and bound to that. Giving users the ability to self enroll is dangerous.

**Comment by HighBrowInTown** [comment]
User will not have the ability to self enroll but they will be provided certificate signed by the root CA certificate which users which not have access to.

**Comment by domosekai** [comment]
I don't understand. Why not create a new user when a certificate is signed?

**Comment by HighBrowInTown** [comment]
Because this users will be provided the certificates by their organization's root CA  and the organization's  root CA certificate will be exported to VPN's trusted root CA.

Because we don't the number of users in each organization it will not be an option to provision users in VPN server.

**Comment by domosekai** [comment]
Externalizing certificate issuance while exposing user creation does not sound like a good design to me. 
But you are free to do anything as it's a free project. That's all I can say.

**Comment by HighBrowInTown** [comment]
Thank you and everyone for your support. Appreciated.

**Comment by cvalka4** [comment]
What about Radius? 
You obviously don't want softhether to manage your users!
Is Radius + certificates supported?
