### ISSUE TITLE
Both server and management app hang if server can not create tap device. Only restart helps

### ISSUE THREAD

**Issue by Dmitriusan** [SoftEtherVPN/SoftEtherVPN#162]
To reproduce that, just try https://github.com/cnf/docker-softether . It runs vpn server inside docker container, without kernel cap NET_ADMIN. This situation should be also common to low-end VPS hostings. 
These capabilities don't allow to create tap device and/or enter promicious mode on a physical interface. 
So if I try to bridge virtual hub with a new tap interface (via create option in vpn server), vpn server shows error as a status. 
![scr1](https://cloud.githubusercontent.com/assets/1825803/8457521/8b109ecc-201a-11e5-8510-6844ec18cf7a.png)
That is expected. But if I try to remove bad bridge, both local management app and vpn server hang. Killing management app does not help, it hangs after reconnect attempt. Only restarting server itself helps

**Comment by connLAN** [comment]
How to make SoftEtherVPN works well on VPS , especially  Local-bridge and cluster feature ,  is very important. If this is resolved, it will promote the promotion and application of SEVPN.

**Comment by domosekai** [comment]
Close due to inactivity. Open new issue if the problem persists with the latest version.
