### ISSUE TITLE
the text of next button has mistake

### ISSUE THREAD

**Issue by YangShizhao** [SoftEtherVPN/SoftEtherVPN#1623]
### Prerequisites

* [ ] Can you reproduce? Yes
* [ ] Are you running the latest version of SoftEtherVPN? No

**SoftEther version: 5.02.5180
**Component: Setup
**Operating system: Windows
**Architecture: 64 bit

### Description

The problem is, in chinese system environment, when running setup.exe, the "next" button is translated to "下一页", while the "prev" button is translated to "上一步"。
the right text should be "下一页"&“上一页”， or “下一步”&“上一步”。
I didn't find the place to modify this text, please tell me how to modify the text of this button, or just change the text to "下一页"&“上一页”。

**Comment by chipitsine** [comment]
please find "*.stb" in `src/bin/hamcore` folder. you are welcome to create PR.

**Comment by YangShizhao** [comment]
> 

I have search strtable_cn.stb and strtable_en.stb, and found nowhere related to this button.
Search for “prev” button, I tried "上一步"， and the result has only one place which is under * PREFIX D_TCP_MSG *.
Search for "next" button, I tried "下一页", and the result still has nowhere under * PREFIX SW_* *

**Comment by lixh1223** [comment]
CentOS7版视频安装教程：https://youtu.be/fWGw6Qdh1pY
Windows版视频安装教程：https://youtu.be/lXb7FxxEcE0

**Comment by domosekai** [comment]
The translation is correct, corresponding to *Next* and *Back*.

**Comment by YangShizhao** [comment]
> The translation is correct, corresponding to _Next_ and _Back_.

it is correct, but not elegant
