### ISSUE TITLE
Cannot config or create local bridge

### ISSUE THREAD

**Issue by lordofthelaw** [SoftEtherVPN/SoftEtherVPN#1625]
### Prerequisites

* [X] Can you reproduce?
* [X] Are you running the latest version of SoftEtherVPN?

**SoftEther version: 4.39 Build 9772**
**Component: Server**
**Operating system: Linux**
**Architecture: aarch64**

### Description
Cannot create or config local bridge. Working normal with virtual NAT but it consume too much CPU

**Expected behavior:**
- Can config or create local bridge.

**Actual behavior:**
- When using CLI with **BridgeCreate** command: _(error 84) Local Bridge cannot be used by the destination VPN Server. Refer to online help or other documentation for the setting method when using Local Bridge on the VPN Server you are using._
- When using VPN Server Manger : Local Bridge Setting button was faded out.
![image](https://user-images.githubusercontent.com/37249858/178697257-2a160e99-4b08-47d3-8317-c69e00b9c874.png)
- When using command **BridgeDeviceList**, it's print out an empty list.

### Steps to reproduce

**- WITH CLI**

1. Login into server with admin privilege
2. Choose Hub to work with
3. Use **BridgeCreate** command to create local bridge and then I got error 84

**Comment by domosekai** [comment]
Did you run vpnserver as root?

**Comment by lordofthelaw** [comment]
> Did you run vpnserver as root?

Thank you, work like a charm now.
