### ISSUE TITLE
Ubuntu 22.04 vpncmd check fail

### ISSUE THREAD

**Issue by BlindB0** [SoftEtherVPN/SoftEtherVPN#1629]
* [x ] Can you reproduce?
* [x ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
Version 5.01 Build 9674   (English)
**Component:** Server, vpncmd
**Operating system:** Ubuntu Server 22.04 (stock, zero kernel changes) x64
**Architecture:** 64 bit

### Description
Connecting using vpncmd, client, localhost.
Running the "check" command gives the following on Checking 'Network system'...
"Connect Failed. (0)"

### Steps to reproduce

1. sudo apt-get install softether-vpnserver (default ubuntu repo, no PPA, installation softether-vpnserver_5.01.9674+git20200806+8181039+dfsg2-2build1_amd64.deb package)
2. vpncmd
3. check

After changes in etc/ssl/openssl.cnf:
```
[ssl_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT:@SECLEVEL=0
```
All checks pass
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1230

**Comment by chipitsine** [comment]
it is somewhat known. maybe we should check SECLEVEL and refuse to start on SECLEVEL=1 and higher

**Comment by domosekai** [comment]
This issue is already fixed. The version in the Ubuntu repo is just too old.

**Comment by chipitsine** [comment]
let us make new release
