### ISSUE TITLE
[requirement] VPN disconnection protection

### ISSUE THREAD

**Issue by sakurayz** [SoftEtherVPN/SoftEtherVPN#1630]
Hello, I think the softether client should add the function of VPN disconnection protection. When the VPN is disconnected or reconnected, the application is prohibited from accessing the Internet.

**SoftEther version: latst version
**Component:** [Client]
**Operating system:** [Windows,]
**Architecture:** [64 bit]

**Comment by r4j4h** [comment]
I think this is similar to #1634

**Comment by domosekai** [comment]
Closing in favor of #1634
