### ISSUE TITLE
InterlockedCompareExchange64 error on Windows XP 32-bit

### ISSUE THREAD

**Issue by anewuser** [SoftEtherVPN/SoftEtherVPN#1631]
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** Client
**Operating system:** Windows XP SP3 (32-bit) on Oracle VM VirtualBox
**Architecture:** 32-bit

### Description

The Build 9772 installer gives this error on a Windows XP SP3 (32-bit) VirtualBox install:

    The procedure entry point InterlockedCompareExchange64 could not be located in the dynamic link library KERNEL32.dll
    
I was able to install and use Build 9760 normally.

**Comment by dnobori** [comment]
This seems to be a bug of OpenSSL 3.x.

https://github.com/openssl/openssl/blob/cbb1cda67f61b34c89fb49c8e2267ec6217bc33f/crypto/threads_win.c#L210

OpenSSL 3.x invokes `InterlockedOr64`. InterlockedOr64 is Windows XP 32bit-incompatible. It is expanded to call `InterlockedCompareExchange64` by a macro definition of `winnt.h`.

I am going to seek a workaround.

**Comment by anewuser** [comment]
Thank you for looking into it. I had assumed that it was broken for all 32-bit versions of Windows because of the error message, but after your comment I was indeed able to install it on Windows 7 Starter SP1.

**Comment by dnobori** [comment]
https://github.com/openssl/openssl/pull/18856

**Comment by dnobori** [comment]
Hello,

Today I fixed this OpenSSL 3.x bug and built a new binaries for test.
https://filecenter.softether-upload.com/d/220724_001_softether-v4_41-9779-beta_09359/

Could you please test it on your Windows XP?

**Comment by anewuser** [comment]
Thank you. I was able to install `softether-vpnclient-v4.41-9779-beta-2022.07.24-windows-x86_x64-intel.exe`:

<details>
  <summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/6733770/180654393-aad9395b-eeaf-429f-acda-705f27a83499.png">
</spoiler>
  ```
  
</details>
