### ISSUE TITLE
Your project is included in awesome-vpn/wiki/Clients

### ISSUE THREAD

**Issue by hugetiny** [SoftEtherVPN/SoftEtherVPN#1632]
Open WIKI for VPNs

https://github.com/awesome-vpn/awesome-vpn/wiki/Clients

Please feel free to edit, add, and correct

**Comment by andrewfer000** [comment]
There are Android Clients (VPN Client Pro and OpenSSTP) and iOS Clients (SSTP Connect)

**Comment by hugetiny** [comment]
> There are Android Clients (VPN Client Pro and OpenSSTP as well as built in for L2TP) and iOS Clients (SSTP Connect and L2TP)

Please provide links
