### ISSUE TITLE
Cannot Access my VPN Server Internal Network Address

### ISSUE THREAD

**Issue by wxf26054** [SoftEtherVPN/SoftEtherVPN#1633]
Cannot Access my VPN Server Internal Network Address
I've opened SecureNAT function and DHCP, my VPN Virtual Card address is 10.4.0.254
For example, my vpn server address at internal network address is 10.0.0.254, but I connect the vpn form the External Network, I cannot access 10.0.0.254. 
How to solve this problem?

**Comment by davidebeatrici** [comment]
If the server is not running on Windows, you have to use a local bridge instead of SecureNAT.

**Comment by wxf26054** [comment]
but the if the local bridge is created, the dhcp server will release IPs to the Internal Network.

**Comment by davidebeatrici** [comment]
No, you can still use Virtual DHCP.
