### ISSUE TITLE
Feature request: VPN chains (Simultaneous connections in chain order)

### ISSUE THREAD

**Issue by pinkrootninja** [SoftEtherVPN/SoftEtherVPN#1635]
### Prerequisites

* [Yes] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** SoftEther VPN 4.0 (Ver 4.39, Build 9772)
**Component:** [Client]
**Operating system:** [Windows]
**Architecture:** [64 bit, 32 bit]

### Description

It could be used to hide the first server's IP from the destination to prevent survelliance and to increase privacy. It is called "Secure Core" by ProtonVPN, when you connect to first server, and then the second one. I expect at least 2 or 3 nodes from this feature, if not more or not capped.

**Expected behavior:**
Using multiple VPN connections in the chain-like style:
Client -> (Proxy 01 ->) VPN Server 01 -> ((Proxy 02 ->) VPN Server 02 -> ... ->) VPN Server X -> Internet

I imagine that this should be done using separate window with the support of drag and drop, to where you could move known connections and where you could move desired VPN connections in desired order. This window could be used to show what connection is establishing right now and what connection dropped.
It also could be used to test establishing connections manually, like, you connect to the first server, it passes, then you try to add second one, it fails, then you try to add the other one instead of not working one, etc. This test should be able to work with active VPN connection and this test should not use this VPN connection, but instead it should use the base connection.

It could be stored as a list of pre-configured chains. It could be stored as a list of "Secure" servers, which you connect firstly, and then you connect to the desired server.

The internet connection should work only through the latest VPN connection from the specified order. If it doesn't work, middle nodes shouldn't be used as exit nodes.

**Part of the description of Secure Core**
What does Secure Core protect against?

Proton VPN’s unique Secure Core architecture allows us to protect our users from network attacks that other VPNs cannot defend against. A classic VPN setup involves a client passing traffic through a VPN server en-route to the final destination. If an attacker can get control of the VPN server, or monitor the network of the server, they will be able to match VPN clients with their traffic, nullifying the privacy benefits of the VPN.

Such timing/correlation attacks are not difficult to accomplish. In countries with restrictive Internet regulations (China, Russia, Iran, Turkey, etc), or countries with broad surveillance powers (USA, UK, etc), state surveillance agencies typically have the legal ability to coerce either the VPN provider, or the network/server provider of the VPN provider, to assist with such network monitoring. Therefore, even though Proton VPN is based in Switzerland, we cannot be certain that authorities are not monitoring our VPN servers located in those high-risk countries.
https://protonvpn.com/support/secure-core-vpn/

**Actual behavior:**
I feel uncertainty about what happens when I connect to the second server using the second VPN adapter, because the connection drops.
There is no convenient menu.

**Comment by Guest126** [comment]
It's the system, not a function. You (or VPN service provider) do it.
Intermediate VPN servers act as VPN clients as well, thus forming a VPN chain.

Note: Tor and DeleGate Proxy have the ability to specify intermediate and exit nodes. This is something VPNs cannot do.

**Comment by domosekai** [comment]
SoftEther already supports cascading.
