### ISSUE TITLE
Feature request: Native local TOR proxy support

### ISSUE THREAD

**Issue by pinkrootninja** [SoftEtherVPN/SoftEtherVPN#1636]
### Prerequisites

* [Yes] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** SoftEther VPN 4.0 (Ver 4.39, Build 9772)
**Component:** [Client]
**Operating system:** [Windows]
**Architecture:** [64 bit, 32 bit]

### Description

**Expected behavior:**
Usually when you connect to a VPN server all the connections should go through it. But if you try to run local proxy like TOR and then try to use it, the TOR itself will start trying to go through the VPN connection that works through TOR. So, it is a dead end.

The implementation should consider this and add some sort of layer to prevent that. It should include the ability to use TOR bridges (https://tb-manual.torproject.org/bridges/)

**Actual behavior:**
VPN connection drops.

**Comment by Guest126** [comment]
It is known to work with Tor proxy but does not work with aother local proxies.

[VPN Gate - MonoBook](https://monobook.org/w/index.php?title=VPN_Gate)

**Comment by domosekai** [comment]
Disable routing table adjustment if you don't want TOR or any internet traffic to be redirected to VPN.
