### ISSUE TITLE
Can't open .ovpn file using Windows' "Open with"

### ISSUE THREAD

**Issue by pinkrootninja** [SoftEtherVPN/SoftEtherVPN#1637]
### Prerequisites

* [Yes] Can you reproduce?
* [Yes] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** SoftEther VPN 4.0 (Ver 4.39, Build 9772)
**Component:** [Client]
**Operating system:** [Windows]
**Architecture:** [64 bit, 32 bit]

### Description

**Expected behavior:**
.ovpn file is read and SoftEther VPN application give the window where I can fill needed IKEv2 username and password.

**Actual behavior:**
vpncmgr_x64.exe : nothing
vpnclient_x64.exe : window with command line arguments list

### Steps to reproduce

1. Click right mouse button on pre-configured .ovpn file
2. Click "Open with..."
3. Choose the .exe-file of SoftEther VPN

**Comment by domosekai** [comment]
.ovpn is OpenVPN configuration file and why softether is supposed to open it?
