### ISSUE TITLE
lport or local bind

### ISSUE THREAD

**Issue by praveenindia** [SoftEtherVPN/SoftEtherVPN#164]
please add local bind options for softether clients or local port and user can change port numbers

**Comment by nomadturk** [comment]
For changing ports,

You can use either the SoftEther VPN Admin GUI for windows or you can do that from command line if that's a *NIX server.

Windows GUI works fine and it's easy to understand and can do those things you require.

**Comment by praveenindia** [comment]
you are wrong i am not server admin to change remote port used by vpn server.
I am asking SoftEther VPN Client manager windows needed option change local port used by vpn config not remote port (like openvpn remote port set by vpn provider but local port can be changed by user using lport option and user can bind to any port, but in softether vpn client manager only option to change remote port )

**Comment by moatazelmasry2** [comment]
Sorry the question is not clear at all. Which port are you talking about? When you start the connection from your PC, a socket is created on your machine with a port number > 1024 and connects to whatever port on the SE-Server (port 443 or so)

Which port do you want to change now?? and why??

**Comment by domosekai** [comment]
Close due to inactivity
