### ISSUE TITLE
Disabling NAT-T on client side creates invalid hostname in TLS Handshake

### ISSUE THREAD

**Issue by qupfer** [SoftEtherVPN/SoftEtherVPN#1642]
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version: 9772**
**Component: Client**
**Operating system: Windows 11 as KVM-VM on proxmox 7**
**Architecture: 64 bit**

**Processor: Intel(R) Core(TM) i5-6500T CPU** 

### Description

Disabling NAT-T with the client GUI adds "/tcp" to the hostname used in the client-hello during TLS Handshare.
A '/' is not valid for a hostname. 
Is between Client and Server a SNI reading  capable device/programm (firewall, reverse proxy), this can be a problem, as the other tool may not match the hostname or reject them as its invalid. 

**Expected behavior:**
Softether creates valid TLS Handshake 
**Actual behavior:**
Softether creates invalid TLS Handshake

### Steps to reproduce

1. configure SoftEthers own SSL-VPN on client side
2. disable NAT-T
3. try to connect

The Client-Hello will contain an invalid hostname as SNI extension.
![grafik](https://user-images.githubusercontent.com/2614431/182785597-4a6614f1-097d-4dec-9531-f65b4f662f9f.png)

I think - without having any clue of the SoftEther code - the "/tcp"  flag should be treated as what it is - a (context) path. That means that the client doesn't add the '/tcp' to the hostname, but to the request and on server side, SE should check if the path is '/' (NAT-T) or '/tcp' (no NAT-T).

kind regards
Henning

**Comment by domosekai** [comment]
This issue is already fixed in this repo. But the fix is not backported to 4.x version.

**Comment by qupfer** [comment]
Thanks for the quick answer. I will close this issue, as its not urgend for me and will be fixed in future versions (works in my envirionment (HAproxy).
