### ISSUE TITLE
Enabling SSTP does not create a listening connection

### ISSUE THREAD

**Issue by akuropka** [SoftEtherVPN/SoftEtherVPN#1646]
### Prerequisites

* [X] Can you reproduce?
* [X] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** https://github.com/SoftEtherVPN/SoftEtherVPN/commit/e85fc4435e352f50a6970d3c7b6fe78ab5ff4463
**Component:** Server
**Operating system:** Arch Linux
**Architecture:** aarch64
**Device:** RPi 4

### Description

Enabled SSTP with vpnsmgr

> root@raspberry ~ # cat /etc/vpn_server.config
...
> declare SSTP
>                         {
>                                 bool Enabled true
>                         }
... 

**Expected behavior:**
The relevant port is opened thus SSTP connections not accepted (L2TP/IPsec is working).

**Actual behavior:**
No port is opened

> root@raspberry ~ # netstat -ltup | grep vpnserver
> tcp        0      0 0.0.0.0:personal-agent  0.0.0.0:*               LISTEN      368/vpnserver
> tcp6       0      0 [::]:personal-agent     [::]:*                  LISTEN      368/vpnserver
> udp        0      0 0.0.0.0:39796           0.0.0.0:*                           368/vpnserver
> udp        0      0 localhost:ipsec-nat-t   0.0.0.0:*                           368/vpnserver
> udp        0      0 raspberry:ipsec-nat-t   0.0.0.0:*                           368/vpnserver
> udp        0      0 localhost:isakmp        0.0.0.0:*                           368/vpnserver
> udp        0      0 raspberry:isakmp        0.0.0.0:*                           368/vpnserver
> udp        0      0 0.0.0.0:10989           0.0.0.0:*                           368/vpnserver
> udp6       0      0 p200300e1ef:ipsec-nat-t [::]:*                              368/vpnserver
> udp6       0      0 localhost:ipsec-nat-t   [::]:*                              368/vpnserver
> udp6       0      0 raspberry:ipsec-nat-t   [::]:*                              368/vpnserver
> udp6       0      0 p200300e1ef2d180:isakmp [::]:*                              368/vpnserver
> udp6       0      0 localhost:isakmp        [::]:*                              368/vpnserver
> udp6       0      0 raspberry:isakmp        [::]:*                              368/vpnserver
> root@raspberry ~ # netstat -lntup | grep 443
> root@raspberry ~ :( #

### Steps to reproduce
as aobe

**Comment by andrewfer000** [comment]
Can you check your listening ports to see if 443 tcp is listed? Also can you try and connect to Port 443 tcp using a SoftEther VPN client?

**Comment by akuropka** [comment]
443 is not listed (see second command), tried to connect to 443 from a different machine and did not work (log does not show any attempt either).
Will check with the client later.
Is there any way to trace this further? (Didn’t find any error in logs)

**Comment by andrewfer000** [comment]
Did you check that SoftEther had port 443 enabled? I think if you run  ListenerEnable 443 in the SoftEther CLI it will be on. If that doesn't fix it let me know.

**Comment by akuropka** [comment]
@andrewfer000, thank you very much for your hint.
I needed to create the port by `ListenerCreate 443` (`ListenerEnable` caused an error). I was not aware of this requirement, maybe because L2TP/IPsec is using UDP.
My fault.. 😞

**Comment by akuropka** [comment]
Okay, memory is coming back... I was removing port 443 as I didn't want to expose the admin console to the outside world.
I am wondering whether it is possible to limit administration to port 5555 (or any other selected one) and keep 443 for SSTP only.

**Comment by andrewfer000** [comment]
> Okay, memory is coming back... I was removing port 443 as I didn't want to expose the admin console to the outside world.
> I am wondering whether it is possible to limit administration to port 5555 (or any other selected one) and keep 443 for SSTP only.

As far as I know this is impossible at the moment due to SoftEther's design/architecture. Not sure if there is a setting to change it.
