### ISSUE TITLE
What happened if port listener shows error?

### ISSUE THREAD

**Issue by Lulixue** [SoftEtherVPN/SoftEtherVPN#1651]
Hi, I recently failed to connect to VPN.

And Softether server manager shows below:

![WechatIMG46](https://user-images.githubusercontent.com/7261326/185746102-0afab0ad-ea9b-4b80-bfdd-81797564f306.png)

Can somebody please help me with this ?

**Comment by domosekai** [comment]
The server is not running as root.

**Comment by andrewfer000** [comment]
Either you are not running as root or you have other programs listening on those ports.

**Comment by Lulixue** [comment]
Thank you so much.
