### ISSUE TITLE
[Feature request] auto connect vpn server one by one 

### ISSUE THREAD

**Issue by fantasyado** [SoftEtherVPN/SoftEtherVPN#1652]
Hi.

Thanks for building this awesome tool!  I am new user of [SoftEtherVPN] on windows, but it seems a lot of servers could not be connected so I have to mannualy try to connect the servers one by one.   I'm wondering if it can have a feature like "One Key Connect" when user clicks it, it will automatically try to connect the server in the server list one by one until a valid server is connected?

**Comment by domosekai** [comment]
This is the repo for the open sourced Softether VPN software. For vpngate questions go to www.vpnusers.com forum.
