### ISSUE TITLE
[bug] issue with server list sort by connection speed 

### ISSUE THREAD

**Issue by fantasyado** [SoftEtherVPN/SoftEtherVPN#1653]
![image](https://user-images.githubusercontent.com/10321851/185978351-452d97bb-49fe-483e-995c-cf5e6b5c6774.png)

It sorts the server connection speed as String which is wrong.

---

### Prerequisites

* [x] Can you reproduce?
   Yes
* [x] Are you running the latest version of SoftEtherVPN?
  Yes

**SoftEther version:**
**Component:** [ Client]
**Operating system:** [Windows]
**Architecture:** [64 bit]
my client version:
![image](https://user-images.githubusercontent.com/10321851/185979404-31396b11-2a94-41ac-89fb-3e1b811a45b6.png)

 

### Steps to reproduce

Just open the server list and click header of "connection speed"("线路速度" in Chinese) row

**Comment by domosekai** [comment]
VPN gate issues should be posted at vpnusers forum.
