### ISSUE TITLE
[iOS SSTP Connect] Authentication fails with SE-VPN

### ISSUE THREAD

**Issue by akuropka** [SoftEtherVPN/SoftEtherVPN#1654]
### Prerequisites

* [X] Can you reproduce?
* [X] Are you running the latest version of SoftEtherVPN? 

**SoftEther version:** Version 5.02 Build 5180 (https://github.com/SoftEtherVPN/SoftEtherVPN/commit/e85fc4435e352f50a6970d3c7b6fe78ab5ff4463)
**Component:** Server
**Operating system:** Arch Linux Arm
**Architecture:** 64 bit
**Device:** RaspBerry Pi 4

### Description

I am using [SSTP Connect](https://apps.apple.com/de/app/sstp-connect/id1543667909) on iOS.
While connection succeeds with SSTP protocol I get an authentication error with SE-VPN protocol.

**Expected behavior:**
Client connects matters not if `SSTP` or `SE-VPN` is used.

**Actual behavior:**
Error upon connecting: `Connection Failed. Incorrect username, password or certificate.`
Yet all authentication data remains same (just swapping protocol) except Virtual Hub name is provided (and recognized by server protocol) and number of connections set to one.

### Steps to reproduce

1. Install SSTP Connect.
2. Set up profile as `SSTP`-VPN with required data.
3. Check if client connects and disconnect it afterwards.
4. Edit profile.
5. Switch protocol to `SoftEther (SE-VPN)`.
6. Fill in `Virtual hub` and numbers of `Connctions`.

### Log files
[Client.log](https://github.com/SoftEtherVPN/SoftEtherVPN/files/9402996/Client.log)
[Server.log](https://github.com/SoftEtherVPN/SoftEtherVPN/files/9402997/Server.log)

**Comment by domosekai** [comment]
I have no idea what has gone wrong. A few suggestions for you. 

1. Retry with a new account with simple password
2. Try connecting from a windows client
2. Use a stable iOS version

**Comment by akuropka** [comment]
Hi @domosekai,
I tested further and it seems password is not valid anymore once switching an existing profile from one protocol to another. This is app-related and maybe it can be fixed or password should be cleared upon switching. However, switching back seems to make it readable again.
Just for your reference since you're the developer of the app.

**Comment by domosekai** [comment]
That's interesting because I change protocol from time to time when using the app and have never encountered such problem. If you can reproduce the issue please advise how to do it. Thank you.
