### ISSUE TITLE
[Once Again!] IKEV2

### ISSUE THREAD

**Issue by MG-Token** [SoftEtherVPN/SoftEtherVPN#1664]
Hi all!
SoftEtherVPN is best vpn server and client manager
but this project just need 2 vpn protocol to finish up at once all!
PPTP [Deperected but good enough :)] 
IKEV2/IPSEC (psk-mschap2-rsa)
IKEV2 is requested from 2014 but its not finished up? or what happened?

Thanks a lot!

**Comment by metalefty** [comment]
Dup of #13

**Comment by domosekai** [comment]
Creating new issues won't help things. Someone has to write code.
