### ISSUE TITLE
OCSP is not supported

### ISSUE THREAD

**Issue by cvalka2** [SoftEtherVPN/SoftEtherVPN#1667]
The Online Certificate Status Protocol is not supported. Why is that?

**Comment by domosekai** [comment]
Major browsers also do not check that.
https://www.ssl.com/blogs/how-do-browsers-handle-revoked-ssl-tls-certificates/

**Comment by cvalka2** [comment]
I'm sorry but what's the alternative?

**Comment by cvalka4** [comment]
@domosekai https://www.ssl.com/blogs/how-do-browsers-handle-revoked-ssl-tls-certificates/#:~:text=Unlike%20Chrome%2C%20Firefox%E2%80%99s%20default%20settings%20also%20query%20OCSP%20responders%20to%20confirm%20the%20validity%20of%20SSL/TLS%20certificates.%20(You%20can%20change%20this%20setting%20in%20Firefox%E2%80%99s%20security%20preferences.)
Firefox does support OCSP. Chrome has its own proprietary CRL.
You can do OCSP or CRL or both. But doing none is unacceptable from the security standpoint.

**Comment by cvalka4** [comment]
pull request #1775   solves this. The right approach is to delegate AAA (Authentication, Authorization, Audit) to a radius server. FreeRADIUS can obviously do OCSP.
@domosekai Thank you and this ticket should be closed.
