### ISSUE TITLE
how auto change IP adress

### ISSUE THREAD

**Issue by sognos** [SoftEtherVPN/SoftEtherVPN#167]
i search a lot to make the vpn gate change my IP adress but i found nothing 
can you help me to solve this issue ?

**Comment by curious-boy** [comment]
When you connect success, your IP was changed; 
If your IP is old IP, connect was failed. I think.

**Comment by sognos** [comment]
No i mean that every 5 min or 15 min my IP change automatically, without that i change it manually

**Comment by moatazelmasry2** [comment]
No such feature is currently implemented unfortunately.

May I ask why do you want to do that?

**Comment by moatazelmasry2** [comment]
No answer in a long time. Closing this issue
