### ISSUE TITLE
[Bug]: VPN Server Manager doesn't work on macOS 12.6

### ISSUE THREAD

**Issue by Drjacky** [SoftEtherVPN/SoftEtherVPN#1672]
I installed this https://www.softether-download.com/files/softether/v4.21-9613-beta-2016.04.24-tree/Mac_OS_X/Admin_Tools/VPN_Server_Manager_Package/softether-vpnserver_manager-v4.21-9613-beta-2016.04.24-macos-x86-32bit.pkg on macOS 12.6, but it doesn't open.

**Comment by domosekai** [comment]
It only works on Intel macs.

**Comment by davidebeatrici** [comment]
Shouldn't the emulation layer kick in?

**Comment by Drjacky** [comment]
It is Intel @domosekai

**Comment by domosekai** [comment]
Sorry to hear that. Anyway, the VPN Server Manager you downloaded is not maintained at this repo. It's distributed by SoftEther Corporation directly and any question should be directed to the vpnusers forum.
