### ISSUE TITLE
Request for Flutter (UI Framework) Client

### ISSUE THREAD

**Issue by drexhacker** [SoftEtherVPN/SoftEtherVPN#1673]
#Feather Request
Hello there!, I am a Flutter Developer with love in Networking I would like to create a Flutter VPN App that uses SoftEther VPN Servers as backend servers for VPN connections. I would also like to contribute to the development of a flutter plugin to be published to pub.dev for even other developers to be able to utilise the system. If possible and also if provided guided on the internal logic of SoftEther Client. I would also like to receive advise on this thank you!

Also not forgetting to Say Thanks Alot for the Good Work.

**Comment by shakibamoshiri** [comment]
Hi @drexhacker , good idea 

You can start developing any client with [SoftEther VPN Server JSON-RPC API Suite Document](https://github.com/SoftEtherVPN/SoftEtherVPN/tree/master/developer_tools/vpnserver-jsonrpc-clients#softether-vpn-server-json-rpc-api-suite-document)

**Comment by domosekai** [comment]
You are free to do anything you want, provided that it conform to the Apache 2.0 license.
