### ISSUE TITLE
No easily accessible Windows binary

### ISSUE THREAD

**Issue by slrslr** [SoftEtherVPN/SoftEtherVPN#1676]
Nightly builds link at https://github.com/SoftEtherVPN/SoftEtherVPN/#for-windows links to a page where at https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_artifacts is no downloadable Windows binary.
Please fix the readme or Artifacts so person can download Windows binary.
At https://github.com/SoftEtherVPN/SoftEtherVPN/releases are some 2 year old PDBs .zip files.

**Comment by domosekai** [comment]
You need to select a build to see artifacts.

**Comment by slrslr** [comment]
> You need to select a build to see artifacts.

I do not see any way to select build and if there is, it does not seem apparent to newbie visitor:

![](https://i.postimg.cc/1RbRTvcr/Screenshot-20221024-122758.png)

**Comment by youring** [comment]
Select a build, for example, 20220807.1 is currently the latest build.
![s20221103_231755](https://user-images.githubusercontent.com/4132418/199761310-3543b6d7-ce96-4ba2-8fa5-2d8f46b0b63c.jpg)
Found the little icon for # published, click then you can download the whole pack of installers or binaries.
![s20221103_231839](https://user-images.githubusercontent.com/4132418/199761789-9e51503e-ec6b-4dba-bb3a-e53ba552490d.jpg)

**Comment by slrslr** [comment]
No luck finding the page on the screenshots.

**Comment by youring** [comment]
This is the link: https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_build?definitionId=6
![s20221103_233701](https://user-images.githubusercontent.com/4132418/199765844-59788b38-291d-4279-a929-d104435ae339.jpg)

Maybe you have to sign in Azure with your Microsoft/outlook account first.

**Comment by youring** [comment]
For the record current nightly builds is a bit old too, and only for windows. Would you mind trigger a new build and publish Ubuntu builds or source, @davidebeatrici  thanks you in advance!
softether-vpnclient-5.02.5274.x86.exe
softether-vpnserver_vpnbridge-5.02.5274.x86.exe
softether-vpnclient-5.02.5274.x64.exe
softether-vpnserver_vpnbridge-5.02.5274.x64.exe

**Comment by slrslr** [comment]
> This is the link

Indeed. Actually accidentally landing to this page i would not think the download would be hiding behind items shown on your screenshot. And i was unable to find it after clicking first item. Maybe not logged in or such. Which remind my complain described in the title of this issue. I do not think that this issue should be closed.
