### ISSUE TITLE
Profiles for routing networks?

### ISSUE THREAD

**Issue by paulmenzel** [SoftEtherVPN/SoftEtherVPN#1678]
Please excuse my ignorance. Does L2TP and the OS clients support to set up profiles to only use the VPN connection for certain IP address ranges, so for example private video streaming is not routed over VPN? [eduVPN](https://www.eduvpn.org/) supposedly supports something like this.

**Comment by domosekai** [comment]
On Windows you can add static routes but probably not within a profile. You can also play with pushed routes with virtual DHCP or a standalone DHCP server.

**Comment by ZARD20** [comment]
试过很多这个确实来噻，注册送永久的流量的，兄弟们可以试试https://915merry.top/auth/register?code=aFk138
