### ISSUE TITLE
lib for openvpn client

### ISSUE THREAD

**Issue by diorahman** [SoftEtherVPN/SoftEtherVPN#168]
Hi,

I need to build an app with openvpn client as one of its functionalities, is there any examples that I can follow? I believe building a lib will be beneficial for everyone.

Thanks

**Comment by otraore** [comment]
Hey if you're still there I think I might be able to help.

**Comment by diorahman** [comment]
Yes @otraore do you have a hint?

**Comment by moatazelmasry2** [comment]
If you are talking about android, there's a library that we used in the past and it works quite fine.

https://github.com/schwabe/ics-openvpn

**Comment by moatazelmasry2** [comment]
No answer in a long time. Closing this issue
