### ISSUE TITLE
Extremely High CPU usage

### ISSUE THREAD

**Issue by deeztek** [SoftEtherVPN/SoftEtherVPN#1681]
Hi, there!

Thank you for using SoftEther.

If you are running SoftEther VPN 4.x (i.e. Stable Edition), please read the comparison with Developer Edition at: 

https://github.com/SoftEtherVPN/SoftEtherVPN#comparison-with-stable-edition

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [ ] Can you reproduce? YES
* [ ] Are you running the latest version of SoftEtherVPN? YES

**SoftEther version: 4.39 Build 9772
**Component: Server
**Operating system: Linux
**Architecture: 64 Bit

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** Intel XEON D-1541

### Description

Softether consumes all CPU

**Expected behavior:**
Not consume all CPU

**Actual behavior:**
It starts off normally consuming about 1% of CPU. After sometime (maybe 1 hour or so) the CPU for the vpncmd process is consuming 100% of the CPU. It seems to be related to the number of sessions. I have a client connections with about 20 concurrent sessions. There is no bridge defined. I have disabled DisableKernelModeSecureNAT based on previous posts about this issue but nothing is helping. I have another Softether server running version 4.36 build 9754 that does not seem to have this issue.

### Steps to reproduce

1. Connect to Softether VPN server
2. Wait 1 hour or so
3. vpncmd process takes up 100% of CPU.

**Comment by metalefty** [comment]
You didn't read the issue template. 

You should have been guided that if the answer is yes whether you're using version 4.x,  you should ask your question on [www.vpnusers.com](http://www.vpnusers.com/).

**Comment by deeztek** [comment]
Is this a joke?

**Comment by metalefty** [comment]
Then, can you confirm if the same issue occurs with 5.x? Anyway, here's the place to report/ask questions for version 5.x.

**Comment by metalefty** [comment]
Also, that's strange that `vpncmd` consumes CPU. `vpncmd` is not a VPN server process but a VPN command line management tool with very low CPU usage. It is natural that changing the configuration does not save CPU usage because it doesn't offer any VPN connectivity at all. You can terminate the `vpncmd` whenever you're not doing VPN server management.

**Comment by deeztek** [comment]
I see. Okay I got it figured out I think. Your comment about vpncmd got me to look in the right place. Thanks!
