### ISSUE TITLE
VPN does not send any requests to RADIUS

### ISSUE THREAD

**Issue by OpneMind** [SoftEtherVPN/SoftEtherVPN#1682]
Hi
I set radius config on SoftEtherVpn, (ip, secret, * user ...) but vpnserver don't sent anything to my radius. (Openvpn now working with my radius).

how to debug verbose and solve this problem?

in my log:

`User authentication failed. The user name that has been provided was "USERNAME"`

thanks a lot

**Comment by domosekai** [comment]
RADIUS is working properly. Make sure the user auth type is RADIUS.
