### ISSUE TITLE
how to disable tls handshake

### ISSUE THREAD

**Issue by amir6182p** [SoftEtherVPN/SoftEtherVPN#1683]
Hi, there!

Thank you for using SoftEther.

If you are running SoftEther VPN 4.x (i.e. Stable Edition), please read the comparison with Developer Edition at: 

https://github.com/SoftEtherVPN/SoftEtherVPN#comparison-with-stable-edition

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [ ] Can you reproduce?
* [ ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** [Server, Client, Bridge, etc.]
**Operating system:** [Windows, Linux, BSD, macOS, etc.]
**Architecture:** [64 bit, 32 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]

### Description

[Description of the bug]

**Expected behavior:**
[What you expected to happen]

**Actual behavior:**
[What actually happened]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [And so on...]

**Comment by amir6182p** [comment]
my country has blocked tls handshake.how to disable it for openvpn connection?

**Comment by shipitsin-ilia** [comment]
openvpn uses its own implementation of handshakes. it is not possible to disable them, but you can try tls-crypt feature

**Comment by amir6182p** [comment]
As i know.you said add tls-crypt on softether openvpn profile?

**Comment by shipitsin-ilia** [comment]
SE VPN did not implement tls-crypt. I mean openvpn itself.

however, there are things to try with SE VPN. it supports "xor" in automatic mode thanks to @davidebeatrici

**Comment by shipitsin-ilia** [comment]
alternatively, you can try https-mode vpn (SE VPN own protocol or some openconnect variant), if https is not blocked as well.

**Comment by ZARD20** [comment]
试过很多这个确实来噻，注册送永久的流量的，兄弟们可以试试https://915merry.top/auth/register?code=aFk138
