### ISSUE TITLE
custom http header support

### ISSUE THREAD

**Issue by praveenindia** [SoftEtherVPN/SoftEtherVPN#169]
when using http proxy there is no option to send custom header like
Host: softether.com
X-Online-Host: softether.com

**Comment by gdh1995** [comment]
Since VPN works on IP layer, not Application Layer, I think your idea has no use.

You can play any online PC games when VPN is connected, and those games usually use TCP/UDP connection directly instead of a HTTP request.

**Comment by moatazelmasry2** [comment]
You can achieve that by a program that mingle with network layer 4-7. For example squid is able to add whatever headers to http requests
