### ISSUE TITLE
Version, OS type, and hostname is leaking

### ISSUE THREAD

**Issue by yourorikamo** [SoftEtherVPN/SoftEtherVPN#17]
I can find some information of the server when I connect to Server from other computer(no localhost).

For example,

what type of OS
Server Hostname(equals Server name in Windows)
SoftetherVPN build version

How can I hide these information?
Clients should not know about these things. (Only an admin should know about them)
Hackers will use those information to DoS SoftetherVPN server.

**Comment by moatazelmasry2** [comment]
I also agree that this should be implemented. I added a "good first issue" tag and hope someone will implement it soon.
