### ISSUE TITLE
Windows Client: Ctrl+O should open options but opens traffic tool

### ISSUE THREAD

**Issue by metalefty** [SoftEtherVPN/SoftEtherVPN#1702]
## Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** I'm using this build artifact.

* https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_build/results?buildId=932&view=results

**Component:** Client
**Operating system:** Windows
**Architecture:** 64 bit

### Description

**Expected behavior:**
Options should open when pressing Ctrl+O

**Actual behavior:**
Traffic tool will open.

### Steps to reproduce

1. Install SoftEtherVPN client 
2. Press Ctrl+O on keyboard
3. Options should open but traffic tool will open

![image](https://user-images.githubusercontent.com/941609/202339644-606feb41-d0f7-499d-90dd-6cdc0a7e087f.png)

**Comment by domosekai** [comment]
Looks like a copy-paste error. Feel free to send a PR.
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/9eb9d57c27e530191940ecdc836230b4505bcc2f/src/Cedar/CM.c#L411-L422

**Comment by metalefty** [comment]
Thanks, I'll raise it soon.

**Comment by metalefty** [comment]
@dnobori san, I first find this issue in the stable version. I'd appreciate id you could apply this also to the stable version.

https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/blob/master/src/Cedar/CM.c#L527-L538

**Comment by dnobori** [comment]
@metalefty Thank you so much. I will do that.
