### ISSUE TITLE
EVP_PKEY_get_raw_public_key() not found in OpenSSL library

### ISSUE THREAD

**Issue by weili0677** [SoftEtherVPN/SoftEtherVPN#1705]
I use VS2019 on windows 11. and Cmark get error:

CMake Error at src/Mayaqua/CMakeLists.txt:32 (message):
  Required EVP_PKEY_get_raw_public_key() not found in OpenSSL library!		F:\zyl\soft\vpn\SoftEther\source\SoftEtherVPN-master\src/Mayaqua/CMakeLists.txt	32

**Comment by domosekai** [comment]
Please follow our instructions.

**Comment by whbwyj** [comment]
> 不好意思。我找到了方法。谢谢。

您好，怎么解决的？

**Comment by weili0677** [comment]
> > 不好意思。我找到了方法。谢谢。
> 
> 您好，怎么解决的？

我不是解决这个问题，我之前想自己编译主要是解决那个官方开源的版本vpn路由推送限制问题。。我用另外的方式解决了。
