### ISSUE TITLE
$ git clone https://code.onedev.io/SoftEther/VPN.git

### ISSUE THREAD

**Issue by AliS242** [SoftEtherVPN/SoftEtherVPN#1710]

**Comment by shipitsin-ilia** [comment]
what's the issue ?

![image](https://user-images.githubusercontent.com/108898059/203913874-1c0f9e06-8180-4d57-beb9-19b284c83bad.png)

**Comment by davidebeatrici** [comment]
The link is currently https://code.onedev.io/projects/497, see https://code.onedev.io/projects/160/issues/458.
