### ISSUE TITLE
Add DHCP or domain name filtering blacklist and whitelist

### ISSUE THREAD

**Issue by danyhm** [SoftEtherVPN/SoftEtherVPN#1713]
hello,

as the use of VPN grows every day, the need for a whilelist&blacklist for domain names arises. this is in addition to the IP filtering already available. since Domains IPs can be changes, we can't track the IPs of the domains we want to blacklist or whitelist every time it changes.

please implement this feature.

**Comment by shipitsin-ilia** [comment]
as your request totally makes sense, it is beyond the scope of vpn software.

vpn software does not deal on domain level. the most close is dns server you use. you can set up to block some domains on dns level

**Comment by shipitsin-ilia** [comment]
another approach my be browser plugin which communicates with vpn software

**Comment by danyhm** [comment]
> as your request totally makes sense, it is beyond the scope of vpn software.
> 
> vpn software does not deal on domain level. the most close is dns server you use. you can set up to block some domains on dns level

how can i block on DNS level?

**Comment by shakibamoshiri** [comment]
> > as your request totally makes sense, it is beyond the scope of vpn software.
> > vpn software does not deal on domain level. the most close is dns server you use. you can set up to block some domains on dns level
> 
> how can i block on DNS level?

Your `/etc/hosts` file 

```bash
0.0.0.0  facebook.com
```

See here [https://github.com/StevenBlack/hosts](https://github.com/StevenBlack/hosts)

**Comment by danyhm** [comment]
since this was very much needed and was beyond Softether VPN scope, i managed to do it using other simple tools.

blocking on DNS level is harder, however it's still possible by changing the following steps to work with ipset instead.

### Summary
To block or allow VPN traffic only (Inbound or Outbound) without messing with other system traffic or softether configuration do the following:
1- install `xtables` as described here
https://www.xmodulo.com/block-network-traffic-by-country-linux.html
2- create a user group specific for softether as described in here
https://askubuntu.com/questions/45072/how-to-control-internet-access-for-each-program
3- change the softether .service file to include the created group as described in here
https://www.golinuxcloud.com/run-systemd-service-specific-user-group-linux/
4- now you can control softether inbound and outbound traffic with iptables and support both ipranges, Geolocation, and domain names. ipset domain names described in here
https://unix.stackexchange.com/questions/557388/firewall-rules-based-on-domain-name-instead-of-ip-address

please note that I only put the URLs as references to the commands needed. you'll need to change them according to your needs.
