### ISSUE TITLE
How to use softether with Android 12

### ISSUE THREAD

**Issue by FurkanGozukara** [SoftEtherVPN/SoftEtherVPN#1714]
I was gonna use PPTP connection in my android phone but they removed all options unfortunately

The only available option is as below

So how can I use this connection with softether 

I did installation on windows server 2019 machine but non of the available guides matches for my android phones connection requirements

My phone is Xiaomi POCO X3 Pro

![Screenshot_2022-11-26-13-35-11-382_com android settings](https://user-images.githubusercontent.com/19240467/204084454-85f244d2-8f2a-4b84-a2e1-7a9e4f55fd78.jpg)

![image](https://user-images.githubusercontent.com/19240467/204084482-3c57cf22-cd47-4741-8186-7120d2f6c7be.png)

**Comment by andrewfer000** [comment]
Unfortunately SoftEther VPN does not support IKEv2 yet. Has been requested for a very long time however Implementing a new protocol takes a lot of work and the developers who know SE well enough to Implement a new protocol do not have the time right now to design, code, and test a new major feature such as that. If you want to connect your mobile device to your  SE server I would suggest either Open SSTP Client (Free) or VPN Client Pro (Paid).

**Comment by FurkanGozukara** [comment]
@andrewfer000 ty for answer. I have somehow found  a way to make it work with open VPN. I will prepare a tutorial video. The documentation is totally lacking and not working in modern android
