### ISSUE TITLE
openvpn configures multiple accounts to log in at the same time

### ISSUE THREAD

**Issue by nazh888888** [SoftEtherVPN/SoftEtherVPN#1719]
My softether version is Version 4.38 Build 9760. I can only log in to one account at a time when using openvpn. How do I configure multiple accounts to log in at the same time? thanks

**Comment by shakibamoshiri** [comment]
Go to policy setting, 
- enable policy setting 
- set Mulit User login to more than 1, e.g 2

**Comment by danyhm** [comment]
this is by default enabled unless you limited the user login count in your virtual hub properties

**Comment by domosekai** [comment]
I can't reproduce the issue.
