### ISSUE TITLE
Android 12 no  supports L2TP. When will softether be updated to support IKEV2?

### ISSUE THREAD

**Issue by Jabiler** [SoftEtherVPN/SoftEtherVPN#1720]
Android 12 no  supports L2TP. When will softether be updated to support IKEV2?

**Comment by IngwiePhoenix** [comment]
LineageOS 19.1 based on Android 12:

![Screenshot_20221205-131454_Einstellungen](https://user-images.githubusercontent.com/2893716/205635059-121f37c5-4a72-4f71-b48e-c5cf6542fae2.png)

I can see L2TP just fine. Maybe your vendor's Android ROM has it disabled?

**Comment by domosekai** [comment]
Duplicate of #13
