### ISSUE TITLE
In app use

### ISSUE THREAD

**Issue by amirhossinD** [SoftEtherVPN/SoftEtherVPN#1723]
Hello to dear Softether Developers
Can I use Softether as an in-app VPN in my C# program?
I want to run Softether in my app for my app users.
I will very much appreciate it if you guide me.

**Comment by shakibamoshiri** [comment]
HI @amirhossinD 
Here is for  
- bug reports
- feature requests

Ask you question here [https://www.vpnusers.com/](https://www.vpnusers.com/)
