### ISSUE TITLE
Traffic amount limitation Option

### ISSUE THREAD

**Issue by bargiaurmia** [SoftEtherVPN/SoftEtherVPN#1724]
I've cruised through the options and have not found one to set a limit, such as allocating 50GB on a plan. A user gets 50GB and if limit is reach the session is disconnected.

Is there such an option or any insight on a possible solution would be appreciated.

Thank you,

**Comment by metalefty** [comment]
Bandwidth can be configured not possible to configure total amount so far.

**Comment by pedrambk** [comment]
There is a problem in creating this feature
By checking, you can see that there are several requests for this feature
