### ISSUE TITLE
Get Client IP? VPN adapter has none...

### ISSUE THREAD

**Issue by IngwiePhoenix** [SoftEtherVPN/SoftEtherVPN#1726]
Hello!

> (template) Is this a question?

Yes - but my question there hasn't gotten verified for quite a while now... so I am trying my luck here. Sorry!

I have set up a server with the 4.x branch - as it was refered to as stable and the first one that I came across - and now I managed to connect my OpenWRT router to it. This router also acts as a mini server, running quite a number of services for me.

However: I don't know their IPs...

```
root@birb:~# ifconfig vpn_vpn
vpn_vpn: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::5c19:fcff:fedf:f990  prefixlen 64  scopeid 0x20<link>
        ether 5e:19:fc:df:f9:90  txqueuelen 1000  (Ethernet)
        RX packets 606122  bytes 36580309 (34.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1815  bytes 150432 (146.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

# ---

root@openwrt:~# ifconfig vpn_vpn
vpn_vpn   Link encap:Ethernet  HWaddr 5E:37:1F:DA:29:3E
          inet6 addr: fe80::5c37:1fff:feda:293e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:720013 errors:0 dropped:5 overruns:0 frame:0
          TX packets:2276 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:43457876 (41.4 MiB)  TX bytes:192288 (187.7 KiB)
```

I do see their IPv6 addresses, but I do not see their actual connected IPs which I would use to ping or send data to the other host. I want to use my VPS as a reverse proxy/frontend for my mini server (plus Varnish caching etc.). But I am quite stumped for now. On my Windows maschine, I was told my IP and could even see it in `ipconfig`.

So, what am I missing?

Kind regards,
Ingwie

**Comment by IngwiePhoenix** [comment]
I ended up finding out why Windows managed to get an IP, and Linux did not. It is exactly the difference that Windows and Linux have: Windows will just do things on its own, Linux won't...

```
root@FriendlyWrt:~# udhcpc -i vpn_vpn
udhcpc: started, v1.35.0
udhcpc: broadcasting discover
udhcpc: broadcasting select for 192.168.222.11, server 192.168.222.1
udhcpc: lease of 192.168.222.11 obtained from 192.168.222.1, lease time 7200
udhcpc: ip addr add 192.168.222.11/255.255.255.0 broadcast + dev vpn_vpn

# ---

root@birb:/srv/softether-vpn# dhclient vpn_vpn
```

Now both have an IP. xD

If possible, please do let people know in the docs that there is a difference between DHCP lease handling inbetween Windows and Linux. This really stumped me for a while.

**Comment by domosekai** [comment]
It's in the manual, under Limitations.
https://www.softether.org/4-docs/1-manual/4._SoftEther_VPN_Client_Manual/4.1_Operating_System_Requirements
