### ISSUE TITLE
Wrong timestamps recorded in the configuration file (vpn_server.config)

### ISSUE THREAD

**Issue by jpclaudino** [SoftEtherVPN/SoftEtherVPN#1741]
**SoftEther version:** latest
**Component:** [Server]
**Operating system:** [Windows]
**Architecture:** [64 bit]

### Description
In a forensic case, I noticed that the timestamps recorded in the configuration file (vpn_server.config) for the Hubs and users (uint64 CreatedTime, uint64 LastLoginTime and uint64 UpdatedTime) were incorrect and also incompatible with the data given records in the Log files (directory server_log).

For example:

In the Log file (vpn_20230107.log), I noticed that the user's last login time was recorded correctly, presented in UTC-3:

2023-01-07 21:01:16.703 [HUB "HUBNAME"] Connection "CID-3-XXX": Successfully authenticated as user "USER".

However, the value stored in the configuration file (vpn_server.config - uint64 LastLoginTime 1673103676703), corresponded to the time 2023-01-07 12:01:16.703 (UTC-3), nine hours behind the correct time.

The same happened for the Hub creation time and other configuration file timestamps.

### Steps to reproduce
Just log into a VPN server via Azure hostname. The server was configured with UTC-3 timezone.
Then just observe data recorded in the configuration file.

**Comment by domosekai** [comment]
This is by design.
Config files are not supposed be read by users. Only time shown in vpncmd and server manager is relevant.
