### ISSUE TITLE
unfortunately build is really difficult

### ISSUE THREAD

**Issue by mohsensamiei** [SoftEtherVPN/SoftEtherVPN#1743]
Hi guys
As written in the readme, the advantages of using the development version are many, for example, wireguard integration, which I need a lot.
But unfortunately, it is really difficult to get a build from the system, should we have a build pipeline?

**Comment by andrewfer000** [comment]
Yes I know. Building for Windows is especially hard. (Linux is easy just copy and paste the commands and the src/build_UNIX.md guide). SE does have a CI/CD pipeline on Azure where you can download the latest builds as exe files and install them like normal.

**Comment by andrewfer000** [comment]
https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_build?definitionId=6

This will take you to the project's Azure CI/CD Pipeline. Feel free to explore and you'll find the downloads.

**Comment by domosekai** [comment]
Just follow our build instructions.
