### ISSUE TITLE
max user problem in ubuntu

### ISSUE THREAD

**Issue by bobyturk** [SoftEtherVPN/SoftEtherVPN#1748]
hi

iam using the softheter server on ubuntu using tunnel with cascade connection

when users reach 40-50 people the server giving error authetntacion error for some clients . 

i dont use any external authentication server exept the softheter .

both servers CPU and RAM usage are normal and under 50% and this is not a server hardware error 

i think i will increase some function somwhere but i dont know where !!

max vpn session is set to unlimited

**Comment by domosekai** [comment]
#1390

**Comment by domosekai** [comment]
This issue has been resolved in the developer edition.

**Comment by domosekai** [comment]
You are looking at it.

**Comment by bobyturk** [comment]
how could i install it in ubuntu 22.04 ?
