### ISSUE TITLE
[ Feature Request ] Create standard systemd templates for suite

### ISSUE THREAD

**Issue by aenertia** [SoftEtherVPN/SoftEtherVPN#175]
Softether VPN is great but especially esoteric in how it integrates into modern linux distros. Crafting systemd compatible unit files (including socket listener for each port) is relatively simple and should be included in the main trunk for reference.

Here is a basic service unit that works for the client (using the default installation paths provided by softether, which are odd also). There are some others floating around mainly around the vpnserver itself but a properly crafted one where individual port listeners etc are spawned on demand by systemd would be great.

[Unit]
Description=Softether VPNClient Daemon

[Service]
ExecStart=/usr/vpnclient/vpnclient start
Type=forking

[Install]
WantedBy=multi-user.target

**Comment by hsaito** [comment]
@aenertia If you need something that works today, here are some that covers all three components.
https://github.com/hsaito/SoftEtherVPN/tree/master/systemd

**Comment by moatazelmasry2** [comment]
@hsaito systemd directory has been merged into SoftEther a while ago. Closing this issue
