### ISSUE TITLE
how could limit maximum login per user ( multi login ) in bridge mode ?

### ISSUE THREAD

**Issue by bobyturk** [SoftEtherVPN/SoftEtherVPN#1750]
hi there . i need to limit the maximum login with same username (multi login ) in softheter bridge mode wich authenticate by softheter itself . i tried so many ways like limit ip or limit macadresses but cant limit the multilogins

**Comment by domosekai** [comment]
You can't.

**Comment by bobyturk** [comment]
is there any guide to connect softheter to ibsng for authenticating ? i did some ways but it dosent work with ibsng
