### ISSUE TITLE
softether limit download or packet transfer byte for user

### ISSUE THREAD

**Issue by pedrambk** [SoftEtherVPN/SoftEtherVPN#1753]
Is it possible to limit the softether packet transfer byte?
Solutions https://www.vpnusers.com/viewtopic.php?f=7&t=1870
I studied but it is not successful

**Comment by domosekai** [comment]
No.
Duplicate of #1389

**Comment by pedrambk** [comment]
There is a problem in creating this feature
By checking, you can see that there are several requests for this feature

**Comment by pedrambk** [comment]
There is a problem in creating this feature
By checking, you can see that there are several requests for this feature

https://www.vpnusers.com/viewtopic.php?f=7&t=1870
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1389
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1724
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1735
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1753
