### ISSUE TITLE
cascade connection lost many times

### ISSUE THREAD

**Issue by bobyturk** [SoftEtherVPN/SoftEtherVPN#1767]
Hi, there!

i am using cascade connection between 2 softether vpn server . but the cascade connection lost so many times during a day somtimes 2 days or even every hour !! i changed the servers location changed the port between 443 , 5555 and even 80 . 
i am enabled securena in second server and clients have to got ip from there .
the main problem is this . when the connection lost and reconnect again . clinets who connect via first server cant get ip and got autenthication error . i have to disconnect and reconnect the cascade many times to solve the problem . and this circle is goining forever ... anyone has any idea to solve this ?

**Comment by shakibamoshiri** [comment]
Github is used for 
- Bug report
- Asking for new feature (or PR)

Ask your question here
https://www.vpnusers.com/viewforum.php?f=7
