### ISSUE TITLE
Centos 7 spec files and RPM build

### ISSUE THREAD

**Issue by elico** [SoftEtherVPN/SoftEtherVPN#177]
Hey,
I am the current unofficial maintainer of the squid-cache project RPMs release for CentOS.
I wanted to somehow make it possible to have a spec\RPM files for CentOS 7 for the SoftEtherVPN.
However I found very little documentation(maybe looked up in the wrong place) on how to build the service on a linux machine.
I will later look at the existing SPEC files to make sure how it is done currently.

Before I am diving into building the RPM I wanted to verify that nobody else have done this until now and for the case I would need some help with the SoftEetherVPN code i would have some contact info by either email or IRC.

Thanks,
Eliezer

**Comment by mcsalgado** [comment]
I think you may want to check out #157, it adds config files for setting up systemd services.

**Comment by moatazelmasry2** [comment]
Please have a look under the directory centos/. There are now a SPECS and a readme file for building the rpm

**Comment by elico** [comment]
@moatazelmasry2 Thanks.
