### ISSUE TITLE
apt package manager version is behind

### ISSUE THREAD

**Issue by AuthorShin** [SoftEtherVPN/SoftEtherVPN#1777]
Hello
I installed SE on few Debian and Ubuntu systems with `apt install softether-vpnserver` but the version was `5.01 Build 9674` which is behind the latest release in this repository `5.02.5180`.
Who's supposed to update this?

P.S. I know I can compile the latest release myself but this way is much more convenient and I prefer this way so I would appreciate it if it was the latest release.

**Comment by metalefty** [comment]
You should ask the maintainer of that package.

**Comment by PizzaProgram** [comment]
@AuthorShin 
Just asking: Do you know that 5.01 and 5.02 are developer versions, not **stable** ones?
The main developers on the forum recommended me yesterday to use the last stable version, which is:
4.38
You may download directly from the: [Official page](https://www.softether-download.com/en.aspx?product=softether)
... and install it manually?

I will need to do the same soon (install to a Debian VPS), so I would appreciate if you could report back, how it went...
