### ISSUE TITLE
MikroTik sstp-client to SoftEther sstp server TLS handshake errors 

### ISSUE THREAD

**Issue by shakibamoshiri** [SoftEtherVPN/SoftEtherVPN#1788]
### Prerequisites

* [X] Can you reproduce?
* [X] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
Only developer version 5.02, built from source (clone of master) on a Debian 11 server

### Description
We can use MikroTik Rotuer OS sstp-client to connect to SoftEther VPN MS-SSTP server.  
It works if connecting to SE stable, but does not work if connecting to SE developer version.

**Expected behavior:**
MT should be able to connect to SE via MT's sstp-client 

**Actual behavior:**
| MT version | Client      | SE stable | SE developer |
|------------|-------------|-----------|--------------|
| 6.48       | sstp-client | YES       | NO           |
| 7.7        | sstp-client | YES       | NO           |

So MT cannot connect to SE developers version

**Errors**
TLS handshake errors 

### Steps to reproduce

1. setup MT os (paid or free)
2. setup SE developer and add a user to a hub
3. Use MT sstp-client to connect to SE sstp server

**Comment by chipitsine** [comment]
I wonder is there a way to setup router os sstp in automatic testing ?

**Comment by chipitsine** [comment]
or, can you describe how to setup (manually) router os from scratch and connect via sstp ?

**Comment by shakibamoshiri** [comment]
> or, can you describe how to setup (manually) router os from scratch and connect via sstp ?

sure   
there are MT commands you can run and test, I will provide them here

**Comment by domosekai** [comment]
I have no problem connecting Mikrotik client to DE version. It may be something different between your SE and DE settings.
Please note that Mikrotik supports the very weak cipher AES256-SHA only. Any advanced settings is not compatible with it, including ECDSA certificates.

**Comment by shakibamoshiri** [comment]
> I have no problem connecting Mikrotik client to DE version. It may be something different between your SE and DE settings. Please note that Mikrotik supports the very weak cipher AES256-SHA only. Any advanced settings is not compatible with it, including ECDSA certificates.

it is all default settings.
Did you configure SE server DE differently than default ones?
I will try it again

**Comment by domosekai** [comment]
Please post connection logs from both SE and DE. Descriptive wording is not helpful.

**Comment by shakibamoshiri** [comment]
> or, can you describe how to setup (manually) router os from scratch and connect via sstp ?

I forgot to ask. do you need commands for full setup double-vpn or just you need to test sstp-client.  
If just sstp-client test is needed here are the commands if you login to MT using `SSSH`   

```bash
/interface sstp-client
add name="sstp-out-home" max-mtu=1500 max-mru=1500 mrru=disabled connect-to=<YOUR_IP_HERE>:443 http-proxy=0.0.0.0:443 certificate=none verify-server-certificate=no verify-server-address-from-certificate=no user="100" password="T3LYmAaEHWjD" profile=default-encryption keepalive-timeout=60 add-default-route=no dial-on-demand=no authentication=pap,chap,mschap1,mschap2 pfs=no tls-version=any

# see the list and ID of a client
print

# enable that one
enable N

# then
/log print

# and you should see
15:51:50 sstp,ppp,info sstp-out-home: authenticated 
15:51:51 sstp,ppp,info sstp-out-home: connected
```

if you login in using "winbox" GUI , just go to ppp > interface > + add sstp-client and add your credentials   

**if you meant a full setup double-vpn, let me know please.**  
In version 6 we have PREROUTE and packet MASK (I tested worked) in MT version 7 we have PBR (Policy Based Routing) ( I did not tested yet)

**Comment by domosekai** [comment]
I know the cause.
You must be reusing the config from SE to DE. SE uses AES128-SHA cipher by default, which is not supported by Mikrotik.
However, the way SE handles the specified cipher is different with DE. 
SE only places the specified cipher in the first place, followed by the default cipher list.
DE uses the standard OpenSSL cipher string so if you specify AES128-SHA, it will only use AES128-SHA.
This is why in DE the default cipher is set to `~DEFAULT~` rather than a specific cipher.
The error message is clearly shown in the log which you failed to provide in the first place.

**Comment by domosekai** [comment]
#343 causes this. Unfortunately it was a breaking change.

**Comment by shakibamoshiri** [comment]
> I know the cause. You must be reusing the config from SE to DE. SE uses AES128-SHA cipher by default, which is not supported by Mikrotik. However, the way SE handles the specified cipher is different with DE. SE only places the specified cipher in the first place, followed by the default cipher list. DE uses the standard OpenSSL cipher string so if you specify AES128-SHA, it will only use AES128-SHA. This is why in DE the default cipher is set to `~DEFAULT~` rather than a specific cipher. The error message is clearly shown in the log which you failed to provide in the first place.

I ran the test near 1 month ago.  
About importing Stable config into Developer version, not sure, but it can be happened, since usually I shutdown one of them and start the other one while importing "vpn_server.config" file. Maybe I did it in that time.

I live in Iran and networks are not stable. In that time I was testing an OHV server  and did not work. 
Today at home I cloned and built from master and worked. :) **MT 6,48 to SE 5.02 OK**    
Thus at the moment while network are not reliable I doubt "vpn_server.config" swapping more than the network.
