### ISSUE TITLE
[RC4 and SSL3 completely!] Users, stop using this VPN and use OpenVPN. Seriously.

### ISSUE THREAD

**Issue by ghost** [SoftEtherVPN/SoftEtherVPN#179]
Dear SEVPN Developers,

Almost 1 year had passed since RC4's dead. And your software, Softether VPN and Packetix VPN
are still using it for encryption.
Why don't you just remove RC4 and SSL3, and use TLS1.2+AES_E?
If you're really against China's great firewall plan, you should use strong encryption
that all people, including governmental agent and journalists, can rely on.

I can see you didn't read these issues. I can say you're not interested in your software's security.
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/147
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/120

**Comment by espress0** [comment]
// title is ['Drop' RC4 and SSL3 completely!]. Sorry.

**Comment by dnobori** [comment]
After SoftEther VPN 4.11 Build 9506 Beta, the SSLv3 protocol can be completely disabled by setting the "bool AcceptOnlyTls" variable to "true" on the vpn_server.config file. For backward compatibility, this variable is set to "false" by default in the current version. We are planning to set it to "true" by default in future versions.

The removing setting for RC4 will be added to future versions.

**Comment by omlaverde** [comment]
Modify files:
/src/Cedar/Server.c
Line 132:
#define	SERVER_DEFAULT_CIPHER_NAME		"AES128-GCM-SHA256"

/src/Mayaqua/Network.c
Line 236:
static char *cipher_list = "AES128-GCM-SHA256 AES128-SHA256 AES256-GCM-SHA384 AES256-SHA256 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-SHA256 DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-SHA256 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384";

Recompile, instructions in BUILD_UNIX.TXT

Install:
cp bin/vpnserver/hamcore.se2  /opt/vpnserver
cp bin/vpnserver/vpnserver  /opt/vpnserver


Good luck

**Comment by davidebeatrici** [comment]
Solved by #343.
