### ISSUE TITLE
about softether vpn server memory leak

### ISSUE THREAD

**Issue by fefewolf** [SoftEtherVPN/SoftEtherVPN#181]
Hi, when vpnclient connect to vpnserver use sevpn protocol, vpnserver memory increase about 50 - 500kb every time，also vpnserver connect to vpnserver can make memory leak. 

So，who can help me find this memory leak. 

1 win7 x64 
2 SoftEther VPN Server Version 1.00 Build 9029
3 vpnserver user SecureNAT

**Comment by macvk** [comment]
Hi
You can start your search from module Mayaqua\Memory.c functions Add() and Delete(). Add to the list increase list capacity for INIT_NUM_RESERVED*2 items. You can try remove memory reservation.
Good luck.

**Comment by moatazelmasry2** [comment]
@fefewolf Why in your openion is this a mempory leak?? Isn't not obvious that every logged in user will use some server capacity. 

This would be a memory leak if for example, after a user logs out, no memory is freed.

**Comment by moatazelmasry2** [comment]
No answer in a long time. Closing this issue
