### ISSUE TITLE
Performance Query!!

### ISSUE THREAD

**Issue by clicksaswat** [SoftEtherVPN/SoftEtherVPN#182]
Hey, this is not an issue rather a query.
I'm using softether to bypass my isp restrictions. I've installed the server software on my vps and I'm using softether SSL vpn. But, I've found that the connection is pretty slow. As it is https, i'm pretty sure it isn't being throttled by the isp. So, theoritically I should get similar speed on browsing over the vpn as much as I'm getting without it. or even better with ssl vpn's compression enabled (note:my client system is pretty capable so compression decompression might not bother it that much). I do want to mention that my Server System is in a different geographic location and has a visible latency. Also the server system has only a single core and 512MB RAM. but, i'm the sole user of the vpn.

So, here's my question. What could be reason for the slow speed. I'm using mutiple tcp streams. Is it because of the latency issue or the weak hardware on the server. Please, reply so that I could make necessary updates to the hardware.

**Comment by macvk** [comment]
You do not need fast hardware. you need only good bandwidth. 

Test your server speed. you can use speedtest to do this. Google "speedtest centos"
