### ISSUE TITLE
Linux client does not use Wi-Fi to connect, always use Ethernet cable and failed to connect

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [SoftEtherVPN/SoftEtherVPN#1825]
### Prerequisites

* [x] Can you reproduce? `Yes`
* [x] Are you running the latest version of SoftEtherVPN? `Yes, the package on website`

**SoftEther version:** `Ver 4.41, Build 9787, rtm`
**Component:** `[Client]`
**Operating system:** `[Linux]`
**Architecture:** `[64 bit Intel x64 / AMD64 (64bit)]`

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]  
`hp 240 g9 laptop`  
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]  
`Intel Celeron N4500`

### Description

[Description of the bug]
VPN client not use Wi-Fi adapter / interface even Ethernet cable is disconnected

**Expected behavior:**
[What you expected to happen]
If Eth cable is disconnected and Wi-Fi network available, `vpnclient` daemon should use Wi-Fi adapter to make connection.

**Actual behavior:**
[What actually happened]
Once Eth cable is disconnected, `vpnclient` failed to connect any server until plug Eth cable back,  
Wi-Fi network is ignored. At the same time, browser and other application works (ping) fine with Wi-Fi network.

### Steps to reproduce

1. Install Fedora 37, compile and install Wi-Fi adapter driver, system update...
2. `wget https://www.softether-download.com/files/softether/v4.41-9787-rtm-2023.03.14-tree/Linux/SoftEther_VPN_Client/64bit_-_Intel_x64_or_AMD64/softether-vpnclient-v4.41-9787-rtm-2023.03.14-linux-x64-64bit.tar.gz`
3. `tar xf softether-vpnclient-v4.41-9787-rtm-2023.03.14-linux-x64-64bit.tar.gz`
4. `cd vpnclient`
5. `make`
6. Unplug Eth cable, connect Wi-Fi
7. `sudo ./vpnclient start`
8. `./vpncmd`, `2`, `Enter directly for local management`
9. `RemoteEnable`
10. Connect to this `vpnclient` instance use graphical management tool, in this case, I use Wine to run Windows program
11. Go to another folder`cd ..`
12. `wget https://www.softether-download.com/files/softether/v4.41-9787-rtm-2023.03.14-tree/Windows/SoftEther_VPN_Client/softether-vpnclient-v4.41-9787-rtm-2023.03.14-windows-x86_x64-intel.exe`
13. `wine softether-vpnclient-v4.41-9787-rtm-2023.03.14-windows-x86_x64-intel.exe`
14. Connect to local vpnclient
15. Create / import vpn connection setting
16. Set as startup connection
17. Try to connect, it doesn't work
18. Plug Eth cable, try to connect again, says connected
19. Unplug Eth cable, connect Wi-Fi
20. Open browser and check internet is available and using Wi-Fi
21. Confirm vpnclient daemon can't connect to vpn server

**Comment by mhtvsSFrpHdE** [comment]
Figure out an upstream network device is blocking traffic to port 443.

**Comment by chipitsine** [comment]
I never considered "wine" as proper use case.
does it work ?

if so, do you mind to provide documentation/recommendation on that ? it looks interesting
