### ISSUE TITLE
RPM Hosting

### ISSUE THREAD

**Issue by mrjefftang** [SoftEtherVPN/SoftEtherVPN#183]
Is there any plan on having prebuilt RPM packages that could be hosted?  PackageCloud.io and BinTray.com offer free binary package hosting for open source projects.

This would make it a lot easier for users to install SoftEtherVPN.

**Comment by scj643** [comment]
Building from source isn't that hard, at least not on Debian based systems.

**Comment by mrjefftang** [comment]
This isn't a matter about building.  It's easy to build, that's not the issue.  It's about deploying.

I don't want to install the entire development toolchain just to compile SoftEther, especially on smaller VMs that lack CPU/RAM.

Additionally, I want to be able to automate the installation of software via Chef.  For instance, I now have a recipe that can go out and fetch a prebuilt RPM hosted on BinTray to install SoftEtherVPN https://bintray.com/mrjefftang/SoftEtherVPN/SoftEtherVPN/v4.19.9582-beta/view#files

**Comment by fenice2** [comment]
Is there any update on whether there will be rpms provided for centos (in my case)? I have built them in the past on a test server but the current master branch fails horribly, not being a developer I'm struggling to get this working again.

I'd also suggest that providing prebuilt installable packages might help in the update of SoftEtherVPN, not everyone has the ability or resources to build these packages and ease of installation is always a bonus. :)

**Comment by chipitsine** [comment]
well, there're couple of very different issues

1) rpm hosting (we plan to do that, however, not ready yet)

2) "but the current master branch fails horribly" - can you provide some details ? it is interesting
