### ISSUE TITLE
How to use softether without secure nat and virtual dhcp ?

### ISSUE THREAD

**Issue by alom4hdi** [SoftEtherVPN/SoftEtherVPN#1842]

**Comment by shakibamoshiri** [comment]
first ,it is better to ask your questions here https://www.vpnusers.com/viewforum.php?f=7

second you can run two SE servers, adding two bridges to each hub, then adding a cascade connection between two servers. lastly with static routing you can connect to server B via server A.  
No secure-nat or dhcp is needed
