### ISSUE TITLE
src/Mayaqua/Encrypt.c:127:25: fatal error: openssl/ssl.h: No such file or directory

### ISSUE THREAD

**Issue by Dewa-ubuntu** [SoftEtherVPN/SoftEtherVPN#185]
any body can help me with this??
src/Mayaqua/Encrypt.c:127:25: fatal error: openssl/ssl.h: No such file or directory

**Comment by findidea** [comment]
ok, i can help you
2015年10月3日 上午12:09于 "Dewa-ubuntu" <notifications@github.com>写道：

**Comment by findidea** [comment]
anything i can do for you?
2015年10月3日 上午12:09于 "Dewa-ubuntu" <notifications@github.com>写道：

**Comment by lillik** [comment]
sudo apt-get install libssl-dev

**Comment by tahasiddiqui123** [comment]
I am a mac os x user and i found that apple depreciates the openssl that why i found the same error when I build using the make command.So for getrid to this error I followed the following link,may be helpful for you

http://adarsh.io/bundler-failing-on-el-capitan/

**Comment by moatazelmasry2** [comment]
@tahasiddiqui123 answer should solve the problem of the OP. Closing
