### ISSUE TITLE
Help... Radius can not be used?

### ISSUE THREAD

**Issue by lanrenwo** [SoftEtherVPN/SoftEtherVPN#186]
I installed the latest version of softether, was faced with a problem.
I'm under vpncmd, when executed RadiusServerSet, tips:

This feature is not supported. It has not been implemented yet on the open-source version of SoftEther VPN.

SoftEther is open source, Radius can not use?

**Comment by hanhealthy** [comment]
Same problem, Any updates?

**Comment by davidebeatrici** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/5cdd2a4e4a6bbef5ecde0dc5a6ef77dcb5de5a4b/src/Cedar/Server.c#L10580-L10631
