### ISSUE TITLE
Authenticating iOS and RADIUS - Only PAP is used

### ISSUE THREAD

**Issue by hesstobi** [SoftEtherVPN/SoftEtherVPN#187]
For Authenticating i use Radius-Authentication. If I enable PAP-Authentication everythink works fine. But i like to diasble PAP, because it's quite unsave. In the Windows L2TP Client a can select the authentication mehtods used, thus the authentication works also fine. But iOS always use the first proposed authentication mehtod. So the VPN-Server accepts PAP and iOS answers in PAP but the Radius server will then deny the authention. There was a simaliar on SonicWall Gateways (https://support.software.dell.com/de-de/kb/sw9013).
To fix this issue it would be greate to have a option to disable PAP completely or to choose the order of proposed  authentication methods.

**Comment by BlackHoleFox** [comment]
Any update on this at all? The native connection protocol though the SoftEther client doesn't work with RADIUS auth because it uses PAP, which is inexcusable in this day and age for password authentication.

**Comment by domosekai** [comment]
If the L2TP client chooses PAP, Radius auth will use PAP as well. This should not be an issue because SoftEther server DE is now proposing to use EAP first.
The native protocol will be able to use EAP / PEAP after #1775 .

**Comment by domosekai** [comment]
Using PAP with Radius should not pose a security risk because Radius implementation is always local, otherwise it's a bad implementation.
