### ISSUE TITLE
Openvpnmakeconfig missing root CA.

### ISSUE THREAD

**Issue by tuapuikia** [SoftEtherVPN/SoftEtherVPN#188]
OpenvpnMakeconfig create ovpn config that do not include root CA. This caused the tls error during the handshake.

It is OK if your servercert is selfsigned.

Might be a good solution by appending the root CA that use to sign the servercert inside ovpn config.

**Comment by moatazelmasry2** [comment]
Certificates are at the moment not supported by OpenVPN Server in SoftEther

**Comment by davidebeatrici** [comment]
Pull request to support OpenVPN certificates: https://github.com/SoftEtherVPN/SoftEtherVPN/pull/327

**Comment by moatazelmasry2** [comment]
PR #327 has just been merged
