### ISSUE TITLE
cascade connection via vpncmd adds wrong  server when is set for IPV6

### ISSUE THREAD

**Issue by shakibamoshiri** [SoftEtherVPN/SoftEtherVPN#1885]
### Prerequisites

* [X] Can you reproduce?
* [X] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** 
Server latest version , built from master

**Operating system:**
Debian 11

**Architecture:**
64

### Description

Adding a cascade connection via `vpncmd` when server is IPV6 address, just the first part up to first colon (`:`) is added

**Expected behavior:**
the whole IPV6 should be added 
If regular expression has been used to match a colon (`:`) as a separator , it should match the last one not the first one  

**Actual behavior:**

Trying different combination of
- double quote `"`
- single quote `'`
- escaping `\`
 
none worked

```
CascadeCreate 1 /server:2a01:xxx:yyy:zzz::1:443 /HUB:VPN /USERNAME:1
CascadeCreate 2 /server:'2a01:xxx:yyy:zzz::1':443 /HUB:VPN /USERNAME:2
CascadeCreate 3 /server:'2a01:xxx:yyy:zzz::1:443' /HUB:VPN /USERNAME:3
CascadeCreate 4 /server:2a01\:xxx:\yyy\:zzz:\:\:1:443 /HUB:VPN /USERNAME:4
CascadeCreate 5 /server:"2a01:xxx:yyy:zzz::1":443 /HUB:VPN /USERNAME:5
CascadeCreate 6 /server:"2a01:xxx:yyy:zzz::1:443" /HUB:VPN /USERNAME:6
```

sample output

```
----------------------+-------------------------
Setting Name          |1
Status                |Offline (Stopped)
Established at        |(None)
Destination VPN Server|2a01
Virtual Hub           |VPN
----------------------+-------------------------
Setting Name          |2
Status                |Offline (Stopped)
Established at        |(None)
Destination VPN Server|2a01
Virtual Hub           |VPN
----------------------+-------------------------
Setting Name          |3
Status                |Offline (Stopped)
Established at        |(None)
Destination VPN Server|'2a01
Virtual Hub           |VPN
----------------------+-------------------------
Setting Name          |4
Status                |Offline (Stopped)
Established at        |(None)
Destination VPN Server|2a01\
Virtual Hub           |VPN
----------------------+-------------------------
Setting Name          |5
Status                |Offline (Stopped)
Established at        |(None)
Destination VPN Server|'2a01
Virtual Hub           |VPN
----------------------+-------------------------
Setting Name          |6
Status                |Offline (Stopped)
Established at        |(None)
Destination VPN Server|2a01
Virtual Hub           |VPN
The command completed successfully.
```

### Steps to reproduce
Add a cascade connection via `vpncmd` while server is IPV6

**Comment by chipitsine** [comment]
wow

**Comment by metalefty** [comment]
Just curious, what about `/server:[2a01:xxx:yyy:zzz::1]:443`?

**Comment by davidebeatrici** [comment]
That would be great, it's a common format.

**Comment by shakibamoshiri** [comment]
nope , both brackets are added as well

tring
```bash
CascadeCreate ipv6 /server:"[2a01:4f8:c010:8cb8::1]:443" /HUB:NFS /USERNAME:ipv6
# and
CascadeCreate ipv6 /server:[2a01:4f8:c010:8cb8::1]:443 /HUB:NFS /USERNAME:ipv6
```

result
```bash
----------------------+-----------------------
Setting Name          |ipv6
Status                |Offline (Stopped)
Established at        |(None)
Destination VPN Server|[2a01:4f8:c010:8cb8::1]
Virtual Hub           |NFS
The command completed successfully.
```

I am wondering this feature never tested ?

**Comment by dnobori** [comment]
You have to set the cascade connection online. 

**[6.4.48 "CascadeOnline": Switch Cascade Connection to Online Status](https://www.softether.org/4-docs/1-manual/6._Command_Line_Management_Utility_Manual/6.4_VPN_Server_%2F%2F_VPN_Bridge_Management_Command_Reference_(For_Virtual_Hub)#6.4.48_.22CascadeOnline.22:_Switch_Cascade_Connection_to_Online_Status)**

**Comment by shakibamoshiri** [comment]
> You have to set the cascade connection online.
> 
> **[6.4.48 "CascadeOnline": Switch Cascade Connection to Online Status](https://www.softether.org/4-docs/1-manual/6._Command_Line_Management_Utility_Manual/6.4_VPN_Server_%2F%2F_VPN_Bridge_Management_Command_Reference_(For_Virtual_Hub)#6.4.48_.22CascadeOnline.22:_Switch_Cascade_Connection_to_Online_Status)**


The issue is not about making a CC online, it is about IPv6 is not added correctly by `vpncmd`  
The `CascadeOnline` command works fine, `CascadeCreate` has the issue for its `/server` argument

**Comment by shakibamoshiri** [comment]
> > You have to set the cascade connection online.
> > **[6.4.48 "CascadeOnline": Switch Cascade Connection to Online Status](https://www.softether.org/4-docs/1-manual/6._Command_Line_Management_Utility_Manual/6.4_VPN_Server_%2F%2F_VPN_Bridge_Management_Command_Reference_(For_Virtual_Hub)#6.4.48_.22CascadeOnline.22:_Switch_Cascade_Connection_to_Online_Status)**
> 
> The issue is not about making a CC online, it is about IPv6 is not added correctly by `vpncmd` The `CascadeOnline` command works fine, `CascadeCreate` has the issue for its `/server` argument

It seems the format for IPv6 could be used inside brackets `[IPV6]`, so bellow are correnct

```bash
CascadeCreate ipv6 /server:"[2a01:4f8:c010:8cb8::1]:443" /HUB:NFS /USERNAME:ipv6
# and
CascadeCreate ipv6 /server:[2a01:4f8:c010:8cb8::1]:443 /HUB:NFS /USERNAME:ipv6
```

Tested and worked.
