### ISSUE TITLE
I think there is an issue with latest updates and Ubuntu 22.04.02 LTS and maybe even OpenSSL?

### ISSUE THREAD

**Issue by DijkstraSolutions** [SoftEtherVPN/SoftEtherVPN#1890]
Hi, there!

Thank you for using SoftEther.

If you are running SoftEther VPN 4.x (i.e. Stable Edition), please read the comparison with Developer Edition at: 

https://github.com/SoftEtherVPN/SoftEtherVPN#comparison-with-stable-edition

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [ ] Can you reproduce? Y
* [ ] Are you running the latest version of SoftEtherVPN? Y (4.42)

**SoftEther version:** 4.42 on Server and Client
**Component:** Client, probably
**Operating system:** Linux/Ubuntu/22.04
**Architecture:** 64 bit

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** Virtual Machine, VMware, AMD Epyc Embedded on client side, AMD Epyc 64 Core on Server side

### Description

I was chasing this down as a bug with the Linux client that I first thought it was a routing problem.  Confirmed that is certainly not the case.  The Windows version works fine in Windows 10 and 11. I have this Linux client implemented in many locations, but just so happens I am discovering that this fails with Ubuntu 22.04. Ubuntu 20.04 and 18.04 does not have this problem where the client is deployed (no one out there with these versions has 4.42 yet, but they vary with 4.29 and 4.38, no issues.  Ubuntu 22.04 with 4.38 does not work either).

Here is what I have disovered using OpenSSL. If I use openssl s_client -connect fqdn:443 function on a working solution, Error = 0, if I use it on the non working solution, I get this:

read R BLOCK
40A726C2C77F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:308:

This used to work, a recent update has cause this problem and I think the update is an issue on the server and client side or maybe just the server, not sure.

**Expected behavior:**
OpenSSL should report (from server)

read R BLOCK
read:errno=0

**Actual behavior:**
OpenSSL reports (from server)

read R BLOCK
40A726C2C77F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:308:

And client never connects

### Steps to reproduce

1. Deploy 22.04 Ubuntu with latest updates
2. Install latest SE client
3. Try to connect to a server

**Comment by chipitsine** [comment]
Ubuntu 22 is shipped with hardened OpenSSL, it is managed by "seclevel"

https://askubuntu.com/questions/1423215/ubuntu-22-04-how-to-set-lower-ssl-security-level

I'd say that in your case client and server have no common algorithms (indeed it can be reported better).

can you try to play with seclevel ? and probably collect tcpdump ? I hope it should have ssl handshakes and we can compare what server suggests and client requests.

**Comment by DijkstraSolutions** [comment]
Oh this is one major issue I have with both the server and client logs, btw. I wish there was a way to including more logging details, I almost didn't even catch the problem with OpenSSL as it reports the cert information just fine, its that error at the end, if you don't wait for it you wouldn't even notice it.

I think this is a server side issue and I may have a way to show that.

**Comment by chipitsine** [comment]
well, openssl itself is known to report errors in very own way ))

as you provided `openssl s_client -connect fqdn:443` output, it is almost useless. ok, you know "it does not work", error does not provide any meaningful info.

I think, currently SE VPN follows that behaviour as well ))

ok, we can log error messages better. but at least we log it in the same way as openssl.

**Comment by DijkstraSolutions** [comment]
No, the logs from the client show none of that, it only states this on client and server logs:

Server Log:
2023-08-17 18:32:39.033 On the TCP Listener (Port 443), a Client (IP address ##PUBLICIP##, Host name "##PUBLICFQDN##", Port number 43667) has connected.
2023-08-17 18:32:39.033 For the client (IP address: ##PUBLICIP##, host name: "##PUBLICFQDN##", port number: 43667), connection "CID-432290" has been created.
2023-08-17 18:32:39.053 Connection "CID-432290" has been terminated.
2023-08-17 18:32:39.053 The connection with the client (IP address ##PUBLICFQDN##, Port number 43667) has been disconnected.

Client Log:
2023-08-17 18:32:07.298 VPN Connection Setting "##CONNECTIONNAME##": The connection has been either disconnected or it failed. Cause: Connection to the server failed. Check network connection and make sure that address and port number of destination server are correct. (code 1)
2023-08-17 18:32:22.300 VPN Connection Setting "##CONNECTIONNAME##": Connection operation starting (this is now 35 times).

I used OpenSSL to make sure a transparent proxy wasn't in the middle.

**Comment by DijkstraSolutions** [comment]
Switched back to my older 4.41 Windows based server, same client, still failed so it was not the issue.

**Comment by DijkstraSolutions** [comment]
Am I troubleshooting this right? If the client is using its own library for openssl, then the OS version shouldn't matter?

**Comment by chipitsine** [comment]
When I refer to adjusting openssl.conf, I mean lowering SECLEVEL to 0.

It is correct statement when you use own library, OS version should not matter.

**Comment by DijkstraSolutions** [comment]
I have adjusted the client to 0 but no change, I am applying this change to the server as well but I cannot restart those services until later.

What I mean by modifying the openssl.cnf, that will affect behavior in SoftEther?

**Comment by chipitsine** [comment]
It is hard to catch what you are doing exactly. If you are using "own" openssl libraries, then them usually do not use system wide openssl.conf. Sorry, I'm lost here

**Comment by DijkstraSolutions** [comment]
I am talking about SE vs the OS. I know I used openssl tool to find out what I did and that is the OS.  SoftEther is using OpenSSL 3.0.9, correct? In theory it should be as simple then to downgrade the client to get a connection, but that doesn't work. I have tried 4.29 and 4.38 on U22.04.

If there is an issue is it my server cert? Why does U20/18.04 work then?  I am just very confused on how to fix this other than downgrading the OS (which I can't in this case). Why would the OS even matter in this case.  Maybe my assumption of the problem is wrong but without logging details this is all I have discovered.

**Comment by chipitsine** [comment]
Sorry, what is "SE vs the OS" ?

as for logging details, you can try debug logging.
also, you can try to collect tcpdump capture between server and  client. especially interesting should be connection establishing.

**Comment by chipitsine** [comment]
as for your cert, I do not think it is an issue. I would suspect certificate at the last

**Comment by DijkstraSolutions** [comment]
SE or SoftEther and the OS in this case is Ubuntu

Sorry, I cannot seem to figure out the debugging settings for logging. I see packet captures but that happens at the VPN Members, connection never gets there.

**Comment by chipitsine** [comment]
I understand that SE stands for SoftEther and OS stands for Ubuntu. But I do not understand what is "SE vs the OS"

**Comment by DijkstraSolutions** [comment]
I assume SE is using its own openssl libraries where the OS is using whatever version of openssl is installed.

So using openssl from Ubuntu command line would be the openssl-OS, I have no details on what openssl-SE is doing other than connecting/dropping, etc.

**Comment by chipitsine** [comment]
SE may be linked against either system or its own openssl library.
you can use `ldd` to check that.

**Comment by DijkstraSolutions** [comment]
Working system:
ldd ./vpnclient
        linux-vdso.so.1 (0x00007ffd70df3000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff94cab7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff94c898000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff94c4a7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff94ccbf000)

Not working:

ldd ./vpnclient
        linux-vdso.so.1 (0x00007fff12390000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f96146ee000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9614f47000)

**Comment by chipitsine** [comment]
seems you are using Stable edition of SE VPN, because of 4.X versioning.

I'm not familiar how it is linking against OpenSSL (most probably statically, but I do not know).
such in depth support of Stable edition is handled on vpnusers.com (you should notice that when opening an issue).

this tracker is for SE Developer edition, i.e. 5.X versions.

as for dynamic linking, for example

```
[ilia@fedora build]$ ldd vpnclient
	linux-vdso.so.1 (0x00007ffc01f3f000)
	libcedar.so => /home/ilia/SoftEtherVPN/build/libcedar.so (0x00007fc143788000)
	libmayaqua.so => /home/ilia/SoftEtherVPN/build/libmayaqua.so (0x00007fc1436cd000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007fc14365f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc143481000)
	libncurses.so.6 => /lib64/libncurses.so.6 (0x00007fc143454000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007fc14341f000)
	libform.so.6 => /lib64/libform.so.6 (0x00007fc14340c000)
	libreadline.so.8 => /lib64/libreadline.so.8 (0x00007fc1433b2000)
	libssl.so.3 => /lib64/libssl.so.3 (0x00007fc14330f000)
	libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007fc142e00000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fc1432f5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc142d1f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc14395d000)
[ilia@fedora build]$ 
```

**Comment by DijkstraSolutions** [comment]
[1890-1-cap.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/12383864/1890-1-cap.txt)
Packet capture

**Comment by DijkstraSolutions** [comment]
Sorry, I misunderstood what this meant:

"Before you submit an issue, please read the following:

Is this a question?"

I don't specifically have a question about how to use the app but rather I think I found a problem.  I guess it should state that any questions, problems or issues with 4.x should be only on vpnusers.com and not here.  I apologize for the misunderstanding.

Given where I am at here, I suspect that the 5.x client should work with a 4.x server?

**Comment by chipitsine** [comment]
yes, generally 5.X and 4.X are interoperable. Unless you met some bug or misconfiguration.

from your observation it looks like there are some incompatibilities between different builds of stable release.
generally, something like that rarely happens between 4.x and 5.x

**Comment by DijkstraSolutions** [comment]
Well, that fixed my problem, installing 5.x using the following instructions:

apt -y install build-essential cmake gcc g++ make 
apt -y install git
apt -y install pkg-config
apt -y install libncurses-dev libssl-dev libsodium-dev zlib1g-dev
apt -y install libreadline-dev
cd ./SoftEtherVPN
./configure
make -C build

I had to re-create my vpn_client.config and reboot was required. And, yes, there is _**slightly**_ more logging detail:

2023-08-18 17:51:28.093 The configuration file has been loaded.
2023-08-18 17:51:28.093 Connection processing for VPN Connection Setting "..." has started.
2023-08-18 17:51:28.114 VPN Connection Setting "...": Connection operation starting (this is now 1 times).
2023-08-18 17:51:28.306 VPN Connection Setting "...": SSL communication has been started. The protocol version is TLSv1.3. The encryption algorithm name is "TLS_AES_256_GCM_SHA384".
2023-08-18 17:51:28.758 VPN Connection Setting "...": SSL communication has been started. The protocol version is TLSv1.3. The encryption algorithm name is "TLS_AES_256_GCM_SHA384".
2023-08-18 17:51:28.849 VPN Connection Setting "...": Now connected. Session name: "SID-####-1742"

**Comment by chipitsine** [comment]
more logging details may be related to successful connection, while on failed connection you might get less details as well.

**Comment by chipitsine** [comment]
I think, for SSL is a common way to say "cannot establish connection" for example if algorithms differ between client and server. And client cannot know the exact reason why is cannot connect. It just tries to connect and it cannot. I never seen errors like "server wants me to use hardened ciphers which I do not support".

Still you can try to get details by capturing tcpdump. Not text log you attached, but full pcap.

**Comment by DijkstraSolutions** [comment]
Thank you for your help, I will close this as this issue is with Version 4.x
