### ISSUE TITLE
请求建议：希望整合obfs流量混淆

### ISSUE THREAD

**Issue by python12450** [SoftEtherVPN/SoftEtherVPN#191]
中国大陆的长城防火墙已经具有流量识别能力，可以根据流量特征阻断大部分的vpn，obfs可以混淆这种识别

**Comment by kennylam777** [comment]
Please speak in English / Japanese as the author of SoftEther is a japanese, especially you are on a worldwide platform.
(Chinese: 因作者是日文人, 請使用英語/日語發言)

Translation of 中国大陆的长城防火墙已经具有流量识别能力，可以根据流量特征阻断大部分的vpn，obfs可以混淆这种识别

As China GFW has capability of detecting traffic signatures, and it is able to block VPN from those signatures, I wish obfuscations (obfs) could be integrated to SoftEther.

What kind of obfuscations did you mentioned? obfsproxy?

From my perspective, SoftEther has already used HTTPS as a obfuscations implementation to pass-thru firewall. However China GFW is able to detect SoftEther indeed as I tested on China Telecom/China Unicom in GuangDong area and the server's IP will be baneed on CT/CU backhaul for a while. I am wondering if there was some kind of SSL signature was detected.

As I tested so far, such issue can be resolved by using a SSL certification purchased from non-free providers (StartSSL and Self-signed doesn't work) on SoftEther server.

**Comment by mindcat** [comment]
@kennylam777 obfs are not obfuscations, I suppose he mean https://github.com/Yawning/obfs4
he said: GFW could detecting VPN traffic pattern, and will block the VPN. obfs will obfuscate the VPN traffic pattern, to hidden the VPN.

> I am wondering if there was some kind of SSL signature was detected.
http://blog.zorinaq.com/?e=81

**Comment by python12450** [comment]
@kennylam777 you can look the code of  shadowvpn....https://github.com/langlichuan123/ShadowVPN
Now the shadowsocks and shadowvpn is still work in CHINA....

**Comment by kennylam777** [comment]
Why don't you guys just use Shadowsocks to carry SoftEther VPN Connection, but requiring to integrate it into SoftEther VPN instead?

**Comment by python12450** [comment]
@kennylam777  shadowsocks use tcp...and it's unfriendly to udp

**Comment by kennylam777** [comment]
@python12450 so it is still irrelevant to SoftEther VPN right? The native SoftEther VPN client uses TCP-SSL connection, although it supports UDP acceleration already, but it seems a signature to be blocked by China's firewall as I tested.

If you can read source codes, you may try to port the transport layer stuffs to SoftEther VPN, just like other protocols like OpenVPN.

btw, I am not the writter of SoftEther VPN, just an old user can read Chinese.

**Comment by aicochow** [comment]
我今天试了一下这个软件，用客服端可以翻墙，但是手机不能

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by adminport** [comment]
BTW no chinese respect this is english forum

**Comment by moatazelmasry2** [comment]
Guys. Please do not write in chinese. This website is in english and we have no way of following this conversation. Closing issue..

**Comment by microcai** [comment]
The Japanese author is forced to write English and block every other languages. bad. Japanese nearly was the world wide language before September 22, 1985.
anyway, Chinese is the languages for all east Asia for almost two thousand years. ;) . so, Japanese and Chinese, don't fight, English is your common enemy.
