### ISSUE TITLE
[BUILD BUG ?]  binaries in "Windows_x64" are same as binaries in "Windows_x86" as artifacts. 

### ISSUE THREAD

**Issue by hiura2023** [SoftEtherVPN/SoftEtherVPN#1913]
Hi, there!

### Prerequisites

* [ ] Can you reproduce?
Yes.
* [ ] Are you running the latest version of SoftEtherVPN?
Yes.

**SoftEther version:**
SoftEther VPN Developer Edition (Ver 5.02, Build 0)

**Component:** [Server, Client, Bridge, etc.]
#20230917.1 • Merge pull request #1905 from chipitsine/master
On Nightly
Windows_x64
Windows_x86

Operating system: [Windows, Linux, BSD, macOS, etc.]
Win 10 PRO 22H2 BUILD 19045.3448 (VPN Client)

Architecture: [64 bit, 32 bit]
64 bit

### Description

[Description of the bug]
Bug on build ?

**Expected behavior:**
[What you expected to happen]
Generally speaking, executable file in "Windows_x64" is different from it in "Windows_x86".

**Actual behavior:**
[What actually happened]
All the executable files in "Windows_x64" are same as in "Windows_x86" .

### Steps to reproduce

1. [First step]
Download "Windows_x64" binaries.

2. [Second step]
Download "Windows_x86" binaries.

3. [And so on...]
Compare two binaries using "WinMerge".

**Comment by chipitsine** [comment]
interesting, files are the same.

**Comment by chipitsine** [comment]
It is likely a bug. I planned to have a look this weekend

**Comment by hiura2023** [comment]
### I would like to suggest to publish three artifacts below.
- Binaries_x64
- Binaries_x86
- Installers
### Changing the "windows-steps.yml" below.
- Refer to No.1, No.2 and No.3 in attached file. I am not sure if the syntax is correct.
[windows-steps.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/13052137/windows-steps.txt)

**Comment by chipitsine** [comment]
you can create your own pipeline in https://dev.azure.com and test changes.

**Comment by chipitsine** [comment]
fixed in https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1924
