### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jirutka** [SoftEtherVPN/SoftEtherVPN#1916]
The latest release [5.02.5180](https://github.com/SoftEtherVPN/SoftEtherVPN/releases/tag/5.02.5180) is 2 years old. Can you please release/tag a new version? The current situation is unfortunate because Linux distributions are forced to pick an arbitrary commit and make up some version number which leads to high fragmentation and confusion for users.

**Comment by BKPepe** [comment]
@davidebeatrici or @domosekai, can you please take a look at it? This would be also helpul for OpenWrt distribution.

**Comment by PizzaProgram** [comment]
Also it would be nice to create a nice step-by-step instruction for "How to download DEV nightly build releases".
`download_nightly.md`
And put a big link to the main readme.md to it.
_(It took me several hours to find the invisible! three dots `...` for download the compiled binary files.)_

https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_build

Also I agree the the version numbering is low and not user friendly at all!
1. It should be at least `5.1` by now
2. the sub version number should be an iso-date. Like: `5.1.20240131`

I also realized: 
 - The **PR build** of the Azure binaries are always: `5.02.0`  .

**Comment by tew42** [comment]
@PizzaProgram  The azure build interface has changed a bit since #1533, so indeed it's a bit harder to locate the binaries now, shouldn't be too difficult to draw up a PR for that. As for version numbering, from my understanding there are legacy reasons for keeping the format.

**Comment by chipitsine** [comment]
released


also, windows installers now bundled to github releases

https://github.com/SoftEtherVPN/SoftEtherVPN/releases/tag/5.02.5183
