### ISSUE TITLE
Bypass some network traffic based on CIDR (Classless Inter-Domain Routing) in softether client

### ISSUE THREAD

**Issue by aa51513** [SoftEtherVPN/SoftEtherVPN#1923]
For some reasons, 

I hope that when I connected to the softether bridge on my windows PC , part of the network traffic will not go through the softether client. 

Is there a way to achieve this?

**Comment by officialh1** [comment]
DHCP classless routes to form split tunneling.

**Comment by aa51513** [comment]
> DHCP classless routes to form split tunneling.

thank you very much,it workes
