### ISSUE TITLE
[SSTP] [Win10 client] Error: Failed to find an available cipher that is supported by both sides, or the cipher specified is not compatible with the server certificate. (code 151)

### ISSUE THREAD

**Issue by akuropka** [SoftEtherVPN/SoftEtherVPN#1926]
### Prerequisites

* [X] Can you reproduce?
* [X] Are you running the latest version of SoftEtherVPN?

### Server

**SoftEther version:** SoftEther VPN Server Developer Edition Version 5.02 Build 5180 (English)
**Operating system:** Arch Linux Arm
**Architecture:** 64 bit

### Client

**Operating system:** Windows 10 [Version 10.0.19045.3636]
**Architecture:** 64 bit
**Processor:** Intel Core i7-3520M

### Description

I am trying to connect to the server with the built-in SSTP client of Windows 10.

**Expected behavior:**
Client connects to network.

**Actual behavior:**
Error message thrown.

### Errors

**Client:**
The message received was unexpected or badly formatted.

**Server:**
Failed to start SSL communication for connection "CID-3". Error: Failed to find an available cipher that is supported by both sides, or the cipher specified is not compatible with the server certificate. (code 151)

### Steps to reproduce

1. Set up VPN client connection in Setting > Network & Internet > VPN
2. Enter username and password
3. Manually edit adapter, select type to SSTP and set to maximum encryption, allow only MS-CHAPv2
4. Try to connect

### Additional information

- The same client setup as above works e.g. on Windows 11 and Windows Server 2022.
- TLS v1.2 and v1.3 are enabled through internet settings (inetcpl.cpl) and Registry (HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols).
- Tls_Disable1_0, Tls_Disable1_1, Tls_Disable1_2, Tls_Disable1_3 are all set to false in server config.
- Server certificate is issued by R3, Let's Encrypt and valid.

**Comment by domosekai** [comment]
The error message already told you what has gone wrong. Run Wireshark to find out what were offered in the client hello.
My understanding is that Win 11 and 2022 RAS supports TLS 1.3 but Win 10 does not (no matter how you change in the registry). So on Win 10 TLS 1.2 is used and the cipher setting on the server must be correct. You have probably misconfigured the cipher.  Since it's not used in TLS 1.3 so no error was thrown there.

**Comment by akuropka** [comment]
Thank you for the hint... this was fully not in my mind. 😱

Adjusting
```
-		string CipherName DHE-RSA-AES256-SHA
+		string CipherName TLS_AES_256_GCM_SHA384
```
fixed this. 👍

(Win 10 RAS seems indeed not to use TLS 1.3)
