### ISSUE TITLE
Listen interface or ip adress settings ??

### ISSUE THREAD

**Issue by fhocorp** [SoftEtherVPN/SoftEtherVPN#193]
Hello

I am very worried that not any parameter for getting Softether VPN server working on a specific interface or ip adress.

I have a server with multiple ip adress and i want to my softether VPN Server listening on a specific IP or interface.

When it will be implemented ?

Best Regards

**Comment by macvk** [comment]
this is already done. You can listen on any interface you want. Use tap bridge to do this. Config example here: http://blog.lincoln.hk/blog/2013/05/17/softether-on-vps-using-local-bridge/

**Comment by fhocorp** [comment]
False ! The tap bridges are working but the VPN server is listening on 0.0.0.0 so the problem is not solved :(

**Comment by macvk** [comment]
I have several vpn servers and all is ok. don't know what you trying to do. Anyway source code is available you can do what you want. good bye.

**Comment by fhocorp** [comment]
I have a dedicated server with two failovers IP attached. I want to softether to listen only on one failover IP and not the others !

Best Regards

**Comment by macvk** [comment]
You can clone SofrEther from my repository https://github.com/macvk/SoftEtherVPN.git
I have added new parameter "ListenIP" to file vpn_server.config, section ServerConfiguration.
If this path is ok, I will add this to main SoftEther project. You can test it.

**Comment by fhocorp** [comment]
Nice work but on my server, the "string ListenIP" modified with my IP is overwritten by "string ListenIP 0.0.0.0"at every reboot of the server or config update so the problem is not solved :(
Best Regards

Date: Mon, 9 Nov 2015 09:39:21 -0800

**Comment by macvk** [comment]
You must 
1. Stop server
2. Edit config
3. Start server

**Comment by fhocorp** [comment]
Thanks ! It works like a charm now ! :) :+1: :smiley:
Let's have a cup of :beers: :smile:

**Comment by jok40** [comment]
Hello, macvk!

10 Nov 2015 you wrote:
> If this path is ok, I will add this to main SoftEther project.

Let me ask: When do you plan to add the patch to the main SoftEther project?

**Comment by amegz** [comment]
Hello ppl. Is this feature implemented to mainline ?

**Comment by macvk** [comment]
this feature is already added in the pull requests.

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by moatazelmasry2** [comment]
@macvk is this still an open PR? What is the link?

**Comment by qbeukes** [comment]
@moatazelmasry2 https://github.com/SoftEtherVPN/SoftEtherVPN/pull/202

**Comment by nikrox2** [comment]
Has this been implemented into the binaries?

**Comment by macvk** [comment]
this is implemented in the main source tree. so you can build it yourself.

**Comment by moatazelmasry2** [comment]
@nikrox2 As mentioned, this has been merged on the master branch. No binaries available yet. I'll try to create a a release within the next days, after I clear something with Daiyuu

**Comment by DRSDavidSoft** [comment]
@moatazelmasry2 Any news yet?

**Comment by fhocorp** [comment]
no :(

**Comment by theg00s3** [comment]
you'll still have to just use the github master branch
