### ISSUE TITLE
OpenVPN scrambled support ?

### ISSUE THREAD

**Issue by fhocorp** [SoftEtherVPN/SoftEtherVPN#194]
Hi 

There is a way to add the scrambling cipher fonction (XOR patch) to the integrated openvpn in softether ?

Best Regards

**Comment by fhocorp** [comment]
Waiting... :neutral_face:

This is for me a security issue :exclamation: :unlock:

**Comment by bjdag1234** [comment]
for reference here is a patch of the source code of openvpn
https://github.com/clayface/openvpn_xorpatch/blob/master/openvpn_xor.patch

I hope it can be integrated in the OpenVPN module of SE-VPN.

**Comment by serveur-web** [comment]
Please Add XOR Patch on OpenVPN function in SE.
https://github.com/clayface/openvpn_xorpatch/blob/master/openvpn_xor.patch

**Comment by fhocorp** [comment]
Still waiting... @dnobori can you update this to the dev team SVP ?

**Comment by fhocorp** [comment]
@dnobori can you help us about that please?
Can you add xor patch in openVPN SVP ?
Source port can be available ?
Best Regards

**Comment by hijack329** [comment]
Hello, Mr. Daiyuu Nobori.

When will we know for sure?

We are waiting.

Best WISHES for YOU.

**Comment by davidebeatrici** [comment]
#808 adds the desired feature.

@hijack329 Could you test and review it, please?

**Comment by davidebeatrici** [comment]
#808 has been merged.
