### ISSUE TITLE
Where can see Debug information?

### ISSUE THREAD

**Issue by lanrenwo** [SoftEtherVPN/SoftEtherVPN#196]
I want open debug mode, but not found, please help me, Thank you!

**Comment by moatazelmasry2** [comment]
I'm using ecliopse

run:

`sh
make clean
make DENUG=YES
`

And you should be able to set break points in eclipse

**Comment by moatazelmasry2** [comment]
Please see this article
http://moatazthenervous.com/how-to-debug-softethervpn/

**Comment by lanrenwo** [comment]
@moatazelmasry2 Thank you very much！
