### ISSUE TITLE
How does certificate based sign-in work in SoftEther VPN?

### ISSUE THREAD

**Issue by top-master** [SoftEtherVPN/SoftEtherVPN#1961]
What are the steps involved in signed certificate based sign-in for SoftEther VPN?

Note that I will send an answer to this shortly, and feel free to edit that if anything is missing, or notify me to edit it.

**Comment by suddhasilsarkar** [comment]
Curious if there is any further enhancement on this, I have requirement of connect more than 30K users with cert based authentication mechanism.  And this also per HUB. Any suggestion would be a great help.
