### ISSUE TITLE
Windows nightly builds is not getting update since April 7

### ISSUE THREAD

**Issue by LinearAlpha** [SoftEtherVPN/SoftEtherVPN#1993]
### Are you using SoftEther VPN 5.x?

- [X] Yes, I'm using SoftEther VPN 5.x, not 4.x.

### Version

5.02.5184

### Component

Other

### Operating system & version

Windows

### Architecture or Hardware model

AMD64

### Steps to reproduce

Since April 7, the nightly build has not been update.

Is there a reason the nightly build is not getting update?

**Comment by chipitsine** [comment]
that's not a bug, it was desired behaviour ))

builds now on GitHub (and that's easier for every developer, once enabled GitHub Actions and voila)


I'll update docs.

releases: https://github.com/SoftEtherVPN/SoftEtherVPN/releases
push/pull requests: https://github.com/SoftEtherVPN/SoftEtherVPN/actions/workflows/windows.yml

**Comment by LinearAlpha** [comment]
I see, thank you for the update!
