### ISSUE TITLE
OpenVPN default UDP port 1194 not working

### ISSUE THREAD

**Issue by lijinlongpq** [SoftEtherVPN/SoftEtherVPN#1996]
### Are you using SoftEther VPN 5.x?

- [X] Yes, I'm using SoftEther VPN 5.x, not 4.x.

### Version

5.02.5184

### Component

VPN Server

### Operating system & version

AlmaLinux 8.9

### Architecture or Hardware model

amd64

### Steps to reproduce

I recently upgraded my SoftEther VPN server to version 5.02.5184. Cos I am using VM and no backup, couldn't remember the exact version of old SoftEther VPN server. Should be 5.01.9674. 
The problem is after upgrade, the VPN server no longer listen on UDP port 1194. I cannot connect to my VPN server using OpenVPN connect client. 
From server manager I can see the configuration for OpenVPN UDP ports is blank. I tried to set the port but didn't work. 
I found that in old version, the configuration for openvpn is under ServerConfiguration and has this item: string OpenVPN_UdpPortList 1194
And in new version, the configuration items for OpenVPN changed to ServerConfiguration  -> Proto -> OpenVPN. I tried to manually add string OpenVPN_UdpPortList 1194 also not working. 

### ✔️ Expected Behavior

The SoftEther VPN server should listen on OpenVPN UDP port 1194 if enabled OpenVPN server function.

### ❌ Actual Behavior

UDP port 1194 not listening and UDP ports configuration is empty.

**Comment by davidebeatrici** [comment]
The setting is now called `PortsUDP` as it also applies to other protocols (i.e. WireGuard), see #1130.

**Comment by lijinlongpq** [comment]
Hi ,

Thanks a lot, Issue resolved, 
It seems that after upgrade, the PortsUDP with value $. It's not picking up the original configuration 1194. I manually updated the configuration file from  string PortsUDP $  ->  string PortsUDP 1194
