### ISSUE TITLE
Where are the specs of SoftEtherVPN management API?

### ISSUE THREAD

**Issue by GildedHonour** [SoftEtherVPN/SoftEtherVPN#200]
where can I find the specs of SoftEtherVPN management API? So I can build a client in, say, in Python or any other language and control my SoftEtherVPN server. 

For example, in openvpn I can communicate with openvpn server via API by openvpn management protocol.

**Comment by brokenglish** [comment]
https://www.softether.org/Template:MindTouch/OOBE/Core/User_Development#API

**Comment by GildedHonour** [comment]
Nobody knows?

**Comment by macvk** [comment]
you can use vpncmd for management purposes. see source code of vpncmd for example API calls.

**Comment by GildedHonour** [comment]
@macvk 
Ok, but where is the documentation, not just code?

**Comment by GildedHonour** [comment]
the code of https://github.com/SoftEtherVPN/SoftEtherVPN/blob/3c8abd60ed71d09dc09953712c8d5a807932efb9/src/vpncmd/vpncmd.c is as simple as it's not possible to understand how it controls SoftEtherVPN  on a low level.

**Comment by macvk** [comment]
Try google first 
https://www.softether.org/4-docs/1-manual/6._Command_Line_Management_Utility_Manual/6.5_VPN_Client_Management_Command_Reference 
I don't know what you trying to do.

**Comment by GildedHonour** [comment]
@macvk , thanks I'll check it out.
Of course you don't know because.... I haven't told you.

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by moatazelmasry2** [comment]
@GildedHonour I'm also unaware of such documentation. There is however another great resource. An implementation of vpncmd in Python:
https://github.com/mindcollapse/SoftEtherPy

Can this ticket be closed?

**Comment by GildedHonour** [comment]
@moatazelmasry2 yes
