### ISSUE TITLE
Feature Request: Option to disable automatic reconnect on RADIUS authentication

### ISSUE THREAD

**Issue by ghost** [SoftEtherVPN/SoftEtherVPN#203]
We are using RADIUS to provide two factor authentication (2fa) with active directory and the automatic reconnect feature is causing a lot of grief as it has the potential to lock accounts in its default config of unlimited reconnects and attempting it every 15 seconds.

Ideally there should be an option to specify if 2FA is being used and to disable the automatic reconnect similar to what the client does for smart card use. 

Currently we are working around it by disabling the automatic reconnect by setting the number of tries to zero and then specifying a high timeout, e.g. 300 seconds, but like I said it would be more ideal to be able to disable it completely. Thx

**Comment by moatazelmasry2** [comment]
Related to Issue #80

**Comment by andi-blafasl** [comment]
Any Update on this topic in the last few years ??? :wink:
