### ISSUE TITLE
Build from source on Windows completely broken?

### ISSUE THREAD

**Issue by siddharth-narayan** [SoftEtherVPN/SoftEtherVPN#2031]
### Are you using SoftEther VPN 5.x?

- [X] Yes, I'm using SoftEther VPN 5.x, not 4.x.

### Version

Latest commit

### Component

VPN Client

### Operating system & version

Windows 11 Home VM

### Architecture or Hardware model

x86_64

### Steps to reproduce

I built from source and ran vpnclient using the steps in BUILD_WINDOWS.md. Running vpnclient.exe gives this error: 
"The service related operation commands can only operate on Windows NT / 2000 / XP / Server 2003 / Vista / Server 2008. They do not operate on Windows 98 / Me."

This issue comes from line 4262 in src/Mayaqua/Microsoft.c, where ```ms->IsNt``` is false instead of what it should be (true)

I checked the stable version, and in there ```ms->IsNt``` is correctly set to true in ```MsInit``` in the same file.

Removing the if condition, vpnclient.exe continues as normal but fails to run NicCreate. (This part might be my fault and not a bug)

### ✔️ Expected Behavior

vpnclient.exe should not complain about not running on a supported Windows when running a supported Windows

### ❌ Actual Behavior

vpnclient complained

### Anything else?

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/4e8f7970361ce4eab26643f2fdbbffad451d1c6a/src/Mayaqua/Microsoft.c#L4262

https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/blob/556bc0afe2333b7f2ea8f6f91fce90e53605b992/src/Mayaqua/Microsoft.c#L15035

**Comment by siddharth-narayan** [comment]
If this can be fixed by replacing ```ms->IsNt``` with ```IsNt()```, I can make a quick PR. I think ```struct MS``` can have ```IsNt``` removed as well.

**Comment by chipitsine** [comment]
I've just built from source. no problem

how do you build ? using Visual Studio ? did you choose "x64" ?

<img width="611" alt="image" src="https://github.com/user-attachments/assets/3aea6e5e-1d8b-43fb-ba87-03325c03b154">

**Comment by siddharth-narayan** [comment]
It builds just fine, it's just that when vpnclient.exe is run it gives that error message. I didn't realize on windows that vpncmgr.exe is what most people run, so I ran vpnclient.exe directly and found the issue. The issue is that ```ms->IsNt``` is never set to true, which it was in the stable edition where I checked.

**Comment by chipitsine** [comment]
@siddharth-narayan , can you please provide the following ?

1. output of sysinternals sigcheck

for me it looks like ...

<img width="814" alt="image" src="https://github.com/user-attachments/assets/c50c9729-249a-43f4-8041-87d006023206">

2. output of "systeminfo"

**Comment by siddharth-narayan** [comment]
I had the same issue with different VMs, so it might be specific to a Virtual Machine. Are you not able to reproduce on a real machine?

Output of sigcheck:
```
C:\Users\User\source\repos\softethervpn-original\out\build\x64-native\vpnclient.exe:
        Verified:       Unsigned
        Link date:      11:28 PM 7/14/2024
        Publisher:      n/a
        Company:        SoftEther VPN Project at University of Tsukuba, Japan.
        Description:    SoftEther VPN Client (Developer Edition)
        Product:        SoftEther VPN Client
        Prod version:   5, 2, 0, 5186
        File version:   5, 2, 0, 5186
        MachineType:    64-bit
```

Output of systeminfo:
```
Host Name:                 DESKTOP-TFIE2LE
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          User
Registered Organization:
Product ID:                00326-10000-00000-AA812
Original Install Date:     6/26/2024, 8:14:41 PM
System Boot Time:          7/15/2024, 2:40:56 PM
System Manufacturer:       QEMU
System Model:              Standard PC (Q35 + ICH9, 2009)
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 97 Stepping 2 AuthenticAMD ~4500 Mhz
BIOS Version:              EDK II unknown, 2/2/2022
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     8,188 MB
Available Physical Memory: 3,491 MB
Virtual Memory: Max Size:  8,700 MB
Virtual Memory: Available: 3,019 MB
Virtual Memory: In Use:    5,681 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-TFIE2LE
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB5039895
                           [02]: KB5027397
                           [03]: KB5036212
                           [04]: KB5040442
                           [05]: KB5037959
                           [06]: KB5039338
Network Card(s):           2 NIC(s) Installed.
                           [01]: VPN Client Adapter - VPN
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
                           [02]: Intel(R) 82574L Gigabit Network Connection
                                 Connection Name: Ethernet Instance 0 3
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.122.1
                                 IP address(es)
                                 [01]: 192.168.122.38
                                 [02]: fe80::10b:9f36:37bd:d81c
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

**Comment by chipitsine** [comment]
interesting, we didn't test on "QEMU". I run Win 11 on my laptop.
also, I tested  on Hyper-V vm.

what is virtualization of yours ? is it virtual box ?

**Comment by siddharth-narayan** [comment]
No, I run Linux, which is why I'm using a virtual machine. [QEMU](https://www.qemu.org/) is an emulator that can use KVM, mostly only used on Linux. Is there any other tests you want me to do? I will test on a native machine soon.

**Comment by siddharth-narayan** [comment]
I was able to reproduce with a native windows machine. Running vpnclient.exe is not enough, it has to be run with one of the following arguments:

1. /install
2. /uninstall
3. /start
4. /stop

Basically, this if condition must be fulfilled (with ```ms->IsNt``` always false):
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/4e8f7970361ce4eab26643f2fdbbffad451d1c6a/src/Mayaqua/Microsoft.c#L4260-L4262

**Comment by chipitsine** [comment]
correct ))

<img width="566" alt="image" src="https://github.com/user-attachments/assets/e412d54f-ed19-4d44-9af2-ad4d2ff98656">

**Comment by siddharth-narayan** [comment]
I'll make a PR to fix it. Replacing  ```ms->IsNt``` with ```IsNt()``` and removing IsNt from the structure MS should be good enough I think.

**Comment by chipitsine** [comment]
I really wonder how installer handles this

**Comment by siddharth-narayan** [comment]
I'm not sure, I think vpnclient.exe is almost never run, instead vpncmgr.exe is what is run. I was surprised that there was such a fundamental bug as well, but it seems like nobody has ever encountered it.

**Comment by siddharth-narayan** [comment]
Testing the fixes removes the error, but NicCreate still fails with error code 31. Is this expected or am I doing something wrong?

**Comment by siddharth-narayan** [comment]
I tracked down the problem with NicCreate as well, but I can't find a solution. NicCreate fails when vpnclient + vpncmd are run, but when vpnclient + vpncmgr are run **and then** vpncmd is run, NicCreate works just fine. The problem comes from these lines here:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/a836b3bd5e7163d041bb2c83d1a920c6e0bac4ce/src/Cedar/Client.c#L948-L956

Where ```CncConnect``` returns NULL. Something about simply starting vpncmgr makes CncConnect connect fine, but I can't figure out what exactly it is. Hoping you might have some insight.

**Comment by siddharth-narayan** [comment]
Still stuck on this problem. Debugging both vpncmd and vpncmgr show that neither of them start the client notification service, so I'm at a loss for where to begin fixing this. Do you have any ideas?
