### ISSUE TITLE
100% core loading related to IPSEC/L2TP issued by AMajor-C

### ISSUE THREAD

**Issue by hiura2023** [SoftEtherVPN/SoftEtherVPN#2043]
### Are you using SoftEther VPN 5.x?

- [X] Yes, I'm using SoftEther VPN 5.x, not 4.x.

### Component

VPN Server

### Operating system & version

Refer to https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1854

### Steps to reproduce

Refer to https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1854

### ❌ Actual Behavior

Refer to https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1854

### Anything else?

As to https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1854
This case has been left alone for a long time.

This case should be resolved by the person who changed the source code (the person concerned).

Source code change made by Evengard.
https://github.com/SoftEtherVPN/SoftEtherVPN/commit/1bdd9a92bcd97b55d0863a01202d872e16c4b32d

Source code:
![PROTO_L2TP C_2024-08-19](https://github.com/user-attachments/assets/5571bec5-3ee4-484f-83e2-31fe151f1d82)

**Comment by chipitsine** [comment]
@Evengard , can you please have  look ?

**Comment by Evengard** [comment]
I'll try to look on the weekend

**Comment by AMajor-C** [comment]
Oh i have openet draft pull request but its gone because i accidentally reset my fork
