### ISSUE TITLE
can not connect vpn server from android

### ISSUE THREAD

**Issue by playgithub** [SoftEtherVPN/SoftEtherVPN#205]
PC can connect to the vpn server successfully every time.
Phone (android 4.4) and Nexus (android 5) can not connect. BTW Nexus connected successful several times when I was trying initially, then I changed some configure in the server for discovering, then I configured it back, but it can not connect any more.

I've followed the instructions below:
- For server:

> https://www.softether.org/4-docs/2-howto/9.L2TPIPsec_Setup_Guide_for_SoftEther_VPN_Server/1.Setup_L2TP%2F%2F%2F%2FIPsec_VPN_Server_on_SoftEther_VPN_Server
- For android client:

> https://www.softether.org/4-docs/2-howto/9.L2TPIPsec_Setup_Guide_for_SoftEther_VPN_Server/3.Android_L2TP_Client_Setup

**Comment by moatazelmasry2** [comment]
Which VPN protocol are you using on your android?

**Comment by playgithub** [comment]
I configure it for Android, it works not, thanks all the same.
