### ISSUE TITLE
liboq fails to build on arm64

### ISSUE THREAD

**Issue by chipitsine** [SoftEtherVPN/SoftEtherVPN#2054]
### Are you using SoftEther VPN 5.x?

- [X] Yes, I'm using SoftEther VPN 5.x, not 4.x.

### Component

VPN Server

### Operating system & version

linux

### Architecture or Hardware model

arm64

### Steps to reproduce

https://github.com/SoftEtherVPN/SoftetherVPN-docker/actions/runs/10871924060/job/30166340593

```
#11 18.35 [  2%] Building C object src/Mayaqua/3rdparty/liboqs/src/common/CMakeFiles/common.dir/common.c.o
#11 18.44 /usr/local/src/SoftEtherVPN/src/Mayaqua/3rdparty/liboqs/src/common/common.c:158:10: fatal error: asm/hwcap.h: No such file or directory
#11 18.44   158 | #include <asm/hwcap.h>
#11 18.44       |          ^~~~~~~~~~~~~
#11 18.44 compilation terminated.
#11 18.44 make[2]: *** [src/Mayaqua/3rdparty/liboqs/src/common/CMakeFiles/common.dir/build.make:202: src/Mayaqua/3rdparty/liboqs/src/common/CMakeFiles/common.dir/common.c.o] Error 1
#11 18.44 make[1]: *** [CMakeFiles/Makefile2:910: src/Mayaqua/3rdparty/liboqs/src/common/CMakeFiles/common.dir/all] Error 2
#11 18.45 make: *** [Makefile:156: all] Error 2
#11 18.45 make: Leaving directory '/usr/local/src/SoftEtherVPN/build'
#11 ERROR: process "/bin/sh -c cd SoftEtherVPN &&\tgit submodule init &&\tgit submodule update &&        ./configure $TARGET_CONFIG_FLAGS &&\tmake -C build" did not complete successfully: exit code: 2
------
 > [builder 5/5] RUN cd SoftEtherVPN &&	git submodule init &&	git submodule update &&        ./configure $TARGET_CONFIG_FLAGS &&	make -C build:
18.11 [  2%] Building C object src/Mayaqua/3rdparty/liboqs/src/common/CMakeFiles/common.dir/ossl_helpers.c.o
18.35 [  2%] Building C object src/Mayaqua/3rdparty/liboqs/src/common/CMakeFiles/common.dir/common.c.o
18.44 /usr/local/src/SoftEtherVPN/src/Mayaqua/3rdparty/liboqs/src/common/common.c:158:10: fatal error: asm/hwcap.h: No such file or directory
18.44   158 | #include <asm/hwcap.h>
18.44       |          ^~~~~~~~~~~~~
18.44 compilation terminated.
18.44 make[2]: *** [src/Mayaqua/3rdparty/liboqs/src/common/CMakeFiles/common.dir/build.make:202: src/Mayaqua/3rdparty/liboqs/src/common/CMakeFiles/common.dir/common.c.o] Error 1
18.44 make[1]: *** [CMakeFiles/Makefile2:910: src/Mayaqua/3rdparty/liboqs/src/common/CMakeFiles/common.dir/all] Error 2
18.45 make: *** [Makefile:156: all] Error 2
18.45 make: Leaving directory '/usr/local/src/SoftEtherVPN/build'
------

 3 warnings found (use --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 13)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 30)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 31)
./Dockerfile:18
--------------------
  17 |     ENV USE_MUSL=YES
  18 | >>> RUN cd SoftEtherVPN &&\
  19 | >>> 	git submodule init &&\
  20 | >>> 	git submodule update &&\
  21 | >>>         ./configure $TARGET_CONFIG_FLAGS &&\
  22 | >>> 	make -C build
  23 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cd SoftEtherVPN &&\tgit submodule init &&\tgit submodule update &&        ./configure $TARGET_CONFIG_FLAGS &&\tmake -C build" did not complete successfully: exit code: 2
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c cd SoftEtherVPN &&\tgit submodule init &&\tgit submodule update &&        ./configure $TARGET_CONFIG_FLAGS &&\tmake -C build" did not complete successfully: exit 
```

@siddharth-narayan  can you have a look please ?

(we miss arm64 builds in CI, thus it only triggered while publishing arm64 to docker hub, which honestly happens from time to time)

**Comment by chipitsine** [comment]
meanwhile, amd64 is just fine https://github.com/SoftEtherVPN/SoftetherVPN-docker/actions/runs/10871859718

**Comment by siddharth-narayan** [comment]
I'll take a look, it might related to this previous issue that liboqs had, which seems to be fixed: 
https://github.com/open-quantum-safe/liboqs/issues/1208

It might also have to do with the build being on Alpine Linux.

**Comment by chipitsine** [comment]
There's small Fedora https://hub.docker.com/r/redhat/ubi8-minimal

**Comment by siddharth-narayan** [comment]
That could work, although the image is still a lot bigger, it's still only 35MB. I'll try to see if the problem is caused by Alpine. Is switching from Alpine caused by this issue or is it something you wanted to do in general?

**Comment by siddharth-narayan** [comment]
It seems like it is caused by Alpine, but can be fixed by adding ```linux-headers``` to the packages installed by ```apk add```. 
This issue and PR seems to have had the exact same problem and solution: https://github.com/docker-library/php/issues/888

**Comment by chipitsine** [comment]
alpine has known performance issues with musl.
other than that, I'm fine with alpine.

I observed something like that performance - Why is the Alpine Docker image
over 50% slower than the Ubuntu image? - Super User
<https://superuser.com/questions/1219609/why-is-the-alpine-docker-image-over-50-slower-than-the-ubuntu-image>

пн, 16 сент. 2024 г. в 22:02, siddharth-narayan ***@***.***>:

**Comment by chipitsine** [comment]
> It seems like it is caused by Alpine, but can be fixed by adding `linux-headers` to the packages installed by `apk add`. This issue and PR seems to have had the exact same problem and solution: [docker-library/php#888](https://github.com/docker-library/php/issues/888)

I will appreciate if you will create a PR

**Comment by siddharth-narayan** [comment]
PR made :)

**Comment by chipitsine** [comment]
thank you for fixing that
