### ISSUE TITLE
I cannot use the VpnGate Plugin with the 5.x client.

### ISSUE THREAD

**Issue by zevelorgani** [SoftEtherVPN/SoftEtherVPN#2065]
How do I use the VpnGate Plugin with the 5.x client on Windows?

I tried to copy the plugin dll from the 4.x client into the installation folder but it did not work.

**Comment by chipitsine** [comment]
Sorry, in https://github.com/SoftEtherVPN/SoftEtherVPN/issues/2066 you've mentioned that you cannot use it

**Comment by chipitsine** [comment]
please use vpngate resources to open issues. we do not know howto handle those issues

this particular issue tracker is for SE VPN 5.x
