### ISSUE TITLE
VpnGate 200 server limits and per-country connections

### ISSUE THREAD

**Issue by zevelorgani** [SoftEtherVPN/SoftEtherVPN#2066]
VpnGate in the SoftEther client only shows 200 connections out of several thousands.

Because of that, it often does not display servers in the country I want to connect to, or only displays a small number of low-quality servers.

Please allow displaying more servers, or better yet, displaying all known running servers in a specific country.

**Comment by zevelorgani** [comment]
I currently use the bundled client from https://www.vpngate.net/en/download.aspx, which is 4.x

**Comment by chipitsine** [comment]
sorry, this issue tracker is for SE 5.x versions, not for 4.x
