### ISSUE TITLE
BitDefender found viruses in *.exe files, also in installer | VPN CLIENT WINDOWS

### ISSUE THREAD

**Issue by daniillavr** [SoftEtherVPN/SoftEtherVPN#2078]
### Are you using SoftEther VPN 5.x?

- [X] Yes, I'm using SoftEther VPN 5.x, not 4.x.

### Component

VPN Client

### Operating system & version

Windows 11 PRO 24h2

### Steps to reproduce

1. Enable BitDefender
2. Try to install new version/run scan on already installed program
3. Get several virus info(when installing it removes file from temp folder)

### ✔️ Expected Behavior

Nothing would happen related to antiviruses

### ❌ Actual Behavior

Found a viruses

### Anything else?

I cant say if it is false-positive, but it is really weird coz i used SoftEther more than 6 months and never got any problems. Ok lets start with info:
1. `vpnsetup.exe` - https://www.virustotal.com/gui/file/e80dad4bba19b2e1a3186fcd6b84a19506134c9828e308ab0282a458c05964ec
2. `vpnclient.exe` - https://www.virustotal.com/gui/file/5fa0172902b1953fe3d03146f4ddbec05c280f0a58203a2280dce6a624148543
3. vpncmgr.exe - virus total ok, look image below.

Also new installer also cant install anything coz it gives error like "Someone is already using this file" and bitdefender at the same time deletes files that i wrote above.
Can someone say something about it? It is just weird that bitdefender didnt find anything all the time till now. It could be false-positive or couldnt.
![image](https://github.com/user-attachments/assets/e8c34e08-7ff7-4cf0-8a09-016e9d123448)
![image](https://github.com/user-attachments/assets/66f0dd64-629e-4936-8d7a-bc20b8de10d7)

**Comment by davidebeatrici** [comment]
I see the files are also being detected as adware and PUA, which is weird. I wonder if it's a result of something that is bundled in plain text (e.g. licenses and instructions)...

As for `vpnclient.exe` specifically: I'm pretty sure the extra detections are due to the code that manipulates network interfaces.

**Comment by daniillavr** [comment]
> everything is built from source, if there's virus.... I'd give 146% there's no virus
> 
> @daniillavr if you have spare time, I would appreciate if you will submit false positive report

Yeah i am going to do it. Coz i made full scan system 4 days ago and BD found nothing but then it updated it database and started to behave weird.

**Comment by daniillavr** [comment]
```

Thank you for your patience and I hope my email finds you well.

Our Malware Research Team has finished analyzing your case.

The files are clean and detection should be removed in the next couple of updates.

Should there be anything else I can assist you with, please let me know.

Have a great day!
```
