### ISSUE TITLE
how to disable HTML5 and JASON pannel for web browser ?

### ISSUE THREAD

**Issue by bobyturk** [SoftEtherVPN/SoftEtherVPN#2079]
### Are you using SoftEther VPN 5.x?

- [X] Yes, I'm using SoftEther VPN 5.x, not 4.x.

### Component

VPN Server

### Operating system & version

ubuntu22.04

### Steps to reproduce

hi . i need to disable HTML and JASON page in server . it means i dont want to show anything in browser when using 

https://<vpn_server_hostname>:<port>/admin/

**Comment by chipitsine** [comment]
well, I thougth to keep it as feature request (as it pretty valid).
why did you close it ?

**Comment by bobyturk** [comment]
> well, I thougth to keep it as feature request (as it pretty valid). why did you close it ?

i found the solution in another issue ticket then closed this because it was duplicated
