### ISSUE TITLE
The destination VPN Client server does not allow administrating connections from remote computers.

### ISSUE THREAD

**Issue by hongyi-zhao** [SoftEtherVPN/SoftEtherVPN#209]
Hi all,

I use Debian Jessie and I compile the latest git version of SoftEtherVPN.

Firstly, I start the vpnclient service:

$ sudo vpnclient start
The SoftEther VPN Client service has been started.

Then I want to use the vpncmd command to do the connection settings, but failed as follows:

$ sudo vpncmd 
vpncmd command - SoftEther VPN Command Line Management Utility
SoftEther VPN Command Line Management Utility (vpncmd command)
Version 4.19 Build 9599   (English)
Compiled 2015/10/19 20:09:05 by yagi at pc30
Copyright (c) SoftEther VPN Project. All Rights Reserved.

By using vpncmd program, the following can be achieved. 
1. Management of VPN Server or VPN Bridge 
2. Management of VPN Client
3. Use of VPN Tools (certificate creation and Network Traffic Speed Test Tool)

Select 1, 2 or 3: 2

Specify the host name or IP address of the computer that the destination VPN Client is operating on. 
If nothing is input and Enter is pressed, connection will be made to localhost (this computer).
Hostname of IP Address of Destination: 

The destination VPN Client server does not allow administrating connections from remote computers. Launch the command line management utility or VPN Client Manager on the computer that VPN Client is running on and connect to localhost.
$

Previously I can use the above command to connect the vpnclient running on my local computer.

But, as you can see, the latest git version doesn't let me do this job, why does this happen?

Regards

**Comment by genez** [comment]
Hello, I have the same issue in Ubuntu 16.04.5 LTS 
vpnclient version is: 

> Version 4.28 Build 9669   (English)
Compiled 2018/09/11 12:23:27 by yagi at pc33


I had to manually set `bool AllowRemoteConfig true` in vpn_client.config file to make it work on localhost

**Comment by ceremcem** [comment]
1. Change the line to: `bool AllowRemoteConfig true`
2. `./vpnclient stop`
3. `./vpnclient start`
