### ISSUE TITLE
ECDHE-RSA support for softether ?

### ISSUE THREAD

**Issue by fhocorp** [SoftEtherVPN/SoftEtherVPN#210]
Hello

Is there a way to have TLS1.2 ECDHE-RSA SSL encryption in softether ?

Best Regards

**Comment by moatazelmasry2** [comment]
Definitely. However it is not implemented yet.

Would you be interested in implementing that?

**Comment by fhocorp** [comment]
Sorry i have not the capacities to do that :(

**Comment by davidebeatrici** [comment]
ECDHE-RSA ciphers are now available.

**Comment by fhocorp** [comment]
Nice :+1:
