### ISSUE TITLE
How many users can a SoftEtherVPN server hold?

### ISSUE THREAD

**Issue by zhjwpku** [SoftEtherVPN/SoftEtherVPN#213]
Here is the senario:
A AWS server: 4vCPU, 8G ram, 2G bandwith
Each user may have at most 3 MultiLogins.

How many user can this server can handle?

And is there any good policy that I can try, like how many VPN should I create?
If it is ok that I have only one VPN and only one Group on the server? Will this
influnce the performance?

**Comment by moatazelmasry2** [comment]
With bridge mode (no virtual NAT) it is known to get much better speed. I have no numbers unfortunately. However SE hat its own speed test tool:
https://www.softether.org/4-docs/1-manual/4._SoftEther_VPN_Client_Manual/4.8_Measuring_Effective_Throughput

Also there's a discussion about SE on reddit. Maybe this helps
https://www.reddit.com/r/VPN/comments/388kpa/openvpn_vs_softether_vpn_protocol/

Good luck
