### ISSUE TITLE
Adapter Prevents Sleep

### ISSUE THREAD

**Issue by ghost** [SoftEtherVPN/SoftEtherVPN#215]
When I have the Ethernet adapter for SoftEther enabled, it prevents my laptop from ever reaching sleep state and causes the device battery to drain. See the following windows sleepstudy report:
![image](https://cloud.githubusercontent.com/assets/11168098/12778400/5ba6e0b8-ca17-11e5-9cf8-bef687d2d22f.png)

**Comment by moatazelmasry2** [comment]
Hi @QewQew . Is this problem still happening? Also with the newest SoftEther?

Which OS are you using? And which SoftEther Version

**Comment by domosekai** [comment]
Close due to inactivity
