### ISSUE TITLE
when open src\sepn.sln with Visual studio 2015, error occur

### ISSUE THREAD

**Issue by Owen2015** [SoftEtherVPN/SoftEtherVPN#218]
BuildUtil\Web References\SignService\Reference.map: Failed to backup file as D:\software\common\vpn\SoftEtherVPN-master\SoftEtherVPN-master\src\Backup\BuildUtil\Web References\SignService\Reference.map

BuildUtil\Web References\HvSignService\Reference.map: Failed to backup file as D:\software\common\vpn\SoftEtherVPN-master\SoftEtherVPN-master\src\Backup\BuildUtil\Web References\HvSignService\Reference.map

**Comment by davidebeatrici** [comment]
Only Visual Studio 2008 is supported.
