### ISSUE TITLE
Feature Request: Add SHA256 in OpenVPN auth

### ISSUE THREAD

**Issue by ijat** [SoftEtherVPN/SoftEtherVPN#222]
Can anyone help add this feature in OpenVPN?
If nobody wants to add, at least please show me which are the right file for me to look at? I can try to implement it slowly.
Thanks

**Comment by 3lysium** [comment]
+1

The Softether implementation is very nice and easy to use, using sha256 would it make perfect in combination with this: https://github.com/SoftEtherVPN/SoftEtherVPN/issues/240

**Comment by moatazelmasry2** [comment]
@ijat  A Pull request I created a while back adds sha256 and sha512 to OpenVPN
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/309

This should resolve your request

**Comment by ijat** [comment]
@moatazelmasry2 thank you. really appreciate it.
