### ISSUE TITLE
vpn bridge start command generates " .dat " file in /tmp folder

### ISSUE THREAD

**Issue by prateekgogia** [SoftEtherVPN/SoftEtherVPN#224]
HI 

We are using VPN bridge for tunneling solution, when we start the bridge it creates a .unicode_cache_xxxxxx.dat file in the /tmp/ directory. I want to understand the purpose for this file, and is it safe to delete the file once the VPN bridge starts. Is there a way to configure it to stop generating this file or create in some other location other than /tmp. ?

I have asked this question in forum as well, but this seems like an issue, so reporting it here too. 

Version 4.18 Build 9570   (English)
Compiled 2015/07/26 15:19:27 by yagi at pc30
Copyright (c) SoftEther VPN Project. All Rights Reserved.
# cat /etc/os-release

NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"

**Comment by chipitsine** [comment]
it is part of hamcore.se2
for more details, have a look: https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Mayaqua/Table.c#L1224
