### ISSUE TITLE
No memory leaks?

### ISSUE THREAD

**Issue by cpitclaudel** [SoftEtherVPN/SoftEtherVPN#227]
The README claims:

```
- No memory leaks. High quality stable codes, intended for long-term runs.
  We always verify that there are no memory or resource leaks before
  releasing the build.
```

This sounds like snake oil. How do you verify this? The code seems to be written in C.
Thanks for the clarification!

**Comment by moatazelmasry2** [comment]
Hi @cpitclaudel I agree that this is not really well defined and the project should work on documentation and transparent test/performance cases to reflect that

**Comment by chipitsine** [comment]
we have added memory leak testing into all supported CI (travis-ci, gitlab-ci, AppVeyor).
vpntest is used

as CI is self descripting, I do not think we need any standalone documentation

however, if someone wishes to provide such a documentation, I will be glad
