### ISSUE TITLE
Mobile server manager client

### ISSUE THREAD

**Issue by scj643** [SoftEtherVPN/SoftEtherVPN#228]
A client to configure softether with iOS Android or Windows phone would be nice

**Comment by jonisc** [comment]
Yes that would be nice. I think it would be possible for Android (APK) but not very simple for unjailbroaken iOS. -> Apple wants $ 99 /Year if you want to publish an app on the AppStore.

**Comment by moatazelmasry2** [comment]
Android also requires 25$ so this is not the issue. 
In my openion however, this is quite luxurious feature and the moment there are more urgant issues that needed attending to

**Comment by scj643** [comment]
Can always release on F-Droid

**Comment by davidebeatrici** [comment]
A web management interface has been added in #916.
