### ISSUE TITLE
Standalone DDNS client

### ISSUE THREAD

**Issue by scj643** [SoftEtherVPN/SoftEtherVPN#233]
If it is possible it would be nice if the DDNS client could be made as a standalone option as well.

**Comment by moatazelmasry2** [comment]
If you just want a standalone DDNS client, why don't you use any of the available products on the market?

**Comment by scj643** [comment]
The reason is I like the softether.net domain

**Comment by moatazelmasry2** [comment]
In my opinion this is an overkill feature
