### ISSUE TITLE
Cedar Communication Module doesn't support auth commands like UserPasswordSet/UserRadiusSet 

### ISSUE THREAD

**Issue by vejuhust** [SoftEtherVPN/SoftEtherVPN#235]
Hi guys, 
I'm using [SoftEtherPy](https://github.com/mindcollapse/SoftEtherPy) library, which is based on Cedar Communication Module, to build a tool that set up Virtual Hub and create User account remotely and automatically. 
But I didn't find any method to set user's authentication method after it's been created, and the default method is "Anonymous Authentication". For password or Radius, I have to login with **vpncmd** and use commands like `UserPasswordSet` or `UserRadiusSet`.
Do you have any plans to fix this?

**Comment by moatazelmasry2** [comment]
I wrote a small nodejs library to automate some of the vpncmd commands. It contains currently only a very small subset of the vpncmd: 
https://github.com/moatazelmasry2/softether.js

I know this is not what you are looking for, but it is something. Feel free to add your functions there

**Comment by vejuhust** [comment]
@moatazelmasry2 Yes. I did the same thing with Python3 🙌

**Comment by CarnageTR** [comment]
@vejuhust  would you share the solution. Im trying for 3 hrs from now still couldnt work it out

**Comment by vejuhust** [comment]
@CarnageTR Sorry I missed your message because of the noise in my GitHub notification. 
My solution was a part of bigger solution, and I just extracted them for you. Hope it helps 🙌
https://gist.github.com/vejuhust/b7437e8b015feb87a45cab54e318fd9c

**Comment by CarnageTR** [comment]
@vejuhust  i reviewed yor gist. So its basicly imitates command line entries right? If so helps half of my problems. Do you know why we cannot set hub password with SoftEtherPy? 

Also i encountered with another problem that i described in [here](https://github.com/mindcollapse/SoftEtherPy/issues/8). Have you seen it before? What might be the problem?

**Comment by vejuhust** [comment]
@CarnageTR Yes, it's just a wrapper for the cmd line tool. 
I read through the source code of SoftEtherPy (esp. [this file](https://github.com/mindcollapse/SoftEtherPy/blob/master/softether/api.py)), and found it's just wrapper of Cedar Communication Module, which doesn't provide instructions like `UserPasswordSet` (all supported instructions are listed in [this file](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/Admin.c)), and that's why I opened this issue.
If it's another unsupported instruction, you might find the answer in Cedar :yum:

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed
