### ISSUE TITLE
Support deb package builds on ARM processors

### ISSUE THREAD

**Issue by Leden** [SoftEtherVPN/SoftEtherVPN#237]
Debian packages cannot now be built on the arm processors because the `debian/rules` script does not recognize these processors and does not call the `configure` script.

I've written a couple of lines to fix that:
- https://github.com/SoftEtherVPN/SoftEtherVPN/pull/231
- https://github.com/SoftEtherVPN/SoftEtherVPN/pull/232

Please consider merging these.
Thank you.

**Comment by moatazelmasry2** [comment]
@leden. your two PR have been either merged or closed. Can this issue be closed?

**Comment by Leden** [comment]
Yep, what needed to be done is done.
