### ISSUE TITLE
[Feature Request]Support of TLS 1.2 with OpenVPN implementation/ in General

### ISSUE THREAD

**Issue by 3lysium** [SoftEtherVPN/SoftEtherVPN#240]
`Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA`

https://www.ssl.com/how-to/turn-off-ssl-3-0-and-tls-1-0-in-your-browser/

Since TLS1.0 is outdated and considered unsecure, I propose to update the OpenVPN implementation or the server in general to TLS1.2. Benefit would also be the support of actual cipher suites to harden the OpenVPN/ Softether server as mentioned here: https://github.com/SoftEtherVPN/SoftEtherVPN/issues/222

https://community.openvpn.net/openvpn/wiki/Hardening

**Comment by davidebeatrici** [comment]
Solved by #343.
