### ISSUE TITLE
Compile: SSLv3 Error 

### ISSUE THREAD

**Issue by Xeroxxx** [SoftEtherVPN/SoftEtherVPN#246]
Compile error v4.21-9613-beta:

tmp/objs/Mayaqua/Network.o: In function `StartSSLEx':
Network.c:(.text+0xa524): undefined reference to`SSLv3_method'
collect2: error: ld returned 1 exit status
make: **\* [Makefile:319: tmp/hamcorebuilder] Error 1

Fix:
1. Go src/Mayaqua/Network.c
2. Search SSLv3_method
3. Replace with SSLv23_method
4. Profit

**Comment by flbla** [comment]
Same issue

**Comment by moatazelmasry2** [comment]
I can compile with no problems. Does this issue still exist. Which OS are you on?

**Comment by panslothda** [comment]
I got the same Problem. OS is Arch Linux

changing the method as suggested in start post fixed Issue

**Comment by angelsclare** [comment]
![1653386314(1)](https://user-images.githubusercontent.com/24250821/170005370-491b4fac-fc3b-45a6-a661-9ef062f961b1.png)
I got the same Problem. OS is centos7
