### ISSUE TITLE
How can I add a new customized cipher？

### ISSUE THREAD

**Issue by jyy1082** [SoftEtherVPN/SoftEtherVPN#247]
Hi, 

Can someone provide any clue or guide to add a new customized cipher into this project? Thank you so much!

**Comment by moatazelmasry2** [comment]
I have just started studying SoftEther code, so I'm not the best to answer this, but here goes anyway.

It doesn't seem that difficult. SoftEther import libssl-dev headers and depends on their implementation. 

To understand how a cipher is imported into SoftEther, do a text search on one of the famous ciphers, basically the cipher is defined and added to the list of supported ciphers. Example: 

`sh
grep -rn "AES-128-CBC " *
`

Hope this helps
