### ISSUE TITLE
How to check rtm versions?

### ISSUE THREAD

**Issue by playgithub** [SoftEtherVPN/SoftEtherVPN#249]
I've found no rtm tag.
Thanks.

**Comment by moatazelmasry2** [comment]
What is rtm??

**Comment by NoahO** [comment]
I agree, I have an issue that there is no signed installer, so I was going to download the source from github (over https) and compile it, but there's no way to tell the rtm release from the beta release programmatically. Can you please add tags so it's easy to checkout the latest version?

**Comment by domosekai** [comment]
Stable repo has rtm but not in developer repo.
