### ISSUE TITLE
服务端版本存在巨大的packet_log文件，如何关闭

### ISSUE THREAD

**Issue by 1265578519** [SoftEtherVPN/SoftEtherVPN#251]
服务端版本存在巨大的packet_log文件，如何关闭

**Comment by aicochow** [comment]
这里不要用中文，他们看不懂

**Comment by 1265578519** [comment]
@aicochow  翻译都不会用么。。话说解决了，在服务端上的gui设置，dhcp那里，关闭数据包日志 话说软件都有中文版，为何会看不懂。

**Comment by aicochow** [comment]
@1265578519 国内用这个翻墙没问题吗？

**Comment by Huanxiongjun** [comment]
OK的 但是必须自己的去搭服务端 @aicochow

**Comment by moatazelmasry2** [comment]
Guys. Could you please all write in english so we can also understand. If this is not possible then please use the japanese forum on vpnusers.com

**Comment by GildedHonour** [comment]
that's chinese.
