### ISSUE TITLE
Disable RC4 in TLS per RFC7465 (chacha20 possible replacement) !!!

### ISSUE THREAD

**Issue by maurerr** [SoftEtherVPN/SoftEtherVPN#253]
This document requires that Transport Layer Security (TLS) clients and servers never negotiate the use of RC4 cipher suites when they establish connections.  This applies to all TLS versions.

An alternate cipher for low powered/cost hw is chacha20-poly1305 that could provide up to 2x performance for any x64 capable device.

**Comment by omlaverde** [comment]
Modify files:
/src/Cedar/Server.c
Line 132:
#define SERVER_DEFAULT_CIPHER_NAME "AES128-GCM-SHA256"

/src/Mayaqua/Network.c
Line 236:
static char *cipher_list = "AES128-GCM-SHA256 AES128-SHA256 AES256-GCM-SHA384 AES256-SHA256 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-SHA256 DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-SHA256 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384";

Recompile, instructions in BUILD_UNIX.TXT

Install:
cp bin/vpnserver/hamcore.se2 /opt/vpnserver
cp bin/vpnserver/vpnserver /opt/vpnserver

Good luck

**Comment by davidebeatrici** [comment]
Solved by #343.
