### ISSUE TITLE
[FEATURE REQUEST] Client device internal IP address in Session information

### ISSUE THREAD

**Issue by ghost** [SoftEtherVPN/SoftEtherVPN#254]
It would be **very useful** to have the **internal** IP assigned by EtherSoft's own DHCP  to clients, displayed in session information (Virtual Hub). Since we are well provisioned with a "Client IP Address" and a "Client IP Address (Reported)", why not a "Private Client IP Address" as well ? 

Any chance the developers might consider this ? 

Thank you.

![2016-09-29_2-38-40](https://cloud.githubusercontent.com/assets/16109536/18943990/d8bc2c30-85f0-11e6-8e18-7ff9d613456b.jpg)

**Comment by domosekai** [comment]
Since the connection is L2, it's impossible to achieve this in every situation.
