### ISSUE TITLE
[Feature Request] Service Start/Stop

### ISSUE THREAD

**Issue by i486** [SoftEtherVPN/SoftEtherVPN#255]
This is the batch script i am currently using

```
sc start SEVPNCLIENT
TIMEOUT /T 1 /NOBREAK
start "" /w /d "C:\Program Files\SoftEther VPN Client\" "vpncmgr_x64.exe"
TIMEOUT /T 1 /NOBREAK
sc stop SEVPNCLIENT
```

It simply starts the VPN Client after VPN Service is started and stop the VPN service when client is not in use.

Its working fine. But it would be nice to see it implemented in the client software. Many people like me who doesn't like useless services (since i am not running VPN SERVER or something) running will really appreciate the function.

Thank you

**Comment by chipitsine** [comment]
installer already allows not to install "useless" components. i.e. you can skip installing server if you do not need it.

what is your suggestion?

**Comment by i486** [comment]
More on here
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/288#issuecomment-374331164

**Comment by hazencruz** [comment]
I too would like to see this implemented. As things are right now, I have to totally uninstall softether when not in use, and re-install when I want to use it. It's very annoying and happens even when I don't install the server software.
