### ISSUE TITLE
Port to ARMv8 (aarch64) on Ubuntu 16.04

### ISSUE THREAD

**Issue by vielmetti** [SoftEtherVPN/SoftEtherVPN#261]
Just started this, didn't get too far to make sure that it's actually working as advertised, but here's the sorts of things I had to do.

Hopefully at some point this is better codified.

1) The instructions refer to the `yum` package manager; Ubuntu uses `apt`, with the same packages available under slightly different package names.

2) The "configure" script adds a "-m64" flag to `cc`, which is not recognized by the ARM compiler. Deleting it was necessary for the build to progress.

3) At run time for `vpnserver` when installed in /usr/bin I get the error

```
Fatal Error: The file "hamcore.se2" is missing or broken.
```

Doing `cd /usr/vpnserver; sudo ./vpnserver start` caused the server to start.

My hope and plan is to eventually have this up and running under Docker, which would force the issue of getting every single dependency named precisely. I don't know if there are Intel-specific things hiding in the code (or if it's ever been ported to a non-Intel system).

thanks

Ed

**Comment by chipitsine** [comment]
I guess we can close this issue after https://github.com/SoftEtherVPN/SoftEtherVPN/pull/507

**Comment by paskal** [comment]
Can be closed.
