### ISSUE TITLE
Scp connection dropped

### ISSUE THREAD

**Issue by deatwisedog** [SoftEtherVPN/SoftEtherVPN#262]
Hello!
First, thank you, guys, for that product - it's just insane!

Unfortunatelly i have some troubles with copying files over vpn (OpenVPN mode)
When i try to copy large (Bigger than 10Mb) from windows machine (Winscp) to linux- server over VPN, i have connection error, and, sometimes, dropping vpn connection.
In WinSCP log i see something like this:

```
. 2016-10-19 10:37:44.679 Timeout waiting for network events
. 2016-10-19 10:37:44.679 There are 32832 bytes remaining in the send buffer
. 2016-10-19 10:37:44.679 There are 32832 bytes remaining in the send buffer, need to send at least another 64 bytes
. 2016-10-19 10:37:44.679 Looking for network events
. 2016-10-19 10:37:44.768 Detected network event
. 2016-10-19 10:37:44.768 Enumerating network events for socket 1644
. 2016-10-19 10:37:44.768 Enumerated 34 network events making 34 cumulative events for socket 1644
. 2016-10-19 10:37:44.768 Handling network write event on socket 1644 with error 0
. 2016-10-19 10:37:44.768 Handling network close event on socket 1644 with error 10053
. 2016-10-19 10:37:44.768 Selecting events 0 for socket 1644
. 2016-10-19 10:37:44.768 Network error: Software caused connection abort
```

When i tro to copy files from linux-to linux, i see "Write Failed: Broken pipe"
I got same trouble, when try to copy files over WebDav.

How i can debug and fix it?

Note! When i try to copy file from vpn-server to target linux-server, all works fine.

p.s. just SSH works fine!

**Comment by moatazelmasry2** [comment]
Ca you access the server logs??
