### ISSUE TITLE
Disabling SSL is not enforced for OpenVPN clients

### ISSUE THREAD

**Issue by xortim** [SoftEtherVPN/SoftEtherVPN#263]
Using
`ServerCipherSet DHE-RSA-AES256-SHA`

And changing the vpn server configuration file to read:
`bool AcceptOnlyTls true`

Still shows SSL in the negotiated Cipher Suite for VPN clients, as seen in the client logs:
`Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA`

The main Cipher Suite appears to be honored, but not the TLS protocol limitation, as seen in OpenVPN client log.

**Comment by moatazelmasry2** [comment]
+1 I think this is a must have feature

**Comment by davidebeatrici** [comment]
SSLv3 has been permanently disabled in #594.
