### ISSUE TITLE
**WARNING** VPNGATE TOTALLY INSECURE! USES RC4 TLSV1 SSLV3

### ISSUE THREAD

**Issue by zyb9** [SoftEtherVPN/SoftEtherVPN#264]
**VPNGATE uses very old broken insecure protocols RC4 TLSv1 SSLv3.
These bugs have been reported as far back as 2014**

_**Only reason not to fix these is, they are considered "Features" that enable spying.**_

**USE AT YOUR OWN RISK!**

[https://github.com/SoftEtherVPN/SoftEtherVPN/issues/120](url)
[https://github.com/SoftEtherVPN/SoftEtherVPN/issues/147](url)
[https://github.com/SoftEtherVPN/SoftEtherVPN/issues/179](url)

**Comment by omlaverde** [comment]
Modify files:
/src/Cedar/Server.c
Line 132:
#define SERVER_DEFAULT_CIPHER_NAME "AES128-GCM-SHA256"

/src/Mayaqua/Network.c
Line 236:
static char *cipher_list = "AES128-GCM-SHA256 AES128-SHA256 AES256-GCM-SHA384 AES256-SHA256 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-SHA256 DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-SHA256 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384";

Recompile, instructions in BUILD_UNIX.TXT

Install:
cp bin/vpnserver/hamcore.se2 /opt/vpnserver
cp bin/vpnserver/vpnserver /opt/vpnserver

Good luck

**Comment by davidebeatrici** [comment]
Solved by #343.
