### ISSUE TITLE
Change MAC Address on tun device for Openvpn windows client

### ISSUE THREAD

**Issue by henderbj** [SoftEtherVPN/SoftEtherVPN#265]
Hi, fellows.

First, congratulations on working on this great open source software.

I have this infrastructure:
Softether Server:
- OS: Ubuntu 16.04.
- Securenat Enabled (full: NAT + DHCP)
- Openvpn protocol enabled: listening on 1194 / UDP

Client:
- OS: Windows (tested on W7 and W10)
- Openvpn GUI
- Using tun device

Problem:
- I find no way to change MAC Address detected by the Softether's DHCP server when a machine is connecting using tun device.

Description:
I have tried:
1.- To change MAC Address shown on Windows Network and Sharing Center (that MAC address is no even the same that get detected on softether server).
2.- Delete and create new tun/tap device, using Windows tun/tap driver scripts deltapall.bat and addtap.bat.

Problem: Same MAC Address is always detected on Softether (SE) server when connecting from my Windows machine (that happens to be a Virtualbox Virtual Machine). This means that a same IP is always leased from SE's DHCP server.

Please help me diagnose this problem. Thanks in advance.

**Comment by MtCedarNet** [comment]
Aren't you using L3(tap) mode client?
In L3 mode, OpenVPN client doesn't send MAC address to server.

**Comment by henderbj** [comment]
@MtCedarNet Hi, thanks for answering.

Yes, I would like to use L3 mode if possible. However problem is that I can't solve IP conflicts because I can't make server to see another MAC and assign a new IP.

Using L2 mode, I am able to change MAC address (and then obtain new IP), but then the routing table is no correctly set to have all internet networking through VPN. Probably I could find a way to correctly update the routing table when using L2 mode.

Well, probably what you say explain why I can't make server see another MAC Address from same Windows machine.

**Comment by henderbj** [comment]
If somebody interested, I was able to make it work by using tap device (layer 2) and routing traffic through VPN adding these lines to configuration file:

dev tap
route-delay 10
route-gateway dhcp
redirect-gateway def1

The route-delay is no essentially necessary. You can test with/without it.
