### ISSUE TITLE
bug Ver 4.21, Build 9613 (windows)

### ISSUE THREAD

**Issue by chenTest2013** [SoftEtherVPN/SoftEtherVPN#266]
linked the vpn,and then exit vpn client manager program ,sometiem make all Browsers on my pc can not internet ,but other software can

**Comment by moatazelmasry2** [comment]
I'm not sure I really understood.

You connected using SoftEther client to some server. Then stopped the client. Now browsers are not working anymore. Is this what you mean?

If yes then please confirm that this issue still happens with the newest SoftEther client and Server. Also please provide more details, like which windows are you using. Your settings, etc..

**Comment by chipitsine** [comment]
browsers are known to use SSL/TLS, windows add DF (don't fragment) bit on such traffic.
very common case of "my browser is not working" is some fragmentation issue

but it is only a guess. actually, I'd say that more information would be really helpful


if there is no update, I'd close this issue

**Comment by chipitsine** [comment]
feel free to reopen when detailed debug is available
