### ISSUE TITLE
Is ovpn import supported by SoftEther client?

### ISSUE THREAD

**Issue by Suncatcher** [SoftEtherVPN/SoftEtherVPN#269]
Can I import ovpn file to and connect to third-party server (not SoftEther)? I used paid VPN service and was given a config.

**Comment by moatazelmasry2** [comment]
SoftEther Client only supports SoftEther own VPN protocol. So it is not feasible to support the import function of another protocol 

Did that answer your question?

**Comment by Suncatcher** [comment]
Yes, indeed.
