### ISSUE TITLE
icmp tunnel

### ISSUE THREAD

**Issue by italy2010** [SoftEtherVPN/SoftEtherVPN#27]
Hello, i use icmp tunnel on windows7 . and my server is win 2003.

many times connection disconnects. and give me error 13.
also when i check ping to my server it is ok.
why connection disconnects?

**Comment by sonvirgo** [comment]
I also got disconnect after a while and VPN over DNS not work just over ICMP so it is very slow
<img width="864" alt="sketch 1" src="https://user-images.githubusercontent.com/10823037/32698259-f8721dc4-c7d4-11e7-8846-ed022c91dbb1.png">

**Comment by PaulGWebster** [comment]
All I can say is that I use vpnserver on a FreeBSD system with windows clients utilizing icmp (tcp/udp is dropped upstream) and all seems well

**Comment by domosekai** [comment]
No change needed.
