### ISSUE TITLE
can't create virtual network adapter

### ISSUE THREAD

**Issue by metya** [SoftEtherVPN/SoftEtherVPN#271]
Hi.

i have a trouble. I can't create a new virtual network adapter.
when i try create new it has a error with text "Installation of the Virtual Network Adapter device driver failed" I use windows 10. So what i'm doint wrong? I can't figure out with it.

**Comment by DJChupa13** [comment]
I've ran into this issue today when installing Build 9745 and I still have no solution.  Installing on Windows 10 Pro x64. Tried multiple previous client builds, but no luck.
- Disabled Windows Firewall
- No AV products running or active
- Running on local administrator account
- Install and client launch is ran as administrator
- Tried multiple package downloads, clean installs, and restarts
This is an out-of-box Microsoft Surface Pro X.  SoftEther VPN is the only third party software installed on the entire machine.

The only thing that I can think of that is not perfectly OOBE here is that it was shipped with Win 10 Home and upgraded to Win 10 Pro via the Microsoft Store method.

Hit me with a reply if you need more info.
