### ISSUE TITLE
Why will this issue section be closed?

### ISSUE THREAD

**Issue by baimafeima** [SoftEtherVPN/SoftEtherVPN#272]
I understand that responding to all the issues raised is a lot of work but I do not see any valuable reasons why the issue section should be closed. Not everyone in the community has the ability to contribute in terms of coding, yet it is important to provide a publicly visible area to discuss issues (bugs, suggestions, problems) related to the use of SoftEtherVPN. Only referring to pull requests or e-mail contact is not an acceptable practice. I encourage you to reconsider. Thank you.

**Comment by xortim** [comment]
My guess is that the goal is not be to discourage issue reporting. Rather, an attempt to force people to write code to fix the bugs as a part of the *public* reporting process.

**Comment by dnobori** [comment]
For the "Issues" forum:

Currently, this project has two duplicated forums: Issues and VPN Users Forum. The actual usage of both forums are very similar. It is very inefficient for users to seek for / post to both forums to ask questions or post feature requests.

The VPN Users Forum has been active before I created this GitHub repository. Spam posts are bothering. While there is a problem of spam posts, spams are periodically removed, and the forum has some anti-spam script features to avoid them as possible.

**Comment by dnobori** [comment]
xortim,

> an attempt to force people to write code to fix the bugs as a part of the public reporting process.

In my thought, forcing people to write code is not a good idea. It is impossible to "force" people to work. Every person can gently request to other person to write a code (or do something). However, any person may not "force" to other person to do something for a speficic person or a group of people, even for public interests.

**Comment by dnobori** [comment]
For issue posting, discussion and pull requests processing on the project, I'd like to discuss about them on the https://github.com/SoftEtherVPN/SoftEtherVPN/issues/268 page.

**Comment by xortim** [comment]
@dnobori - thanks for your reply. I apologize if I gave the wrong impression. Force is a little hyperbolic, but rather encourage people to author code alongside their bug reports :)

**Comment by adminport** [comment]
Co new maintener wanted

https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

**Comment by moatazelmasry2** [comment]
As it looks like, the issue section on github definitely won't be killed, but I like to keep it for developer related questions, but not user related questions. As for vpnusers.com there's an issue #424  created recently and we should discuss there what to do about spam on vpnusers.com. I'd like to close this issue within the next few days if there are no pbjections.
