### ISSUE TITLE
Remove blank line at the start of init script (Debian)

### ISSUE THREAD

**Issue by DDGo** [SoftEtherVPN/SoftEtherVPN#277]
See #276 for the pullrequest I made for this. Simply said, the recent addition of the LSB header by user knok in version 4.22 introduced a blank line, causing the vpnserver daemon not to start.

**Comment by paskal** [comment]
I guess there is no need for separate issue apart from #276. Let's resolve this one, @DDGo?

**Comment by DDGo** [comment]
Not needed. Pull request already exists
