### ISSUE TITLE
Bonjour/mDNS passthru option

### ISSUE THREAD

**Issue by schidakov** [SoftEtherVPN/SoftEtherVPN#278]
Unfortunately, when connecting from macOS or iOS-devices via L2TP-connection to a server with enabled iTunes Home Sharing option, it doesn't 'see' media storage.
I even established connect with my Windows 10 PC, but result is the same: iTunes doesn't detect mediabase at remote server.
Within established VPN-connection clinet receives a local IP-address, i.e. server has 192.168.10.2 and client has 192.168.10.17 and ping freely in both directions,

How can I enable multicast packets passthru to remote device?

**Comment by domosekai** [comment]
macOS / iOS issue. No change needed.
