### ISSUE TITLE
MTU not changeable

### ISSUE THREAD

**Issue by wernersbacher** [SoftEtherVPN/SoftEtherVPN#280]
Hi,
my server doesn't allow a change of the MTU size bigger than 1514. Sadly, the Bridge mode will send Jumboframes with 2000 Bytes, so that's not working.

There has to be a setting where you can chose the MTU size - please!

**Comment by DevGoslinga** [comment]
> Sadly, the Bridge mode will send Jumboframes with 2000 Bytes, so that's not working.

There has to be some kind of misconfiguration. The bridge function supports a MTU (excluding Ethernet header) of up to 1500 bytes without incident. My guess is that some client on your ethernet segment or from a cascaded connection has jumbo frames configured.

**Comment by domosekai** [comment]
SoftEther does not send jumbo frames. It must be some other devices doing that.
