### ISSUE TITLE
error occurred while setting up VPN Server Using SoftEther

### ISSUE THREAD

**Issue by suyash95** [SoftEtherVPN/SoftEtherVPN#286]
sudo chmod 755 /etc/init.d/vpnserver && /etc/init.d/vpnserver start
-- Alert: SoftEther VPN Kernel --
Fatal Error: The file "hamcore.se2" is missing or broken.
Please check hamcore.se2.

(First, reboot the computer. If this problem occurs again, please reinstall VPN software files.)
touch: cannot touch '/var/lock/subsys/vpnserver': Permission denied

I tried rebooting my system..still i get the same problem.
Help me out with this.

Thanks

**Comment by Siggemada** [comment]
I had the same problem. It´s related to path.

I use it from /usr/vpnserver and added a WorkingDirectory = to the service module (systemd).

**Comment by moatazelmasry2** [comment]
You must start SoftEther as a root.

**Comment by ToroNZ** [comment]
For future travellers driving rhel7 or similar: Make sure 'hamcore.se2' has the same file permissions as the vpnserver binary.

```sudo chown --reference=vpnserver hamcore.se2```

**Comment by johnbendi** [comment]
For me I had this problem when attempting to run it from a symlink I created thus `/usr/local/bin/(vpnmd/vpnclient) -> /usr/local/vpnclient/(vpncmd/vpnclient)`. The problem can be resolved by instead adding `/usr/local/vpnclient/` to path or running `./(vpncmd/vpnclient)` from the installation directory.
