### ISSUE TITLE
vpnclient_**.exe is still running after closing SoftEther VPN

### ISSUE THREAD

**Issue by i486** [SoftEtherVPN/SoftEtherVPN#288]
I  am not running VPNGate server.  
I don't need this service (SEVPNCLIENT) always running when i am NOT using SoftEther VPN.

Please implement a feature to automatically start service when needed by VPN Client and stop service when SoftEther VPN is closed/not in use.

**Comment by moatazelmasry2** [comment]
Hi there, I just tested this and I can not see any sevpnclient and all related SofEther client processes are closed when the client is closed. The client has to be closed by going to the bottom right side of the screen and close it and not just click on X in the SE client windows

If you are seeing this phenomena then my questions:
- Which windows are you using?
- Are you using the latest release of SoftEther?

**Comment by moatazelmasry2** [comment]
OP did not answer in a while.  Closing this issue.

**Comment by i486** [comment]
Hey, moatazelmasry2. Sorry for answering late.

When we install SoftEther Client software for a first time, it installs SEVPNCLIENT (vpnclient.exe & vpnclient_x64.exe) SERVICE as AUTOMATIC startup type, which means its running all the time. 

I know it manages Virtual Network Adapter and needed to be running when one has to use SoftEther VPN Client Manager. But it really doesn't have to running all the time when we aren't even using/running the SoftEther Client/VPN. 

So what i am hoping to see implemented is to install SEVPNCLIENT SERVICE with Manual startup type. So it doesn't run all the time because it will not start when Windows started.
And when user run SoftEther VPN Client Manager (VPNvpncmgr & vpncmgr_x64.exe), it starts the SEVPNCLIENT service first and continues.
And when user finished using SoftEther VPN Client, it stops the SEVPNCLIENT service.

This is my BAT script that does exactly the same thing. But it would really nice to have it natively implemented in SoftEther Client.

```
sc start SEVPNCLIENT
TIMEOUT /T 1 /NOBREAK
start "" /w /d "C:\Program Files\SoftEther VPN Client\" "vpncmgr_x64.exe"
TIMEOUT /T 1 /NOBREAK
sc stop SEVPNCLIENT
```

**Comment by sebasijan** [comment]
I am seeing this issue too

Windows 10 
SoftEther 4.25.0.9656
