### ISSUE TITLE
IPsec is mentioned as supported in README

### ISSUE THREAD

**Issue by ohault** [SoftEtherVPN/SoftEtherVPN#289]
Hello,

In SoftEther README, we can read the following:

+++++++++++++++++++++++++++++++

SOFTETHER VPN ADVANTAGES
------------------------
- Supporting all popular VPN protocols by the single VPN server:
  SSL-VPN (HTTPS)
  OpenVPN
  IPsec
  L2TP
  .....

+++++++++++++++++++++++++++++++

I presumed "full flavor" IPsec would be supported by SoftEtherVPN, but I'm not sure it is currently the case. I mean in the way similar to a project like strongSwan.  

Olivier

**Comment by aenertia** [comment]
There are varied references to users managing to get radius support working, but only IKEv1 / PSK is currently supported. 

See:

http://www.vpnusers.com/viewtopic.php?p=5425

**Comment by ohault** [comment]
According to #13 , @moatazelmasry2 is already working on this at 
https://github.com/moatazelmasry2/SoftEtherVPN/tree/ipsec-tunnel

**Comment by ohault** [comment]
Any update on this ?

In the while of a "full flavor" IPsec support, I suggest to the following change in the readme

> Supporting all popular VPN protocols by the single VPN server:
> SSL-VPN (HTTPS)
> OpenVPN
> IPsec

by 

> Supporting all popular VPN protocols by the single VPN server:
> SSL-VPN (HTTPS)
> OpenVPN
> IPsec (only IKEv1 / PSK is currently supported)

**Comment by domosekai** [comment]
Close due to inactivity

**Comment by ohault** [comment]
[IKE2 is still missing](https://github.com/SoftEtherVPN/SoftEtherVPN/issues/13)
