### ISSUE TITLE
No vpncmd option for DHCP static routing table

### ISSUE THREAD

**Issue by sanderux** [SoftEtherVPN/SoftEtherVPN#290]
There does not seem to be a vpncmd command to edit the static route table of the secureNAT dhcp server.

**Comment by MtCedarNet** [comment]
There is 'PUSHROUTE' option in 'DhcpSet' command.
> DhcpSet [/START:start_ip] [/END:end_ip] [/MASK:subnetmask] [/EXPIRE:sec] [/GW:gwip] [/DNS:dns]
 [/DNS2:dns2] [/DOMAIN:domain] [/LOG:yes|no] [/PUSHROUTE:"routing_table"]
> /PUSHROUTE - Specify the static routing table to push.
> Example: "192.168.5.0/255.255.255.0/192.168.4.254, 10.0.0.0/255.0.0.0/192.168.4.253"
> Split multiple entries (maximum: 64 entries) by comma or space characters. Each entry must be specified in the "IP network address/subnet mask/gateway IP address" format.
> This Virtual DHCP Server can push the classless static routes (RFC 3442) with DHCP reply messages to VPN clients.
> Whether or not a VPN client can recognize the classless static routes (RFC 3442) depends on the target VPN client software. PacketiX VPN Client and OpenVPN Client are supporting the classless static routes. On L2TP/IPsec and MS-SSTP protocols, the compatibility depends on the implementation of the client software. You can realize the split tunneling if you clear the default gateway field on the Virtual DHCP Server options. On the client side, L2TP/IPsec and MS-SSTP clients need to be configured not to set up the default gateway for the split tunneling usage.
> You can also push the classless static routes (RFC 3442) by your existing external DHCP server. In that case, disable the Virtual DHCP Server function on SecureNAT, and you need not to set up the classless routes on this command.
> See the RFC 3442 to understand the classless routes.

**Comment by moatazelmasry2** [comment]
Hi @sanderux . As @MtCedarNet mentioned you can use the PushRoute option in vpcmd. Is this what you are looking for. This issue has seen no reply since a couple of month and I'd like to close it within the next few days if it remained inactive

**Comment by sanderux** [comment]
Hi, Thanks for the answer. We have since moved to a different solution but thanks.
