### ISSUE TITLE
New vpnusers.com or mailing list is needed

### ISSUE THREAD

**Issue by moatazelmasry2** [SoftEtherVPN/SoftEtherVPN#296]
Dear all,

for sometime now, I've been trying to be active on vpnusers.com helping others to solve their issues.
Unfortunately the experience of using vpnusers.com has been quite frustrating, in particular the following points:

1- Spam: there's alot of that. And when reporting it, it takes way too long to disappear
2- When an issue is resolved, there's no way to mark the thread as resolved
3- There's really no notification mechanism, to know when someone replies to my answer. Going to "View my posts" is not really ideal

I suggest that may we move to some other form of QA forums, really any available solution would do. Some suggestions:

1- A clone of stackoverflow self hosted
2- Stackoverflow itself
3- Github issues
4- https://gitter.im/
5- Reddit (as a last resort)

**Comment by fenice2** [comment]
I'd agree that it is about time something was done about the forums. In my opinion the major problem with the forums is the lack of management and effective moderation. There are plug-ins that can allow a moderator to mark a thread as solved. If you're a moderator then you can edit the first post and that allows you to edit the thread title to mark it as solved but that too long-winded.

Spam, there are also effective plug-ins that can get rid of most of the spam and my guess is they aren't implemented. Spammers should be banned (and their posts removed) immediately but that doesn't seem to be happening as the posts and users accounts are visible for years.

The forums software allows subscriptions to specific threads (or boards) and you should get a notification but I'm not sure if there's a feature to get an email notification about a thread update.

The above features might all depend on addition plug-ins or more recent versions of the software  and again, that needs someone to manage the forums (software).

I would agree with you about the general state of the forums and that something needs to be done. I'm a moderator on a forum that has the some phpBB software and I see very little (almost none) spam and if anyone posts with spam links they're banned immediately I see them.

If you're not getting email notifications then it's possible to get an rss feed to these forums, I use quiteRSS for that and a scrape can be scheduled as often as you like and I find that better than getting a ton of email notifications.

Unfortunately I have a feeling that this subject isn't likely to go very far or fast but it does need doing. It's a shame really as this is a great product that could, and should, be in widespread use. Although I'm a novice with VPN software I found this SoftEtherVPN far easier to set-up and configure than comparable products.

BTW, you do an excellent job of helping on the forums. :)

**Comment by moatazelmasry2** [comment]
+1
Totally agree
And many thanks for your kind words

**Comment by chipitsine** [comment]
@davidebeatrici , I heard you did something with spam on vpnusers.com ? if so, can we close this issue?

**Comment by davidebeatrici** [comment]
I'm going to reply in #424, which is more recent.
