### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [SoftEtherVPN/SoftEtherVPN#3]
I find that include guards like "[ACCOUNT_H](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/749497dde0a1dd08c434a73b9d4e93dc3e3326d9/src/Cedar/Account.h#L84)" and "[CM_H](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/749497dde0a1dd08c434a73b9d4e93dc3e3326d9/src/Cedar/CM.h#L84)" are too short for the safe reuse of your header files.

**Comment by domosekai** [comment]
Close in favor of #381
