### ISSUE TITLE
sslv3 problem in archlinux on raspberry

### ISSUE THREAD

**Issue by youxiaojie** [SoftEtherVPN/SoftEtherVPN#305]
compile in archlinux on raspberrypi and in link step it shows:

tmp/objs/Mayaqua/Network.o: In fuction 'StartSSLEx':
Network.c(.text+0xa15c):undefinedreference to 'SSLv3_method'

how to change the source to prevent it?

**Comment by akuropka** [comment]
why not using the available package?

**Comment by mpipo** [comment]
There's a patch available [here](https://aur.archlinux.org/cgit/aur.git/tree/disable_sslv3.patch?h=softethervpn) (AUR link)
