### ISSUE TITLE
Multiple logins policy doesn't work

### ISSUE THREAD

**Issue by RegnaM-** [SoftEtherVPN/SoftEtherVPN#306]
Hello,

I'm using latest beta version 4.22 Build 9634.

After several test it seems multiple logins policy doesn't work at all.

I've set policy to "1" and i'm still able to connect several times simultaneously.

**Comment by moatazelmasry2** [comment]
Are you using radius? in this case the policy will be ignored. But you can configure that in Radius. Please see :
https://www.gnu.org/software/radius/manual/html_node/Multiple-Login-Checking.html

Does this help?

**Comment by raorao05** [comment]
@moatazelmasry2 
no，according to my test,if you want to use radius to limit multiple login,the radius's accounting feature must be used,but i find softether does not implement this feature.

any thing i can do to fix this or my testing is wrong

**Comment by moatazelmasry2** [comment]
You can help by implementing radius accounting :)

There are some further options in Policy, like "Number of simultaneous MAC Address" or "Number of sessions". Sorry don't remember the names exactly, but try those too
