### ISSUE TITLE
IPv6 Leak: IPv6 is not VPN encapsulated

### ISSUE THREAD

**Issue by Zenith-Nadir** [SoftEtherVPN/SoftEtherVPN#307]
When using VPN tunnel, IPv6 protocol is not VPN tunneled and is connecting to Internet without VPN encapsulation. Serious security and privacy issue. Disabling entirely IPv6 protocol in OS is a partial solution, but since softether is supporting IPv6, this issue should be addressed as soon as possible.
SE VPN client connecting to SE server supporting IPv6 acquires new DHCPv6 address, yet the traffic from the client is not redirected through VPN.

**Comment by moatazelmasry2** [comment]
:+1:

**Comment by Zenith-Nadir** [comment]
After some more detailed research it turns out that SoftEther VPN tunnel encapsulates both IPv4 and IPv6 protocols, and I have noticed there are no IPv6 or DNS leaks.
However this works only while NOT using VPNGate connections. With VPNGate, it appears IPv6 is probably not supported at all.
Closing as no issue.
