### ISSUE TITLE
[vpncmd] No way to change NoUdpAcceleration

### ISSUE THREAD

**Issue by mogikanin** [SoftEtherVPN/SoftEtherVPN#308]
How to change NoUdpAcceleration option via vpncmd?

**Comment by mogikanin** [comment]
I've added DISABLEUDP option into AccountDetailSet command. This is done in my fork.
@dnobori would you like to have this changes in main repo? If so, then I'll create pull request for this.

**Comment by moatazelmasry2** [comment]
Could you please create a Pull Request so that it can be reviewed from the community?

**Comment by mogikanin** [comment]
sure, https://github.com/SoftEtherVPN/SoftEtherVPN/pull/389

**Comment by chipitsine** [comment]
the corresponding PR was merged. closing the issue
