### ISSUE TITLE
Cannot compile client under Kubuntu 16.10

### ISSUE THREAD

**Issue by Paul17041993** [SoftEtherVPN/SoftEtherVPN#310]
All the required libraries installed, the client still cannot be compiled. Compiler complains about needing the -fPIC flag yet adding said flag to the arguments is ignored (both via CLI and adding it to the makefile).

[output.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/805333/output.txt)

**Comment by hfs** [comment]
Try editing the `Makefile` and replace the line

    CC=gcc

with

    CC=gcc-4.9

(Package gcc-4.9 has to be installed.)

**Comment by Paul17041993** [comment]
I ended up just compiling the entire project from raw source as the pre-made object files provided by the site are simply too stale to work with modern compilers...
