### ISSUE TITLE
[ Alternatives for users ]

### ISSUE THREAD

**Issue by ghost** [SoftEtherVPN/SoftEtherVPN#317]
It's 2017 and this software has many vulnerability. Most of them are already reported several years ago
but they never fix it. Stop using it, seriously, for your network and your vpn users.
If you're a developer, you should help either project: OpenVPN, stone.

1) OpenVPN
Long-lived VPN software. Has wide community from worldwide.

2) stone
Developed by Mr. Sengoku, this software can re-route the packet to anywhere.

If you tried VPN on your smartphone, you may noticed battery decrease rapidly.
If you stop using VPN and choose stone, battery life will improve. Unlike VPN, stone send/receive
a packet only when necessary.

Website: http://www.gcd.org/sengoku/stone/Welcome.en.html
Read Comments: http://www.gcd.org/blog/2011/06/806/#comments
Latest "stone.c": http://ja.osdn.net/cvs/view/stone/stone/stone.c?view=log

> Android[stone(Personal Certification Auth)]====TLS1.2(stone 2.4+)===>Open Server[stone--routeto-->Privoxy]⇒internet

**Comment by yoursoftwarebug** [comment]
> Android[stone(Personal Certification Auth)]====TLS===>Open Server[stone--routeto-->Privoxy]⇒internet

Here's how to do it; ready for some cooking?

Requirements:
1 Open server(Linux/Windows)
1 Android (download "stone for Android") _it's a shame it can't be found on FDroid, someone do something!_
Your brain


Okay.

> STEP 1: CREATE SELFSIGN CERTIFICATE FOR SERVER AND CLIENT

Useful memo: https://tinyurl.com/kcs7gm6

1.
Run "CA, client" codes on your terminal(on Windows, download openssl.exe).
This will generate CA(for server) and DEVICE(for Android) - 2 certificate pairs.
(if you need another cerificate for DEVICE, run "2+ client" codes)

2.
Change these cerificates to PEM format (above URL > ".key/.crt to .pem")
Stone can only recognize PEM format.

> STEP 2: CREATE CONFIG FILE

1. On server side, create a file named "stone.conf".

> -dd
> -z tls1
> -z key=/path/to/serverKEY.pem
> -z cert=/path/to/serverCRT.pem
> -z CAfile=/path/to/personalCA.pem
> -z verify
> -z re0=”^/C=XXXXXXXXXXX$”
> -z re1=”^/C=YYYYYYYYYYY$”
> -z verbose
> 127.0.0.1:8118 192.168.100.100:443/ssl 192.168.100.200

2. On client side(Android), create a file named "stone.conf". Save it to SD card or something.

> -q tls1
> -q key=/path/to/deviceKEY.pem
> -q cert=/path/to/deviceCRT.pem
> -q CAfile=/path/to/personalCA.pem
> -q verify
> -q re0=”^/C=XXXXXXXXXXX$”
> -q re1=”^/C=YYYYYYYYYYY$”
> -q verbose
> 192.168.100.100:443/ssl 127.0.0.1:8888

Make sure you change some lines.
a. -z = for server, -q = for client.
b. If you don't need any debug output, remove -dd and "verbose" lines(which is not recommend).
c. -z re = e.g., ”^/C=US/O=Github/CN=client(00|01)\.mycompany\.local$” <- z(server) specify what client certificate is approved to connect
d. -q re = e.g., ”^/C=US/O=Github/CN=wireless\.mycompany\.local$” <- q(client) specify what server certificate is OK.
e. "127.0.0.1:8118 192.168.100.100:443/ssl 192.168.100.200" This means, .200 can connect to .100:443. Packet will forward to :8118.
f. If you don't limit "from" connection, just remove 3rd argument like this: "127.0.0.1:8118 192.168.100.100:443/ssl"

> STEP 3:

Server: run "stone -C /path/to/stone.conf"
Android: Open app and run: "stone -C /path/to/stone.conf"

> Conclusion

Android(localhost:8888->stone=>TLS)===>===Server(:443--stone-->localhost:8118) (8118 is privoxy)

**Comment by yoursoftwarebug** [comment]
More "stone" config file sample:

> proxy/v4only 192.168.100.100:9999 -- 
> 127.0.0.1:2018 10.0.200.15:2018/udp -- 
> 127.0.0.1:2017 10.0.200.14:2017 -- 
> google.com:443 127.0.0.1:443

Line 1:
Incoming from ANY to 192.168.100.100:9999 will act as a v4only Web proxy(HTTP Proxy).

Line 2:
Packet reached to "10.0.200.15 UDP 2018" will send it to "127.0.0.1:2018 TCP".
(you can also write "127.0.0.1:2018/tcp")

Line 3:
10.0.200.14:2017 to 127.0.0.1:2017.

Line 4:
https://localhost/ will show google.com.


You must add " -- " to each line(except last one); without it stone will raise error.

I hope this help you start using it.

**Comment by yoursoftwarebug** [comment]
1. Create RootCA certificate. (we call them CAp, CAk. p as Public key, k as Private key).
e.g., CN = god.server
2. Create Server certificate signed by RootCA. SERVp, SERVk.
e.g., CN= serverman.server
3. Create Device certificate signed by RootCA. DEVp, DEVk.
e.g., CN= alice.server
4. Delete CAk - or keep it if you're planning to sign more device.

Server side config:
-dd
-z tls1
-z key=SERVk
-z cert=SERVp
-z CAfile=CAp
-z verbose
XXXX(your routing settings)XXXX


Client side config:
-dd
-q tls1
-q servername=serverman.server <---- set your server FQDN here(= signed CN)
-q key=DEVk
-q cert=DEVp
-q CAfile=CAp
-q verbose
XXXX(your routing settings)XXXX

**Comment by adminport** [comment]
Go somewhere else

https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

**Comment by moatazelmasry2** [comment]
Hi @ghost. While I really do understand your frustration as I've also been frustrated for years about the status of this software, there are now some new board members for this project and we will try our best to revive this project. I'm well aware of the security issues you mentioned and I'm currently trying to create an overview of all security related issues.

That being said, the issue you created is not really an issue, or better said, there are other issues describing the security problems more detailed. No work can be done here, so I'm closing this issue.
