### ISSUE TITLE
Unable to connect when "Do not use TLS 1.0" is checked in SoftEtherVPN Client on Windows 10

### ISSUE THREAD

**Issue by weez15** [SoftEtherVPN/SoftEtherVPN#321]
![image](https://cloud.githubusercontent.com/assets/24721459/25309771/38fd1dea-27c5-11e7-9b8f-48fd5a86a952.png)

The server side is running on debian

**Comment by MtCedarNet** [comment]
Why do you want to use SSL 3.0?

**Comment by weez15** [comment]
Oh I thought it's an option to use TLS 1.1 or higher😂
