### ISSUE TITLE
Is 'return' keyword missing?

### ISSUE THREAD

**Issue by AppChecker** [SoftEtherVPN/SoftEtherVPN#322]
Hi!

Please, look this [code fragment:](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/4df2eb4f9c2a8cf50e0123496bc20470edc21dc4/src/Cedar/Admin.c#L6742)

```
	if (c->Bridge)
	{
		return ERR_NOT_SUPPORTED;
	}
	if (t->Cert == NULL)
	{
		ERR_INVALID_PARAMETER;
	}
	if (t->Cert->is_compatible_bit == false)
	{
		return ERR_NOT_RSA_1024;
	}
```
Is 'return' keyword missing before 'ERR_INVALID_PARAMETER'?

This possible defect found by [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)

**Comment by MtCedarNet** [comment]
Thank you for reporting the problem.
I'll fix it.

**Comment by moatazelmasry2** [comment]
Yes you are right. This block in this case is useless. @GildedHonour why was this ticket closed without resolving?

**Comment by GildedHonour** [comment]
@moatazelmasry2 it'd been resolved.

**Comment by moatazelmasry2** [comment]
Ah. Thanks for the Tipp. Could you please mention these important Tips while closing a ticket? Thanks
