### ISSUE TITLE
without username and password android connection

### ISSUE THREAD

**Issue by sachinbanugariya** [SoftEtherVPN/SoftEtherVPN#324]
hello,

is it possible to connect android with vpn server, without username and password??
any other method using with i am able to connect with vpn server without username and password.

please let me know ASAP.

thanks.

**Comment by moatazelmasry2** [comment]
Sorry I didn't understand that.

Do you want to connect to SoftEther without username/password? 

or are you saying you are already able to connect so SoftEther WITHOUT username/password??

**Comment by moatazelmasry2** [comment]
OP did not answer in a while.  Closing this issue.
