### ISSUE TITLE
Project Admin Gone Holiday?

### ISSUE THREAD

**Issue by adminport** [SoftEtherVPN/SoftEtherVPN#328]
Just... The last update is half year ago but .... @dnobori twitter still working...

What gives??

**Comment by cmilanf** [comment]
He deserves a good break, but to be honest, I am also worried that the most powerful general purpose VPN software gets stalled...

**Comment by DDGo** [comment]
@dnobori Could you please look at this project a bit more? In the past seven months there have been made dozen of pull requests to further improve this project.

**Comment by adminport** [comment]
https://opensource.com/open-organization/17/4/open-leadership-softether

A summary here, but no new info.

**Comment by vampywiz17** [comment]
I hope they update it in the future... This is one of the best VPN server on the market....

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341
