### ISSUE TITLE
怎样编译才能使用radius认证呢？

### ISSUE THREAD

**Issue by JorgeLiu** [SoftEtherVPN/SoftEtherVPN#338]
windows下怎样修改编译才能使用radius认证服务？

**Comment by aicochow** [comment]
没试过radius认证

**Comment by jack2007** [comment]
代码里面会自动检测你的服务器所在的地区，如果是中国地区和日本地区，radius服务会禁用。

**Comment by moatazelmasry2** [comment]
Guys please. This is an english forum. and so most of us do not understand Chinese and hence this post is not very useful for the community. Closing
