### ISSUE TITLE
Call for development board members of this project

### ISSUE THREAD

**Issue by dnobori** [SoftEtherVPN/SoftEtherVPN#341]
I'm sorry for my late response for the planning to fork this repository.
Because of my lack of capacity, my response to pull requests for this repository has been delayed frequently.

To solve this problem, I'd like to call three (or more) new development board members.

I will grant GitHub permissions to the new members.

Development board members have:
1) Authority and responsibility to govern this project.
2) Use the brand name "SoftEther VPN" on activities for this project.
3) Commit new codes to this repository by the sole decision. (Applying new pull requests.)
4) Add new members (or dismiss existing members) to / from the board, based on the discussion and the consent of all existing board members. In other words, after three (or more) initial board members will be designated, further board members designation process will be controlled to the board members.

I'd like to designate initial three (or more) board members by self-nomination, by the end of July 2017.
Please kindly email the following application form to softether-board@softether.org if you are interested in becoming a board member.

a) Your account name on GitHub.
b) The URL of your representative Pull Requests to this repository.
c) Your comment (e.g. please describe your motivation to contribute to this project.)

(For your reference)
As I posted the plan on https://github.com/SoftEtherVPN/SoftEtherVPN/issues/268 seven months ago,
I am considering to do the following things:

1) Keep this current "SoftEtherVPN" repository without changing the repository name (to avoid confuse users by changing the URL.)
- I will call this repository as the "Modern" repository, in contrast to the "LongTerm" repository.
- I will add some board members to this repository.
- I will also be one of the board members.
- Some delegated board members will have authority to control the source code, including accepting Pull Requests.

2) Create a new conservative repository named "SoftEtherVPN_LongTerm" .
- I will be the sole maintainer of " SoftEtherVPN_LongTerm".
- I will import new feature from "SoftEtherVPN" to " SoftEtherVPN_LongTerm" manually by my decision.
- I will import bug fixes from "SoftEtherVPN" to " SoftEtherVPN_LongTerm" manually as soon as possible.
- The "Issues" and the "Pull Requests" will be hidden on the " SoftEtherVPN_LongTerm" repository.
* I took the hint from the Wireshark project. Wireshark has two branches: Wireshark (Modern) and Wireshark (Legacy). Wireshark Legacy is very conservative while the Modern is aggressive to improve its functionality.

**Comment by dnobori** [comment]
We have one candidate of eligible board members of this project for now.

I'd like to have one member's application at least. Please feel free to email the following application form to softether-board@softether.org if you are interested in becoming a board member.

**Comment by dnobori** [comment]
Currently I have received just 1 eligible new board member's self-nomination.

I still suppose that we need at least one additional nomination in order to build a solid development team.

Please kindly recommend yourself to softether-board@softether.org if you are interested in becoming a board member.

**Comment by GildedHonour** [comment]
Watashi mo to omoimasu yo.

**Comment by dnobori** [comment]
Currently I have received self-nominations for initial board members from the following three developers.

Moataz Elmasry
https://github.com/moatazelmasry2

Zulyandri Zardi
https://github.com/zulzardi

Alex Maslakov
https://github.com/GildedHonour

I'd like to listen opinions from members on this forum. Also, please feel free to email the following application form to softether-board@softether.org if you are interested in becoming one of the initial board members.

**Comment by macvk** [comment]
Can't understand why you share this project. looks like SE has big
commercial potential.

Regards.

**Comment by paulmenzel** [comment]
Here are the SoftEther VPN branches of the first two candidates.

1.  https://github.com/moatazelmasry2/SoftEtherVPN/branches
2.  https://github.com/zulzardi/SoftEtherVPN/branches

Are the candidate applications publicly visible?

@dnobori, I believe you are best to judge how the past contributions to SoftEther VPN look like. @moatazelmasry2 code and pull requests look professional. From a quick look, I’d prefer better commit messages from the other two, but that is not the most important thing.

I’d say, make the call, and don’t wait for other folks in here.

**Comment by petervnv** [comment]
I agree with @paulmenzel 

Make the call and let's get this project moving ASAP again.

**Comment by parkycai** [comment]
I've been using SoftEther since 2004. Hope this project become alive again.

**Comment by petervnv** [comment]
@dnobori  What's the current status of this issue?

Have you made a decision and relinquished commit power yet?

**Comment by dnobori** [comment]
I have already decided to fork the project to into two branches: Current-Development and Long-Term.
Right before forking the current project, I'd like to complete the unfinished job: to accept commits by many of posted pull requests which are already (or just being) reviewed and tested by myself. I suppose it will be done in few weeks. This will be last commits before forking.

**Comment by dnobori** [comment]
Currently I am on the task to merge the following pull requests. They will be merged before the forking. In some patches there are conflicts. To solve conflicts I need to study the usage of Git commands.

Using client parameter in function CtConnect
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/256

Remove blank line at the start from init file (Debian)
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/276

Stop Radius Delay from counting to next_resend
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/282

Add DH groups 2048,3072,4096 to IPSec_IKE
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/293

Add HMAC SHA2-256, HMAC SHA2-384, HMAC SHA2-512 support
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/294

Openvpn extend ciphers
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/309

Fixed RSA key bits wrong calculation for certain x509 certificate
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/313

Added support for RuToken USB key PKCS#11
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/315

OpenSSL 1.1 Port
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/344

**Comment by GildedHonour** [comment]
how are we going to work and contribute to this project? anyone may pick any issue or what? anyone among whom - any developer on github at all?

**Comment by paulmenzel** [comment]
Dear Alex,


Am 01.10.2017 um 06:41 schrieb Alex Maslakov:
> how are we going to work and contribute to this project? anyone may pick any issue or what? anyone among whom - any developer on github at all?

Well, as it’s free software, *everyone* can work on any issue they like. 
As SoftEther VPN is currently hosted on GitHub, if you have something 
that should be added to the project, you create a merge/pull request.

Then it’ll be reviewed by the still to be announced board members, and 
if it is to the liking of the board members, the changes will be 
accepted/merged.

Personally, I’ll work on Travis integration in the next weeks.


Kind regards,

Paul

**Comment by paulmenzel** [comment]
Dear Daiyuu,


Am 01.10.2017 um 06:03 schrieb Daiyuu Nobori:
> I have already decided to fork the project to into two branches: Current-Development and Long-Term.

As it has been well proven in other projects like the Linux kernel, I 
suggest to name the current development branch *master*. Regarding the 
LTS branch, I think that could be named in a variety of ways like 
*stable* or *lts*. It depends on the policy you want to have for that 
branch.

If I understand you correctly, you only want to cherry-pick commits from 
master in it, and never merge a certain state of the master branch in 
there, right? That’s kind of the Linux stable or LTS series. In that 
case, I ask you, to put the version number of SoftEther VPN in there, 
when you fork it.


Kind regards,

Paul

**Comment by GildedHonour** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341#issuecomment-327034653

**Comment by chipitsine** [comment]
@paulmenzel , there's already some travis-ci stuff: https://github.com/SoftEtherVPN/SoftEtherVPN/pull/348

(yet, it's compile only, no unit testing yet)

**Comment by moatazelmasry2** [comment]
Yes obviously everyone can contribute and create PR. The role of board members (to my understanding) is to review and merge PR.

Regarding workflow, I also prefer having the master branch as the development branch and cherry pick the good changes into a stable release. This has proven to work quite well in many projects. But also will require certain amount of work from Daiyuu

**Comment by DDGo** [comment]
@dnobori To help you, #309 is extension of #294, as the first one I mentioned has the same commits in them as in the latter pull request, hence the probable merge conflict you are talking about.

**Comment by GildedHonour** [comment]
@dnobori  who are the board members and what's their role? what tasks should they be working on now?

**Comment by petervnv** [comment]
Wow,
Surprised to see that there is still no apparent progress after all this effort

**Comment by moatazelmasry2** [comment]
@dnobori  Maybe it would be a good idea to involve the the new board members or the community in general while reviewing the Pull requests. This way everyone gets a feeling how a cooperative work in the future would look like

**Comment by dnobori** [comment]
Today, the following prominent pull requests (which are already well tested) are merged:

Using client parameter in function CtConnect
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/256

Remove blank line at the start from init file (Debian)
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/276

Stop Radius Delay from counting to next_resend
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/282

Add DH groups 2048,3072,4096 to IPSec_IKE
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/293

Add HMAC SHA2-256, HMAC SHA2-384, HMAC SHA2-512 support
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/294

Openvpn extend ciphers
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/309

Fixed RSA key bits wrong calculation for certain x509 certificate
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/313

Added support for RuToken USB key PKCS#11
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/315

OpenSSL 1.1 Port
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/344

Rest of the patches will be reviewed after the new system will be started.

**Comment by dnobori** [comment]
I decided that this repository will be the development repository and will not renamed.
The stable repository will be forked from this repository and renamed "SoftEtherVPN_LTS".

**Comment by dnobori** [comment]
@moatazelmasry2 @zulzardi @GildedHonour I submit invitations to the slack work space for OSS board member discussion to your email. Please kindly join to the work space.

**Comment by dnobori** [comment]
Today I forked the repository into two repositories:

1) Developer Edition Master Repository (this)
https://github.com/SoftEtherVPN/SoftEtherVPN/

2) Stable Edition Repository
https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/

I modified some source codes on the Developer Edition Master Repository to avoid conflict problems if the same user installed both version on the same computer. Now both version can run concurrently on the single computer.

**Comment by sonvirgo** [comment]
I think you should have been a big boss already by this valuable product

**Comment by dnobori** [comment]
I added three new board members to this project.

Moataz Elmasry (Since Nov 6, 2017)
https://github.com/moatazelmasry2

Zulyandri Zardi (Since Nov 6, 2017)
https://github.com/zulzardi

Alex Maslakov (Since Nov 6, 2017)
https://github.com/GildedHonour

The list of board members:
https://github.com/orgs/SoftEtherVPN/teams/softether-development-board-members/members

**Comment by paulmenzel** [comment]
Accessing that [last URL](https://github.com/orgs/SoftEtherVPN/teams/softether-development-board-members/members), I get a *Not found* (404) reply.

**Comment by dnobori** [comment]
@paulmenzel 
Recently I asked each of three new members to make the states to "public".
Perhaps the following URL is now correctly displayed.
https://github.com/orgs/SoftEtherVPN/teams/softether-development-board-members/members

**Comment by paulmenzel** [comment]
@dnobori, it’s still not accessible to me.
![20171115 softether_vpn](https://user-images.githubusercontent.com/9318792/32847630-d640f362-ca2a-11e7-8871-763e8a5b7a0e.png)

**Comment by dnobori** [comment]
@paulmenzel 
Sorry, the URL was wrong.
Correct one: https://github.com/orgs/SoftEtherVPN/people

**Comment by paulmenzel** [comment]
On 11/15/17 17:47, Daiyuu Nobori wrote:
> @paulmenzel
> Sorry, the URL was wrong.
> Correct one: https://github.com/orgs/SoftEtherVPN/people

Thank you, no it works.

**Comment by moatazelmasry2** [comment]
Hi guys. This task is done I believe. And if there are no objects, I'd like to close this issue within the next few days. Any objections??

**Comment by paulmenzel** [comment]
[Commit 4f23c7d0 (Added the board members list on README)][1] should have had *Fixes: #341* in its commit message, closing the and *referencing the right issue*.

In my opinion, this issue can be closed right away.

[1]: https://github.com/SoftEtherVPN/SoftEtherVPN/commit/4f23c7d08a7d38aaf0dd9c81cfa13a0ae4355b04

**Comment by sagar-chandarana** [comment]
Just wanted to thank you guys for your enthusiasm & work in this project.

**Comment by GildedHonour** [comment]
Be my guest.

El 13 de octubre de 2019 19:21:47 GMT+07:00, Sagar Chandarana <notifications@github.com> escribió:
>Just wanted to thank you guys for your enthusiasm & work in this
>project.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341#issuecomment-541413814

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
