### ISSUE TITLE
Can't connect using UDP

### ISSUE THREAD

**Issue by micromatrix14** [SoftEtherVPN/SoftEtherVPN#345]
using the VPNGATE plugin some servers support UDP, and I can choose between SSL-VPN using TCP or UDP like the picture
sometimes I add a new connection selecting one of servers in VPNGATE, but when I connect I don't have the option to select between TCP or UDP, so how can I do that, I found no option to do that even in the vpncmd
![sketch](https://user-images.githubusercontent.com/22969054/28803383-68288dd0-765c-11e7-9d2d-2ff31956e8d4.png)

**Comment by MtCedarNet** [comment]
Append '/tcp' to the server name to use TCP.
Append '/' to use UDP.

**Comment by micromatrix14** [comment]
/tcp works with me
but using UDP by appending / to the server name didn't work
just to mention, that server I'm connecting to has UDP available!!, and connect successfully when I use the VPNGATE plugin
![sketch](https://user-images.githubusercontent.com/22969054/28808065-b3f69b22-7679-11e7-8cd7-6d3f5a43bcc2.png)

**Comment by micromatrix14** [comment]
this is the same server when connected by the vpngate plugin
![sketch](https://user-images.githubusercontent.com/22969054/28808183-57a69a88-767a-11e7-9526-0ec46b940f70.png)

**Comment by MtCedarNet** [comment]
NAT-T uses DDNS name to UDP hole punching.
Please try DDNS name instead of numeric IP.

**Comment by micromatrix14** [comment]
Thank you MtCedarNet
but it still doesn't work
appending "/" to the host name like "vpn684161662.opengw.net/" didn't work and give a connection error
I tried the server name without "/" it connects but the problem comes again and uses TCP
appending /tcp is the same without /tcp
and to mention, the server support UDP

and why Softether doesn't support UDP but only if I use their DDNS, if I have my own server with UDP port already available why I need to use DDNS!!!
I mean if Softether is ALL IN ON app, this is not good to support something like that in their client!

**Comment by micromatrix14** [comment]
btw the references say, if I didn't append any thing, it will automatically search for UDP connection available, if it didn't find it, it will start using TCP
and if I out /tcp it will start using tcp even if UDP is available
but in all cases, however, I append /tcp or not, it doesn't use UDP even if it is available
only if I use the VPNGATE plugin

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by Meesmaalt** [comment]
I'm having the same issue. Cannot seem to connect with UDP. I'm successfully forwarding traffic of my mc server through TCP but another game server im trying to do required UDP and that doesnt work. 
How do i solve it?
