### ISSUE TITLE
Solved: Secure NAT, Possible to make SoftEther server following system route table?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [SoftEtherVPN/SoftEtherVPN#349]
@MtCedarNet tells the method to make this work.

```
http://ja.softether.org/4-docs/3-kb/VPNFAQ036
Virtual NAT of SoftEther VPN has 3 modes.
In Kernel-mode or RawIP-mode, the NAT uses gateway which can access google.com automatically.
In User-mode, the NAT delegates routing to the host OS.
If you want to control NAT behavior, you should use User-mode SecureNAT.

Please disable the mode you don't want to use with Virtual HUB extended option.
```

And this is the GUI way:
```
Connected via "SE-VPN Server manager" GUI
Select target Virtual Hub
Click on Properties button
Click on "Edit Virtual Hub Extended Option List" around the lower left corner
Scroll down and find "DisableKernelModeSecureNAT" and "DisableIpRawModeSecureNAT", set these values to 1
Click on "Save"
Click on "OK"
Perhaps restart your server or not. I'm not sure how does the new settings will apply.
```
**More details could found in the document just like MtCedarNet says.
Below is the original issue. And there's an image at the bottom of issue will shown the network structure if you not sure you're facing the same situation.**
 

Issue title may not clearly... What I mean is, how the network request finally come to the internet, the "exit gateway".

On my server, it has multiple gateways assigned.
I call them, "gateway 1" and "gateway 2".
The "gateway 1" is server IPv4 default gateway.
But on some IP range, "gateway 2" have higher priority(lower metric).
Gateway 1 assigned to both server and client, they're in a LAN network. 

For example, set up a SoftEther VPN server and enable Secure NAT feature,
when the VPN client connected, assigned IP address and gateway:
```client -> server gateway 1 -> Internet```

"gateway 1" is the server IPv4 default gateway.
When the client is connected, network traffic will follow gateway 1.
But I wish client traffic follow gateway 2, just like:
```client -> server gateway 2 -> Internet```

What I want is the client access the internet exactly the same as the server.
But it's not. Server always forward traffic to gateway 1.
After 2 hours Google on the web, I still not able to solve this problem.
Could anyone point me what kind of technology do I need to implement the setup?

**Comment by Raafat** [comment]
Do you have control over the gateway? Do you have a firewall?

**Comment by mhtvsSFrpHdE** [comment]
@Raafat 172.16.1.1 and 192.168.19.1 under my control, 10.3.35.1 is not. I don't have firewall set on my server or client.

**Comment by mhtvsSFrpHdE** [comment]
@Raafat Now I guess maybe SoftEther VPN Server use bridged method to access its adapter gateway. And in this situation route table settings have no effect. Same situation happen in VMware workstation bridge mode. Don't know how to deal with it though.

**Comment by Raafat** [comment]
Just to be extra clear about your situation. There are two gateways on client side, and you want SE client to interact with SE server, which is on a remote network, through the second gateway, right?

**Comment by mhtvsSFrpHdE** [comment]
@Raafat  I made an image for what I'm facing.
![image](https://user-images.githubusercontent.com/10773245/33523966-6b286de4-d84e-11e7-8db6-36f04d4be20a.png)

I'm trying to config SoftEther server to green line. So the client can utilize the "Gateway 2".
Currently, the SoftEther server only provide "Gateway 1" to client.

**Comment by mhtvsSFrpHdE** [comment]
The "Gateway 2" is not a true network adapter, it comes with a VPN connection though "Gateway 1" on the server.

**Comment by Raafat** [comment]
How does your SE client receive the IP settings?

**Comment by mhtvsSFrpHdE** [comment]
@Raafat Sorry for the comment delay. SE client receive IP via "DHCP" set on SE server. And the DHCP is enabled in
```
"Manage Virtual Hub\Virtual NAT and Virtual DHCP Server(Secure NAT)"
(Secure NAT is Enabled)
"SecureNAT Configuration\Virtual Host's Network Interface Settings"
```
Under the option tab, IP address set to 192.168.9.1 with subnet mask 255.255.255.0.
DHCP follow this address range, set to 192.168.9.10~192.168.9.200.
The "Options Applied to Clients(optional)" have values "Default Gateway Address" and "DNS Server Address 1" set to 192.168.9.1, other values keeps empty.
On the left hand side, Virtual NAT Settings is enabled with default values(MTU 1500, TCP Session Timeout 1800, UDP Session Timeout 60).
Static routing table settings is default(empty).

**Comment by mhtvsSFrpHdE** [comment]
"192.168.9.1" or "192.168.9.0" IP range doesn't exactly exist in my entire physical network(both LAN and internet). That's a unique IP range and seems became a new isolated LAN network under SE server. When more than one clients connected, they can "ping"(communication with) each other use assigned "192.168.9.x" range IP address.

**Comment by mhtvsSFrpHdE** [comment]
When the clients trying to access internet through 192.168.9.1, SE server forward the traffic to "Gateway 1" in the image shown. And I want to "Gateway 2".

The solution is imagined in here because server and client running on different OS platform. Only SE server machine support a kind of VPN protocol and server provided by someone. SE clients machine are not.
(For example, IkeV2 clients work fine on Windows but not on Android, strongSwan not work either, the same situation happened with Linux/SSTP clients,  just for a example, is not what I'm actually facing).

**Comment by MtCedarNet** [comment]
http://ja.softether.org/4-docs/3-kb/VPNFAQ036
Virtual NAT of SoftEther VPN has 3 modes.
In Kernel-mode or RawIP-mode, the NAT uses gateway which can access google.com automatically.
In User-mode, the NAT delegates routing to the host OS.
If you want to control NAT behavior, you should use User-mode SecureNAT.

Please disable the mode you don't want to use with Virtual HUB extended option.

**Comment by mhtvsSFrpHdE** [comment]
@MtCedarNet Thank you! Though I'm not able to read Japanese directly, but your answer is points out the way path. I'm going to do some test or anything else I can do.

Once I'm success I'll change the issue title for more clearly, popup the solution to the top and close issue.

Thanks again for your great help.
