### ISSUE TITLE
Implementing full RADIUS support

### ISSUE THREAD

**Issue by Omid-Shojaee** [SoftEtherVPN/SoftEtherVPN#350]
Please implement full RADIUS support into SoftEther.

**Comment by moatazelmasry2** [comment]
What do you mean about full radius support? Can you be more specific please

**Comment by moatazelmasry2** [comment]
The OP seems to be inactive. For this reason I'd like to close this issue within the next few days if there are no objections. 

Cheers

**Comment by deba12** [comment]
Assigning ip from framed-ip-address or framed-pool
radius accounting
Interim updates

**Comment by Omid-Shojaee** [comment]
SE currently supports Radius authentication only. I am requesting to add Radius accounting too.

**Comment by moatazelmasry2** [comment]
Well this is not clear from the issue description. Radius accounting is also requested in Issue #101 . 
I'd like to close this ticket as a duplicate.
