### ISSUE TITLE
Change Server Protocol from UDP to TCP

### ISSUE THREAD

**Issue by anwareset** [SoftEtherVPN/SoftEtherVPN#351]
How to change the server protocol from UDP to TCP protocol?

thank you

**Comment by moatazelmasry2** [comment]
What do you mean by server protocol? SoftEther supports both TCP and UDP connections. 

If you are using vpngate and you append "/tcp" to the server's name it will connect using tcp. 

Does this answer your question?

**Comment by youxiaojie** [comment]
I prefer to UDP than TCP because of NAT and firewalls

**Comment by moatazelmasry2** [comment]
OP did not answer in a while.  Closing this issue.
