### ISSUE TITLE
Problem with osx client

### ISSUE THREAD

**Issue by lrk** [SoftEtherVPN/SoftEtherVPN#352]
Hello,

i'm currently trying to use Softether in client mode on OSX and i encounter some problems.

My company use a cloud service managed by another company, and they offer a VPN over SSL access.
I have a windows configuration guide, it work well.
My workstation is under macos sierra, and i need to connect to this VPN.

I have tried with tunnelblick but the connection failed on authentication.

I download the osx version of softether but i didn't manage to get it work:
- it seem that i can't use the exported configuration from the windows version (V4.22 build 9634), the osx client move it directly in backup conf and start with an empty one.
- the remote vpn server don't respond to ping/icmp and the vpncmd client configuration can't reach the remote client (it seem that it has to ping the remote server to go to the next configurations steps). I havent found any command line option to override that. 

Any suggestions ?

**Comment by lrk** [comment]
Any news ?

**Comment by lrk** [comment]
@dnobori: do you have some ideas about this problem ?

**Comment by sonvirgo** [comment]
I use sstp-client flawless

**Comment by aicochow** [comment]
VPN Client for Mac OS X is not recommended to use.
Please use native Mac OS vpn

**Comment by sonvirgo** [comment]
You have to use sstp in case ISP block udp 500 and other VPN ports

**Comment by lrk** [comment]
@aicochow well as i said, this is for an SSL vpn, not supported by osx native vpn client
