### ISSUE TITLE
One spammer: 12000 posts on the forums - when will it be fixed or get a moderator.

### ISSUE THREAD

**Issue by fenice2** [SoftEtherVPN/SoftEtherVPN#353]
By the time you read this, one forum user will have posted 12,000 (or more) spam messages on these forums - take a look here: http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=16212 FYI, that's about 25% of all the posts on these forums!

I've commented many times on the dire situation of these forums and nothing ever gets done about the rubbish, illegal content and downright junk all over the forums. If anyone thinks that spam, or spammers, ever  gets removed they are deluding themselves.

My last forum post on this topic is here: http://www.vpnusers.com/viewtopic.php?f=14&t=26978 - forty-odd views and no comments 

The University of Tsukuba has it's name and logo all over the site, does it approve of the state of the forums and does it want to been seen to be approving of the products that are littering the forums? It's a shame that such a prestigeous organisation doesn't do something about the state of these forums.

As I've mentioned in the thread, I care that these forums are in a fit state for users to visit, ask questions and get answer - what not acceptable is that the forums are covered in rubbish spam post advertising and selling all kinds of junk - this should be stopped as soon as possible. These forums do not do the reputation of SoftEther, the University of Tsukuba or the developer any favours. Please do something

Sadly, I expect this post to go down the same black hole as all the other comments about the state of the forums.

**Comment by dnobori** [comment]
Recently we deleted most of SPAM posts and upgraded the forum system. However, it is a cat-and-mouse game. Need to solve the forum problem fundamentally.

**Comment by fenice2** [comment]
Yes, I noticed when the forums were upgraded and the prolific spammer was deleted - that was a job well done and quick. :)

I don't really think that most of the spam (or spammers) gets deleted, if you look at the link above for my forum thread on this topic and click on some of the links there you'll see that most of those users have not been banned and therefore the posts are still visible on the internet and one of those has two thousand plus posts.

I do understand the problem as I have been a moderator on a fairly large/busy forum for the past twelve years. They also use phpbb and we get between one and ten posts a month, there are good plugins for the forum software that will keep most of the spammers away.

I have said this before but if you need additional help moderating the forums then I'm willing to help.

Thanks again for this great software and I'm looking forward to the project moving forward with the upcoming 'fork', that's a brave and exciting change and if the forums are cleaned it wiil be more welcoming to new users.

**Comment by moatazelmasry2** [comment]
Hi guys. Thanks for the info. Can we close this issue?

**Comment by moatazelmasry2** [comment]
Also one more remark. @dnobori please give on the forum admin rights to some trusted users and allow them to ban people who post even one spam message

**Comment by fenice2** [comment]
It would be useful to have more admins, at least they could cover different timezones and hopefully catch a few more spammers. My additional 2c worth, it would also be helpful if we had some timeline to improvements to the forum software with regards to implementing some of the plug-ins for catching spammers i.e.: stopforumspam; don't let members add signatures without a minimum number of forum posts.

I will say this again, most of the spammers that I report don't get removed and are still visible on the forums. For a welcoming, helpful and open forum this spam problem needs addressing as soon as possible.

As far as I'm concerned this issue can be closed.

BTW, @moatazelmasry2 - you're doing a great job of filling up my mailbox with all this hard work you're doing on these issues. :)

**Comment by moatazelmasry2** [comment]
@fenice2 thanks for your kind words. Hopefully it will become better soon
with the forum situation
