### ISSUE TITLE
Can not connect from Ubuntu 17.04

### ISSUE THREAD

**Issue by dungtv543** [SoftEtherVPN/SoftEtherVPN#356]
Hi, 
I have a problem when connect from my Ubuntu PC to my L2TP Preshare Key SoftEtherVPN server.
When i capture traffic and only have:
![image](https://user-images.githubusercontent.com/5428817/31714606-2c437c50-b42b-11e7-9093-0e70315d5430.png)
but on windows 10 machine is successful.
I hope you can help me. 
Thank you very much!
------
Ps: Syslog is:

`Oct 18 17:43:42 DutasWorld NetworkManager[863]: <info>  [1508323422.6886] audit: op="connection-activate" uuid="105d45cf-e739-4609-827b-b9f6acab464a" name="VPN" pid=13192 uid=1000 result="success"
Oct 18 17:43:42 DutasWorld NetworkManager[863]: <info>  [1508323422.7022] vpn-connection[0x560d3b5af100,105d45cf-e739-4609-827b-b9f6acab464a,"VPN",0]: Started the VPN service, PID 15650
Oct 18 17:43:42 DutasWorld NetworkManager[863]: <info>  [1508323422.7229] vpn-connection[0x560d3b5af100,105d45cf-e739-4609-827b-b9f6acab464a,"VPN",0]: Saw the service appear; activating connection
Oct 18 17:43:43 DutasWorld kernel: [12087.443871] NOHZ: local_softirq_pending 80
Oct 18 17:43:43 DutasWorld nm-l2tp-auth-di[15659]: GtkDialog mapped without a transient parent. This is discouraged.
Oct 18 17:43:43 DutasWorld hud-service[2377]: #033[31mvoid DBusMenuImporter::slotGetLayoutFinished(QDBusPendingCallWatcher*)#033[0m: "No such interface 'com.canonical.dbusmenu' on object at path /org/ayatana/bamf/window/79691784"
Oct 18 17:43:44 DutasWorld kernel: [12088.403851] NOHZ: local_softirq_pending 80
Oct 18 17:43:44 DutasWorld kernel: [12088.883773] NOHZ: local_softirq_pending 80
Oct 18 17:43:48 DutasWorld kernel: [12092.483483] NOHZ: local_softirq_pending 80
Oct 18 17:43:48 DutasWorld NetworkManager[863]: <info>  [1508323428.4341] keyfile: update /etc/NetworkManager/system-connections/VPN-105d45cf-e739-4609-827b-b9f6acab464a (105d45cf-e739-4609-827b-b9f6acab464a,"VPN")
Oct 18 17:43:48 DutasWorld NetworkManager[863]: <info>  [1508323428.4526] vpn-connection[0x560d3b5af100,105d45cf-e739-4609-827b-b9f6acab464a,"VPN",0]: VPN connection: (ConnectInteractive) reply received
Oct 18 17:43:48 DutasWorld nm-l2tp-service[15650]: Check port 1701
Oct 18 17:43:48 DutasWorld nm-l2tp-service[15650]: Can't bind to port 1701
Oct 18 17:43:48 DutasWorld NetworkManager[863]: Stopping strongSwan IPsec failed: starter is not running
Oct 18 17:43:50 DutasWorld NetworkManager[863]: Starting strongSwan 5.5.1 IPsec [starter]...
Oct 18 17:43:50 DutasWorld NetworkManager[863]: Loading config setup
Oct 18 17:43:50 DutasWorld NetworkManager[863]: Loading conn '105d45cf-e739-4609-827b-b9f6acab464a'
Oct 18 17:43:50 DutasWorld NetworkManager[863]: found netkey IPsec stack
Oct 18 17:43:50 DutasWorld charon: 00[DMN] Starting IKE charon daemon (strongSwan 5.5.1, Linux 4.10.0-37-generic, x86_64)
Oct 18 17:43:50 DutasWorld charon: 00[CFG] loading ca certificates from '/etc/ipsec.d/cacerts'
Oct 18 17:43:50 DutasWorld charon: 00[CFG] loading aa certificates from '/etc/ipsec.d/aacerts'
Oct 18 17:43:50 DutasWorld charon: 00[CFG] loading ocsp signer certificates from '/etc/ipsec.d/ocspcerts'
Oct 18 17:43:50 DutasWorld charon: 00[CFG] loading attribute certificates from '/etc/ipsec.d/acerts'
Oct 18 17:43:50 DutasWorld charon: 00[CFG] loading crls from '/etc/ipsec.d/crls'
Oct 18 17:43:50 DutasWorld charon: 00[CFG] loading secrets from '/etc/ipsec.secrets'
Oct 18 17:43:50 DutasWorld charon: 00[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-105d45cf-e739-4609-827b-b9f6acab464a.secrets'
Oct 18 17:43:50 DutasWorld charon: 00[CFG]   loaded IKE secret for %any
Oct 18 17:43:50 DutasWorld charon: 00[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-8b0a4919-8392-48bf-ba94-a0bce414d5a9.secrets'
Oct 18 17:43:50 DutasWorld charon: 00[CFG]   loaded IKE secret for %any
Oct 18 17:43:50 DutasWorld charon: 00[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-a007f8d4-7b99-4b74-bd63-635a2ee0540c.secrets'
Oct 18 17:43:50 DutasWorld charon: 00[CFG]   loaded IKE secret for %any
Oct 18 17:43:50 DutasWorld charon: 00[LIB] loaded plugins: charon test-vectors aesni aes rc2 sha2 sha1 md4 md5 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem openssl fips-prf gmp agent xcbc hmac ccm gcm attr kernel-netlink resolve socket-default connmark stroke updown eap-mschapv2 xauth-generic
Oct 18 17:43:50 DutasWorld charon: 00[LIB] dropped capabilities, running as uid 0, gid 0
Oct 18 17:43:50 DutasWorld charon: 00[JOB] spawning 16 worker threads
Oct 18 17:43:50 DutasWorld charon: 09[CFG] received stroke: add connection '105d45cf-e739-4609-827b-b9f6acab464a'
Oct 18 17:43:50 DutasWorld charon: 09[CFG] added configuration '105d45cf-e739-4609-827b-b9f6acab464a'
Oct 18 17:43:51 DutasWorld charon: 04[CFG] rereading secrets
Oct 18 17:43:51 DutasWorld charon: 04[CFG] loading secrets from '/etc/ipsec.secrets'
Oct 18 17:43:51 DutasWorld charon: 04[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-105d45cf-e739-4609-827b-b9f6acab464a.secrets'
Oct 18 17:43:51 DutasWorld charon: 04[CFG]   loaded IKE secret for %any
Oct 18 17:43:51 DutasWorld charon: 04[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-8b0a4919-8392-48bf-ba94-a0bce414d5a9.secrets'
Oct 18 17:43:51 DutasWorld charon: 04[CFG]   loaded IKE secret for %any
Oct 18 17:43:51 DutasWorld charon: 04[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-a007f8d4-7b99-4b74-bd63-635a2ee0540c.secrets'
Oct 18 17:43:51 DutasWorld charon: 04[CFG]   loaded IKE secret for %any
Oct 18 17:43:51 DutasWorld charon: 06[CFG] received stroke: initiate '105d45cf-e739-4609-827b-b9f6acab464a'
Oct 18 17:43:51 DutasWorld charon: 02[IKE] initiating Main Mode IKE_SA 105d45cf-e739-4609-827b-b9f6acab464a[1] to 10.4.19.51
Oct 18 17:43:51 DutasWorld charon: 02[ENC] generating ID_PROT request 0 [ SA V V V V V ]
Oct 18 17:43:51 DutasWorld charon: 02[NET] sending packet: from 10.3.51.5[500] to 10.4.19.51[500] (240 bytes)
Oct 18 17:43:53 DutasWorld kernel: [12097.550989] NOHZ: local_softirq_pending 80
Oct 18 17:43:53 DutasWorld kernel: [12097.585455] intel_powerclamp: Stop forced idle injection
Oct 18 17:43:55 DutasWorld charon: 10[IKE] sending retransmit 1 of request message ID 0, seq 1
Oct 18 17:43:55 DutasWorld charon: 10[NET] sending packet: from 10.3.51.5[500] to 10.4.19.51[500] (240 bytes)
Oct 18 17:44:01 DutasWorld NetworkManager[863]: Stopping strongSwan IPsec...
Oct 18 17:44:01 DutasWorld charon: 00[DMN] signal of type SIGINT received. Shutting down
Oct 18 17:44:01 DutasWorld charon: 00[IKE] destroying IKE_SA in state CONNECTING without notification
Oct 18 17:44:01 DutasWorld NetworkManager[863]: initiating Main Mode IKE_SA 105d45cf-e739-4609-827b-b9f6acab464a[1] to 10.4.19.51
Oct 18 17:44:01 DutasWorld NetworkManager[863]: generating ID_PROT request 0 [ SA V V V V V ]
Oct 18 17:44:01 DutasWorld NetworkManager[863]: sending packet: from 10.3.51.5[500] to 10.4.19.51[500] (240 bytes)
Oct 18 17:44:01 DutasWorld NetworkManager[863]: sending retransmit 1 of request message ID 0, seq 1
Oct 18 17:44:01 DutasWorld NetworkManager[863]: sending packet: from 10.3.51.5[500] to 10.4.19.51[500] (240 bytes)
Oct 18 17:44:01 DutasWorld NetworkManager[863]: destroying IKE_SA in state CONNECTING without notification
Oct 18 17:44:01 DutasWorld nm-l2tp-service[15650]: g_dbus_method_invocation_take_error: assertion 'error != NULL' failed
Oct 18 17:44:01 DutasWorld NetworkManager[863]: <info>  [1508323441.7180] vpn-connection[0x560d3b5af100,105d45cf-e739-4609-827b-b9f6acab464a,"VPN",0]: VPN service disappeared
Oct 18 17:44:01 DutasWorld NetworkManager[863]: <warn>  [1508323441.7195] vpn-connection[0x560d3b5af100,105d45cf-e739-4609-827b-b9f6acab464a,"VPN",0]: VPN connection: failed to connect: 'Message recipient disconnected from message bus without replying'
Oct 18 17:44:06 DutasWorld gnome-terminal-[15577]: Allocating size to GtkBox 0x55feb7f08880 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Oct 18 17:44:18 DutasWorld gnome-terminal-[15577]: message repeated 14 times: [ Allocating size to GtkBox 0x55feb7f08880 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?]
Oct 18 17:44:47 DutasWorld gnome-screensho[15749]: Unable to select area using GNOME Shell's builtin screenshot interface, resorting to fallback X11.
`

**Comment by moatazelmasry2** [comment]
In your log there is the error message:
`Can't bind to port 1701`
Please make sure that from your client you are able to reach the server on this port
