### ISSUE TITLE
Ubuntu ppa - version problem

### ISSUE THREAD

**Issue by vampywiz17** [SoftEtherVPN/SoftEtherVPN#358]
Hello there,

This PPA Compile on ubuntu release, but it has a version problem.

https://github.com/SoftEtherVPN/SoftEtherVPN/issues/37

PPA: https://launchpad.net/~paskal-07/+archive/ubuntu/softethervpn

**Comment by vampywiz17** [comment]
The problem is still exist. it is possible to fix it?

**Comment by moatazelmasry2** [comment]
As far as I know, SoftEtherVPN project has nothing to do with this Ubuntu PPA. Please contact the maintainer "Dmitry Verkhoturov" of this PPA for further questions

**Comment by davidebeatrici** [comment]
@paskal Our current version is `5.01.9659`, but on the PPA repository it's `5.01.9662`.

**Comment by paskal** [comment]
It's because once you've sent some version to launchpad, you can't reupload it for rebuild and only way is forward. I hope softether vpn will close the gap someday, I can't revert version in PPA now.
Status is won't fix for now.

**Comment by davidebeatrici** [comment]
No problem, we will close the gap as soon as possible.

**Comment by chipitsine** [comment]
I noticed that launchpad is newer :)

**Comment by chipitsine** [comment]
we are going to release next week. we can take, for example, 5.01.9663

**Comment by davidebeatrici** [comment]
We should get on par with the stable repository, which is currently at build `9669`.

**Comment by chipitsine** [comment]
I doubt we should take numbers from stable repo. it has its own release cycle. even if we set 9669 next week, what we have to pick for the next release?

**Comment by davidebeatrici** [comment]
Let's ask @dnobori.

**Comment by paskal** [comment]
Yes, this issue have nothing to do with this very repo.
