### ISSUE TITLE
Fetch available ciphers list from server

### ISSUE THREAD

**Issue by DDGo** [SoftEtherVPN/SoftEtherVPN#360]
The new Softether version release supposedly had DHE-RSA-CHACHA 20-POLY 1305 and ECDHE-RSA-CHACHA 20-POLY 1305 support. After compiling the soure code with OpenSSL 1.1.0f I didnt get an option to select it in the server manager afterwards. It was a fresh Ubuntu 16.04 Server install.

Maybe support for it is still not in the server itself or its manager?

**Comment by dnobori** [comment]
I checked the code and found that the encryption candidate list is not fetched from the server, but using the suppoert list of the manager-side.

This is not a good, and I am considering to add a new RPC to fetch the support cipher list from the running server to list on the UI and vpncmd.

**Comment by DDGo** [comment]
Any update regarding this? I still don't have an option to update this, other then to try manually. But even this does not work, as the client simply refuses to use the new CHACHA 20-POLY 1305 encryption options.

**Comment by StevenDoesStuffs** [comment]
Bump. Would like to use chacha20. Its much faster than AES.

**Comment by Dreyk007** [comment]
for me it is also important

**Comment by TheBoroer** [comment]
I'd like to see this too.
@DDGo how would I set it manually? Edit the vpn_server.config file and set the cipher line like:
`string CipherName DHE-RSA-CHACHA 20-POLY 1305`?

**Comment by DDGo** [comment]
Yes, but it doesn't work if you manually edit the config file. The Softether client simply refuses to use the cipher and uses another one.

**Comment by TheBoroer** [comment]
Yup you're right. I tried it with L2TP/IPsec (with the built in windows client), it just uses AES 128 instead.

**Comment by davidebeatrici** [comment]
> This is not a good, and I am considering to add a new RPC to fetch the support cipher list from the running server to list on the UI and vpncmd.

Done in #852.
