### ISSUE TITLE
compile  warning "implicit declaration" when compile Console.c and BridgeUnix.c solved

### ISSUE THREAD

**Issue by youxiaojie** [SoftEtherVPN/SoftEtherVPN#362]
I am a freshman. and when I compile the source code with raspbian I found the warning "implicit declaration" one is without function declaration, one is without proper functional compiling.I fix it.

commit 975debfed4413464492f5d93b016abeb67be1126
Author: You Xiaojie <yxj790222@163.com>
Date:   Sat Oct 21 16:19:20 2017 +0800

    Resolve "Implicit declaration of function warning" when compiling Console.c and BridgeUnix.c

diff --git a/src/Cedar/BridgeUnix.h b/src/Cedar/BridgeUnix.h
index 7f9b089..4ba495d 100644
--- a/src/Cedar/BridgeUnix.h
+++ b/src/Cedar/BridgeUnix.h
@@ -186,6 +186,7 @@ struct CAPTUREBLOCK{
 
 
 // Function prototype
+void FreeTap(VLAN *v);
 void InitEth();
 void FreeEth();
 bool IsEthSupported();
diff --git a/src/Cedar/Console.c b/src/Cedar/Console.c
index ba2ec28..21c5e2a 100644
--- a/src/Cedar/Console.c
+++ b/src/Cedar/Console.c
@@ -2048,7 +2048,13 @@ bool PasswordPrompt(char *password, UINT size)
                else if (c == 0xE0)
                {
                        // Read one more character
+
+#ifdef OS_WIN32
                        c = getch();
+#else  // OS_WIN32
+                       c = getc(stdin);
+#endif // OS_WIN32
+
                        if (c == 0x4B || c == 0x53)
                        {
                                // Backspace

**Comment by vampywiz17** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/281

**Comment by paskal** [comment]
#281 merged now, please test again.

**Comment by youxiaojie** [comment]
it seems like #281 refers to arm64 platform, is none of business with my patch, I compile on x86 linux,  armhf raspbian, both are show these errors~~ so I looked for source code, find these two errors. conditional compile codes is taken from context, functional declaration is to track to define of function and add then declaration by myself.

**Comment by paskal** [comment]
Could you please prepare a merge request with your commit then? It will greatly increase the chance of this fix going into upstream.

**Comment by youxiaojie** [comment]
sure
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/363

**Comment by youxiaojie** [comment]
I am excited if my code will be accepted~

**Comment by davidebeatrici** [comment]
Fixed in #632.
