### ISSUE TITLE
4.23 - OpenVPN mode does not work properly

### ISSUE THREAD

**Issue by PtDragon** [SoftEtherVPN/SoftEtherVPN#364]
4.22 - all works as expected
4.23 - SSTP works as expected but OpenVPN cannot connect and also removes IP from bridged tap adapter on server side(which breaks all vpn connections).
Most possibly on connecto of OpenVPN client tap adapter does reset/recreate.

**Comment by dnobori** [comment]
Thank you for your report. I fixed the bug.
http://www.softether.org/5-download/history

**Comment by PtDragon** [comment]
Thanks  a lot! I confirm it is fixed now!
