### ISSUE TITLE
Native Windows VPN not working with SoftEther VPN server

### ISSUE THREAD

**Issue by cdcseacave** [SoftEtherVPN/SoftEtherVPN#366]
I can successfully connect to the server using your client, but no matter how I try to connect with the native Windows VPN client it fails with the error:
`The PPP link control protocol was terminated.`
I am using the client on Windows 10 x64 16299.

Thank you!

**Comment by sonvirgo** [comment]
In correct config, See this [Azure VPN](https://www.youtube.com/watch?v=ckOaaWfUczU)

**Comment by cdcseacave** [comment]
That connects indeed, thank you, but the speed is incredibly slow, somewhere around 1kbps. I imagine it is caused by not using a direct connection, while your client somehow manages to get a direct connection after establishing the connection through Azure server. Is there any solution for that?

**Comment by sonvirgo** [comment]
check your setup 
http://oi67.tinypic.com/2rxbjg0.jpg

**Comment by cdcseacave** [comment]
not sure what you mean
on the same machine the connection established by the SoftEtherVPN client is much faster than the connection established by native Windows 10 VPN client
what do you want me to check?

**Comment by sonvirgo** [comment]
You said 1kbps in correct. See, that 500kbps. SoftEther client got better is clearly mention in the manual. Why do you siad you can not use Native Windows, also 1kbps. So what do you want?

**Comment by cdcseacave** [comment]
I am sorry I do not understand your English.

**Comment by sonvirgo** [comment]
I am sorry for my bad English. 
In short. Native SSTP Windows client is lower in throughput because it run over SSL. But it can reach reasonable speed. Sstp can bypass all blockage of other VPN protocol

**Comment by aicochow** [comment]
I tested the speed, no problem

**Comment by renatosc** [comment]
I was getting that problem and for my was related to the authentication. When I set the username to be : user@MY_VPN_HUB_NAME  I get that error ("The PPP link control protocol was terminated."). But if I use the username as just "user" (without the VPN Hub name) it connects without problem.
