### ISSUE TITLE
[Question] Multi-Factor Authentication Support

### ISSUE THREAD

**Issue by roniemartinez** [SoftEtherVPN/SoftEtherVPN#368]
Hi,

Does SoftEther support multi-factor authentication? If not, are there plans to support this feature?

Cheers!

**Comment by Raafat** [comment]
I support your suggestion.

**Comment by demon-ru** [comment]
I need authorization via a simple call external scripts. It is possible, for example, in OpenVPN.
And very frustrating when I have to deploy Radius for this simple task.

So it would be very nice if these or other scripts could convey the desired network settings (client IP, routes).

**Comment by diev** [comment]
Using free https://freeotp.github.io/ might be excellent!

**Comment by nanet-pl** [comment]
This would be nice functionality, is there any chance to push it further?

**Comment by domosekai** [comment]
MFA solutions usually speak Radius with VPN servers. SoftEther already works with Radius.
