### ISSUE TITLE
Launchpad PPA with daily builds

### ISSUE THREAD

**Issue by paskal** [SoftEtherVPN/SoftEtherVPN#37]
I've created  [a PPA](https://launchpad.net/~paskal-07/+archive/softethervpn) which takes code from github and builds new versions of SoftEther VPN if there is any changes since last build. To use the ppa:

```
sudo apt-add-repository ppa:paskal-07/softethervpn
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install softether-vpnserver
```

I'll be glad if Daiyuu Nobori include that information in README install section and, maybe, in documentation. Deb package builds from this very repository with rules from DEBIAN directory - if you'll need any additional info - contact me by email paskal.07@gmail.com

**Comment by hongquan** [comment]
Thanks, @paskal. Could you please produce more update?

**Comment by paskal** [comment]
@hongquan, it's updated daily, just the version number is crippled because it's never updated in the code.

**Comment by vampywiz17** [comment]
Hi @paskal . Now the code id updated. it will be update on your PPA?

**Comment by paskal** [comment]
I'll swap it now, aarch64 will break as a result of unmerged #281.

**Comment by vampywiz17** [comment]
> I'll swap it now, aarch64 will break as a result of unmerged #281.

Thanks.

I think some problem with versioning right?

It say: 4.04.9412

But the correct one: v4.23-9647

**Comment by paskal** [comment]
It could be corrected only in this repository by @dnobori but he never did it before. You should open a separate issue and ask him update build files versions as well when he does new release, probably.

**Comment by meramsey** [comment]
In case someone else stumbles on this these are in latest Ubuntu/Debian default repos
https://packages.ubuntu.com/jammy/softether-vpnserver
