### ISSUE TITLE
Multiple IP / network interfaces

### ISSUE THREAD

**Issue by cjconstante** [SoftEtherVPN/SoftEtherVPN#371]
There is any option to listen in all interfaces?
I need to create clients that can connect to any network interface or to any specific interface. How can i do that?

**Comment by macvk** [comment]
vpn server listens on every interface by default. every interface on the server musts have an unique IP. please explain what is your problem?

**Comment by cjconstante** [comment]
The problem is this:
The server has several interfaces: eth0, eht1, eth2, etc. When the users get connected to the vpn on any interface, the always browse the internet with the ip from eth0.

I am not sure about the server listen in all the interfaces, when I do a netstat only I see the ports opened to eth0 instead 0.0.0.0 or each interface.

--
Cristian Constante

**Comment by domosekai** [comment]
It's already listening on all interfaces by default.
