### ISSUE TITLE
android vpn not working after build 9651 upgrade

### ISSUE THREAD

**Issue by vinchu** [SoftEtherVPN/SoftEtherVPN#372]
SoftEther VPN 4.24 Build 9651 Beta (October 23, 2017)
tested on both windows and ubuntu

I have upgraded to this and all android inbuilt VPN clients are not working now...it is saying unsuccessful

MacOS and iOS are working

the login is not even hitting the server logs.

any clues?

**Comment by siomiz** [comment]
The error seems to be:
> The client denied to accept both the "PAP" (Password Authentication Protocol, a clear-text password authentication protocol) and MS-CHAP v2 Protocol. Enable either PAP or MS-CHAP v2 on the client-side and retry.

User reports that 9634 works fine.

According to [some forum posts](https://community.ubnt.com/t5/EdgeMAX/Cannot-connect-to-L2TP-IPSec-from-Android/td-p/1527099) Android doesn't use MS-CHAPv2 unless required by the server.

**Comment by moatazelmasry2** [comment]
Are you trying L2TP or which protocol?

**Comment by Khsed4** [comment]
@moatazelmasry2  I am trying to implement an l2TP IPsec VPN for application for Android can I use this project if yes please send me some resources.

**Comment by moatazelmasry2** [comment]
@Khsed4 There are already man L2TP Apps for Android and they can connect to SoftEtherVPN

**Comment by Khsed4** [comment]
@moatazelmasry2, thanks, man, can you describe more how can I use SoftEtherVPN project to implement my own VPN, thanks in advance.

**Comment by moatazelmasry2** [comment]
What do you mean own VPN? Client or Server?

Anyways this is not an easy task to implement own VPN Server like SoftEther
or strongswan. Of course you can look at the source code and copy many
classes/headers. Why do you want to do that anyway??

**Comment by Khsed4** [comment]
I mean my company need an android application to run on smartphone and yes we have our server, the app only needs to connect to the server and create a tunnel to connect it, so how should I start and would you mind give which folder I need to use in my project and I know JAVA do I need to know another programming language or no ?Thanks for your response , you are gonna solve  a great problem of me

**Comment by moatazelmasry2** [comment]
There are many OpenVPN and L2TP android apps. Why don't you use any of them?

**Comment by weidi** [comment]
So i have the same issue but only on Android 8.1 Beta on a Nexus 5X. When testing from a Galaxy S8 running 7.0 it´s working fine. I built 9647 
There is an issue open in the Android Bugtracker https://issuetracker.google.com/issues/66537566 stating that it´s not working since 8.0. What Version are you running?

**Comment by Khsed4** [comment]
@weidi Do you use the SoftEther project programmatically(codes) or you set up your VPN  from android VPN settings?

**Comment by weidi** [comment]
I use SoftEther as L2TP/IPSec Server and use the builtin VPN Client in android. so i dont use any code from the SE Repo for my own Android Client

**Comment by Khsed4** [comment]
@weidi Do you have any idea how create an android app to connect to our own server?

**Comment by weidi** [comment]
@Khsed4 no and i actually like the onboard functionality so i don´t have to bring anything on the System

**Comment by moatazelmasry2** [comment]
@Khsed4 Your questions are not relevant at all to the issue. Please do not hijack this issue.

**Comment by davidebeatrici** [comment]
Superseded by #571.
