### ISSUE TITLE
I can't find linux gui client

### ISSUE THREAD

**Issue by tidatida** [SoftEtherVPN/SoftEtherVPN#374]
I am a super fan of this great project,  I use this and read the code for a long time .  Of course this project is awesome, but it not  as easy  as most other mobile applications, mobile app always user friendly,  The client  is  more difficult to use  in linux. So I am wondering : if a gui client for linux in the development roadmap?  Thx.

**Comment by aicochow** [comment]
vpn server manager should be manage by web browser

**Comment by moatazelmasry2** [comment]
Nop. Unfortunately there is no GUI client for Linux and it is not on a roadmap. Only  the standard linux VPN clients like OpenVPN or L2TP. 

If you are talking about managing SoftEther, one solution is to use vpncmd:
https://www.softether.org/4-docs/1-manual/2._SoftEther_VPN_Essential_Architecture/2.6_VPN_Command_Line_Management_Utility_(vpncmd)

I will close this issue, since there's nothing to do here for now.

Cheers,
Moataz

**Comment by tenten8401** [comment]
Just wanted to throw this out here, the client and server manager both work flawlessly under Wine in Linux.

**Comment by bmpezzi** [comment]
> Just wanted to throw this out here, the client and server manager both work flawlessly under Wine in Linux.
> ![image](https://user-images.githubusercontent.com/6174343/33621993-8d1a718c-d9ba-11e7-9d60-ee9d1aacf361.png)
> 
> For VPN connectivity, I use `networkmanager-sstp` to connect to SoftEther.

Can you still use it on wine?
I tried it, made it run, but it breaks when I start the first configuration I get this error:

Unhandled exception: page fault on read access to 0x00000000 in 64-bit code (0x0000000140221259).Register dump:rip:0000000140221259 rsp:000000000022eb90 rbp:000000000022ffd0 eflags:00010206 (  R- --  I   - -P- )rax:0000000000000000 rbx:0000000000000008 rcx:0000000001e57500 rdx:0000000000000010rsi:00007fffffea8000 rdi:0000000140000000  r8:0000000001fa0000  r9:0000000001e60000 r10:0000000000000002r11:0000000001e57560 r12:0000000000000000 r13:0000000000000000 r14:0000000000000000 r15:0000000000000000Stack dump:0x000000000022eb90:  0000000000000000 00000000000000000x000000000022eba0:  0000000000000000 00000000000000000x000000000022ebb0:  0000000000000000 00000000000000000x000000000022ebc0:  0000000000000000 0000000001e575000x000000000022ebd0:  0000000000000000 00000000000000000x000000000022ebe0:  0000000000000000 00000000000000000x000000000022ebf0:  0000000000000000 00000000000000000x000000000022ec00:  0000000000000000 00000000000000000x000000000022ec10:  0000000001e574e8 00000000006900e80x000000000022ec20:  000000000022ed50 000000007bc6a1140x000000000022ec30:  0000000000000000 00000000000000000x000000000022ec40:  0000000000000000 0000000000000000Backtrace:=>0 0x0000000140221259 in driver_installer (+0x221259) (0x000000000022ffd0)1 0x0000000140221107 in driver_installer (+0x221106) (0x000000000022ffd0)2 0x000000014021c993 in driver_installer (+0x21c992) (0x000000000022ffd0)3 0x000000014021c81d in driver_installer (+0x21c81c) (0x000000000022ffd0)4 0x000000014000112c in driver_installer (+0x112b) (0x000000000022ffd0)5 0x00000001400014a2 in driver_installer (+0x14a1) (0x000000000022ffd0)6 0x00000001400015a9 in driver_installer (+0x15a8) (0x000000000022ffd0)7 0x00000001403c3267 in driver_installer (+0x3c3266) (0x000000000022ffd0)8 0x000000007b456bce __wine_start_process+0x3bd() in kernel32 (0x000000000022ffd0)0x0000000140221259: movl	(%rax),%eaxModules:Module	Address					Debug info	Name (125 modules)PE	         10c0000-         10de000	Deferred        dwmapiPE	         10e0000-         1752000	Deferred        msiPE	         1760000-         1816000	Deferred        wintrustPE	        61d00000-        61d43000	Deferred        sxsPE	        61f40000-        61f63000	Deferred        wtsapi32PE	        62140000-        621dc000	Deferred        uxthemePE	        62580000-        625b2000	Deferred        mspatchaPE	        62600000-        626ef000	Deferred        usp10PE	        62740000-        62772000	Deferred        imagehlpPE	        63100000-        6311b000	Deferred        newdevPE	        637c0000-        63942000	Deferred        winmmPE	        64940000-        64988000	Deferred        shcorePE	        65000000-        655ab000	Deferred        ole32PE	        65780000-        6579f000	Deferred        versionPE	        66440000-        664a7000	Deferred        msacm32PE	        68a40000-        68b71000	Deferred        shlwapiPE	        69c80000-        69c8f000	Deferred        icmpPE	        6a100000-        6a545000	Deferred        oleaut32PE	        6a700000-        6a8d3000	Deferred        setupapiPE	        6acc0000-        6acd2000	Deferred        psapiPE	        6b2c0000-        6b4c5000	Deferred        wininetPE	        6b6c0000-        6b914000	Deferred        comdlg32PE	        6bec0000-        6bf0c000	Deferred        imm32PE	        6d9c0000-        6da19000	Deferred        mprPE	        6dfc0000-        6e021000	Deferred        cabinetPE	        6e6c0000-        6eb53000	Deferred        comctl32PE	        6f080000-        6f0cc000	Deferred        odbccp32PE	        6fbc0000-        6fdfc000	Deferred        rpcrt4PE	        71140000-        71423000	Deferred        urlmonPE	        7b000000-        7b2fa000	Deferred        kernelbaseELF	        7b400000-        7b67c000	Dwarf           kernel32<elf>\-PE	        7b410000-        7b67c000	\               kernel32ELF	        7bc00000-        7bec7000	Deferred        ntdll<elf>\-PE	        7bc20000-        7bec7000	\               ntdllELF	        7c000000-        7c004000	Deferred        <wine-loader>PE	       140000000-       140523000	Export          driver_installerELF	    7feba8c00000-    7feba8e12000	Deferred        libnss_myhostname.so.2ELF	    7feba8e12000-    7feba9019000	Deferred        libnss_dns.so.2ELF	    7feba9019000-    7feba921c000	Deferred        libnss_mdns4_minimal.so.2ELF	    7feba921c000-    7feba9242000	Deferred        bcrypt<elf>\-PE	    7feba9220000-    7feba9242000	\               bcryptELF	    7feba9242000-    7feba9346000	Deferred        crypt32<elf>\-PE	    7feba9250000-    7feba9346000	\               crypt32ELF	    7feba9346000-    7feba93cf000	Deferred        dbghelp<elf>\-PE	    7feba9350000-    7feba93cf000	\               dbghelpELF	    7feba93cf000-    7feba941e000	Deferred        secur32<elf>\-PE	    7feba93e0000-    7feba941e000	\               secur32ELF	    7feba9464000-    7feba9679000	Deferred        libgpg-error.so.0ELF	    7feba9679000-    7feba9995000	Deferred        libgcrypt.so.20ELF	    7feba9995000-    7feba9bb1000	Deferred        liblz4.so.1ELF	    7feba9bb1000-    7feba9dd7000	Deferred        liblzma.so.5ELF	    7feba9dd7000-    7febaa05b000	Deferred        libsystemd.so.0ELF	    7febaa05b000-    7febaa263000	Deferred        libffi.so.6ELF	    7febaa263000-    7febaa47e000	Deferred        libresolv.so.2ELF	    7febaa47e000-    7febaa682000	Deferred        libkeyutils.so.1ELF	    7febaa682000-    7febaa8cf000	Deferred        libdbus-1.so.3ELF	    7febaa8cf000-    7febaab50000	Deferred        libgmp.so.10ELF	    7febaab50000-    7febaad84000	Deferred        libhogweed.so.4ELF	    7febaad84000-    7febaafba000	Deferred        libnettle.so.6ELF	    7febaafba000-    7febab1cd000	Deferred        libtasn1.so.6ELF	    7febab1cd000-    7febab54b000	Deferred        libunistring.so.2ELF	    7febab54b000-    7febab768000	Deferred        libidn2.so.0ELF	    7febab768000-    7febaba97000	Deferred        libp11-kit.so.0ELF	    7febaba97000-    7febabca2000	Deferred        libkrb5support.so.0ELF	    7febabca2000-    7febabea6000	Deferred        libcom_err.so.2ELF	    7febabea6000-    7febac0d8000	Deferred        libk5crypto.so.3ELF	    7febac0d8000-    7febac3ae000	Deferred        libkrb5.so.3ELF	    7febac3ae000-    7febac5bf000	Deferred        libavahi-client.so.3ELF	    7febac5bf000-    7febac7cb000	Deferred        libavahi-common.so.3ELF	    7febac7cb000-    7febacb31000	Deferred        libgnutls.so.30ELF	    7febacb31000-    7febacd7c000	Deferred        libgssapi_krb5.so.2ELF	    7febacd7c000-    7febad008000	Deferred        libcups.so.2ELF	    7febad026000-    7febad22c000	Deferred        libxfixes.so.3ELF	    7febad22c000-    7febad436000	Deferred        libxcursor.so.1ELF	    7febad436000-    7febad646000	Deferred        libxi.so.6ELF	    7febad646000-    7febad849000	Deferred        libxcomposite.so.1ELF	    7febad849000-    7febada54000	Deferred        libxrandr.so.2ELF	    7febada54000-    7febadc5e000	Deferred        libxrender.so.1ELF	    7febadc5e000-    7febade64000	Deferred        libxxf86vm.so.1ELF	    7febade64000-    7febae067000	Deferred        libxinerama.so.1ELF	    7febae067000-    7febae26f000	Deferred        librt.so.1ELF	    7febae26f000-    7febae484000	Deferred        libbsd.so.0ELF	    7febae484000-    7febae68a000	Deferred        libxdmcp.so.6ELF	    7febae68a000-    7febae88e000	Deferred        libxau.so.6ELF	    7febae88e000-    7febaeab6000	Deferred        libxcb.so.1ELF	    7febaeab6000-    7febaedee000	Deferred        libx11.so.6ELF	    7febaedee000-    7febaf000000	Deferred        libxext.so.6ELF	    7febaf000000-    7febaf01c000	Deferred        kerberos<elf>\-PE	    7febaf010000-    7febaf01c000	\               kerberosELF	    7febaf01e000-    7febaf0e1000	Deferred        winex11<elf>\-PE	    7febaf030000-    7febaf0e1000	\               winex11ELF	    7febaf15c000-    7febaf38e000	Deferred        libexpat.so.1ELF	    7febaf38e000-    7febaf5d3000	Deferred        libfontconfig.so.1ELF	    7febaf5d3000-    7febaf7f0000	Deferred        libz.so.1ELF	    7febaf7f0000-    7febafa22000	Deferred        libpng16.so.16ELF	    7febafa22000-    7febafcd6000	Deferred        libfreetype.so.6ELF	    7febafcd6000-    7febafd07000	Deferred        iphlpapi<elf>\-PE	    7febafce0000-    7febafd07000	\               iphlpapiELF	    7febafd07000-    7febafd4f000	Deferred        netapi32<elf>\-PE	    7febafd10000-    7febafd4f000	\               netapi32ELF	    7febafd4f000-    7febafd8f000	Deferred        ws2_32<elf>\-PE	    7febafd60000-    7febafd8f000	\               ws2_32ELF	    7febafd8f000-    7febafded000	Deferred        winspool<elf>\-PE	    7febafda0000-    7febafded000	\               winspoolELF	    7febafded000-    7febb082c000	Deferred        shell32<elf>\-PE	    7febafe10000-    7febb082c000	\               shell32ELF	    7febb082c000-    7febb0aae000	Deferred        user32<elf>\-PE	    7febb0850000-    7febb0aae000	\               user32ELF	    7febb0aae000-    7febb0b8f000	Deferred        msvcrt<elf>\-PE	    7febb0ad0000-    7febb0b8f000	\               msvcrtELF	    7febb0b8f000-    7febb0c20000	Deferred        advapi32<elf>\-PE	    7febb0ba0000-    7febb0c20000	\               advapi32ELF	    7febb0d20000-    7febb0ec8000	Deferred        gdi32<elf>\-PE	    7febb0d40000-    7febb0ec8000	\               gdi32ELF	    7febb0fc8000-    7febb11da000	Deferred        libnss_files.so.2ELF	    7febb11da000-    7febb13f4000	Deferred        libnsl.so.1ELF	    7febb13f4000-    7febb1600000	Deferred        libnss_nis.so.2ELF	    7febb1600000-    7febb180a000	Deferred        libnss_compat.so.2ELF	    7febb1ce9000-    7febb1f01000	Deferred        libgcc_s.so.1ELF	    7febb1f01000-    7febb229f000	Deferred        libm.so.6ELF	    7febb22a1000-    7febb24a5000	Deferred        libdl.so.2ELF	    7febb24a5000-    7febb2896000	Deferred        libc.so.6ELF	    7febb2896000-    7febb2ab5000	Deferred        libpthread.so.0ELF	    7febb2ad3000-    7febb2e74000	Dwarf           libwine.so.1ELF	    7febb2e76000-    7febb30a0000	Deferred        ld-linux-x86-64.so.2Threads:process  tid      prio (all id:s are in hex)00000010 services.exe0000002f    00000002a    000000027    00000001f    000000015    000000012    000000011    000000013 plugplay.exe00000019    000000018    000000014    00000001a vpnclient_x64.exe00000057    000000056    000000055    000000054    000000047    000000043    00000003d    00000003c    00000003b    00000003a    000000035  -1500000034    000000033    000000026   1500000021    000000020    00000001b    00000001c explorer.exe00000025    000000024    00000001e    00000001d    000000022 winedevice.exe0000002c    00000002b    000000029    000000028    000000023    00000002d winedevice.exe00000032    000000031    000000030    00000002e    000000036 vpncmgr_x64.exe00000050    000000042    000000041    00000003e   1500000037    000000038 vpncmgr_x64.exe00000060    000000051    000000046    000000045    00000003f   1500000039    000000049 vpnclient_x64.exe00000053    000000052    00000004f    00000004e    00000004d   150000004b    00000006b (D) C:\users\bruno\Temp\VPN_7D37\driver_installer.exe00000071    00000006e    00000006d   150000006c    0 <==System information:Wine build: wine-5.0.2Platform: x86_64Version: Windows 7Host system: LinuxHost version: 5.4.0-47-generic
