### ISSUE TITLE
linux client can't get ip var dhcp protocol

### ISSUE THREAD

**Issue by tidatida** [SoftEtherVPN/SoftEtherVPN#377]
I can't find any code to request ip-adress after connected to server.

**Comment by MtCedarNet** [comment]
SoftEther VPN protocol is a Layer-2 VPN protocol.
Basically, client don't care about IP address.

Please try DHCP client to get IP address.
(Do not forget to statically add a route to the VPN server if the default gateway update masks the route to the VPN server.)

**Comment by tidatida** [comment]
@MtCedarNet  Thanks for your reply  :) 
What confused me is the windows client can use dhcp protocol to request ip address and route info,  It also safe the original route  and restore route when it disconnected from  a server,  BUT  I can't find any code 
 in this project about this .  Am I missing something or  the  CLIENT-DHCP-AND-ROUTE-PROCESSING part isn't publiced?

**Comment by MtCedarNet** [comment]
Windows client only monitor DHCP packets. DHCP request is sent by Windows OS.
Of course, routing is processed by OS.

**Comment by tidatida** [comment]
@MtCedarNet  But, how and when does windoes client trigger DHCP request?

**Comment by MtCedarNet** [comment]
The client makes virtual NIC online when connection is established.
When Windows detect NIC raised to online, Windows sends DHCP request.

**Comment by tidatida** [comment]
Thank you,   @MtCedarNet ,  you are so cool.

**Comment by moatazelmasry2** [comment]
Hi @tidatida. Does this answer solve your issue. If so I'll close this issue within the next days

**Comment by tidatida** [comment]
Yes,  you can close it now   :)
