### ISSUE TITLE
SoftEther VPN Server eventually crashes macOS 

### ISSUE THREAD

**Issue by nstuyvesant** [SoftEtherVPN/SoftEtherVPN#378]
SoftEther VPN Server 4.22 periodically crashes my macOS causing a restart. Today, I upgraded to 4.24 and will keep an eye out as to whether it's still happening.

Here's the crashlog for 4.22...

Anonymous UUID:       4C688681-7B8C-9685-4211-139FAAB7F174

Sun Nov 19 06:49:49 2017

*** Panic Report ***
panic(cpu 2 caller 0xffffff8029f352e0): "zalloc: zone map exhausted while allocating from zone socket, likely due to memory leak in zone socket (5896172016 total bytes, 6193458 elements allocated)"@/Library/Caches/com.apple.xbs/Sources/xnu/xnu-3789.71.6/osfmk/kern/zalloc.c:2405
Backtrace (CPU 2), Frame : Return Address
0xffffff9213c8bc00 : 0xffffff8029eea56c 
0xffffff9213c8bc80 : 0xffffff8029f352e0 
0xffffff9213c8bdd0 : 0xffffff802a37358d 
0xffffff9213c8be20 : 0xffffff802a3c6cf6 
0xffffff9213c8be40 : 0xffffff802a3c6e66 
0xffffff9213c8bea0 : 0xffffff802a3d7f01 
0xffffff9213c8bf10 : 0xffffff802a3d7d73 
0xffffff9213c8bf50 : 0xffffff802a424995 
0xffffff9213c8bfb0 : 0xffffff8029e9bd96 

**BSD process name corresponding to current thread: vpnserver**

Mac OS version:
16G1036

Kernel version:
Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64
Kernel UUID: F487A842-6E21-37AB-83C3-83F951218734
Kernel slide:     0x0000000029c00000
Kernel text base: 0xffffff8029e00000
__HIB  text base: 0xffffff8029d00000
System model name: Macmini6,2 (Mac-F65AE981FFA204ED)

System uptime in nanoseconds: 805870781477818
Zone Name              Cur Size  Free Size
vm objects             58875904     573952
vm object hash entri    8555760       5840
VM map entries          3688320     930960
pagetable anchors       1261568          0
pv_list                16234320        720
vm pages array        219707096          0
vm pages               11755520      16960
kalloc.32               1654784     297984
kalloc.48              13521120       4176
kalloc.64               4284416     182272
kalloc.80               1313760     291600
kalloc.96               1297440      24480
kalloc.128              1830912      46976
kalloc.256              1257472       5632
kalloc.512             12025856      65024
kalloc.1024             1396736       6144
kalloc.2048             4706304      59392
kalloc.4096             2404352          0
kalloc.8192             3227648          0
mem_obj_control         3424256       4288
sched groups            1741824     171072
ipc ports               3249960     243768
threads                 2399040    1235976
x86 fpsave state        1557504     872768
uthreads                1191360     383520
socket               5896172016          0
vnodes                 65267400       1736
namecache              24276000       6432
decmpfs_cnode          10665592      27104
buf.4096                2437120          0
buf.8192               61808640          0
ubc_info zone          17325528      10296
knote zone              2019600     147456
vnode pager structur    7878480       7920
HFS node               86305984     247968
HFS fork               25260032       8832
compressor_pager        1114112      30656
compressor_segment      3039232       1024
Kernel Stacks           3735552
PageTables            118665216
Kalloc.Large         18446744073531057432

Backtrace suspected of leaking: (outstanding bytes: 2901696)
0xffffff8029f35a95 
0xffffff802a37358d 
0xffffff802a3c6cf6 
0xffffff802a3c6e66 
0xffffff802a3d7f01 
0xffffff802a3d7d73 
0xffffff802a424995 

last loaded kext at 27126013884: com.apple.driver.AppleWWANSupport1	4.0.0 (addr 0xffffff7fab2fd000, size 57344)
last unloaded kext at 190270778804: com.apple.driver.AppleUSBMergeNub	900.4.1 (addr 0xffffff7fab061000, size 12288)
loaded kexts:
com.vmware.kext.vmioplug.17.1.2	17.1.2
com.vmware.kext.vmx86	0675.41.83
com.vmware.kext.vmnet	0675.41.83
com.vmware.kext.vmci	90.8.1
net.sf.tuntaposx.tap	1.0
net.sf.tuntaposx.tun	1.0
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.autofs	3.0
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.AGPM	110.23.17
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleMikeyHIDDriver	131
com.apple.driver.AppleGraphicsDevicePolicy	3.14.49
com.apple.driver.AppleMikeyDriver	279.48
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleHDA	279.48
com.apple.driver.AppleMCCSControl	1.3.4
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	5.0.5f1
com.apple.driver.AppleIntelHD4000Graphics	10.2.5
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleThunderboltIP	3.0.8
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleIntelFramebufferCapri	10.2.5
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleIRController	341.2
com.apple.iokit.SCSITaskUserClient	394.50.1
com.apple.driver.AppleUSBStorageCoexistentDriver	404.50.6
com.apple.driver.AppleRAID	5.1.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	366.70.3
com.apple.iokit.IOAHCIBlockStorage	295.20.1
com.apple.driver.AppleSDXC	1.7.6
com.apple.iokit.AppleBCM5701Ethernet	10.2.10
com.apple.driver.AppleFWOHCI	5.5.5
com.apple.driver.AirPort.Brcm4360	1151.1.1a1
com.apple.driver.AppleAHCIPort	326.60.1
com.apple.driver.AppleACPIButtons	5.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	5.0
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	219.0.0
com.apple.nke.applicationfirewall	172
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	219.0.0
com.apple.filesystems.acfsctl	589
com.apple.filesystems.acfs	589
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	279.48
com.apple.kext.OSvKernDSPLib	525
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOSurface	159.10
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.AppleHDAController	279.48
com.apple.iokit.IOHDAFamily	279.48
com.apple.iokit.IOAudioFamily	205.15
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.iokit.IOFireWireIP	2.2.7
com.apple.iokit.IONDRVSupport	516.1
com.apple.driver.AppleGraphicsControl	3.14.49
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.iokit.IOAcceleratorFamily2	311.15
com.apple.AppleGraphicsDeviceControl	3.14.49
com.apple.iokit.IOGraphicsFamily	515.3
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	5.0.5f1
com.apple.iokit.IOBluetoothHostControllerUSBTransport	5.0.5f1
com.apple.iokit.IOBluetoothHostControllerTransport	5.0.5f1
com.apple.iokit.IOBluetoothFamily	5.0.5f1
com.apple.driver.usb.IOUSBHostHIDDevice	1.1
com.apple.iokit.IOSCSIBlockCommandsDevice	394.50.1
com.apple.iokit.IOUSBMassStorageClass	4.0.4
com.apple.iokit.IOUSBMassStorageDriver	131.60.1
com.apple.iokit.IOSCSIArchitectureModelFamily	394.50.1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.1
com.apple.driver.usb.AppleUSBHub	1.1
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleThunderboltDPInAdapter	5.0.2
com.apple.driver.AppleThunderboltDPAdapterFamily	5.0.2
com.apple.driver.AppleThunderboltPCIUpAdapter	2.1.3
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.3
com.apple.driver.AppleXsanScheme	3
com.apple.driver.AppleThunderboltNHI	4.5.4
com.apple.iokit.IOThunderboltFamily	6.5.7
com.apple.iokit.IOEthernetAVBController	1.0.3b4
com.apple.iokit.IOFireWireFamily	4.6.6
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBEHCIPCI	1.1
com.apple.driver.usb.AppleUSBEHCI	1.1
com.apple.driver.usb.AppleUSBXHCIPCI	1.1
com.apple.driver.usb.AppleUSBXHCI	1.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleUSBHostMergeProperties	1.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.1
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.DiskImages	444.50.16
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	5.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
Model: Macmini6,2, BootROM MM61.010B.B00, 4 processors, Intel Core i7, 2.6 GHz, 16 GB, SMC 2.8f0
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x10E), Broadcom BCM43xx 1.0 (7.21.171.131.1a1)
Bluetooth: Version 5.0.5f1, 3 services, 17 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Thunderbolt Ethernet, Ethernet, en5
PCI Card: Apple 57762-A0, Ethernet Controller, Thunderbolt@195,0,0
Serial ATA Device: APPLE SSD SM256E, 251 GB
Serial ATA Device: APPLE SSD SM256E, 251 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
USB Device: My Book 25EE
USB Device: Composite Device
Thunderbolt Bus: Mac mini, Apple Inc., 23.4
Thunderbolt Device: Thunderbolt to Gigabit Ethernet Adapter, Apple Inc., 1, 5.5

**Comment by nstuyvesant** [comment]
Still a problem with 4.27

**Comment by davidebeatrici** [comment]
Superseded by #569.
