### ISSUE TITLE
Problem while connecting using Cisco VPN client

### ISSUE THREAD

**Issue by gauravkhullar1690** [SoftEtherVPN/SoftEtherVPN#38]
I am trying to connect to the SoftEther VPN Server using the Cisco VPN client but not  able to connect. Can someone please provide some steps to so that. 

Thanks in advance

**Comment by moatazelmasry2** [comment]
As far as I remember from an old Project, the Cisco client was using IPSec tunneling mode, which is currently not supported by SoftEtherVPN. So this is not a problem, it is simply not implemented. This can be solved by extending the current IPSec implementation in SoftEther (Used in L2TP) to completely implement IKEv1 (IPSec tunneling mode)

**Comment by moatazelmasry2** [comment]
The OP seems to be inactive. For this reason I'd like to close this issue within the next few days if there are no objections. 

Cheers
