### ISSUE TITLE
can not  in china

### ISSUE THREAD

**Issue by wensanlang0817** [SoftEtherVPN/SoftEtherVPN#382]
why cannot connect in china .

**Comment by moatazelmasry2** [comment]
SoftEtherVPN works in China.
What have you tried? which protocol? which setup etc..

For user related question, please use the forum http://www.vpnusers.com/

**Comment by aicochow** [comment]
you can try my server.
[https://eikochow.gitbooks.io/vpn/content/](https://eikochow.gitbooks.io/vpn/content/)

if you can not access the site, please download pdf file.
[https://github.com/aicochow/SoftEther-VPN/releases/download/v4.24/vpn.pdf](https://github.com/aicochow/SoftEther-VPN/releases/download/v4.24/vpn.pdf)
