### ISSUE TITLE
How to run VGate project on android ?

### ISSUE THREAD

**Issue by Khsed4** [SoftEtherVPN/SoftEtherVPN#383]
I want to develop an L2TP IPsec VPN  android application, I searched and found that I can use VGate project for my application, but I don't know how and which IDE I should use run it?

**Comment by GildedHonour** [comment]
Visual studio

**Comment by Khsed4** [comment]
@GildedHonour  Should I import all SortEther project or just I need VGate classes   
https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/tree/master/src/VGate          
I need L2TP IPsec VPN would you please tell me which folders or classes I need ?

**Comment by GildedHonour** [comment]
I don't know.

**Comment by moatazelmasry2** [comment]
As far as I know the source code for VPNGate is not openly released, although it uses many headers, c files from SoftEther. 
Also vpngate has nothing to do L2TP or OpenVPN. On android there are many L2TP and VPN clients that can be directly used with a SoftEtherVPN Server. 
Closing this ticket
