### ISSUE TITLE
User name can not use email

### ISSUE THREAD

**Issue by aicochow** [SoftEtherVPN/SoftEtherVPN#384]
User name can not use `@ `
So I can not use email as user name.

**Comment by moatazelmasry2** [comment]
Are you using Radius? In this case it is not possible to use an Email as a username. The reason for  is that Softether  uses the "@" sign to distinguish between hubs and to which Radius Server it should send the traffic, for example user@hub1 or @hub2. So I'm not really sure how to solve this problem without further discussion.

**Comment by aicochow** [comment]
@moatazelmasry2 I am not using Radius.

**Comment by moatazelmasry2** [comment]
Ok. But nevertheless SoftEther is using the "@" sign internally to send the requests to the right hub. so you can not use this sign in this username. Some other characters are also not allowed like = or ! or ?.

Sorry there is nothing to do here.

**Comment by aicochow** [comment]
@moatazelmasry2 ok,I see.thank you.
