### ISSUE TITLE
Earn the CII Best Practices Badge Program

### ISSUE THREAD

**Issue by moatazelmasry2** [SoftEtherVPN/SoftEtherVPN#386]
This program is a set of best practices for open source projects that known OSS like kubernetes und nodejs have. They cover aspects like code quality, security, documentation etc..

Look for example at the badge under:
![screenshot from 2017-11-23 14-08-08](https://user-images.githubusercontent.com/4456901/33174309-d12b6122-d057-11e7-8f28-89cd6fcb1225.png)

Bringing this project to such a high quality level will enhance the acceptance of the project overall and encourage more users to contribute

**Comment by fenice2** [comment]
I wholeheartedly agree with an initiative such as this, it can only be beneficial to the project. :)
