### ISSUE TITLE
Connect to my own server using SoftEther project or Vagate?

### ISSUE THREAD

**Issue by Khsed4** [SoftEtherVPN/SoftEtherVPN#387]
Hi Every one 
I need to implement an L2TP IPsec VPN android application that the user would connect from app to my server(I have my own server, just the need to connect it).
Is softEther can help me if yes please describe more?

**Comment by Raafat** [comment]
Hello! Are you **required** to create a L2TP IPsec VPN android-based application or do you need to connect to SE via an L2TP IPsec to an SE server?

**Comment by Khsed4** [comment]
@Raafat  I required to create an L2TP IPsec VPN Android-based application and I had googled a lot but couldn't found a good solution. 
As I mention in question I have my own server, and the android app to connect to it I would really appreciate any kind of help.

**Comment by moatazelmasry2** [comment]
Ok. But I'm not sure what kind of help you expect to get..
Implementing a VPN client is not an easy task at all. You can start by reading the source code under Cedar/IPSec.c and IPSec_L2TP.c

Also you need to be able to read and understand RFCs, for example like 2661 (L2TP):
https://tools.ietf.org/html/rfc2661

and then port SoftEther implementation to Java.

There's already an android open source library for OpenVPN
https://github.com/schwabe/ics-openvpn

Hope this helps

**Comment by Khsed4** [comment]
@moatazelmasry2  Thanks, I really appreciate your help, so let me conclude by creating this kind of VPN I need to use C, C++, Java and RFCs and I can you use from the source code of SoftEher and OpenVPN projects to implement it.
If the answer is yes you can close the issue since I found what I was looking for.
again Thanks.

**Comment by moatazelmasry2** [comment]
Yes. SE is in C and you need to port several files into Java (or Kotlin). But again, this is not an easy task at all. Good luck
