### ISSUE TITLE
Feature request: web API included

### ISSUE THREAD

**Issue by karlvlam** [SoftEtherVPN/SoftEtherVPN#390]
I would like to ask if is it possible to include an RESTful API for the server administration? 

Thank you.

**Comment by zulzardi** [comment]
U can try this https://github.com/mindcollapse/SoftEtherPy

**Comment by moatazelmasry2** [comment]
I know about SoftEtherPy but it is also true that there's no clear REST API for this project and it would be good to have some clean API or Documentation

**Comment by raorao05** [comment]
hi,https://github.com/mindcollapse/SoftEtherPy

**Comment by davidebeatrici** [comment]
Superseded by #562.
