### ISSUE TITLE
While Connected to SoftEther VPN via IPsec/L2TP Mac OS Client - Using Finder File Manager, Search Function Crashes

### ISSUE THREAD

**Issue by vepicurean** [SoftEtherVPN/SoftEtherVPN#396]
SoftEther Client Configuration - Mac OS (10.12) connected to Mac OS Workstation via SoftEther VPN over wifi.  Network is very fast (over 50Mbs up and down) and stable. 

The issue: When doing a search for a file from the Finder file explorer crashes the Finder application right away on hitting enter.  The VPN stays connected, just Finder crashes. 

Essentially a base function of the client computer (searching for files) is taken away when using the SoftEther VPN.  **This can't stay as is. Needs to be fixed ASAP.** (when using the MacOS IPsec/L2TP Client configuration). 

This would go a long way to improving acceptance of SoftEther by the vast population of people with Mac laptops. 

Thanks for your help and time.  Greatly appreciated.

**Comment by domosekai** [comment]
Since the VPN stays connected, this looks like a macOS bug.

**Comment by vepicurean** [comment]
I doubt it's a MacOS bug. Never notices that behaviour in any other situation. 

SoftEther performance was never stable for me. I have not looked at it for years. OpenVPN on Linux, I got that install down and it's rock solid, so I stay with that. 

I'll revisit SoftEther when I get some time. The SoftEther documentation was not great, and community is not as active as I would have hoped. I remember the project has potential, so I'll revisit it down the road to see what's changed.

**Comment by domosekai** [comment]
The documentation sucks and the community is not active. Totally agree. 
SE is not a big name in the VPN world comparing to OpenVPN, Wireguard etc. It was created by some Japanese individual a decade ago. But we do have something those big players don't, such as multi-protocol support, local bridge and easy-to-use server manager (Windows only). 
Once you got some time and found something interesting, please leave comments and we are happy to look into it again.

**Comment by vepicurean** [comment]
Will do. I am aware that SoftEther has certain features that make it very powerful. I know it has a lot of potential, I just wish they had open sourced it sooner. 

Just my view, things would be different today if they had open sourced the project sooner. It's hard to take over mindshare once people get used to using another tool and the knowledge base for the other tool reaches critical mass and works for most people (as I'm sure you all know).
