### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by sahal** [SoftEtherVPN/SoftEtherVPN#40]
`debian/changelog` needs to be updated every time you update the current build number `src/CurrentBuild.txt` or else the binaries that are created have the "wrong" version number.

Normally, on a Debian system this is easy with the `dch` command, but it looks like you can just edit the file with any text editor too.

For more information see [Intro to Debian Packaging](https://wiki.debian.org/IntroDebianPackaging).

**Comment by moatazelmasry2** [comment]
Hi @sahal it looks like your merged PR resolves this issue. Could you please add some documentation in the README on how to use this solution for debian users so that we can close this issue?

**Comment by moatazelmasry2** [comment]
The OP seems to be inactive. For this reason I'd like to close this issue within the next few days if there are no objections. 

Cheers
