### ISSUE TITLE
Softether on ubuntu with letsencrypt wailed openvpn

### ISSUE THREAD

**Issue by vatslav** [SoftEtherVPN/SoftEtherVPN#400]
Step for represent bug:

1.  Deploy  Ubuntu 16.04
2. install build-essential
3. install certbot and make ssl cert
4. compile Softether
5. export SSL cert (fullchain & privkey) to softether
6. Download openvpn config and run openvpn
`Thu Dec 14 18:44:51 2017 VERIFY ERROR: depth=0, error=unable to get local issuer certificate: CN=my.vpn.domain
Thu Dec 14 18:44:51 2017 TLS_ERROR: BIO read tls_read_plaintext error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Thu Dec 14 18:44:51 2017 TLS Error: TLS object -> incoming plaintext read error
Thu Dec 14 18:44:51 2017 TLS Error: TLS handshake failed
Thu Dec 14 18:44:51 2017 SIGUSR1[soft,tls-error] received, process restarting
Thu Dec 14 18:44:51 2017 Restart pause, 2 second(s)`

I`m testing this steps scrips on multiple clean servers and always have this errors. I`m get this error on 3 latest build

**Comment by domosekai** [comment]
OpenVPN needs self-signed certificate to be saved in chain_certs directory.
