### ISSUE TITLE
What's "hamcore.se2"?

### ISSUE THREAD

**Issue by youxiaojie** [SoftEtherVPN/SoftEtherVPN#401]
What's hammcore.se2? It is contained in three platforms.

**Comment by youxiaojie** [comment]
It contains files concerned with Windows?

**Comment by MtCedarNet** [comment]
It contains non-executable resources.
https://github.com/SoftEtherVPN/SoftEtherVPN/tree/master/src/bin/hamcore

**Comment by youxiaojie** [comment]
It maybe used in windows but in liunx?

**Comment by youxiaojie** [comment]
Driver for Windows  is useless for Linux ~_~confused.

**Comment by MtCedarNet** [comment]
Drivers are not used in Linux.
If you need smaller footprint, you can build hamcore.se2 without driver files.

**Comment by youxiaojie** [comment]
what files can be delete safely in Linux?

**Comment by MtCedarNet** [comment]
I think 'DriverPackages' folder and *.exe files aren't used in Linux.

**Comment by chipitsine** [comment]
the question is answered.

can we close the issue ?
