### ISSUE TITLE
Linux Client Rewrite for Android

### ISSUE THREAD

**Issue by top-master** [SoftEtherVPN/SoftEtherVPN#402]
We want to implement an L2TP IPsec PSK VPN for Android: since SE looks like it has linux client code we want to make an android client of your code but my top question:
is your linux client code made STABLE or does it contain TODO code for connecting to existing SE server.

if not STABLE do you can recommend any open source linux or android client supporting and/or using SE

we want to make SoftEtherAndroid open source to safe others time but last question:
Is it possible to allow us to work on it at "github.com/SoftEtherVPN/SoftEtherAndroid"
or do we need to first work on it at "github.com/top-master/SoftEtherAndroid"
and if that gets good and stable you clone it latter under "github.com/SoftEtherVPN/SoftEtherAndroid"

**Comment by aenertia** [comment]
It compiles for arm fine, you can sideload it and so long as you have a
rooted phone with a Linux stack installed it should 'just work' . Coding an
android native UI is an excercize left to the user.

**Comment by top-master** [comment]
It's some time since last comment (being just two developers without much network knowledge) but at last the world has an other new VPN App for Android!
for now it's just a prove of concept but will change that for sure.

thanks to this project we have learned much about Internet-Protocol's and also Android.

**Comment by davidebeatrici** [comment]
Superseded by #453.

**Comment by tangw0** [comment]
> It's some time since last comment (being just two developers without much network knowledge) but at last the world has another new VPN App for Android! (without rooting the device)
> for now it's just a prove of concept but will change that for sure.
> 
> thanks to this project and our work to change it we have learned much about Internet-Protocol's and also Android.

could you please share your android client to connect to softether?
