### ISSUE TITLE
L2TP/IPSec PSK client not working

### ISSUE THREAD

**Issue by top-master** [SoftEtherVPN/SoftEtherVPN#404]
**hello and with respects:**
we want to start SE linux client with command line to connect to existing SE server using L2TP/IPSec PSK but my questions:
where can we find help online for SE linux client command line options?
does SE linux client support L2TP/IPSec PSK and connection to existing SE server with that?
if SE linux client does NOT support L2TP/IPSec PSK, is there any open source linux client that does support connection to existing SE server using L2TP/IPSec PSK not CRT?

**Comment by top-master** [comment]
we did find tour "http://lukeluo.blogspot.com/2013/11/how-to-set-up-softehter-vpn-client.html" for linux but still got no connection to existing SE server using L2TP/IPSec PSK did anyone made such connection befor?
if YES which commands did you follow?

**Comment by moatazelmasry2** [comment]
SE client only supports SoftEther own VPN protocol. It doesn not support L2TP.

That being said, there are several documentation out there on how to use an L2TP client on Linux, for example:
https://wiki.archlinux.org/index.php/StrongSwan
https://www.elastichosts.com/blog/linux-l2tpipsec-vpn-client/
https://support.hidemyass.com/hc/en-us/articles/202721466-HMA-Pro-VPN-PPTP-L2TP-setup-on-Linux-Command-line-

Good luck
