### ISSUE TITLE
Update code files to 9652

### ISSUE THREAD

**Issue by scegg** [SoftEtherVPN/SoftEtherVPN#406]
Please update code files here to version 4.22 9652.

Because all new released binary files cannot be compiled in Ubuntu 17+, all affected user have to get codes here for building.

**Comment by MtCedarNet** [comment]
Plaese try adding "-no-pie” to LDFLAGS to link binaries on late Ubuntu.

**Comment by scegg** [comment]
@MtCedarNet 
Thanks for your idea.
By adding LDFLAGS=-no-pie in Makefile (between OPTIONS and default lines), nothing changed in make process.

Multiple errors about relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

**Comment by MtCedarNet** [comment]
Position Dependent Executable doesn't require -fPIC.

**Comment by scegg** [comment]
@MtCedarNet 
Hmm, dont know how to edit Makefile to get avoid of this.
Compiling from source code here is OK (but not the latest).

**Comment by davidebeatrici** [comment]
The issue has been fixed in the latest release (Build 9668 Beta).

https://www.softether.org/5-download/history
