### ISSUE TITLE
how to cross compile? I want to cross compile armhf and armel version.and then make deb package

### ISSUE THREAD

**Issue by youxiaojie** [SoftEtherVPN/SoftEtherVPN#409]
how to cross compile? I want to cross compile armhf and armel version.and then make deb package.
I try to 1. replace Makefile with usr/makefiles/linux_32bit.mak, "cp usr/makefiles/linux_32bit.mak Makefile"  2. "make -j4 CC=arm-linux-gnueabihf-gcc" but failed. what should I do?

**Comment by paskal** [comment]
Here you can find actual builds for Ubuntu: https://launchpad.net/~paskal-07/+archive/ubuntu/softethervpn

**Comment by nullx5** [comment]
I have the following error to execute the check of command `vpncmd:`

Checking 'Kernel System'...
              Pass
Checking 'Memory Operation System'...
              Pass
Checking 'ANSI / Unicode string processing system'...
              Pass
Checking 'File system'...
              Pass
Checking 'Thread processing system'...
              Pass
Checking 'Network system'...
Connect Failed. (0)
              Fail

Some checks failed.

I install the PPA:
sudo apt-add-repository ppa:paskal-07/softethervpn && sudo apt-get update && sudo apt-get upgrade && sudo apt-get install softether-vpnserver

How could I solve it

**Comment by youxiaojie** [comment]
I did not  meet this error.I use offical repository if my memory reserved me correctly.

**Comment by domosekai** [comment]
Close due to inactivity
