### ISSUE TITLE
hard to connect from china

### ISSUE THREAD

**Issue by wensanlang0817** [SoftEtherVPN/SoftEtherVPN#410]
sometimes i can connect it from china by UDP. there  is something wrong with TCP.

**Comment by aicochow** [comment]
@wensanlang0817 you can try this.
https://aicochow.github.io/vpn/

**Comment by Nefurtity** [comment]
Unfortunately many TCP ports has been blocked in recently, it would be working try to set your TCP port into a normal one, e.g 80, 443.

**Comment by moatazelmasry2** [comment]
You can use OpenVPN and set the port to 80 or 443. Alternatively you can use SoftEther Own VPN Protocol
