### ISSUE TITLE
Provide .zip package for VPN Client Manager for Windows

### ISSUE THREAD

**Issue by net147** [SoftEtherVPN/SoftEtherVPN#411]
Please provide .zip package (without installer) for VPN Client Manager for Windows, similar to the Server Manager for at least the latest stable version. This will make it easier to set up the VPN Client Manager to run on Linux using Wine.

**Comment by chipitsine** [comment]
It's a niche case. I will resolve it using app veyor artifacts

**Comment by aicochow** [comment]
@chipitsine I need it.
