### ISSUE TITLE
Deep Packet Inspection

### ISSUE THREAD

**Issue by moniekabir** [SoftEtherVPN/SoftEtherVPN#412]
Hi There . I live in Iran and I'am facing the DPI enforcement by country government. so i decided to use softether to bypass censorship. however it works just fine on my PC with softether or sstp. but i cant connect using mobile with ipsec or openvpn. which is completely blocked by DPI technology by my country. so my question is and how i can configure openvpn servers configuration for obfsproxy. or do you have any other suggestion ... 

Thanks . Regards Monie

**Comment by MRizkBV** [comment]
As far as I know. OpenVPN on Softether is not exactly OpenVPN. It is a clone of the protocol which means you can't do much about it. You can't add obfsproxy. Feel free to run a separate OpenVPN instance on your host with obfs if needed.

**Comment by moniekabir** [comment]
I found a solution ,  I hope soft-ether team will update their wiki with this information , there is a free sstp emulator for android. VPN Client Pro , Ihave used it and works great

**Comment by moniekabir** [comment]
Thank you. by using android SSTP client the problem fixed temporary.

**Comment by pdarcos** [comment]
Hi guys,

This is one aspect of SoftEther that worries me.
What good is having a VPN if it's blocked in many countries (which will only likely grow) and therefore useless?

I think that SoftEther should focus some of the effort on lessons learned with OpenVPN and Tor regarding bypassing DPI and other restrictive tech. How hard would it be to incorporate obfsproxy and other similar modules into SoftEther?

Thanks for this great software

**Comment by moniekabir** [comment]
Soft-ether is actually a great app, but it's not as fast as it should be.it's not cross-platform. I also tried ikev2 with StrongSwan which is really faster than my experience with Soft-ether on the same network. also, I have tried secure web proxy which is slightly faster though. also I found an app called Squid, I don't know how to set up a secure proxy with them yet but as it is a caching proxy it seems to have some advantage. by the way, i'm seek to create a cross-platform unlimited solution VPN/proxy app to help privacy and freedom, I got some ideas.

**Comment by pdarcos** [comment]
Hey @moniekabir 
How can we get in touch? It would be great to exchange some ideas with you

**Comment by moniekabir** [comment]
Hey @pdarcos  . actually, i'm not a developer yet. but a long time ago my brother create a program that could pass dpi with a trick, but after the national security of our country asked him to stop his program. , he left the app. but I think the source is still available, I also got some ideas around VPN . if you are interested and know someone who has enough skill to help development, I'm in

**Comment by pdarcos** [comment]
Hi @moniekabir 
Please check the issue I created on your wine repo.
Cheers

**Comment by yotta1998** [comment]
what about V2Ray , has any one tried it to some success in bypassing DPI ?
