### ISSUE TITLE
How could I use multi Cluster Controller

### ISSUE THREAD

**Issue by raorao05** [SoftEtherVPN/SoftEtherVPN#414]
hi, I read the cluster document,
(https://www.softether.org/4-docs/1-manual/3._SoftEther_VPN_Server_Manual/3.9_Clustering)

and i want to use “Static Virtual Hubs”

but i found i can use multi "Cluster Member" as Load Sharing,but there is only one "Cluster Controller", what happen if the "Cluster Controller" down?

**Comment by arqteqnet** [comment]
The and is the vpn servers fail.

The the best solution is to design a more scalable solution. I've currently designed a solution which load balances hundreds of users, load balancing, failover, one vpn provides access to thousands of internal resources in hybrid cloud and on prem inclusive with 2fa.
Arqteq.co.uk

**Comment by domosekai** [comment]
You can setup multiple cluster controllers that share the same hostname so that a member can randomly connect to one of them.
Close as no change on SoftEther is needed.

**Comment by elipsion** [comment]
Using this line of reasoning; would it be possible to have all the members of a cluster be controllers, and thus support clustering of L2TP/SSTP/OVPN?
