### ISSUE TITLE
A few questions 

### ISSUE THREAD

**Issue by canusuck** [SoftEtherVPN/SoftEtherVPN#415]
1. How to change the preset vpn: preshared key name and other moments.
2. How to get rid of dnsleaks? Use dnsmasq on the host machine, you can tell by the settings then.
3. Can I do it and if I can do it better: Double / Triple / Quad bundle for VPN
4. How to change ports to others? How to change ports if VPN is already installed on the server? Where to look ?

In advance I thank for answers

**Comment by moatazelmasry2** [comment]
1. I don't have a GUI right now, but you can change the preshared key on vpncmd via the command "IPsecEnable"
2. I don't understand the question? What do you want to achieve??
3. Currently there is no support as far as I know
4. For L2TP you can not. For OpenVPN you can change port from GUI or vpncmd. Further sstp is supported over 443. For SE own protocol you can also use any port. Also it is possible to use dns or icmp for creating a vpn connection

**Comment by moatazelmasry2** [comment]
@canusuck If you are happy with this answer, I'd like to close this ticket
