### ISSUE TITLE
nvram (router) friendly vpn_server.config version/options?

### ISSUE THREAD

**Issue by Andy2244** [SoftEtherVPN/SoftEtherVPN#423]
Hi, i use the server on a router via openwrt and while i have managed to move the startup to /var (ram) via soft-links the server seems to still update some trivial data in its vpn_server.config, which has to reside on nvram so config changes are kept.

It would be nice to get a version with options to remove any automatic runtime writes to the server config, so we can reduce nvram wear to only actual config changes.

Here are some entries that seem to change at runtime over time, which i like to get rid of:
```
		vpn_server.config
		
		declare ServerTraffic
		{
			declare RecvTraffic
			{
				uint64 BroadcastBytes 14833805137
				uint64 BroadcastCount 11585410
				uint64 UnicastBytes 71006703827
				uint64 UnicastCount 169943856
			}
			declare SendTraffic
			{
				uint64 BroadcastBytes 5240867939
				uint64 BroadcastCount 3913541
				uint64 UnicastBytes 70164691999
				uint64 UnicastCount 162072906
			}
		}
		
		declare Traffic
		{
			declare RecvTraffic
			{
				uint64 BroadcastBytes 14833805137
				uint64 BroadcastCount 11585410
				uint64 UnicastBytes 71006703827
				uint64 UnicastCount 169943856
			}
			declare SendTraffic
			{
				uint64 BroadcastBytes 5240867939
				uint64 BroadcastCount 3913541
				uint64 UnicastBytes 70164691999
				uint64 UnicastCount 162072906
			}
		}

		declare VPN
		{
			uint64 LastCommTime 1515918516619
		}
```

PS: Maybe i missed a already existing config option to remove the traffic monitoring?

**Comment by paulmenzel** [comment]
Could you please document the reason, why you closed the issue?

**Comment by Andy2244** [comment]
Opened a new more specific one #575 after checking the source and not finding a easy way to uncomment/define out the updates. What i did is patch the default values to 24h and max to 7 days for my openwrt package.
