### ISSUE TITLE
Forum Spam: I think I'm wasting my time.

### ISSUE THREAD

**Issue by fenice2** [SoftEtherVPN/SoftEtherVPN#424]
I'm sorry to post this in the issues page but I don't think I'd get an answer in the forums amongst all the spam.

Is it possible to have a sensible discussion about the state of the forums and some sort of action plan on what could/should be done to improve the situation?

It seems to me that the SoftEther forums are overrun with spam and spammers and nothing gets done about it. I dutifully report the spam messages I see but they are almost never removed and certainly the spammer (or rather spam bot) is never banned which then removes all their posts.

The IP address of the spammer/spam bot is usually known and can be banned before they post by adding an extension/plugin to the forum software, take a look at this one:

http://stopforumspam.com/

You can, in addition, place restrictions on what the spammer can add to their profile by requiring them to have a minimum number of posts. 

It also helps if the moderators/admins actually act on the spam reported messages and ban the user, if you don't have enough mods/admins then PLEASE appoint some more people that have the time and inclination to act on reported postts.

With all the spam on the forums there is no incentive for anyone to visit and post their questions. Without any changes to the forum they will die, here's some more spam threads containing illegal content (amongst other topics):

http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=18362
http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=16014
http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=16015
http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=16012
http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=16013
http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=16011
http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=16016
http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=18267
http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=18356
http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=1737
http://www.vpnusers.com/memberlist.php?mode=viewprofile&u=14147

http://www.vpnusers.com/viewtopic.php?t=41329
http://www.vpnusers.com/search.php?keywords=bank

**Comment by moatazelmasry2** [comment]
Hi @fenice2 no you are not wasting your time at all. I among many other people are also quite bothered with the status of the forum. Even @dnobori is bothered about it. There was a thread in the past about the forum and I think there's a general consensus to do something about it. Best approach is like you said to implement some modern forum software with spam blocking. 

We should keep this issue open, until this issue is actually resolved

**Comment by moatazelmasry2** [comment]
There are basically two solutions to this problem:

1. Migrate the bbforum to a better modern forum software and keep all the posts
2. Move to a hosted trusted service like github issues, stackoverflow, reddit etc.. but lose all the posts (they remained archieved on the frozen vpnusers.com of course)

I personally prefer the second solution as it will surely stop the spam

**Comment by thunfischbrot** [comment]
I agree, option 2 sounds best.

**Comment by fenice2** [comment]
MY choice would be for it to stay on a 'forum' and get some more moderators that have the time to remove spam etc.

I've been reporting spam on these forum almost from the day I joined and there's still a ton of spammers (some with thousands of posts) posting a load of rubbish (illegal in a lot of cases) and those posts are still there. All it would take on the current forum is an admin to ban the user and all the 3000+ for that user would go.

Keeping it in a forum only takes a bit of effort in the beginning but, IMO, it's worth the effort.

**Comment by thunfischbrot** [comment]
They are most likely bots which do not go away by banning a couple of existing users. They will continue signing up accounts as long as there isn't a well-automated system for banning spammers. I suggest migrating to an existing, established platform as running a forum is not the core competency of the SoftEther team and would require way less maintenance.

**Comment by moatazelmasry2** [comment]
I also would love to migrate somewhere else where bot fighting is daily bread, like github or stackoverflow

**Comment by moatazelmasry2** [comment]
Hi @fenice2 and thanks for your suggestions. I'm not a forum moderator and I don't know much about moderating forums anyways, but the answer to your question is simple: 
It is not a trust issue, but simply a time constraint issue. No one somehow has the time or capacity to solve this problem. I will try to reach out to Daiyuu and actually work on a root solution to this problem. 

Maybe in the mean time you can help me a little by first telling me the names of the plugins you use to fight spam.

**Comment by fenice2** [comment]
One of the best plug-ins is stopforumspam or Akismet which is mentioned in this blog post: https://michelkraemer.com/5-anti-spam-measures-for-phpbb3/

**Comment by davidebeatrici** [comment]
I removed the spam by deleting users (and their posts) which:
1. Had less than 2 posts.
2. Had a link to a "bad" website on the profile.
3. Posted spam threads/messages.

I also deleted all posts made by the Anonymous (guest) user.

As a side effect of point 1, a few valid users were affected and there are some threads which don't have the original first message anymore, because phpBB doesn't delete the entire thread.

@fenice2 Thank you very much for your help, you're now a global moderator.

**Comment by fenice2** [comment]
That must have been quite an horrendous task getting rid of all that 'mess', well done. :)

I'm surprised, amazed and honoured to be a moderator, I'll try my best to keep the forums clean. I've had a quick trial of various bits on the forums and no great surprises but a couple of questions.

I'd like to suggest that a 'private' forum for moderators/admins is created where we can ask questions without cluttering github, is that possible?

**Comment by davidebeatrici** [comment]
> That must have been quite an horrendous task getting rid of all that 'mess', well done. :)

Thank you.

It took some days, but it was worth it.

> I'm surprised, amazed and honoured to be a moderator, I'll try my best to keep the forums clean. I've had a quick trial of various bits on the forums and no great surprises but a couple of questions.

I'm sure you'll do a great job as a moderator, you did a lot of work as a user with limited power.

> I'd like to suggest that a 'private' forum for moderators/admins is created where we can ask questions without cluttering github, is that possible?

Done.
