### ISSUE TITLE
Add support Pluggable Transports and Enable HTTPS for all sites of vpngate

### ISSUE THREAD

**Issue by nuxrg** [SoftEtherVPN/SoftEtherVPN#427]
www.vpngate.net
# Add support Pluggable Transports
China ISP Enable Port Whitelist
http://forum.vpngate.net/viewtopic.php?f=11&t=42498#p59407
https://www.bloomberg.com/news/articles/2017-07-10/china-is-said-to-order-carriers-to-bar-personal-vpns-by-february
https://www.networkworld.com/article/3245795/sd-wan/china-to-block-sd-wan-and-vpn-traffic-by-jan-11.html

As China GFW has capability of detecting traffic signatures, and it is able to block VPN from those signatures, I wish following could be integrated to vpngate servers.

- Pluggable Transports
e.g:obfuscations(obfs),
     meek,
     Format-Transforming Encryption,
     ScrambleSuit...
More Details:https://www.torproject.org/docs/pluggable-transports.html.en

- DNS/IPv6 leak protection;

- Internet Kill Switch;

- split tunneling;

- NAT Firewall.
# Enable HTTPS for all sites
http://forum.vpngate.net/viewtopic.php?f=11&t=42256
Do not forget Let's Encrypt provide a free SSL certificate.
https://letsencrypt.org

**Comment by nuxrg** [comment]
VPNs & Internet in China: Everything you need to know 
https://vpnreviewer.com/internet-vpn-china

**Comment by nuxrg** [comment]
1. China GFW early stage
https://vpnreviewer.com/internet-vpn-china
    
2. ## China GFW Identifying traffic
identify Traffic treatise

- The Random Forest Based Detection of Shadowsock's Traffic
http://ieeexplore.ieee.org/document/8048116/

- Identifying Tor Anonymous Traffic Based on Gravitational Clustering Analysis
http://ieeexplore.ieee.org/document/8048117/

More details for: shadowsocks/shadowsocks-org#81

3. ## China ISP Enable Port Whitelist

- China Tells Carriers to Block Access to Personal VPNs by February
https://www.bloomberg.com/news/articles/2017-07-10/china-is-said-to-order-carriers-to-bar-personal-vpns-by-february

- China to block SD-WAN and VPN traffic by Jan. 11
https://www.networkworld.com/article/3245795/sd-wan/china-to-block-sd-wan-and-vpn-traffic-by-jan-11.html

- China disrupts global companies’ web access
https://www.ft.com/content/80e50a6c-fa8a-11e7-9b32-d7d59aace167
https://www.ft.com/video/553e829e-ffc3-4982-95e5-be5f64a23b26

- China’s VPN Crackdown May Aid Government Surveillance
https://www.wsj.com/articles/chinas-vpn-crackdown-may-aid-government-surveillance-1516189155

As China GFW has capability of detecting Traffic and Protocol, so it is able block vpngate servers/SoftEtherVPN
,I wish following could be add Pluggable Transports to vpngate/SoftEtherVPN.

Pluggable Transports more details on https://www.torproject.org/docs/pluggable-transports.html

Thank.

**Comment by nuxrg** [comment]
@moatazelmasry2 @dnobori @zulzardi @GildedHonour @paulmenzel @guidovranken 
The Project need more people Participate in order to advance with the times.

**Comment by pdarcos** [comment]
I agree with the OP. We need to add those pluggable transports or else SoftEther won't work at all in many countries in the world that are increasingly using DPI and other techniques to block VPNs.

What does the team think about this? Is it a priority or not really relevant for your goals?

Thanks

**Comment by paulmenzel** [comment]
@nuxrg, @pdarcos, I am no deveioper, but I am unsure what you expect? It’s free software, and all the developers seem to busy especially as none seem to do SoftEther VPN work for a living. So, if you want/need this support and the developers haven’t implemented it yet, please either pay somebody to do the work or do it yourself. I know it’s harsh, but that’s how it works.

if you have other ideas, how more people can be acquired to work on SoftEther VPN, everybody will love to hear those.

**Comment by pdarcos** [comment]
@paulmenzel

I'm not expecting anything, simply a reply to my question: is this on the roadmap or not?
I'm bringing together some of the smartest minds in this area for a future project and am willing to invest resources to get things done. So, I ask again, is this on the roadmap at all? If not, who from the community would be able to implement these pluggable transports (a paid job)?

Thanks

**Comment by aicochow** [comment]
@nuxrg I provide vpn server for china, and work well, no problem

**Comment by nuxrg** [comment]
@paulmenzel yes,but 

> The Great Firewall of China (abbreviated to GFW) is the combination of legislative actions and technologies enforced by the People's Republic of China to regulate the Internet domestically.

This is a struggle between institutional (group) strength vs personal strength, and it can be quite different in an open source community or nonprofit organization if an individual company is not estimated to last long.

I hope that if VPN Gate can open donations, I believe many people will be happy to donate.

@aicochow sure,but I believe it will be blocked soon.

Freedom of information is an extension of freedom of speech, a fundamental human right recognized in international law.
**one-party state is Devil,authoritarian regimes, Ideology the output of is very powerful and need world people pay attention.**

**Comment by aicochow** [comment]
@nuxrg My server running more than one year, never blocked.

**Comment by nuxrg** [comment]
More Precisely ,**Traffic Feature detection**

**Comment by moatazelmasry2** [comment]
@nuxrg yes and no. I agree that blocking VPN really sucks and I'm quite aware of the implications of living under an authoritarian regime like in China since I spent a good portion of my life in Egypt and I know how this really sucks.  Also one of the reasons this project became quite popular in China and Japan is its ability to penetrate through firewalls and proxies. 

VPNGate opening for donation won't advance this project, since as far as I know they act as two separate entities.  Also please notice that the Chinese state has way more resources to spend than the developers of this project. 

If you want this project to advance, then please review the issues and pull requests and give thumbs up if they are good and Invite your friends to do the same. There are some very good Pull requests here which are several years old and no one cared to comment or upvote them. 

On a side note @nuxrg  and @aicochow if anyone of you understands traditional chinese then plese review the PR #154 :) Thanks

**Comment by domosekai** [comment]
If anyone is going to contribute, you are more than welcome to do so. Close for now as the discussion is meaningless.

**Comment by kovalensky** [comment]
I back this issue, easy API for plugins for developers would solve this issue
