### ISSUE TITLE
Integrate fuzzers

### ISSUE THREAD

**Issue by paulmenzel** [SoftEtherVPN/SoftEtherVPN#428]
Integrate Guido Vranken’s [work](https://guidovranken.wordpress.com/2018/01/15/security-audit-of-softether-vpn-finds-11-security-vulnerabilities/) from https://github.com/guidovranken/SoftEtherVpn-Fuzz-Audit.

**Comment by chipitsine** [comment]
@guidovranken , can you help with fuzzers ?
