### ISSUE TITLE
SoftEther only client peer-to-peer

### ISSUE THREAD

**Issue by legionpheonix** [SoftEtherVPN/SoftEtherVPN#429]
How to use only SoftEther client for peer to peer or mesh network?
Is there such an option in SoftEther?
I would like clients to see each other without dependence on the server and work fine.

**Comment by jack2007** [comment]
It's not possibe now. Client must connect to the same hub of the same vpn server to see each other.

**Comment by Nemesiz** [comment]
In Linux I use SoftEther server soft as server and as client. You create 1. hub 2. bridge tap for hub 3. cascade connection to another server. So it is work around for peer-to-peer

**Comment by zero77** [comment]
@legionpheonix 
This may or may not be of use to you, its a Peer-to-peer VPN .
https://github.com/ntop/n2n
