### ISSUE TITLE
Request a tag

### ISSUE THREAD

**Issue by cicku** [SoftEtherVPN/SoftEtherVPN#43]
Hi,

I hope you can tag the releases as a good habit can keep your project in good status.

I'm going to package it into Fedora & EPEL.

Thanks.

**Comment by moatazelmasry2** [comment]
@cicku . The project has now some new board members (me included)  and we will try to take care of these stuff in the sfuture. 

Did you manage to pack it into Fedora and EPel??

**Comment by cicku** [comment]
Why not 😃

**Comment by moatazelmasry2** [comment]
why not what??

**Comment by moatazelmasry2** [comment]
A new release tag has been created on github containing the release binaries
https://github.com/SoftEtherVPN/SoftEtherVPN/releases/tag/v4.24-9651-beta
This will hopefully be automated in the future
