### ISSUE TITLE
Extend Travis CI build matrix to cover ARM

### ISSUE THREAD

**Issue by paulmenzel** [SoftEtherVPN/SoftEtherVPN#432]
Make sure the build does not break on different architectures to avoid problems as in pull request [#419][1].

[1]: https://github.com/SoftEtherVPN/SoftEtherVPN/pull/419

**Comment by moatazelmasry2** [comment]
Hi @paulmenzel  you already did some work on this. Would you kindly create a PR with your changes from https://github.com/paulmenzel/SoftEtherVPN/commits/integrate-travis-ci ??

**Comment by chipitsine** [comment]
I did some investigation towards armh builds.
currently softethervpn is not friendly for cross-builds at all.

so, we have to choose from
1. do nothing
2. modernize build system to support cross builds (and use travis-ci)
3. upload sources to launchpad (it builds natively as far as I seen)

**Comment by paskal** [comment]
armhf builds for all supported Ubuntu version (https://code.launchpad.net/~paskal-07/+archive/ubuntu/softethervpn/+packages) on Launchpad.
I think this issue should be reviewed, a lot changed since March.

**Comment by muuvmuuv** [comment]
Is ARM support still something to be considered? Since macOS moved cmpletely to ARM and Windows also supports it now I think I should be considered.

**Comment by chipitsine** [comment]
I enabled macos-14 builds recently

https://github.com/SoftEtherVPN/SoftEtherVPN/actions/runs/8995375739

I think, we can close this issue. Travis-CI is not an option anymore (unless someone is going to invest into it)

**Comment by chipitsine** [comment]
as for Windows on ARM, currently it is not implemented in any public CI/CD unfortunately

**Comment by muuvmuuv** [comment]
> I enabled macos-14 builds recently

Any issue I can subscribe to, to receive a notification when a ARM build for macOS is available, or will it be on the GH release page?

> as for Windows on ARM, currently it is not implemented in any public CI/CD unfortunately

Oh ok, so this is something somebody needs to compile locally from source.

**Comment by chipitsine** [comment]
<img width="857" alt="image" src="https://github.com/SoftEtherVPN/SoftEtherVPN/assets/2217296/552dce58-b66a-4590-9b9f-8851ca6e259d">


not sure what you mean by subscribing an issue. macos-14 is enabled

**Comment by muuvmuuv** [comment]
Sometimes authors make issues for thinks like that to provide feedback about the process until a release build is made.
Yes I saw that already but I cannot download the build from there, so I was asking if it will be available on the release page here or somewhere else. Because I can subscribe to release here on GH to be notified :)

**Comment by chipitsine** [comment]
scope of this particular issue was adding CI on ARM. it was done.
I didn't mean ARM releases (at least within this issue)

currently, with the help of @barracuda156 , releases are done on MacPorts https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1884#issuecomment-1679671617

(we still did not add any link to them)

maybe it makes sense to extend macos-14 build to releases, if you have an appepitite for that, you are welcome to contribute
