### ISSUE TITLE
OpenVPN loses connection, Authenticate/Decrypt packet error: missing payload

### ISSUE THREAD

**Issue by redeaglekiller** [SoftEtherVPN/SoftEtherVPN#434]
Hi, i have a problem with the vpnserver.
When I try to connect to the server via OpenVPN Clone function on port UDP443 (or TCP) with the OpenVPN Client (version 2.44-l601) using username/password authentification, I'm able to authenticate successfully. 

After I got an address from the DHCP server the error "Authenticate/Decrypt packet error: missing payload" occurs on the client side and the client looses connection right after.

On the server side this message occurs in the logs: 
"Connection "CID-46" terminated by the cause "The VPN session has been deleted. It is possible that either the administrator disconnected the session or the connection from the client to the VPN Server has been disconnected." (code 11).
2018-01-23 17:10:41.254 Connection "CID-46" has been terminated."

When I try to connect with the SoftEtherVPN client, there are no problems, but I need the server to work with both OpenVPN and SoftEther VPN Clients.

I use pretty much the default configuration of the server and I can't find any information about the missing payload error.

Does anyone have the same problem??

Let me know if you need any logs or files.

Versions:
OS: Debian 9.3 32-bit
Softether server version; 4.23 (build 9647) 32-bit (i cloned and compiled yesterday)
OpenVPN Client version: 2.44-l601

**Comment by redeaglekiller** [comment]
I resolved the issue by using libssl1.0.0-dev during build instead of the libssl1.1.0-dev (default in debian stretch).

I resolved the issue. Please close.

**Comment by davidebeatrici** [comment]
After some testing, I found out that the problem only happens with OpenSSL 1.1.0f.

Newer and older versions work fine, meaning that it's probably a regression introduced in `1.1.0f` and then fixed in `1.1.0g`.

Debian Stretch users should install [`libssl1.1`](https://packages.debian.org/sid/libssl1.1) from the `sid` branch, as a temporary workaround.

**Comment by chipitsine** [comment]
Any chance of unit test for that))?
