### ISSUE TITLE
I provide docker image

### ISSUE THREAD

**Issue by aicochow** [SoftEtherVPN/SoftEtherVPN#435]
I provide docker image.
This is the up to date version of softether.
I tested both Kubernetes and Docker

[docker hub](https://hub.docker.com/r/eiko/softethervpn/)
[git hub](https://github.com/aicochow/SoftEtherVPN)

**Comment by chipitsine** [comment]
can you please share details of how to use it ?

typical use cases, examples ... it would be nice if you can provide PR on current docs

**Comment by domosekai** [comment]
This is not an issue.
