### ISSUE TITLE
Hub traffic through socks5

### ISSUE THREAD

**Issue by tellst1** [SoftEtherVPN/SoftEtherVPN#436]
Hello, explain me is it possible to make the hub traffic went through socks5 proxies?

**Comment by BlackHoleFox** [comment]
You would need to setup some kind of routing rule outside of SoftEther to send the traffic from the SoftEther server through a proxy, if its possible. To my knowledge, SoftEther has no inbuilt ability to send traffic through a proxy.

**Comment by domosekai** [comment]
Close due to inactivity
