### ISSUE TITLE
VPN Gate public VPN Relay serves 

### ISSUE THREAD

**Issue by cisc0** [SoftEtherVPN/SoftEtherVPN#44]
In some countries like Iran the filtering firewall blocks http://vpngate.net so the VPN Gate VPN public VPN relay servers not updated How change this url to daily mirror URLs?

**Comment by moatazelmasry2** [comment]
Hmm. One idea is to use travis-ci or a similar tool to fetch the list from vpngate.net and create a daily commit on github. 
vpngate client can then be configured with a new mirror URL (github) to fetch the list from.

**Comment by chipitsine** [comment]
do you mean mirroring http://www.vpngate.net/api/iphone/ to some other URL ?
it might be done by anybody. just download that list and put it on you site.
make cron do it daily :)
