### ISSUE TITLE
push static route table to the client

### ISSUE THREAD

**Issue by github-joey** [SoftEtherVPN/SoftEtherVPN#441]
Excuse me, I want to know what version of softether cat push static route table to the client? I using as below can't push :

server -- softether-vpnserver-v4.22-9634-beta-2016.11.27-linux-x64-64bit.tar.gz
client -- softether-vpnclient-v4.22-9634-beta-2016.11.27-windows-x86_x64-intel.exe

**Comment by moatazelmasry2** [comment]
1. Open SoftEther Server Manager
2. Double Click on your hub name
3.  Click on "Virtual Nat and virtual DHCP Settings"
4. Click on SecureNAT Configurations
5. Click on the static routing table to push
6. Add whatever routes you want as described in that window

**Comment by itsKV** [comment]
@moatazelmasry2 What exactly has to be entered in static routing field? An example will help a lot.
