### ISSUE TITLE
vpnsever v4.23.9647 beta download speed drops to 20Mbits

### ISSUE THREAD

**Issue by francisuk1989** [SoftEtherVPN/SoftEtherVPN#442]
Recently i have installed vpnserver v4.23.9647 from ubuntu PPA using Ubuntu 16.04.3 LTS x64 now the issue i have is speeds are dropping over tiime as i installed 4.23.9647 tuesday so i did a speedtest with the windows vpn client and was getting roughly 95Mbits up and down what is great compared to OpenVPN  (i have tested OpenVPN but was only getting 5Mb up and down but this is another issue)

So today (Saturday) i connected to my softethervpn client via windows but im hit with 20Mbits Max! however my first thought was theres an issue with my server speeds dropping but again no issue with the server speed as i tryed a 500Mb HTTP file on the server iself and downloaded at 100Mbits so there must be a bug somewhere in softethervpn on beta v4.23.9647 that over time the speeds get slower.

i have tryed:
1)  tryed to reboot the server but still an issue to it been stuck to max of 20Mbits again run speedtest-cli but shows 1G down 1G upload so this is far from plently of bandwidth for my needs
2)  i have created another virtual hub named vpn2 but again 20Mbits max.

server spec

Ubuntu 16.04.3 LTS x64 (Linux Kernel 4.4.0-112-generic x86_64
Intel Xeon E3-1270v6 @ 3.80GHz (8 Core CPU)
32GB RAM (210MB used)
500GB SSD HDD
1G port

**Comment by domosekai** [comment]
Close due to inactivity
