### ISSUE TITLE
Android not working

### ISSUE THREAD

**Issue by tomgie** [SoftEtherVPN/SoftEtherVPN#443]
I am running the server on a CentOS server. I've tried to connect to the server(latest softether version) With oreo 8.1.0 and it never connects. It'll just timeout. If i put a port in like 4500 or 500 then it'll just deny the.connection right away.

**Comment by qbeukes** [comment]
Which android settings did you use?

**Comment by tomgie** [comment]
I use the ones that the tutorial on the site provided and I do have it enabled

**Comment by aicochow** [comment]
@tomgie I think you are using old version

**Comment by moatazelmasry2** [comment]
@tomgie This has been fixed on the master branch but not yet released in a binary. Please clone and build the binaries youself

**Comment by tomgie** [comment]
I've just cloned them and it still seems to not work. I can give one of you an example login and see if my settings are the problem or if its the Android version.

**Comment by davidebeatrici** [comment]
Superseded by #571.
