### ISSUE TITLE
Sort errors with label "Line Speed" 

### ISSUE THREAD

**Issue by NguyenPhucAn** [SoftEtherVPN/SoftEtherVPN#446]
It happened with version Windows 10 64-bit when I wanted to sort by max speed.
I'm using SoftEther ver 4.25 build 9656.
![image](https://user-images.githubusercontent.com/27940316/35969957-207d472e-0cfb-11e8-996d-d15fb36ba96b.png)

**Comment by moatazelmasry2** [comment]
Hi there. This is the Repo for SoftEther Software and not VPN Gate or relarted software. Please open this issue on their thread. 
vpnusers.com

**Comment by davidebeatrici** [comment]
Duplicate of #99.
