### ISSUE TITLE
Can VPN over DNS listen to specific IP address / network interfaces?

### ISSUE THREAD

**Issue by metalefty** [SoftEtherVPN/SoftEtherVPN#447]
VPN over DNS feature always listen on any IP adresses, any interfaces (`0.0.0.0:53`). 
I really appreciate if I could configure vpnserver to listen on specific network interfaces or IP addresses. 

AFAIK it is not possible so far. This is a feature request.

**Comment by metalefty** [comment]
The purpose is to run a local DNS resolver which listens on `127.0.0.1:53` and use VPN over DNS together.

**Comment by metalefty** [comment]
ping

**Comment by davidebeatrici** [comment]
See #777.
