### ISSUE TITLE
Android client?

### ISSUE THREAD

**Issue by connLAN** [SoftEtherVPN/SoftEtherVPN#453]
I means use  mostly softethervpn code( with  some  extra wrap  work ) to  build android client like windows one.  I just wonder is it possible in theory.  Any advise is appreciated.

Android SDK provide VpnService class( java ,  https://developer.android.com/reference/android/net/VpnService.html  ) to build vpn app, the core function is VpnService.Builder(), which return in interface, it create a virtual interface,  use netfilter hack input/output traffic to this  virtual interface, and connect to vpn-server. Then do recv()/ send() on returned interface handler. This sounds some similiar with softethervpn, but not exactly the same.  I am not clear this idea is possible or not? If not , why?  

Thank you for reading my question.

**Comment by tidatida** [comment]
the below articles give detail of use android vpnservice:  https://www.thegeekstuff.com/2014/06/android-vpn-service/

**Comment by tidatida** [comment]
I tried to built android version on ubuntu, too much error, I can't find a good start.  :(

**Comment by reza5858** [comment]
- [ ]

**Comment by tidatida** [comment]
But I can't get it.

**Comment by moatazelmasry2** [comment]
Which VPN protocol are you trying to use?

**Comment by aicochow** [comment]
If you can implement https protocol, that is great

**Comment by tidatida** [comment]
@moatazelmasry2  @aicochow  I just want use native softether-protocol , including all feathures like windows client.

**Comment by davidebeatrici** [comment]
There is a client available on Play Store, which requires root permissions in order to work: https://play.google.com/store/apps/details?id=io.github.lfasmpao.softethervpn

The repository on GitHub is not up-to-date though: https://github.com/lfasmpao/softethervpn-android

**Comment by davidebeatrici** [comment]
Superseded by #1019.
