### ISSUE TITLE
implement virtual network independently of microsoft / windows

### ISSUE THREAD

**Issue by Axe-Usa** [SoftEtherVPN/SoftEtherVPN#457]
hello when will be this feature?
I get some errors in my windows and i think using your own virtual network will be more easy to setup it!

**Comment by BlackHoleFox** [comment]
The only thing from Microsoft that they are using is a "clone" of MS's SSTP VPN server and then authentication inside of a Windows NT Domain. You dont have to use either of these options, so you could set this up on a Linux box, disable the "MS-SSTP" server and use any authentication method but "Windows NT Domain Controller or Windows Server Active Directory Controller" and you would not be using a single thing related to MS.
