### ISSUE TITLE
sofEther VPN Protocol client to Android

### ISSUE THREAD

**Issue by hnqoliveira** [SoftEtherVPN/SoftEtherVPN#46]
Has some possibility to implement a client to Android Plataform ?
If do, how can I help ?

**Comment by moatazelmasry2** [comment]
As far as I know, no there is no SoftEther client for Android.

How can you help? Good question. Can you programm android apps?

**Comment by demon-ru** [comment]
sofEther VPN among his merits is the ability to bypass many locks that are powerless OpenVPN and L2TP.
But all this is useless until there's no client for Android which supports Protocol over https/dns/icmp.
It's very sad.

**Comment by fenice2** [comment]
What's wrong with running SoftEther in OpenVPN clone mode then using the android OpenVPN Client to access the server? I use it and it works well and I don't think I've ever seen anyone complain about the security of OpenVPN, unless you know otherwise. :)

**Comment by demon-ru** [comment]
https://en.wikipedia.org/wiki/Deep_packet_inspection

What's wrong is that it is blocked in some countries. And that means not working.
Otherwise, why use the SoftEtherVPN protocol via a https/dns/icmp?

**Comment by aicochow** [comment]
[Android L2TP Client Setup](https://www.softether.org/4-docs/2-howto/9.L2TPIPsec_Setup_Guide_for_SoftEther_VPN_Server/3.Android_L2TP_Client_Setup)
this tutorial use native android vpn client.
If you can implement client over https,that is great

**Comment by moatazelmasry2** [comment]
@aicochow L2TP uses port 1701 and it cannot be easily changed.

**Comment by davidebeatrici** [comment]
Superseded by #453.
