### ISSUE TITLE
[Security Issue] Force Creation of Root Certificate

### ISSUE THREAD

**Issue by pgwipeout** [SoftEtherVPN/SoftEtherVPN#461]
The current VPN Server generates a certificate consisting of vpn<random-string>.softether.net.
This makes VPN servers extremely easy to locate, that do not change the default certificate.
There are currently 43 hits on shodan.io for the default softether.net certificate.

The server should request the administrator generate their own certificate during initial setup.

**Comment by Dreyk007** [comment]
I agree. Such a function should be.
At one time I was surprised that there is no possibility to create a separate port for the admin login.

**Comment by BlackHoleFox** [comment]
By this, you mean the certificate specified under `Encryption and Network Settings`, correct? This could probably be fixed with a simple notification with instructions on how to change it, if actual generation would be unlikely.

**Comment by domosekai** [comment]
This is only true if the user uses the default DDNS service. It is easy to opt out at any time.
