### ISSUE TITLE
L2TP/IPSec PSK not working on Android Oreo 8.0 

### ISSUE THREAD

**Issue by zongo** [SoftEtherVPN/SoftEtherVPN#463]
I am finding an issue with Android  8.0 with latest RTM (Ver 4.25, Build 9656, rtm). 
Working on Windows 10 with no issue. Android  8.0 has no connection possible with error as per below:

03-13 13:35:19.624 16712 16712 I mtpd    : Connection established (socket = 8)
03-13 13:35:19.624 16712 16712 D mtpd    : Sending SCCRQ (local_tunnel = 60356)
03-13 13:35:21.626 16712 16712 D mtpd    : Timeout -> Sending SCCRQ
03-13 13:35:23.628 16712 16712 D mtpd    : Timeout -> Sending SCCRQ

It looks similar to issue #403 but can't really tell. 

Logcat attached in Debug mode. 
Thank you for your help
[Log_2018-03-13_13-36-41_A.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/1806897/Log_2018-03-13_13-36-41_A.txt)

**Comment by davidebeatrici** [comment]
Superseded by #571.
