### ISSUE TITLE
Suggestion: Better documentation for Linux Installs

### ISSUE THREAD

**Issue by wicknet** [SoftEtherVPN/SoftEtherVPN#466]
SoftEtherVPN project appears to suffer from a glut of info, much of which appears to be marketing oriented rather than designed to help users quickly install the product and start using it.

Strongly recommend the developers to check out [Pritunl's](https://github.com/pritunl/pritunl) page -  crystal clear and cogent instructions are provided to help a user install Pritunl and get online for nearly every major distro. 

Contrast that with SoftEtherVPN's instructions [here](https://github.com/SoftEtherVPN/SoftEtherVPN_Stable) and [here](http://www.softether-download.com/en.aspx)

FWIW!

**Comment by chipitsine** [comment]
feel free to open PR

**Comment by wicknet** [comment]
Apologies if this was construed as criticism, instead of constructive feedback. Speaking as a hobbyist (not a coder) who’s explored many interesting projects on Github, I can personally attest to the remarkable ease of spinning up an instance from scratch using Streisand, Pritunl, Algo, Nyr’s OpenVPN, or Wireguard scripts.

I must confess that despite wading through many pages of the manual and tutorials on the site, I still couldn’t figure out what to do after finishing make, create, move, etc, as I found the documentation confusing at best.

I’m sure there might be other users, like me, who’d love to try SoftEtherVPN but are limited by their “linux chops” and give up halfway during what appears to be a needlessly complicated install. 

An ansible script to automate the entire installation might be of immense help for rookies users like me.
