### ISSUE TITLE
Custom domain name instead xxxx.vpnazure.net

### ISSUE THREAD

**Issue by itsKV** [SoftEtherVPN/SoftEtherVPN#468]
It is not possible to use own custom domain name, say _vpn.custom.com_ instead _xxxxx.vpnazure.net_ as VPN server address. Is there any possibility to do so?
Simply using CNAME record does not work.

**Comment by moatazelmasry2** [comment]
Currently no. .vpnazure.net is hard coded into a header file

**Comment by MtCedarNet** [comment]
*.vpnazure.net is not a usual DDNS.
vpnazure.net is a server which act as reverse proxy for HTTPS.
Because this proxy distributes the connection to the server by SNI, CNAME can not be used for connecting this.

**Comment by itsKV** [comment]
As, Softether is open source, can we edit code and header file to use our own domain name? Can we run same reverse-proxy as like of vpnazure.net on our own server? 
Actually, I am working on a project which will require custom domain name as server address.
Guidance requested.
