### ISSUE TITLE
static IP and pushing routes

### ISSUE THREAD

**Issue by ashah976** [SoftEtherVPN/SoftEtherVPN#469]
I don't have my own DHCP server to assign address so I'm using the onboard virtual DHCP server.
However there's no options for static IP assignment.
If I assign the IP address from the client side then my static routes doesn't get pushed because its hasn't been pushed by DHCP.
Is there any way round this apart from creating routes on all my clients individually?

thanks

**Comment by domosekai** [comment]
Fixed in #1218
