### ISSUE TITLE
How to change protocol id to eacape GFW detect?

### ISSUE THREAD

**Issue by connLAN** [SoftEtherVPN/SoftEtherVPN#471]
Install any version softethervpn  server outside GFW,  then use SOFTETHERVPN SERVER MANAGER behind GFW   to config the searver,  GFW  will detect the vpn server and block it immediately.  So, is there anything  can do to escape GFW detect?  Thanks.

**Comment by aicochow** [comment]
@tidatida you can try my server.
https://gfw.netlify.com/

**Comment by tidatida** [comment]
@aicochow   From your tutorial I guess you setup a softether  sever.  As more as I know , L2TP  is very easy blocked by GFW.  Have you try to do sth to enhance SE SERVER ?  If you give me a test account , I'd like to test it for a few days.

**Comment by aicochow** [comment]
@tidatida 
1 Week Free Trial
[Apply for a test account](mailto:minicoolva@gmail.com?Subject=账号申请&amp;Body=账号：%0D%0A%0D%0A密码：%0D%0A%0D%0A留言：)

**Comment by moatazelmasry2** [comment]
What exactly is protocol id?

**Comment by tidatida** [comment]
@moatazelmasry2  , simplely speeking, protocol id is the flow patterns can be identified with others, for example, run one severv manager to connect any ip's 443 port, if it send back the right response, it is a se server.
