### ISSUE TITLE
Softether throws error for ECDSA based certs

### ISSUE THREAD

**Issue by arvindiotium** [SoftEtherVPN/SoftEtherVPN#475]
I built softether from the latest sources (https://github.com/SoftEtherVPN/SoftEtherVPN.git). On vpnserver, I tried to set a cert for a user but vpnserver does not understand ECDSA based certs.

Does Softether support ECDSA based certs?

VPN Server/testHub>usercertset test_cert
UserCertSet command - Set Individual Certificate Authentication for User Auth Type and Set Certificate
Read X.509 certificate from file name: /home/arvind/certs/inode-2018-03-05-16-21-46.pem

Error occurred. (Error code: 77)
The specified X509 certificate file does not contain a RSA 1024 bit or 2048 bit public key. SoftEther VPN software supports only RSA 1024 bit or 2048 bit certificates.
VPN Server/testHub>

VPN Server/testHub>usercertset test_cert
UserCertSet command - Set Individual Certificate Authentication for User Auth Type and Set Certificate
Read X.509 certificate from file name: /home/arvind/certs/vpn-ca-chain.crt

Error occurred. (Error code: 77)
The specified X509 certificate file does not contain a RSA 1024 bit or 2048 bit public key. SoftEther VPN software supports only RSA 1024 bit or 2048 bit certificates.
VPN Server/testHub>

**Comment by arvindiotium** [comment]
More information - this is linux/ubuntu setup.

**Comment by moatazelmasry2** [comment]
Without looking deep into the source code, no I don't think that anything other than RSA for user authentication is supported

**Comment by arvindiotium** [comment]
@davidebeatrici Thanks so much for your response, appreciate it !

**Comment by davidebeatrici** [comment]
@arvindiotium You're welcome!

I would transform this issue into a feature request.
