### ISSUE TITLE
add "baking" capability to softethervpn

### ISSUE THREAD

**Issue by chipitsine** [SoftEtherVPN/SoftEtherVPN#478]
https://github.com/duplicati/duplicati - here's good example of using so called "baking" feature.
i.e. things people are willing to pay for.

should we enable such a feature for softethervpn ?

(I recall several issues, when nobody wanted to participiate, however, if people will to pay, it might open possibilities for them to hire developers)

**Comment by davidebeatrici** [comment]
I think it's a good idea.

I've seen many projects using Bountysource lately.

**Comment by chipitsine** [comment]
well, Bountysource may be another alternative

**Comment by chipitsine** [comment]
superceeded by https://github.com/SoftEtherVPN/SoftEtherVPN/issues/687
