### ISSUE TITLE
How to keep l2tp/ipsec connection alive with vpn server setting

### ISSUE THREAD

**Issue by chaosworld** [SoftEtherVPN/SoftEtherVPN#48]
Hi, sorry to bother you. I've try to search the answer in google and i am a newbie of system networking. So i'm really sorry to ask such an idiot question. 

I read the document of 'KeepSet' command (https://www.softether.org/4-docs/1-manual/6._Command_Line_Management_Utility_Manual/6.3_VPN_Server_%2F%2F_VPN_Bridge_Management_Command_Reference_(For_Entire_Server)#6.3.26_.22KeepEnable.22:_Enable_the_Keep_Alive_Internet_Connection_Function), and i didn't figure it out yet. 

And the reason i want to keep connection alive with vpn server setting is because iphone 5s doesn't have keep alive option. thanks for such a great software btw.

**Comment by moatazelmasry2** [comment]
Unfortunately this is an apple issue not a SoftEther issue. You need to install a VPN Profile with the "always on" feature enabled. Please see this article:
https://www.howtogeek.com/218851/how-to-enable-always-on-vpn-on-an-iphone-or-ipad/
