### ISSUE TITLE
How to print Debug info in Cedar /Mayaqua subdir  sources? 

### ISSUE THREAD

**Issue by tidatida** [SoftEtherVPN/SoftEtherVPN#486]

**Comment by tidatida** [comment]
I want to trace some code in Cedar/Mayaqua to monitor how it works. I can do this by adding printf( ... ) in linux os . But I don't know how to do  in windows. I know less about windows platform coding/debuging.  Thanks for any tips.

**Comment by davidebeatrici** [comment]
The "official" way would be to use Visual Studio 2008 with the Debug preset, so that you can see debug messages in the console.

**Comment by tidatida** [comment]
Thank you to @davidebeatrici  .  I add one debug print code in Win32PrintToFileW(), and view the debug print via dbgview.exe of sysinternal suites. It works for me. 

diff --git a/src/Mayaqua/Win32.c b/src/Mayaqua/Win32.c
index 20376ada..555ffc2c 100644
--- a/src/Mayaqua/Win32.c
+++ b/src/Mayaqua/Win32.c
@@ -3499,6 +3499,8 @@ void Win32PrintW(wchar_t *str)
 	{
 		return;
 	}
+	
+	OutputDebugStringW(str);
 
 	if (IsNt())
 	{

**Comment by davidebeatrici** [comment]
You're welcome.

Could you create a pull request, please?

Viewing debug messages via [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) or [DebugView++](https://github.com/CobaltFusion/DebugViewPP) can be useful for many people.

**Comment by tidatida** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/489

**Comment by davidebeatrici** [comment]
Thank you very much!

**Comment by tidatida** [comment]
My pleasure.
