### ISSUE TITLE
since commit  83295bb generated Openvpn configs need manual editing to allow connection

### ISSUE THREAD

**Issue by maurerr** [SoftEtherVPN/SoftEtherVPN#492]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [x] Can you reproduce?
yes
* [x] Are you running the latest version of SoftEtherVPN?
yes

**SoftEther version:**
Version: 5.01, Build: 9657
**Component:** [Server, Client, Bridge, etc.]
server
**Operating system:** [Windows, Linux, BSD, macOS, etc.]
ubuntu server 16.04.4
**Architecture:** [64 bit, 32 bit]
64bit

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]
intel nuc dn2820fykh

### Description
[Description of the bug]
after updating the softether server to version 5.01.9657 my openvpn client cannot connect to softether

**Expected behavior:**
[What you expected to happen]
Connect successfull

**Actual behavior:**
[What actually happened]
openvpn 2.4.5 client (x64 windows 7) log:
Tue Apr 17 10:58:08 2018 AUTH: Received control message: AUTH_FAILED
Tue Apr 17 10:58:08 2018 SIGUSR1[soft,auth-failure] received, process restarting
Tue Apr 17 10:58:08 2018 MANAGEMENT: >STATE:1523951888,RECONNECTING,auth-failure,,,,,

### Steps to reproduce

download the softether openvpn config from softether manager and try to connect with openvpn L2 (tap in my case - although probably it's the same for L3 config)
server log:
2018-04-17 10:58:08.488 [HUB "myhub"] The connection "CID-30" (IP address: <x.y.z.w>, Host name: <x.y.z.w>, Port number: 61610, Client name: "OpenVPN Client", Version: 5.01, Build: 9657) is attempting to connect to the Virtual Hub. The auth type provided is "OpenVPN certificate authentication" and the user name is "myuser".
2018-04-17 10:58:08.488 [HUB "myhub"] Connection "CID-30": User authentication failed. The user name that has been provided was "myuser".
2018-04-17 10:58:08.488 OpenVPN Session 29 (<x.y.z.w>:61610 -> 0.0.0.0:5333) Channel 0: Failed to connect a channel.

Please revert the commit 83295bb736d282940a79f0bd2c1a4e45910101cf and or make sure a config switch is implemented with default to: "External server authentication" instead of "OpenVPN certificate authentication"

thanks

**Comment by davidebeatrici** [comment]
The auth type is "OpenVPN certificate authentication" because your client configuration contains a certificate and a key.

See [my comment](https://github.com/SoftEtherVPN/SoftEtherVPN/pull/327#issuecomment-380305697) in #327.

**Comment by moatazelmasry2** [comment]
Hi @maurerr . Does the answer from @davidebeatrici resolves your issue? 
Basically removing private/public key and use the correct server certificate should solve the problem

**Comment by maurerr** [comment]
It's a good workaround however I would prefer to see a code fix to this issue. Like removing dummy key/cert from generated ovpn config file

**Comment by moatazelmasry2** [comment]
I agree that this issue should be fixed, but the dummy configuration has been there forever, so 83295bb does not really break openvpn. 
So in my humble openion, there are two ways to go. Either this issue should be renamed to reflect the request it is adressing, or we close this issue and you can open a new issue requesting this dummy cert to be fixed. But in the current state, the title is misleading

**Comment by maurerr** [comment]
Closing it

**Comment by maurerr** [comment]
reopened issue with edited name

**Comment by moatazelmasry2** [comment]
But this behavior was there way before this commit happened!!

**Comment by moatazelmasry2** [comment]
The behavior is wrong, but it has nothing to do with this commit

**Comment by maurerr** [comment]
well, now it needs a code fix - because that commit broke connection for all setups using generated config files.
As a result of the commit - all generated configs are useless without manual editing - what's the point of auto-generated config files?

**Comment by davidebeatrici** [comment]
It asks for the credentials because `auth-user-pass` is specified in the configuration.
