### ISSUE TITLE
Please increase ping-restart param for openvpn compatible server

### ISSUE THREAD

**Issue by bdfy** [SoftEtherVPN/SoftEtherVPN#495]
My stupid ARM router does not have time to connect openvpn compatible server. I'm forced to increase this parameter and recompile the sources. It is very uncomfortable. Or put this parameter to config file.

+#define	OPENVPN_RECV_TIMEOUT					60000	// Communication time-out

I see on the forum that the problem is relevant for stupid routers:
http://www.vpnusers.com/search.php?keywords=ping-restart

**Comment by davidebeatrici** [comment]
I think that 30 seconds for the ping transmission interval and 120 seconds for the communication timeout are too high.

I would set the ping transmission interval to 10 seconds and the communication timeout to 30 or 60 seconds.

What do you think?
