### ISSUE TITLE
 invalid numbering for build rtm version

### ISSUE THREAD

**Issue by bdfy** [SoftEtherVPN/SoftEtherVPN#496]
if I compile a deb package from the stable version ( https://github.com/SoftEtherVPN/SoftEtherVPN_Stable) , result:

softether-vpnbridge_4.04.9412-rtm_amd64.deb
softether-vpnserver_4.04.9412-rtm_amd64.deb
softether-vpnclient_4.04.9412-rtm_amd64.deb
softether-vpncmd_4.04.9412-rtm_amd64.deb     

but last stable version - v4.25-9656-rtm

**Comment by moatazelmasry2** [comment]
Ok, but shouldn't this issue be created in the stable fork?

**Comment by davidebeatrici** [comment]
Issues are disabled in the stable repository.

**Comment by moatazelmasry2** [comment]
Crap!
