### ISSUE TITLE
Is SoftEther's VPN Protocol (Ethernet over SSL) support PFS(perfect forward secrecy)?

### ISSUE THREAD

**Issue by bobwenx** [SoftEtherVPN/SoftEtherVPN#52]
Is SoftEther's VPN Protocol (Ethernet over SSL)  support perfect forward secrecy just like OpenVPN's tls-auth?
PFS is on SSL/TLS, which is used by OpenVPN and SoftEther's VPN Protocol.
OpenVPN with double certificate authentication in TLS mode (as implemented in Air) provides forward security. New encryption key is negotiated every hour by default ("re-keying").

**Comment by PacoBell** [comment]
For future reference, they technically did publicly announce PFS support for SSL about 8 days before the above comment. 

https://www.softether.org/5-download/history
