### ISSUE TITLE
VPN Client Adapter Not detected as ethernet connection in Windows 10 Spring Creators Update (version 1803)

### ISSUE THREAD

**Issue by Romneel** [SoftEtherVPN/SoftEtherVPN#527]
**SoftEther version:** SoftEther VPN 4.27 Build 9666 Beta (April 21, 2018)
**Component:** [Client]
**Operating system:** [Windows]
**Architecture:** [64 bit]

Whenever  I try to connect in softether it is not detected as a network anymore, which was working in version 1709 before I updated to 1803. Normally after connection a network(names like Network followed by a number) would appear in the network tab but now it doesn't appear anymore whenever I try to connect

![image](https://user-images.githubusercontent.com/38980397/39628659-5586f784-4fdc-11e8-9d84-665da88bf25f.png)

In network status its connected as public network

![image](https://user-images.githubusercontent.com/38980397/39628947-2948f87e-4fdd-11e8-8654-cb9de5a86090.png)

But it doesn't appear in Ethernet which was working in 1709

![image](https://user-images.githubusercontent.com/38980397/39628979-415afa0c-4fdd-11e8-97cb-343a76bd3879.png)

Sorry for my bad english

**Comment by davidebeatrici** [comment]
Pull request: #508

**Comment by maurerr** [comment]
it's in the changelog of softether-stable http://www.softether.org/5-download/history

**Comment by davidebeatrici** [comment]
There's a bug in it: https://github.com/SoftEtherVPN/SoftEtherVPN/pull/511#discussion_r183244902

**Comment by krugdenis** [comment]
I have this problem too with the latest 9668 build. I can't use VPN adapter in WiFi HotSpot and can't change it's network location (private | public). Windows 1803.

**Comment by davidebeatrici** [comment]
Did you reinstall the virtual network adapter driver?

**Comment by krugdenis** [comment]
Yes, I've reinstalled them, drivers' version is .9658

**Comment by krugdenis** [comment]
Windows 10 (version 1809) - problem still exists

**Comment by davidebeatrici** [comment]
#508 changed the virtual network adapter's type to `IF_TYPE_PROP_VIRTUAL`, as explained there: https://support.microsoft.com/en-us/help/2919900/windows-connection-manager-disconnects-wlan-if-a-vpn-connection-is-est.

The network adapter not appearing in the list is a Windows issue.
