### ISSUE TITLE
Discussion: Why are the libraries Mayaqua and Cedar linked statically?

### ISSUE THREAD

**Issue by cm0x4D** [SoftEtherVPN/SoftEtherVPN#533]
Hello SoftEtherVPN community,

We are using SoftEtherVPN on an embedded system with very limited disk capacity. The actual makefiles build the libraries Mayaqua and Cedar statically and links the executables vpnserver, vpnclient, vpnbridge and vpncmd to them. As 99% of the SoftEtherVPN code is in Mayaqua and Cedar, this results in 4 quite big executables whereas it would be possible to have a total package size of about 4MB and not 9.3 MB if all executables would be linked dynamically to the Mayaqua and Cedar libraries build as shared libs.

Here my experiment (using cmake) to build SoftEtherVPN using shared libraries: https://github.com/cm0x4D/SoftEtherVPN/tree/experiment/shared-libs

I did not test the resulting executables excessively, but it seems to work.

Is there any technical reason to build the libraries statically?

What would you think to have two build definitions for SoftEtherVPN on UNIX, a static and a dynamically linked version?

**Comment by cm0x4D** [comment]
Mayaqua and Cedar libraries can still be linked statically to OpenSSL itself I guess.

**Comment by chipitsine** [comment]
please ignore my deleted comment ))

I recall that we use 'ldd' in travis-ci builds. openssl is linked dynamically (from custom folder)

**Comment by davidebeatrici** [comment]
Superseded by #760.
