### ISSUE TITLE
Add support for modern TLS suites

### ISSUE THREAD

**Issue by BlackHoleFox** [SoftEtherVPN/SoftEtherVPN#536]
I noticed that in the spec for SoftEther it says "Both SSL 3.0 and TLS 1.0 are supported". I think that support for more modern (and secure) communication security protocols should be implemented, such as TLS 1.2 and TLS 1.3. In my opinion, SSL 3.0 support should be entirely removed, as modern CA's do not support this and the POODLE attack has broken any security it used to offer.

Best of days, Shadus

**Comment by BlackHoleFox** [comment]
Also if possible, it is also probably time to move to CHAP for RADIUS auth as PAP is not the best idea in terms of sending auth.

**Comment by chipitsine** [comment]
hello

will it break compatibility with earlier SE VPN clients?

**Comment by BlackHoleFox** [comment]
@chipitsine  Thanks for responding! To answer your questions, removing the SSL3 support, most likely. However, it would still be better then nothing to include support for TLS1.1 and 1.2 options for those who have updated clients and wish to use it. In terms of PAP auth that exists for RADIUS right now, no. As far as I can see the RADIUS auth is a server side setting only.

**Comment by chipitsine** [comment]
did you build SE with SSL3 removed and tested compatibility between different builds?

**Comment by BlackHoleFox** [comment]
I did not, sorry. I sadly do not know enough C to work with this project personally. I primarily just opened this issue as a possibility for implementing it in the future.

**Comment by chipitsine** [comment]
feel free to try :)

**Comment by BlackHoleFox** [comment]
@chipitsine So I removed all the headers that had SSL in them (I really am bad with C) and while the server built on it, a server manager that was properly built failed to connect to it due to a protocol error occurring. I had to build it on Linux as I couldn't even find a Visual Studio 2008 installer. So the answer to the question is that SSL3 support cannot be purged from the client and server, it breaks everything. TLS 1.2 support options would have to be added in extra with it to maintain compatibility.

**Comment by BlackHoleFox** [comment]
Well, I said that more in the crude way I removed SSL3 from it

**Comment by paulmenzel** [comment]
@blakestell’s comment in https://github.com/SoftEtherVPN/SoftEtherVPN/pull/208/ has ideas how to change the code to set the minimal versions.

**Comment by BlackHoleFox** [comment]
@chipitsine If I were to look into this again, would it be best to deprecate SSLv3 completely or to just add an option to use higher versions of TLS? I'm thinking option one would be against the developer guidelines though.

**Comment by davidebeatrici** [comment]
We deprecated SSLv3 in #594.

**Comment by BlackHoleFox** [comment]
Oh, seems I missed that PR being merged in. So now it uses TLS1.0 and 1.1?

**Comment by davidebeatrici** [comment]
TLS 1.0, 1.1 and 1.2.

**Comment by BlackHoleFox** [comment]
Oh, awesome. I would assume it defaults to the highest supported on both ends. As 1.2 counts as "modern", this issue is probably closable i'd imagine.

**Comment by davidebeatrici** [comment]
> I would assume it defaults to the highest supported on both ends.

Right.

> As 1.2 counts as "modern", this issue is probably closable i'd imagine.

Done.

**Comment by BlackHoleFox** [comment]
Thanks! I'm glad i'll be able to recommend this project to others with no apparent downsides anymore :)

**Comment by davidebeatrici** [comment]
You're welcome!
