### ISSUE TITLE
Cant compile SoftEther on Debian 9

### ISSUE THREAD

**Issue by Adrian-Voelker** [SoftEtherVPN/SoftEtherVPN#541]
### Prerequisites

* [ x] Can you reproduce?
* [ x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** [5.1]
**Component:** [Server]
**Operating system:** [Windows, Linux, BSD, macOS, etc.]
**Architecture:** [64 bit]

### Description

Can't make and install the SoftEtherVPN even though i installed all dependencies mentioned in issue #301.

**Expected behavior:**
./configure
make

**Actual behavior:**
Error:

tmp/objs/Mayaqua/Encrypt.o: In function `Enc_tls1_P_hash':
Encrypt.c:(.text+0x175d): undefined reference to `HMAC_CTX_new'
Encrypt.c:(.text+0x1765): undefined reference to `HMAC_CTX_new'
Encrypt.c:(.text+0x1882): undefined reference to `HMAC_CTX_free'
Encrypt.c:(.text+0x188a): undefined reference to `HMAC_CTX_free'
tmp/objs/Mayaqua/Encrypt.o: In function `FreeMd':
Encrypt.c:(.text+0x2006): undefined reference to `HMAC_CTX_free'
tmp/objs/Mayaqua/Encrypt.o: In function `NewMd':
Encrypt.c:(.text+0x2060): undefined reference to `HMAC_CTX_new'
tmp/objs/Mayaqua/Encrypt.o: In function `RsaPublicToBuf':
Encrypt.c:(.text+0x2442): undefined reference to `EVP_PKEY_get0_RSA'
Encrypt.c:(.text+0x2458): undefined reference to `RSA_get0_key'
tmp/objs/Mayaqua/Encrypt.o: In function `NewExtendedKeyUsageForX509':
Encrypt.c:(.text+0x2ca7): undefined reference to `OPENSSL_sk_new_null'
Encrypt.c:(.text+0x2d40): undefined reference to `OPENSSL_sk_pop_free'
tmp/objs/Mayaqua/Encrypt.o: In function `LoadXDates':
Encrypt.c:(.text+0x33fd): undefined reference to `X509_get0_notBefore'
Encrypt.c:(.text+0x3411): undefined reference to `X509_get0_notAfter'
tmp/objs/Mayaqua/Encrypt.o: In function `RsaVerifyEx':
Encrypt.c:(.text+0x3579): undefined reference to `EVP_PKEY_get0_RSA'
tmp/objs/Mayaqua/Encrypt.o: In function `RsaSignEx':
Encrypt.c:(.text+0x3665): undefined reference to `EVP_PKEY_get0_RSA'
tmp/objs/Mayaqua/Encrypt.o: In function `NewX509.part.13':
Encrypt.c:(.text+0x4520): undefined reference to `X509_getm_notBefore'
Encrypt.c:(.text+0x452c): undefined reference to `X509_getm_notAfter'
tmp/objs/Mayaqua/Encrypt.o: In function `NewRootX509':
Encrypt.c:(.text+0x4836): undefined reference to `X509_getm_notBefore'
Encrypt.c:(.text+0x4843): undefined reference to `X509_getm_notAfter'
tmp/objs/Mayaqua/Encrypt.o: In function `X509ToX':
Encrypt.c:(.text+0x4fdf): undefined reference to `OPENSSL_sk_num'
Encrypt.c:(.text+0x4fed): undefined reference to `OPENSSL_sk_value'
tmp/objs/Mayaqua/Encrypt.o: In function `InitCryptLibrary':
Encrypt.c:(.text+0x5a45): undefined reference to `OPENSSL_init_ssl'
Encrypt.c:(.text+0x5a51): undefined reference to `OPENSSL_init_crypto'
Encrypt.c:(.text+0x5a5d): undefined reference to `OPENSSL_init_crypto'
Encrypt.c:(.text+0x5a69): undefined reference to `OPENSSL_init_crypto'
Encrypt.c:(.text+0x5a75): undefined reference to `OPENSSL_init_ssl'
tmp/objs/Mayaqua/Encrypt.o: In function `DhNew':
Encrypt.c:(.text+0x6d24): undefined reference to `DH_set0_pqg'
Encrypt.c:(.text+0x6d3c): undefined reference to `DH_get0_key'
tmp/objs/Mayaqua/Encrypt.o: In function `AddKeyUsageX509':
Encrypt.c:(.text+0x2c8d): undefined reference to `OPENSSL_sk_push'
tmp/objs/Mayaqua/Secure.o: In function `WriteSecKey':
Secure.c:(.text+0x12e4): undefined reference to `EVP_PKEY_get0_RSA'
Secure.c:(.text+0x1304): undefined reference to `RSA_get0_key'
Secure.c:(.text+0x131a): undefined reference to `RSA_get0_factors'
Secure.c:(.text+0x133b): undefined reference to `RSA_get0_crt_params'
collect2: error: ld returned 1 exit status

**Comment by moatazelmasry2** [comment]
How did you Download the source code?? From this git repo??

**Comment by Adrian-Voelker** [comment]
Yes I did.

**Comment by moatazelmasry2** [comment]
It looks like you are missing openssl somehow.

Could you please tell me the output of `openssl version` and also paste the output of `./configure` command

**Comment by chipitsine** [comment]
```
./configure
make
```

does not work after cmake:

https://gitlab.com/chipitsine/SoftEtherVPN/-/jobs/70356321

however, error message is different from you observe

**Comment by chipitsine** [comment]
@davidebeatrici , we should update BUILD_WINDOWS with "make -C tmp"

**Comment by davidebeatrici** [comment]
@chipitsine What do you think about creating a new script called `build`, which calls `make` in the `tmp` folder?

**Comment by chipitsine** [comment]
I think about more traditional

```
./configure
make
```

without "-C tmp"

**Comment by davidebeatrici** [comment]
```
./configure
cd tmp
make
```
?

**Comment by moatazelmasry2** [comment]
@Adrian-Voelker I just created a digital ocean instance with debian 9 installed and successfully compiled SoftEther. 

Here's what I did on a brand new machine:

```
sudo apt-get update
sudo apt -y install cmake gcc libncurses5-dev libreadline-dev libssl-dev make zlib1g-dev git
git clone https://github.com/SoftEtherVPN/SoftEtherVPN.git
cd SoftEtherVPN
./configure
make -C tmp
```

**Comment by chipitsine** [comment]
@davidebeatrici  , I mean something like that

https://github.com/chipitsine/SoftEtherVPN/commit/6557532b1316e04655965f928af214a07ddd5d72

**Comment by davidebeatrici** [comment]
@chipitsine I don't think it's a good idea, because all of the build files are created into the source code folders.

**Comment by chipitsine** [comment]
well, anyway BUILD_UNIX is incosistent, we should update "make" with "make -C tmp"

if you do not like my idea, let follow your way

**Comment by moatazelmasry2** [comment]
You guys agree on an approach and proceed. I've seen both solutions quite often, but `make` without extra arguments is definitely more popular.

The decision will affect PR #530. Also this issue is not the right place to have this discussion (in my opinion). Please create an issue for that if necessary.

**Comment by moatazelmasry2** [comment]
@Adrian-Voelker  Has your problem been solved?

**Comment by Adrian-Voelker** [comment]
Hey Guys. Please excuse my belated answer.

After i did it like @moatazelmasry2  did on a brand new maschine, it worked!

Thank you for helping.
