### ISSUE TITLE
Question: does that SoftEtherVPN officially support ARM64 (running in Ubuntu 1804 ARM64) now?

### ISSUE THREAD

**Issue by scegg** [SoftEtherVPN/SoftEtherVPN#547]
I build a busybox with RPi 3b+ with Ubuntu 1804 ARM64. I didn't get any info about ARM64 support of SoftEther.

Thanks for your information.

**Comment by chipitsine** [comment]
sure,  https://github.com/SoftEtherVPN/SoftEtherVPN#for-ubuntu

(just noticed, we have break them recently, need to fix)

**Comment by scegg** [comment]
Thanks.  I’ll wait for the next release and make it from here.

**Comment by genez** [comment]
Hi, any news on support for ARM64?

**Comment by davidebeatrici** [comment]
Hi, ARM64 is supported.

**Comment by genez** [comment]
Hello, I am trying to build vpnclient on a NanoPi 2 NEO PLUS

The architecture is `Linux NanoPi-NEO-Plus2 4.14.52 #94 SMP Thu Jun 28 18:34:19 CST 2018 aarch64 aarch64 aarch64 GNU/Linux`

I downloaded both ARM32 EABI and ARM32 legacy EABI but the "make" script fails with the following error:

`make[1]: Entering directory '/home/pi/vpnclient'
Preparing SoftEther VPN Client...
ranlib lib/libcharset.a
ranlib lib/libcrypto.a
ranlib lib/libedit.a
ranlib lib/libiconv.a
ranlib lib/libncurses.a
ranlib lib/libssl.a
ranlib lib/libz.a
ranlib code/vpnclient.a
gcc code/vpnclient.a -O2 -fsigned-char -pthread -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a -o vpnclient || gcc -no-pie code/vpnclient.a -O2 -fsigned-char -pthread -lm -ldl -lrt -lpthread -L./ lib/libssl.a lib/libcrypto.a lib/libiconv.a lib/libcharset.a lib/libedit.a lib/libncurses.a lib/libz.a -o vpnclient
code/vpnclient.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
code/vpnclient.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
`

**Comment by davidebeatrici** [comment]
Hello, the build fails because the objects are built for ARM32.

You should build SoftEther VPN from this repository using CMake: https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/BUILD_UNIX.md#build-from-source-code-and-install

**Comment by genez** [comment]
Thank you, I am now building CMake and trying to update all required dependencies.
I would be usefull to have a binary package ready for deployment

**Comment by davidebeatrici** [comment]
Ubuntu packages are available in @paskal's PPA repository: https://launchpad.net/~paskal-07/+archive/ubuntu/softethervpn/+packages
