### ISSUE TITLE
Upload to slow.

### ISSUE THREAD

**Issue by spirritus** [SoftEtherVPN/SoftEtherVPN#549]
### Prerequisites

* [yes] Can you reproduce?
* [yes] Are you running the latest version of SoftEtherVPN?

**SoftEther version: 4.27 Build 9667
**Component:Server, Bridge
**Operating system: Linux Server
**Architecture:64 bit

**Processor: Server runs on Intel(R) Atom(TM) CPU  C2550  @ 2.40GHz

### Description

The Servers upload is ridiculously slow. Donwload is fine.

**Expected behavior:**
Nearly same upload as donwload speed.

**Actual behavior:**
Testsed with the "Network Traffic Speed Test Tool":
On a 100mbit/100mbit 20ms internet connection the:
Upload from the vpn server to the client is painfully slow with around 300Kbps.
Download is fine with around 8Mpbs.
(Client has 40mbit/80mbit 50ms connection [up/down])

Softether vpn is an amazing vpn server. But this "speedbrake" makes it virtually unusable.
Please fix this. If you need more information I am happy to comply.

[vpn_server.config.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/2054888/vpn_server.config.txt)

**Comment by vampywiz17** [comment]
try this!

It is a temp. sollution, but working to me.

https://github.com/SoftEtherVPN/SoftEtherVPN/issues/553

**Comment by davidebeatrici** [comment]
Hello,

Did the issue appear with the latest version?

**Comment by spirritus** [comment]
Hi, nope this issue has always been there as far as i could tell at least since 4.19 Build 9605. I just now manged to report :-)

**Comment by vampywiz17** [comment]
@davidebeatrici if you check this issue, you will say that we found a "workaround" to solve the problem, but we don't know the "source" problem...

https://github.com/SoftEtherVPN/SoftEtherVPN/issues/553
