### ISSUE TITLE
Help please with OpenVPN client + certificates authorization

### ISSUE THREAD

**Issue by avel9** [SoftEtherVPN/SoftEtherVPN#55]
Hello. Came here to ask to solve my problem.
System: FreeBSD 9.2 x64, CentOS 6.5 x64, Ubuntu 14.04 x64 (tried all of them)
Client: Windows XP SP3 openvpn-install-2.3.4-I001-i686
SoftEther VPN Server 4.06 Build 9437

I am trying to authorise users without password, just by certificates(with OpenVPN client). Made CA certificate, installed to SoftEther, made certificate for client, added to .ovpn file and to softether. But when I try to connect always getting error:

Sun May 25 00:00:00 2014 us=15625 AUTH: Received control message: AUTH_FAILED
Sun May 25 00:00:00 2014 us=15625 TCP/UDP: Closing socket

Password auth works like a charm!

So maybe somebody figured that problem? Or how to make it work.

Logs:
http://pastebin.com/crgs6PVa
http://pastebin.com/n3qB06EH
http://pastebin.com/rXURRVqW

SE config http://pastebin.com/cFLYVub2
OVPN http://pastebin.com/AsY8H7tW

**Comment by bjdag1234** [comment]
Isn't it available in your vpngate implementation? or is it because the vpngate server assumes a user vpn, as i can see vpngate openvpn certs have no user auth but only certs, I would like the same functionality on the SE VPN server, either no user auth and only certs or being able to give each user certs and authenticate them. Thanks!

**Comment by superpippo82xxx** [comment]
There are any update with this problem?

**Comment by eN-Joy** [comment]
@dnobori I am also interested in the most recent status of the feature. Thanks,

**Comment by m-emelchenkov** [comment]
Please let me know the state of the problem.

**Comment by ly2314** [comment]
Are there any update with this issue?

**Comment by alexsalex** [comment]
Is there any update on this issue?

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by er1z** [comment]
Any news on issue?

**Comment by vainkop** [comment]
Almost 4 years later & still no TLS auth support 👎

**Comment by fenice2** [comment]
@vainkop 

If you think this is important then submit a pull request.

You could, on the other hand, wait until the changes in the development model for this project become more effective - give the developers a chance to clean-up the code and make some progress with the development of this project.

**Comment by davidebeatrici** [comment]
Pull request: #327

**Comment by moatazelmasry2** [comment]
PR #327 has been merged into the master branch. Happy compiling

**Comment by er1z** [comment]
When could we expect to have a binary install?

**Comment by moatazelmasry2** [comment]
Hi guys, ideally we can create releases within travis-ci or appveyor. I'll try to either integrate the build binaries into one of the build tools, or just quickly create binaries and upload them. Cheers

**Comment by agfasaud** [comment]
Thanks, That's great

**Comment by agfasaud** [comment]
Hi, Any update on this.

Thanks

**Comment by agfasaud** [comment]
Hi Moataz, any update about the fixed release.
Regards

**Comment by davidebeatrici** [comment]
If you are on Windows, you can download the latest build from AppVeyor here: https://ci.appveyor.com/project/SoftEtherVPN/softethervpn/build/artifacts

**Comment by davidebeatrici** [comment]
You can install the package from @paskal's PPA repository: https://launchpad.net/~paskal-07/+archive/ubuntu/softethervpn/+packages

**Comment by chipitsine** [comment]
What Linux distribution do you use?

**Comment by agfasaud** [comment]
RASPBIAN LINUX "Minimal image based on Debian Stretch" for Raspberry Pi

I was using this package from softether download: http://www.softether-download.com/files/softether/v4.27-9668-beta-2018.05.29-tree/Linux/SoftEther_VPN_Server/32bit_-_ARM_EABI/softether-vpnserver-v4.27-9668-beta-2018.05.29-linux-arm_eabi-32bit.tar.gz

**Comment by chipitsine** [comment]
4.27 is "stable" edition of SoftEtherVPN. question of "stable" edition should be asked here: https://www.softether.org/7-forum

**Comment by chipitsine** [comment]
developer edition currently is not shipped for raspberry. you can build it from source.

if you know how to build for raspberry, we need you:)

**Comment by chipitsine** [comment]
softether forum is an official place where 4.27 build is supported, if you know better place, please suggest

**Comment by anthony143** [comment]
Please support AUTH PAM in the next update. Thanks...
