### ISSUE TITLE
coverity scan

### ISSUE THREAD

**Issue by chipitsine** [SoftEtherVPN/SoftEtherVPN#551]
@moatazelmasry2 , can you please enable coverity scan ?

I did this on my fork, there're interesting defects found by coverity, sure, many developers would want to have a look

https://scan.coverity.com/projects/chipitsine-softethervpn?tab=overview

how it was enabled from project side (to be discussed):
https://github.com/chipitsine/SoftEtherVPN/tree/coverity

**Comment by chipitsine** [comment]
I sent an invitation (in order to view defects)

**Comment by moatazelmasry2** [comment]
I received no invitation. But I'll try to check this tool today evening

**Comment by chipitsine** [comment]
![screenshot from 2018-05-29 13-29-41](https://user-images.githubusercontent.com/2217296/40647099-7b229e3c-6344-11e8-81f5-c7656971f8ef.png)

**Comment by macvk** [comment]
in my opinion it looks absolutely useless.

**Comment by chipitsine** [comment]
@macvk , do you mean "overview provided on screenshot" is useless? Or coverity in general (including detailed reports) is useless?

**Comment by moatazelmasry2** [comment]
Sorry. Still receiving nothing. Looked also in the spam folder and everywhere else

**Comment by moatazelmasry2** [comment]
But its not important, I can just setup a new account there anyway

**Comment by chipitsine** [comment]
@moatazelmasry2 , I took your email from github profile. is it correct ?

**Comment by moatazelmasry2** [comment]
Shit 
no: moataz dot elmasry2 at gmail.com

**Comment by moatazelmasry2** [comment]
Got it

**Comment by chipitsine** [comment]
Please update github profile))

Some employers might be searching you

**Comment by moatazelmasry2** [comment]
Done

**Comment by moatazelmasry2** [comment]
Ok. Saw the tool and read a bit of documentation. Here are my first thoughts:

- Cool. Could be useful
- why use own script instead of travis-ci addon?
- Do we really need this with every commit, or can we have a kind of a manual step or on demand somehow?

**Comment by moatazelmasry2** [comment]
To continue on this discussion, I see 2 situations where this is necessary:
1. PRs just before merge
2. Manual

**Comment by macvk** [comment]
I mean the whole tool is useless. )

**Comment by chipitsine** [comment]
@macvk , your opinion is valuable, however, what do you suggest to do (based on opinion provided by you) ?

**Comment by chipitsine** [comment]
@moatazelmasry2 there're coverity build limits

"Up to 21 builds per week, with a maximum of 3 builds per day, for projects with 100K to 500K lines of code"


I've no idea what happens when you build more often. Maybe nuclear war :) Most probably, extra builds would be dropped. Nothing to worry about.


as for PR, it is not possible to run "secure" travis-ci tokens with PR builds. it is considered as a security hole.

as for travis-ci addon, I could not manage to get it running with build matrix.


so, if we will build it several times a week, I think it is ok. Another common way is setup "coverity" git branch and merge it manually once a week. someone volunteer to do so ?
