### ISSUE TITLE
Latest Version of SoftEther VPN Server on x86_64 Ubuntu Breaks L2TP/IPSec Connections

### ISSUE THREAD

**Issue by 501ari5** [SoftEtherVPN/SoftEtherVPN#552]
Hello!

   The latest version of SoftEther VPN Server on x86_64 Ubuntu breaks connections initiated from Windows XP, which renders the system to be stuck at "Connecting to 1.2.3.4" instead of entering next phase of "Verifying user name and password...". This issue does not occur on Windows Vista and onwards. Can someone fix the issue?

* [ V ] Can you reproduce? -> Yes!
* [ V ] Are you running the latest version of SoftEtherVPN? -> Yes

**SoftEther version: Ver 4.27, Build 9668, beta
**Component:** Server
**Operating system:** Ubuntu 18.04 LTS
**Architecture:** 64-bit

**Processor:**: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz

### Description

Clients from Windows XP cannot establish connections to VPN server via L2TP/IPSec protocol.

**Expected behavior:**

Connections should be established successfully instead of hanging there.

**Actual behavior:**

Connections from Windows XP hang at "Connecting to W.X.Y.Z" instead of entering "Verifying user name and password..." phase.

### Steps to reproduce

1. Setup SoftEther VPN Server on x86_64 Ubuntu.
2. Establish L2TP/IPSec connections from Windows XP.
3. Windows XP cannot make connections to the server.
4. Try with Windows Vista and onwards to establish VPN tunnels via L2TP/IPSec.
5. Vista and onwards can reach the server and establish VPN tunnels via L2TP?IPSec successfully.

Hope to get your reply soon.

Thanks! Much appreciated!

Regards,

Andy

**Comment by maurerr** [comment]
windows XP is out of support from Microsoft.
Not even Firefox supports it.
you should move away from/upgrade it.
Use openvpn 2.3.18 as alternative

**Comment by chipitsine** [comment]
Ver 4.27, Build 9668, beta is related to https://github.com/SoftEtherVPN/SoftEtherVPN_Stable


anyway, I could not find a way to download WinXP, it's support ended.

can you try the following - install several latest builds and check every build on WinXP compatibility ?
thus we can find the change that breaks WinXP

**Comment by jartester** [comment]
I confirm this issue. The latest server build that runs properly on WinXP SP3 (no other Windows versions tested, just XP) is "softether-vpnserver_vpnbridge-v4.25-9656-rtm-2018.01.15-windows-x86_x64-intel.exe". I tested ALL higher versions (they are all betas) one by one and they all failed.

**Comment by jartester** [comment]
I confirm a similar issue.I am running SoftEther VPN server under winXP SP3 machines. The latest server build that runs properly on WinXP SP3 (no other Windows versions tested, just XP) and can successfully accept incoming L2TP connections is "softether-vpnserver_vpnbridge-v4.25-9656-rtm-2018.01.15-windows-x86_x64-intel.exe". I tested ALL higher versions (they are all betas) one by one and they all failed.

**Comment by chipitsine** [comment]
4.X is "stable" repo.
since 4.25-9656 there were 5 commits:

https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/compare/v4.25-9656-rtm...master

we can try them one by one and have a look which one breaks WinXP
unfortunately, I do not have an WinXP here (and I have no idea where to get it).

can you try to find the breaking change ?

**Comment by chipitsine** [comment]
@501ari5 , I've managed to get WinXP image. couple of questions

1) are you using x86 or x64 build of WinXP ?
2) are you using SP3 on WinXP ?
3) which ubuntu do you use ? 18.04 ?

**Comment by davidebeatrici** [comment]
Superseded by #688.
