### ISSUE TITLE
Softether VPN - Strange thing with Upload speed

### ISSUE THREAD

**Issue by vampywiz17** [SoftEtherVPN/SoftEtherVPN#553]
Hello there,

i set a local bridge interface (not TAP, a second virtual interface my VM) and my Upload speed is constant 355 kb/sec 

But, if  i enable SecureNAT and after disable it, the Upload speed up to 60 Mbit/sec. It is good, but if i restart the server, it need to do it again (SecureNAT enable/disable) to normalize the Upload speed.

I use latest PPA ubuntu release. 

My system: ubuntu 18.04 (Proxmox VM)

Edit: if i restart only softether VPN service the Upload speed is still normal. It only need to do the above method, if i restart the server.

**Comment by vampywiz17** [comment]
My dirty solution:

I create a shell script, that running after reboot:

```
!/bin/bash
/usr/bin/vpncmd localhost /SERVER /HUB:vpn /CMD SecureNatEnable
/bin/sleep 15
/usr/bin/vpncmd localhost /SERVER /HUB:vpn /CMD SecureNatDisable
```

It solve my problem.

**Comment by spirritus** [comment]
Hi there, our server has the same problem with limited upload speed. Sadly this solution did not work. The Uplaod from the server remains at the slow rate.

**Comment by vampywiz17** [comment]
If you ebable SecureNAT, the Upload speed is better? (i know that is generate high CPU, it only just test)

**Comment by spirritus** [comment]
Nope, speed stays the same about 200 kb/s

**Comment by vampywiz17** [comment]
Strange...

**Comment by spirritus** [comment]
Ok, tested with another host. Test with Network Traffic Test Tool. Fullduplex Test 2 connections. Testserver on connecting side, Testclient on local network

bridge and securenat on then off:
VPNClient to VPNServer 30Mb/s
VPNServer to VPNClient 300kb/s

tap no modification:
VPNClient to VPNServer 30Mb/s
VPNServer to VPNClient 300kb/s

tap and securenat on off:
VPNClient to VPNServer 30Mb/s
VPNServer to VPNClient  8Mb/s

A bit on the odd side maybe related or not, if the Testserver and Testclient roles are swapped to Testclient on connecting side, Testserver on local network, the following results:
tap and securenat on off:
VPNClient to VPNServer  46Mb/s
VPNServer to VPNClient  1.5Mb/s

**Comment by spirritus** [comment]
I am an idiot.

The two nics connecting the firewall with the vpn gateway were set to 100mbit instead of 1000 mbit.
However the connection to the internet ist "only" a 100 mbit line.

Setting the nics to 1000 yields the following results.

Test with Network Traffic Test Tool. Fullduplex Test 2 connections. Testserver on connecting side, Testclient on local network
bridge and securenat on then off:
VPNClient to VPNServer 43Mb/s
VPNServer to VPNClient 38kb/s

Ok that is at least close to symmetric.


Test with Network Traffic Test Tool. Fullduplex Test 2 connections. Testclient on connecting side, Testserver on local network
bridge and securenat on then off:
VPNClient to VPNServer 76Mb/s
VPNServer to VPNClient 71kb/s

That is damn near linespeed and symetrical.
But why differ the total speeds so much depending on who innitates the test...
Anyway thx for the on/off tip, that really helped.

**Comment by ooijiyoung** [comment]
Using SecureNAT, Try disable/set "DisableIpRawModeSecureNAT"  and "DisableKernelModeSecureNAT" to '1' in Virtual Hub Extended Option.

This fix my issue on slow download speed

**Comment by r-mach** [comment]
Hello,

Just leaving a message to say that I have the exact same problem here (on proxmox lxc ubuntu 16).
Perfect with secureNat. I'm using a pfSense firewall (which isn't throttling, I tried it...).
I'm using the latest beta release of SoftEther.
65Mb/s up/down with SecureNat

65Mb/s up without, 500Kb/s download...

Best regards

**Comment by phil-flex** [comment]
> 
> 
> Using SecureNAT, Try disable/set "DisableIpRawModeSecureNAT" and "DisableKernelModeSecureNAT" to '1' in Virtual Hub Extended Option.
> 
> This fix my issue on slow download speed

Using this settings with SecureNAT will improve the performance, my experience download speed can be improved from 300kps to 2Mbs (whole average is 5Mpbs). But compare the the physical link speed 42Mbps DOWNLOAD, 8Mbps UPLOAD (4G network client side) and 200+Mbps (server side) there are seems to be a lot of speed loss. 

Is the VPN bandwidth bounded by the lowest 8Mbps UPLOAD speed at client side?

**Comment by BPiepmatz** [comment]
Hey,

running SE on Ubuntu 18. With secureNat I get nearly speeds as without using VPN. Using my own DHCP server (dnsmasq) I get high download speeds but only 1/10 of my previous upload. Couldn't figure out what the reason is so far...

best

**Comment by greg-jaunt** [comment]
I was seeing exactly what r-mach was seeing...  60 megabits/s up and about 300 kilobits/s down from the Softether server.  Oddly, ooijiyoung's solution worked for me even with SecureNAT disabled and I am now getting wire speed through ipsec in both directions.

FWIW, I've seen a lot of other people with the same issue trying to run Softether in a container and looking at docker-related causes, but I'm even getting wire speed through the container now with the above two Virtual Hub Extended Options set.

Thanks!

**Comment by DayZAnder** [comment]
Also replying here. This is an issue with SoftetherVPN running on Linux VM under Proxmox PVE9 / QEMU.
[ooijiyoung](https://github.com/ooijiyoung) solution works for me.
