### ISSUE TITLE
establish L2tp（onl L2TP） vpn connection in my own app

### ISSUE THREAD

**Issue by Android1404** [SoftEtherVPN/SoftEtherVPN#557]
base on this project.can i use  server address,port,account and pwd to establish L2tp vpn connection in my own app?NOT on system Setting

**Comment by davidebeatrici** [comment]
Of course you can, if your app supports it.

You can connect using raw L2TP (not encrypted) or L2TP with IPSec (encrypted).

**Comment by MHuangXin** [comment]
we're using  raw L2TP now.but For third-part app. Android doestn't provide  public api to setup vpn address,port,account and pwd.now we want to do project like this.Can u give me some advice?

**Comment by davidebeatrici** [comment]
You could use Android's [VpnService](https://developer.android.com/reference/android/net/VpnService) API and then write your own L2TP client implementation.
