### ISSUE TITLE
SoftEther connects to external servers by itself

### ISSUE THREAD

**Issue by ghost** [SoftEtherVPN/SoftEtherVPN#561]
Hi,

- what usecase is there for querieng yahoo.com every 60 seconds? If possible please add an option to remove that useless pinging.

Found at:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/ab54b73737091ecd638ad89101eb94fc551d489e/src/Cedar/Virtual.c#L2438-L2447

- What is the purpose of repeatedly connecting to public.softether.com as soon as im connecting with VPN Server Manager?

Found at:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/f96ac3644a946bb3ecc65b47c55f4bb4d581971c/src/Cedar/CM.c#L9821-L9826

**Comment by r4j4h** [comment]
Hi! Great questions! I am no spokesperson for the  project, but I do think I can provide possible explanations for these behaviors:

* The first case I believe is an internet-connectivity check. I do agree the rate and an option to toggle it completely would be useful.

    * Maybe even the target should be configurable, www.yahoo.com may not be responsive forever. Also in a large private network environment one may want VPN to segregate further but the entire network is incapable of reaching yahoo it makes no sense to attempt to but perhaps it does make sense to hit some other internal endpoint instead. Configurability would be great there.

* To the second case

  
  https://github.com/SoftEtherVPN/SoftEtherVPN/blob/0b8fcb75bc577847af2405d7dfc87cdc3945ad89/src/Mayaqua/Internat.c#L2046-L2048

    UniSearchStrEx indicates this behavior is only for when SoftEther runs with the account name specifically set to "public.softether.com" https://github.com/SoftEtherVPN/SoftEtherVPN/blob/9f9dc459a72a963c5c435186958117778b7b4cf5/src/Cedar/CM.h#L136-L139

    To the latter, tracing the "VpnServerHtml" leads to this warning page for English people http://www.softether.com/jp/special/se2hub_en.aspx and a matching one presumably for Chinese/Japanese/?. 

    The warning page could be quite concerting! But I think both cases are benign. I would presume the latter one is due to as it claims, actual legal involvement requiring some form of warning and liability release. I would propose adding code to enable compiling it out, but I could see in that case that releasing SoftEther with the ability to compile WITHOUT that code in would be flagrant violation of whatever happened, at least as long as the public SoftEther purported to run the same code base. So in the worst case if you really distrust it you can always fork and disable I guess.

I hope my answers make sense and someone with more authority can come in and give better answers. :)

**Comment by r4j4h** [comment]
After some thinking, the public server name functionality appears to be like  a sort of capture portal. In that case it may be worth advancing further as a feature to allow VPN Admins to create custom pages before allowing access. In addition to warnings or reminders they can be used as portals and announcements vehicles  as well. Overall they are probably annoying though. I just thought I would add that thought.
