### ISSUE TITLE
SSTP authentication bug with Windows 10 1803

### ISSUE THREAD

**Issue by Hero1711** [SoftEtherVPN/SoftEtherVPN#563]
### Prerequisites

* [ Yes ] Can you reproduce?
* [ Yes ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** v4.27-9668-beta-2018.05.29
**Component:** Server
**Operating system:** Ubuntu 16.04
**Architecture:** 64 bit

### Description
Can not authenticate users connecting from Windows built-in SSTP client on Windows 10 1803. It works with Windows 10 1709 and below.

**Expected behavior:**
The username and password are correct and the user is active; the user should be authenticated

**Actual behavior:**
Error code 691 is returned to the client.
In the server_log_vpn, "User authentication failed." (code 9). And then "Connection has been disconnected." (code 3).

### Steps to reproduce
1. Setup SoftEther server with MS-SSTP enabled.
2. Create a user with Auth Type of "Password Authentication" or "RADIUS Authentication" (For RADIUS, "Use RADIUS Authentication" and appropriate RADIUS server info are supplied).
3. Set "Encryption Algorithm Name" to "AES256-SHA".
4. Create a new Server Certificate with CN as the IPv4 address of the SoftEther server.
5. Export the X509 Certificate (.cer) from the SoftEther server.
6. Import the X509 Certificate (.cer) above to the client's certificate store under Local Computer\Trusted Root Certification Authorities\Certificates\.
7. Try to connect to the VPN server via SSTP on Windows 10 1803 (Specifying the IPv4 IP address of the Softether server).

**Comment by Hero1711** [comment]
Actually when I tried to reproduce this problem on another Windows 10 1803 computer, it did not appear. Then I ran the following commands to repair the computer with this issue:
```
dism /Online /Cleanup-image /Restorehealth
sfc /scannow
```
After that, SSTP worked correctly now. I guess this was because Windows was corrupted. Please close this issue.

**Comment by isimsizolan** [comment]
> 
> 
> Actually when I tried to reproduce this problem on another Windows 10 1803 computer, it did not appear. Then I ran the following commands to repair the computer with this issue:
> 
> ```
> dism /Online /Cleanup-image /Restorehealth
> sfc /scannow
> ```
> 
> After that, SSTP worked correctly now. I guess this happened because Windows was corrupted. Please close this issue.

Well i was having same problem with 1809, i managed to solve my problem with your hint. I'm not in any domain but sstp disconnecting after a seconds, still i was able to solve this by changing network identity to home computer from system settings.
