### ISSUE TITLE
Possibility to use a custom Certificate Authority for generating certificates

### ISSUE THREAD

**Issue by hajekj** [SoftEtherVPN/SoftEtherVPN#568]
As far as I understand the [documentation](https://www.softether.org/4-docs/1-manual/2._SoftEther_VPN_Essential_Architecture/2.2_User_Authentication), SoftEther can be used with signed certificates only when the certificates have been issued by SoftEther as well (I can bring my own intermmediate or root, but the user certificate has to be issued by SoftEther). I think this is quite limiting and I believe it would be a great benefit to be able to set an accepted certificate for client connections.

It would work that on the server side, you set the public root/intermmediate certificate with which the connections will be validated and then, you distribute the certificates to the clients your preffered way - Active Directory, Intune etc. After that, the client can initiate the session with SoftEther server, the server can optionally check against the CA's CRL or its internal CRL, check the certificate's validity (expiration, issuance, chain, ...) and if all is okay, let the client connect. Is this something that could be implemented into the server?

The main reason why I am bringing this up is that we would like to leverage the [Conditional Access](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/ad-ca-vpn-connectivity-windows10) feature for VPN of Azure AD + Intune which actually generates the certificate for the user with support for multifactor authentication and other various flows and security checks.

**Comment by Firm** [comment]
No, SoftEther supports client authentication with certificates issued by 3rd party CAs. Just add CA's certificate to Trusted CA Certificates and choose Signed Certificate Authentication in User's properties. You could also use Individual Certificate Authentication but this requires user's cert to be uploaded to server.

**Comment by domosekai** [comment]
No change needed.
