### ISSUE TITLE
"USE ONLY IN JAPAN" This project is completely USELESS

### ISSUE THREAD

**Issue by eaffea** [SoftEtherVPN/SoftEtherVPN#57]
## "DISCLAIMER

USE ONLY IN JAPAN. DO NOT USE IT IN OTHER COUNTRIES."

https://github.com/SoftEtherVPN/SoftEtherVPN/
Copy(evidence): https://archive.today/fKqqE

**Comment by slacka** [comment]
Please close this issue. **It's a DISCLAIMER, not LICENSE.**

**Comment by mikini** [comment]
@dnobori Why has the improved wording from [22 Jun 2014](https://github.com/SoftEtherVPN/SoftEtherVPN/issues/57#issuecomment-46771522) not been integrated in the releases yet?

I'm looking into SoftEtherVPN and almost rejected it based on this really harsh wording in the ReadMeFirst_License.txt before finding the elaborations in this issue. A shame if this keeps people from even considering the software.

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by moatazelmasry2** [comment]
I also agree we should close this issue, because it is a disclaimer and not a license. 
@dnobori You mentioned there will be new disclaimer text. What is the status on that?

Further Suggestions: 
- Move the disclaimer in its own text file. This approach is the most popular one

**Comment by davidebeatrici** [comment]
Pull request: #417

**Comment by moatazelmasry2** [comment]
@davidebeatrici could you please thumb up PR #417 so that it can be merged into master?

**Comment by davidebeatrici** [comment]
@moatazelmasry2 Done!

**Comment by davidebeatrici** [comment]
#417 has been merged, I think that this issue can now be closed.

**Comment by moatazelmasry2** [comment]
Yup agree. Please feel free to comment against closing this issue if you see otherwise
