### ISSUE TITLE
ARM builds fail because <cpuid.h> is not available for that architecture

### ISSUE THREAD

**Issue by maurerr** [SoftEtherVPN/SoftEtherVPN#573]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** [Server, Client, Bridge, etc.]
**Operating system:** [Windows, Linux, BSD, macOS, etc.]
**Architecture:** [64 bit, 32 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]

### Description

[Description of the bug]

**Expected behavior:**
[What you expected to happen]

**Actual behavior:**
[What actually happened]

### Steps to reproduce

buildlog:
[ 67%] Building C object src/CMakeFiles/mayaqua.dir/Mayaqua/Encrypt.c.o
/<<PKGBUILDDIR>>/src/Mayaqua/Encrypt.c:151:10: fatal error: cpuid.h: No such file or directory
 #include <cpuid.h> // For __get_cpuid()
          ^~~~~~~~~
compilation terminated.

**Comment by davidebeatrici** [comment]
From https://github.com/SoftEtherVPN/SoftEtherVPN/issues/574#issue-343408913:
> The commit that added cpuid.h to Encrypt.c breaks cross-compiling, because only i386 targets have support for <cpuid.h> via gcc and the file is not included/copied by most cross-compile sdk's on other targets.
>
>Maybe /proc/cpuinfo and checking for the aes flag could be used on unsupported linux/bsd platforms instead?
Some arm/mips have aes support, but i'm not sure what has to-be in-place to actually get this working on none i386 platforms.

**Comment by chipitsine** [comment]
@davidebeatrici , I did a quick look how this is resolved in similar projects.
however, I was not able to find something usable :(

we have to invent a wheel here, I guess

**Comment by chipitsine** [comment]
@Andy2244 , can you please share your script for cross compiling ?
I want to integrfate it into travis-ci build matrix to avoid similar breakage in the future

**Comment by Andy2244** [comment]
Just found a possible solution, check: https://github.com/google/cpu_features
We can ask in the openwrt community to test the mips/arm targets with aes support, if you want to also try enable acceleration on those?
