### ISSUE TITLE
Block DNS leaks feature is missing in .ovpn files downloaded from official site !

### ISSUE THREAD

**Issue by Whibelf2** [SoftEtherVPN/SoftEtherVPN#583]
Yours need to add a string in .ovpn files by default

String to Block DNS Leaks in OpenVPN:  `block-outside-dns`

Source:

https://www.dnsleaktest.com/how-to-fix-a-dns-leak.html

https://forums.openvpn.net/viewtopic.php?t=21742

https://forums.openvpn.net/viewtopic.php?t=22039

**Comment by davidebeatrici** [comment]
From https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage:

> --block-outside-dns
>
>Block DNS servers on other network adapters to prevent DNS leaks. This option prevents any application from accessing TCP or UDP port 53 except one inside the tunnel. It uses Windows Filtering Platform (WFP) and works on Windows Vista or later.
This option is considered unknown on non-Windows platforms and unsupported on Windows XP, resulting in fatal error. You may want to use --setenv opt or --ignore-unknown-option (not suitable for Windows XP) to ignore said error. Note that pushing unknown options from server does not trigger fatal errors.

We should push the option from the server.

**Comment by jonnybravocoder** [comment]
> From https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage:
> 
> > --block-outside-dns
> > Block DNS servers on other network adapters to prevent DNS leaks. This option prevents any application from accessing TCP or UDP port 53 except one inside the tunnel. It uses Windows Filtering Platform (WFP) and works on Windows Vista or later.
> > This option is considered unknown on non-Windows platforms and unsupported on Windows XP, resulting in fatal error. You may want to use --setenv opt or --ignore-unknown-option (not suitable for Windows XP) to ignore said error. Note that pushing unknown options from server does not trigger fatal errors.
> 
> We should push the option from the server.

It would be great if someone would implement this.  As in have the softether vpn server require all devices that connect to it to send dns requests through the vpn server.  Its been two years people.  Come on.
