### ISSUE TITLE
Can't build on Windows due to nowhere to download Visual Studio 2008

### ISSUE THREAD

**Issue by BlackHoleFox** [SoftEtherVPN/SoftEtherVPN#586]
The Windows build instructions tell you that VS Studio 2008 is needed, which MS no longer provides downloads for. Is there any chance that this project could be moved to Visual Studio 2015 for its solution, or even 2017?

**Comment by BlackHoleFox** [comment]
Oh, thank you. The only download I had found was a .pptx file on their site. Are there any plans to move to a newer Visual Studio project file? Newer versions still support .NET 3.5

**Comment by davidebeatrici** [comment]
From https://github.com/SoftEtherVPN/SoftEtherVPN/wiki/SoftEther-VPN-Developers-Guideline-(DRAFT):

> MUST support Microsoft Visual C++ 2008. Microsoft Visual C++ 2008 is the latest version to support Windows 9x and Windows NT 4.x binary linking. It is OK to add new Visual Studio's solution files (e.g. for Visual Studio 2017). In such a case, there must be dual solution files for both Visual C++ 2008 and the latest Visual Studio.

I'm working on adding Windows support to our CMake configuration.

**Comment by chipitsine** [comment]
That info seem to be good to add to BUILD_WINDOWS.MD

@BlackHoleFox , can you take care of that?

**Comment by BlackHoleFox** [comment]
@chipitsine Assuming that you mean details on what C++ versions it must support and that a CMake config for windows is coming, sure.

**Comment by BlackHoleFox** [comment]
With the merging of #588, this can be closed now right?
