### ISSUE TITLE
SoftEther Vpn server IP is not correct in Vpn client connection properties !

### ISSUE THREAD

**Issue by oooo1** [SoftEtherVPN/SoftEtherVPN#61]
Vpn server IP is lways 1.0.0.1 even if virtual host's IP is specified as 192.168.0.1.

**Comment by lateagain** [comment]
With it always handing out a dummy IP we can't use the remote IP to select the routes to add in /etc/ppp/ip-up

I use that file to add routes on L2TP connections on a Macbook. Works fine with connections to Draytek routers, not to softether.

**Comment by Ilhom-S** [comment]
It's getting problem when router trying to ping back and can't 1.0.0.1 . Is there any way to push real IP ?

**Comment by davidebeatrici** [comment]
Pull request: #524

**Comment by davidebeatrici** [comment]
Superseded by #114.
