### ISSUE TITLE
Multiple L2TP-IPsec clients behind same NAT !

### ISSUE THREAD

**Issue by oooo1** [SoftEtherVPN/SoftEtherVPN#63]
It sound strange, but I have been able to establish 2 simultaneous connections from 2 clients: Win XP and Win 7 sited behind one external IP NAT.
Both are IPSec over L2tp, one is 3DES, other one is AES128 crypto.
But can not test establishing 3rd connection, because there are only 2 clients in this test net only. :)))))  
That is Win XP and Win 7 is in some LAN where is NAT.
My SoftEther is in physically different net.
And the cliens has been got different IPs from specified in SecureNAT dhcp pool.
I don' t know is it an issue/ bug or a feature.

**Comment by domosekai** [comment]
Expected behavior.
