### ISSUE TITLE
new port for MacOS 

### ISSUE THREAD

**Issue by Hamid-Najafi** [SoftEtherVPN/SoftEtherVPN#630]
can anyone port new soft ether server manager for new macOS Mojave (v4.27) for 64bit cpu ?

**Comment by jaykosky** [comment]
Anyone manage get the latest stable build compile on macOS high sierra?

I am stuck at this error

SoftEther VPN for Unix

Copyright (c) Daiyuu Nobori.
Copyright (c) SoftEther VPN Project, University of Tsukuba, Japan.
Copyright (c) SoftEther Corporation.
Copyright (c) all contributors on SoftEther VPN project in GitHub.

License: The Apache License, Version 2.0

Read and understand README.TXT, LICENSE.TXT and WARNING.TXT before use.
---------------------------------------------------------------------

Welcome to the corner-cutting configure script !

The Makefile is generated. Run 'make' to build SoftEther VPN.
Jays-Mac-mini:SoftEtherVPN_Stable jayko$ make
cc -DNDEBUG -DVPN_SPEED -DUNIX -DUNIX_MACOS -DBRIDGE_PCAP -DCPU_64 -D_REENTRANT -DREENTRANT -D_THREAD_SAFE -D_THREADSAFE -DTHREAD_SAFE -DTHREADSAFE -D_FILE_OFFSET_BITS=64 -I./src/ -I./src/Cedar/ -I./src/Mayaqua/ -O2 -fsigned-char -m64 -c src/Mayaqua/Encrypt.c -o tmp/objs/Mayaqua/Encrypt.o
src/Mayaqua/Encrypt.c:118:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make: *** [tmp/objs/Mayaqua/Encrypt.o] Error 1
