### ISSUE TITLE
Build System

### ISSUE THREAD

**Issue by martell** [SoftEtherVPN/SoftEtherVPN#65]
Hi @dnobori,

I have been watching this project since it became Open Source.
The biggest issue I can see is the manual makefile setup that is included.

To add support to more and more platforms you may want to look at using something like cmake. You will be able to remove the visual studio solutions with this also and have it all managed from one script.

Will you be accepting PR's?
I may do one for this

Many Thanks,
Martell

**Comment by topherbuckley** [comment]
I'd like to bump this issue. I'd also like to contribute in some way, but don't have access to a paid 2008 version of Visual Studio. I'm completely new to C coding, and didn't want to invest a whole lot of time learning it. Just wanted to help fix a sorting bug thats been bothering me a while. What would it take to be able to build/test without such a dependency?

**Comment by meganerd** [comment]
https://www.visualstudio.com/products/visual-studio-community-vs

**Comment by topherbuckley** [comment]
@meganerd 

My understanding was that only the 2008 SP1 would work. Have you successfully built using the 2015 package linked?

Regardless, I tried downloading the 2015 version from the link provided and only downloaded a 207 kb file which failed to open. I'll debug that on my own if you confirm you are able to build with the 2015 version.

**Comment by moatazelmasry2** [comment]
hi @martell . This sound good, please implement that if you can. 
There are some new board members here and we can actually accept PRs :) . So please do it.

Also @martell  and @topherbuckley . You do not really need Visual Studio to compile this project. I don't even have windows. I have linux and eclipse. Both are free and I use make and gcc to compile. 

However there are many things that could be enhanced in the configure and the make file. 
Do you have concrete ideas???

**Comment by topherbuckley** [comment]
@moatazelmasry2 Sorry, but I haven't used this in quite some time and ended up going with a paid service for my VPN. The one concrete idea I HAD, (not sure if it is even still an issue), was the sorting of VPN servers. I remember I couldn't sort by ping or speed properly. I don't remember exactly, but there was something in the sorting that favored alphabetical name order over ping/speed or something like that. Sorry I can't be of more help, but hope that sparks at least one product improvement.

**Comment by MaverickTse** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/65#issuecomment-346202196

I'd also like to know how exactly you build the **windows installers** or windows **gui tools** without using windows nor vs2008. If GCC/MINGW-w64 alone can deal with it, it would simplify the build process a lot (and helps to gain more contributors).

I have tried MSYS2 but it refuse to build. Only in a VM with the relic VS2008 SP1 installed can generate the installer.

If the build process is clear (and hopefully not requiring C#), than writing a cmake build script MIGHT be possible.

**Comment by davidebeatrici** [comment]
CMake is now used as build system on Linux (#518).

@MaverickTse I created a feature request for MinGW: #591
