### ISSUE TITLE
Please tag the releases and upload them in a github conform way

### ISSUE THREAD

**Issue by martell** [SoftEtherVPN/SoftEtherVPN#66]
Hi @dnobori ,

I want to point out a few things that will help make softEther more accessible to you and help you get others in the open source world working on it for you.

If I try to package up the software into a package manager I have to use a really long string like this.

pkgver=4.08
_build_type=rtm
_build_num=9449
_build_date=2014.06.08

source=("http://www.softether-download.com/files/softether/v${pkgver}-${_build_num}-${_build_type}-${_build_date}-tree/Source%20Code/softether-src-v${pkgver}-${_build_num}-${_build_type}.tar.gz")

something like
http://www.softether-download.com/files/softether/softether-src-v4.08.tar.gz
would be much easier. have a look at you version numbering system.
It could be much simpler. 

also when using git could you use tagging instead of committing for each version
http://git-scm.com/book/en/Git-Basics-Tagging

So instead of using commit to tell us the version number like "v4.09-9451-beta" you could actually put in a comment as to what was was added and changed.
compare this kind of message 
https://github.com/SoftEtherVPN/SoftEtherVPN/commits/master
to this
https://github.com/bagder/curl/commits/master

Then with the tagging you can have

v4.09
v4.09-rc0
v4.08
v4.08-rc2
v4.08-rc1
v4.08-rc0

example look at cmake's tagging
https://github.com/Kitware/CMake/releases

These are just a few things to get you started and there is much more that can be done.
What you want is to get a community behind your project and this will help do that

I hope you like my input and I think softether is an amazing project :)

Many Thanks
Martell

**Comment by moatazelmasry2** [comment]
Hi @martell . These are all valid suggestions. I fully agree with a better build number suggestion as well as the tagging. 

I will change the title of this issue (I hope this is ok) to reflect these requests and would also like to use this issue to track the progress on a release process.
