### ISSUE TITLE
I was attacked heavily from China and JAP and I really want "Auto-BAN" function!!

### ISSUE THREAD

**Issue by collaboratorscollaborators** [SoftEtherVPN/SoftEtherVPN#67]
Many server software has "Auto-ban" function.

"Auto-ban" ... If the user fail to login [X] times, deny it's [IP address] for [10080] hours.

I know your VPN server has IP control(Virtual Hub prop > IP Access Control list),
but this is not for me because blocking all these countries are not my option(I have a few friends in these).

So, please, add AutoBAN function...

**Comment by moatazelmasry2** [comment]
This feature does not exist in SoftEther and is really out of scope of SoftEther. 
fail2ban is one solution. There are several threads on the forum regarding this:
http://www.vpnusers.com/search.php?keywords=fail2ban

You can also implement a similar result if you are using freeradius as a backend for Softether:
http://wiki.freeradius.org/guide/lockout

There is really nothing to do here unfortunately, so I'll go ahead and close this issue.

**Comment by benrubson** [comment]
#1122 helps here.
