### ISSUE TITLE
Start Before Logon feature

### ISSUE THREAD

**Issue by chipitsine** [SoftEtherVPN/SoftEtherVPN#677]
for enterprise vpn there is very useful feature, description is here:

https://community.cisco.com/t5/vpn-and-anyconnect/vpn-client-start-before-logon/td-p/1863732

**Comment by moatazelmasry2** [comment]
The feature is not really clear to me from that link. Could you please describe here what "start before logon" does?

**Comment by chipitsine** [comment]
I will try to find proper document.

In short, windows 8.1 and later allows to start VPN connection from logon window (before user logs in). 

It is nice for enterprises, so road warriors can log to active directory from home notebook.

**Comment by elliot-labs** [comment]
Windows 10 has always on VPN which does the same thing:
https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/always-on-vpn-technology-overview

**Comment by chipitsine** [comment]
api first was implemented in windows 8.1
windows 10 api is totally reworked

and yes, I mean that feature :)

**Comment by dnobori** [comment]
Please use the "Startup Connection" function which is already implemented on SoftEther VPN Client. This function realizes what you want to do.

![clip_4](https://user-images.githubusercontent.com/3041130/45222148-94033980-b2ee-11e8-96c4-991d3da06bf0.jpg)


This function is expressly described in the 4.4.19 Startup Connection section on the manual:

> You can set a connection setting for startup connection by using VPN Client Manager to select a connection setting and then clicking [Set as Startup Connection] on the [Connect] menu. **When a connection setting is set for startup connection, a connection to VPN Server is automatically started using that connection setting when Windows is started.**

https://www.softether.org/4-docs/1-manual/4._SoftEther_VPN_Client_Manual/4.4_Making_Connection_to_VPN_Server#4.4.19_Startup_Connection

**Comment by chipitsine** [comment]
Wow, I missed that

**Comment by elliot-labs** [comment]
Omg, I set that up on a network and I forgot about that.
Silly me.

**Comment by mr-flibble** [comment]
Maybe this issue could be closed?

**Comment by mkuzmanis** [comment]
Can this be reopened? Existing feature (startup connection) works, but is not the same as connecting to VPN before logon.
Use case, if user has domain joined laptop, that sometimes is taken outside of the office:

* When user is in the office, he can log in normally without VPN (and VPN should not be used, since it is local network).
* VPN is configured to use domain authentication.
* When working remotely, windows 10 allows joining WiFi before user logon. This is also where it would be nice to have ability to start SoftEther VPN connection on demand and enter user details (those should not be stored on computer, especially since it might be shared between people).

Windows 10 built in VPN client allows this functionality (https://athelp.sfsu.edu/hc/article_attachments/360087483494/logon2.png), however it is a lot slower and less stable.

**Comment by billroland** [comment]
> Can this be reopened? Existing feature (startup connection) works, but is not the same as connecting to VPN before logon. Use case, if user has domain joined laptop, that sometimes is taken outside of the office:
> 
> * When user is in the office, he can log in normally without VPN (and VPN should not be used, since it is local network).
> * VPN is configured to use domain authentication.
> * When working remotely, windows 10 allows joining WiFi before user logon. This is also where it would be nice to have ability to start SoftEther VPN connection on demand and enter user details (those should not be stored on computer, especially since it might be shared between people).
> 
> Windows 10 built in VPN client allows this functionality (https://athelp.sfsu.edu/hc/article_attachments/360087483494/logon2.png), however it is a lot slower and less stable.

I agree with this. It seems that almost all the pieces for this are already in place, there just needs to be some mechanism for Softether to detect when its on the corporate network vs not.  Softether is way faster and much more stable than Windows AoVPN, so it would be nice to see s solution.

**Comment by Dmitry422** [comment]
I think user can connect to Wi-FI with checkbox "autoconnect to this network" and reboot laptop, so after reboot SoftEther VPN automatically connect to server by the Startup Connection option.
