### ISSUE TITLE
Tap interface

### ISSUE THREAD

**Issue by ksimonenko-zz** [SoftEtherVPN/SoftEtherVPN#68]
Hi @dnobori !
From the point of view of the SE VPN server, what is the difference between a tap interface created by SE Manager and, for instance, a tap interface by tunctl from the linux shell?

Can SE VPN Server communicate with the TAP interfaces that are created outside of SE VPN Server (i.e. using tunctl)?

Regards.

**Comment by domosekai** [comment]
Close due to inactivity
