### ISSUE TITLE
discussion: would you personally pay for implementing features ?

### ISSUE THREAD

**Issue by chipitsine** [SoftEtherVPN/SoftEtherVPN#687]
from time to time people open "feature requests" with very time consuming things like

- bypassing china great firewall
- implementing protocols like wireguards or anyconnect
- enterprise features

while those things are considered to be useful for requestors, not many developers are motivated to implement those.

the question is: if there would be a possibility to hire a developer for implementing a feature, would you personally pay for it ? if "yes", please say "thumb up"

after reasonable number of "thumbs up", I will add SE VPN project to https://opencollective.com/

**Comment by chinamore** [comment]
Norbert, HI
Congratulations on being a member of softether. I have a problem that needs to trouble you. I don't know if you can achieve it. I have been researching the software of SOFTETHER for a long time. I have new ideas:
1 Modify the software verification interface: one of the servers to verify the account time, the successful verification of the account can be carried out, other settings of the server (mainly time control is very useful, other servers).
2 The routing table function is added. The current routing table has only 64 entries, and the entries are too few. At present, the branches of https://github.com/fivesheep/chnroutes can be separated by traffic. The WINDWOS in the attached file is also a finished routing table. .
3, optimize the game acceleration function: really enough to make more optimizations for the game's connection (such as FPS games)

**Comment by chinamore** [comment]
我已经EMail 给Norbert ，我希望SOFTETHER能够实现 游戏加速器的功能
