### ISSUE TITLE
Cascade Connection Between two VPN Servers ?

### ISSUE THREAD

**Issue by petergsnm** [SoftEtherVPN/SoftEtherVPN#69]
Hi,

All the examples showed in the document says, a SoftEther VPN Bridge is connected to the SoftEther VPN Server. I am just wondering if we can  connect two sites (site-to-site VPN) using two VPN Servers connected through a cascade connection.

Client 1<---------->Site1VPN Server <====Cascade Conn===> Site2VPNServer<-->Private User.

Is the above setup allowed. I think it is possible in theory. But, has this been tested? I tried to setup this way, but it was not working. So, I am not  sure if this is supported? Please let me know.

I am trying to setup this way, using VPN Server instead of a VPN Bridge because I wanted to do clustering on Site 1. 

Please let me know if this is allowed?

Thank you.

--Peter

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by adminport** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by sonvirgo** [comment]
Instead of providing proxychain to my user, it is possible to cascade 
VPN Server's Virtual Hub => Public VPNGATE
or
VPN Server's Virtual Hub => non SoftEther VPN Server (e.g, VPNBOOK, OPENVPN)
Thanks

**Comment by sonvirgo** [comment]
Instead of providing proxychain to my user, it is possible to cascade 
my user => my VPN Server's Virtual Hub => Public VPNGATE => Internet
or
my user => my VPN Server's Virtual Hub => non SoftEther VPN Server (e.g, VPNBOOK, OPENVPN) => Internet
Thanks

**Comment by domosekai** [comment]
Close due to inactivity.
