### ISSUE TITLE
Version of the source code and bug fixes

### ISSUE THREAD

**Issue by scegg** [SoftEtherVPN/SoftEtherVPN#696]
Hi.

https://www.softether.org/5-download/history says that the latest version is 4.28 9669

But the binary built from https://github.com/SoftEtherVPN/SoftEtherVPN.git has the different versions:
For client: 4.27 9667 (linux)
For server: 0.51 9657 (linux)

Does the binary built from here contains all fixes listed in the https://www.softether.org/5-download/history ?

Thanks.

**Comment by davidebeatrici** [comment]
Hi,

> https://www.softether.org/5-download/history says that the latest version is 4.28 9669

That's the latest version from the stable repository: https://github.com/SoftEtherVPN/SoftEtherVPN_Stable

> But the binary built from https://github.com/SoftEtherVPN/SoftEtherVPN.git has the different versions:
For client: 4.27 9667 (linux)
For server: 0.51 9657 (linux)

The current version is `5.01.9657`:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/64b68c15f413d7c0313132a4c7164f46d74f0061/CMakeLists.txt#L4

We will increase it and create a new tag, once the packaging system is finished.

> Does the binary built from here contains all fixes listed in the https://www.softether.org/5-download/history ?

Yes.

**Comment by davidebeatrici** [comment]
You're welcome.

I agree that the virtual network adapter's driver should have the same version as the software.
