### ISSUE TITLE
LGPL request

### ISSUE THREAD

**Issue by top-master** [SoftEtherVPN/SoftEtherVPN#697]
we are currently writing a **SoftEther VPN client** for **Windows** using our SoftEther based VPN servers
however although currently we are just using SoftEther as an external `.dll` file, the GPL licence does force us to provide the source-code of the Executable file (i.e. `*.exe` file which is dynamically linked to `soft-ether.dll`)

but the problem is our Executable file does contain (except a simple GUI) the authentication and user token algorithms which anyone would prefer to keep private and closed-source, so **we ask here to add the `LGPL` license to the SoftEther project** since we want keep our software secure.

there are two work-around's that could be used even without any support or additional license:

1. instead of using SoftEter as `.dll` file we could just **separate our authentication and ... in a `.dll` file and keep it closed-source** but it will be hard since that `authentication.dll` would cause us a large rewrite in the source codes

2. or we could keep authentication in our Executable but **make SoftEther background service listen for commands on a localhost port**, using this we do not need to make anything open-source since the `GPL` does allow such indirect commands and we would just need to make public our changes to `SoftEther background service` (which is no problem for us until our authentication and ... are closed-source)

but nothing from the above would be required if support for `LGPL` is added to SoftEther project

**Edit:**
to get sure did also request at:
[vpnusers.com](http://www.vpnusers.com/viewtopic.php?f=7&t=63250&p=83540&hilit=lgpl)

**Comment by chipitsine** [comment]
there's work in progress on moving towards apache license
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/516

**Comment by top-master** [comment]
that issue was opened at begin 2018, which is soon over and yet no answer from all contributors???
but sure will close this and continue there at #516

**Comment by paulmenzel** [comment]
Hmm, could you elaborate, why you need to link to SoftEther, when you write your own VPN client?

**Comment by top-master** [comment]
in short: any RPC interface needs to be usable from two directions **Service-Provider** and **Client**, but the `RPC` interface of SoftEther is under `GPLv2` too

Even if we plan to use `SoftEther` as **background-client-service** for connecting using **SoftEther protocol** to our server, still all the `SoftEther RPC` functions are under `GPLv2`:
1. we need `LGPL`, so we can dynamically-link our Client to use that `RPC` functions in a `dll` file or something which's source-code we would publish
2. should the license really change to `Apache 2.0` we could go even further and include that `RPC` functions with static-linking
3. but until waiting for any license change, we are adding our own `RPC` interface to the `background-client-service`, since our own `RPC` interface can be used under whatever license we need, that should be a simple work-around for now
