### ISSUE TITLE
uch as diverting China's target to the local network card without going through the VPN

### ISSUE THREAD

**Issue by chinamore** [SoftEtherVPN/SoftEtherVPN#711]
How to divide traffic according to rules in the source program, such as diverting China's target to the local network card without going through the VPN

example：http://ip.taobao.com/service/getIpInfo.php?ip=120.36.223.142
I use the IP query interface, query IP to get the target IP request is China's IP, the software will automatically put all the links like China's traffic, go local without going VPN

**Comment by domosekai** [comment]
You can do your own routing but this is not something we should do.
