### ISSUE TITLE
Softether on VPS Using Local Bridge

### ISSUE THREAD

**Issue by chinamore** [SoftEtherVPN/SoftEtherVPN#719]
http://blog.lincoln.hk/blog/2013/05/17/softether-on-vps-using-local-bridge/
Follow the tutorial to make a very bad failure,
But this buddy is a magical success. I want to know who has the TXT document available?
https://www.youtube.com/watch?v=jqRkFKHdz4A

**Comment by cmdwhoami** [comment]
Lincoln's bridge example works... Did you disable SecureNAT before you set up the bridge and dnsmasq? That could be the reason for your failure...

I'm guessing your only working with IPv4?

**/etc/sysctl.conf**
```
# For binary values, 0 is disabled, 1 is enabled.
# To save changes run command  sysctl -p
# For more information, see sysctl.conf(5) and sysctl.d(5).

# Controls IP packet forwarding
net.ipv4.ip_forward = 1
```

**/etc/init.d/vpnserver**
```
#!/bin/sh
### BEGIN INIT INFO
# Provides:          vpnserver
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SoftEther VPN Server
### END INIT INFO

DAEMON=/usr/local/vpnserver/vpnserver
LOCK=/var/lock/subsys/vpnserver
TAP_ADDR=192.168.30.1
TAP_INTERFACE=tap_soft

test -x $DAEMON || exit 0
case "$1" in
start)
$DAEMON start
touch $LOCK
sleep 3
#####################################################
#       ifconfig tap interface                      
#####################################################
#
# Assign $TAP_ADDR to our tap interface
/sbin/ifconfig $TAP_INTERFACE $TAP_ADDR
#
#####################################################
#       End                                         
#####################################################
sleep 3
service dnsmasq start
;;
stop)
$DAEMON stop
rm $LOCK
;;
restart)
$DAEMON stop
sleep 3
$DAEMON start
sleep 3
######################################################
#       ifconfig tap interface                       
######################################################
#
# Assign $TAP_ADDR to our tap interface
/sbin/ifconfig $TAP_INTERFACE $TAP_ADDR
#
######################################################
#       End                                          
######################################################
sleep 3
service dnsmasq restart
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
esac
exit 0
```


**/etc/dnsmasq.conf**
```
##################################################################################
# SoftEther VPN server dnsmasq.conf
################################################################################## Interface Settings

# If you want dnsmasq to listen for DHCP and DNS requests only on
# specified interfaces (and the loopback) give the name of the
# interface (eg eth0) here.
# Repeat the line for more than one interface.
interface=tap_soft

# If you want dnsmasq to really bind only the interfaces it is listening on,
# uncomment this option. About the only time you may need this is when
# running another nameserver on the same machine.
bind-interfaces

################################################################################## Options

# Uncomment this to enable the integrated DHCP server, you need
# to supply the range of addresses available for lease and optionally
# a lease time. If you have more than one network, you will need to
# repeat this for each network on which you want to supply DHCP
# service.
dhcp-range=192.168.30.10,192.168.30.255,12h

# Override the default route supplied by dnsmasq, which assumes the
# router is the same machine as the one running dnsmasq.
dhcp-option=3,192.168.30.1

# If you don't want dnsmasq to poll /etc/resolv.conf or other resolv
# files for changes and re-read them then uncomment this.
no-poll

# If you don't want dnsmasq to read /etc/resolv.conf or any other
# file, getting its servers from this file instead (see below), then
# uncomment this.
no-resolv

# Disable re-use of the DHCP servername and filename fields as
# extra option space. This makes extra space available in the
# DHCP packet for options but can, rarely, confuse old or broken
# clients. This flag forces "simple and safe" behavior to avoid
# problems in such a case.
dhcp-no-override

# Never forward addresses in the non-routed address spaces.
bogus-priv

################################################################################## External DNS Servers

# Use this DNS servers for incoming DNS requests = Cloudflare
server=1.1.1.1
server=1.0.0.1

#########################################

################################################################################## Client DNS Servers

# Let's send these DNS Servers to clients.
# The first IP is the IPv4 address that are already assigned to the tap_soft

# Set IPv4 DNS server for client machines
dhcp-option=option:dns-server,192.168.30.1,1.1.1.1

#########################################

```

**Comment by connLAN** [comment]
> Lincoln's bridge example works... Did you disable SecureNAT before you set up the bridge and dnsmasq? That could be the reason for your failure...
> 
> I'm guessing your only working with IPv4?
> 
> **/etc/sysctl.conf**
> 
> ```
> # For binary values, 0 is disabled, 1 is enabled.
> # To save changes run command  sysctl -p
> # For more information, see sysctl.conf(5) and sysctl.d(5).
> 
> # Controls IP packet forwarding
> net.ipv4.ip_forward = 1
> ```
> 
> **/etc/init.d/vpnserver**
> 
> ```
> #!/bin/sh
> ### BEGIN INIT INFO
> # Provides:          vpnserver
> # Required-Start:    $network $remote_fs
> # Required-Stop:     $network $remote_fs
> # Default-Start:     2 3 4 5
> # Default-Stop:      0 1 6
> # Short-Description: SoftEther VPN Server
> ### END INIT INFO
> 
> DAEMON=/usr/local/vpnserver/vpnserver
> LOCK=/var/lock/subsys/vpnserver
> TAP_ADDR=192.168.30.1
> TAP_INTERFACE=tap_soft
> 
> test -x $DAEMON || exit 0
> case "$1" in
> start)
> $DAEMON start
> touch $LOCK
> sleep 3
> #####################################################
> #       ifconfig tap interface                      
> #####################################################
> #
> # Assign $TAP_ADDR to our tap interface
> /sbin/ifconfig $TAP_INTERFACE $TAP_ADDR
> #
> #####################################################
> #       End                                         
> #####################################################
> sleep 3
> service dnsmasq start
> ;;
> stop)
> $DAEMON stop
> rm $LOCK
> ;;
> restart)
> $DAEMON stop
> sleep 3
> $DAEMON start
> sleep 3
> ######################################################
> #       ifconfig tap interface                       
> ######################################################
> #
> # Assign $TAP_ADDR to our tap interface
> /sbin/ifconfig $TAP_INTERFACE $TAP_ADDR
> #
> ######################################################
> #       End                                          
> ######################################################
> sleep 3
> service dnsmasq restart
> ;;
> *)
> echo "Usage: $0 {start|stop|restart}"
> exit 1
> esac
> exit 0
> ```
> 
> **/etc/dnsmasq.conf**
> 
> ```
> ##################################################################################
> # SoftEther VPN server dnsmasq.conf
> ################################################################################## Interface Settings
> 
> # If you want dnsmasq to listen for DHCP and DNS requests only on
> # specified interfaces (and the loopback) give the name of the
> # interface (eg eth0) here.
> # Repeat the line for more than one interface.
> interface=tap_soft
> 
> # If you want dnsmasq to really bind only the interfaces it is listening on,
> # uncomment this option. About the only time you may need this is when
> # running another nameserver on the same machine.
> bind-interfaces
> 
> ################################################################################## Options
> 
> # Uncomment this to enable the integrated DHCP server, you need
> # to supply the range of addresses available for lease and optionally
> # a lease time. If you have more than one network, you will need to
> # repeat this for each network on which you want to supply DHCP
> # service.
> dhcp-range=192.168.30.10,192.168.30.255,12h
> 
> # Override the default route supplied by dnsmasq, which assumes the
> # router is the same machine as the one running dnsmasq.
> dhcp-option=3,192.168.30.1
> 
> # If you don't want dnsmasq to poll /etc/resolv.conf or other resolv
> # files for changes and re-read them then uncomment this.
> no-poll
> 
> # If you don't want dnsmasq to read /etc/resolv.conf or any other
> # file, getting its servers from this file instead (see below), then
> # uncomment this.
> no-resolv
> 
> # Disable re-use of the DHCP servername and filename fields as
> # extra option space. This makes extra space available in the
> # DHCP packet for options but can, rarely, confuse old or broken
> # clients. This flag forces "simple and safe" behavior to avoid
> # problems in such a case.
> dhcp-no-override
> 
> # Never forward addresses in the non-routed address spaces.
> bogus-priv
> 
> ################################################################################## External DNS Servers
> 
> # Use this DNS servers for incoming DNS requests = Cloudflare
> server=1.1.1.1
> server=1.0.0.1
> 
> #########################################
> 
> ################################################################################## Client DNS Servers
> 
> # Let's send these DNS Servers to clients.
> # The first IP is the IPv4 address that are already assigned to the tap_soft
> 
> # Set IPv4 DNS server for client machines
> dhcp-option=option:dns-server,192.168.30.1,1.1.1.1
> 
> #########################################
> ```

I used above configuration  and add a iptables nat rule for it, vpn client can get a dhcp IP ,  but  the client can't visit any website , it seems that vpnserver not work in kernel nat mode.

**Comment by connLAN** [comment]
May be different VPS  not  act the same?  I used VPS of www.bandwagonhost.net  and local vmware workstations vm,  add OS is CentOS7.x  64bit. 

Local bridge bug limited the useing range  of SoftEtherVPN, for more and more vpn server is installed on VPS.

**Comment by cmdwhoami** [comment]
If you get a local ip assigned but can't connect to websites.... then sounds like a DNS issue. If you can ping 8.8.8.8 DNS nameserver is your issue.

**Comment by cmdwhoami** [comment]
`# Allow outgoing DNS
iptables -A OUTPUT -o tap_soft -s 192.168.30.1/24 -p tcp --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -o tap_soft -s 192.168.30.1/24 -p udp --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT

# Allow incoming DNS & DHCP (dnsmasq)
iptables -A INPUT -i tap_soft -p udp --dport 67 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i tap_soft -p tcp --sport 53 -m state --state ESTABLISHED -j ACCEPT
iptables -A INPUT -i tap_soft -p udp --sport 53 -m state --state ESTABLISHED -j ACCEPT`

`# NAT using Local Bridge
# 192.168.30.0/24 = Local Bridge & SoftEther VPN Clients (dnsmasq)
# 192.168.0.12 = SoftEther VPN Server's network interface (Local IP if behind NAT or Public IP of VPS)
iptables -t nat -A POSTROUTING -s 192.168.30.0/24 -j SNAT --to-source 192.168.0.12`

**Comment by connLAN** [comment]
> ```
> #Allow outgoing DNS
> iptables -A OUTPUT -o tap_soft -s 192.168.30.1/24 -p tcp --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
> iptables -A OUTPUT -o tap_soft -s 192.168.30.1/24 -p udp --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
> 
> #Allow incoming DNS & DHCP (dnsmasq)
> iptables -A INPUT -i tap_soft -p udp --dport 67 -m state --state NEW,ESTABLISHED -j ACCEPT
> iptables -A INPUT -i tap_soft -p tcp --sport 53 -m state --state ESTABLISHED -j ACCEPT
> iptables -A INPUT -i tap_soft -p udp --sport 53 -m state --state ESTABLISHED -j ACCEPT
> 
> #NAT using Local Bridge
> #192.168.30.0/24 = Local Bridge & SoftEther VPN Clients (dnsmasq)
> #192.168.0.12 = SoftEther VPN Server's network interface (Local IP if behind NAT or Public IP of VPS)
> iptables -t nat -A POSTROUTING -s 192.168.30.0/24 -j SNAT --to-source 192.168.0.12
> ```

It works! Many thanks to you.  You see, it is really hard for beginners. Would you make a tutorial  on Local-bridge and Cluster?
