### ISSUE TITLE
How to pull statistics from SoftEther VPN server

### ISSUE THREAD

**Issue by petergsnm** [SoftEtherVPN/SoftEtherVPN#72]
Hi,

Is there anyway, we can pull the performance stats from the SoftEtherVPN Server. It will be  great to present this in dashboard. So, I was wondering if there is already anything available or any work done to pull the stats and send to a remote system. 

Even if the stats are available in a file or in logs, I can develop a redis module to send the stats to a remote server through redis.

Please let me know.

Thanks...Peter

**Comment by moatazelmasry2** [comment]
There are some log files available but nothing more. What do you mean by performance stats. What kind of logs are you looking at collecting?

**Comment by moatazelmasry2** [comment]
No answer in a long time. Closing this issue
