### ISSUE TITLE
OpenVPN HMAC authentication failed

### ISSUE THREAD

**Issue by ronneke1996** [SoftEtherVPN/SoftEtherVPN#720]
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** Build from master commit https://github.com/SoftEtherVPN/SoftEtherVPN/commit/06c06f1db885f70e585aaeef0df5a26de8b953e4 
**Component:** Server
**Operating system:** Docker container with base image centos:7
**Architecture:** 64 bit

### Description

I've build softethervpn server and configured it with the appropriate certificates that are relevant to my test case. When I try to connect with an openvpn client  with a certificate (Signed by a CA), I get an HMAC error after the initialization sequence completed.

I've had no issues with this when I ran a SoftEtherVPN server build from source when using commit https://github.com/SoftEtherVPN/SoftEtherVPN/commit/8fdd224ba7f5676f99d74c7c63f60e046d07ec97. 

Error:

```
Thu Sep 27 12:07:49 2018 Attempting to establish TCP connection with [AF_INET]172.17.0.2:1194 [nonblock]
Thu Sep 27 12:07:49 2018 TCP connection established with [AF_INET]172.17.0.2:1194
Thu Sep 27 12:07:49 2018 TCPv4_CLIENT link local: [undef]
Thu Sep 27 12:07:49 2018 TCPv4_CLIENT link remote: [AF_INET]172.17.0.2:1194
Thu Sep 27 12:07:49 2018 [openvpn.rsc.ixdev.net] Peer Connection Initiated with [AF_INET]172.17.0.2:1194
Thu Sep 27 12:07:51 2018 Preserving previous TUN/TAP instance: tun0
Thu Sep 27 12:07:51 2018 Initialization Sequence Completed
Thu Sep 27 12:07:54 2018 Authenticate/Decrypt packet error: packet HMAC authentication failed
Thu Sep 27 12:07:54 2018 Fatal decryption error (process_incoming_link), restarting
Thu Sep 27 12:07:54 2018 SIGUSR1[soft,decryption-error] received, process restarting
```

**Expected behavior:**
An openvpn connection

**Actual behavior:**
HMAC authentication failed

### Steps to reproduce

1. Build softethervpn from commit https://github.com/SoftEtherVPN/SoftEtherVPN/commit/06c06f1db885f70e585aaeef0df5a26de8b953e4
2. Run SoftEtherVPN server with certificates
3. Create an account with as username the common name of the certificate.
4. Connect with openvpn and and the appropriate certificates in the openvpn.ovpn file

**Comment by davidebeatrici** [comment]
Thank you very much for your report!

I opened #721 to fix the issue, please test and review it.

**Comment by ronneke1996** [comment]
I will test this after the weekend.

**Comment by davidebeatrici** [comment]
No problem.
