### ISSUE TITLE
Local bridging not working under OpenBSD

### ISSUE THREAD

**Issue by solipse** [SoftEtherVPN/SoftEtherVPN#723]
SoftEther version: 5.01 Build 9657 
Component: Server
Operating system: OpenBSD 6.3
Architecture: 64 bit

If create on vpncmd:
BridgeCreate command - Create Local Bridge Connection
Virtual Hub Name to Create Bridge: Default
Bridge Destination Device Name: soft
Error occurred. (Error code: 52)
Not enough privileges.

In vpnsmgr.exe button “Local Bridge Setting” not work

**Comment by davidebeatrici** [comment]
Are you logged in as server administrator?

**Comment by solipse** [comment]
If logged in server administrator:
Error occurred. (Error code: 84)
Local Bridge cannot be used by the destination VPN Server. Refer to online help or other documentation for the setting method when using Local Bridge on the VPN Server you are using.

**Comment by davidebeatrici** [comment]
I created #725 to fix the issue, please test and review it.

**Comment by chipitsine** [comment]
@solipse , we are looking for volunteers to support various BSD build agents

if you are interested in, please write something here: https://github.com/SoftEtherVPN/SoftEtherVPN/issues/668

**Comment by solipse** [comment]
Tested, everything works.

Thank you!

**Comment by davidebeatrici** [comment]
You're welcome!
