### ISSUE TITLE
Is Clustering Possible for Site to Site VPN

### ISSUE THREAD

**Issue by petergsnm** [SoftEtherVPN/SoftEtherVPN#73]
I was reading that clustering is not possible in cascade connection scenario. Is that true ? If this is true it will be a big limitation for site to site VPN.

Please let me know how can we achieve the clustering for a site-to-site VPN in order to increase the performance.?

**Comment by moatazelmasry2** [comment]
This is definitely currently not possible. I remember from a discussion some months (year?) ago that this is technically not possible, but I'm not sure anyway. 

What if you didn't use clustering and used instead multiple stand alone with the same configurations and all use the same radius server for authentication. Then added a load balancer infront of them Would that solve your problem???
