### ISSUE TITLE
Useage of "common" nameing for release tar.gz?

### ISSUE THREAD

**Issue by Andy2244** [SoftEtherVPN/SoftEtherVPN#731]
Just a quick note regarding the source release files.
I'm trying to switch from git releases to the source.tar.gz versions for openWRT and the naming is a bit odd.

Would be nice if Softether could follow other projects naming schemes.

Example:
Samba.org: `samba-4.9.0.tar.gz`
Softether: `v5.01.9658.tar.gz`

Its also unusual to have case sensitive root folders inside the archive aka "SoftEtherVPN" instead of "softethervpn". This means i need to specially construct the download url and build folders to match this scheme, instead of using the defaults.

Its just a minor thing, but maybe this can be changed?

**Comment by davidebeatrici** [comment]
The archive and its name are automatically generated by GitHub, they cannot be changed.

We could setup Travis CI so that it archives the repository and pushes the archive to GitHub.

**Comment by chipitsine** [comment]
I would stay with github naming

**Comment by Andy2244** [comment]
Just remembered that you can use codeload and a hidden redirect to get a proper filename-version scheme.

https://codeload.github.com/SoftEtherVPN/SoftEtherVPN/tar.gz/v5.01.9658
https://github.com/SoftEtherVPN/SoftEtherVPN/archive/v5.01.9658/SoftEtherVPN-v5.01.9658.tar.gz
