### ISSUE TITLE
Missing Mayaqua/cpu_features in the source releases.

### ISSUE THREAD

**Issue by Andy2244** [SoftEtherVPN/SoftEtherVPN#732]
It seems the default github release logic wont include external git projects, so Mayaqua/cpu_features is not included for the release and a build will fail. This means projects like openWRT can't use those archives and still need to use the rather large/slow 320MB git version.

So you could either switch to a copy/fork of cpu_features or manually add them to a local tar.gz and upload the releases.

**Comment by davidebeatrici** [comment]
From https://github.com/SoftEtherVPN/SoftEtherVPN/issues/731#issuecomment-427116553:
> We could setup Travis CI so that it archives the repository and pushes the archive to GitHub.

**Comment by paskal** [comment]
Hooray, I've fixed it in Launchpad by nesting it before the build! So Launchpad is not an issue anymore.

**Comment by chipitsine** [comment]
@paskal , do you mean something like "build step" within launchpad recipe ?

**Comment by paskal** [comment]
Yes. Now it fails in different place, I'll try to finally fix it.

**Comment by paskal** [comment]
Debian folder restored from last available before deletion version and now lives in [separate repo](https://github.com/paskal/SoftEtherVPN-debianisation). For now it [successfully builds](https://code.launchpad.net/~paskal-07/+recipe/softether-vpn-unstable) packages (trough likely improperly), I'll test and fine-tune it shortly.
I think we could include a note to readme what in case of trouble with Ubuntu packages people should create issues in this [separate repo](https://github.com/paskal/SoftEtherVPN-debianisation).

**Comment by chipitsine** [comment]
as for cmake (very recent cmake required), you can take something like that

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.gitlab-ci.yml#L7-L8

**Comment by chipitsine** [comment]
hi, @Andy2244 , @paskal 

I added tar + submodules in new releases

(it is done via AppVeyor machinery  https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.appveyor.yml#L79)

in the next release (which I expect in few days) full archive will look like that:

https://github.com/chipitsine/SoftEtherVPN/releases/download/v666.666.666/v666.666.666.tar.gz

**Comment by paskal** [comment]
It won't affect Ubuntu builds, however it seems it should fix Andy's problem.

**Comment by Andy2244** [comment]
Thanks will test this next week, if i have some time for openWRT again.

**Comment by Andy2244** [comment]
thanks is fixed and working now.
