### ISSUE TITLE
Administration of the VPN-Server only via Intranet

### ISSUE THREAD

**Issue by Adrian-Voelker** [SoftEtherVPN/SoftEtherVPN#737]
Hello,

first of all: SoftEther is great! Thank you all for developing!

My Question is:
Is there a possibility to block SoftEther-Server-Administration from the internet?

Currently it is possible to configure the server via the standart port. 
I want to limit the server-configuration to my local intranet.

Thank you all.

**Comment by MtCedarNet** [comment]
https://www.softether.org/4-docs/1-manual/3._SoftEther_VPN_Server_Manual/3.3_VPN_Server_Administration#3.3.18_Restricting_by_IP_Address_of_Remote_Administration_Connection_Source_IPs
