### ISSUE TITLE
Clarification of SoftEther release cycles

### ISSUE THREAD

**Issue by BlackHoleFox** [SoftEtherVPN/SoftEtherVPN#742]
I think it would be good to have documented somewhere publicly about how the release cycles work for the stable edition of SoftEther. Such items could be: What changes in the development branch(here) constitute a new download, general release cycle dates, or anything else that would be clarifying for those curious. 

This could possibly exist in a `releaseCycle_info.txt` file or the not inside the repository.

Thanks!

**Comment by chipitsine** [comment]
not sure it is a good place where stable edition should be discussed.
