### ISSUE TITLE
Support for SOCKS5 proxy

### ISSUE THREAD

**Issue by chinamore** [SoftEtherVPN/SoftEtherVPN#746]
There are two questions to ask:
1, SOFTETHER does not support the SOCKES5 protocol problem
The client uses the SOCKES5 protocol to link to the server and reports an error.
2, SOFTETHER source code CM.C on the simple mode and the normal mode is too complicated to write, how to simple control program default installation simple mode, no switch will never become normal mode

**Comment by davidebeatrici** [comment]
I copied your server's info in private and edited your message, for security.

**Comment by chinamore** [comment]
Don't worry, this SOCKES5 is only for testing, it doesn't affect anything, I just need to test SOCKES5 for everyone.

**Comment by chinamore** [comment]
172/5000
Rúhé zài yuánmǎ zhōng shèzhì
:Bool EasyMode;	// Simple mode
bool LockMode;	
mòrèn wéi zhēn, mùqián ānzhuāng mòrèn wéi jiǎ, wǒ bù zhīdào nǎlǐ huì xiě rù zhège cān shǔ de zhí

declare ClientManagerSetting
{
bool EasyMode false
bool LockMode false
}
How to set up in the source code
:bool EasyMode; // Simple mode
Bool LockMode;
The default is true, the current installation is false by default, I don't know where to write the value of this parameter.

Declare ClientManagerSetting
{
Bool EasyMode false
Bool LockMode false
}

**Comment by smssexe** [comment]
This is a very good PR.

**Comment by davidebeatrici** [comment]
@chinamore I created #790 which adds support for SOCKS5 servers, could you please test it with your own server?

**Comment by davidebeatrici** [comment]
Pull request merged.
