### ISSUE TITLE
L2TP/IPSec RSA authentication

### ISSUE THREAD

**Issue by ValdikSS** [SoftEtherVPN/SoftEtherVPN#76]
Hello, SoftEtherVPN team!

I'm trying to connect via L2TP/IPSec on Android using RSA certificate, and it always fails. According to bug #55, it seems that RSA authentication is not supported on all protocols except SoftEther protocol, is it?

**Comment by moatazelmasry2** [comment]
Unfortunately yes.

Is this a feature you would like to request? If so, please change the issue description accordingly, or even better we close this issue and create a new feature request issue

**Comment by moatazelmasry2** [comment]
No answer in a long time. Closing this issue
