### ISSUE TITLE
Why are the bins static linked, instead of shared?

### ISSUE THREAD

**Issue by Andy2244** [SoftEtherVPN/SoftEtherVPN#760]
I still wonder why after the cmake changes the bins are still linked static, instead of shared?

I use a simple sed fix, for the openWRT builds and everything works fine, while reducing the size by up to 3 times, since each binary links basically the same 2 libs.
```
$(SED) 's,STATIC,SHARED,g' $(PKG_BUILD_DIR)/src/Mayaqua/CMakeLists.txt
$(SED) 's,STATIC,SHARED,g' $(PKG_BUILD_DIR)/src/Cedar/CMakeLists.txt
```

Whats the reason for doing this and why not switch to shared by default and add a static build option?

PS: Since each bin has only small private code (10kb) a static linked multicall binary would also work fine, but since the bridge has different kernel dependency its not a ideal solution.

**Comment by davidebeatrici** [comment]
We will switch to shared libraries after #757 is merged.

**Comment by davidebeatrici** [comment]
Done: #761
