### ISSUE TITLE
libcedar.so not found automatically

### ISSUE THREAD

**Issue by qupfer** [SoftEtherVPN/SoftEtherVPN#766]
Hi,
I'm not very well with the "libary search thing" of linux systems, so this is maybe correct behaviour and my system is not propper configured.  :-)

### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
commit 5b11e6bffdceeb6d6203674b690397c85cb38452 (HEAD -> master, tag: v5.01.9661, origin/master, origin/HEAD)

**Component:** 
Server

**Operating system:** 
Linux (arch)

**Architecture:** 
64 bit

### Description

[Description of the bug]
If I want to start vpnserver (or vpnclient, vpncmd) I got the following error:
`/usr/local/libexec/softether/vpnserver/vpnserver: error while loading shared libraries: libcedar.so: cannot open shared object file: No such file or directory
`
**Expected behavior:**
vpnserver starts

**Actual behavior:**
vpnserver did not start because libcedar.so not found

### Steps to reproduce
```
1. ./configure
2. make -j4 -C tmp
3. sudo  make -j4 -C tmp install
4. vpnserver
```

#### Workaround
`env LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64 vpnserver`

**Comment by chipitsine** [comment]
@qupfer , can you try the following https://github.com/SoftEtherVPN/SoftEtherVPN/pull/767 ?

**Comment by qupfer** [comment]
Works on my system

**Comment by chipitsine** [comment]
it works for me as well. ok, merging

**Comment by paskal** [comment]
https://github.com/paskal/SoftEtherVPN-debianisation/issues/6 is the same, is it supposed to be fixed in upstream?

**Comment by paskal** [comment]
@davidebeatrici @chipitsine current location is an issue for debian:
```
Found files in /usr/local (must be in /usr).
debian/softether-common/usr/local
debian/softether-common/usr/local/lib
debian/softether-common/usr/local/lib/libcedar.so
debian/softether-common/usr/local/lib/libmayaqua.so
dh_builddeb.pkgbinarymangler: dpkg-deb --build debian/softether-common .. returned exit code 1
```
I'll switch it to /usr/lib for Ubuntu PPA and suggest you do the same.

**Comment by chipitsine** [comment]
we build packages for ubuntu 16.04, 18.04 (I am going to add upload to launchpad for those packages some time)

https://ci.appveyor.com/project/SoftEtherVPN/softethervpn/build/job/w1tydq8nsd0o1b3u

as a part of test process, we install packages and do "systemctl restart ...", it restarts (that means, no issue with `/usr/local`)


as for "doing the same", it is bad to use hardcode path, I think configurable path is better.
in those terms `/usr/local` is more "configurable" then default `/usr/lib`

you can choose either solution.
if you will include "install package" + "test restart" (ike we did already for app veyor), it would be nice

**Comment by chipitsine** [comment]
as for "doing the same in upstream", feel free to open PR on that (if you understand what you mean exactly), as I said already, we do not observe those issues in upstream anymore

**Comment by paskal** [comment]
It's against [Debian standard](https://wiki.debian.org/FilesystemHierarchyStandard) which is why Ubuntu PPA build refuses to do so. Quote:
> `/usr/local/` : Tertiary hierarchy for **local** data installed by the system administrator

**Comment by chipitsine** [comment]
it is exactly what you are installing.
local data.


how can you determine SE VPN is not local data, installed by system administrator ?

**Comment by paskal** [comment]
Local data installed by system administrator means something which is brought manually, not by packages: no standard Ubuntu packages write to this folder.
Also an issue I've bumped into: I can't use this repo tags because they are not correct version number from dpkg-buildpackage POV:
```
dpkg-buildpackage: warning:     debian/changelog(l1): version 'v5.01.9665~201812020153~ubuntu18.04.1' is invalid: version number does not start with digit
LINE: softether-vpn (v5.01.9665~201812020153~ubuntu18.04.1) bionic; urgency=low
```
Because of this I need to maintain my own versions. Could you please use tags without "v" in future?

**Comment by chipitsine** [comment]
@paskal, you seem trying to find the worst practice ever.

this issue is closed already. and originally it is not related to tags.

why not to open dedicated issue on tags ?

as for tags, currently they are not used for build numbers. build numbers are supposed to be taken from `src/CurrentBuild.txt`

probably we need to discuss it and do something. like CI check on "are build numbers the same in tag and inside that file"

**Comment by boubou** [comment]
Still have the same issue when building the source from git on a Debian 10.
