### ISSUE TITLE
Softether is blacklisted by BattlEye

### ISSUE THREAD

**Issue by chinamore** [SoftEtherVPN/SoftEtherVPN#768]
Hello developers of softether, tell everyone a less friendly news, https://www.battleye.com/ In the new version October 23, 2018, BattEEye 4.8.8 has blacked the use of softether The softether system processes vpnlient_64.exe and vpncmgr_x64.exe, and blocked all the vpnlient_64.exe and vpncmgr_x64.exe on the disk, which causes all the games using BattlEye to be accelerated by softether. Please help the developer to handle it, I also Will contact the busye official to deal with this problem, battleye. Anti-cheat does not work, anti-VPN is very good!

**Comment by davidebeatrici** [comment]
Hello!

By `which causes all the games using BattlEye to be accelerated by softether` you mean that the games which make use of BattlEye fail to start in case SoftEther VPN Client is running?

**Comment by chinamore** [comment]
BattEEye 4.8.8 kills all the softther system processes and scans the softether installation directory. If I don't uninstall all the software files, it will cause the computer to not participate in the game match of pubg.

**Comment by davidebeatrici** [comment]
Does stopping the SoftEther VPN Client service let you participate in a match?

**Comment by chinamore** [comment]
I am still unable to participate in the game by closing softether, because vpnclinte.exe is a service process, I can only participate in the game when uninstalling softether (BattEEye 4.8.8 detects the installation directory of softether)

**Comment by chinamore** [comment]
I can now install pptp with Korean VPS and use softether l2tp/ipsc to participate in the competition, but the risk is very high, and there is danger of being blocked by China Great Wall Firewall at any time, because I have not paid the protection fee.Moreover, we all use the China-Korea-CN2 line, which is very expensive. Once the IP is blocked, the loss cannot be afforded.

**Comment by chinamore** [comment]
Found the root cause: BattEEye 4.8.8 checks the software's digital signature, so the self-generated software used does not have a digital certificate, which results in direct detection by BattEEye 4.8.8, and then can not open the game, just do not know how to add a certificate to the source code

**Comment by chinamore** [comment]
CodeSign.cs ？？？？？Is this file? Who can give an example? It is best to provide a free signed certificate

**Comment by PaulGWebster** [comment]
if its doing process level detection you could put something like a rpi +usb ethernet infront of your computer, I mean preferable something a bit better but some sortof device with 2 ethernet ports anyhow... use that as a softether client and route you're pc through it.

Handle the connection at the other end exactly the same and then no process on you're computer will have any idea at all how its being routed :)
