### ISSUE TITLE
No Installer. ZIP please.

### ISSUE THREAD

**Issue by vpnserver-x64** [SoftEtherVPN/SoftEtherVPN#77]
On Windows, why can't you just offer a zip file containing (C:\Program Files\SoftEther VPN Server*.*) core files?

Why should I run Installer again to upgrade VPN software?
Please provide .ZIP package, so I can overwrite them to C:\Program Files\SoftEther VPN Server.

**Comment by chipitsine** [comment]
we have "zip" available at App Veyor artifacts now
