### ISSUE TITLE
Cluster Member's Local Bridge configuration

### ISSUE THREAD

**Issue by petergsnm** [SoftEtherVPN/SoftEtherVPN#78]
I am testing the SoftEther VPN Service Cluster service functionality.

In the Cluster Controller, I have configured a local bridge to the hub using tap device.  I used to have the following configuration (CL_MO being the static hub) and it used to create the static hub and do a local bridge.

declare LocalBridgeList
        {
                declare LocalBridge0
                {
                        string DeviceName tap0
                        string HubName CL_MO
                        bool LimitBroadcast false
                        bool MonitorMode false
                        bool NoPromiscuousMode true
                        bool TapMode true
                }
        }

Now, as I understand in a cluster scenario also, we also need to create the local bridge for the members too. 

The issue here is, the cluster member does not refer to the vpn_server.config, it receives the configuration from the Cluster Controller. So, if I put the local bridge configuration on the member's vpn_server.config it does not use the same. Also, once the cluster is established, it does not get the local bridge configuration from the cluster controller.

So, it boils down the thing that once the cluster is activated I have to go and manually configure the local bridge on the cluster member. We say, we not supposed to configure anything on the cluster member then why is this limitation?

Also, when we create a local bridge on the command line,  we can set the TAP mode by giving the following command, but we can't create set the PROMISC mode. 

VPN Server/CL_MO>BridgeCreate CL_MO /DEVICE:tap0 /TAP:yes

Ideally speaking the cluster member should also get the BRIDGE configuration from the master after it establishes the cluster configuration. Can this be fixed?

Thanks...Peter

**Comment by domosekai** [comment]
No. Local bridge must be setup on members as there is no assurance that each member has the same NIC or even OS.
