### ISSUE TITLE
How to distribute routes

### ISSUE THREAD

**Issue by petergsnm** [SoftEtherVPN/SoftEtherVPN#79]
I am trying to setup a site to site VPN. Once the site-to-site VPN is established, I want the VPN Server (using SoftEther VPN) to broadcast a route in that subnet (it is required to setup a route in that network such that all the PCs start sending the traffic to that VPN server for a particular route.

I heard this can be done through Quaaga. Has anyone done it? Any pointers please?

Thanks...Pete

**Comment by domosekai** [comment]
This is irrelevant to SE. You can use scripts and DHCP server to achieve that.
