### ISSUE TITLE
Feature request: Allow @ in username

### ISSUE THREAD

**Issue by GlennMatthys** [SoftEtherVPN/SoftEtherVPN#809]
Right now user accounts with the @ symbol in the username cannot be created. Since these days it's common to have email addresses double as username, it would be nice to maintain consistency and allow this.

**Comment by davidebeatrici** [comment]
The `@` symbol is used to determine the user's virtual hub, we should probably add a setting to specify a different character.

**Comment by BlackHoleFox** [comment]
A `:` character may work?

**Comment by davidebeatrici** [comment]
Sure, but we should use `@` as default in order not to break the login for updated servers.

**Comment by BlackHoleFox** [comment]
So it would be a config switch in the server between `@` and `:`, with `@` being the default?

**Comment by davidebeatrici** [comment]
Better: a config option to specify the character, with `@` being the default.

**Comment by davidebeatrici** [comment]
Done.
