### ISSUE TITLE
Feature Request: Support by default build chacha20 cipher on https

### ISSUE THREAD

**Issue by solipse** [SoftEtherVPN/SoftEtherVPN#810]
Supports DHE-RSA-CHACHA20-POLY1305 and ECDHE-RSA-CHACHA20-POLY1305, аnnounced in version 4.23 Build 9647 Beta (October 18, 2017), but so far they are not in the default builds.

And with this would greatly works the old devices without AES-NI and soho routers.

**Comment by davidebeatrici** [comment]
The OpenSSL static libraries in the repository have been updated to version 1.1.1 in #738, the ciphers you mentioned should be available in the latest builds.

What do you mean by "they are not in the default builds"?

**Comment by solipse** [comment]
Understood, they are not available for selection in GUI manager for Windows version 4.xx
In vpncmd release v5.01.9663 available and works.
Windows GUI manager v5.01.9663 I did not test, it looks like the installer is broken, closes during installation.

**Comment by davidebeatrici** [comment]
> Understood, they are not available for selection in GUI manager for Windows version 4.28
In vpncmd release v5.01.9663 available and works.

Related issue: #360

> Windows GUI manager v5.01.9663 I did not test, it looks like the installer is broken, closes during installation.

Related issue: #689
