### ISSUE TITLE
Win7 - IP leak while connected

### ISSUE THREAD

**Issue by top-master** [SoftEtherVPN/SoftEtherVPN#829]
**SoftEther version:** `4.24, Buils 9651` and `5.01, 9665` (i.e. tested on both)
**Component:** Client
**Operating system:** Windows 7
**Architecture:** 64 bit (x86_x64)
**Processor:** Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz

### Description

after a successful connection to server everything just works and `ipaddress.com` does show the `IP` of the server, However after a while if we refresh the site `ipaddress.com` we see that our original IP is restored while the connection is still established.

**Expected behavior:**
It should keep routing the traffic to our companies SE-server until we press disconnect or at least until there is an error

**Actual behavior:**
We do lose servers IP address and our original IP gets visible while there is no single error with the connection

### Steps to reproduce
1. Install SoftEther-Client, run, connect to any SE-Server (ensure it works), disconnect
2. Run `ipconfig /release` and `ipconfig /renew` commands to refresh all Network-Adapters
3. Open `ipaddress.com` in `Chrome` (to make at least one use from real-adapter)
4. Connect to any SE-Server
5. Refresh the site `ipaddress.com` (to make at least one use from vpn-adapter, ensure it works)
6. First disconnect from SE-Server
7. Then `Hibernate` the system (without even closing the browser)
8. Power-on again
9. Refresh the site `ipaddress.com` (to again use the real-adapter at least once)
10. Connect to any SE-Server again (the IP should be changed in this point)
11. Start any download in your Internet-Download manager
(just to increase bandwidth usage, mine is limited by 512 Kilo-Bit)
12. Keep refreshing the site `ipaddress.com` about `7` times (wait each time until fully loaded)
13. After some point we notice that the server IP is lost and the original is visible again

If we Disconnect and repeat above steps only the number of times we need to refresh does change
### Update:
After running the commands `ipconfig /release` and `ipconfig /renew` it did become really hard to reproduce this issue;
and it is really stable, only after long time playing around with `connect` and `disconnect` it did happen again (without any hibernate).

**Comment by top-master** [comment]
below is the `route print` command result (where `192.168.30.10` and metrics `2` and `257` belong to `VPN Client Adapter`):
```cmd
===========================================================================
Interface List
 35...00 ac 57 34 84 38 ......VPN Client Adapter - VPN
 42...84 3a 4b 40 e8 6d ......Microsoft Virtual WiFi Miniport Adapter #25
 16...00 21 cc d8 fe 4a ......Intel(R) 82579LM Gigabit Network Connection
 14...f4 b7 e2 f6 db ac ......Bluetooth Device (Personal Area Network)
 11...84 3a 4b 40 e8 6c ......Intel(R) Centrino(R) Advanced-N 6205
  1...........................Software Loopback Interface 1
 68...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter
 73...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #2
 43...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #3
 37...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #4
 45...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #6
 64...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #7
===========================================================================

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0   192.168.10.254    192.168.10.21     25
          0.0.0.0          0.0.0.0     192.168.30.1    192.168.30.10      2
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    306
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    306
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    306
     192.168.10.0    255.255.255.0         On-link     192.168.10.21    281
    192.168.10.21  255.255.255.255         On-link     192.168.10.21    281
   192.168.10.255  255.255.255.255         On-link     192.168.10.21    281
     192.168.30.0    255.255.255.0         On-link     192.168.30.10    257
    192.168.30.10  255.255.255.255         On-link     192.168.30.10    257
   192.168.30.255  255.255.255.255         On-link     192.168.30.10    257
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    306
        224.0.0.0        240.0.0.0         On-link     192.168.10.21    281
        224.0.0.0        240.0.0.0         On-link     192.168.30.10    257
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    306
  255.255.255.255  255.255.255.255         On-link     192.168.10.21    281
  255.255.255.255  255.255.255.255         On-link     192.168.30.10    257
===========================================================================
Persistent Routes:
  None

IPv6 Route Table
===========================================================================
Active Routes:
 If Metric Network Destination      Gateway
  1    306 ::1/128                  On-link
 11    281 fe80::/64                On-link
 35    276 fe80::/64                On-link
 11    281 fe80::8438:32e4:4257:a00a/128
                                    On-link
 35    276 fe80::c52b:1bc6:9a60:156b/128
                                    On-link
  1    306 ff00::/8                 On-link
 11    281 ff00::/8                 On-link
 35    276 ff00::/8                 On-link
===========================================================================
Persistent Routes:
  None
```

**Comment by dnobori** [comment]
Could you please attack the "Advanced Settings" dialog box of your connection settings as the following?

![clip_12](https://user-images.githubusercontent.com/3041130/49496203-ac143600-f8a8-11e8-8fa0-08a52217d44c.jpg)

**Comment by top-master** [comment]
We did ask the server provider for the screenshot, but I do not think it is related to the server;
since `WireShark` does not show any traffic being sent to the `VPN Adapter` once the issue happens.

we are sure this is related to the `client` or `adapter`

**Comment by top-master** [comment]
After setting `No Adjustments of Routing Table` to `off` was never again able to reproduce this issue (no wonder since `SoftEther-Client` now does ensure there is only one `0.0.0.0` in route table)

so will close this issue, but feel free to open this issue if `No Adjustments of Routing Table` is meant to be `on` by default (when `SoftEther-Client` is installed the first time)
