### ISSUE TITLE
Please remove trailing leading "v" from version in git tags

### ISSUE THREAD

**Issue by paskal** [SoftEtherVPN/SoftEtherVPN#836]
Hello, team!

Could you please remove "v" from version so it's will be [semver](https://semver.org/)-compatible and I'll be able to use it as-is as package version for Ubuntu PPA builds? With current scheme (`v5.01.9666`) I can't use tag as-is.

Thank you!

**Comment by davidebeatrici** [comment]
Done!

**Comment by paskal** [comment]
Thanks _a lot_!

**Comment by davidebeatrici** [comment]
You're welcome!
