### ISSUE TITLE
[Deb] Move files from /usr/local/ to /usr/

### ISSUE THREAD

**Issue by paskal** [SoftEtherVPN/SoftEtherVPN#837]
Hello, team!

At least for Debian packages you're putting common files in `/usr/local/` directory. As discussed [there](https://github.com/SoftEtherVPN/SoftEtherVPN/issues/766#issuecomment-443667556) could you please move them to just `/usr/`? No Ubuntu or Debian package puts files in `/usr/local` and I think this package shouldn't be doing this as well.

**Comment by chipitsine** [comment]
@paskal , we are not very powerful on debian packaging (as you might have noticed already, we break packaging few times per year).

however, we do not proud of breaking packaging and we ask your help on improving its robustness.

particularly, can you help in a couple of things:

1) can this setting help to resolve this issue https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/CMakeLists.txt#L59 ? if so, can you add `CMAKE_INSTALL_PREFIX=/usr` to your packaging recipies ?

2) if packaging need to be resolved within upstream, what kind of change should it be ? and how can we test it (we will add tests to App Veyor) ?

**Comment by paskal** [comment]
I'm sorry, I've looked into it and it looks like there is no elegant way to fix things. I think current state is good and shoudln't be altered because this problem solving will add complexity but will give no value in return. Resolving, if noone minds.
