### ISSUE TITLE
Some Passwords with special characters do not work with the SoftEther Client.

### ISSUE THREAD

**Issue by spirritus** [SoftEtherVPN/SoftEtherVPN#840]
Hi there,

when using the SoftEther Client to connect to the SoftEther Server some passwords do not work. However, when using an OpenVPN client the SAME passwords do work. I guess there is something wrong with UTF-8 handling or escaping of special symbols.

Server Version: 4.27 Build 9667
Client Version: 4.28 Build 9669

[PasswordTestResult.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/2690080/PasswordTestResult.txt)

**Comment by chipitsine** [comment]
hello, thank you for your investigation.
4.X is related to https://github.com/SoftEtherVPN/SoftEtherVPN_Stable

you have opened an issue in "developer" repo, it has 5.X versions. can you try to reproduce your issue on 5.X ?

**Comment by spirritus** [comment]
Ah, i did not know there where multiple repos. I reopen the issue in 4.x then. If there are 5.x builds i can try yes.

**Comment by chipitsine** [comment]
which OS do you use ?

we built releases for few of them https://github.com/SoftEtherVPN/SoftEtherVPN/releases

(or you can follow build instruction and build it from source)
