### ISSUE TITLE
What naming scheme would the users like to see for releases?

### ISSUE THREAD

**Issue by davidebeatrici** [SoftEtherVPN/SoftEtherVPN#846]
These are the current names of the files:
```
softether-vpn-portable-v5.01-9667-2018.12.21-windows-x64-pdbs.zip
softether-vpn-portable-v5.01-9667-2018.12.21-windows-x64.zip
softether-vpn-src-5.01.9667.tar.gz
softether-vpn-v5.01-9667-2018.12.21-windows-x64-pdbs.zip
softether-vpn-v5.01-9667-2018.12.21-windows-x86-pdbs.zip
softether-vpnclient-v5.01-9667-2018.12.21-windows-x86_x64-intel.exe
softether-vpnserver_vpnbridge-v5.01-9667-2018.12.21-windows-x86_x64-intel.exe
```

We would like to adopt a clear and concise naming scheme which can be used for automated build systems.

@Andy2244 @paskal

**Comment by metalefty** [comment]
And create a directory like `SoftEtherVPN-${VERSION}` under the tarball. Please don't mess up current working directory.

**Comment by davidebeatrici** [comment]
I agree.

**Comment by paskal** [comment]
I like your debian packages naming and I think you can use it for all platforms.

**Comment by davidebeatrici** [comment]
```
softether-common_5.1.9667_amd64.deb
softether-vpnbridge_5.1.9667_amd64.deb
softether-vpnclient_5.1.9667_amd64.deb
softether-vpncmd_5.1.9667_amd64.deb
softether-vpnserver_5.1.9667_amd64.deb
```

You mean this one?

**Comment by Andy2244** [comment]
ok i just tried to create a new makefile for openwrt using softether-vpn-src-5.01.9667.tar.gz

The problem is that there is no root subfolder inside the archive, which means i need to use special handling to unpack the file and get it inside a valid build subfolder. Usually packages have a single root folder named like $(PKG_NAME)-$(PKG_VERSION) inside the archive.

Example: samba-4.9.4.tar.gz has a "samba-4.9.4" root folder and all code is under it. I cant remember the last 
QEMUworks similar:
```
wget https://download.qemu.org/qemu-3.1.0.tar.xz
tar xvJf qemu-3.1.0.tar.xz
cd qemu-3.1.0
```

So if its possible i would suggest to handle the source with a similar structure.

**Comment by metalefty** [comment]
@Andy2244 you're just repeating what i said

**Comment by Andy2244** [comment]
> 
> 
> @Andy2244 you're just repeating what i said

Sorry just skimmed over the thread and missed your quick note about this :)

**Comment by ronneke1996** [comment]
Like @paskal said I really like the debian package naming. 
I do think you should add something like the commit hash(the short hash) for builds that do not have a tag. So when somebody builds from master you would know which version and commit they use. This would also be easier for reporting issue etc.

So something like this:
Tags:
```
softether-common_5.1.9667_amd64.deb
softether-vpnbridge_5.1.9667_amd64.deb
softether-vpnclient_5.1.9667_amd64.deb
softether-vpncmd_5.1.9667_amd64.deb
softether-vpnserver_5.1.9667_amd64.deb
```

Build from master/other branches
```
softether-common_5.1.9667.3b85a11_amd64.deb
softether-vpnbridge_5.1.9667.3b85a11_amd64.deb
softether-vpnclient_5.1.9667.3b85a11_amd64.deb
softether-vpncmd_5.1.9667.3b85a11_amd64.deb
softether-vpnserver_5.1.9667.3b85a11_amd64.deb
```

This could be achieved by using the TWEAK version option from cmake.

**Comment by Andy2244** [comment]
> 
> 
> And create a directory like `SoftEtherVPN-${VERSION}` under the tarball. Please don't mess up current working directory.

Just updated to 9668, so source releases are now always under `https://github.com/SoftEtherVPN/SoftEtherVPN/archive/` ?
I also noticed that any other openwrt package, extracts using lowercase only aka `softethervpn-${VERSION}`?
I guess that's some convention of preventing case errors in scripts?

**Comment by Andy2244** [comment]
@chipitsine Quick question, i don't see the manual created source releases i use for openwrt for the last two releases 9668/9 are those just minor updates so they have none or did something change how you release versions?

**Comment by chipitsine** [comment]
@Andy2244 , they were not manual. they were supposed to be created by App Veyor, however we ran out of artifacts quota.

we are moving that to Azure Pipelines. thank for your patience

**Comment by Andy2244** [comment]
np, thanks for the info was just wondering if something broke, was changed.

**Comment by Andy2244** [comment]
@chipitsine Why does the current release ignore anything that was discussed here and does not even follow the old naming rule.
`5.01.9670.tar.gz` vs `softether-vpn-src-5.01.9667.tar.gz`
The archive still has no root folder like SoftEtherVPN-${VERSION} under the tarball.

**Comment by chipitsine** [comment]
@Andy2244 , sorry. lack of time

**Comment by metalefty** [comment]
This issue is still pinned. I would say this can be unpinned.
