### ISSUE TITLE
softethervpn-android ，I really want everyone to develop and develop.

### ISSUE THREAD

**Issue by chinamore** [SoftEtherVPN/SoftEtherVPN#853]
“github.com/lfasmpao/softethervpn-android”
“https://play.google.com/store/apps/details?id=io.github.lfasmpao.softethervpn&hl=zh”
At present, some enthusiasts have developed a test version, but they must have ROOT permissions. In the past, he also released the source code, but unfortunately the new mobile phone can not make ROOT permissions, can not use his test client, I hope to have a team development The client that comes out of the mobile phone link, don't try to use the protocol that comes with the phone to link to the server, because this is completely impossible in some countries, such as China.
The benefit of this is that it can increase the range of customers using softether, and maybe this project is really difficult. But someone has tried it, but I think this is a way that software must go. There must be a dedicated Android mobile client.

**Comment by chinamore** [comment]
This software is licensed open source, so they removed the digital signature part. As for how to increase the digital signature, you have to ask SOFTETHER, the version they released is signed, and the open source is not signed.

**Comment by davidebeatrici** [comment]
Superseded by #1019.
