### ISSUE TITLE
How  to gen CSR and buy cert on COMODO

### ISSUE THREAD

**Issue by caizixian** [SoftEtherVPN/SoftEtherVPN#86]
I want to use COMODO's SSL cert for SSTP, openvpn, l2tp and Server Manager.
Is that possible?
If some of them are possible, I'd like to know how to gen CSR and use it to buy SSL cert.

**Comment by moatazelmasry2** [comment]
Currently certificate authentication is only supported in own SoftEtherVPN Protocol but not in other protocols
