### ISSUE TITLE
Available encryption algorithms list not shown with server running in OpenBSD

### ISSUE THREAD

**Issue by solipse** [SoftEtherVPN/SoftEtherVPN#861]
SoftEther version: 5.01 Build 9667
Component: Server
Operating system: OpenBSD 6.4
Architecture: 64 bit

In vpncmd:
Command ServerCipherGet don't retrieve the list of all available encryption algorithms.
Retrieve only currently used algorithm.

Command ServerInfoGet retrieve previous Version 5.01 Build 9666

**Comment by davidebeatrici** [comment]
Has SoftEther VPN Server been compiled after 8ec43e76182227a308d5c40ee66d5eb49fce0197 was merged?

The list of available ciphers is unavailable when the RPC call fails.

**Comment by solipse** [comment]
Yes, compiled after https://github.com/SoftEtherVPN/SoftEtherVPN/commit/8ec43e76182227a308d5c40ee66d5eb49fce0197 merged.

**Comment by davidebeatrici** [comment]
I created #862 to fix the issue, please test and review it.
