### ISSUE TITLE
[Bug] Status 'connected' but cannot access vpn network

### ISSUE THREAD

**Issue by marjanoh2** [SoftEtherVPN/SoftEtherVPN#863]
I noticed that sometimes I can not access the vpn network although the status is connected. I tried to discover one such case in the following way:
1. I connect to one WiFI network and connect to a vpn connection and I can normally access the network.
2. I change the WiFI network and the status remains 'connected', but I no longer have access to the network (no ping).
3.Click disconnect and then re-connect the vpn connection and it works again normally.

Whether it is a bug or need some additional setup? I think it's a bug since the status is 'connected' and I do not have access until I reconnect the vpn connection.

Ver 4.28, Build 9669

Video from situation:
https://drive.google.com/open?id=1ieQttpdUBA5x5i-rqjgBbFhxktCnrLFS

**Comment by chinamore** [comment]
This may be caused by firewall interference and flashing. This situation often occurs in China. If you have this situation, please change the server encryption method and do not use the RC-MD5 encryption method.

**Comment by marjanoh2** [comment]
I try with AES256-SHA256, but the problem is not resolved.

**Comment by domosekai** [comment]
No change needed.
