### ISSUE TITLE
Client profile password field encryption is not consistent

### ISSUE THREAD

**Issue by bevinhex** [SoftEtherVPN/SoftEtherVPN#874]
**SoftEther version:**
**Component:** [Server, Client 4.28 latest]
**Operating system:** [Windows, Linux, macOS tried on all of them]
**Architecture:** [64 bit, 32 bit included]

**Processor:** [Mine is AMD64, my colleague also tried on his computer, on windows as well as mac]

### Description
Client software exported 'EncryptedPassword' field is not consistent among computers.
**Expected behavior:**
With same version of softether, same password should be encrypted same.

**Actual behavior:**
EncryptedPassword field varies depending on the computer

### Steps to reproduce
* create one account on client on linux (64bit debian) machine using vpncmd, set password with 'accountpasswordset' command, for test put '0' as password, choose 'radius' for authentication type, then I export the profile using 'accountexport' command, observing the *.vpn file that exported, will see something like
```
declare ClientAuth
	{
		uint AuthType 2
		byte EncryptedPassword Xg==
		string Username test
	}
```
* create another user on windows machine (32bin win7), set password as '0' as well, choose 'radius' for authentication type, then export the profile, will get:
```
declare ClientAuth
	{
		uint AuthType 2
		byte EncryptedPassword tw==
		string Username test
	}
```

So here problem is in both cases I used '0' as password, however encryption is different, The point of doing this is to be able to share exported configuration to other people, but since password encryption is kept varying, it is becoming impossible.

After some testing we found out that we get 'tw==' on 32bit CPU, 'Xg==' on 64bit CPU, so encryption might be affected by CPU

Another interesting fact is:
At one point after checking password field encryption part of the source code, I managed to encrypt '0' using 'rc4' on same linux machine (64bit) using same 'Key' used in softether, with openssl, but I get 'tw==' instead of the 'Xg==' that I was getting from softether.

**Comment by domosekai** [comment]
No change needed.
