### ISSUE TITLE
5.01.9669  Construction failure

### ISSUE THREAD

**Issue by chinamore** [SoftEtherVPN/SoftEtherVPN#876]
1#:
#endif	// BU_OSS

			/*
			w.WriteLine("mkdir \"{0}\\autorun\"", cddir);
			w.WriteLine("copy /b /y autorun\\autorun.ico \"{0}\\autorun\"", cddir);
			w.WriteLine("copy /b /y autorun\\autorun.exe \"{0}\\autorun\"", cddir);
			w.WriteLine("copy /b /y autorun\\autorun.inf \"{0}\\autorun.inf\"", cddir);
			 * */

			 string zipFileName = string.Format("VPN-CD-v{0}.{1:D2}-{2}-{3}-{4:D4}.{5:D2}.{6:D2}.zip",

Unrecognized command =string
				
2#:错误	12	fatal error LNK1104: 无法打开文件“atlthunk.lib”	vpnweb	vpnweb

Error 12 fatal error LNK1104: Unable to open file "atlthunk.lib" vpnweb vpnweb

**Comment by domosekai** [comment]
Close due to inactivity
