### ISSUE TITLE
USERLIST for servers

### ISSUE THREAD

**Issue by chinamore** [SoftEtherVPN/SoftEtherVPN#879]
How to manage users on the server through the database, such as mysql database?

**Comment by chipitsine** [comment]
you can try some RADIUS implementation with mysql backend. or write some code to support mysql directly

**Comment by chinamore** [comment]
Thank you for your reply, I see a few questions when I see you: 1. The source code cannot compile errors, fatal errors. 2. Why does the development version not generate linux-x64-64bit.tar.gz?3, which local custom routing table can be achieved? 4. Happy New Year!

**Comment by paulmenzel** [comment]
On 18.02.19 09:01, chinamore wrote:
> I see a few questions when I see you: 1. The source code cannot compile errors, fatal errors. 2. Why does the development version not generate linux-x64-64bit.tar.gz?3, which local custom routing table can be achieved? 4. Happy New Year!

Please open separate issues for each item.

**Comment by chinamore** [comment]
＃876

**Comment by chinamore** [comment]
＃858

**Comment by metalefty** [comment]
Just to link, #876 #858

**Comment by chinamore** [comment]
softether ues RADIUS (only windwos server),now some servers ues freeRADIUS
