### ISSUE TITLE
SoftEther in Zankyou no Terror

### ISSUE THREAD

**Issue by ValdikSS** [SoftEtherVPN/SoftEtherVPN#88]
![Episode 4](http://i.imgur.com/GQ0Nanl.png)

**Comment by fhocorp** [comment]
Nice !

**Comment by moatazelmasry2** [comment]
Sorry I don't understand. What is the issue????

**Comment by moatazelmasry2** [comment]
The OP seems to be inactive. For this reason I'd like to close this issue within the next few days if there are no objections. 

Cheers

**Comment by ValdikSS** [comment]
Well, what should I comment here? These are screenshots from Zankyou no Terror anime series, and, as you can see, softether is mentioned in a traceroute and in a host name.
So this is not a real issue, just a fun fact.
