### ISSUE TITLE
L2TP SEE USER ONLINE 

### ISSUE THREAD

**Issue by Ilo89** [SoftEtherVPN/SoftEtherVPN#880]
Hello
For l2tp
 is it possible to see if the users are online ?

Thanks

**Comment by BlackHoleFox** [comment]
It looks like you should be able to look at the session management tab inside the virtual hub settings.
![image](https://user-images.githubusercontent.com/20936452/52976058-dbbede80-33bf-11e9-9e71-34037c4920ba.png)

**Comment by Ilo89** [comment]
> It looks like you should be able to look at the session management tab inside the virtual hub settings.
> ![image](https://user-images.githubusercontent.com/20936452/52976058-dbbede80-33bf-11e9-9e71-34037c4920ba.png)

Thank you for your reply, i don't specify, i use linux centos not windows software

**Comment by BlackHoleFox** [comment]
I'm thinking then `vpncmd` would work better for you then. See [SoftEther Docs](https://www.softether.org/4-docs/1-manual/6._Command_Line_Management_Utility_Manual/6.4_VPN_Server_%2F%2F_VPN_Bridge_Management_Command_Reference_(For_Virtual_Hub)#6.4.82_.22SessionList.22:_Get_List_of_Connected_Sessions)

**Comment by Ilo89** [comment]
I have already tried but there is no command to see if the user is online or offline

**Comment by BlackHoleFox** [comment]
I may of misunderstood the original intent then, my bad. You want to compare users that are in that hub with those who currently have a active session on the server?

**Comment by Ilo89** [comment]
yes, I'm interested to see if the user I created is online or not

**Comment by MtCedarNet** [comment]
User objects don't have online/offline status.
What kind of state do you want to know?

**Comment by BlackHoleFox** [comment]
@Ilo89 I went ahead and created a small Python application that checks what users are "online". It does this by seeing how many sessions the user has, if any. Probably not perfect but it may help you out. https://github.com/BlackHoleFox/SoftEtherVPN-User-Checker
