### ISSUE TITLE
CI Server for Illumos/Solaris

### ISSUE THREAD

**Issue by hww3** [SoftEtherVPN/SoftEtherVPN#881]
Hi,

This could probably be considered a response to #668, but I didn't want to comment on a closed issue.

A few months ago I submitted some patches for Illumos/Solaris. At the time there was a suggestion that running CI for this platform might be a good idea. Since Travis doesn't support Solaris or Illumos, setting up a gitlab-runner seemed like the best option. It took me a lot longer than expected, but I finally got a gitlab-runner compiled and set up on an Illumos (i.e., OpenSolaris) box. 

If this is still of interest, I'm happy to help get this set up, though the gitlab-runner documentation recommends against running a runner on a private box that's not "part of the project". I've set the runner up on a free AWS instance that I wouldn't be using for anything else, but I think that concern is /possibly/ still valid... happy to hear thoughts about that.

Anyhow, feel free to comment if having help on illumos (and solaris as its compatibility intersects with illumos) is of interest.

Bill

**Comment by chipitsine** [comment]
great news!

so, do you have public gitlab.com repo to have a look at ?

**Comment by hww3** [comment]
Hi-

I've got a Gitlab Runner running on a test repo I've got mirrored from Github, and it seems to be working. I've also created a CI mirror of the SoftEtherVPN repo that I've connected to my Illumos/Solaris runner. I think that a job will need to be added to .gitlb-ci.yaml... the runner is tagged for "illumos". Shall I make a proposal for this, or is there someone skilled in this that might prefer to do that? The runner should have all of the required tools and libs ready to run, so I don't expect it will require a lot of tinkering.

That repository is at https://gitlab.com/hww3/SoftEtherVPN

**Comment by chipitsine** [comment]
hello, I suggest the following steps

1. break mirror relationship between  https://gitlab.com/hww3/SoftEtherVPN and its parent
2. create some working CI config
3. create PR with .gitlab-ci.yml changes
4. attach your runner to SE VPN gitlab repo

as for "2", I think it is good idea to tag as "illumos" (both runner and CI job). what to run in job itself, I would start with "just build" job. I do not understand solaris, but if you will add me to your fork, I can try something (or feel free to try yourself)
