### ISSUE TITLE
[Security problem] "CheckServerCert" default value

### ISSUE THREAD

**Issue by tienthanh411** [SoftEtherVPN/SoftEtherVPN#882]
By default , "CheckServerCert" setting of SoftEther VPN client is set to False, which means that the client doesn't verify the server's TLS certificate. This default value properly has negative impacts on the commercial VPN providers that deploy SoftEther VPN. In fact, I found several VPN providers that support SoftEther VPN don't change the default value of "CheckServerCert", which makes their VPN connection insecure. 

Thus, I think that it is better to set "CheckServerCert" to True, by default. Also, since all the examples I found on SoftEther VPN's github also set the setting to False, these examples should also be updated.

**Comment by chipitsine** [comment]
Hello

Can it be propagated in client configs?

**Comment by tienthanh411** [comment]
Sorry, I don't understand what you meant

**Comment by chipitsine** [comment]
when commercial VPN provider deploys SoftEtherVPN, usually he supply config files for clients. Can that setting be included in that config ?

**Comment by tienthanh411** [comment]
Yes, the setting is set to False in the config file.
Also, some VPN providers instruct their users to use the SoftEther VPN GUI on Windows (e.g. [this](https://www.cactusvpn.com/tutorials/how-to-set-up-softether-vpn-on-windows/) or [this](https://my.ibvpn.com/knowledgebase/321/How-to-configure-and-use-ibVPN-with-SoftEther-on-Windows-OS.html)), and the GUI by default does not enforce the server certificate's verification.

**Comment by chipitsine** [comment]
I would say that it is up to cactus vpn and their customers. if they beleive in "True", they can provide their users way to set it up.

no need to change default setting (it might break things)

**Comment by chipitsine** [comment]
well, I see "Step 2. Follow this link to download the .vpn files" in their guide.
why not to include proper setting to those .vpn files ?

**Comment by chipitsine** [comment]
thank for SE VPN public providers, btw
really nice sites, will have a deeper look

**Comment by tienthanh411** [comment]
It's always better to have the software secure by default. Normal users, who usually don't have technical background, may not understand the risk of not checking the server's certificate. 

If the SoftEther VPN team doesn't want to change the default value of "CheckServerCert", is it possible to update the examples (e.g. [this](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/1e8cf1dc5d40d35b3f3ae5847de9e817b24fe3b0/src/bin/hamcore/empty_sevpnclient.config)) so that the value is set to True? Also, is it possible to update the guides and documentations of the software so that SoftEther VPN users would understand more about the importance of the ""CheckServerCert" setting?

**Comment by chipitsine** [comment]
changing default values is bad.
providing better documentation is good.


you are welcome to make PR

**Comment by domosekai** [comment]
I assume no change is required.
