### ISSUE TITLE
PacketiX API for PHP

### ISSUE THREAD

**Issue by chinamore** [SoftEtherVPN/SoftEtherVPN#890]
https://github.com/Flast/php-packetix
PHP-packetix
例：
<html>
<head>
  <title>PacketiX API for PHP</title>
</head>
<body>
  <?php
    require_once('packetix/packetix.php');
    try {
      $client = packetix_readonly_admin('example.com')->pass('password');
      if ($client->test()) {
        printf("<p>PacketiX RPC test successful</p>\n");
      }
    } catch (PacketiX\VPNException $e) {
      printf("<p>%s</p>\n", $e->getMessage());
    }
  ?>
</body>
</html>

Who knows how to use this stuff, I have already installed it!

**Comment by chinamore** [comment]
http://rusa.175.es/

**Comment by chipitsine** [comment]
unfortunately, this is wrong repo for such questions.
we are interested in third party components, however, currently nobody of us is related to PacketIX PHP
