### ISSUE TITLE
TAP, DNS, Unbound ?

### ISSUE THREAD

**Issue by BedoM** [SoftEtherVPN/SoftEtherVPN#895]
Hello,
Thank you all for your work!
I'm using softether for 1 day, before i was on openvpn only.
Everything works as I want it only I have a DNS leak that I did not have on openvpn because I used unbound with it.

Do you know if some happens to use unbound with softether?
And
Do you know why my TAP does not have an ip address?

Thank you for all.

Debian 9 stretch at oneprovider

**Comment by ronneke1996** [comment]
I'm not sure whats the problem with DNS, but about you not having an ip address on TAP is right.

I highly suggest reading this issue: https://github.com/SoftEtherVPN/SoftEtherVPN/issues/822

If you want DHCP with tap you should apply the patch of davidebeatrici yourself. 
Patch: https://github.com/SoftEtherVPN/SoftEtherVPN/pull/827/files
