### ISSUE TITLE
vpncmd stdout buffering (Linux)

### ISSUE THREAD

**Issue by MatAtBread** [SoftEtherVPN/SoftEtherVPN#898]
### Prerequisites

* [Y ] Can you reproduce?
* [ Y] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** vpncmd (client or server)
**Operating system:** Linux
**Architecture:** 64 bit (probably the same in 32 bit)

**Processor:** i7

### Description

Feature request: provide a command line option to disable stdout buffering, eg:
```
#include <stdio.h>
setbuf(stdout, NULL);
```

This is required to drive `vpncmd` as a child process interactively (in my case from Node JS). Note that is NOT an issue in Windows (works fine - output is passed to the parent process line by line)

**Comment by chipitsine** [comment]
Hi

Can you tell us what do you do with node.is?

**Comment by MatAtBread** [comment]
Sure. The code is here: https://github.com/MatAtBread/SoftEtherWeb/blob/master/lib/vpncmd.js

I'm building a simple Web UI, It spawns `vpncmd` and then uses it interactively - reading responses and sending commands.

The issue is not `node` per se - the same behavior happens if you pipe `vpncmd` to `tr`, for example. The responses don't fill the output buffer, so `tr` just sits waiting on the pipe.

Another fix would be to call `fflush` after printing the "VPN Server>" prompt - this would cause the pipe to output to the parent process.

This is a feature of Linux buffering - under Windows it works fine

**Comment by chipitsine** [comment]
So, it is web api on top of vpncmd, right?

**Comment by chipitsine** [comment]
@MatAtBread , we have discussed that in SE VPN team.
it is ok to change behaviour of vpncmd.

can you submit a patch (pull request) please ?

**Comment by chipitsine** [comment]
also, please notice, you are talking about SE VPN developer edition, not stable edition (I noticed your Web UI relates to www.softether.org - that is stable edition)

**Comment by MatAtBread** [comment]
TBH, I've not yet the developer edition, etc, so I don't know if that you'd behave differently.

Yes, it's a (basic) WebUI on top of `vpncmd`

I'd happily submit a PR, could you point me at a file that is the CLI interpreter (it's a very big project, and I'm not familiar with it). If you have any tips about building for Linux, or a page that describes the build process, that'd be really helpful too.

As for default behaviour, I can't imagine a scenario where the current behaviour (buffered IO) in an interpretive system would be useful, or why anyone would depend on such behaviour

**Comment by MatAtBread** [comment]
...in any case, I'd put it behind a CLI option such as `/unbuffered`

**Comment by chipitsine** [comment]
development process of stable and developer editions differ, however they are supposed to be compatible.

build process is described (at least we think so), if you will find some difficulties, we would like to hear about them.

current behaviour is not intended, so we do not want to keep it (buffered).

sources are in `src/vpncmd`

**Comment by MatAtBread** [comment]
Ok, thanks. I'm just setting up a new Linux box for this project (I like to keep projects in separate VMs).

TBH, it's 20 years since I did any C coding(!) I looked at the `src/vpncmd` dir, and it's not immediately obvious where it does the user IO - can you point me in the right direction?

**Comment by chipitsine** [comment]
we definetly wish to keep in touch, your web UI might be useful for many people

**Comment by MatAtBread** [comment]
Sure. It's just a toy at the moment, but it does work. Give me a few days and I'll give it a readme and a few tweaks, and you can install & run it

**Comment by chipitsine** [comment]
maybe it worth a note in https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/README.md ?
can you make a PR on that ?

**Comment by chipitsine** [comment]
also, this issue can be closed, I guess
