### ISSUE TITLE
Debian - Add Simple Packaging - dpkg-source: error: can't build with source format '3.0 (quilt)

### ISSUE THREAD

**Issue by ezgoen** [SoftEtherVPN/SoftEtherVPN#90]
Hi,

In Ubuntu Precise) (and others)  dpkg-buildpackage fails with 
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../softether-vpn_4.04.9412.orig.tar.{bz2,gz,lzma,xz}
(or similar)

The fix is 
in  SoftEtherVPN / debian / source / format 
change "quilt" to "native"

similar problems have been reported for other projects - for example https://code.google.com/p/pymds/issues/detail?id=1

I required I can fork and create pull request - but its such a small fix I thought it would be best posted here

**Comment by moatazelmasry2** [comment]
As I understood from the other thread, one need to remove the format file from the git repository. Is this correct?
