### ISSUE TITLE
Client API

### ISSUE THREAD

**Issue by M0n7y5** [SoftEtherVPN/SoftEtherVPN#901]
Hello,
is there a way to communicate with Client on Localhost? Like RPC API or something like that? I know about VPNCMD, but that's not what i need. I need .Net library for SE Client, but found only for SE Server API. Any ideas?

**Comment by hoppler** [comment]
For more details: Hes referring to the issue https://github.com/hoppler/SoftEtherApi/issues/5

**Comment by hoppler** [comment]
And like expected, the project is dead again (only build-script commits in the last months). Therefore @M0n7y5 maybe close the issue.

**Comment by chipitsine** [comment]
you are welcome to make pull request
