### ISSUE TITLE
Half-Open connection problem

### ISSUE THREAD

**Issue by hafedh-trimeche** [SoftEtherVPN/SoftEtherVPN#902]
One SEVPN server interface is attached to OPNsense firewall (VM) to reach the LAN network via SecureNAT.

Firewall: 
WAN IP : 192.168.0.250 connected to the router (Gateway 192.168.0.254)
LAN IP : 192.168.38.1

SEVPN
WAN IP: 192.168.0.3 connected to the router (Gateway 192.168.0.254)
LAN IP: 192.168.38.3
SecureNAT IP: 172.16.38.1
SecureNAT push: 192.168.38.0/255.255.255.0/172.16.38.1, 192.168.138.0/255.255.255.0/172.16.38.1, 192.168.0.0/255.255.255.0/172.16.38.1

When rebooting the firewall, the connection to firewall interfaces is lost and the VPN client still connected causing Half-Open (Dropped) Connections issue (SEVPN still consider it is connected to the firewall).

I solved this issue by using keep-alive functionality and assigning the firewall IP (192.168.0.250) to the host parameter.
![2019-04-16 08_39_20-Encryption and Network Settings](https://user-images.githubusercontent.com/988584/56191102-9adff080-6023-11e9-8c3e-aab6e0bd7bf2.png)

**Comment by domosekai** [comment]
Close as I assume no change is required.
