### ISSUE TITLE
fork rejected by pids controller

### ISSUE THREAD

**Issue by RonNabuurs** [SoftEtherVPN/SoftEtherVPN#903]
### Prerequisites

* [x] Can you reproduce?
* [ ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** 9666
**Component:** Server
**Operating system:** Linux - Ubuntu 18.04
**Architecture:** 64 bit

### Description

I've got a 'problem' with the SoftEtherVPN server when creating a lot of connection.

My test environment:
1 Ubuntu 18.04 host with SoftEtherVPN server
1 Ubuntu 18.04 host with Docker

I'm creating 400+ openvpn clients on the docker host within a docker container that are connecting to the SoftEtherVPN server.

The problem arises when I'm around the 250 connections. In /var/log/syslog I can find this:
`Apr 18 12:53:25 kernel: [ 1886.755045] cgroup: fork rejected by pids controller in /system.slice/softether.service` 

After I changed the unit file to include:
```bash
[Service]
TasksMax=8192
```
The problem is resolved.

Maybe the default unit file should be changed on the repo? Or at least this should be documented somewhere.

**Comment by chipitsine** [comment]
how did you install it ? launchpad or did you built packages by youselve ?

**Comment by ronneke1996** [comment]
I've build the package myself. And ran it with the unit file in place -> systemctl start softether.

**Comment by chipitsine** [comment]
I asked because launchpad packages are built in their very own way.

ok, so you suggest to 

a) change doc
b) increase limit

I'm not sure "b)" is good. Neither I'm sure it is bad. feel free to make a decision :) and you are welcome to make a PR

**Comment by ronneke1996** [comment]
Changing the docs seems like a good plan to me, just to create awareness and for other people encountering the same issue.

About increasing the limit. I'm not sure it's increasing the tasks in the unit file is closely related to the ulimit of the application, but I think it does. And the ulimit in the code base is set to the maximum 32/64bit integer. So I think it's fine to increase the limit(at least more than the default 512).

I'll make a PR to increase the limit to a reasonable size.

**Comment by chipitsine** [comment]
I asked colleagues to update docs. Do you have a suggestion where to update docs ?

also. I have a thought, we can investigate open files, I'm not sure we really need 16777216
did you have a look at /proc/.../fd/... ? any ideas how to reduce number of files ?

**Comment by ronneke1996** [comment]
The documentation maybe can be updated in the chapter [7.3.9 Starting and Stopping Service](https://www.softether.org/4-docs/1-manual/7._Installing_SoftEther_VPN_Server/7.3_Install_on_Linux_and_Initial_Configurations#7.3.9_Starting_and_Stopping_Service), there also isn't a part yet for the systemd unit file. Or maybe in the [11.1 Troubleshooting](https://www.softether.org/4-docs/1-manual/B._Troubleshooting_and_Supplemental/11.1_Troubleshooting).

About the open files. I have looked into that, but the MaxTasks in a unit file is not the openfiles. This is about threads. The maximum openfiles was correct and set to a high number in the SoftEther code base, but the MaxTasks default of ubuntu (and systemd overall I think) is 512. Therefore we couldn't create a lot of connections.

**Comment by domosekai** [comment]
Unfortunately 16777216 is too large.
The max pid is 32768 on 32-bit systems and 4194304 on 64-bit.
We had better set it to `infinity` which means unlimited for systemd.

> TasksMax=N
> Specify the maximum number of tasks that may be created in the unit. This ensures that the number of tasks accounted for the unit (see above) stays below a specific limit. This either takes an absolute number of tasks or a percentage value that is taken relative to the configured maximum number of tasks on the system. If assigned the special value "infinity", no tasks limit is applied. This controls the "pids.max" control group attribute. For details about this control group attribute, see [Process Number Controller](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/pids.html).
