### ISSUE TITLE
port-sharing and openvpn configuration

### ISSUE THREAD

**Issue by BedoM** [SoftEtherVPN/SoftEtherVPN#907]
Hello,

Can you add the "block-outside-dns" on the generated config for Openvpn ? and

Do you know if a port sharing project for cohabitation with a web server is in progress ? 

Than'ks !

**Comment by chipitsine** [comment]
I seen nice portsharing approach in https://github.com/StreisandEffect/streisand

**Comment by chipitsine** [comment]
as for "block-outside-dns" is not good idea

1) people might want to use SE VPN for corporate vpn solution. it is common not to block dns queries when connected to corporate vpn
2) "block-outside-dns" is supported starting openvpn-2.4.X, it is not supported for earlier versions

you are welcome to make pull request however (taking into account the above mentioned considerations)

**Comment by davidebeatrici** [comment]
Done in #1092.
