### ISSUE TITLE
how can we use this client to connect globalprotect vpn? 

### ISSUE THREAD

**Issue by ilovefood2** [SoftEtherVPN/SoftEtherVPN#908]
palo  alto (globalprotect) vpn is using ssl/tls protocol, how can we use client to connect it ?
i tried with client command, but seems i cannot make connection to server

im on OSX 10.14.4

**Comment by chipitsine** [comment]
globalprotect seem to be proprietary SSL vpn, not compatible with SE VPN

**Comment by chipitsine** [comment]
ask those guys are they compatible or not ?

**Comment by ikelca** [comment]
> globalprotect seem to be proprietary SSL vpn, not compatible with SE VPN

im sure it's proprietary, but they should accept third-party clients i think. for instance, OpenConnect v8 integrated globalprotect protocol

**Comment by chipitsine** [comment]
do they accept SE VPN clients as well ?

**Comment by ilovefood2** [comment]
Hmmm I’m not sure
