### ISSUE TITLE
L2TP/IPsec from IPv6 clients

### ISSUE THREAD

**Issue by dongjuanyong** [SoftEtherVPN/SoftEtherVPN#910]
---

### Prerequisites

* [ Y ] Can you reproduce?
* [ Y ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** 5.01.9670
**Component:** Server
**Operating system:** Linux(OpenWrt)
**Architecture:** X86_64

**Processor:** Intel(R) Pentium(R) CPU N3710

### Description

Sorry for my English. I compiled SoftEther VPN server 5.01.9670 from OpenWrt packages feed and installed it on my router. It runs OK, but when I tried to connect to my router through L2TP/IPsec from my office (I used IPv6 to connect), it failed to connect. I used to have a stable version of v4.29-9680-rtm before. With the same configuration (I tried exactly the same vpn_server.config file, and also from a fresh reconfiguration), L2TP/IPsec from IPv6 clients worked without any flaws. What I found was that "netstat -lnp" showed the 5.01.9670 versions listened to udp port 1701, 4500 and 500, but only IPv4 of them. The v4.29-9680-rtm listened to further more, including udp :::1701, :::4500 and :::500, raw protocol 50 and 52 for both IPv4 and IPv6. I think that may be the problem.

**Expected behavior:**
The server listens to udp 1701, 4500, 500 and raw protocol 50, 52 for both IPv4 and IPv6. Thus we can make L2TP/IPsec connections from IPv6 clients.

**Actual behavior:**
I can't connect L2TP/IPsec VPN from IPv6 clients.

### Steps to reproduce

1. Install 5.01.9670 version of server and run. Try to connect L2TP/IPsec VPN from IPv6 clients and use "netstat -lnp" to find out what ports is it listening to.
2. Install v4.29-9680-rtm version of server and run. Try to connect L2TP/IPsec VPN from IPv6 clients and use "netstat -lnp" to find out what ports is it listening to.

**Comment by chipitsine** [comment]
nice report, btw

**Comment by chipitsine** [comment]
@Andy2244 , can you have a look, please ?

**Comment by Andy2244** [comment]
mhh if your openwrt version was compiled with ipv6 (default) support, than ipv6 "should" work. 
I personally only use the softether protocol via ipv4, so have not personally tested the other permutations, so i rely on user feedback for those.

@chipitsine Is there a specific build option for ipv6, i should check, be aware of?

**Comment by domosekai** [comment]
This is very likely a client issue. Android and iOS native L2TP client does not support IPv6. 
Win 10 has no problem connecting to SoftEther server over L2TP and IPv6.
