### ISSUE TITLE
Issue with Version 5.01 9670 2019/05/09 - Open VPN Client "Invalid Password" Error

### ISSUE THREAD

**Issue by weidnerj1** [SoftEtherVPN/SoftEtherVPN#912]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [x] Can you reproduce? Yes
* [x] Are you running the latest version of SoftEtherVPN?  Yes

**SoftEther version:**
**Component:** [Server, Client, Bridge, etc.]  Server
**Operating system:** [Windows, Linux, BSD, macOS, etc.]  DD-WRT (Linux 4.4.179)
**Architecture:** [64 bit, 32 bit]  32 bit

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]  Qualcomm IPQ8065 | 1.7 GHz
-- | --

### Description

[Description of the bug]
Error using Open VPN client connecting to Soft-ether.
**Expected behavior:**
[What you expected to happen]
The ability to connect to Soft-ether using the function to clone Open VPN.
**Actual behavior:**
[What actually happened]
Get error, invalid password
### Steps to reproduce

1. [First step]
Install DD-WRT with Soft-ether Version 5.01 9670 2019/05/09
Connect with OpenVPN Client on Android Phone.
Get error "Invalid Password"

2.
Roll back to DD-WRT version of Soft-Ether Ver 4.28 9669 2018/09/11
Connect with OpenVPN Client on Android Phone (no change to Android Open VPN client)
Get connected and pass VPN traffic.

Note:  Can roll forward and backwards with DD-WRT and SoftEther and each time it works with the older version or stops working with the current version.  Using TCP port 443 as the Open VPN clone port.

**Comment by chipitsine** [comment]
"it works with the older version" - what is the latest "working" build ?

**Comment by weidnerj1** [comment]
4.28 9669 2018/09/11 is the last known working build.

**Comment by domosekai** [comment]
Close due to inactivity.
