### ISSUE TITLE
Option to verify certificates with host name

### ISSUE THREAD

**Issue by quantum5** [SoftEtherVPN/SoftEtherVPN#914]
**SoftEther version:** 5.01.9670
**Component:** All
**Operating system:** All
**Architecture:** All
**Processor:** Any

Currently, SoftEther verifies the server certificate only by identity (if an exact certificate is specified), or by issuer (from the list of trusted CAs) when certificate verification is turned on. This happens when SoftEther connects to a server, whether in client mode or bridge mode or server cascade mode.

This works well when you are running your own CA, but it has become increasing attractive to use SoftEther server with certificates issued by Let's Encrypt. This simplifies management and allows the Windows SSTP client to connect without any hassle. However, if you want to verify certificates, the server simply has to send over *any* Let's Encrypt-issued certificate to pass SoftEther's verification, assuming you configured the Let's Encrypt intermediate certificate as a trusted CA. Hard coding the exact certificate in the configuration is a pain when certificates renew every 2 months.

It would be nice if there is the option to verify if the server name matches the name in the certificate.

From a quick look at the code, this requires adding a configuration flag, and modifying `ClientCheckServerCert` in `Cedar/Protocol.c` to check the server name against the common name of the certificate when the flag is set.

But since modern certificates also use the Subject Alternate Name extension, this requires a list of SANs to be stored in `struct X` in `Mayaqua/Encrypt.h`. This list will have to be populated in `X509ToX`, and `ClientCheckServerCert` should also check the server name against the list of SANs.

**Comment by noaho** [comment]
Using letsencrypt with Softether (eg for SSTP compatibility) is also hard because softether doesn't support intermediate certificates chaining to a root. ( https://www.vpnusers.com/viewtopic.php?t=3555 )

This means in September 2021 there's likely to be a rash of complaints when letsencrypt's intermediate certificate expires, and users configurations are invalidated... That's if softether verifies SSL expiry, which I haven't tested. 

Why does softether try to do this all itself? Couldn't it use OpenSSL (or some other library..) for this purpose?

**Comment by quantum5** [comment]
Validating Let's Encrypt certificates by specifying the intermediate in SoftEther is inherently pointless because any Let's Encrypted issued certificate will pass that validation, hence the need for this issue. The only workaround is to make the client manually prompt you when the certificate changes so you can verify the fingerprint manually.

**Comment by noaho** [comment]
right... and yet one of the main reasons people deploy Softether is Windows's built in SSTP client, which requires using a valid CA for easy client-less setup. 

So either you deploy a server that needs a manual download of a CA for SSTP to work, and a 10 point instruction guide,  defeating the "just works" functionality of SSTP, or you deploy a server that *just works* for SSTP, but is insecure for softether client.

**Comment by domosekai** [comment]
The current way of doing server certificate validation is just replicating what the server is doing in client certificate validation.
On server side it's OK. But on client side (as noaho said) it's better delegate verification to OpenSSL. Just adding a hostname check is not enough.
