### ISSUE TITLE
[Suggestion] Adding a dependency package list

### ISSUE THREAD

**Issue by AngelFalse** [SoftEtherVPN/SoftEtherVPN#917]
Will that help newbies (like me) build software easier?
For example, these are the packages I installed during the build process on a Debian 9 OpenVZ VPS.

```
gcc
make
libreadline-dev
libssl-dev
zlib1g-dev
libncurses5-dev
```

**Comment by chipitsine** [comment]
there's a list already

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/BUILD_UNIX.md#install-requirements-on-debianubuntu

however, you have not find it. so feel free to suggest a better place of documentation

**Comment by AngelFalse** [comment]
Sorry for the bothering... Didn't read the README.md carefully before building, my fault.

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/README.md#build-from-source-code
