### ISSUE TITLE
Port forward for clients

### ISSUE THREAD

**Issue by ENTIREALL-COM** [SoftEtherVPN/SoftEtherVPN#918]
Hi, there!

Thank you for using SoftEther.

### Prerequisites

* [ Yes] Can you reproduce? Yes
* [ Yes ] Are you running the latest version of SoftEtherVPN? Yes
All operating systems
**Processor:** All

### Description

[Description of the bug]

Can you please add port forwarding both to Softether VPN server and Softether OpenVPN server config, so that when I connect to either I can port forward on my machine as on host, THANK YOU IF IN ADVANCE! please report forward my message to developers.

**Expected behavior:**
Opening ports / forwarding ports on client from softether OpenVPN and Softether default servers

**Actual behavior:**
Impossible to open ports on client side

### Steps to reproduce

1. Set whole Softether folder to read only
2. In NAT configuration of the hub enter your host default gateway to replicate on client 
3. Wait till you lose connection or do you just loose remote access connection.

**Comment by domosekai** [comment]
Close due to inactivity
