### ISSUE TITLE
Route table is not processed correctly

### ISSUE THREAD

**Issue by AngelFalse** [SoftEtherVPN/SoftEtherVPN#920]
### Prerequisites

* [Y] Can you reproduce? Yes.
* [?] Are you running the latest version of SoftEtherVPN? Running the latest Stable Release.

**SoftEther version:** Stable release v4.29 9680.
**Component:** Client
**Operating system:** Windows 10
**Architecture:** 64 bit

**Processor:** Intel Core i7-6500U

### Description

After connected to the VPN server, VPN client didn't process the system route table secure enough.

**Expected behavior:**
VPN Client processed the system route table so that all traffic (including DNS queries) go through the VPN interface, and none shall go through the physical interface, except VPN traffic.

**Actual behavior:**
VPN Client didn't remove the old def. gw. table entry from the route table.
It also added one entry for the DNS servers I set manually for the physical interface, and one entry for an IP located in AS37917. These two entries points to the physical network gateway(192.168.1.1).
As DNS queries is made in plain text, the original ISP may know what website I am visiting.
The system route table is shown below (irrelevant entries like vmware, wifi direct, Team viewer, teredo interfaces is removed):

> 接口列表
 50...00 ac 51 8c 91 ef ......VPN Client Adapter
 51...__ __ __ __ __ __ ......<Physical Interface>
  1...........................Software Loopback Interface 1
>
> IPv4 路由表
> ===========================================================================
> 活动路由:
网络目标        网络掩码          网关       接口   跃点数
          **0.0.0.0          0.0.0.0      192.168.1.1    192.168.1.193     41      <<<Old Def. gw. entry**
          0.0.0.0          0.0.0.0     192.168.30.1    192.168.30.11      2      <<<VPN Def. gw. entry
          **1.1.1.1  255.255.255.255      192.168.1.1    192.168.1.193     41    <<<DNS server (CloudFlare DNS), routed to physical interface**
   <VPN SERVER IP>  255.255.255.255      192.168.1.1    192.168.1.193     41
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
    **130.158.6.114  255.255.255.255      192.168.1.1    192.168.1.193     41    <<<an IP belonged to BGP AS37917 (maybe in charge of the VPN Gate function?), routed to physical interface**
      192.168.1.0    255.255.255.0            在链路上     192.168.1.193    296
    192.168.1.193  255.255.255.255            在链路上     192.168.1.193    296
    192.168.1.255  255.255.255.255            在链路上     192.168.1.193    296
     192.168.30.0    255.255.255.0            在链路上     192.168.30.11    257
    192.168.30.11  255.255.255.255            在链路上     192.168.30.11    257
   192.168.30.255  255.255.255.255            在链路上     192.168.30.11    257
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上     192.168.1.193    296
        224.0.0.0        240.0.0.0            在链路上     192.168.30.11    257
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上     192.168.1.193    296
  255.255.255.255  255.255.255.255            在链路上     192.168.30.11    257

Screenshot of Wireshark showing DNS queries going through physical interface, in plain text.
![image](https://user-images.githubusercontent.com/28922095/59265075-303fdf80-8c77-11e9-8b0d-4a93785a1d43.png)

During the whole process, "No adjustment of Routing Table" is not checked.

### Steps to reproduce

0. Install rtm9680 vpn client to the machine.
1. Set up DNS server for the physical interface.
2. Connect to a VPN server.
3. run `route print` in a command prompt.

### Current batch script I used to avoid this problem
After VPN is connected:
```
@echo off
echo Adding route table entry for VPN server...
route change *.*.*.* mask 255.255.255.255 192.168.1.1
echo Changing default gateway...
route change 0.0.0.0 mask 0.0.0.0 192.168.30.1
echo Changing DNS server route table entry (if existed)...
route change 1.1.1.1 mask 255.255.255.255 192.168.30.1
echo Changing SoftEther VPN Gate function entry...
REM This new route table entry overrides the original 130.158.*.* one because of its metric number.
route add 130.158.0.0 mask 255.255.0.0 192.168.30.1
pause
```
After disconnecting from VPN:
`route change 0.0.0.0 mask 0.0.0.0 192.168.1.1`

**Comment by domosekai** [comment]
If you setup manual DNS servers, SE will add routes for them to the current default gateway for not breaking things.
You can implement your own DNS anti-leakage strategy (see #520 ).
Route to 130.158.x.x is for DDNS feature. 
All expected behavior.
