### ISSUE TITLE
[feature request] Support for Multifactor Authentication (MFA / 2FA)

### ISSUE THREAD

**Issue by p4tpr0** [SoftEtherVPN/SoftEtherVPN#922]
Hello,

It would be really nice to have MFA/2FA support in SoftEther VPN, preferably with simple implementations like Yubikeys, GAuth, and the like. Not sure WebAuthn or U2F would work, but the simpler it gets the better it is.
If not possible in a foreseeable future, adding support for user+password+certificate would be great (as stated in issue #226).

Thanks

**Comment by arqteqnet** [comment]
Deploy freeradius and a 2fa service on the vpn server. As long as you have a backend user store you'll be able to use 2fa if sending passwords in clear text.

**Comment by domosekai** [comment]
You can use any MFA solution that supports Radius.
