### ISSUE TITLE
SoftEther VPN server RAM overload

### ISSUE THREAD

**Issue by pirpiliter** [SoftEtherVPN/SoftEtherVPN#923]
### Prerequisites

**Can you reproduce?**
yes
**Are you running the latest version of SoftEtherVPN?**
Yes

**SoftEther version:**
softether-vpnserver_4.27-9668 
softether-vpnserver_4.29-9680

**Component:**
Server

**Operating system:** 
Ubuntu 14.04 LTS
Ubuntu 16.04 LTS

**Architecture:**
64 bit

**Processor:** 
Intel(R) Xeon(R) CPU  X5675  @ 3.07GHz
Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
Intel(R) Xeon(R) CPU E31230 @ 3.20GHz
etc.

### Description
I have multiple softether vpnservers running on vps/dedicated servers on ubuntu 16.04 and 14.04. Authentification is with 2 radius servers, SecureNAT is disabled. Clients are connecting to openvpn and sstp servers. No special config is done to kernel. They all have the same config and they all have the same problem: RAM is filled nearly full after a couple of days after starting vpnserver and I have to restart it manually.

I have tested it on another machine with 3  or more clients connected, RAM goes to, let's say 1 GB, I disconnect all clients from the server. After all the clients are disconnected the amount of memory occupied by vpnserver it is also 1 GB.

**Expected behavior:**
Memory should free up as soon as users are disconnecting

**Actual behavior:**
Memory does not free up after users are disconnecting

### Steps to reproduce

1. Run softether vpnserver with attached config
2. Connect some clients to it, let them connect to OpenVPN and SSTP protocols  and use it for a couple days
3. The RAM will fill up and after all users will be disconnected the amount of occupied RAM will be the same.
![htop](https://user-images.githubusercontent.com/2566659/59665867-62dc6180-91bc-11e9-9980-6370db48063f.PNG)
[vpn_server.config(1).txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/3300526/vpn_server.config.1.txt)

**Comment by dnobori** [comment]
Please paste the result of
```
# ps auxf
```

**Comment by pirpiliter** [comment]
0 users connected at the moment
[psauxf.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/3300965/psauxf.txt)
![htop](https://user-images.githubusercontent.com/2566659/59672984-2f540400-91c9-11e9-8961-7143b5196b5e.PNG)

**Comment by dnobori** [comment]
How many VPN concurrent VPN sessions are connected on this VPN Server at the maximum moment?

**Comment by dnobori** [comment]
Please also paste the result of
```
ps auxH
```

**Comment by pirpiliter** [comment]
"How many VPN concurrent VPN sessions are connected on this VPN Server at the maximum moment?" around 13 users

[psauxH.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/3301076/psauxH.txt)

**Comment by dnobori** [comment]
Very interesting.

In normal systems (including Ubuntu Linux) the vpnserver process consumes only < 50MB RSS memory even when processing 10 ~ 30 VPN sessions. For example I am running the vpnserver in the production environment for 30 VPN sessions, but the RSS memory usage is only 47Mbytes as following.

```
root     19155  2.0 11.1 2224196 47364 ?       S<l  Feb28 3226:54  \_ /root/vpnserver/vpnserver/vpnserver execsvc
```

Your results of `ps auxH` seems normal except the size of RSS.

**Comment by arzinekfh4** [comment]
Same problem here. It is happening with the newest softether installation apparently.
Only rebooting vpnserver process  every X would mitigate this problem, with obvious disease for vpn clients (and customers).

How to solve ?

**Comment by pirpiliter** [comment]
Because of impossibility to stop "server_log", we set up attributes as immutable to server_log folder  (chattr -i server_log)
Because of this, the log was saved in RAM. After unsetting this parameter all unsaved log were copied to server_log directory and the RAM gradually was cleared. 
After removing the immutable parameter, no more RAM overload was observed.

**Comment by Gr8z** [comment]
@pirpiliter Could you specify how exactly you went to solving this memory issue? Where do I remove this parameter?

**Comment by pirpiliter** [comment]
> 
> 
> @pirpiliter Could you specify how exactly you went to solving this memory issue? Where do I remove this parameter?


Read again comment above + https://wiki.archlinux.org/index.php/File_permissions_and_attributes#File_attributes
