### ISSUE TITLE
Option to run vpnserver in foreground (for use with e.g. docker)

### ISSUE THREAD

**Issue by cnf** [SoftEtherVPN/SoftEtherVPN#93]
Please make it possible to have vpnserver NOT fork, and just run in foreground.

Docker is a container service that has one instance of a program running. If the program that was started (vpnserver start) exits, the docker instance exits, and a such the vpn server stops.

Keeping vpnserver in the foreground would make use in things like docker much more feasible. It would also make it easier to monitor with systems such as supervisord.

Thank you

**Comment by moatazelmasry2** [comment]
Nop. SoftEther write the logs by default to the logs folder. 

What if you start SoftEther WITHOUT execsvc
Then in the next line you run `cat -f <PATH TO LOG FILES>`

Would this solve your docker problem?
