### ISSUE TITLE
Lots of typo "descrption" in JSON-RPC scheme

### ISSUE THREAD

**Issue by metalefty** [SoftEtherVPN/SoftEtherVPN#938]
Hi,

I noticed #916 was merged with typo "descrption". I can see lots of such typo everywhere(see `git grep -i descrption`). However, the typo "descrption" is used in JSON key. Fixing typo will break backward API compatibility.

Fortunately, JSON-RPC API is implemented very recently. I think it is not too late to fix that typo. Fixing that ASAP will minimize the damage. When time passes without fixing it, it will be harder to fix like FirstConnectionEstabli**si**edTime.

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/50e39826e4395ab46ccef918430b3403662cace5/src/Cedar/Client.c#L4805-L4806

I would say that should be fixed immediately. What do you think?

**Comment by metalefty** [comment]
https://github.com/dnobori/SoftEtherVPN/tree/190528_jsonrpc_api/developer_tools/vpnserver-jsonrpc-clients#getcaps-rpc-api---get-list-of-server-functions--capability

The misspelled "descrption" can be found in the response "GetCaps" API.

```JSON
{
  "jsonrpc": "2.0",
  "id": "rpc_call_id",
  "result": {
    "CapsList": [
      {
        "CapsName_str": "capsname",
        "CapsValue_u32": 0,
        "CapsDescrption_utf": "capsdescrption"
      },
      {
        "CapsName_str": "capsname",
        "CapsValue_u32": 0,
        "CapsDescrption_utf": "capsdescrption"
      },
      {
        "CapsName_str": "capsname",
        "CapsValue_u32": 0,
        "CapsDescrption_utf": "capsdescrption"
      }
    ]
  }
}
```

**Comment by dnobori** [comment]
Thank you reporting it.

I fixed the JSON-RPC document's typo.

https://github.com/SoftEtherVPN/SoftEtherVPN/pull/939

In the JSON-RPC message I don't agree to change the property name because each of JSON-RPC message is derived from the original PACK RPC message structure. If we change a specific property name  of the JSON it will be difficult to keep the future integrity.

**Comment by metalefty** [comment]
Okay, to correct typo or not is up to you architect. It sounds like a `creat` systemcall.

If typos or misspellings are cannot be corrected to keep protocol/API consistency, new words should be checked carefully before merging. No more "FirstConnectionEstablisiedTime"s!
