### ISSUE TITLE
CR-LF in the codebase

### ISSUE THREAD

**Issue by neheb** [SoftEtherVPN/SoftEtherVPN#942]
Is there a good reason for using CRLF for the source? I ask since CRLF can cause issues with git.

**Comment by metalefty** [comment]
+1 to LF, I prefer LF.

**Comment by chipitsine** [comment]
I was sure .gitattributes keep us safe. Any example of how it could go wrong?

**Comment by neheb** [comment]
For OpenWrt, we have separate patch files that get applied to the main package.

Using git diff > .patch works with git config core.autocrlf true

When it comes time to commit to the repository though, core.autocrlf must be enabled as well. Otherwise git will change the line endings to LF. No amount of configure changes and git commit --amend will help after that.

**Comment by chipitsine** [comment]
that option does not help ?

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.gitattributes

btw, what are those patches ? can you provide a link ?

**Comment by chipitsine** [comment]
@neheb , do you mean https://github.com/neheb/packages/tree/master/net/softethervpn5 ?

**Comment by neheb** [comment]
No. https://github.com/neheb/packages/tree/soft5/net/softethervpn5/patches

Last two

**Comment by chipitsine** [comment]
so, I have several questions

1) the last two looks like they might be included in upstream, @davidebeatrici  ?
2) if you are talking about CR-LF, you mean only limited number of files ? do you mind to open a PR ?
3) we definetly will appreciate some help to setup openwrt build in our travis-ci matrix (or maybe openwrt uses some other kind of CI)

**Comment by neheb** [comment]
Well, I'm only asking why CRLF is used in the codebase at all. My guess is for Windows development. I would guess that with Windows 10, Visual Studio supports LF just fine, given that Notepad does.

Travis used to be used. But it had hard to debug build failures (was using an old Ubuntu LTS). OpenWrt uses CircleCI. The configuration file is in the root directory.

Since I got this to build, I noticed it does not compile with OpenSSL lacking deprecated APIs. I might whip up a patch to fix.

**Comment by Andy2244** [comment]
A year ago or so this issue was also noted by me and while the .gitattributes was changed, the conclusion was that "someone" would have to recommit the whole project with LF endings, which never happened.

So yes while you create diffs/patches, the result has mixed endings. This works fine unless some form of auto conversion happens either via texteditor or on commit. So you need to take extra care not to modify the patches.

**Comment by neheb** [comment]
I figured out that vi does not mess with the line endings. Everything else does.

**Comment by chipitsine** [comment]
if you feel better about line ending conversion, please provide such patch

**Comment by neheb** [comment]
Meh this is a minor point. It's only really relevant to the OpenWrt workflow where GNU patch and git differ. Closing.
