### ISSUE TITLE
DHCP server sends `DHCP_OFFER` with the same IP address to multiple clients

### ISSUE THREAD

**Issue by Alchiadus** [SoftEtherVPN/SoftEtherVPN#944]
### Prerequisites

* [X] Can you reproduce?
* [X] Are you running the latest version of SoftEtherVPN?

**SoftEther version: 831c9075126143755310ce1259274a9ff2fcffd0 (Latest Master branch as of Jul 12, 2019)**
**Component: Server**
**Operating system: Linux (VM)**
**Architecture: 64-bit**
**Processor: Intel® Core™ i7-8700B (Mac mini 2018)**

### Description

When many OpenVPN clients try to connect at roughly the same time, the DHCP server is unable to provide them all with an IP lease and only a few are able to successfully complete their initialisation sequence.

**Expected behavior:** All OpenVPN clients establish a successful connection and complete their initialisation sequence.

SoftEtherVPN DHCP server remembers which IP addresses it recently offered when deciding on an IP address for a `DHCP_OFFER`, so that different clients will get offers with different IP addresses.

**Actual behavior:** Only some OpenVPN clients establish a successful connection, most OpenVPN clients are unable to complete their initialisation sequence.

SoftEtherVPN DHCP server responds to `DHCP_DISCOVER` requests from different clients with `DHCP_OFFER` containing the same IP address when many clients connect at roughly the same time, resulting in a race condition where only the client sending the `DHCP_REQUEST` populated with the IP address suggested by the server's `DHCP_OFFER` that gets processed first will receive a `DHCP_ACK` (and thus a DHCP lease). The other clients will receive a `DHCP_NACK` because their requested IP address is already handed out to the client whose request happened to be processed first, and ultimately this results in an `AUTH_FAILED` being pushed to all OpenVPN clients who received an `DHCP_OFFER` with that same IP address.

Server log:
```
DHCP DHCP_OFFER : CA94C6120B0E given 10.187.10.1
DHCP DHCP_OFFER : CA21681C0EFB given 10.187.10.1
DHCP DHCP_OFFER : CAFF7F2A81BE given 10.187.10.1
DHCP DHCP_OFFER : CA056762A807 given 10.187.10.1
DHCP DHCP_ACK : CA056762A807 given 10.187.10.1
```

Client log (multiple OpenVPN processes writing to same file):
```
Fri Jul 12 06:33:44 2019 TUN/TAP device tun0 opened
Fri Jul 12 06:33:44 2019 /sbin/ip link set dev tun0 up mtu 1500
Fri Jul 12 06:33:44 2019 /sbin/ip addr add dev tun0 10.187.10.1/16 broadcast 10.187.255.255
Fri Jul 12 06:33:44 2019 Initialization Sequence Completed
Fri Jul 12 06:33:47 2019 AUTH: Received control message: AUTH_FAILED
Fri Jul 12 06:33:47 2019 SIGUSR1[soft,auth-failure] received, process restarting
Fri Jul 12 06:33:47 2019 AUTH: Received control message: AUTH_FAILED
Fri Jul 12 06:33:47 2019 SIGUSR1[soft,auth-failure] received, process restarting
Fri Jul 12 06:33:47 2019 AUTH: Received control message: AUTH_FAILED
Fri Jul 12 06:33:47 2019 SIGUSR1[soft,auth-failure] received, process restarting
```

### Steps to reproduce

1. Prepare the SoftEtherVPN server with at least one OpenVPN client configured (tun device, certificate authentication).
2. Let several OpenVPN processes connect to the server simultaneously. (`for i in $(seq 10); do openvpn config.ovpn & done`)
3. Observe how only a few clients get `Initialization Sequence Completed`, while most get `AUTH: Received control message: AUTH_FAILED`.

### Workaround

The workaround I use at the moment is to set `bool SecureNAT_RandomizeAssignIp true` in `vpn_server.config`. Assuming a DHCP range much larger than the amount of connected clients with an active DHCP lease, the likelihood of several `DHCP_OFFER` messages containing the same IP address becomes negligible when they are picked at random from the pool.

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue.

Could you confirm that #945 fixes it, please?

**Comment by Alchiadus** [comment]
Thank you for the quick response. I've (stress)tested #945 and can confirm it fixes the issue, all clients get an IP and successfully connect.

**Comment by davidebeatrici** [comment]
Excellent, thank you very much for testing!
