### ISSUE TITLE
Every single connection is shutdown in China.

### ISSUE THREAD

**Issue by forever8938** [SoftEtherVPN/SoftEtherVPN#948]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [*] Can you reproduce?
* [*] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
SoftEther VPN 4.0 (Ver 4.30, Build 9696)
**Component:** [Server, Client, Bridge, etc.]
Client
**Operating system:** [Windows, Linux, BSD, macOS, etc.]
Windows
**Architecture:** [64 bit, 32 bit]
32 bit

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]

### Description

[Description of the bug]
Every single connection is shutdown in China.

**Expected behavior:**
[What you expected to happen]
VPN connection established.

**Actual behavior:**
[What actually happened]
VPN connection shutdown immediately and the IP is blocked for a few minutes.

### Steps to reproduce

1. [First step]
launch vpngate client, update server list.
2. [Second step]
find a reachable IP and keep ping-ing it.
3. [And so on...]
connect to the IP using TCP. You can clearly see that ICMP timeout as soon as you connect to it. Of course the connection is failed, and the IP is blocked for quite a few minutes.

**Comment by forever8938** [comment]
Do you think SoftEther VPN connection can be distinguished from HTTPS connection, or Chinese Communist Party just block any connection to the IPs in the server list?

**Comment by chipitsine** [comment]
It is hard to tell. Can you investigate wireshark level traffic?

**Comment by forever8938** [comment]
I can see a RST in wireshark, and the IP is completely blocked for a while.

**Comment by chipitsine** [comment]
Who sends those RSTs?

**Comment by forever8938** [comment]
Sorry, I checked a few times again, there is no RST.

Anyway, this screenshot should be self-explanatory.
https://i.pinimg.com/originals/91/5a/2e/915a2e4b2544ac89ac8b0a09ee6199c6.png
https://i.pinimg.com/originals/c9/cf/fc/c9cffc8f68adac1e70478172c85999e6.png
https://i.pinimg.com/originals/41/d0/1e/41d01ee7382bc2ff624c8fc06472a95a.png

**Comment by chipitsine** [comment]
any other question left ?

**Comment by forever8938** [comment]
I'm not asking question. I'm just reporting the fact that vpngate doesn't in China at all.

**Comment by chipitsine** [comment]
If you know how to fix it, please submit PR

**Comment by jackforlit** [comment]
I met the same problem... Is there any update?

**Comment by chipitsine** [comment]
there are more than a billion people in China. if noone of them is able to resolve this issue, do not expect foreign people to resolve it
