### ISSUE TITLE
Add support for TAP driver on Windows

### ISSUE THREAD

**Issue by jdstroy** [SoftEtherVPN/SoftEtherVPN#95]
It would be great if the SoftEther VPN client could use the [signed TAP drivers](https://community.openvpn.net/openvpn/wiki/ManagingWindowsTAPDrivers#ExtractingTAP-driversfromOpenVPNinstallers) from OpenVPN in order to lower the trusted code base footprint.

(It would also be awesome if the code base for SE VPN's virtual adapter could be merged in to the TAP code -- Keep Link is the same as Media Status, and Indicate Speed (Mbps) does not exist.)

**Comment by moatazelmasry2** [comment]
As far as I understand, this project does not really depend on other external vpn libraries and include stuff directly into its own ecosystem, which is ok I guess.
