### ISSUE TITLE
Is SoftEtherVPN suitable deploy as SDWAN? Or How to reuse it to build SDWAN?

### ISSUE THREAD

**Issue by connLAN** [SoftEtherVPN/SoftEtherVPN#954]
All of us can see that SoftEtherVPN is still valuable and powerful in  many application scenario.  We can notice SDWAN becomes more and more hot. SoftEtherVPN  and SDWAN looks the same in many aspects, such as enterprise branch interconnection and cloud network collaboration.  So comes my question: Is seVPN  suitable to use as SDWAN,  or how to reuse it to build a SDWAN system?

**Comment by chipitsine** [comment]
generally, answer might be either "yes" or "no" depending on details.

yes, it is suitable to be used as SDWAN generally

no, it might not be suited in some particular questions
