### ISSUE TITLE
JSON-RPC API for Client?

### ISSUE THREAD

**Issue by M0n7y5** [SoftEtherVPN/SoftEtherVPN#958]
Hello,
Is possible implement JSON-RPC API to Client or SEVPNCLIENT service?

**Comment by he852100** [comment]
Vpncmd 。它更强大。

**Comment by M0n7y5** [comment]
Vpncmd sucks ... Its doesn't have JSON output ... Only CSV. Also i don't wanna make wrapper around executable. And i know i can contribute to this project, but i can't my c/c++ skills are usable only in industrial environment. 
Besides ... this project is dead anyway, so i am switching to Wireguard soon ...

**Comment by chipitsine** [comment]
@M0n7y5 , what do you mean by c/c++ skills in industrial environment ?

**Comment by M0n7y5** [comment]
@M0n7y5 I can program MCUs, PLC and other things like that ... usually usable in automation and robotics. But for Desktop, i am using mainly C#. And i am currently working on my custom VPN for gaming (Like Tunngle and Evolve) and Softether seems to be ideal solution for this. So i want to make a Client side app that can communicate with Softether service. But there is no proper way how to do it, other than make a C# wrapper for vpncmd executable. And that's a big nono. At least ... Add a option for JSON output for vpncmd.
