### ISSUE TITLE
非 SoftEther VPN 软件客户端已连接到该端口。

### ISSUE THREAD

**Issue by wagayaluda** [SoftEtherVPN/SoftEtherVPN#965]
How to allow JSON-RPC API(use project vpnserver-jsonrpc-client-csharp from developer_tools) to manage the SoftEther VPN Server?

> 2019-08-12 21:56:52.698 在 TCP 监听器(端口 443)上，客户端 (IP 地址 127.0.0.1，主机名 "Workstation"，端口号 31199) 的连接已建立。
> 2019-08-12 21:56:52.698 客户端 (IP 地址：127.0.0.1，主机名："Workstation"，端口号：31199) 的连接 "CID-2" 已建立。
> 2019-08-12 21:56:52.822 连接 "CID-2" 的 SSL 通信已启动。加密算法名为 "ECDHE-RSA-AES256-GCM-SHA384"。
> 2019-08-12 21:56:53.060 连接 "CID-2"因原因 "非 SoftEther VPN 软件客户端已连接到该端口。" (代码 5)已终止。
> 2019-08-12 21:56:53.060 连接 "CID-2" 已结束。
> 2019-08-12 21:56:53.060 与客户端 (IP 地址 127.0.0.1，端口号 31199) 的连接已断开。

**Comment by he852100** [comment]
JSON-RPC API 据说没有管理功能。

**Comment by scegg** [comment]
static char http_detect_server_startwith[] = "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\r\n<HTML><HEAD>\r\n<TITLE>403 Forbidden</TITLE>\r\n</HEAD><BODY>\r\n<H1>Forbidden</H1>\r\nYou don't have permission to access ";
static char http_detect_server_tag_future[] = "9C37197CA7C2428388C2E6E59B829B30";

**Comment by privateheart** [comment]
我的iphone遇到了这个问题，手动配置vpn,连接不上，服务器日志报 非 SoftEther VPN 软件客户端已连接到该端口。服务器就断开了
