### ISSUE TITLE
High load on SoftEther server

### ISSUE THREAD

**Issue by RonNabuurs** [SoftEtherVPN/SoftEtherVPN#969]
### Prerequisites

* [x] Can you reproduce?
* [ ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** Version 5.01 Build 9671
**Component:** Server
**Operating system:** Linux
**Architecture:** 64 bit

**Processor:** Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
**Cores:** 4
**Memory:** 8Gb

### Description

I've got an SoftEtherVPN server running on my VPS, with about 450 users connected (via OpenVPN config). I'm experiencing high load on the server. This load fluctuates between high and medium values (i've attached a screenshot of my monitor). 

Although the load is very high, the CPU usage seems fine, about 30/40% across all cores. Also memory usage is fine, about 2/3Gb of the total 8Gb.

After some digging around (and using netdata) I came netdev_budget, because time_squeeze value in `/proc/net/softnet_stat` kept increasing. I'm not sure if this has something to do with SoftEther, but the only network intensive process running on my server is SoftEther. 

I also got an OpenVPN server running and I compared the value of `/proc/net/softnet_stat` with the SoftEther one and saw that the OpenVPN server had way less  packets squeezed than the SoftEther server.

So my main question is, is it normal that I have such an high load on my server and is there something I can do (maybe in the configuration of SoftEther) to get the load values down?

And is it normal for a SoftEther server to send so many packets that alot of the get squeezed?

**Comment by dnobori** [comment]
In general, the load average value is lack of correctness.


It is recommended to check the the total sum of processing bandwidth. If the bandwidth suddenly decrease after the number of session exceeds 450, it is the scale-able problem. If not, there are no problem.

**Comment by ronneke1996** [comment]
When I use nethogs for monitoring the traffic. Is not very busy at all. Around 200 KB/sec sent and 200KB/sec received. So I dont think its and bandwidth problem.

But I'm still not sure if it's ok that alot of my packets get squeezed, is it ok?

**Comment by yx800** [comment]
> When I use nethogs for monitoring the traffic. Is not very busy at all. Around 200 KB/sec sent and 200KB/sec received. So I dont think its and bandwidth problem.
> 
> But I'm still not sure if it's ok that alot of my packets get squeezed, is it ok?

I have a similar problem. Have you solved it?
