### ISSUE TITLE
Build Fails with Visual Studio 2013

### ISSUE THREAD

**Issue by xaoseric** [SoftEtherVPN/SoftEtherVPN#97]
So, I modified the buildall.cmd to use Visual Studio 2013. It appears to be failing because the c++ directory can't be found. Is there any way to have it use .NET 4.5?

http://i.imgur.com/E9bIFjH.png

**Comment by moatazelmasry2** [comment]
The answer from @test-github123  does actually solve the problem.

Another solution is to use Eclipse C++ (I use it myself) and it works great. You will have to compile on the command line though.
