### ISSUE TITLE
[Feature Request] Radius Accounting

### ISSUE THREAD

**Issue by Omid-Shojaee** [SoftEtherVPN/SoftEtherVPN#971]
Hello,

I am ready to pay to developers to add Radius Accounting to SE.

Please contact me to discuss.

Thanks.
Omid

**Comment by whattheserver** [comment]
should reach out to or checkout this guys github
https://github.com/kosztyua/softether-radacct

**Comment by metalefty** [comment]
Dup of #101.

**Comment by chipitsine** [comment]
closing this in favour of #101 
thank you, @metalefty
