### ISSUE TITLE
What is the Initial Login & Password for the Web Administrator application?

### ISSUE THREAD

**Issue by bmullan** [SoftEtherVPN/SoftEtherVPN#974]
Hi, there!

Thank you for using SoftEther.

Before you submit an issue, please read the following:

Is this a question?
Yes, but I can't log into the users site either?

All I want to know is WHAT is the the initial Login ID and Password required to login to the new SoftEther Web Administrator console.

I've got everything installed okay and can connect to the Web  Console but have no idea what the initial Login ID  and Password are as they are not documented on the SoftEther website as far as I can find although I "think" the initial Login ID is "administrator" I do NOT know what the initial Password is???

Thanks for any help...

Brian

**Comment by Gr8z** [comment]
+1

**Comment by Gr8z** [comment]
Found this: 

user: administrator
pass: (your server manager pass)
