### ISSUE TITLE
listen on specific IPs

### ISSUE THREAD

**Issue by mjheidari** [SoftEtherVPN/SoftEtherVPN#976]
how to config to Softether to listen on one IP?

**Comment by SolSoCoG** [comment]
From what I've read here, it should be:

string ListenIP 127.0.0.1

for example, however on testing, this line just gets removed from config and that's about it, nothing changing.

I'd really be interested in using Softether, however I can't. It won't work running on the same machine as a webserver with a wildcard :443.

**Comment by davidebeatrici** [comment]
Closing in favor of #100.
