### ISSUE TITLE
Is it support muti-core ?

### ISSUE THREAD

**Issue by zyxs2018** [SoftEtherVPN/SoftEtherVPN#979]
Hi, there!

Thank you for using SoftEther.

* [ ] Can you reproduce?
* [ ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:
**Component:** [Server]
**Operating system:** [Linux]
**Architecture:** [64 bit]

      When I test vpnserver  on centos7 (3.10.0-862.el7.x86_64), I use top,vpnserver spend  at least %70 CPU,I press 1,it only use one cpu, ohter cpus are idle.  Is it not support multi-cpus?

And on a same  device, when cpu high load，it  cause  that maction reboot. and when vpnclient connected , the cpu  high load,it reboot again.

**Comment by domosekai** [comment]
Of course it does support multi-thread but not everything can be multi-threaded.
