### ISSUE TITLE
[Urgent] VpnGatePlugin(*.dll) source code is not publicly?

### ISSUE THREAD

**Issue by test-github123** [SoftEtherVPN/SoftEtherVPN#98]
Resource file: 
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/PenCore/PenCore.rc
Code file: 
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/VG.c

The above documents, I can't find the actual implementation code. Not publicly?

For example: the dialog(D_VGC_LIST) -> button(B_REFRESH) click event code in where? (See attachment)

Excuse me, I should how to modify the B_REFRESH button click event? Where to???

![qq 20140828142858](https://cloud.githubusercontent.com/assets/8524714/4072004/b212137c-2e7e-11e4-9053-a48bcb7c9a7a.jpg)
![qq 20140828145028](https://cloud.githubusercontent.com/assets/8524714/4072048/a5f4c8d6-2e7f-11e4-97de-f3440f9a8a6e.jpg)

**Comment by moatazelmasry2** [comment]
Nop. Looks like it is not part of the OpenSource Repository and is not being generated when compiling the code.
