### ISSUE TITLE
SSTP with ipv6 Router Advertise(RA)

### ISSUE THREAD

**Issue by badgv** [SoftEtherVPN/SoftEtherVPN#980]
Question 1:
My VPN server uses the bridge mode, bridges to the physical network card, the device can receive RA messages in the LAN, and use EUI64 to automatically configure the IPV6 address and gateway information.

When I connect with DEBIAN and Windows using vpnclient software, the virtual network port can correctly receive the RA and automatically configure the IPV6 address and gateway information of the interface.

However, when I use the built-in SSTP connection in WINDOWS, I cannot receive the RA message correctly, and the interface cannot automatically configure the IPV6 address.

Is my setting wrong? Or is it a bug in the software?

Question 2:
By the way, after windows is connected with sstp client, the speed can reach 100Mbps, but using vpnclient connection, the maximum can only run 20Mbps, is the setting wrong? Still BUG？

**Comment by Evengard** [comment]
The PPP IP stack is layer 3 while the SoftEther main stack is layer 2. PPP got the helper code transitioning from L3 to L2 to request DHCP and transfer data for IPv4, but it does not have any support for IPv6.
