### ISSUE TITLE
SecureNAT provides dhcp address to LAN

### ISSUE THREAD

**Issue by mmiat** [SoftEtherVPN/SoftEtherVPN#985]
I've this issue: #981 
for some reason, dhcp doesnt provide any more addresses to vpn clients, so I've enabled SecureNAT
but it provides dhcp addresses to my LAN too !!!
why?

**Comment by dnobori** [comment]
You need to disable Local Bridge before enabling SecureNAT. Otherwise, the virtual DHCP server of SecureNAT will be directly connected to the Ethernet segment of the Local-Bridged physical network.

**Comment by mmiat** [comment]
ok it works thanks
