### ISSUE TITLE
Sorting by line speed

### ISSUE THREAD

**Issue by hrastnik** [SoftEtherVPN/SoftEtherVPN#99]
There's a small issue when trying to sort the servers by line speed. The program parses the values under "Line Speed" as strings and sorts them alphabetically, so that for example "15" comes before "2" or "5". You should make it so that it parses the numbers as floats and sorts them in ascending or descending order.
![pn](https://cloud.githubusercontent.com/assets/3407234/4102226/d10c8f3e-311f-11e4-9198-a207835ae858.png)

**Comment by topherbuckley** [comment]
Could someone point me in the right direction as to where the sorting is performed in the code? I'd be happy to try to fix this, but don't want to spend the time understanding the entire code structure, etc.

**Comment by MtCedarNet** [comment]
// List-view sort function
int CALLBACK LvSortProc(LPARAM param1, LPARAM param2, LPARAM sort_param){

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/WinUi.c#L5350
